### ISSUE TITLE
Can't in any way make a Release version .exe from my bot

### ISSUE THREAD

**Issue by DamienVG99** [RogueException/Discord.Net#1032]
How do you even do this?

**Comment by Still34** [comment]
Hello, for .NET Core, you may need to specify a runtime ID upon build. For more information, please check out https://docs.microsoft.com/en-us/dotnet/core/rid-catalog

Also, for questions that aren't directly related to the library, please visit us at the Discord API guild instead.

**Comment by khionu** [comment]
For general C# help, it would be better suited for the C# Discord http://aka.ms/csharp-discord
