### ISSUE TITLE
 A MessageReceived handler is blocking the gateway task.

### ISSUE THREAD

**Issue by Marsgames** [RogueException/Discord.Net#1041]
Hey, 

I'm new to Discord api, so I tried something simple, took from youtube.

Here's my Program.cs : 
```C#
public class Program {

	DiscordSocketClient _client;
	CommandService _commands;
	IServiceProvider _services;

	static void Main() => new Program().RunBotAsync().GetAwaiter().GetResult();

	async Task RunBotAsync() {
		_client = new DiscordSocketClient();
		_commands = new CommandService();
		_services = new ServiceCollection()
			.AddSingleton(_client)
			.AddSingleton(_commands)
			.BuildServiceProvider();

		string botToken = "-------------------";

		_client.Log += Log;

		await RegisterCommandsAsync();
		await _client.LoginAsync(TokenType.Bot, botToken);
		await _client.StartAsync();

		await Task.Delay(-1);

	}

	Task Log(LogMessage arg) {
		Console.WriteLine(arg);

		return Task.CompletedTask;
	}

	async Task RegisterCommandsAsync() {
		_client.MessageReceived += HandleCommandAsync;
		await _commands.AddModulesAsync(Assembly.GetEntryAssembly());
	}

	async Task HandleCommandAsync(SocketMessage arg) {
		var message = arg as SocketUserMessage;

		if (message is null || message.Author.IsBot) return;

		int argPos = 0;

		if (message.HasCharPrefix('!', ref argPos) || message.HasMentionPrefix(_client.CurrentUser, ref argPos)) {
			var context = new SocketCommandContext(_client, message);
			var result = await _commands.ExecuteAsync(context, argPos, _services);

			if (!result.IsSuccess) {
				Console.WriteLine("Error01 : " + result.ErrorReason);
			}
		}
	}

}
```

And here's my Ping.cs : 
```C#
public class Ping : ModuleBase<SocketCommandContext> {

	[Command("ping")]
	public async Task PingAsync() {
		await ReplyAsync("pong");
	}

}
```

When I write "!ping" in the chat, my bot answer "pong", but if I do it another time, then I get an error : 

> A MessageReceived handler is blocking the gateway task.

and the bot crash.

I don't understand why I get this issue since my HandleCommandAsync() func uses await to execute code and my PingAsync() func too...

Do you have any idea ?

Thanks

**Comment by Still34** [comment]
Could you provide more information about the system this is being run on? What runtime version and such. Normally this blockage warning only occurs when the registered handler fails to return within 3 seconds, as explained [here](https://docs.stillu.cc/faq/commands/Commands.html?tabs=cmdconfig#i-have-a-long-running-task-in-my-command-and-discordnet-keeps-saying-that-a-messagereceived-handler-is-blocking-the-gateway-what-gives). This shouldn't happen for simple pong command unless there's something else wrong with the connection or runtime.

**Comment by Marsgames** [comment]
I'm running it on macOS.
I think all the informations are here

=== Visual Studio Community 2017 for Mac ===

Version 7.4.3 (build 10)
Installation UUID: 7f15ad41-f5d0-454b-a465-f7513aec9697
Runtime:
	Mono 5.8.1.0 (2017-10/6bf3922f3fd) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)

	Package version: 508010000

=== NuGet ===

Version: 4.3.1.4445

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.0.5
	2.0.0
	1.1.1
	1.0.4
SDK: /usr/local/share/dotnet/sdk/2.1.4/Sdks
SDK Versions:
	2.1.4
	2.0.0
	1.0.3
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.8.1/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

'/Applications/Xamarin Profiler.app' not found

=== Apple Developer Tools ===

Xcode 9.3 (14154)
Build 9E145

=== Xamarin.Mac ===

Version: 4.2.1.29 (Visual Studio Community)

=== Xamarin.iOS ===

Version: 11.9.1.24 (Visual Studio Community)
Hash: f62de472
Branch: xcode9.3
Build date: 2018-03-29 19:30:53-0400

=== Xamarin.Android ===

Version: 8.2.0.16 (Visual Studio Community)
Android SDK: /Users/Raph/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		6.0 (API level 23)
		7.1 (API level 25)
		8.0 (API level 26)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 27.0.1
SDK Build Tools Version: 27.0.0

Java SDK: /usr
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Xamarin Inspector ===

Version: 1.4.0
Hash: b3f92f9
Branch: master
Build date: Fri, 19 Jan 2018 22:00:34 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 704030010
Git revision: 5af3e98549653fcc5335896ccc296343d08f31bb
Build date: 2018-04-12 12:32:07-04
Xamarin addins: fadb82fb0fe2668cb7789f8b524aec6fb8568ee7
Build lane: monodevelop-lion-d15-6

=== Operating System ===

Mac OS X 10.13.5
Darwin 17.6.0 Darwin Kernel Version 17.6.0
    Fri Apr 13 19:57:44 PDT 2018
    root:xnu-4570.60.17.0.1~3/RELEASE_X86_64 x86_64

=== Enabled user installed addins ===

Internet of Things (IoT) development (Preview) 7.1

**Comment by Still34** [comment]
>Mono 5.8.1.0 (2017-10/6bf3922f3fd) (64-bit)

This library does not play well with Mono's WebSocket implementation. Switch over to .NET Core instead. Starting #988, we have added [a warning against the use of Mono](https://docs.stillu.cc/guides/getting_started/installing.html?tabs=dotnet-cli#supported-platforms) as the runtime.

**Comment by Marsgames** [comment]
Ok, it works perfectly with .net core. Thank you 😄
