### ISSUE TITLE
Allow redifinition of `RequestOptions.Default` so new defaults do not need to be added to every function

### ISSUE THREAD

**Issue by trigger-segfault** [RogueException/Discord.Net#1050]
I'm trying to combat rate-limiting by setting every Async function with a `RequestOptions` parameter to have `RetryMode.RetryRatelimit`. At the moment, it's really tedious to assign this to every single method so I was hoping a method to implement s new default `RequestOptions` could be implemented, such as a setter for `RequestOptions.Default`

**Comment by HelpfulStranger999** [comment]
For `RetryMode` you can actually use the property the config of all the various clients - rest, websocket, webhook - that specifies the default retry mode.

**Comment by trigger-segfault** [comment]
Thanks. That was exactly what I was looking for. :)
