### ISSUE TITLE
Error "System.InvalidOperationException: Cannot add commands to the root node"

### ISSUE THREAD

**Issue by ghost** [RogueException/Discord.Net#1058]
i have this code
`using System;
using System.Threading.Tasks;

using Discord.WebSocket;
using Discord.Commands;
using Microsoft.Extensions.DependencyInjection;
using System.Reflection;
using Discord;

namespace Discord_bots
{
    class Program
    {
        static void Main(string[] args)
        {
            Program prg = new Program();
            prg.RunBotAsynch()
                .GetAwaiter()
                .GetResult();
        }

        private DiscordSocketClient _client;
        private CommandService _commands;
        private IServiceProvider _services;

        #region tasks

        public async Task RunBotAsynch()
        {
            Console.WriteLine("starting!");

            _client = new DiscordSocketClient();
            _commands = new CommandService();

            _services = new ServiceCollection()
                .AddSingleton(_client)
                .AddSingleton(_commands)
                .BuildServiceProvider();

            string botToken = "bla...bla...bla...";

            //event substriction
            _client.Log += Log;

            await RegisterCommandsAsynch();

            await _client.LoginAsync(Discord.TokenType.Bot, botToken);

            await _client.StartAsync();

            await Task.Delay(-1);
        }

        private Task Log(LogMessage arg)
        {
            Console.WriteLine(arg);

            return Task.CompletedTask;
        }

        public async Task RegisterCommandsAsynch()
        {
            _client.MessageReceived += HandleCommandAsynch;

            await _commands.AddModulesAsync(Assembly.GetEntryAssembly());
        }

        private async Task HandleCommandAsynch(SocketMessage arg)
        {
            var messige = arg as SocketUserMessage;

            if (messige is null || messige.Author.IsBot)
            {
                return;
            }

            int argPos = 0;

            if (messige.HasStringPrefix("!m", ref argPos) || messige.HasMentionPrefix(_client.CurrentUser, ref argPos))
            {
                var context = new SocketCommandContext(_client, messige);

                var resoult = await _commands.ExecuteAsync(context, argPos, _services);

                if (!resoult.IsSuccess)
                {
                    Console.WriteLine(resoult.ErrorReason + " and error is " + resoult.Error);

                }
            }
        }

        #endregion
    }
}
`

and its saying at
 `            prg.RunBotAsynch()
                .GetAwaiter()
                .GetResult();
` this : System.InvalidOperationException: Cannot add commands to the root node.

anyone knows how to fix this?

**Comment by LDSpits** [comment]
@burgerlX **please reset your token IMMEDIATELY and remove your token from this example** you should treat your token as a password. Malicious users can use this to make your bot malicious & get you banned from discord

**Comment by ghost** [comment]
done (edited + reseted)

**Comment by ComputerMaster1st** [comment]
Hi There,

I've encountered this before. The issue is you have a command with no name attached.

`!help` = Valid Command.
`!hello <@mention>` = Valid Command with parameter.

`!` = Root & can not be used as a command.
`!<@mention>` = Root can not have parameters and will throw exceptions also.

**Comment by ghost** [comment]
oh thank you

**Comment by Joe4evr** [comment]
Please ask questions in our [Discord API channel](https://discord.gg/jkrBmQR) (#dotnet_discord-net) next time. The issue tracker is meant for genuine bugs, not PEBKACs.

And close the issue.

**Comment by ghost** [comment]
@ComputerMaster1st thank you that was the problem!
