### ISSUE TITLE
Bot is unable to connect on one PC but is fine on the other.

### ISSUE THREAD

**Issue by webmilio** [RogueException/Discord.Net#1062]
Hi there.

I have the same issue [as this man](https://github.com/RogueException/Discord.Net/issues/671) except that this issue only arises on my Windows 7 computer. I'm using NET Framework 4.5 so I shouldn't need WS4. I did, however, try it with and without the package.

The relevant code looks like this:
![image](https://user-images.githubusercontent.com/836345/40152651-212f8510-5954-11e8-90e7-9e791ca96469.png)

My console shows me this:
![image](https://user-images.githubusercontent.com/836345/40152709-473f6f54-5954-11e8-9eea-ae0ee2e7df59.png)

I have read through the existant issue and have tried their solutions, nothing works. The complexity of the bot doesn't seem to matter either.

**Comment by FiniteReality** [comment]
Are you hiding any log messages? I have a feeling an exception is being thrown which isn't being logged.

**Comment by webmilio** [comment]
I am not, no. I'm using my own logger but it doesn't filter anything.

**Comment by webmilio** [comment]
Seems like more is being said now.
![image](https://user-images.githubusercontent.com/836345/40272382-45479e56-5b7a-11e8-900d-fceb53a05e9e.png)

**Comment by webmilio** [comment]
I created a new project completely and it seems to work. Even my second bot, which I haven't touched, works now.
