### ISSUE TITLE
How do I get an IVoiceRegion?

### ISSUE THREAD

**Issue by Ben3345** [RogueException/Discord.Net#1063]
I've seen the method "CreateGuildAsync" and It requires an IVoiceRegion, but when I try to create one or get one, it doesn't work because it's null and a type. Can anyone help?

        [Command("create-newdiscord")]
        public async Task DoSo(bool GiveInvite = true)
        {
            IVoiceRegion region = null;
            if (GiveInvite)
            {
                var newguild = await Context.Client.CreateGuildAsync("Guildman", region);

                var channel = await newguild.GetChannelsAsync();

                var invite = await channel.FirstOrDefault().CreateInviteAsync();

                await ReplyAsync("Your Invite: " + invite.Url);
            }
            else
            {
                var newguild = await Context.Client.CreateGuildAsync("Guildman", region);

                var channel = await newguild.GetChannelsAsync();

                await ReplyAsync("DOONE");
            }
        }

**Comment by Adamv21** [comment]
Make a class that derrives from IVoiceRegion and it should contain a string that has to do with the region name. Assign that to the voice region name you want to use.

**Comment by AntiTcb** [comment]
You don't need to create a class that implements that interface, there's a collection of voice regions available on [DiscordSocketClient](https://github.com/RogueException/Discord.Net/blob/dev/src/Discord.Net.WebSocket/DiscordSocketClient.cs#L69).

**Comment by Adamv21** [comment]
Apparently that ^^

**Comment by Ben3345** [comment]
Thanks so much for the help, I have managed to successfully created a guild using my bot 😄
