### ISSUE TITLE
Is it possible to edit channel permissions?

### ISSUE THREAD

**Issue by Ben3345** [RogueException/Discord.Net#1065]
How would I do it, like make one role allowed to add reactions in a certain channel but not let the other roles do that and using a bot?  I tried ChannelPermissions but It doesn't work, says it can't convert to RequestOptions.
![image](https://user-images.githubusercontent.com/24615662/40263842-f699f580-5b4a-11e8-9c1e-60a53254b9cd.png)

**Comment by HelpfulStranger999** [comment]
Hi, you would need to add permission overwrites where you deny add reactions. However, these things are better handled in  our [Discord API channel](https://discord.gg/jkrBmQR) (#dotnet_discord-net).

**Comment by Ben3345** [comment]
Okay, i'll join.

**Comment by Ben3345** [comment]
I joined but when I try to send a message I get this "Your message could not be delivered because you don't share a server with the recipient or you disabled direct messages on your shared server, recipient is only accepting direct messages from friends, or you were blocked by the recipient."
