### ISSUE TITLE
Context.Channel.SendFileAsync Does Not Properly Load MemoryStream

### ISSUE THREAD

**Issue by JoshuaKlaser** [RogueException/Discord.Net#1077]
When you try to upload a file using a MemoryStream, it does not load the file properly. It results in a 0 byte file with the filename you have provided.

Uploading a FileStream works just fine, however I cannot get any implementation of a MemoryStream to work. This is for both bitmaps created in memory and passed into a MemoryStream and files loaded in via a FileStream that has been passed into a MemoryStream.

**Comment by Quahu** [comment]
Make sure to rewind the stream before sending it by, for example, setting its `Position` to 0.

**Comment by JoshuaKlaser** [comment]
Thankyou @Quahu. That solved the issue.
