### ISSUE TITLE
IDMChannel::SendMessageAsync hangs if user does not allow DMs from non-friends

### ISSUE THREAD

**Issue by Nihlus** [RogueException/Discord.Net#1082]
Instead of failing with an exception or other method of reporting error, IDMChannel::SendMessageAsync (and I would expect SendFileAsync as well) hangs indefinitely if the receiving user does not accept DMs from non-friends. I have not found any API to verify whether or not they are able to receive DMs from the bot in the current version of Discord.NET, and as such, any operations relying on user DMs are rather unpredictable.

The only workaround so far is to time out the task after a certain timespan, but that may cause false positives.

**Comment by NovusTheory** [comment]
I've personally never had issues with this and currently (in my live bot) just try/catch the SendMessageAsync and it seems to work fine 🤷‍♂️

**Comment by FiniteReality** [comment]
Do you have any code to reproduce this?

**Comment by Nihlus** [comment]
I'll put together a minimally reproducible example as soon as I can.

**Comment by Nihlus** [comment]
@FiniteReality Here's a minimal reproduction. Works fine for users accepting DMs from server members, hangs on sending the message if they don't.

https://gist.github.com/Nihlus/2c58de826b060d9ff3ecda82a5c9f96f

EDIT: In fact, here's the whole project zipped up.

[BugRepro.zip](https://github.com/RogueException/Discord.Net/files/2065174/BugRepro.zip)

**Comment by Nihlus** [comment]
After some closer inspection, the issue was that the exception didn't bubble up to the debugger so I could catch it during development. Adding a manual catch clause does catch the thrown exception properly.

Closing the issue.
