### ISSUE TITLE
CancellationTokenSource memory leak

### ISSUE THREAD

**Issue by Twistplay** [RogueException/Discord.Net#1084]
Discord.Net is not calling Dispose after using CancellationTokenSource.CreateLinkedTokenSource.    According to MSDN, this is necessary.  See remarks in:

[https://msdn.microsoft.com/en-us/library/system.threading.cancellationtokensource(v=vs.110).aspx](url)

This therefore creates a memory leak on each web call, which becomes quite significant over time.

See DefaultRestClient.SendInternalAsync for example.   It calls:

`cancelToken = CancellationTokenSource.CreateLinkedTokenSource(_cancelToken, cancelToken).Token;`

But provides no means for the caller to dispose of the CancellationTokenSource that is created.   Note that it is the source that needs to be disposed, not just the token itself.

**Comment by Auralytical** [comment]
Did a profiler show that this was actually memory leaking?

While I agree that disposing it would be the correct pattern, I'd be surprised if the GC wasn't cleaning up linked tokens.

**Comment by Twistplay** [comment]
It did come from the Visual Studio memory profiler, yes.   Taking memory snapshots from diagnostics periodically and using it's diff'ing capabilities clearly showed a continuous growth in the number of CancellationTokenSource objects and associated structures.   This was in proportion to the number of calls made to the API.

My understanding is that they do not get automatically GC'ed according to everything I've read online, hence the need to Dispose.
