### ISSUE TITLE
Sending message not delivered on linux

### ISSUE THREAD

**Issue by matek9292** [RogueException/Discord.Net#1086]
I make Discord bot in C# using Discord.NET.

When I run it on Windows it works good and all messages sent by bot was delivered.

But when I run the same program on Linux using mono command, only first sended message was delivered and other messages wasn't deliered. It's not connection lost problem, because all the time bot react to received messages.

**Comment by Joe4evr** [comment]
Discord.Net is not compatible with Mono. Use .NET Core instead.,

**Comment by matek9292** [comment]
Ok, now it works. Thanks.
