### ISSUE TITLE
StackOverflowException while running RenameChannelAsync

### ISSUE THREAD

**Issue by Muirey03** [RogueException/Discord.Net#1087]
When I run the line `await RenameChannelAsync(newName);`, I get this error: `Process is terminating due to StackOverflowException.` and my bot crashes.

**Comment by Joe4evr** [comment]
What is `RenameChannelAsync()`? Last I checked, we don't have a method like that in the library.

**Comment by Muirey03** [comment]
@Joe4evr Ah, that'll be the problem then. It must have been from a different library I am using. So how would I rename a channel then?

**Comment by Joe4evr** [comment]
https://docs.stillu.cc/api/Discord.IGuildChannel.html#Discord_IGuildChannel_ModifyAsync_System_Action_Discord_GuildChannelProperties__Discord_RequestOptions_

**Comment by Muirey03** [comment]
Got it, thanks.
