### ISSUE TITLE
Give role to user VB.NET

### ISSUE THREAD

**Issue by ghost** [RogueException/Discord.Net#1091]
Tried searching forums, but i dont find nothing that works.

For example, i tried this, but it doesn't work `Await DirectCast(message.Author, SocketGuildUser).AddRoleAsync("Testrole")`

**Comment by Yucked** [comment]
There is no such thing as `AddRoleAsync("SomeRole")`
It's either `AddRoleAsync(RoleId)` or `AddRoleAsync(IRole)`.

**Comment by ghost** [comment]
How do I use `AddRoleAsync(IRole)` ? @Yucked

**Comment by Still34** [comment]
You would need to fetch the role from somewhere first. Either by LINQing from the socket guild or by using the GetRole method. 

Also, for non-erroneous issues, please visit us on the DAPI server instead of opening an issue.

**Comment by ghost** [comment]
Sorry, didnt know that the DAPI server existed. But how do I use GetRole method?
Maybe I didn't explain what I mean with my question correctly, I want to give a person that puts a command, a role, but the bot will be used in 2 servers, so I can't get the id of the role, it should be by its name, and I also tested right now the GetRole method, but I think the syntax im using its incorrect

**Comment by ghost** [comment]
Found how to do it
