### ISSUE TITLE
Visual Studio 2017 hangs when displaying list of available Methods, Property's etc..

### ISSUE THREAD

**Issue by ghost** [RogueException/Discord.Net#1096]
Whenever i'm typing something and the list of available Methods & such show Visual Studio 2017 stops responding for 10 seconds then goes back to normal, this only happens when i'm using Discord.NET methods and none else, here's an example:

`embed.WithFooter()` <- this makes Visual Studio 2017 not respond

I'm using the 2.0.0 beta from Nuget.

**Comment by khionu** [comment]
This could be the fault of any number of factors, including hardware, or just VS being VS. This has absolutely nothing to do with the library in any way, shape, or form, even if it's only happening with Discord.Net.

Intellisense loads up what it needs to to understand the library, just as it would any other library, and Discord.Net doesn't have anything to do with how that process works.

**Comment by ghost** [comment]
Okay thanks, it posted it here incase it was an actual problem but i guess it's just VS being buggy like always :P
