### ISSUE TITLE
How can I tell if a received message is a DM?

### ISSUE THREAD

**Issue by JaneSmith** [RogueException/Discord.Net#1099]
I was using a much older version of this before, with DiscordClient. I'm now updating it, and following the documentation to use DiscordSocketClient. My problem is that I can't figure out how to check if a received message is a DM. I used to access the MessageEventArgs.Channel.IsPrivate property, but that no longer seems to exist on a SocketMessage. I find the documentation extremely lacking. What do I do?

**Comment by Yucked** [comment]
You will need to check if the channel is `IPrivateChannel` in your command handler.

**Comment by JaneSmith** [comment]
Thanks for the quick response! Sorry about that.
