### ISSUE TITLE
Can't look up a channel by its Id? Empty Channels collections?

### ISSUE THREAD

**Issue by ChrisTucker2000** [RogueException/Discord.Net#1100]
Hi guys. Thanks for taking the time to put this together. I'm having some problems though.

I've registered a bot. I've added it to my Discord bot. I can use Discord.Net to login and I see the bot appear online on the server. I can even @mention the bot and it will reply, using the `MessageReceived` event. That all works fine.

My problem is, I want the bot to also be able to post on its own, in a specific channel. I know the Id of that channel. I want to get a reference to it. But I don't seem to be able to do so.

At runtime, if I call `discordSocketClient.GetChannel(channelId)`, it returns null. If I call `discordSocketClient.GetGuild(guildId)`, I get back a `SocketGuild` object, but almost everything in it has default values - the Channels, Emotes, Features, Name, Owner, Roles, etc. properties are all null or empty. Of course, If I call `guild.GetChannel(channelId)`, it returns null again.

What could I be doing wrong?

**Comment by k-boyle** [comment]
Sounds like you're doing this before the client is ready. Hook into `discordSocketClient.Ready` and try it there

**Comment by ChrisTucker2000** [comment]
Thanks, that seemed to be it! A bit confusing though.

**Comment by Still34** [comment]
It is written in our getting started guide that one should not interact with the client until it is ready.

Also, for future non-erroneous issues, visit us on the Discord API chat. Close the issue if you think the issue has been resolved.

**Comment by ChrisTucker2000** [comment]
I did wait until ConnectionState was Connected, which I thought was enough. Thanks.
