### ISSUE TITLE
Async async 

### ISSUE THREAD

**Issue by netcrave** [RogueException/Discord.Net#1109]
Hi, I'm having trouble asyncing an async to async the login async:
```
 return (_client.LoginAsync(TokenType.Bot, SettingsManager.Instance.settings.BotLogin, true)
            .ContinueWith(new Action<Task>(async (result2) =>
            {
                if (result2.IsFaulted)
                    throw new Exception("useless login");
                await _client.StartAsync().ContinueWith(new Action<Task>(async (result3) =>
                {
                    if (result3.IsFaulted)
                        throw new Exception("useless startasync");
                }));
            })));
```
What token am I supposed to use? Why do they have all of these usernames on the discord create id / token page if none of them are used for anything?

**Comment by Emzi0767** [comment]
Use await

**Comment by netcrave** [comment]
there's a client id and a client secret, not using either of those, then theres a bot username and bot token (I'm only using the bot token because there's only a bot token field in the params for login

**Comment by Hawxy** [comment]
You should really stop whatever you're doing and follow the guide on creating a new bot, your questions are answered there:
https://docs.stillu.cc/guides/getting_started/first-bot.html

**Comment by netcrave** [comment]
Nah man its cool I figured it out already, only because I did what I did though. How come that 401 unauthorized / whatever exception it originated from is getting swallowed and not logged though? Based off the samples provided in the source, I would have expected that approach to throw an exception or make use of that logging event but it doesn't.

**Comment by netcrave** [comment]
Nah man its cool I figured it out already, only because I did what I did though. How come that 401 unauthorized / whatever exception it originated from is getting swallowed and not logged though? Based off the samples provided in the source, I would have expected that approach to throw an exception or make use of that logging event but it doesn't.

**Comment by netcrave** [comment]
but yeah sorry forgot to mention the problem was my SettingsManager class was picking up the wrong config, so it was trying to auth with an empty string

**Comment by netcrave** [comment]
but I promise you if you go and try it yourself with your own sample projects and try to auth with an empty string you'll find that it doesn't give you any useful info about why it's not working because you're swallowing that exception and not using the Log event to log the error.

**Comment by netcrave** [comment]
its working fine now
