### ISSUE TITLE
what is "Gateway     A GuildMemberUpdated handler is blocking the gateway task." message

### ISSUE THREAD

**Issue by msx752** [RogueException/Discord.Net#1119]
i dont know whether it is blocking my thread or not, can someone help me?, if it is blocking what should i do.

also when i modify the usernickname sometimes it is not modify the user's nickname/roles what is the reason of that issue

thank you

**Comment by ghost** [comment]
The event is taking too long. A fix for this is to wrap it in Task.Run()

As for ModifyAsync, make sure your bot is above them in Discord's hierarchy & has sufficient permissions. Also, keep in mind we have rate limits on pretty much everything.

**Comment by k-boyle** [comment]
For issues like these, it's better to join the Discord and ask in there https://discord.gg/discord-api
