### ISSUE TITLE
Unable to remove role from the user, after the bot was online for a few days.

### ISSUE THREAD

**Issue by RheaAyase** [RogueException/Discord.Net#112]
Steps to reproduce are simple:
1) Have a bot running for a few days.
2) Try to simply remove a role from a user.
3) Observe that the bot does everything without any errors or exceptions, thinking that it's done, but it did not remove the role from the user.
4) Restart the bot to fix the issue.

This was a problem since 0.91/92

**Comment by RogueException** [comment]
Are you running the latest 0.9.x? I fixed a lot of role-related bugs in 0.9.3.

**Comment by RheaAyase** [comment]
Unable to reproduce with the latest, as the bot just crashes (no exceptions, no logs) way too often to be able to test this... (It used to be stable for weeks before I updated.)

**Comment by khionu** [comment]
Without more information, we have nothing to go on. Even if you can't get a stack trace, logging at Debug level would be more helpful than nothing.

There's a few things that could cause crashes without exceptions, however the most likely one is a threading issue. Given no one else is complaining of this level of instability, I would suggest you review your code for anything that deviates from TAP, particularly look to see if you have any Tasks that aren't being awaited. If you have an exception being thrown in there that isn't caught, it would be fatal.

**Comment by RheaAyase** [comment]
This is not an issue about crashes, hence why I will not provide any info on it here.

**Comment by khionu** [comment]
Closing until there is further information to go off of.
