### ISSUE TITLE
Error handling for commands

### ISSUE THREAD

**Issue by DCBN** [RogueException/Discord.Net#1135]
Hey!

Can't seem to find anyway to handle errors at the command methods themselves. I suggest that in cases where a user run a command but don't add enough arguments or invalid data, a helpful string (such as a usage guide) would be better than a "BadArgCount: The input text has too few parameters.".  Would it be something you'd be interested in to add?

**Comment by k-boyle** [comment]
This is already something you could handle yourself... If you'd give this a quick read: [post execution handling](https://docs.stillu.cc/guides/commands/post-execution.html)

**Comment by DCBN** [comment]
Thank you for the quick response! Huh, haven't seen these docs before. Will definitely give a read! Sorry for the inconvenience!
