### ISSUE TITLE
[HELP]

### ISSUE THREAD

**Issue by ItZskyler** [RogueException/Discord.Net#1137]
[Command("serverinfo")]
		public async Task ServerInfo([Remainder]string message)
		{
			string player = Context.User.Username;
			var embed = new EmbedBuilder();
			embed.WithTitle("Server info");
			embed.WithAuthor(Context.User.Username);
			embed.WithDescription("Members: " + Context.Guild.Users);
			embed.WithDescription("Your acount was created at: " + Context.User.CreatedAt);
			embed.WithFooter($"{DateTime.Now}: Message was send to {player}");
		}

Unknown Dispatch (PRESENCES_REPLACE)
The input text has too few parameters.

is the error i am getting idk whats wrong?

**Comment by AntiTcb** [comment]
A: Use the text channel we have in the Discord API guild for general questions about the library, not GitHub issues.
B: That's a gateway event that normally doesn't get sent to bots. Sometimes it does, and a little warning message just gets logged when it does. Has nothing to do with your code, and nothing you need to concern yourself with.
C: You defined your command with a `message` parameter, so if you're calling `!serverinfo` without any content to fulfill that parameter, you're going to get that error message that you had too few parameters. Either remove the parameter from the method definition or start supplying parameters when calling the command.

**Comment by ItZskyler** [comment]
So i need to delete message and remainder?

**Comment by AntiTcb** [comment]
That is one of the options I gave you, yes.

**Comment by ItZskyler** [comment]
Ok, i will try if it does not work ill let you know

**Comment by ItZskyler** [comment]
I think i saw the problem i forgot to send the embed

**Comment by Anu6is** [comment]
You are also overwriting your description with your second description
And context.guild.users will only return cached users. Try context.guild.membercount

**Comment by ItZskyler** [comment]
ik thanks i saw that one did not work

**Comment by ItZskyler** [comment]
Still not working the Mebercount function

**Comment by ItZskyler** [comment]
Member*

**Comment by Anu6is** [comment]
By not working you mean? If you still have two descriptions defined it will only use the second.

**Comment by ItZskyler** [comment]
Thats what i tought... How to fix that?

**Comment by AntiTcb** [comment]
You can only have one description. Combine the two strings you're trying to have as separate descriptions into one. Pretty obvious solution.

**Comment by ItZskyler** [comment]
Oh yeah thx

**Comment by ItZskyler** [comment]
idk how to do that oof

**Comment by AntiTcb** [comment]
There are many resources out there to teach you how to concatenate strings. This is starting to get entirely off topic for this issue.

**Comment by ItZskyler** [comment]
Ok. Someone can close this now

**Comment by AntiTcb** [comment]
You can close the issue. If you're the author, you get a "close issue" button in the form to add a new comment.
![image](https://user-images.githubusercontent.com/4700391/44797463-4152b080-ab7d-11e8-9aa0-980f26b612ab.png)

**Comment by ItZskyler** [comment]
Oh ok cya thx for the help
