### ISSUE TITLE
Connection manager bug

### ISSUE THREAD

**Issue by xXBuilderBXx** [RogueException/Discord.Net#1138]
Hi im currently using .net framework for my bots and im getting a really weird bug with the connection manager i have spent the past hour trying to debug it with no luck and the only error im getting is https://i.imgur.com/8EeuCkr.png

Up untill now my bot has been working perfectly but it seems like Discord has changed something with the shard system causing these issues because i have been testing it with multiple versions including the latest and 0091 which is old.

**Comment by FiniteReality** [comment]
I don't think Discord wouldn't change things like sharding without warning us. What I think is happening is that your websocket is timing out in the connect phase.

**Comment by k-boyle** [comment]
The ConnectionManagar hasn't been touched in over a year. Try targetting .net core instead since that's where Microsoft have focussed their websocket improvements.

**Comment by xXBuilderBXx** [comment]
I just changed the ConnectionTimeout config from 30000 > 40000 and all my shards are connecting properly
