### ISSUE TITLE
System.NullReferenceException at AddOrUpdateUser(GuildMember model)

### ISSUE THREAD

**Issue by cjbonn** [RogueException/Discord.Net#1153]
Bot just gave off this message and stack trace makes this seem like an internal library issue. Not sure what caused it or even remotely know how it can be reproduced.

> 21:39:58 Gateway     Error handling Dispatch (MESSAGE_CREATE):
System.NullReferenceException: Object reference not set to an instance of an object.
   at Discord.WebSocket.SocketGuild.AddOrUpdateUser(GuildMember model)
   at Discord.WebSocket.DiscordSocketClient.<ProcessMessageAsync>d__107.MoveNext()

Posting here in case you can take a quick gander and pinpoint where it's stemming from. This has only occurred twice in the time that I've been using this version of Discord.Net, and both times happening within minutes of each other. I will be keeping an eye on it in the coming hours / days to see if it occurs again.

**Comment by Still34** [comment]
Is this from the latest nightly?

**Comment by cjbonn** [comment]
From the time of posting yes. Haven't seen the error since, so no clue what caused it.

**Comment by Still34** [comment]
This had previously been reported before, back when g250k impl was first introduced. We shrugged it off as it not being rolled out to all guilds yet - there might be other possibilities if it is still happening.

**Comment by cjbonn** [comment]
@foxbot Just got this again today:

> 03:44:09 Gateway     Error handling Dispatch (MESSAGE_CREATE):
System.NullReferenceException: Object reference not set to an instance of an object.
   at Discord.WebSocket.SocketGuild.AddOrUpdateUser(GuildMember model)
   at Discord.WebSocket.DiscordSocketClient.<ProcessMessageAsync>d__107.MoveNext()

Currently using: `Discord.Net v2.0.0-beta2-00999 (API v6)`

Was this fix implemented in this release ?
