### ISSUE TITLE
Discord.Net supports F#?

### ISSUE THREAD

**Issue by AwesomeObserver** [RogueException/Discord.Net#1154]

**Comment by TheNoodleMummy** [comment]
yes discord.net supports F# but do note the support is very litle as in 1 in 1000 (aka not alot of people can help)

**Comment by Emzi0767** [comment]
Discord.Net is compatible with all .NET-based languages, provided they're supported by frameworks which the library targets.

As F# is supported by both FX and Standard, you can use the library with F#.
