### ISSUE TITLE
How to make a bot react to its own message?

### ISSUE THREAD

**Issue by itsdyzoon** [RogueException/Discord.Net#1158]
The bot sends a message "Do u like or dislike smth" and reacts :thumb-up: and :thumb-down:, then calculates how many people voted for each option. How can I do it?
Btw, I don't completely understand how to add emoji reaction by text indificator (:thumb_up:).
Thanks for help :D

**Comment by Still34** [comment]
Each message sent via `SendMessageAsync` will return an `IUserMessage` for you to interact with and store in a variable. From there, use the stored message and call `AddReactionAsync` while passing in an `Emoji` of your choice, instantiated by passing in the desired Unicode in the class's ctor.

Read more about emojis over at our latest [Emoji guide](https://docs.stillu.cc/guides/emoji/emoji.html).
Furthermore, for trivial questions that are not directly related to lib's internal issues, please visit us over at [Discord API](https://discord.gg/discord-api) under #dotnet_discord-net.

**Comment by itsdyzoon** [comment]
Thanks for help :D
