### ISSUE TITLE
frozen discord client?

### ISSUE THREAD

**Issue by frostu8** [RogueException/Discord.Net#1179]
the client sometimes does this thing where it just disconnects and stays disconnected. This is kinda hurting my bot uptime, but I hope it isn't anything with mono.
`02:24:47 Gateway     System.Exception: WebSocket connection was closed ---> Discord.Net.WebSocketClosedException: The server sent close 1001: ""
  at Discord.Net.WebSockets.DefaultWebSocketClient.RunAsync (System.Threading.CancellationToken cancelToken) [0x000dd] in <ed3cc7469a404ac2add5b89a9be58fc2>:0
   --- End of inner exception stack trace ---
  at Discord.ConnectionManager+<>c__DisplayClass28_0.<StartAsync>b__0 () [0x0014b] in <ed3cc7469a404ac2add5b89a9be58fc2>:0
02:24:47 Gateway     Disconnecting`

**Comment by Still34** [comment]
Mono does not work with this lib. Use .NET Core instead.

**Comment by frostu8** [comment]
granted but this issue continues on windows too.

**Comment by frostu8** [comment]
after re initiating the project as a .net core project, it works perfectly fine and reconnects without issue. thanks to @Still34 for helping me out
