### ISSUE TITLE
Adding Multiple Reactions to Message is Slow

### ISSUE THREAD

**Issue by XtremeOwnageDotCom** [RogueException/Discord.Net#1184]
I have noticed when looping over a message to add or remove reactions,

Its extremely slow.

Even in a loop, where all references are already resolved, it seems to add or remove reactions at the rate of one per second. Is there some way to tune the rate limiter to... resolve this?

**Comment by sudo-gab** [comment]
Fixed in #1108

**Comment by Anu6is** [comment]
Update to the latest nightly build on https://www.myget.org/F/discord-net/api/v3/index.json for faster reaction adding. 
Also, in future, use the [dotnet_discord-net](https://discord.gg/discord-api) discussion channel for questions such as these.

**Comment by XtremeOwnageDotCom** [comment]
Issue resolved. Updated my local branch.
