### ISSUE TITLE
TokenType.User is not responding to commands

### ISSUE THREAD

**Issue by Xeevis** [RogueException/Discord.Net#119]
I'm trying to start selfbot on an user account
```
private DiscordSocketClient client;

static void Main(string[] args) => new Program().Run().GetAwaiter().GetResult();
        
public async Task Run()
{
    client = new DiscordSocketClient(new DiscordSocketConfig() { LogLevel = LogSeverity.Verbose });

    client.MessageReceived += async (message) =>
    {
        if (message.Text == "!ping")
        await message.Channel.SendMessageAsync("pong");
    };

    client.Log += async (message) => await Console.Out.WriteLineAsync($"[{message.Severity}] {message.Source} -> {message.Message}");


    await client.LoginAsync(TokenType.User, "xxxxxxxxxxxxxxxxxxxxxxxxxxxxx_xXxxxxxxxxxxxxxxxxxxxxxxxxxx");

    await client.ConnectAsync();

    Console.Read();
}
```
Even though log states no error and everything appears to be connected correctly, bot will not respond to !ping command. 

I've managed to get it `talking` by commenting out this single line which is probably **not a proper fix**
https://github.com/RogueException/Discord.Net/blob/dev/src/Discord.Net/DiscordSocketClient.cs#L534

**Comment by khionu** [comment]
https://i.lithi.io/TxVX.png My self bot, which is most definitely working. I would advise using breakpoints to track exactly what's going on.

I have noticed sometimes the bot doesn't respond right away, but that hasn't happened in a while. Try pulling a fresh instance

**Comment by RogueException** [comment]
Just checking, since this appears to be 1.0, are you also running client.ConnectAsync?

**Comment by Xeevis** [comment]
Edited OP with more code, it's just a basic code on latest `dev` branch. **TokenType.Bot** works well, **TokenType.User** with user token isn't working.

**Comment by RogueException** [comment]
I added extra logging in https://github.com/RogueException/Discord.Net/commit/d667420303fae121b087e6c8ade9f190c7bdb08d that will give me more of an idea of what's going on with the background tasks. Could you please post a new log with that info?

I tried reproducing with my own user token but can't seem to repro.

**Comment by Xeevis** [comment]
There you go
```
[Info] Client -> DiscordSocketClient v1.0.0 (Gateway v5, json)
[Verbose] Client -> Runtime: .NET Core 4.0.0.0 (x64)
[Verbose] Client -> OS: Microsoft Windows 10.0.10586 (x64)
[Verbose] Client -> Processors: 8
[Verbose] Rest -> GET auth/login: 408.01 ms
[Verbose] Rest -> GET voice/regions: 245.75 ms
[Info] Gateway -> Connecting
[Verbose] Rest -> GET gateway: 32.8 ms
[Debug] Gateway -> Sent Identify
[Debug] Gateway -> Received Hello
[Debug] Client -> Heartbeat Started
[Debug] Gateway -> Received Dispatch (READY)
[Debug] Client -> GuildDownloader Started
[Debug] Client -> GuildDownloader Stopped
[Debug] Gateway -> Sent GuildSync
[Info] Gateway -> Connected
[Debug] Gateway -> Sent Heartbeat
[Warning] Gateway -> Server missed last heartbeat
[Info] Gateway -> Disconnecting
[Debug] Gateway -> Disconnecting - CancelToken
[Debug] Gateway -> Disconnecting - ApiClient
```

**Comment by RogueException** [comment]
does it work if you change `_connectTask.TrySetResult(true);` to `Task.Run(() => _connectTask.TrySetResult(true));`?

**Comment by Xeevis** [comment]
Yes! This change does resolve the issue for me.

**Comment by RogueException** [comment]
Awesome :D.

Thanks for the help, I'll have a more complete fix pushed in half an hour or so.

**Comment by RogueException** [comment]
Pushed: https://github.com/RogueException/Discord.Net/commit/1aa908512fd997fda900f8309e53b61f507d2ef3
