### ISSUE TITLE
Shards randomly disconnecting.

### ISSUE THREAD

**Issue by BrammyS** [RogueException/Discord.Net#1193]
I'm randomly getting the error: `A MessageReceived handler is blocking the gateway task` and when that happens my shard were the error occurred disconnects without reconnecting.

The problem seems to occur with all the commands. But there is only a small change of it actually occurring. Most of the time the error happens when someone uses my **[Color =](https://github.com/BramEsendam/Color-Chan/blob/master/ColorChan/Discord/Commands/ColorCommands/UserCommands/SetColorCommand.cs)** command because that's the most used command.

I'm using Discord.net v2.0.0-beta. I switched to the beta because i was having the same issue with 1.0.2

**Comment by Still34** [comment]
Your commands are likely blocking the gateway thread. Considering using RunMode.Async. Read more in our FAQ in docs.

**Comment by BrammyS** [comment]
i am using [DefaultRunMode = RunMode.Async](https://github.com/BramEsendam/Color-Chan/blob/59dd99c7ea390c58b1345ebe0fcbe9560d9b5e1a/ColorChan/Discord/Handlers/CommandHandler.cs#L55)

**Comment by Still34** [comment]
What is your host environment (e.g. operating system, dotnet runtime version)?

**Comment by BrammyS** [comment]
Runtime: Win10-x64
dotnet runtime version: 2.1.4
Target framework: netcoreapp2.1
and im hosting it on a windows server

**Comment by BrammyS** [comment]
I added RunMode = RunMode.Async to all the commands.
But that wont change anything right? because i already had it as my default run mode in my commandServiceConfig

**Comment by svr333** [comment]
@BramEsendam https://github.com/discord-bot-tutorial/common-issues/blob/master/Issues/GatewayTaskBlocked.md
Fully explained over here
