### ISSUE TITLE
Discord Invitation link on page ran out.

### ISSUE THREAD

**Issue by mclucario** [RogueException/Discord.Net#122]
The discord help server invitation doesnt work anymore.

**Comment by khionu** [comment]
Thanks for noticing x33

**Comment by khionu** [comment]
Huh.... apparently it wasn't expired. You were banned for spamming. Either way, now the README has the Vanity Invite

**Comment by mclucario** [comment]
What? Why? I never spammed in there.

**Comment by mclucario** [comment]
I really wanna talk with that admin. I never spammed the chat.

**Comment by mclucario** [comment]
Im sorry but I never spammed the server. Could you please add me on discord so we can see what actually happened and discuss it? I really wanna see a screenshot of what I did wrong. My discord name is McLucario#1194
