### ISSUE TITLE
Cannot convert from System.Collections.Generic.IEnumerable<Discord.IMessage> to 'ulong'

### ISSUE THREAD

**Issue by Moonbase2004** [RogueException/Discord.Net#1228]
This error occurs in my Prune command. I don't know if this is a bug, or a coding error on my part, but this shouldn't be happening.

These lines used to work in V1.0.2:  
`var messages = await this.Context.Channel.GetMessagesAsync((int)amountToDelete + 1).FlattenAsync();`

`await this.Context.Channel.DeleteMessageAsync(messages);`

Now in V2.0.0, I am getting the error in `await this.Context.Channel.DeleteMessageAsync(messages);`

If this is a bug, please fix as soon as possible. If not, please explain to me what is going on.

**Comment by Joe4evr** [comment]
There are 2 methods: DeleteMessageAsync, and DeleteMessage**s**Async. Take a wild guess why one is singular and one is plural. :upside_down_face: 

Oh, but the plural one is only declared on `ITextChannel` now, because the bulk-delete endpoint doesn't work for private/DM channels.
