### ISSUE TITLE
Delete all messages

### ISSUE THREAD

**Issue by 0Lucifer0** [RogueException/Discord.Net#1232]
Hi, i'm trying to add a command to delete all messages but it seems like discord limit to two weeks old messages.
I'm thinking about doing this but i'm not sure it's even possible:
- clone the channel name
- move all the webhooks from old to new
- delete old channel.

Is this possible ? 
Does anyone have a better idea or some code example on how to do a nuke of a channel ?

**Comment by k-boyle** [comment]
The best way to wipe a channel clean is what you described, deleting it and recreating. For future reference, the GitHub issues are meant to be related to the development of the library. For receiving general help with the library it's best to join the Discord API guild and message the Discord.Net channel
