### ISSUE TITLE
Missing model properties

### ISSUE THREAD

**Issue by Still34** [RogueException/Discord.Net#1233]
As the *vague* title states, currently the lib has several missing properties.

Currently known properties that need updating
* `Activity` or `Game` - [details](https://discordapp.com/developers/docs/topics/gateway#activity-object)
  - This property provides details about the game; if it's a streaming status, this provides the name of the game. This has already been implemented in discord.py.
* `IUser` - [flags](https://discordapp.com/developers/docs/resources/user#user-object-user-flags) and [premium](https://discordapp.com/developers/docs/resources/user#user-object-premium-types)
  - The former property provides info about the user's flag details, which may include the status of HypeSquad ranking.
  - The latter property provides info about the user's Nitro status, a popular request on the official API as well as this lib.
  - This may require `identity` scope, not sure if this is delivered under normal circumstances.

There are probably more models that need updating, opening an issue to raise awareness of such problem.

**Comment by Chris-Johnston** [comment]
Is this still up for grabs? If so, I can work on it.

**Comment by Chris-Johnston** [comment]
https://github.com/RogueException/Discord.Net/blob/db50badcc4306b4cdbc49e29d15b9ffe1b8984dc/src/Discord.Net.Rest/API/Common/Game.cs#L17

Looks like the Game `Details` property already exists.
