### ISSUE TITLE
Exceptions don't seem to be logged

### ISSUE THREAD

**Issue by pie-flavor** [RogueException/Discord.Net#1238]
Code:
```csharp
client.Log += Log;
client.Ready += () => throw new Exception();
```
```csharp
public Task Log(LogMessage msg)
{
    Console.WriteLine(msg);
    return Task.CompletedTask;
}
```
Expected result: logging the error to stdout
Actual result: nothing at all.

**Comment by pie-flavor** [comment]
any sort of status?

**Comment by karpovichv** [comment]
> any sort of status?

I'm wondering the same thing. I was trying to figure out why my bot was ignoring some messages and it seems like there were thrown some exceptions but they were not logged.

**Comment by DannyKrendel** [comment]
Same thing happened to me today, client ignores all exceptions. This bug is critical (especially when you rely on exception logs) and should be fixed asap.
