### ISSUE TITLE
Question: `CommandService.ExecuteAsync ()` always return `ExecuteResult.FromSuccess()`

### ISSUE THREAD

**Issue by kamiyaowl** [RogueException/Discord.Net#1242]
Thank you for a wonderful library.

I am sorry for my difficult-to-read sentences, I may not be able to express well because I am not good at English.
I'm trying to implement error handling using the result of `IResult CommandService.ExecuteAsync ()`.
Concretely, I'm planning on implementing a class that inherits `IResult`.

`IResult CommandService.ExecuteAsync ()` returned the result of `IResult CommandInfo::ExecuteInternalAsync()`.
But why does not `CommandInfo::ExecuteInternalAsync()` return `result` if `_action` return type of `IResult`?

https://github.com/RogueException/Discord.Net/blob/dev/src/Discord.Net.Commands/Info/CommandInfo.cs#L238

# Original
```
        private async Task <IResult> ExecuteInternalAsync (ICommandContext context, object [] args, IServiceProvider services)
        {
            await Module.Service._ cmdLogger.DebugAsync ($ "Executing {GetLogText (context)}"). ConfigureAwait (false);
            try
            {
                var task = _action (context, args, services, this);
                if (task is Task <IResult> resultTask)
                {
                    var result = await resultTask.ConfigureAwait (false);
                    await Module.Service._commandExecutedEvent.InvokeAsync (this, context, result) .ConfigureAwait (false);
                    if (result is RuntimeResult execResult)
                        return execResult;
                }
...
```

# Code I'm expecting

```
        private async Task <IResult> ExecuteInternalAsync (ICommandContext context, object [] args, IServiceProvider services)
        {
            await Module.Service._ cmdLogger.DebugAsync ($ "Executing {GetLogText (context)}"). ConfigureAwait (false);
            try
            {
                var task = _action (context, args, services, this);
                if (task is Task <IResult> resultTask)
                {
                    var result = await resultTask.ConfigureAwait (false);
                    await Module.Service._commandExecutedEvent.InvokeAsync (this, context, result) .ConfigureAwait (false);
                    if (result is RuntimeResult execResult)
                        return execResult;
                    return result; // here
                }
...
```

**Comment by k-boyle** [comment]
If you read further down the method you'll see that there are multiple returns, each one is for a specific scenario, e.g. if there's an exception in the command it'll return a failed result [L287](https://github.com/RogueException/Discord.Net/blob/dev/src/Discord.Net.Commands/Info/CommandInfo.cs#L287). And you seem to be misunderstanding how the command result stuff is intended to be used. Commands that return a result to be used in the `CommandExecuted` event are meant to inherit `RuntimeResult`. You can read up more on post-execution handling in our [docs](https://docs.stillu.cc/guides/commands/post-execution.html)

**Comment by kamiyaowl** [comment]
Thank you for your polite explanation
I read the your content of the remarks and documentation, and my understanding of `IResult` was wrong.
We will use `RuntimeResult`. Thank you!
