### ISSUE TITLE
"You are trying to install this package into a project that targets 'native,Version=v0.0'" Issue

### ISSUE THREAD

**Issue by mohamedabdu17** [RogueException/Discord.Net#1245]
I've just installed Discord.Net successfully, but when I try to install Discord.Net.Commands. This error pops up. I'm very new to coding and Visual Studio. If someone could help me, it would be really appreciated.
![visualstudioerror](https://user-images.githubusercontent.com/44753072/51781713-9b36b280-20ea-11e9-8421-0ccc1e9723b1.PNG)

**Comment by Yucked** [comment]
If you installed Discord.NET then the commands package is included in it. You shouldn't have to install it again.

Also, use our DAPI channel for issues like these.

**Comment by mohamedabdu17** [comment]
Thanks

**Comment by brikirkpatrick** [comment]
> Thanks

If that fixed the issue do you mind closing it?
