### ISSUE TITLE
A way to tell if a child Channel's permissions are synced with its parent Category

### ISSUE THREAD

**Issue by filthfiend** [RogueException/Discord.Net#1254]
It would be very useful for me if it were possible to check whether a given channel currently has its permissions synced to a parent category! This way I could go through a given server's channels and selectively edit the permissions for channels that aren't already synced to their parent! 

If there is a way to do this already I'm sorry, I looked for a pretty long time but I miss a lot of things!

**Comment by Joe4evr** [comment]
Please use our support channel in the Discord API server for support questions.

**Comment by filthfiend** [comment]
I didn't really understand how permission syncing worked when I brought this up, this was dumb, sorry!
