### ISSUE TITLE
feature request: Setting presence on WebSocket identification 

### ISSUE THREAD

**Issue by Still34** [RogueException/Discord.Net#1258]
Per Discord spec of the [OpCode 2 Identify payload](https://discordapp.com/developers/docs/topics/gateway#identifying), user should have the ability to set a presence on login without having to make a separate call to the WebSocket after-the-fact. By supporting this feature, the user could set their application's user status and game status during login. 

It is worth nothing that other .NET libs such as D#+ and Disqord already have support (or are implementing) support for this feature.

**Comment by quinchs** [comment]
Looks like this was implemented in #1923 in the [DiscordSocketApiClient](https://github.com/discord-net/Discord.Net/blob/dev/src/Discord.Net.WebSocket/DiscordSocketApiClient.cs#L267)
