### ISSUE TITLE
Can`t get full list of user

### ISSUE THREAD

**Issue by takikunxo** [RogueException/Discord.Net#1264]
I  tried to get all user list of my guild (**400**members).
But,returned response has just **270** users.
This is sample of my source code.
How to get full user list of my guild ? Thany kou!

Discord.NET 2.0.1
.Net Frame Wordk 4.6.1
```
var client = new DiscordSocketClient();
var token = "secret"
await client.LoginAsync(TokenType.Bot, token);
await client.StartAsync();
//this returned users list has just  270 elements.
var users=client.Guilds.ToList()[0].Users.ToList();
```

**Comment by AntiTcb** [comment]
Guild information isn't completed in its retrieval and processing until the Ready event is fired. Put all your logic in an event handler for that.

**Comment by FiniteReality** [comment]
`SocketGuild.Users` returns a list of cached users. You need to download the users to get the full user set.

In addition, you should likely not be using ToList, as the data returned is in a format which can be used the same anyway.

**Comment by Joe4evr** [comment]
Set [`AlwaysDownloadUsers = true` in your client config](https://docs.stillu.cc/api/Discord.WebSocket.DiscordSocketConfig.html#Discord_WebSocket_DiscordSocketConfig_AlwaysDownloadUsers).

**Comment by takikunxo** [comment]
I could get all user finally !
Thank you, everone for kind advice.
I'll keep studying, and work hard.

**Comment by thienson30** [comment]
> I tried to get all user list of my guild (**400**members).
> But,returned response has just **270** users.
> This is sample of my source code.
> How to get full user list of my guild ? Thany kou!
> 
> Discord.NET 2.0.1
> .Net Frame Wordk 4.6.1
> 
> ```
> var client = new DiscordSocketClient();
> var token = "secret"
> await client.LoginAsync(TokenType.Bot, token);
> await client.StartAsync();
> //this returned users list has just  270 elements.
> var users=client.Guilds.ToList()[0].Users.ToList();
> 

You said that you found a solution to get a list of users ... Could You please post a solution for us to see ?

**Comment by basi1ik** [comment]
How to get all users of the server?

**Comment by maseurodrigo** [comment]
> How to get all users of the server?

Like @Joe4evr said:
`new DiscordSocketClient(new DiscordSocketConfig() { AlwaysDownloadUsers = true });`

Then, in your command event, you just need to retrieve a list of guild users, using a foreach loop for example:
`SocketGuildUser serverUser in Context.Guild.Users`

You can have another approach using `.DownloadUsersAsync()`, but here you have to specify the guild(s) that you want to download the users from.

**Comment by maseurodrigo** [comment]
> How to get all users of the server?

Like @Joe4evr said:
`new DiscordSocketClient(new DiscordSocketConfig() { AlwaysDownloadUsers = true });`

Then, in your command event, you just need to retrieve a list of guild users, using a foreach loop for example:
`SocketGuildUser serverUser in Context.Guild.Users`

You can have another approach using `.DownloadUsersAsync()`, but here you have to specify the guild(s) that you want to get the users from.

**Comment by maseurodrigo** [comment]
> How to get all users of the server?

Like @Joe4evr said:
`new DiscordSocketClient(new DiscordSocketConfig() { AlwaysDownloadUsers = true });`

And like @FiniteReality said, in your command event, you just need to retrieve a list of guild users, using a foreach loop for example:
`SocketGuildUser serverUser in Context.Guild.Users`

You can have another approach using `.DownloadUsersAsync()`, but here you have to specify the guild(s) that you want to get the users from.

But for all of this guild users stuff works properly, remember to enable the **SERVER MEMBERS INTENT** in bot your configurations.
