### ISSUE TITLE
Documentation in Documentation link is outdated

### ISSUE THREAD

**Issue by PlasmaEye** [RogueException/Discord.Net#1265]
The documentation referenced in the README (https://discord.foxbot.me/docs/index.html) points to outdated documentation and does not follow the documentation in the /docs/ folder.

For example, the documentation on installation looks like this through the foxbot documentation:
![image](https://user-images.githubusercontent.com/3521652/52903565-e1140180-31e4-11e9-901e-194d78c92ad5.png)

The docs folder has this as the sample for installing Discord.Net:
https://github.com/discord-net/Discord.Net/blob/dev/docs/guides/getting_started/samples/project.xml

**Comment by Still34** [comment]
Unofficially, the latest nightly docs is currently hosted at docs.stillu.cc. The documentation link in README.md is run by our current main maintainer, @foxbot, who has yet to update his branch of documentation. In the future we will likely change the documentation host strategy to gh-page under discord-net/docs, but for now, please visit the nightly docs for up-to-date docs.
