### ISSUE TITLE
401 Unauthorized

### ISSUE THREAD

**Issue by RexTheCapt** [RogueException/Discord.Net#1272]
I have been searching on google on why i can't get it to work. I have checked other issues here (#891 #585 #282 #92) but none of them helped me. I have tried the prefix solution but didn't work. Yes this is an example code i got from this repo.

```
#region usings

using System;
using System.Threading.Tasks;
using Discord;
using Discord.WebSocket;

#endregion

namespace DiscordNetCore
{
    internal class Program
    {
        private readonly DiscordSocketClient _client;

        public Program()
        {
            // It is recommended to Dispose of a client when you are finished
            // using it, at the end of your app's lifetime.
            _client = new DiscordSocketClient();

            _client.Log += LogAsync;
            _client.Ready += ReadyAsync;
            _client.MessageReceived += MessageReceivedAsync;
        }

        private string Token => $"{BotUser.Default.Token}";

        // Discord.Net heavily utilizes TAP for async, so we create
        // an asynchronous context from the beginning.
        private static void Main()
        {
            new Program().MainAsync().GetAwaiter().GetResult();
        }

        public async Task MainAsync()
        {
            // Tokens should be considered secret data, and never hard-coded.
            await _client.LoginAsync(TokenType.Bot, Environment.GetEnvironmentVariable(Token), false);
            await _client.StartAsync();

            // Block the program until it is closed.
            await Task.Delay(-1);
        }

        private Task LogAsync(LogMessage log)
        {
            Console.WriteLine(log.ToString());
            return Task.CompletedTask;
        }

        // The Ready event indicates that the client has opened a
        // connection and it is now safe to access the cache.
        private Task ReadyAsync()
        {
            Console.WriteLine($"{_client.CurrentUser} is connected!");

            return Task.CompletedTask;
        }

        // This is not the recommended way to write a bot - consider
        // reading over the Commands Framework sample.
        private async Task MessageReceivedAsync(SocketMessage message)
        {
            // The bot should never respond to itself.
            if (message.Author.Id == _client.CurrentUser.Id)
                return;

            if (message.Content == "!ping")
                await message.Channel.SendMessageAsync("pong!");
        }
    }
}
```

**Comment by Anu6is** [comment]
Your token is invalid or you aren't using the environment variable correctly 
Also, you should probably join the [Discord Server](https://discord.gg/discord-api) for questions like these. Use the **dotnet_discord-net** channel

**Comment by RexTheCapt** [comment]
> 
> 
> Your token is invalid or you aren't using the environment variable correctly

Just used an if statement to test it. It was true.

```
            if (Token == "Token"){
                Console.WriteLine("Token match");
            }
```

**Comment by MarkusGordathian** [comment]
That means your `Token` variable holds a value of "Token," literally. Your token to authenticate to Discord will never be "Token," so that's your issue.

**Comment by AntiTcb** [comment]
Sure, that may be true, but look at the code above.  You're passing `Environment.GetEnvironmentVariable(Token)` as your token, which isn't the same thing as the condition you tested above. The example there is for if you're storing your bot token in your system's environment variables, but since you have it hard coded to the `Token` variable, you should just be passing that instead.

**Comment by RexTheCapt** [comment]
Still the exact same error.

`await _client.LoginAsync(TokenType.Bot, Environment.GetEnvironmentVariable("Token"), false);`

**Comment by AntiTcb** [comment]
Do you understand what `Environment.GetEnvironmentVariable()` is doing?

**Comment by Anu6is** [comment]
Get rid of `Environment.GetEnvironmentVariable()` unless you actually set an environment variable

**Comment by RexTheCapt** [comment]
No i actually do not. I read the reply too quickly and kinda missed that. I removed it and it worked.
