### ISSUE TITLE
Discord.Net.HttpException when Sending Message with Embed

### ISSUE THREAD

**Issue by AtzederSerbe** [RogueException/Discord.Net#1279]
This gives me a Discord.Net.HttpException:
`        public async Task EmbedCommand([Remainder]string input = null)
        {
            EmbedBuilder embed = new EmbedBuilder();
            embed.WithAuthor("TestAuthor", Context.User.GetAvatarUrl());
            embed.WithColor(Color.Green);
            embed.WithFooter("This is a test embed", Context.Guild.Owner.GetAvatarUrl());
            embed.WithDescription("This is a test description");
            if (input != null)
            {
                embed.AddField("User Input:", input);
            }
            await Context.Channel.SendMessageAsync("",false,embed.Build());
        }`
while this runs fine:
`await Context.Channel.SendMessageAsync("Hello World");`

**Comment by Still34** [comment]
Chances are it's a 400 Bad Request, which means your embed is malformed. Double check your field values and other elements of the embed.

**Comment by AtzederSerbe** [comment]
I tried the same with an empty embed and it still does not work. I'm on .Net Core 2.1. Code I tried:
`        [Command("embed"), Summary("embed test command")]
        public async Task EmbedCommand([Remainder]string input = null)
        {
            EmbedBuilder embed = new EmbedBuilder();
            await Context.Channel.SendMessageAsync("", false, embed.Build());
        }`

**Comment by Joe4evr** [comment]
Well yes, Discord rejects empty embeds.

**Comment by AtzederSerbe** [comment]
I just realized that my error handling was wrong and I did not get the exception, that the bot has missing permissions. Sorry
