### ISSUE TITLE
CreateRoleAsync doesn't update internal cache

### ISSUE THREAD

**Issue by woutervs** [RogueException/Discord.Net#1281]
I have a bot, that has an option to verify assign roles to users in a for loop, that method can create roles if the roles shouldn't exist on that server.
Now if User A is assigned role X then that role gets created, but then when user B get's assigned role X in that loop the role gets recreated because this "client.GetGuild(guildUser.Guild.Id).Roles.FirstOrDefault(x => x.Name == roleName)" fails since the Roles property collection doesn't seem updated after the first create.
Hence we get two roles with an identical name but a different id.

Any workarounds or solutions?

**Comment by Anu6is** [comment]
CreateRoleAsync returns a RestRole. You have to store that role object if you intend to use it immediately after creation. It takes a little while for the websocket to send the update and the for cache to be updated. Fetching the Roles collection from the guild will not contain the new role as you've experienced. Your loop would have to then check against cached roles and newly created roles that aren't yet in cache.

**Comment by woutervs** [comment]
Okay, it complicates matters for me a bit.
Thanks for the info.
