### ISSUE TITLE
Scoped Services acts as Singletons.

### ISSUE THREAD

**Issue by igorquintaes** [RogueException/Discord.Net#1286]
Initially, I think that when we register a class as Scoped on `ServiceCollection` should be created a new object every message request received who attends a module class - and intuitively, I assumed that each message request has its own scope. 

But every message uses the same class registered as scoped, and there is not a clear of objects managed from each message request. It is like a singleton instance.

I don't think this behavior is expected since I was not found any reference on documentation about it works this way, and also because a transient object looks to works as expected.

If I 'vent been clear about the subject, I am sorry. Later, I can create an example project to try to explain what we can intuitively expect of a scoped object and how it is managed nowadays on Discord.Net and to know if it is an issue or not.

**Comment by Joe4evr** [comment]
Discord.Net will not create scopes for you, you are responsible for creating the scope in your command handler yourself.
```cs
using (var scope = _services.CreateScope())
{
    await _commands.ExecuteAsync(message, argpos, scope.ServiceProvider);
}
```

**Comment by igorquintaes** [comment]
Thanks, it fits my needs. And sorry for the useless Github issue, I had not understood how Discord.Net works internally.
