### ISSUE TITLE
UWP Support?

### ISSUE THREAD

**Issue by OceanOSdev** [RogueException/Discord.Net#129]
Is supporting UWP apps a possibility?  I've been trying to put together a simple client for my phone but I noticed that this doesn't support UWP.

**Comment by Mushroom** [comment]
https://1drv.ms/f/s!An8Fz_Axudl5pPxSV9pbM9tIGsl4nw

Yes it does. App coming soon™

**Comment by RogueException** [comment]
Yeah, both 0.9 and 1.0 support .Net Standard 1.3, which is compatible with UWP.

The main issue is that Visual Studio's tooling right now doesn't allow reference an xproj from a normal csproj. You can get around this by `dotnet pack`-ing Discord.Net and adding the output folder as a NuGet package source (see NuGet settings).

Or you can wait until Microsoft releases a clear way for me to upgrade an xproj back to csproj sometime soon (hopefully).

**Comment by Mushroom** [comment]
This will be fixed in the next iteration of Visual Studio ("15"), which will automatically do this - it will convert xproj files to csproj files.

https://blogs.msdn.microsoft.com/dotnet/2016/05/23/changes-to-project-json/

Right now the easiest option by far is to simply pack the project as a nuget package locally, and import it into your app like that.

**Comment by RogueException** [comment]
Oh I missed that blog post, good find. I'll make an issue to track it

**Comment by Mushroom** [comment]
Can this issue be considered solved then? Seeing as it does work with UWPs

**Comment by ar-inerdtia** [comment]
Hey @Mushroom I am running Visual Studio 2015 Update 3 and ran into this problem of not being able to add Discord.Net to my UWP project. I tried with the VS 15 Preview 3 but it does not support UWP projects at the moment. How did you do this? Via the packaging as a NuGet trick? --- sorry for posting here, I couldn't figure out how to message you via GitHub.

**Comment by Mushroom** [comment]
Yes, via packaging as a local nuget package
