### ISSUE TITLE
MissingMethodException - GetUsersAsync - Windows Form Application

### ISSUE THREAD

**Issue by RiisDev** [RogueException/Discord.Net#1296]
I saw another guy have the same issue regarding making a bot on a Windows C# Form, on the code 

` DiscordSocketClient _client = new DiscordSocketClient();` I receive the following error

 `An unhandled exception of type 'System.MissingMethodException' occurred in Discord.Net.WebSocket.dll
Method not found: 'System.Collections.Generic.IAsyncEnumerable`1<System.Collections.Generic.IReadOnlyCollection`1<Discord.IUser>> Discord.IChannel.GetUsersAsync(Discord.CacheMode, Discord.RequestOptions)'.
`

Here are the project files.
https://mega.nz/#!7MNnTYga!nMk8jO_kgVdZHP9yU9ymm2YlSk-dl_6m2iAqcUAbNFE

Sorry if I did something wrong first time posting an issue.

EDIT: Managed to fix the issue by installing discord.net from nuget but then not updating dependencies, no idea why this fixed it and you devs should probably look into it!

**Comment by FiniteReality** [comment]
Make sure your library versions are the same - it appears the version that you're building against isn't the same as the version you're running against.

A quick way to check this would be to delete the `bin` and `obj` folders in your project, and ensure your NuGet packages are up-to-date. Then build your project again.

**Comment by RiisDev** [comment]
> 
> 
> Make sure your library versions are the same - it appears the version that you're building against isn't the same as the version you're running against.
> 
> A quick way to check this would be to delete the `bin` and `obj` folders in your project, and ensure your NuGet packages are up-to-date. Then build your project again.

Did what you said but still getting the error.

**Comment by RiisDev** [comment]
@FiniteReality Sorry for @ just really need this helped/fixed
