### ISSUE TITLE
Channel Order Not Preserved

### ISSUE THREAD

**Issue by CodeSteele** [RogueException/Discord.Net#1306]
Currently adding an announcement for when the bot joins.

We're using `Client.JoinedGuild` to hook into the event when the bot joins, and `SocketGuild.Channels` (from the event argument) to get all channels. Ideally: we try to send to the first, if that fails (due to lack of permissions) we'll try to next.

_During testing_ this seemed to grab the first channel, sweet, usually this is the announcements/welcome channel and that works _doubly_ well. We slip this out and try it again -- now it grabbed a random voice channel, after some filtering it's now grabbing a different text channel, now here is the catch:

- When it kept grabbing a voice channel, it failed, a ton (we don't support announcing into voice), we only have one voice channel.
- When we skip voice channels, it keeps choosing the _same_ text channel, it's pretty far down on our list though (our channel list is flat, no groups).

So it appears to be deterministic, but I have no clue how it's deciding what channel is "first".

Is there a way to sort them in client-order?

Bots are currently installed as full admins, so it's not like these are the only channels they have access to, also issuing commands in other channels (eg: the one I expect them to announce in) they'll respond in that channel to me just fine.

**Comment by FiniteReality** [comment]
I believe the Channels property does not sort the channels, as they IIRC are not given to us in order from Discord. You could use `Channels.OrderBy(x => x.Position)` to get the channels in (roughly) the same order the client sees them, but I forget how categories interact with that property.

**Comment by CodeSteele** [comment]
@FiniteReality I have no clue how I missed that, I poked at the class thinking there may be something like that... oops.

Thanks! That should do it, I'll go try it now.

**Comment by CodeSteele** [comment]
Yep, my bad. Sorry about that!

**Comment by Joe4evr** [comment]
By the way, you can also prevent grabbing voice channels in the first place by using the `TextChannels` property instead of just `Channels`.
