### ISSUE TITLE
Service provider is inaccessible due to its protection level (when trying to host)

### ISSUE THREAD

**Issue by nikolap3** [RogueException/Discord.Net#1307]
So after changing my methods from the deal with commands in messagereceivedasync to Commands with depency injections; i decided to host my discord bot again. After setting it up identicly to the old versions, i clicked build. After a few minutes i was told "Service Provide is inaccessible due to its protection level", which was strange since minutes before i ran it on my pc without such an issue. After research i found out the problem was the constructor being sealed.
How would i fix this?
The hosting service I use (heroku) has linux servers,if that might help.

**Comment by Cisien** [comment]
Without seeing your code, this sounds like a compile error you're receiving. This means that the protection levels (public, private, not set) don't match

**Comment by nikolap3** [comment]
I dont think its related to a compiler error, since i can run the bot in my local environment without a problem. The problem is only showing up while trying to start it online.

**Comment by JohnRamberger** [comment]
When you update certain libraries in the Nuget manager it fixes this, but too many updates and I get the error:
[10/26/2019 10:43:01 AM at Discord.Net.WebSocket] Method not found: 'System.Collections.Generic.IAsyncEnumerable1<System.Collections.Generic.IReadOnlyCollection1<Discord.IUser>> Discord.IChannel.GetUsersAsync(Discord.CacheMode, Discord.RequestOptions)'.

**Comment by JohnRamberger** [comment]
it works when you add/update to the latest version of discord.addons.passiveinteracrtive
