### ISSUE TITLE
Modifying Embeds in VB.Net not working?

### ISSUE THREAD

**Issue by Nekonika** [RogueException/Discord.Net#1322]
I keep getting an error when I try to edit an Embed using the following Code:

```
Dim Msg = Await Context.Channel.SendMessageAsync(embed:=Functions.GetEmbed("Is a Test-Embed"))
Context.Message.ModifyAsync(Function(x) x.Embed() = Functions.GetEmbed("This is a modified Embed!"))
```
Note that Function.GetEmbed returns a builded Embed containing the given Text.

But it just doesn't seem to work, no matter what I try:
![image](https://user-images.githubusercontent.com/51423438/58992048-fe97c600-87e9-11e9-96fa-178940c5fbc3.png)

Is this an Issue based on the API or did I miss something?

**Comment by Anu6is** [comment]
Use `Sub(x)` instead of `Function(x)`
```vb
Context.Message.ModifyAsync(Sub(x) x.Embed = Functions.GetEmbed("This is a modified Embed!"))
```

**Comment by Nekonika** [comment]
Thank you so much for that quick response. I'll have a look at it tomorrow after work.

**Comment by Nekonika** [comment]
I just testet the code as you said and everything is working fine.
Thank you once again ^^

Final Code:
```
Dim Msg = Await Context.Channel.SendMessageAsync(embed:=Functions.GetEmbed("Is a Test-Embed"))
Await Msg.ModifyAsync(Sub(x) x.Embed = Functions.GetEmbed("This is a modified Embed!"))
```
