### ISSUE TITLE
Missing properties for Nitro Server Boosting

### ISSUE THREAD

**Issue by Hellession** [RogueException/Discord.Net#1325]
At the beginning of June Server Boosting was introduced.
I assume that most likely the Server Boosting related values are missing in Guild, GuildUser and other related types in Discord.NET Stable 2.1.1.
I failed to find anything related to Server Boosting in SocketGuild, IGuild and SocketGuildUser objects.
Here are examples of the new values added to guilds and users as they are documented in the Developer Portal of Discord...
*premium_tier* and *premium_subscription_count* in [Guild Object](https://discordapp.com/developers/docs/resources/guild)
*premium_since* in [Guild Member Object](https://discordapp.com/developers/docs/resources/guild#guild-member-object)

**Comment by Anu6is** [comment]
[PR 1319](https://github.com/discord-net/Discord.Net/pull/1319) already exists for including these.

**Comment by Hellession** [comment]
Oops. My bad. Sorry.
