### ISSUE TITLE
Color.ToString returns wrong value

### ISSUE THREAD

**Issue by Jyrka98** [RogueException/Discord.Net#1327]
For example `new Discord.Color(0x0080ff).ToString()` returns `#80ff`, which results in this color: https://www.color-hex.com/color/8800ff

**Comment by PassiveModding** [comment]
this is a result of Convert.ToString() returning the minimal string value to represent a number.
ie. the padding zeros at the start are ignored.
this can be mitigated by doing the following:
```
var colourString = new Discord.Color(0x0088ff).toString();
colourString = colourString.Replace("#", "");
colourString = colourString.PadLeft(6, '0');
```
