### ISSUE TITLE
Restarts cause Discord.Net to hang

### ISSUE THREAD

**Issue by hbjydev** [RogueException/Discord.Net#1332]
For some reason, when I debug/run a bot, it goes through fine. But then when I restart that debug/run session, it hangs at either `<time here> Discord.Net <version here>` or `<time here> Connecting`.

**Comment by RheaAyase** [comment]
Duplicate of #960 ?

**Comment by SubZero0** [comment]
I'll be closing this since a lot of changes were made since it was created.
If you have any issue like this one, I recommend updating to the latest nightly and if not resolved, create a new issue or check #960
