### ISSUE TITLE
Getting Mentioned user from message

### ISSUE THREAD

**Issue by mgonulkirmaz** [RogueException/Discord.Net#1338]
I am struggling with an issue about getting mentioned user. I saw on videos there is a func called FirstOrDefault but its not available for me. I tried to get it different ways and i ended up making overloads for my commands. But it takes like 4 functions with different args so makes messy look. I wonder if there is another way to get mentioned user from message.

**Comment by Joe4evr** [comment]
> I am struggling with an issue about getting mentioned user.

If this is a command, you can just take an `IUser` (or `SocketUser`) as a parameter to your command method and Discord.Net does everything for you to get the object that represents the mentioned user.
> I saw on videos there is a func called FirstOrDefault but its not available for me.

Protip: In cases like this, you can hit Ctrl+. to see if VS can offer you a fix (in this case you haven't imported the appropriate namespace for the method to be available).

**Comment by mgonulkirmaz** [comment]
Oh looks like i am an idiot. Didnt realized its a function from another lib. Thank you for your answer.
