### ISSUE TITLE
Problems with sending embed. 

### ISSUE THREAD

**Issue by xxCherry** [RogueException/Discord.Net#1342]
Discord.NET 2.1.1
Code: 
![изображение](https://user-images.githubusercontent.com/42537021/60755625-f5716300-9ffa-11e9-84c1-f8cda70186a5.png)
![изображение](https://user-images.githubusercontent.com/42537021/60755631-fb674400-9ffa-11e9-85f6-84defb670215.png)
Response:
![Image](https://user-images.githubusercontent.com/42537021/60755612-d1ae1d00-9ffa-11e9-96b4-60dad8ab47b6.png)

**Comment by LtLi0n** [comment]
Why are you using static SocketMessage? That makes no sense.
Just reply through Context

**Comment by xxCherry** [comment]
how? for me Context is not defined

**Comment by LtLi0n** [comment]
Did you even look at the documentation specifying Discord.Net usage?
You are doing something horribly wrong, follow the guidelines.

https://discord.foxbot.me/docs/guides/commands/intro.html
Here's an in depth guide

Should also close this issue

**Comment by xxCherry** [comment]
i using Discord.Commands but ModuleBase not exist for me 
![Image](https://user-images.githubusercontent.com/42537021/60755991-6e26ee00-a000-11e9-9c02-3880d5c5a241.png)

**Comment by LtLi0n** [comment]
I don't think you are ready to use a library, especially as complex as Discord.net. You need to cover c# fundamentals first
