### ISSUE TITLE
Unhandled exception, need help

### ISSUE THREAD

**Issue by panthernet** [RogueException/Discord.Net#1345]
Here's the log text: https://paste.ubuntu.com/p/xXX8SQZwDB/

The problem is I'm getting it from time to time on a .NET Core app and catching it as an unhandled ex means that there's already no way to recover app at this point. I'm pretty sure I've covered all Discord interactions in a try/catch blocks but still getting this. 

So I wanted to know:
1. Is this a Discord .NET library issue?
2. Can I catch it and process on my side? And if so where I can look for it to happen? Logs shows some internal calls and processing :|

**Comment by k-boyle** [comment]
It's a cloudflare issue. Nothing you can do about it, nothing the lib can do either. The library _should_ attempt to reconnect though. Which is a separate issue.

**Comment by panthernet** [comment]
I know it is a cloudflare, but shouldn't the pipe connection exception be handled somewhere in the library? I get it as unhandled and it ruins the app workflow.
