### ISSUE TITLE
ReadFrameAsync() Unknown Opcode (12)

### ISSUE THREAD

**Issue by thesn10** [RogueException/Discord.Net#1347]
If i call AudioInStream.ReadFrameAsync(), nothing happens and the log shows the following:
```
22:47:00 Discord     Discord.Net v2.1.1 (API v6)
22:47:01 Gateway     Connecting
22:47:01 Gateway     Connected
22:47:02 Gateway     Ready
22:47:07 Audio #1    Connecting
22:47:07 Audio #1    Unknown OpCode (Hello)
22:47:07 Audio #1    Connected
ReadFrameAsync
22:47:09 Audio #1    Unknown OpCode (12)
```
The code i used:

    [Command("join", RunMode = RunMode.Async)]
    public async Task JoinAsync()
    {
        var channel = discord.GetChannel(1337);
        if (channel is SocketVoiceChannel voiceChannel)
        {
            audioClient = await voiceChannel.ConnectAsync();
            audioClient.StreamCreated += AudioClient_StreamCreated;
        }
    }

    private async Task AudioClient_StreamCreated(ulong userid, AudioInStream stream)
    {
        Console.WriteLine("ReadFrameAsync");
        var frame = await audioStream.ReadFrameAsync(System.Threading.CancellationToken.None);
    }

**Comment by k-boyle** [comment]
Unless someone knows something that's not documented, then no idea.
The docs don't have anything for 12 https://discordapp.com/developers/docs/topics/opcodes-and-status-codes#voice

**Comment by nopjmp** [comment]
seems as though 12 and 14 are being sent from the server for now, they can be ignored, at least JDA ignores them for now.

https://github.com/DV8FromTheWorld/JDA/blob/19acdd57a88c2b93c1c61f76ba59ddfb849a6d45/src/main/java/net/dv8tion/jda/internal/audio/AudioWebSocket.java#L513-L519

**Comment by FiniteReality** [comment]
You can safely ignore "Unknown Opcode" messages - they are mainly intended for library debugging and development. Opcodes 12, 13 and 14 were originally related to guild screen-share, and they have likely been re-used in the new "Go Live" feature.

**Comment by zorkind** [comment]
We are in 2.2 and these messages still exist.

Please, can we disable them? they are annoying, i use my bot to stream audio and every time i join a voice channel i get those 3 messages :(

**Comment by AntiTcb** [comment]
You have full control on what messages get put in your console/logs. Just filter them out if you don't want them.
