### ISSUE TITLE
Bot disconnects every minute, "server sent close 1000"

### ISSUE THREAD

**Issue by Chlorobite** [RogueException/Discord.Net#1352]
My setup:
- The operating system is Debian Stretch, running on an arm64 processor on an armv7 host (Android)
- The device is connected to the Internet through Wi-Fi. I know the Wi-Fi is reliable because I literally ran a Minecraft server on this same device
- The Discord bots are run using Mono or .NET Core (both have this issue)
- The bots disconnect every minute for seemingly no reason. The exact error message is below:
```
System.Exception: WebSocket connection was closed ---> Discord.Net.WebSocketClosedException: The server sent close 1000: ""
  at Discord.Net.WebSockets.DefaultWebSocketClient.RunAsync (System.Threading.CancellationToken cancelToken) [0x000df] in <3331075733c74092b9fa467c888c9e7b>:0 
   --- End of inner exception stack trace ---
  at Discord.ConnectionManager+<>c__DisplayClass29_0.<StartAsync>b__0 () [0x0014b] in <3331075733c74092b9fa467c888c9e7b>:0
```

I can't seem to reproduce this issue on an x86 machine. Is this even a Discord .NET bug? If it's not, what can I do to fix the issue? (apart from just running x86 lmao, I'm unable to do that)

**Comment by k-boyle** [comment]
Nothing Discord.Net can do about this, this is on Discord's end. However, Discord.Net isn't compatible with Mono so that's going to be causing some extra issues.

**Comment by Chlorobite** [comment]
> However, Discord.Net isn't compatible with Mono so that's going to be causing some extra issues.

I mean, this is the only time I had issues with Discord.Net. I've been running them on a Linux VPS (with Mono, obviously) for a while, but that VPS has recently become unstable, so I had to try something out; running the bots on my phone instead. It's basically the same setup, just a different CPU architecture and probably a different setup for the system.

**Comment by FiniteReality** [comment]
I'd suggest trying using .NET Core instead of Mono if you can - you may get better mileage.

**Comment by Chlorobite** [comment]
Alright, I've tried .NET Core. The exact same issue happens.

**Comment by Chlorobite** [comment]
Update: mysteriously, the reconnects stopped somewhere after midnight. I've done more testing, and it seems that the reconnects stop if the device is plugged in (charging). I'll assume this is a pretty stupid bug on my bootleg phone that no wonder I decided to dedicate to running Discord bots.

Sorry for bothering you, it was just a pretty confusing error with no context at all.
