### ISSUE TITLE
Loosing network connection won't reach disconnected state

### ISSUE THREAD

**Issue by Xeevis** [RogueException/Discord.Net#136]
I'm trying to hook disconnected event when network connection is lost. Problem is that disconnected event is never invoked 

```
[Debug] Gateway -> Sent Heartbeat
[Debug] Gateway -> Received HeartbeatAck
[Verbose] Gateway -> Latency = 140 ms
[Debug] Gateway -> Sent Heartbeat
[Warning] Gateway -> Server missed last heartbeat
[Info] Gateway -> Disconnecting
[Debug] Gateway -> Disconnecting - CancelToken
[Debug] Gateway -> Disconnecting - ApiClient
[Debug] Gateway -> Disconnecting - Heartbeat
```

It will get stuck on this line https://github.com/RogueException/Discord.Net/blob/dev/src/Discord.Net/DiscordSocketClient.cs#L216

**Comment by RogueException** [comment]
Possible duplicate of #130

**Comment by RogueException** [comment]
Looks like this is fixed in the recent set of reconnect commits. Feel free to reopen this if it happens again on the latest.
