### ISSUE TITLE
Cannot Dispose() CommandService

### ISSUE THREAD

**Issue by Foxite** [RogueException/Discord.Net#1363]
[CommandService](https://github.com/discord-net/Discord.Net/blob/dev/src/Discord.Net.Commands/CommandService.cs#L30) is IDisposable. It [explicitly implements](https://github.com/discord-net/Discord.Net/blob/dev/src/Discord.Net.Commands/CommandService.cs#L619)  this interface, and naturally the Dispose() method is public.

However, I am unable to see the Dispose() method when viewing the metadata inside Visual Studio, and I cannot call it either (it tells me that Dispose(bool) is inaccessible because it is `protected`).

This directly contradicts my knowledge that all members that implement an interface must be public. How is this possible?

And what should I do instead to dispose a CommandService instance?

**Comment by Emzi0767** [comment]
Explicit implementations are not public unless instance is referred to as interface they are implemented for. In other words the only way to access this particular member is to treat the command service instance as an instance of `IDisposable`.

**Comment by FiniteReality** [comment]
The CommandService implements IDisposable to properly support certain dependency-injection scenarios - if you are creating them manually then you likely only ever have one instance during the entire lifetime of your application, hence cleanup is not particularly necessary.
