### ISSUE TITLE
Client cant React to DMs

### ISSUE THREAD

**Issue by StempunkDev** [RogueException/Discord.Net#1366]
Hey there,
so i wanned a Bot to react to his own Msg with a normal Discord Emote(not a custom one)

It trows an error.
My question now is: Is that a Discord Api thing or a Discord.Net Problem

**Comment by Joe4evr** [comment]
It's a You Problem, you have to use `Emoji` for Unicode emoji instead of custom emotes.

**Comment by StempunkDev** [comment]
so i just made it like this http://prntscr.com/ozyxs2, but i got the same error

**Comment by Anu6is** [comment]
Use the unicode instead. 
```cs
await msg.AddReactionAsync(new Emoji("\u25b6")); 
```

**Comment by Still34** [comment]
This issue appears to be solved. Please re-open the issue if you have any other questions. Thanks!
