### ISSUE TITLE
[Suggestion] SocketGuildChannel Mention 

### ISSUE THREAD

**Issue by Laiteux** [RogueException/Discord.Net#1367]
What about adding ``.Mention`` for ``SocketGuildChannel``?
Actually, we have to do:
```cs
SocketGuildChannel generalChannel = Context.Guild.Channels.FirstOrDefault(c => c.Name.ToLower() == "general");
ReplyAsync($"<#{generalChannel.Id}>");
```

**Comment by k-boyle** [comment]
Because technically speaking you can't mention a voice channel.

**Comment by Laiteux** [comment]
SocketGuildChannel can also be a text channel.

**Comment by Laiteux** [comment]
Would there be a way of converting it to ``SocketTextChannel``, then?

**Comment by k-boyle** [comment]
> Would there be a way of converting it to `SocketTextChannel`, then?

Cast it to a `SocketTextChannel`. Or fetch from the `TextChannels` collection to begin with.

**Comment by Laiteux** [comment]
Yep, thank you.

**Comment by Laiteux** [comment]
I need some sleep.
