### ISSUE TITLE
TypeReader evaluate the absence of a parameter

### ISSUE THREAD

**Issue by Foxite** [RogueException/Discord.Net#1380]
I have a command that takes a custom class as a parameter. I have a TypeReader for this, and it works fine. I want a user to be able to omit the parameter, but I want to have a default value that is based on the user executing the command.

The system I have right now involves a second module with the same commands, except that they don't take any parameters. All of these commands call CommandService.ExecuteAsync with a fake input string, which consists of the input, plus a special value which my TypeReader will pick up and resolve based on the user.

This works but it's effectively abuse of ExecuteAsync's string parameter, and it has a few more problems (which aren't important right now, but I can't have those). I want to get rid of it as soon as possible, and have the CommandService use the TypeReader when there is no input for the parameter.

Is this at all possible? If not, is it feasible to implement any time soon?

**Comment by Anu6is** [comment]
> I want a user to be able to omit the parameter, but I want to have a default value that is based on the user executing the command.

Why doesn't optional parameters work for this?

**Comment by Foxite** [comment]
Because the default value has to be a compile time constant, and I need to resolve the default value based on the user executing it.

I considered making the default value some kind of "special" instance of the class, but it quickly became a huge mess.

Edit: I'm currently trying to manually invoke the TypeReader with the special value, if this works, then this feature won't be necessary for me.

Edit 2: This works, I no longer need a second module and I won't need the ability to do what I was asking.

This issue may be closed.
