### ISSUE TITLE
Is is possible to retrieve messages from a channel?

### ISSUE THREAD

**Issue by Sinesters** [RogueException/Discord.Net#1389]
I can send messages to a text channel via my app already, but now i'm trying to read that same text channel is that possible? if yes please can you send me into the right direction \ documentation would really appreciate.

Thank you

**Comment by GreemDev** [comment]
[It's on the same page as SendMessageAsync().](https://docs.stillu.cc/api/Discord.WebSocket.SocketTextChannel.html#Discord_WebSocket_SocketTextChannel_GetMessagesAsync_Discord_IMessage_Discord_Direction_System_Int32_Discord_RequestOptions_)

**Comment by Sinesters** [comment]
Thank you
