### ISSUE TITLE
Scopes and RunMode.Async

### ISSUE THREAD

**Issue by CodeSteele** [RogueException/Discord.Net#1397]
Alright, as per #1286 I'm creating a new scope per command, pretty handy, keeps everything straight and doesn't cause any issues with EF Core, awesome.

Problem: I'm trying to move to `RunMode.Async`, changes are fairly trivial outside of scope management.

`CommandService.ExecuteAsync` will return immediately with that run mode, it'll drop out of the using and dispose of the scope, killing the service provider.

There doesn't seem to be a way to pass it a scope or any ancillary information to pass into the `CommandService.CommandExecuted` event handler so I can clean up unused scopes.

My options are pretty poor as far as I can tell:

  - Move all scoped items to transients
  - Move all commands to take a service provider instead of their injected objects, new up a scope there, trash on dispose.
  - Extend the CommandService to mange my scope inside of it.

Any other ideas that are supported by the lib out of the box? I'm working on the last one right now.

**Comment by k-boyle** [comment]
1) what do you mean trying to move to RunMode async? We only recommend that RunMode for long running commands since it introduces issues, such as this.
2) command executed has a service provider parameter, no? Just dispose of it there

**Comment by CodeSteele** [comment]
> 1. what do you mean trying to move to RunMode async? We only recommend that RunMode for long running commands since it introduces issues, such as this.

Changing the `RunMode` on commands, ideally because we do have I/O and don't want to block the main gateway thread while doing these commands, arguably yeah, we're expecting them to take <100ms, probably even within the range of like <20ms, but figured it would be ideal to make the entire stack async.

> 2. command executed has a service provider parameter, no? Just dispose of it there

Not _currently_, the commands take a `DbContext` in the constructor and are relying on the `CommandService` to handle dependency injection to do so. That was an _option_ for resolving it but pushes DI scoping responsibilities down to the individual commands and requires me to call a bunch of `Scope.GetRequiredService<T>(...)` calls in the constructors which is a little rough, but a viable solution if there isn't built-in support for this.

**Comment by k-boyle** [comment]
@CodeSteele the recommendation for RunMode.Async is 3seconds. And why can't you call dispose in the command executed event exactly? You should have access to your db context within it (and if not its not exactly hard to get it via your own command context implementation)

**Comment by CodeSteele** [comment]
> @CodeSteele the recommendation for RunMode.Async is 3seconds. 

I know you get a warning at 3 seconds, but I didn't know how badly blocking the gateway thread harmed throughput or caused the possibility for command back-up on higher volume systems. So I was trying to get off the gateway thread earlier and earlier as we grow. Because of this possible throughput issue I _figured_ I was missing some native way this lib supported this flow.

>And why can't you call dispose in the command executed event exactly?

I have no access to the command executed specific scope during the event, I have no way to pass it through to the new thread.

> (and if not its not exactly hard to get it via your own command context implementation)

Cool, that's probably what I'm leaning towards, I just didn't want to re-invent the wheel if the lib already supported this. I'll check it out and come back with my implementation if anyone else needs it, thanks!

**Comment by CodeSteele** [comment]
Custom scoped command context:

```csharp
public class ScopedCommandContext : CommandContext
{
	public IServiceScope ServiceScope { get; }

	public ScopedCommandContext(
		IServiceScope serviceScope,
		global::Discord.IDiscordClient client,
		global::Discord.IUserMessage msg) : base(client, msg)
	{
		ServiceScope = serviceScope;
	}
}
```

And first thing we do is dispose of it because by this point we're done with all command context injection:

```csharp
private async Task CommandExecuted(Optional<CommandInfo> commandInfo, ICommandContext context, IResult result)
{
	if (context is ScopedCommandContext scopedCommandContext)
	{
		scopedCommandContext.ServiceScope.Dispose();
	}

        // Handle the executed event here
}
```

Works well for me, I'll close this.

**Comment by k-boyle** [comment]
Probably best to inherit `SocketCommandContext` and then make your context
disposable

**Comment by CodeSteele** [comment]
Good point on that, makes it much more reliable, will do.
