### ISSUE TITLE
Allow MessageTypeReader to read non cached messages

### ISSUE THREAD

**Issue by OhB00** [RogueException/Discord.Net#1398]
The `MessageTypeReader` will only ever get cached messages. 

If a non-cached message is used as an input parameter the type reader will always return `message not found`.

It would be useful if it could return cached messages, or if user added type readers had a higher priority than default type readers so that their behaviours can be changed.

Heres some example code:

```
[Command("message")]
public async Task Echo(IUserMessage message)
{
   await ReplyAsync($"Message: {message.content}");
}
```

To reproduce, use a message-id that is not cached as input, or set message cache size to 0 and use any message-id.

**Comment by Anu6is** [comment]
You can change the behavior, just override the default with your custom typereader.
[Documentation on overriding a typereader](https://docs.stillu.cc/api/Discord.Commands.OverrideTypeReaderAttribute.html)
```
public Task MyCommand([OverrideTypeReader(typeof(CustomMessageTypeReader))] IUserMessage msg)
```
[Documentation on creating a custom typereader](https://docs.stillu.cc/guides/commands/typereaders.html#example---creating-a-type-reader)

**Comment by OhB00** [comment]
How is this done?

**Comment by Anu6is** [comment]
update my previous comment

**Comment by OhB00** [comment]
Thank you! Apologies for any wasted time.
