### ISSUE TITLE
Get the id of the message I just sent

### ISSUE THREAD

**Issue by minisbett** [RogueException/Discord.Net#1408]
I use `SocketTextChannel.SendMessageAsync()` to send my messages. But after I sent them I need their ID. How can I accomplish that?

**Comment by Anu6is** [comment]
SendMessageAsync returns the message object for the message that gets sent. Store it and retrieve it's ID property

**Comment by Yinci** [comment]
> 
> 
> SendMessageAsync returns the message object for the message that gets sent. Store it and retrieve it's ID property

In case that still confuses you; `var message = await SocketTextChannel.SendMessageAsync()` will return you an `IUserMessage` which you can then get the ID from.

**Comment by minisbett** [comment]
Thanks!
