### ISSUE TITLE
MessageUpdated second argument is not initialized properly if a link preview is fetched after sending it

### ISSUE THREAD

**Issue by Foxite** [RogueException/Discord.Net#1409]
If discord fetches a link preview after the message was sent, then this code:

    void Init() {
    	DiscordSocketClient client;
    	// set up client
    	client.MessageUpdated += OnMessageUpdated;
    }
    
    private async Task OnMessageUpdated(Cacheable<IMessage, ulong> messageBefore, SocketMessage messageAfter, ISocketMessageChannel channel) {
    	Console.WriteLine(messageAfter.Content.Length);
    }

Will throw a NullReferenceException when the link preview is fetched. When inspected with a debugger, it appears that several properties return a default value, including Content, Author, and Timestamp.

I was able to reproduce this by grabbing some random links from https://github.com/trending and sending them directly into a text channel. This works once per link, as sending the same link twice will cause the preview to be fetched immediately, and MessageUpdated won't be executed.

**Comment by Anu6is** [comment]
Is your cache enabled?

**Comment by Foxite** [comment]
It is not, but it seems odd that caching must be enabled to view the *new* version of a message.

Edit: that's what the second argument is, right? I've always assumed so because the first message is wrapped in a Cachable, but I've never actually written anything based on that assumption. 

Enabling cache by setting the size to 1024 prevents this problem from happening.

**Comment by AntiTcb** [comment]
IIRC, the gateway passes back a partial message object with only with what was updated.

**Comment by Foxite** [comment]
That would explain it. The content or any of those other fields isn't actually updated, but an embed is added, which is present in the new object.

Thanks for the answer, I'll modify my code to be aware of this.

**Comment by Anu6is** [comment]
1024 is storing 1024 messages per channel, per guild btw.
The cache is per channel
