### ISSUE TITLE
IGuildUser needs a property for their boost count.

### ISSUE THREAD

**Issue by LtLi0n** [RogueException/Discord.Net#1410]
![image](https://user-images.githubusercontent.com/31516441/67899788-b64bbc80-fb6b-11e9-8442-8efbd95771df.png)
![image](https://user-images.githubusercontent.com/31516441/67899793-b9df4380-fb6b-11e9-9163-5601d6c749f4.png)

Noticed by:
 **darkmanifest#1204** user id: `136666894810742785`

**Comment by NovusTheory** [comment]
To my knowledge, the API currently doesn't expose this information to bots.

**Comment by Chris-Johnston** [comment]
After doing a bit of investigation, I've also found `premium_guild_since` in addition to [`premium_since` on users](https://github.com/discord-net/Discord.Net/blob/7f0c0c91556dd786f556de293dac8dea531a7414/src/Discord.Net.Rest/API/Common/GuildMember.cs#L21). If this is set, the user will have a boost icon badge on their profile.

![image](https://user-images.githubusercontent.com/16418643/67915212-8a224280-fb4f-11e9-9bcc-527a6890c5c4.png)

This is not the same as a boost count property, but I think it's similar enough to group them together. For now this is blocked until the API exposes this info.

**Comment by Chris-Johnston** [comment]
Actually, I was looking in the wrong place.
`GET https://discordapp.com/api/v6/guilds/<guild id>/premium/subscriptions`

```json
[
    {
        "ended": false,
        "guild_id": "297485054836342786",
        "user_id": "1234",
        "id": "629520696724422656",
        "user": {
            "username": "<user>",
            "discriminator": "9346",
            "id": "123123123",
            "avatar": "123123123"
        }
    },
    {
        "ended": false,
        "guild_id": "297485054836342786",
        "user_id": "1234",
        "id": "638852622572585032",
        "user": {
            "username": "<user>",
            "discriminator": "9346",
            "id": "123123123",
            "avatar": "123123123"
        }
    }
]
```

The client doesn't render this data correctly as of writing, but the API correctly shows both boosts from the same user.

I do not know if bots can access this, though.

Update: Nope, they cannot. `"The server responded with error 20001: Bots cannot use this endpoint"`
