### ISSUE TITLE
Get user by ID

### ISSUE THREAD

**Issue by ghost** [RogueException/Discord.Net#1411]
Hi there,

Just wondering if it is possible to get a User property by the User's ID? E.g. `Client.GetUserAsync(userId)` instead of `Client.GetUserAsync(username, discriminator)`.

Thanks in advance.

**Comment by ghost** [comment]
Apparently this is impossible to do within Discord's API.

**Comment by Anu6is** [comment]
What? `Client.GetUser(id)` is **[available](https://docs.stillu.cc/api/Discord.WebSocket.DiscordSocketClient.html#Discord_WebSocket_DiscordSocketClient_GetUser_System_UInt64_).**

**Comment by NeonPhoenix** [comment]
You can either use ```SocketGuildUser``` inside a command async.
Or grab the user ID from ```SocketCommandContext```
