### ISSUE TITLE
Why is TypeReaderResult a struct

### ISSUE THREAD

**Issue by Foxite** [RogueException/Discord.Net#1420]
Why is [TypeReaderResult](https://github.com/discord-net/Discord.Net/blob/dev/src/Discord.Net.Commands/Results/TypeReaderResult.cs) a struct rather than a class? Other IResult derived types are classes as well, and this is preventing me from extending TypeReaderResult to carry localization information.

**Comment by FiniteReality** [comment]
![why](https://cdn.discordapp.com/attachments/106126169627181056/231117241892995072/unknown.png)

In all seriousness; I'd gladly merge a PR to change it to a class, but it would be a breaking change.

**Comment by Joe4evr** [comment]
Could be done for 3.0, since we're already planning to break a few other things with that release.

**Comment by FiniteReality** [comment]
> planning to break a few other things with that release.

> a few

:rofl:

**Comment by Joe4evr** [comment]
Also, [SearchResult](https://github.com/discord-net/Discord.Net/blob/dev/src/Discord.Net.Commands/Results/SearchResult.cs), [ParseResult](https://github.com/discord-net/Discord.Net/blob/dev/src/Discord.Net.Commands/Results/ParseResult.cs), and [ExecuteResult](https://github.com/discord-net/Discord.Net/blob/dev/src/Discord.Net.Commands/Results/ExecuteResult.cs).

**Comment by quinchs** [comment]
@Cenngo Could you look at this

**Comment by Cenngo** [comment]
When dealing with frequently instanciated, short lived and small objects you should use strcuts to reduce memory allocations and Gc preassure so thats why results are structs. I know ideally you shouldnt be boxing structs but it is what it is.

**Comment by Cenngo** [comment]
how would you access the localization info anyways, typereaderresult isnt returned unless it fails.
