### ISSUE TITLE
Moving Mobile Users in VCs disconnects them

### ISSUE THREAD

**Issue by GIRU-GIRU** [RogueException/Discord.Net#1423]
`                    await user.ModifyAsync(x =>
                    {
                        x.Channel = channel;
                    });`

Works fine for desktop users, mobile users get moved briefly then immediately disconnected. Affecting both Android and IOS

**Comment by AntiTcb** [comment]
What if you move them in the client rather than via the lib?

**Comment by tmeijome** [comment]
I'm not sure this is limited to mobile users. I have the same or similar issue on a Windows client, but I feel like this used to work.

If I go to discord and drag the connected user down to a different voice channel, I get the following exception: Discord.Net.WebSocketClosedException: 'The server sent close 4014: "Disconnected."'

Then a whole host of other exceptions follows as the library attempts to access the websocket.

**Comment by MrCakeSlayer** [comment]
@GIRU-GIRU this issue seems to be resolved as far as I can tell. If you run into it again feel free to open a new issue.
