### ISSUE TITLE
Adding reactions is slow in 2.2.0

### ISSUE THREAD

**Issue by Confruggy** [RogueException/Discord.Net#1431]
Adding reactions in 2.2.0 is slower than it was in 2.1.1
I tested it with the following code:
```cs
[Command("test")]
public async Task TestCommand(int amount)
{
    for (int i = 0; i < amount; i++)
    {
        var message = await ReplyAsync("test");
        var emotes = new[]
        {
            new Emoji("1️⃣"),
            new Emoji("2️⃣"),
            new Emoji("3️⃣"),
            new Emoji("4️⃣"),
            new Emoji("5️⃣"),
            new Emoji("6️⃣"),
            new Emoji("7️⃣"),
            new Emoji("8️⃣"),
            new Emoji("9️⃣"),
            new Emoji("🔟")
        };
        var stopWatch = new Stopwatch();
        stopWatch.Start();
        await message.AddReactionsAsync(emotes);
        stopWatch.Stop();
        await message.ModifyAsync(x => x.Content = $"{DiscordConfig.Version}: {stopWatch.ElapsedMilliseconds} ms");
        await Task.Delay(5000);
    }
}
```
The result is that adding reactions in 2.2.0 takes about twice as much.

![image](https://user-images.githubusercontent.com/5957412/70926299-27b4d100-202d-11ea-95a6-224a81cc626a.png)

**Comment by Chris-Johnston** [comment]
I've found that [re-adding this block of code seems to "fix" the issue, since it ignores the reset and lag from the ratelimit headers.](https://github.com/discord-net/Discord.Net/blob/7b9029dd914f2448eee9ed46f4a77947ca6f430c/src/Discord.Net.Rest/Net/Queue/RequestQueueBucket.cs#L258) Given this, it seems that the longer time is intentional from the API itself.

**Comment by PentoreXannaci** [comment]
is this still a thing?
i have that issue too.

**Comment by csmir** [comment]
Reactions suffer from horrible ratelimiting since buttons have been added. I doubt the recent issues come from the same root cause. As stated before, this is probably API intentional.
