### ISSUE TITLE
Creating AudioClient from SessionId, Token, GuildId and EndpointURL

### ISSUE THREAD

**Issue by ItsNerd** [RogueException/Discord.Net#1434]
When my bot wants to "join" a voice channel, Discord sends some temporary login details (session ID and token) to one of the voice servers in what's called a “voice server update”. How i can create AudioClient (or something, that help me send audio) from this data?

I cannot use the usual methods because I want to transfer this data to another instance of the program and keep accessToken in secret.

**Comment by csmir** [comment]
Please follow up if you still have need for this answer. With the planned rework of the voice API, this functionality will change and probably be handled appropriately by default.
