### ISSUE TITLE
 System.InvalidOperationException: This property has no value set.

### ISSUE THREAD

**Issue by msx752** [RogueException/Discord.Net#1436]
are  there any reported issue for **GetTextChannelsAsync** or **GetChannelsAsync** methods for **Discord.Net.Rest v2.1.1**

because there is an issue when i try to get channels (with both methods), but this issue occured only specific discords which have [Announcement Channels](https://support.discordapp.com/hc/en-us/articles/360032008192-Announcement-Channels-) , in other discords which don't have that channel, can successfully retrive channels.

error detail
```
 ---> System.InvalidOperationException: This property has no value set.
   at Discord.Optional`1.get_Value()
   at Discord.Rest.RestTextChannel.Update(Channel model)
   at Discord.Rest.RestNewsChannel.Create(BaseDiscordClient discord, IGuild guild, Channel model)
   at System.Linq.Enumerable.SelectIListIterator`2.ToArray()
   at System.Collections.Immutable.ImmutableArray.CreateRange[T](IEnumerable`1 items)
   at Discord.Rest.GuildHelper.GetChannelsAsync(IGuild guild, BaseDiscordClient client, RequestOptions options)

```

**Comment by msx752** [comment]
i found something but i don't know whether it is related with this issue or not https://github.com/discord-net/Discord.Net/issues/1415

**Comment by msx752** [comment]
**more detail about issue on debugging.**

`RestGuildChannel.Create()` --> `switch `--> ` ChannelType.News ` --> `RestNewsChannel.Create()` --> `Update() ` --> `'model.SlowMode.Value' threw an exception of type 'System.InvalidOperationException' `, **iff Announcement Channel feature is enabled on discord**  
https://github.com/discord-net/Discord.Net/blob/dev/src/Discord.Net.Rest/Entities/Channels/RestTextChannel.cs#L45

**Comment by njlr** [comment]
I am also seeing this issue.
