### ISSUE TITLE
Clients don't respect the gateway identify rate-limit.

### ISSUE THREAD

**Issue by Quahu** [RogueException/Discord.Net#1442]
This causes bots with more than 1 gateway connection to get instantly disconnected upon attempting to identify. The more shards, the more disconnections this causes.

To fix this, DiscordShardedClient and individual clients/shards should respect the 1/5s identify limit with a shared connection lock that would properly delay subsequent identify attempts.
#519 is somewhat related.

**Comment by Lymdun** [comment]
Any news on it? My bot has 20 shards, and it became very slow to identify because of all the caused disconnections.
