### ISSUE TITLE
Is "Go Live" supported in this API?

### ISSUE THREAD

**Issue by Aida-Enna** [RogueException/Discord.Net#1445]
I've been trying to find a way to detect if a user is streaming via Discord's "Go Live", and according to the Discord API's previous chat, I should see a ``IsStreaming`` under the GuildMemberUpdated SocketGuildUser object. However, I don't see it.

![image](https://user-images.githubusercontent.com/5483362/73603208-a74f1e80-454d-11ea-899b-2b538f8126da.png)

I'm also using the latest version available on nuget:

![image](https://user-images.githubusercontent.com/5483362/73603212-b3d37700-454d-11ea-8002-1813d9dd1c6a.png)

**Comment by Chris-Johnston** [comment]
The `IsStreaming` property was added after the 2.1.1 release. It's currently available using the prerelease builds, which are published to the MyGet feed. [Instructions for how to install the latest prerelease builds can be found in the docs.](https://docs.stillu.cc/guides/getting_started/nightlies.html#installing-with-myget-recommended)

**Comment by Aida-Enna** [comment]
Thank you!
