### ISSUE TITLE
Modifying a webhook's channel doesn't actually modify it?

### ISSUE THREAD

**Issue by Aida-Enna** [RogueException/Discord.Net#1447]
I'm trying to create a generic webhook for use across the entire server, as opposed to an obnoxious number of webhooks per channel. I create the singular webhook and reassign it's Channel, but it still posts in the original specified channel in server settings. ChannelID reassignment doesn't work either.

```
using (var client = new DiscordWebhookClient("https://discordapp.com/api/webhooks/whatever"))
{
await client.ModifyWebhookAsync(x => x.Channel = BotClient.GetChannel(Context.Channel.Id) as SocketTextChannel);
await client.ModifyWebhookAsync(x => x.ChannelId = Context.Channel.Id);
await client.SendMessageAsync("test", false, null);
}
```

**Comment by merthsoft** [comment]
I'm also running into this--has anyone found a workaround?
