### ISSUE TITLE
DiscordSocketClient.Dispose() hangs

### ISSUE THREAD

**Issue by RheaAyase** [RogueException/Discord.Net#1448]
Calling DiscordSocketClient.Dispose() hangs what seems like indefinitely.

(And just throwing away reference to it leads to memory leak.)

How would one correctly get rid of the client and everything attached to it?

**Comment by BrammyS** [comment]
Are you stopping the client before you dispose of it?

**Comment by RheaAyase** [comment]
No, does it matter? I need to dispose of it, I expect it to dispose of everything that may or may not be running. o.o

I mean it does matter to the memory leak of course, makes sense, but the dispose shouldn't hang...

**Comment by k-boyle** [comment]
Pretty sure it deadlocks on dispose

**Comment by BrammyS** [comment]
That's what i thought as well.
Probably on the `StopAsync().GetAwaiter().GetResult();`
That's why i asked if the client was stopped before disposing.
```csharp
        internal override void Dispose(bool disposing)
        {
            if (!_isDisposed)
            {
                if (disposing)
                {
                    StopAsync().GetAwaiter().GetResult();
                    ApiClient?.Dispose();
                    _stateLock?.Dispose();
                }
                _isDisposed = true;
            }

            base.Dispose(disposing);
        }
```

**Comment by RheaAyase** [comment]
I'm gonna run with just StopAsync without dispose and see what happens.

**Comment by RheaAyase** [comment]
Yep, as far as I can tell it does die there.

**Comment by FiniteReality** [comment]
Where's this being called? If it's in response to a gateway event, that will absolutely deadlock, since StopAsync waits for any pending gateway events to be processed before returning.

**Comment by RheaAyase** [comment]
Well, that's the only use-case I can think of - Responding to `Disconnected` with `Dispose -> new client` in order to get around _another_ [hang in reconnecting](https://github.com/discord-net/Discord.Net/issues/960). :rofl:
