### ISSUE TITLE
Wrong rate limits for the 'role' endpoint.

### ISSUE THREAD

**Issue by BrammyS** [RogueException/Discord.Net#1451]
Discord.net is detecting a ratelimit at the 'roles' endpoint.
So my logs are getting spammed with messages like these:
```
09:50:52.176 : Shard 47 : Rate limit triggered: guilds/669302144016580628/roles
09:50:52.198 : Shard 47 : Rate limit triggered: guilds/669302144016580628/roles
```
I've sent a POST request to the discord API to see the rate limit headers and it still has plenty of remaining requests.
         
```
POST https://discordapp.com/api/guilds/669302144016580628/roles
```
Rate limit headers:
```
X-RateLimit-Limit: 250
X-RateLimit-Remaining: 223
X-RateLimit-Reset: 1582987327
X-RateLimit-Reset-After: 101995
```

Any idea why this is happening?

**Comment by BrammyS** [comment]
Still having the same problems.
This is making the library almost unusable.

**Comment by BrammyS** [comment]
Quick update: Switching to a different server/pc fixes the problem somehow.

And trying the manual way of creating a role as explain above, on the machine where the bot is getting rate limited, works fine as well.

So I'm starting to get a bit lost on this issue.
Would love to get some help.

**Comment by BrammyS** [comment]
Seems like it was sending a lot of wrong api calls to the api causing the IP to get banned i think.
Because switching to more smaller nodes helped fixing the  issue.

**Comment by BrammyS** [comment]
Back with the same issue. My logs are getting spammed with the message again.
And once again the problem goes away temporarily if i change the IP address of the node where that instance is running on. 

Really hoping that someone with more knowledge about the pre-emptive rate limits can help. Because this is making the library almost unusable. because it happens every other day with 90 thousand guilds.

**Comment by SubZero0** [comment]
I'll guess this is the same issue as #1535 
You are getting that message but that isn't really the correct endpoint (it probably got trimmed).
POST and PUT/PATCH/DELETE have different ratelimits buckets but are probably being handled by the same in Discord.Net

I don't know which methods you are using and when to be sure, but seems like it.
You could test #1546 (it isn't 100% ready, but close, I believe it's just not handling correctly when updating to a hash bucket when there's already a queue ongoing, kinda hard to explain but it's written there)

**Comment by BrammyS** [comment]
After some digging i found out that 2 requests are being done to the Discord API when a role is being created.

The first request is a POST request `await SendAsync<Role>("POST", () => $"guilds/{guildId}/roles", ids, options: options).ConfigureAwait(false);` and the second one is a PATCH request to modify the role with the correct settings `await SendJsonAsync<Role>("PATCH", () => $"guilds/{guildId}/roles/{roleId}", args, ids, options: options).ConfigureAwait(false);`.  

The first request works fine so the role gets created. But when it goes to the modify requests it runs into the rate limit issue. So i think this indeed the same issue as #1535. But these two request are not necessary according to the [Discord API documentation](https://discord.com/developers/docs/resources/guild#create-guild-role), it can be done in one request. Or is there a reason why it was done this way that i am not aware of? :P

```csharp
        public static async Task<RestRole> CreateRoleAsync(IGuild guild, BaseDiscordClient client,
            string name, GuildPermissions? permissions, Color? color, bool isHoisted, bool isMentionable, RequestOptions options)
        {
            if (name == null) throw new ArgumentNullException(paramName: nameof(name));

            var model = await client.ApiClient.CreateGuildRoleAsync(guild.Id, options).ConfigureAwait(false);
            var role = RestRole.Create(client, guild, model);

            await role.ModifyAsync(x =>
            {
                x.Name = name;
                x.Permissions = (permissions ?? role.Permissions);
                x.Color = (color ?? Color.Default);
                x.Hoist = isHoisted;
                x.Mentionable = isMentionable;
            }, options).ConfigureAwait(false);

            return role;
        }
```

**Comment by BrammyS** [comment]
#1557 Fixed.

**Comment by SubZero0** [comment]
Just a small thing, but that PR didn't fix the rate limit issue, it just won't happen when creating a role now because it's not calling the modify request anymore (that has a different ratelimit bucket for discord but it's dealt by the same in discord.net atm).
