### ISSUE TITLE
Give threads names

### ISSUE THREAD

**Issue by lewisakura** [RogueException/Discord.Net#1452]
I am using Serilog as a logging library for my bot, and I have had to write a custom enricher (a way of adding properties to a log line) to override thread names with a custom name because Discord.Net does not name its threads. I have a feeling that some other people may use thread names for a similar purpose and it might just be better to, as well as give it to the `LogMessage.Source` parameter, also name the threads that provide log lines.

**Comment by FiniteReality** [comment]
Discord.Net works entirely within the default ThreadPool and uses the TPL. There is no way to name the threads unless you use your own ThreadPool implementation.
