### ISSUE TITLE
Do not throw the basic Exception type

### ISSUE THREAD

**Issue by SimonPilkington** [RogueException/Discord.Net#1456]
In several places in the codebase, the basic Exception type is instantiated upon an error, in some cases with a more derived type as the InnerException.

Please consider not doing this. It makes handling exceptions in BaseDiscordClient.Log more complicated. For the case where there is no InnerException ([e.g.](https://github.com/discord-net/Discord.Net/blob/2c93363653d7935cd142b664b7abc63fd2641110/src/Discord.Net.WebSocket/ConnectionManager.cs#L51)) provide a derived Exception type. If there is an InnerException ([e.g](https://github.com/discord-net/Discord.Net/blob/2c93363653d7935cd142b664b7abc63fd2641110/src/Discord.Net.WebSocket/ConnectionManager.cs#L46)) wrap it in a derived Exception type, or do not wrap it.

**Comment by FiniteReality** [comment]
Should we fix this? Absolutely.
Will we actually fix this? Probably not.

Right now nothing is really being done as we're waiting for Wumpus.Net to start work on 3.0. If you want to put in a PR to fix this, feel free.

**Comment by SimonPilkington** [comment]
I'd be happy to, but would it be worth the effort? Will there be another 2.x release? Or is this code likely to remain in 3.0?

**Comment by FiniteReality** [comment]
¯\\\_(ツ)\_/¯

@foxbot is in charge of pushing to NuGet and such, last I checked

**Comment by AnalogFeelings** [comment]
Willing to pick this up.
