### ISSUE TITLE
Can't change color of text in embeded?

### ISSUE THREAD

**Issue by Chaos192** [RogueException/Discord.Net#1457]
So I can manually enter codes like:

Solarized Cyan: #2aa198

```
"```cs

"This is a for the statement"

```"
```

and it would change the color but I can't send that using my bot to change the color of embeds etc. It just doesn't work. Not even for normal text. Is this normal or is there a way to do this?

**Comment by Joe4evr** [comment]
Yes, you can't change the color of text in an embed. Color only affects the side-line:
![](https://cdn.discordapp.com/attachments/84319995256905728/252292324967710721/embed.png)

You can see this in action on [this interactive visualizer](https://leovoel.github.io/embed-visualizer/) as you change the value of `color` in the JSON pane.

**Comment by Chaos192** [comment]
Yeah I know how to change that but changing the text would of been cool.
