### ISSUE TITLE
Get the PreconditionAttribute in an PreconditionResult on error

### ISSUE THREAD

**Issue by ZargorNET** [RogueException/Discord.Net#1463]
Hey, preconditions are a super and easy way to require certain circumstances like NSFW. 
But there is (as far that I can see) no way to get the throwing Attribute in the `CommandExecuted` event when the error is `UnmetPrecondition`. You can only get the error message which you can define though, but it is just a poor design to use when you want completely custom error handling.

So my idea is that we add a field in [PreconditionResult.cs](https://github.com/discord-net/Discord.Net/blob/dev/src/Discord.Net.Commands/Results/PreconditionResult.cs) that holds the throwing Attribute, so that one is able to get at least the type of error. 
In order to not break custom code, I suggest that we make this field Nullable and make the parameter in the matching `FromError` method and the argument in the constructor optional,

**Comment by FiniteReality** [comment]
Ideally, your preconditions shouldn't throw and you should subclass PreconditionResult to contain the appropriate data.

**Comment by ZargorNET** [comment]
> 
> 
> Ideally, your preconditions shouldn't throw and you should subclass PreconditionResult to contain the appropriate data.

Yeah, I meant with "throw" when they were not successful, so for example when you're not in a NSFW channel but the command requires it

**Comment by JoshuaKlaser** [comment]
To 'Throw' (which I'm assuming is to prevent the command from being executed given how you described it in your previous comment) you can return a FromError. Check the following code sample:
```
public override Task<PreconditionResult> CheckPermissionsAsync(ICommandContext context, CommandInfo command, IServiceProvider services)
{
   bool checkFailedAndDontRunCommand = // check thing;

   if (checkFailedAndDontRunCommand)
      return Task.FromResult(PreconditionResult.FromError(string.Empty));
   else
      return Task.FromResult(PreconditionResult.FromSuccess());
}
```
