### ISSUE TITLE
Chanching Voice Server Region

### ISSUE THREAD

**Issue by DaNeubi** [RogueException/Discord.Net#1464]
Hey,

is there a way to change the voice server region?

**Comment by renanrcp** [comment]
For Socket Guild Entity: SocketGuild#ModifyAsync https://docs.stillu.cc/api/Discord.WebSocket.SocketGuild.html#Discord_WebSocket_SocketGuild_ModifyAsync_System_Action_Discord_GuildProperties__Discord_RequestOptions_

For REST Guild Entity RestGuild#ModifyAsync
https://docs.stillu.cc/api/Discord.Rest.RestGuild.html#Discord_Rest_RestGuild_ModifyAsync_System_Action_Discord_GuildProperties__Discord_RequestOptions_

**Comment by DaNeubi** [comment]
Thanks!
