### ISSUE TITLE
A BadImageFormatException will most likely stem from you having the incorrect binaries for your architecture. (32-bit when you need 64-bit, or vice versa). Check out https://discord.foxbot.me/binaries/ and grab the proper binaries and try again.

### ISSUE THREAD

**Issue by BalazsVokHeloXD** [RogueException/Discord.Net#1465]
A BadImageFormatException will most likely stem from you having the incorrect binaries for your architecture. (32-bit when you need 64-bit, or vice versa). Check out https://discord.foxbot.me/binaries/ and grab the proper binaries and try again.

_Originally posted by @AntiTcb in https://github.com/discord-net/Discord.Net/issues/578#issuecomment-287581108_

I owe you a beer or two thank you very much!

**Comment by Still34** [comment]
For future reference, please try to reply in the original thread instead of opening a new issue. Thanks! Closing for now.
