### ISSUE TITLE
SocketReaction.User unspecified

### ISSUE THREAD

**Issue by Coke21** [RogueException/Discord.Net#1468]
I'm using .Net Core 3.1 and Discord.Net 2.1.1.
I've got a reaction bot working, in 99% the bot functions normally, however, in some cases, I have the following exception:
![](https://i.gyazo.com/2027acb8486a79c4a7ed32110f9732bb.png)
When I've looked into `reaction.User` it had `<unspecified>`. The exception doesn't always happen and I'm not sure what's wrong here.
My log:
![7551ede9b0a0091f6c969c9907d9187a](https://user-images.githubusercontent.com/44268275/77855641-f3d37500-71f1-11ea-8e3d-2828aae583dd.png)

I found a discord user who raised that exception and asked him to redo the steps (the removing and adding a reaction) when he did that, no exceptions happened. It looks like it's random.

**Comment by moiph** [comment]
That's because `SocketReaction.User` is an `Optional<IUser>` meaning it may not have a value. That can happen if a user hasn't been downloaded (in large guilds not all users are downloaded automatically). However the reaction will still have a userId property.

**Comment by Coke21** [comment]
@moiph I appreciate your help.
I've changed:
`var user = await reaction.Channel.GetUserAsync(reaction.UserId) as SocketGuildUser;`
`await user.AddRoleAsync(role);`
`await user.RemoveRoleAsync(role);`
It seems that this might do it.
