### ISSUE TITLE
GuildAvailable event not fired & IsConnected false; after joining a new guild.

### ISSUE THREAD

**Issue by TheKingEagle** [RogueException/Discord.Net#1471]
DiscordShardedClient is not firing the GuildAvailable event after a user adds the bot to their guild, as a result, IsConnected property is not properly updated. The client has to be restarted in order for the new guild to be considered connected and available.

**Comment by renanrcp** [comment]
I think you wanna the JoinedGuild event

**Comment by TheKingEagle** [comment]
Right, I am using that event but I also need the client to check SocketGuild.IsConnected for a management screen. That variable is false until I fully restart the client.

**Comment by renanrcp** [comment]
I'm taking a look in the lib code, https://github.com/discord-net/Discord.Net/blob/adf823ca9a4fe8d6d812d952630023c9e7bfdcb9/src/Discord.Net.WebSocket/DiscordSocketClient.cs#L625 the lib really doesn't setting this property true when the CurrentUser join.

**Comment by TheKingEagle** [comment]
Would this be considered an API, rather than library issue? `if (data.Unavailable == false)` is evaluating `false` in this case, which would tell me that the data is being sent as unavailable. I'm not entirely sure if that would mean anything though... [sorry]

**Comment by rmsoftware-development** [comment]
Fixed with #1473
