### ISSUE TITLE
Clearing Guild and User cache

### ISSUE THREAD

**Issue by th0mk** [RogueException/Discord.Net#1474]
I have recently added a command that allows people to see what users from their guild I store in my database. For that command I use the method [`GetUsersAsync()`](https://discord.foxbot.me/docs/api/Discord.IGuild.html#Discord_IGuild_GetUsersAsync_Discord_CacheMode_Discord_RequestOptions_) from `IGuild`.

This gets all users and the guild info and stores it forever in the cache which (in my case) results in storing 2 massive lists in memory. This is visible in DotMemory:
![image](https://user-images.githubusercontent.com/9088316/78692898-db064600-78fa-11ea-852d-44a6a6241037.png)

![image](https://user-images.githubusercontent.com/9088316/78692952-e8bbcb80-78fa-11ea-82c4-c603b461efc4.png)

Some background info; the bot is on ~5k guild and some of the largest servers have around 120k members. I only use this request to get the IDs from the users in the server; I don't care about any other data.

As far as I can see (and asked on Discord) there is currently no easy way to clear the cache or set a lifetime on this cache. I do see a `CacheMode`, but that is only used to set if the requests requests new objects or only uses the cache.
The only way to clear the cache would be to restart the application, or else it will just keep storing more servers even if they only use the command once.

My question is: Is it possible to add a method to clear the user/guild cache? Or maybe set a lifetime on the cache?

**Comment by k-boyle** [comment]
`GetUsersAsync` doesn't cache members and as fair as I know users aren't cached in lists internally

**Comment by th0mk** [comment]
Hm, but it has a `CacheMode`  ([link](https://discord.foxbot.me/docs/api/Discord.IGuild.html#Discord_IGuild_GetUsersAsync_Discord_CacheMode_Discord_RequestOptions_)). 

If you're interested, you can see how I use it [here](https://github.com/fmbot-discord/fmbot/blob/2.5/src/FMBot.Bot/Commands/LastFM/ArtistCommands.cs#L282) and [here](https://github.com/fmbot-discord/fmbot/blob/2.5/src/FMBot.Bot/Services/IndexService.cs#L103). Note: I know the code has some improvements to be made, but the code for getting users seems fine to me.

**Comment by Joe4evr** [comment]
[The `CacheMode` isn't used on the socket, tho](https://github.com/discord-net/Discord.Net/blob/dev/src/Discord.Net.WebSocket/Entities/Guilds/SocketGuild.cs#L1172-L1173).

**Comment by k-boyle** [comment]
> Hm, but it has a `CacheMode` ([link](https://discord.foxbot.me/docs/api/Discord.IGuild.html#Discord_IGuild_GetUsersAsync_Discord_CacheMode_Discord_RequestOptions_)).
> 
> If you're interested, you can see how I use it [here](https://github.com/fmbot-discord/fmbot/blob/2.5/src/FMBot.Bot/Commands/LastFM/ArtistCommands.cs#L282) and [here](https://github.com/fmbot-discord/fmbot/blob/2.5/src/FMBot.Bot/Services/IndexService.cs#L103). Note: I know the code has some improvements to be made, but the code for getting users seems fine to me.

Notice how you're the one creating lists of users?

**Comment by k-boyle** [comment]
> [The `CacheMode` isn't used on the socket, tho](https://github.com/discord-net/Discord.Net/blob/dev/src/Discord.Net.WebSocket/Entities/Guilds/SocketGuild.cs#L1172-L1173).

Fairly sure CacheMode does nothing in every occurrence
