### ISSUE TITLE
Why isTTS = false not working in SendMessageAsync?

### ISSUE THREAD

**Issue by GVerse-Dev** [RogueException/Discord.Net#1476]
Why isTTS = false not working in SendMessageAsync?

When set to false, the bot still tts message.

 await message.Channel.SendMessageAsync("Test", false);

**Comment by Silverdimond** [comment]
I have tested this using version 2.2.0 and in my findings this is **probably** not the doing of Discord.Net but a setting in the notifications in discord
![image](https://user-images.githubusercontent.com/46320280/89122575-6918c480-d4c8-11ea-9253-5e2088f955dd.png)
I have tried with the following code 
```c#
 [Command("testtts")]
        public async Task testtts()
        {
           

            IUserMessage message =await ReplyAsync("Test",false);
            await message.Channel.SendMessageAsync("Test Number 2", false);
            await message.Channel.SendMessageAsync("Test Number 3", true);

        } 
```
