### ISSUE TITLE
Question: how to edit old message

### ISSUE THREAD

**Issue by Evi1Penguin** [RogueException/Discord.Net#1477]
I am trying to edit the text of a message previously created by the bot when someone reacts to it.
The only way I have found to edit messages is using this code
```
await message.ModifyAsync(msg => { msg.Content = "test [edited]"; });
```

but to use this I need to get the message. I try using these 2 options
```
var message = reaction.Message;
var message = reaction.Channel.GetMessageAsync(reaction.MessageId);

```
both of these return different types of message and if I try and use the modifyAsync it won't work because it only works on SocketUserMessage types and I can't convert the types the 2 options give me into a SocketUserMessage. Does anyone have any idea on how to fix it?``

**Comment by Joe4evr** [comment]
`reaction.Message` is an `Optional<SocketUserMessage>`, you have to extract the message object value out of the Optional to access its methods.

**Comment by Evi1Penguin** [comment]
How do I extract it?
