### ISSUE TITLE
Feature Request: Getting user tag

### ISSUE THREAD

**Issue by MordechaiHadad** [RogueException/Discord.Net#1481]
Currently you cannot get user tag via `Context.User`
Is there a plan to implement it?

**Comment by Anu6is** [comment]
What exactly are you asking for when u say user tag?

**Comment by MordechaiHadad** [comment]
> 
> 
> What exactly are you asking for when u say user tag?

the number after the username e.g. Mordechai#1234
Currently SocketUser lacks it

**Comment by Anu6is** [comment]
No it does not it has properties for Username, Discriminator, and DiscimintorValue. 
Discriminator is the String representation of 1234 in your example while DiscriminatorValue is UShort. 
You can combine username and discrim to get your tag or simply call `ToString` on your `User` object as that gives you the formatted tag.

**Comment by MordechaiHadad** [comment]
> 
> 
> No it does not it has properties for Username, Discriminator, and DiscimintorValue.
> Discriminator is the String representation of 1234 in your example while DiscriminatorValue is UShort.
> You can combine username and discrim to get your tag or simply call `ToString` on your `User` object as that gives you the formatted tag.

Okay thank you
but wouldn't it be convenient to add tag property? username property already exists so why not just add tag?

**Comment by k-boyle** [comment]
You mean the `Mention` property?

**Comment by AntiTcb** [comment]
What you're asking for already exists, as the overridded `ToString()` method on all concrete implementations of `IUser`.

Closing since there's no feature to implement.
