### ISSUE TITLE
Question - Most efficient way of checking if server or DM

### ISSUE THREAD

**Issue by KitsuneAndCake** [RogueException/Discord.Net#1482]
What's the most efficient way of checking if a command is being sent through a DM or server channel? I've been closely following the documentation without any issue and there seems to potentially be multiple ways of accomplishing what I need and yet none seem to fit in the situation very well.

I'd like to check via an if() statement once a command is run, if possible!

**Comment by Anu6is** [comment]
Just pattern match the channel.
Additionally, there is an in-built precondition for RequireContext() if you want to prevent the command from running in a given context, guild or dm

**Comment by KitsuneAndCake** [comment]
Oh hey, thanks so much! RequireContext is actually so helpful
