### ISSUE TITLE
How to get SocketUserMessage out of Discord.Optional

### ISSUE THREAD

**Issue by Evi1Penguin** [RogueException/Discord.Net#1490]
I am trying to edit a message when it is reacted but when I try and grab it It is a Discord.Optional<Discord.WebSocket.SocketUserMessage> and I can't edit the text with that. How do I get the SocketUserMessage from that?

```
var t = reaction.Message as SocketMessage;
await t.ModifyAsync(msg => msg.Content = "test [edited]");
```

**Comment by Anu6is** [comment]
Optional entities have a `Value` property to get the entity if it exists. That said the fact that it is optional means that it may not exist so you should first check if it `HasValue`. In regards to the reaction method, that value is only populated if the message is cached.

**Comment by Evi1Penguin** [comment]
When I check it is null. Do you know how to get the message that someone reacts to in order to change the message?

**Comment by Anu6is** [comment]
Like I said, it won't be there if the message isn't in cache. Either enable message cache or use the first parameter (cacheable) and call the GetOrDownload method

**Comment by Evi1Penguin** [comment]
That worked. Thank You!
