### ISSUE TITLE
Cannot install Discord.Net from NuGet

### ISSUE THREAD

**Issue by Nothing-Just-a-Code** [RogueException/Discord.Net#1494]
Hello Everyone,
When im trying to install discord.net from nuget. i got this error.

Iam using VS2013 with .NET 4.8 standard

Attempting to resolve dependency 'Discord.Net.Core (≥ 2.2.0)'.
Attempting to resolve dependency 'Newtonsoft.Json (≥ 12.0.2)'.
Attempting to resolve dependency 'System.Collections.Immutable (≥ 1.3.1)'.
Attempting to resolve dependency 'System.Interactive.Async (≥ 4.0.0)'.
Attempting to resolve dependency 'System.Linq.Async (≥ 4.0.0)'.
Attempting to resolve dependency 'Microsoft.Bcl.AsyncInterfaces (≥ 1.0.0)'.
Attempting to resolve dependency 'System.Threading.Tasks.Extensions (≥ 4.5.2)'.
Attempting to resolve dependency 'System.Runtime.CompilerServices.Unsafe (≥ 4.5.2)'.
Attempting to resolve dependency 'Discord.Net.Rest (≥ 2.2.0)'.
Attempting to resolve dependency 'Discord.Net.WebSocket (≥ 2.2.0)'.
Attempting to resolve dependency 'Discord.Net.Commands (≥ 2.2.0)'.
Attempting to resolve dependency 'Discord.Net.Webhook (≥ 2.2.0)'.
Installing 'System.Collections.Immutable 1.3.1'.
Successfully installed 'System.Collections.Immutable 1.3.1'.
Installing 'System.Runtime.CompilerServices.Unsafe 4.5.2'.
Successfully installed 'System.Runtime.CompilerServices.Unsafe 4.5.2'.
Installing 'System.Threading.Tasks.Extensions 4.5.2'.
Successfully installed 'System.Threading.Tasks.Extensions 4.5.2'.
Installing 'Microsoft.Bcl.AsyncInterfaces 1.0.0'.
Successfully installed 'Microsoft.Bcl.AsyncInterfaces 1.0.0'.
Installing 'System.Linq.Async 4.0.0'.
Successfully installed 'System.Linq.Async 4.0.0'.
Installing 'System.Interactive.Async 4.0.0'.
Successfully installed 'System.Interactive.Async 4.0.0'.
Installing 'Discord.Net.Core 2.2.0'.
Successfully installed 'Discord.Net.Core 2.2.0'.
Installing 'Discord.Net.Rest 2.2.0'.
Successfully installed 'Discord.Net.Rest 2.2.0'.
Installing 'Discord.Net.WebSocket 2.2.0'.
Successfully installed 'Discord.Net.WebSocket 2.2.0'.
Installing 'Discord.Net.Commands 2.2.0'.
Successfully installed 'Discord.Net.Commands 2.2.0'.
Installing 'Discord.Net.Webhook 2.2.0'.
Successfully installed 'Discord.Net.Webhook 2.2.0'.
Installing 'Discord.Net 2.2.0'.
Successfully installed 'Discord.Net 2.2.0'.
Adding 'System.Collections.Immutable 1.3.1' to INDB Scrims.
Successfully added 'System.Collections.Immutable 1.3.1' to INDB Scrims.
Adding 'System.Runtime.CompilerServices.Unsafe 4.5.2' to INDB Scrims.
Successfully added 'System.Runtime.CompilerServices.Unsafe 4.5.2' to INDB Scrims.
Adding 'System.Threading.Tasks.Extensions 4.5.2' to INDB Scrims.
Successfully added 'System.Threading.Tasks.Extensions 4.5.2' to INDB Scrims.
Adding 'Microsoft.Bcl.AsyncInterfaces 1.0.0' to INDB Scrims.
Successfully added 'Microsoft.Bcl.AsyncInterfaces 1.0.0' to INDB Scrims.
Adding 'System.Linq.Async 4.0.0' to INDB Scrims.
Successfully added 'System.Linq.Async 4.0.0' to INDB Scrims.
Adding 'System.Interactive.Async 4.0.0' to INDB Scrims.
Successfully added 'System.Interactive.Async 4.0.0' to INDB Scrims.
Adding 'Discord.Net.Core 2.2.0' to INDB Scrims.
Successfully added 'Discord.Net.Core 2.2.0' to INDB Scrims.
Adding 'Discord.Net.Rest 2.2.0' to INDB Scrims.
Successfully added 'Discord.Net.Rest 2.2.0' to INDB Scrims.
Adding 'Discord.Net.WebSocket 2.2.0' to INDB Scrims.
Successfully added 'Discord.Net.WebSocket 2.2.0' to INDB Scrims.
Adding 'Discord.Net.Commands 2.2.0' to INDB Scrims.
Successfully added 'Discord.Net.Commands 2.2.0' to INDB Scrims.
Adding 'Discord.Net.Webhook 2.2.0' to INDB Scrims.
Uninstalling 'Discord.Net.Webhook 2.2.0'.
Successfully uninstalled 'Discord.Net.Webhook 2.2.0'.
Uninstalling 'Discord.Net.Commands 2.2.0'.
Successfully uninstalled 'Discord.Net.Commands 2.2.0'.
Uninstalling 'Discord.Net.WebSocket 2.2.0'.
Successfully uninstalled 'Discord.Net.WebSocket 2.2.0'.
Uninstalling 'Discord.Net.Rest 2.2.0'.
Successfully uninstalled 'Discord.Net.Rest 2.2.0'.
Uninstalling 'Discord.Net.Core 2.2.0'.
Successfully uninstalled 'Discord.Net.Core 2.2.0'.
Uninstalling 'System.Interactive.Async 4.0.0'.
Successfully uninstalled 'System.Interactive.Async 4.0.0'.
Uninstalling 'System.Linq.Async 4.0.0'.
Successfully uninstalled 'System.Linq.Async 4.0.0'.
Uninstalling 'Microsoft.Bcl.AsyncInterfaces 1.0.0'.
Successfully uninstalled 'Microsoft.Bcl.AsyncInterfaces 1.0.0'.
Uninstalling 'System.Threading.Tasks.Extensions 4.5.2'.
Successfully uninstalled 'System.Threading.Tasks.Extensions 4.5.2'.
Uninstalling 'System.Runtime.CompilerServices.Unsafe 4.5.2'.
Successfully uninstalled 'System.Runtime.CompilerServices.Unsafe 4.5.2'.
Uninstalling 'System.Collections.Immutable 1.3.1'.
Successfully uninstalled 'System.Collections.Immutable 1.3.1'.
Install failed. Rolling back...
Could not install package 'Discord.Net.Webhook 2.2.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.8', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by AldeRoberge** [comment]
Have you tried targetting another .NET Framework version on your project?

**Comment by Hawxy** [comment]
>  VS2013 

Your VS version is not capable of resolving .NET Standard 2.0 packages correctly. Install VS2019.

**Comment by Still34** [comment]
The issue appears stale. Have you resolved this issue?

**Comment by Nothing-Just-a-Code** [comment]
Nah. Not yet.

**Comment by AraHaan** [comment]
@Nothing-Just-a-Code I would install VS2019 community. That version should fix it. Also why VS2013? That version is unsupported I believe by microsoft now.v Also not like VS2019 will break anything anyway so ye.
