### ISSUE TITLE
Am I using the packages and classes correctly?

### ISSUE THREAD

**Issue by njlr** [RogueException/Discord.Net#1498]
I am trying to create a client and connect to Discord. 

I have the package from Nuget:

```
nuget Discord.Net 2.2.0
```

My code:

```csharp
using Discord;
using Discord.Net;
using Discord.Net.WebSockets;

void DoStuff() 
{
    var config = new DiscordSocketConfig();

    var client = new DiscordSocketClient(config);

    return;
}
```

But I get a compilation error: 

> The value or constructor 'DiscordSocketConfig' is not defined. 
> Maybe you want one of the following:   DiscordConfig   DiscordClientExtensions   Discord   DiscordComparers 

I am using .NET Core 3.0 on Linux.

**Comment by Joe4evr** [comment]
You have the wrong namespace in your `using`s, you need `Discord.WebSocket`. The namespaces with `.Net` are all of the network related stuff and 99.9% you never need anything that's in there.

Also, for the future, usability questions like this should be asked in our channel in [the DAPI guild](https://discord.gg/jkrBmQR), and only use the issue tracker for actual bugs. Thanks.

**Comment by njlr** [comment]
Yes, can confirm the imports were wrong. 

```csharp
using Discord.WebSocket;
```
