### ISSUE TITLE
Question; how to create a private text channel

### ISSUE THREAD

**Issue by Franklin89** [RogueException/Discord.Net#1506]
It seems not very developer friendly to create a private channel. 
Create a new text channel and then update the permissions. But updating the permissions is not that clear in my opinion.
Do you have any snippets for this? 
Thanks

**Comment by asm512** [comment]
`var permissionOverrides = new OverwritePermissions(viewChannel:PermValue.Deny);`
`myChannel.AddPermissionOverwriteAsync(Context.Guild.EveryoneRole, permissionOverrides)`

**Comment by Franklin89** [comment]
Thanks 😂

**Comment by NikolayGameDev** [comment]
Thank you bro!!!
