### ISSUE TITLE
Documentation Requiring Re-reviews

### ISSUE THREAD

**Issue by Still34** [RogueException/Discord.Net#1515]
# Summary

There are several articles within the documentation that may need additional re-reviews for clarity and additional corrections for content that may be misleading or incorrect. Specifically, the following pages:

https://github.com/discord-net/Discord.Net/blob/dev/docs/faq/commands/general.md
https://github.com/discord-net/Discord.Net/blob/dev/docs/guides/introduction/intro.md
https://github.com/discord-net/Discord.Net/blob/dev/docs/guides/getting_started/terminology.md
https://github.com/discord-net/Discord.Net/blob/dev/docs/guides/voice/sending-voice.md
https://github.com/discord-net/Discord.Net/blob/dev/docs/guides/commands/dependency-injection.md

…and potentially many other articles.

## The Problem

Some of these articles feature terminologies or descriptions that are inaccurate or out-of-date, potentially leading to bad or smelly code. For example, our documentation regarding DI can be somewhat misleading for beginners that are not yet familiar with the concept of Inversion of Control or Dependency Injection. Our example code suggests `AddSingleton` for all implementations, which may or may not be ideal depending on the underlying service without additional explanation. While this is not necessarily within the scope of library documentation, additional comments could be made regarding DI instead of just few lines of words and a code snippet.

**Comment by HarrySpyrou** [comment]
I was going to open another issue but I think this one will do. I was trying to make a bot and I ran into an issue specifically on C#.  In the [Dependency Injection C# docs](https://github.com/discord-net/Discord.Net/blob/dev/docs/guides/text_commands/dependency-injection.md/#L1) it is mentioned that we should pass a 'context' argument, but nowhere to be found on **how** to get the context:

```csharp
public async Task HandleCommandAsync(SocketMessage msg)
	{
		// ...
		// Pass the service provider to the ExecuteAsync method for
		// precondition checks.
		await _commands.ExecuteAsync(
			context: **context**, 
			argPos: argPos, 
			services: _services);
		// ...
	}
```

Is there a possibility for an update or at least a comment, letting me know what to do? What is the context in this case? I tried reading through the docs, trying to find out where it is, so if I missed it, my apologies.

**Comment by quinchs** [comment]
https://discordnet.dev/guides/text_commands/intro.html#get-started

**Comment by HarrySpyrou** [comment]
@quinchs Thank you I thought that would be the answer.

However, it's not very clear if I have to jump back to the docs (especially since I'm new to it). Can I edit it and do a PR to make sure it's clear for whoever is reading it?

**Comment by csmir** [comment]
Will take up this chore

**Comment by MrCakeSlayer** [comment]
@Rozen4334 status on this issue?

**Comment by csmir** [comment]
The majority of issues in these articles have been resolved. Only dependency injection is not. I do not really know how to improve this outside of adding code examples, but a listing of plain examples is something that really doesn't fit the design of our docs.

**Comment by HarrySpyrou** [comment]
I have some comments on DI and I'd love to suggest a few things on how things could be done, would you mind if I put them all in a post here? And feel free to disregard all of them if you see them as not worth.

**Comment by MrCakeSlayer** [comment]
@HarrySpyrou yeah you could post them here or even open a PR for them. Either is fine.

**Comment by HarrySpyrou** [comment]
Used code from the wrong branch. I'll post the correct one here later on

**Comment by HarrySpyrou** [comment]
So, one thing that I didn't use for DI is building my own `ServiceCollection` as done in the docs. MSFT gives me this ready for me to use in their `Startup.cs`. So, I'm just using it. I register anything I need and then in the end I have something I call an Initialisation class (not good with names, please spare me) which does the basics for when the program starts, like registering the modules. The outcome of all this is,  a) I don't make anything that's already there b) I just register a new module in the Startup and there's nothing else I need to do (Mind you, **all of this is WIP**):

```csharp
public class Startup
{
    private IConfiguration Configuration { get; }
    private IDiscordClient DiscordSocketClient { get; set; }
    
    public Startup(IConfiguration configuration)
    {
        Configuration = configuration;
    }

    // This method gets called by the runtime. Use this method to add services to the container.
    public void ConfigureServices(IServiceCollection services)
    {
        //Register client and command service, then init service to get it working properly
        services.AddSingleton<DiscordSocketClient>();
        services.AddSingleton<CommandService>();
        services.AddSingleton<IInitializationService, InitializationService>();
        
        //then register modules and anything else (e.g. db)
        services.AddTransient<IInfoModule, InfoModule>();
        services.AddTransient<IWelcomeModule, WelcomeModule>();
        services.AddTransient<IColourModule, ColourModule>();
        services.AddTransient<IFirestoreDb, FirestoreDbContext>();
    }

    // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
    public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
    {
        if (env.IsDevelopment())
        {
            app.UseDeveloperExceptionPage();
        }

         // use any .NET Core / .NET 5 middleware you want here
        // get any service you need from the service provider during startup of the app to set the bot correctly
        // and call the methods you need (this is a DiscordSocketClient I have made 
        // for easy start up and shutdown stuff, no need for anyone to do this specifically
        DiscordSocketClient = app.ApplicationServices.GetService<IDiscordClient>();
        DiscordSocketClient?.LoginAndStartAsync().Wait();
        
        var initializationService = app.ApplicationServices.GetService<IInitializationService>();
        initializationService?.InitializeAsync().Wait();

        var applicationLifetime = app.ApplicationServices.GetRequiredService<IHostApplicationLifetime>();
        applicationLifetime.ApplicationStopping.Register(OnShutdown);
    }
    
    private void OnShutdown()
    {
        DiscordSocketClient.LogoutAndStopAsync().Wait();
    }
}
```
The initialisation service. The main thing here is again that because of my Startup class, I'm not manually making my own Service Provider. I'm just using what MSFT gave me by default. Just enhancing it with the things I need to use:
```csharp
public class InitializationService : IInitializationService 
{
    private readonly CommandService _commands;
    private readonly DiscordSocketClient _client;
    private readonly IServiceProvider _services;

    private const int PrefixPosition = 0;

    public InitializationService(
        IServiceProvider services, 
        CommandService commands, 
        DiscordSocketClient client)
    {
        _commands = commands;
        _client = client;
        _services = services;
    }

     // This one is responsible for delegates etc on startup
    public async Task InitializeAsync()
    { 
        await _commands.AddModulesAsync(Assembly.GetEntryAssembly(), _services);
        
        _client.MessageReceived += HandleCommandAsync;
        
        var welcomeModule = _services.GetService<IWelcomeModule>();
        if (welcomeModule != null) 
            _client.UserJoined += welcomeModule.AnnounceJoinedUser;
    }

    // basic handling, like in the docs. In the end, it executes commands.
    private async Task HandleCommandAsync(SocketMessage msg)
    {
        if (msg.Author.IsBot)
            return;

        if (msg is not SocketUserMessage message) 
            return;
        
        var context = new SocketCommandContext(_client, message);   
        
        await _commands.ExecuteAsync(
            context,
            PrefixPosition,
            _services);
    }
}
```

I basically tried to set it up in a way where I don't have to touch it most of the time. the init service just gets called during startup and is used by the `IServiceProvider` when needed. 

Good idea here would be to use the Modules the same as I would use Controllers, to call services that have the logic but that's not really relevant, I guess.

Now, I only get to create a Module, make it inherit from `ModuleBase<ICommandContext>, IInterfaceOfModule` and I don't need to touch anything else again.


There's also a question I've been meaning to ask. If I remember correctly, the generic recommendation is to register services as transient, unless we need them as something else. Do we need the client and the rest of the services in the docs as Singletons?
