### ISSUE TITLE
Setting builder.Group in OnModuleBuilding does not do anything.

### ISSUE THREAD

**Issue by OhB00** [RogueException/Discord.Net#1522]
When setting `ModuleBuilder.Group` in `OnModuleBuilding` the group is changed, however it is not added as an alias to the module.  This means changing the group does not do anything, it just appears that the module has a group, and its commands can only be executed without using the group (or only by using whatever Group or Alias it already has).

This seems like it would not be the intended behavior.

To get around this you can use `ModuleBuilder.AddAliases` but this is not particularly intuitive, as you would assume setting the group would make this change, as would setting the `GroupAttribute`.

Example:
```cs
[Group("x")]
public class XYZ : ModuleBase 
{  
   ... Add some commands
   protected override void OnModuleBuilding(CommandService commandService, ModuleBuilder builder)
   {
      builder.Group += "yz";
   }
```
Using `x` as for the group would work, using `xyz` would not.

**Comment by quinchs** [comment]
@Cenngo Can you take a look at this?

**Comment by Cenngo** [comment]
Under the hood, the `[GroupAttribute]` not only sets the Group property of the module but it also invokes the `AddAliases()` method as well. Thats why your method is not working. @quinchs If you want, i can modify the setter of the Group property to directly invoke the `AddAliases()` method.

![image](https://user-images.githubusercontent.com/57065323/143625936-31542386-fe37-46fe-9acb-a2f675b65a62.png)

**Comment by quinchs** [comment]
> i can modify the setter of the Group property to directly invoke the AddAliases() method.

Sounds good!
