### ISSUE TITLE
Rate limit help required

### ISSUE THREAD

**Issue by panthernet** [RogueException/Discord.Net#1524]
Hi, can you please help me identify what request in C# can cause this? I think it is started to appear when I've added the ability for my bot to work with several guilds.

![image](https://user-images.githubusercontent.com/5926603/81676065-c95f1380-944f-11ea-8c1b-daa699da5799.png)

Also is there any public info on what actions can trigger Discord entities refresh? For example do `GuildUser.Roles.Select(a => a.Name).ToList()` or `Roles.ToList()` will trigger refresh? And is there a difference if I select user from `guild.Users` or use `guild.GetUser(id)` method?

EDIT: I were using v2.1.1 will check v2.2.0 as there're some rate limit changes implemented. Other questions still actual, ty.

**Comment by k-boyle** [comment]
https://discord.com/developers/docs/resources/guild#modify-current-user-nick

**Comment by panthernet** [comment]
> https://discord.com/developers/docs/resources/guild#modify-current-user-nick

Oh it's a Discord path, thanks a lot!

**Comment by SubZero0** [comment]
@panthernet if your issue is solved, please close it.

**Comment by Still34** [comment]
> And is there a difference if I select user from guild.Users or use guild.GetUser(id) method?

`SocketGuild.GetUser` retrieves from `SocketGuild.Users`, so essentially no.
