### ISSUE TITLE
Add preemptive rate limit to GET and PATCH /channels/.../messages

### ISSUE THREAD

**Issue by BitPatty** [RogueException/Discord.Net#1535]
It appears that the preemptive rate limit is only triggered on POST /channels/.../messages, looking up (GET/ `SocketTextChannel.GetMessageAsync`) or modifying messages (PATCH/ `RestUserMessage.ModifyAsync`) hits the actual rate limit.

**Comment by SubZero0** [comment]
The library already has those. From my testing, Discord wasn't always sending the ratelimit headers, making Discord.Net disable the ratelimiter and cause this issue.

**Comment by SubZero0** [comment]
Forgot to update it here, but the problem isn't the header but how Discord.Net is creating and maintaining the ratelimit buckets.

**Comment by BitPatty** [comment]
Fixed by #1451

**Comment by BitPatty** [comment]
My bad, wrong pr
