### ISSUE TITLE
Replace Newtonsoft.Json with System.Text.Json.

### ISSUE THREAD

**Issue by AraHaan** [RogueException/Discord.Net#1536]
Since .net core 3.1 has a working System.Text.Json and I figured it out, perhaps we could replace the newtonsoft with System.Text.Json.

However I am currently pulling in the .net 5.0 pre-release version as it seems it is not broken on the latest on that one (yet).

It seems to work well on netcoreapp3.1 target too. Not sure about other frameworks, not like it would matter much once net5.0 is released. Also I seen something that unlike Newtonsoft.Json, System.Text.Json is faster because it does matching to what casing you place in code exactly unlike what newtonsoft does which it matches any variant of casing for it and is said from Microsoft to be more performant.

I could even make a pull request to add it as well if needed.

**Comment by AraHaan** [comment]
Also note: the parts of the library that sets: ``NullValueHandling = NullValueHandling.Ignore`` would have to be placed in global options that would then need to be passed to the deserializer / serializer instead.

Documentation of this part here: https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-how-to#exclude-all-null-value-properties

**Comment by FiniteReality** [comment]
System.Text.Json does not support everything required for Discord.Net.
