### ISSUE TITLE
Webhook add support for multiple file upload

### ISSUE THREAD

**Issue by KoB-Kirito** [RogueException/Discord.Net#1538]
Webhooks support uploading multiple files.
See https://birdie0.github.io/discord-webhooks-guide/structure/file.html for example.

Please add a method to the WebhookClient that allows multiple files.

**Comment by AraHaan** [comment]
So basically like a ``List<IFile>``

**Comment by KoB-Kirito** [comment]
More like an IEnumerable\<Stream\>, or IEnumerable\<String\> if you want to support path.
