### ISSUE TITLE
Unity Support?

### ISSUE THREAD

**Issue by AutumnEvans418** [RogueException/Discord.Net#1540]
Since unity has .net standard support, is there a way to reference this library in unity?  I am working on a webgl game that I'd like to integrate with discord.

**Comment by FiniteReality** [comment]
Probably not; Unity uses Mono and we've not really supported Mono properly for a while.

**Comment by TheAirBlow** [comment]
you can set in setting to use .NET

read this https://docs.unity3d.com/Manual/UsingDLL.html?_ga=2.86920792.1962343525.1608908996-191257631.1598611094

**Comment by SubZero0** [comment]
We don't plan on making specific changes for Mono, so don't expect Unity support.
You should be using the GameSDK or try to find another solution (like #1704 ).
