### ISSUE TITLE
Command modules seems to never execute on commands.

### ISSUE THREAD

**Issue by AraHaan** [RogueException/Discord.Net#1553]
So basically I tried doing something similar to the commands example you guys have where you use an handling service and other things for commands.

However it seems since ``Discord.Net v2.3.0-dev-20200525.6`` that for me the commands in a class that derives from ``ModuleBase<SocketCommandContext>`` never executes.

And lets just say for example that command caches a role to a database to give to users under certain conditions like so:

``!cacherole follower @followers``

Except the method that should do the caching in the command code seems to now to nothing for me and I copy pasted the command handling service file from the example exactly so it should not be that.

Edit: It seems to think that they are not specified.

Edit 2: It seems this actually does not add any modules for me: https://github.com/discord-net/Discord.Net/blob/dev/samples/02_commands_framework/Services/CommandHandlingService.cs#L33 even though there should be exactly 1 with only 1 command.

Edit 3: When I overrode the ``OnModuleBuilding`` and the other methods in the module with this:

```cs
protected override void BeforeExecute(CommandInfo command)
{
    Console.WriteLine($"About to execute the '{command.Name}' command.");
    base.BeforeExecute(command);
}

protected override void AfterExecute(CommandInfo command)
{
    Console.WriteLine($"Executed the '{command.Name}' command.");
    base.AfterExecute(command);
}

protected override void OnModuleBuilding(CommandService commandService, ModuleBuilder builder)
{
    Console.WriteLine("Building Command Module!");
    base.OnModuleBuilding(commandService, builder);
}
```
It was able to successfully print this:
```
23:44:07 Discord     Discord.Net v2.3.0-dev-20200525.6 (API v6)
Building Command Module!
MyBot#1567 is connected!
```

However it seems somehow it never added it to the modules list nor the commands to it to the commands list. Also the commands never printed the ``About to execute`` nor the ``Executed`` lines because the command never executed.

**Comment by Anu6is** [comment]
That's a lot of details without sharing what you've actually done. No one can say if you did something wrong when they don't know what you did.

**Comment by AraHaan** [comment]
https://gist.github.com/AraHaan/5df8fd1117b4048976fac5aecac5a8b8

These are the files.

**Comment by AraHaan** [comment]
Turns out it was me misstyping the command and then I ended up messing it all up when I was trying to debug it.
