### ISSUE TITLE
SoketGuild IsEmbeddable and EmbedChannelId return wrong data

### ISSUE THREAD

**Issue by riamandii** [RogueException/Discord.Net#1559]
I am querying a guild that has the widget enabled along with a widget invite channel. 

```
var guild = discordSocketClient.GetGuild(guild_id);
```

I am seeing IsEmbeddable as false and EmbedChannelId as null, even though https://discord.com/api/guilds/{guild_id}/widget.json returns the appropriate widget object.
Wondering if I have something wrong configured on the DiscordSocketClient, or if this is a bug in the client.

Razvan

**Comment by SubZero0** [comment]
@riamandii could you check if #1573 fixes your issue?
If you need, here are the nupkgs with the changes: 
[1573.zip](https://github.com/discord-net/Discord.Net/files/4804486/1573.zip)

**Comment by SubZero0** [comment]
Closing since the PR was merged and the issue has gone stale.
