### ISSUE TITLE
ITextChannel.Equals does not work

### ISSUE THREAD

**Issue by Kermalis** [RogueException/Discord.Net#1560]
Hi, I ran into a problem where Dictionary.Remove, .Contains, etc are returning false for two different ITextChannel instances, even if the IDs are equal. It actually seems .Equals itself is also returning false

```cs
if (context.Channel is ITextChannel c)
            {
                    bool b2 = _channelDeletion.ElementAt(0).Key.Equals(c); // false
                    bool b3 = _channelDeletion.ElementAt(0).Key.Id == c.Id; // true
                    bool b = _channelDeletion.ContainsKey(c); // false
                    if (_channelDeletion.Remove(c)) // false
                    {
                        return c.SendMessageAsync($"{context.User.Mention} ― This channel will no longer be deleted.");
                    }
            }
```

This definitely seems like a bug. Both channels are from `SocketCommandContext.Channel`, whatever type that gets built for commands, in this case, `Discord.WebSocket.SocketTextChannel`

**Comment by MarkusG** [comment]
As far as I know, you should always be comparing entities by their IDs and not by object reference, which I believe `Equals()` does.

**Comment by Kermalis** [comment]
These classes inherit `IEquatable<ulong>` though, so I'd assume they'd make use of it. I'm pretty sure that's what they're intended for, but I'm not sure. This check worked with other objects I've been using, such as `IGuild` objects, although I'm not sure if it's reusing those objects everywhere or not.

**Comment by MarkusG** [comment]
What type is `_channelDeletion`?

**Comment by Kermalis** [comment]
It is `Dictionary<ITextChannel, (DateTime, IUserMessage)>`
The way I check guilds is similar, `Dictionary<IGuild, ICategoryChannel>` and I use .TryGetValue/.Remove on those which works.

**Comment by FiniteReality** [comment]
You're misreading. `ITextChannel` does not implement `IEquatable`; it implements `IEntity<ulong>`, whose generic type has a constraint that T must be a `IEquatable<T>`.

**Comment by Kermalis** [comment]
Right, so what's the correct way to use Discord.Net objects in dictionaries etc? Am I supposed to write an extension method for everything a dictionary does, to instead check Id == Id? I don't think that's intuitive design, if that's the case, considering all it takes for support is adding a `.Equals` to `SocketEntity.cs`.

**Comment by MarkusG** [comment]
What would you have to reimplement? It seems here all you're doing is comparing two `ITextChannel` entities, which can be accomplished by comparing their IDs. You should use the entity's ID as they key instead of the entity itself.

**Comment by Kermalis** [comment]
Alright that makes more sense, I should've thought of it sooner actually. Thanks, I am just used to .Equals overloading

**Comment by Kermalis** [comment]
Upon changing all of my code now, in some places I still need the original instance in the dictionary (IE to delete the channel once I'm done with it) which means I'd still need an extension method. I really believe since this is C# we're talking about, overloads are important (which is why I'm going to use `IEqualityComparer<T>`)

**Comment by MarkusG** [comment]
You can use the `GetChannel()` method to get the channel with its ID. You could PR a change in to make entities equatable, but I can't make a guarantee that the active contributors and maintainers will approve it.

**Comment by Kermalis** [comment]
I know, but it's a little too messy for me when I already had the instances, and just had to check if they existed in the dictionary. Especially now that I have to change multiple files with collections to use ulongs, it's just not worth it for me to code in that style.

I don't think they will approve it either, since it'd probably break a lot of peoples' existing code (because most people don't think in OOP and are probably unaware of `object.ReferenceEquals`), but if they would approve it I'd definitely make a PR for it since it feels like such a necessary addition (100% of the time you ask "is this entity the same as that one?" we are talking about IDs, not memory address).

**Comment by MarkusG** [comment]
@FiniteReality do we want entities to implement `IEquatable`?

**Comment by Joe4evr** [comment]
@Kermalis [We provide a set of Equality Comparers for all the entities for the specific purpose of using in dictionaries](https://docs.stillu.cc/api/Discord.DiscordComparers.html).

**Comment by Kermalis** [comment]
@Joe4evr thanks for that, it's what I was after
