### ISSUE TITLE
SocketGuild.CreateRoleAsync Overload Can Cause Ambiguous Error In Version 2.2.0

### ISSUE THREAD

**Issue by JoshuaKlaser** [RogueException/Discord.Net#1563]
In the SocketGuild.cs class a new overload was introduced for the method CreateRoleAsync that brought in the parameter 'isMentionable'.

Upgrading from 2.1.1 to 2.2.0 caused a build error for me as 'The call is ambiguous between the following methods or properties ...' for the code:
`var guildRole = await Context.Guild.CreateRoleAsync(Enum.GetName(typeof(RoleType), role), GuildPermissions.None, Color.Teal);`

The error will also occur if you use named arguments:
`var guildRole = await Context.Guild.CreateRoleAsync(name: Enum.GetName(typeof(RoleType), role), permissions: GuildPermissions.None, color: Color.Teal);`

I can easily fix this by updating the line to become:
`var guildRole = await Context.Guild.CreateRoleAsync(Enum.GetName(typeof(RoleType), role), GuildPermissions.None, Color.Teal, false, null);`

I wanted to bring this up as I feel that adding an overload shouldn't break the build. I think that combining default parameters with overloads may not be the best idea. Given that the parameters are nearly all defaulted, could we perhaps just have the 1 method that has the `bool isMentionable = false` at the end of the argument list?

**Comment by Anu6is** [comment]
I believe the decision was made that the request options should always be last parameter. You don't need to set every option in order to fix this, simply pass isMentionalble as a named parameter.
`var guildRole = await Context.Guild.CreateRoleAsync(name: roleName, color: Color.Teal, isMentionable: false);`

**Comment by JoshuaKlaser** [comment]
Fair enough. Happy to update the code to work with the update.
