### ISSUE TITLE
ExecuteAsync always returns UnknownCommand but Modules exist

### ISSUE THREAD

**Issue by ghost** [RogueException/Discord.Net#1565]
I've switched over to using Microsoft.NET.Sdk.Web and using the `ConfigureServices(IServiceCollection service)` method of dependency injection in order to configure my database, but somewhere along the way, this has introduced a somewhat odd issue where every command returns an `Unknown Command` result.

If I try and get the available commands like such:
`var exeCommands = await commands.GetExecutableCommandsAsync(context, services);`
then a list of the correct commands is retrieved. 

If, on the very next line the following is called:
`var result = await commands.ExecuteAsync(context, argPos, services) .ConfigureAwait(false);`
Then an unknown command is returned.

I've looked at the documentation and I can only surmise something is going on in [CommandMapNode.GetCommands](https://github.com/discord-net/Discord.Net/blob/dev/src/Discord.Net.Commands/Map/CommandMapNode.cs#L79)

Is there something that wouldn't be supported with this SDK?

**Comment by Hawxy** [comment]
> I've switched over to using Microsoft.NET.Sdk.Web and using the ConfigureServices(IServiceCollection service) method of dependency injection in order to configure my database.

FYI, if you want to use this pattern in a plain .NET Core application, all you need is the `Microsoft.Extensions.Hosting` package and to create a new `HostBuilder` at your entry point. The specific SDK is only required for ASP.NET Core.

**Comment by ghost** [comment]
If that's all that's needed then it must be something more subtle, as I'm definitely using host builder correctly. 

So let me go more in-depth. 

In the `Startup.cs` I have 
```
public async void ConfigureServices(IServiceCollection services)
{
  services.AddDbContext<ApplicationDbContext>(options =>
    {
       options.UseSqlServer("Server=(localdb)\\mssqllocaldb;Database=AnimalCrossingContext;Trusted_Connection=True;MultipleActiveResultSets=true",
        x => x.MigrationsAssembly("AnimalCrossingDiscordBotDalMigrations"));
        options.UseQueryTrackingBehavior(QueryTrackingBehavior.NoTracking);
    });
    services.AddAutoMapper(typeof(Startup));

    var serviceProvider = services.BuildServiceProvider();
    var isabelleBot = new IsabelleBot(serviceProvider);

    await isabelleBot.RunAsync().ConfigureAwait(false);
    services.AddSingleton(isabelleBot);
}
```

Meanwhile my bot `IsabelleBot.cs`:
```
public class IsabelleBot
{
   private readonly DiscordSocketClient client;
   private readonly CommandService commands;
   private readonly ILogger logger;
   private readonly CommandHandler commandHandler;

   public IsabelleBot(IServiceProvider services)
   {
        client = new DiscordSocketClient(new DiscordSocketConfig
        {
            LogLevel = LogSeverity.Info,
            MessageCacheSize = 50,
        });

        commands = new CommandService(new CommandServiceConfig
        {
            LogLevel = LogSeverity.Info,
            CaseSensitiveCommands = false,
            SeparatorChar = '&',
        });

        logger = new LoggingService(client, commands);

        commandHandler = new CommandHandler(client, commands, services, logger);
    }

    public async Task RunAsync()
    {
        await commandHandler.InstallCommandsAsync().ConfigureAwait(false);

        await client.LoginAsync(TokenType.Bot, Environment.GetEnvironmentVariable("DiscordToken")).ConfigureAwait(false);
        await client.StartAsync().ConfigureAwait(false);
   }
}
```

And finally for the `CommandHandler.cs`, the place where the problems occur, I have
```
class CommandHandler
{
    private readonly DiscordSocketClient client;
    private readonly CommandService commands;
    private readonly IServiceProvider services;
    private readonly ILogger logger;

    public CommandHandler(DiscordSocketClient client, CommandService commands, IServiceProvider services, ILogger logger)
    {
        this.commands = commands;
        this.client = client;
        this.services = services;
        this.logger = logger;
    }

    public async Task InstallCommandsAsync()
    {
        client.MessageReceived += HandleCommandAsync;
        commands.CommandExecuted += OnCommandExecutedAsync;

        try
        {
            var moduleInfo = await commands.AddModulesAsync(assembly: Assembly.GetEntryAssembly(), services).ConfigureAwait(false);
        }
        catch(Exception ex)
        {
            await logger.LogAsync(new LogMessage(
                LogSeverity.Critical,
                "CommandExecution",
                $"Command modules failed to load: {ex.Message}.")
                );
        }
    }

    private async Task OnCommandExecutedAsync(Optional<CommandInfo> command, ICommandContext context, IResult result) { /.../ }

    private async Task HandleCommandAsync(SocketMessage messageParams)
    {
        var message = messageParams as SocketUserMessage;
        if (message == null) return;

        int argPos = 0;

         if (!(IsCommand(message, argPos) || IsTalkingToBot(message, client.CurrentUser, argPos)) ||
            message.Author.IsBot)
            return;

        var context = new SocketCommandContext(client, message);
        //  ** Returns the correct Modules/Commands
        var exeCommands = await commands.GetExecutableCommandsAsync(context, services);
        // *** Return Discord.Commands.CommandError.UnknownCommand
        var result = await commands.ExecuteAsync(context, argPos, services)
            .ConfigureAwait(false);
    }

    private static bool IsCommand(IUserMessage message, int argPosition) { /.../ }

    private static bool IsTalkingToBot(IUserMessage message, SocketSelfUser user, int argPosition) { /.../ }
}
```

It doesn't seem like I'm doing anything fancy. I'm not sure why the line at ** in `CommandHandler.cs` would work but *** would not.

**Comment by Hawxy** [comment]
> SeparatorChar = '&'

This is a relatively uncommon setting to change and might be the source of your problems. Was this intentional?

> as I'm definitely using host builder correctly.

The service collection should scaffold your entire dependency structure, and your bot shouldn't be starting up in the middle of service registration. `ConfigureAwait(false)` also doesn't do anything within this context. Your structure is a real mash of a more traditional bot structure and one using a host builder.

You might want to take a look at my package https://github.com/Hawxy/Discord.Addons.Hosting and the samples in the repo if you intend to stick with a hostbuilder.

**Comment by ghost** [comment]
Ah, you've made quite a nice couple simplifying extension! Much appreciated. Using `ConfigureDiscordHost` did help solve this issue.
