### ISSUE TITLE
Discord.net not working on windows 7

### ISSUE THREAD

**Issue by SDSHFSHFSHFHGS** [RogueException/Discord.Net#1582]
My bot don't online. I have windows 7, how to fix?

**Comment by Moonbase2004** [comment]
Discord.NET required at least Windows 8 or higher to run. This is because Windows 7 doesn't have the necessary websocket protocols.

**Comment by Still34** [comment]
Please refer to our [documentation](https://docs.stillu.cc) for platforms using Windows 7 or below.

**Comment by Liviu23** [comment]
@SDSHFSHFSHFHGS Did you use WebSocket4Net?
