### ISSUE TITLE
SocketException: No such host is known

### ISSUE THREAD

**Issue by OrbitMPGH** [RogueException/Discord.Net#1587]
Hello! Randomly tonight my bot died. When trying to start it back up it just instantly crashes on bootup. It looks like it can't log in to the bot as it can't connect to Discord. Anyone got a clue as to why?  Is this something discord.net related or is this something I have to fix locally? Here is the stacktrace:

![image](https://user-images.githubusercontent.com/22508498/86876342-ccd7e980-c0e4-11ea-8ea5-7a15136864a1.png)

**Comment by Still34** [comment]
Please make sure that your DNS settings on the server is properly set up and can resolve `discordapp.com`.

**Comment by OrbitMPGH** [comment]
It is now magically working, without me doing anything. I'm confused.
