### ISSUE TITLE
SetActivityAsync with custom status not working

### ISSUE THREAD

**Issue by gen-angry** [RogueException/Discord.Net#1590]
Hello,

I'm a bit of a novice with all this, having an issue with custom statuses with Discord.Net 2.2.0 (at least latest version on nuget as of this post).

When I try to set activity via `DiscordSocketClient.Ready` event

`SockClient.SetActivityAsync(new Game("with farts", ActivityType.Playing, ActivityProperties.None));`

it works fine for me. (Shows 'Playing with farts'). However, when I try to change the `ActivityType` enum to `CustomStatus`, it doesn't work - the status doesn't show at all.

From the message log:

```
2020-07-20 1:06:14 AM [   Debug] Gateway: GuildDownloader Stopped
2020-07-20 1:06:14 AM [   Debug] Gateway: Sent StatusUpdate
2020-07-20 1:06:14 AM [    Info] Gateway: Ready
```

so it's not throwing any error there. 

Have tried to attach it right after `StartAsync()` on the startup async task

`await SockClient.SetActivityAsync(new Game("with farts", ActivityType.CustomStatus, ActivityProperties.None)).ConfigureAwait(false);`

which does the same as above.

Not sure if I'm missing something or there's an issue with CustomStatus. The documentation doesn't have any of it and I can't seem to find any examples online.

Thank you :)

**Comment by TheNoodleMummy** [comment]
if im not mistaken bots cant have custom statuses and the enum prop is there to read users customs statuses 
for more question feel free to join the [discord](https://discord.gg/discord-api) and look for the #dotnet_discord-net

**Comment by SubZero0** [comment]
Like it was said above, bots can't use custom statuses.
