### ISSUE TITLE
[Req] Mention object on Server/Channel/User objects

### ISSUE THREAD

**Issue by Nikey646** [RogueException/Discord.Net#16]
Would make it a hell of a lot easier if the aforementioned objects have a .Mention property, even if it only calls the Mention class internally.

As it stands with the limited Documentation that is around this API, little things like the Mention class can be missed quite easily, if you are not familiar with the internet workings of this library.

```C#
// On the user object..
public string Mention {
	get { return Mention.User(this); }
}
```

**Comment by RogueException** [comment]
Sounds good to me - added and pushed to dev branch.

**Comment by Nikey646** [comment]
Tyvm :>
