### ISSUE TITLE
Crosspost throwing exception for new Community Discord news channel

### ISSUE THREAD

**Issue by fdsprod** [RogueException/Discord.Net#1605]
Hi,

I recently switched my discord to a Community Discord which gave us access to announcement channels 
![image](https://user-images.githubusercontent.com/1947295/89743276-61bc6280-da56-11ea-94cf-a89e1fe3e123.png)

I added the .CrosspostAsync call to my bot when posting news and it is throwing this exception here for the channel.   Is there a new channel type that needs to be added?  

        /// <inheritdoc />
        /// <exception cref="InvalidOperationException">This operation may only be called on a <see cref="SocketNewsChannel"/> channel.</exception>
        public async Task CrosspostAsync(RequestOptions options = null)
        {
            if (!(Channel is SocketNewsChannel))
            {
                throw new InvalidOperationException("Publishing (crossposting) is only valid in news channels.");
            }

            await MessageHelper.CrosspostAsync(this, Discord, options);
        }

My code is basically this 

                    var userMessage = await _socketChannel.SendMessageAsync(announceTo, embed: builder.Build());
                    
                    await userMessage.CrosspostAsync();

**Comment by SubZero0** [comment]
Could you post the exception?

**Comment by fdsprod** [comment]
I did it is the invalidoperationexception from the code above

**Comment by SubZero0** [comment]
No, you posted our code, not the exception (with the stacktrace).
Just to be sure you didn't confuse anything.

**Comment by LXGaming** [comment]
Encountered this issue myself, I believe it's due to `SendMessageAsync` returning a `RestUserMessage` even though the channel it's being sent to is a `SocketNewsChannel`.

Code:
```csharp
public static async Task ReadyAsync() {
    var channel = (SocketNewsChannel) _discordClient.GetChannel(CHANNEL_ID_HERE);
    var message = await channel.SendMessageAsync("Testing Discord.Net");
    await message.CrosspostAsync();
}
```

Exception:
```
System.InvalidOperationException: Publishing (crossposting) is only valid in news channels.
   at Discord.Rest.RestUserMessage.CrosspostAsync(RequestOptions options)
```
