### ISSUE TITLE
A warn command

### ISSUE THREAD

**Issue by anf** [RogueException/Discord.Net#1606]
A warn command that warns a user and logs it in the audit log, and also some other commands such as seeing user warnings and how many times for what reason, that would be nice.

**Comment by k-boyle** [comment]
You were literally just told in the dapi channel that it's not possible. 
![image](https://user-images.githubusercontent.com/17115277/89832509-5c930c80-db57-11ea-9b9c-533acdb41be1.png)

**Comment by AntiTcb** [comment]
The library intentionally doesn't come with any pre-configured commands. Anything you wish to have, you need to implement the functionality for your commands on your own.
