### ISSUE TITLE
Cannot Resolve Mention to Discord.IUser with The Correct Gateway Intents

### ISSUE THREAD

**Issue by JayAvenian** [RogueException/Discord.Net#1607]
![image](https://user-images.githubusercontent.com/69430011/90075094-9b959f00-dcca-11ea-8de8-eb6fc17752fb.png)

Just updated to the latest nightly. I had a command someone could pay another user. With the new update users with special characters in their mention cause the Discord.IUser parse to fail when converting from a mention.

**Comment by MarkusG** [comment]
Mentions are represented as `<@ID>` in the raw message format, so it's unlikely that a user's username would affect mention parsing. If the command was presented with the target user's username and discriminator without the @ symbol (i.e. `SomeUser#1234`), it might be a possibility. Could you include the exact message you send that makes the parsing fail?

**Comment by JayAvenian** [comment]
Sorry it looks like on the current nightly you can't parse any mentions to IUsers at all. It looks like when you use the gateway intents for users it bugs out.

The following gateway intents are what I have and should allow me to get the user in the tag if available:
GatewayIntents = GatewayIntents.GuildBans | GatewayIntents.GuildInvites | GatewayIntents.GuildMessages | GatewayIntents.Guilds | GatewayIntents.GuildMembers

**Comment by SubZero0** [comment]
Like it was said in discord, it's because the user isn't in the cache. The lib is working as intended and there's no issue here. You can get the user in other ways (rest, downloading, message mentions).
