### ISSUE TITLE
How do I run something when a use only uses the Group?

### ISSUE THREAD

**Issue by Azthenix** [RogueException/Discord.Net#1611]
How can I make my bot do something when a user tries to use a Group but not a specific command?

Like when a user sends `.music` instead of something like `.music play` where `music` is the Group.

**Comment by Azthenix** [comment]
Nevermind I figured it out.

I can just put
```
[Command]
public async Task method()
```

**Comment by jakedacatman** [comment]
or if you want you can also do `[Command("")]`
