### ISSUE TITLE
[Question] System.Exception: Server requested a reconnect

### ISSUE THREAD

**Issue by dakata1337** [RogueException/Discord.Net#1620]
Hello. I'm new to Discord.Net and I'm using a bot i downloaded from GitHub. The bot works fine but after ~30 minutes the bot is getting disconnected. Can anyone tell me why and is there any way for me to fix it? If you need more information ask me. Thanks!

This is the console:
```
05:39:17 [Info] Gateway: Connected
05:39:17 [Info] Gateway: Connected to testserver
05:39:17 [Info] Gateway: Connected to test
05:39:18 [Info] Gateway: Ready
06:08:38 [Warn] Gateway: System.Exception: Server requested a reconnect 
at Discord.ConnectionManager.<>c__DisplayClass29_0.<<StartAsync>b__0>d.MoveNext()
06:08:38 [Info] Gateway: Disconnecting
06:08:38 [Info] Gateway: Disconnected from testserver
06:08:38 [Info] Gateway: Disconnected from test
06:08:38 [Info] Gateway: Disconnected
06:08:39 [Info] Gateway: Connecting
06:08:40 [Info] Rest: GET gateway: 51.99 ms
06:08:41 [Warn] Gateway: Failed to resume previous session
06:08:41 [Info] Connected
06:08:42 [Info] Gateway: Connected to testserver
06:08:42 [Info] Gateway: Connected to test
```
*EDIT*: This happens with all bots i test.

**Comment by Anu6is** [comment]
Discord requested a reconnect and so the bot reconnected. There is no issue to be fixed there. There is however slight issue in the failure to resume the previous session. That can be fixed by updating your project to use the latest nightly version of Discord.Net

**Comment by dakata1337** [comment]
> Discord requested a reconnect and so the bot reconnected. There is no issue to be fixed there. There is however slight issue in the failure to resume the previous session. That can be fixed by updating your project to use the latest nightly version of Discord.Net

I am using Discord.Net v2.2.0 from NuGet. I don't see any other version.

**Comment by asmejkal** [comment]
Nighly builds are on MyGet, check the [README.md](https://github.com/discord-net/Discord.Net/blob/dev/README.md).

**Comment by Anu6is** [comment]
https://docs.stillu.cc/guides/getting_started/nightlies.html?tabs=vs
