### ISSUE TITLE
Create&Maintain OAuth2

### ISSUE THREAD

**Issue by JKamsker** [RogueException/Discord.Net#1625]
Hey,
I know this repo aims primarely on bots, but i found an unmaintained OAuth2 repo ([Here](https://github.com/RogueException/Discord.OAuth2)) which doesnt work on the newest netcore3.1.

A  pending [pull request](https://github.com/confessore/Discord.OAuth2) would fix this, but as i said, the maintainer hasnt done anything in years.

Integrating this rather simple repo (the forked version) in this one would propably resolve this issue.

**Comment by Emzi0767** [comment]
I would love to know the thought process that led you to post an issue on a completely different repo.

**Comment by Joe4evr** [comment]
Also, the reason that repo is no longer maintained is because there's a maintained package as part of [aspnet-contrib/AspNet.Security.OAuth.Providers](https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers).

**Comment by AntiTcb** [comment]
Have you considered forking that repo, merging the PR in your fork, and running with that?

Having said that, why did you post this issue on an entirely different repo? Closing.

**Comment by JKamsker** [comment]
> I would love to know the thought process that led you to post an issue on a completely different repo.
@Emzi0767 
Well, first of all, the name of the repo & the organisation is Discord.Net . It even states, that its "An unofficial .Net wrapper for the Discord API (http://discordapp.com)". If I'm not wrong, Discord OAuth2 is part of  Discord's api. The next logical thought is, that an organisation which claims that is "An unofficial .Net wrapper for the Discord API" should also implement their OAuth Api, because noone else does it. Atleast actively maintains a project which does that.



> Also, the reason that repo is no longer maintained is because there's a maintained package as part of aspnet-contrib/AspNet.Security.OAuth.Providers.

@Joe4evr 
Thank you. I did not know that. All my searches ended up in legacy code which didnt work anymore. The only thing that worked for me was the hidden PR that was unanswered for months.

> Have you considered forking that repo, merging the PR in your fork, and running with that?

@AntiTcb 
Yes, im currently running the code of the PR, but im not sure if everyone who searches for a solution finds it easily.


> Having said that, why did you post this issue on an entirely different repo? Closing.

@AntiTcb 
As i said, the original maintainer is inactive for years and wont answer any issues. The point was to find a new maintainer.
