### ISSUE TITLE
Parameter naming

### ISSUE THREAD

**Issue by AndyGybels** [RogueException/Discord.Net#1628]
Please consider using more user friendly names for parameters. 
Not just arg1, arg2 etc..
Documentation is good but self explaining code is even better.

**Comment by AntiTcb** [comment]
Have anything in particular you’d like to point out that could be renamed?

**Comment by AndyGybels** [comment]
Ok my bad it seems to be because they are all Func delegates, For example BaseSocketClientChannelUpdated.
Maybe its an idea to wrap the arguments, e.g. ClientChannelUpdatedArguments.

**Comment by SubZero0** [comment]
I'm sure there's no plan for changing this in v2, but you could suggest it in the v3 issue #1248
