### ISSUE TITLE
DiscordSocketClient.GetChannel() apparently not working properly

### ISSUE THREAD

**Issue by EmanueleSpadaro** [RogueException/Discord.Net#1629]
Hi guys,
I'm trying to develop a private bot that interacts only inside a specific text channel, but I can't seem to be able to create a valid SocketChannel instance by using something like this:
`var channel= client.GetChannel(12345678912345678);
foreach(var user in canale.Users)
{
Console.WriteLine(user.Username);
}`
It throws a NullObject exception everytime I try to access the given channel object properties.
Maybe I'm doing something wrong, thanks in advance.

**Comment by Anu6is** [comment]
If `GetChannel` returns null, then either your id is incorrect, or the client has not yet finished downloading data for the guild that channel belongs to. You need to wait for the ready event to fire before accessing any form of guild data from the `DiscordSocketClient`.

**Comment by EmanueleSpadaro** [comment]
You're right, thanks for the tip. Much appreciated!
