### ISSUE TITLE
SocketGuild.Roles is not updated

### ISSUE THREAD

**Issue by RheaAyase** [RogueException/Discord.Net#1630]
Similar to users not being updated in #1533, roles also seem to become out of sync when creating new ones.

**Comment by Xyphius** [comment]
I've noticed the same thing with SocketGuildUser. When a user is granted a role via AddRoleAsync(), the SocketGuildUser doesn't sync until a restart of the application.

**Comment by RheaAyase** [comment]
That requires MEMBERS intent - not what this issue is about.

**Comment by Xyphius** [comment]
> That requires MEMBERS intent - not what this issue is about.

Ah, you'll have to forgive me. I figured since both were out of sync involving roles they would be a similar / the same issue.

**Comment by RheaAyase** [comment]
It's not an issue though, make sure you have members intent enabled at https://discord.com/developers/applications
(and your bot is also setting it.)

**Comment by julius-gmeinder** [comment]
im having the same problem
