### ISSUE TITLE
CacheMode.AllowDownload is in fact ForceDownload

### ISSUE THREAD

**Issue by RheaAyase** [RogueException/Discord.Net#1631]
https://github.com/discord-net/Discord.Net/blob/dev/src/Discord.Net.WebSocket/Entities/Channels/SocketTextChannel.cs#L286
```
if (mode == CacheMode.AllowDownload)
    return await GetMessageAsync(id, options).ConfigureAwait(false);
else
    return GetCachedMessage(id);
```

..should really be:
```
IMessage msg = GetCachedMessage(id);
if (mode == CacheMode.AllowDownload && msg == null)
    msg = await GetMessageAsync(id, options).ConfigureAwait(false);
return msg;
```

...other such wrong implementations probably exist as well

**Comment by k-boyle** [comment]
Pretty sure cache mode isn't actually properly implemented anywhere

**Comment by RheaAyase** [comment]
Oh well...

**Comment by k-boyle** [comment]
But it'd probably be a BrEaKiNg ChAnGe to sort it all out

**Comment by RheaAyase** [comment]
Oh wow it's even worse the more I look into it... There is another method that's ... literally the same thing, except that it's not using GetCachedMessage wrapper, but accesses _messages directly and doesn't care about CacheMode :D

**Comment by k-boyle** [comment]
The trick to using dnet is to not read the source code

**Comment by RheaAyase** [comment]
So anyway I don't know how to actually title this issue given the more recent findings (that the method actually calls yet another one that does check cache first as well) - it's just awful but technically functioning? Perhaps that the Socket implementation is missing CacheMode alltogether. (Given you need to cast it to the IMessageChannel to get the other implementation.)

What is however missing on the topic of cache is adding a newly downloaded message into the cache.

**Comment by RheaAyase** [comment]
I'll be closing this issue as it doesn't reflect the actual problem, a new issue should be opened for that instead...
