### ISSUE TITLE
ABI instead of API

### ISSUE THREAD

**Issue by rk3141** [RogueException/Discord.Net#1632]
In `README.md`, instead of API there is ABI

**Comment by Izumemori** [comment]
And that is incorrect how?

**Comment by Joe4evr** [comment]
![](https://i.kym-cdn.com/entries/icons/original/000/026/618/ZEBxqIA.jpg)

**Comment by Still34** [comment]
ABI is intentional. https://stackoverflow.com/questions/2171177/what-is-an-application-binary-interface-abi
