### ISSUE TITLE
Culture problem with webhook token regex validation

### ISSUE THREAD

**Issue by serkanyazicioglu** [RogueException/Discord.Net#1636]
Hello,

Webhook url validation regex fails when used with various different cultures. You can basically add 'RegexOptions.CultureInvariant' to WebhookUrlRegex object to mitigate the issue.

`private static Regex WebhookUrlRegex = new Regex(@"^.*(discord|discordapp)\.com\/api\/webhooks\/([\d]+)\/([a-z0-9_-]+)$", RegexOptions.CultureInvariant | RegexOptions.Compiled | RegexOptions.IgnoreCase);`

Thanks...

**Comment by Starbors** [comment]
lol

**Comment by SubZero0** [comment]
Closing since #1637 was merged.
