### ISSUE TITLE
Problem with audio streaming

### ISSUE THREAD

**Issue by MrNatanael** [RogueException/Discord.Net#1648]
My bot stops playing audio after few seconds without any error, can it be a problem with my connection or with ffmpeg ?
I'm using youtube-dl to get a valid url from youtube and stream the audio.

Here is my code
```CSharp
public static async Task CreatePlayer(string url, IAudioClient voice)
{
    using (Process ffmpeg = Process.Start(new ProcessStartInfo
    {
        FileName = "ffmpeg",
        Arguments = $"-hide_banner -loglevel panic -i \"{url}\" -ac 2 -f s16le -ar 48000 pipe:1",
        UseShellExecute = false,
        RedirectStandardOutput = true
    }))
    {
        using (Stream output = ffmpeg.StandardOutput.BaseStream)
        {
            using (AudioOutStream audio = voice.CreatePCMStream(AudioApplication.Mixed))
            {
                try { await output.CopyToAsync(audio); }
                finally { await audio.FlushAsync(); }
             }
        }
    }
}
```

**Comment by jakedacatman** [comment]
Are you using `youtube-dl` to grab the raw audio stream URL? YouTube closes the connection after a little while and it does actually throw an error.

This is not a Discord.Net issue.

If you need an example implementation of audio streaming from YouTube I can send it here.

**Comment by MrNatanael** [comment]
I would be grateful if you could send an example.

**Comment by jakedacatman** [comment]
https://github.com/jakedacatman/donniebot/blob/audio-dev/services/audioservice.cs#L70

You basically download the audio into memory (this should happen before the stream is cut off); you can then pipe it in to ffmpeg.

Unfortunately, stock streams are not able to be written to and read from at the same time; this is why I used an external library to provide the SimplexStream.

**Comment by MrNatanael** [comment]
Thank you.
