### ISSUE TITLE
[Question] How to make Join Guild 

### ISSUE THREAD

**Issue by BeamNawapat** [RogueException/Discord.Net#1649]
when run this user then auto join guild?

**Comment by Anu6is** [comment]
Please add some actual details to your question (auto joining a guild really isn't a thing though).

**Comment by BeamNawapat** [comment]
Am such as 
When i place my token to run Discord.net 
when it Ready it will join guild my guild auto

**Comment by Anu6is** [comment]
You cannot auto join a guild. When you "run Discord.net" logging in and starting the client will simply connect to the Discord gateway and your bot will show as online in whatever guilds it already belongs to.

**Comment by BeamNawapat** [comment]
I mean Like this 
https://i.gyazo.com/5f9180bec4ce3687b63c00aaaba026cc.png
But make it with Discord.Net Join Guild Support

**Comment by Anu6is** [comment]
You can use OAuth to join a user to a guild. That's somewhat outside of of simply using Discord.Net

**Comment by TH3AL3X** [comment]
Go here: https://discord.com/developers/applications
1º Press your bot and copy the client ID 
2º Put the client ID inside of this and then press enter....
https://discord.com/oauth2/authorize?client_id= **YOUR CLIENT ID** &scope=bot&permissions=8

**Comment by SubZero0** [comment]
I'll assume the author of this issue found his answer since there were no updates since the first day.
