### ISSUE TITLE
[Question/Possible issue?] SetGameAsync() Not working.

### ISSUE THREAD

**Issue by ProjektCode** [RogueException/Discord.Net#1650]
```
Imports Discord
Imports Discord.WebSocket
Imports Discord.Net.Providers.WS4Net
Imports System.Windows.Forms
Imports System.Drawing
Imports System.Runtime.InteropServices
Imports System.Threading
Imports Discord.Commands

Public Module Main

    Private config As MasterConfig
    Private Client As DiscordSocketClient
    Private d_events As DiscordEvents
    Private commandHandle As CommandHandler

    Sub Main(args As String())

        RunBotASync.GetAwaiter.GetResult()

    End Sub

    Private Async Function RunBotASync() As Task
        Console.WriteLine("Now Loading Bot...")

        config = Await MasterConfig.LoadAsync

        Dim ClientConfig As New DiscordSocketConfig With {
                        .DefaultRetryMode = Discord.RetryMode.AlwaysRetry,
                        .LogLevel = LogSeverity.Info,
                        .WebSocketProvider = WS4NetProvider.Instance
                        }

        Client = New DiscordSocketClient(ClientConfig)
        d_events = New DiscordEvents(Client)
        commandHandle = New CommandHandler(config, Client)


        Await Client.LoginAsync(TokenType.Bot, config.token)
        Await Client.StartAsync()



        Await Task.Delay(Timeout.Infinite)
        Await Client.SetGameAsync("Giving Damage While Taking Damage | -help", ActivityType.Playing, ActivityProperties.None).ConfigureAwait(False)
    End Function

End Module
```
It could be just that I'm setting `SetGameAsync()` in the incorrect spot, or somewhere in my code is just not allowing it to work but it is not setting the game status. I tried to set it before and after `StartAsync()` but nothing. again probably me not putting it in the right place or am missing something that causes it not to work. I also tried to set it in the Main() sub but got errors. (I am pretty new to discord.net)

**Comment by 230Daniel** [comment]
You are trying to call SetGameAsync after your infinite delay (Await Task.Delay(Timeout.Infinite)), that would be why.

Also, my preference is to call SetGameAsync() on the Ready handler (add it using Client.Ready +=) because by that point you can be sure that the client is properly logged in.

I hope that helps!

**Comment by ProjektCode** [comment]
I'm new to coding discord.net. Where would I put this code you're talking about or how do I use it? I tried putting it in my discordevents class but still have no result. I'm not sure how to go about this. Sorry if I'm being really noob here. I tried to do Client.Ready += Client.SetGameAsync() in below `StartAsync()` but gives me an error saying `'Public Event Ready as Func(Of Task)' is an event, and cannot be called directly. Use a 'Raise Event' statement to raise an event`

**Comment by 230Daniel** [comment]
I'm not familiar with visual basic, but I assume that the library is used in the same way that it is in C#.

Create a method with return type async Task, and name it appropriately (eg. Client_Ready). The ready method takes no parameters.
Then add the method to Client.Ready using Client.Ready += Client_Ready (c#)
Finally, place your Client.SetGameAsync() line in that method. The method will be called once the client is logged in and has downloaded relevant caches.

**Comment by ProjektCode** [comment]
where am I placing `Client.Ready()`? Within my RunBotAysnc() Function? If so it still gives me the same [error](https://i.imgur.com/pN8a4R5.png). I also tried in my discord events but there I'm not entirely sure where to place it.

**Comment by 230Daniel** [comment]
Perhaps take a look at this example bot in visual basic:
https://github.com/Anu6is/DiscordBotExample/tree/master/Example1-Basic

**Comment by ProjektCode** [comment]
I'm not entirely sure what I need to look for?

**Comment by ProjektCode** [comment]
Nvm Found out how to do it. thanks

**Comment by SubZero0** [comment]
Closing since it's solved.
