### ISSUE TITLE
Could not Load File or Assembly 'Discord.net.WebSocket'

### ISSUE THREAD

**Issue by SukuyaZ** [RogueException/Discord.Net#1654]
The title explains it. Here's an image. 

![image](https://user-images.githubusercontent.com/71856517/97134433-71b91980-170a-11eb-849e-69ebe2e49db0.png)

**Comment by TH3AL3X** [comment]
You missed one library, called "Discord.Net.WebSocket" version 2.2.0.0, install it via Nuget, is the best way for install libraries

**Comment by SukuyaZ** [comment]
ah.

**Comment by iska69** [comment]
I have the same problem but I have everything installed that I need
