### ISSUE TITLE
Current TimeSpanTypeReader doesn't parse negative TimeSpan

### ISSUE THREAD

**Issue by SergeantSerk** [RogueException/Discord.Net#1657]
The current TimeSpanTypeReader doesn't parse negative TimeSpans like -1m30s, which is supported by players like lavaplayer/lavalink and Lavalink4NET.

**Comment by Anu6is** [comment]
Make your own TypeReader.

**Comment by SubZero0** [comment]
This is by design, so while it would be fine as an improvement it would require a major version bump to be changed since it could change the expected output if done. For now you can either run your own version with #1666 or create your own custom type reader as stated above.
