### ISSUE TITLE
DownloadAllUsersAsync Hangs

### ISSUE THREAD

**Issue by Torvin** [RogueException/Discord.Net#1660]
I'm experiencing #226 in `v2.2.0`. I wait for the `Ready` event to fire, then call to `await client.DownloadAllUsersAsync()` and it never returns.

**Comment by SubZero0** [comment]
You probably don't have the server members intent so it never downloads. Enable that privilege intent for your bot so you can request users by the gateway.
One of my plans is adding a timeout futurely just so it doesn't hang there when that's the case.

**Comment by Torvin** [comment]
Thank you, you are right! That fixed my issue and I didn't even have to use `DownloadAllUsersAsync`, `AlwaysDownloadUsers = true` was enough
