### ISSUE TITLE
Lock problem

### ISSUE THREAD

**Issue by panthernet** [RogueException/Discord.Net#1662]
Hi, I use latest dev version but it seems that the problem started to occur in my app with the older version too.
It locks on the DownloadUsersAsync() method of the SocketGuild object. Debug shows it hangs on the following code:

**await Task.WhenAll(batchTasks).ConfigureAwait(false);**  DiscordSocketClient.cs line 395

Not sure for how long it started to occur but some time ago it was functioning fine. No response, no error, just simple dead hang.
I need some advice with this one as currently it simply shuts down all the Discord operations.

**Comment by SubZero0** [comment]
Check #1660

**Comment by panthernet** [comment]
> Check #1660

Thanks, missed that issue. Have no deals with intents yet, have to find out what it is.
