### ISSUE TITLE
GuildMemberUpdated won't show global changes like username

### ISSUE THREAD

**Issue by hendrikdemir** [RogueException/Discord.Net#1664]
When using the `GuildMemberUpdated` event, global changes are simply being copied from the `after` value. For example, when someone changes their username, both the `before` and `after` value of the username will be the same.
![SocketGuidUser](https://i.imgur.com/oU4iix2.png)

However, this is not the case when using the `UserUpdated` event.
![SocketUser](https://i.imgur.com/EAwjzRn.png)

Is this something that is meant to be this way or am I missing something? It would be nice to know both the before and after values (when using the `GuildMemberUpdated` event) of global changes (e.g. username), so you can compare them in order to check if you should log it or not.

**Comment by Anu6is** [comment]
As far as I am aware, this is intentional. Like you said, `Username` is a global change, not a guild specific change. While the `GuildMemberUpdated` event does fire, the `UserUpdated` event is meant to track username changes.

**Comment by hendrikdemir** [comment]
I see and that also makes sense, but in that case, shouldn't global changes be excluded from the `GuildMemberUpdated` event? For instance, if my bot were to be in 500 servers, would that event be triggered 500 times?

**Comment by SubZero0** [comment]
What version are you using?

**Comment by hendrikdemir** [comment]
> What version are you using?

The latest stable, V2.2.0.

**Comment by SubZero0** [comment]
Ok, that happens because no checks happens in GuildMemberUpdate, so it's up to you to check if one happened and log it.
About the Username specifically, you should be using UserUpdated for that. If you don't have presence intents enabled (or don't want to use it for this), you will need to use the nightly version, that has #1623 included.

**Comment by hendrikdemir** [comment]
> Ok, that happens because no checks happens in GuildMemberUpdate, so it's up to you to check if one happened and log it.
> 
> About the Username specifically, you should be using UserUpdated for that. If you don't have presence intents enabled (or don't want to use it for this), you will need to use the nightly version, that has #1623 included.

Alright, thanks. I don't need it, but someone mentioned it and I wanted to know how it works. Thanks for the response!

**Comment by SubZero0** [comment]
Closing since this was already resolved by #1623 (global changes are in UserUpdated).
