### ISSUE TITLE
can't handle deleted messages

### ISSUE THREAD

**Issue by officialdakari** [RogueException/Discord.Net#1668]
I wanted to log deleted messages in my bot, but when I trying to get something from message object, it throws NullReferenceException.
Here my code:
```
private async Task _client_MessageDeleted(Cacheable<IMessage, ulong> msg, ISocketMessageChannel ch)
        {
            EmbedBuilder builderLog = new EmbedBuilder();
            IMessage message = await msg.GetOrDownloadAsync();
            IGuildUser user = (IGuildUser)message.Author; // NULLREFERENCE thrown
            ITextChannel channel = (ITextChannel)message.Channel;
            IGuild guild = user.Guild;
            builderLog.WithDescription($"Message sent by <@!{user.Id}> deleted in <#{channel.Id}>.\nMessage: {message.Content}");
            builderLog.WithColor(Color.Gold);
            if (Program.instance.servers.ContainsKey(guild.Id))
            {
                Program.Server obj = Program.instance.servers[guild.Id];
                if (obj.logchannel != 0)
                {
                    await ((ITextChannel)guild.GetChannelAsync(obj.logchannel)).SendMessageAsync(null, false, builderLog.Build());
                }
            }
        }
```

**Comment by SubZero0** [comment]
Messages deleted won't be available to download anymore, if it isn't in your cache, you can't retrieve it anymore.
So your `message` is null and that's what's throwing.

**Comment by followarcane** [comment]
> Messages deleted won't be available to download anymore, if it isn't in your cache, you can't retrieve it anymore.
> So your `message` is null and that's what's throwing.

Can we get a message which sent before bot online? Can i delete any message before bot online in that guild? I can hard code that message id too but it does not find it because its not cached

**Comment by SubZero0** [comment]
> Can we get a message which sent before bot online? Can i delete any message before bot online in that guild? I can hard code that message id too but it does not find it because its not cached

Yes, `GetMessageAsync` in the channel object that has it.
For these kind of questions, I recommend joining [Discord API](http://discord.gg/discord-api) and asking in #dotnet_discord-net

**Comment by xXBuilderBXx** [comment]
A wordaround for this is by setting the message cache size on the client.
Client = new DiscordSocketClient(new DiscordSocketConfig
{
    MessageCacheSize = 20,
});

**Comment by SubZero0** [comment]
Closing since the question was answered and no update was done by OP.
