### ISSUE TITLE
Can't find commands when on Windows

### ISSUE THREAD

**Issue by LeShaps** [RogueException/Discord.Net#1669]
I usually use Windows to develop and then push it to a Linux server to deploy.
But since yesterday, when I try to start and test it on Windows, he return an Unknown Command as result, if I push the exact same binaries on Linux and try, he can find theses without any kind of problems.
I've also tried on other PC's and with older versions of the code, without any success.

Any ideas of why, and / or how to fix this?

**Comment by FiniteReality** [comment]
Probably a locale issue. What's the value of the `LANG` environment variable on your Linux server, and what language is your Windows computer set to?

**Comment by LeShaps** [comment]
LANG on the server is set to C.UTF-8, my Windows computer is in French

**Comment by FiniteReality** [comment]
Try setting `LANG` to something like `fr_FR.UTF-8` and see if you can reproduce the issue

**Comment by LeShaps** [comment]
So, I tried by setting LANG like you said, but he was still working, on the other hand, I tried to set my Windows's system language to English, with no better results
