### ISSUE TITLE
Support for server icon format

### ISSUE THREAD

**Issue by ghost** [RogueException/Discord.Net#1684]
Well the title says it all and this is perfectly [possible](https://discord.com/developers/docs/reference#image-formatting-cdn-endpoints).  The id of a server icon is similar to that of a user, what I mean is that you don't have to look that far
 [L68](https://github.com/discord-net/Discord.Net/blob/dev/src/Discord.Net.Core/CDN.cs#L68) & [L162](https://github.com/discord-net/Discord.Net/blob/dev/src/Discord.Net.Core/CDN.cs#L162)

Thanks in advance.

**Comment by quinchs** [comment]
If you're talking about guild icons then they are already supported with `IconUrl` and `BannerUrl` on guilds.

If you're referring to guild specific user avatars those have been added in #1923 by using `GetGuildAvatarUrl` on a guild user
