### ISSUE TITLE
The input text has too many parameters. CommandService.executeasync

### ISSUE THREAD

**Issue by stockmansy** [RogueException/Discord.Net#1687]
Hi there, recently my bot has been acting up on one discord server in particular, other servers continue to work fine.

Most of the bot's functions work as expected, however sometimes certain commands error out with the message: 'The input text has too many parameters.'.

This error is thrown by the 'CommandService.executeasync' call.

The strange thing is that I can execute the same command, with the same functionality on another server for the same user, and it will work fine. (When debugging, locally, on the same code)

Another thing I've noticed is that the bot has issues removing roles from users automatically. (Might somehow be related)
I've checked permissions, even made the bot an admin briefly, but it didn't make a difference. In the role hierarchy it was also at the top.

I'm using the 2.2 version, didn't update anything in recent months, hope somebody can help, thanks.

-------
![error](https://user-images.githubusercontent.com/483904/99591303-e2441500-29ee-11eb-96fe-43642a756c6c.png)

**Comment by Anu6is** [comment]
That error is not related to permissions, it simply means the command is being called with invalid input. In particular, more arguments than the command method expects.

**Comment by stockmansy** [comment]
Hi, added some more info. Yes, the error message I understand, but what I don't understand is why I only get it on one discord server, and not the other one with the same commands. And these commands have worked for years at this point with my last update being a few months back. It only broke in recent weeks, so I suspect discord updated something on their end, or something changed on that particular server. I just can't figure out what.

**Comment by stockmansy** [comment]
Went into the source code, the issue had nothing to do with too many arguments. It had to do with the fact that I have 4 overloads for the same command (punish user, punish user and time, punish user time reason etc)
The one that was supposed to work was the one with user, but because the user wasn't cached due to the 'Privileged Gateway Intents' discord change, it didn't match, thus breaking everything.

I've now adjusted the settings of the bot and everything works again.

Source: https://discordapp.com/channels/81384788765712384/381871767846780928/770678489404932146

Big thank you to Zackattak01T on the Discord Api 'discord'
