### ISSUE TITLE
The example bots that are linked in the included samples are several years old and v1.x

### ISSUE THREAD

**Issue by MostHated** [RogueException/Discord.Net#1692]
Hey there,
    I went to take a look at the more "feature-filled" examples that were linked in the sample bots comments, but they were last updated in 2017, using D.Net v1.x. I just wanted to put it on someone's radar, as it would be great to have some similar but up to date projects like that to look over. 👍 

Thanks,
-MH

**Comment by csmir** [comment]
Will take this up further.

**Comment by Almighty-Shogun** [comment]
I have also noted that they aren't any good examples on how to work with Discord.NET and Dependency Injection. While I am doing it now, I had a thought it might be appreciated by others if there is an simple and basic example of it. 

I could make 2 samples for:
- Dependency Injection and text based commands like `!ping` and `.ping`
- Dependency Injection and the Interaction Framework to work with slash commands, components etc.

If this would be appreciated by the developers I could make those

**Comment by csmir** [comment]
I already have this nearly finished, I think it would not serve much use to add another. However, you can read my [discussion topic](https://github.com/discord-net/Discord.Net/discussions/2114) to have your own samples featured another way if you wish.

**Comment by MrCakeSlayer** [comment]
We have tons of samples and example bots that are using the latest features now. You can browse the repo for them and can also submit new sample bots via the link Rozen provided above.
