### ISSUE TITLE
Cant change the server cant save save settings after changing 

### ISSUE THREAD

**Issue by AadilFarhan29** [RogueException/Discord.Net#1693]
so after i change my server region it tells me to save settings and when I press that i loads again and says i need to save settings once more this happens in both web and app i even checked after disconnecting the bot 
![image](https://user-images.githubusercontent.com/74016678/100182974-471fd380-2ef7-11eb-9738-e4f2536019df.png)
![image](https://user-images.githubusercontent.com/74016678/100182997-5737b300-2ef7-11eb-8dff-72a6454019a2.png)
adn then again it goes back to the first pic
HELP plss

**Comment by AntiTcb** [comment]
This isn't a Discord.Net issue.
