### ISSUE TITLE
DiscordClient.UserJoined does not appear to be firing anymore

### ISSUE THREAD

**Issue by RononDex** [RogueException/Discord.Net#1698]
For some time now it appears, that the DiscordClient.UserJoined event is no longer firing.

I am registering my event like this:
```
            DiscordClient.UserJoined += OnUserJoined;
```
The event is defined as:
```
        protected Task OnUserJoined(SocketGuildUser user)
        {
            return Task.Factory.StartNew(() =>
            {
                 [...]
            });
        }
```

Other events fire fine. However this specific event does not appear to be firing when a new user joins a server the bot is on. It does not hit any debug points.

**Comment by Anu6is** [comment]
You should search other issues before creating new ones
https://github.com/discord-net/Discord.Net/issues/1675

**Comment by RononDex** [comment]
I searched open issues, but didn't find any related to my issue.
The issue you linked does not show any resolution, only "update to nightly builds", no reasoning what so ever. Updating to nightly builds would mean one can no longer use nuget packages or am I missing something?

**Comment by Anu6is** [comment]
**"intents are here, please do some light reading. to specify intents"** -- that is the answer. The nightly suggestion is due to the fact that you can only **specify** intents on the nightly. You don't need to specify them for the event to work. But you do need to enable them. The link provided also goes into more details

**Comment by RononDex** [comment]
I am sorry I dont understand what my issue has to do with intents.

**Comment by Anu6is** [comment]
...the event will not fire if the server member intent is not set.

**Comment by RononDex** [comment]
Ah I see. The issue you linked links to a discord channel / message which does not open for me (it appears like a dead link).

Thanks for the fast answer tho, will try with nightly builds then

**Comment by Anu6is** [comment]
the post exists still...discord being weird
Also, the main solution is **enable intents** the nightly is not specifically required.

**Comment by RononDex** [comment]
I guess you mean this by intents?
https://docs.stillu.cc/api/Discord.GatewayIntents.html

**Comment by Anu6is** [comment]
The nightly allows you to specify those yes, but like I said, intents needs to be enabled on the dev portal

**Comment by RononDex** [comment]
Just got it working by enabling the intents on the dev dashboard of the bot in discord.
So yeah nightly build isnt needed. Thanks for the help :)

**Comment by IS4Code** [comment]
In my case I also had to enable the intent when connecting:
```cs
var cfg = new DiscordSocketConfig();
cfg.GatewayIntents |= GatewayIntents.GuildMembers;
```

**Comment by Anu6is** [comment]
That is a more recent change where the intent needs to be specified in code as well.

**Comment by IS4Code** [comment]
> That is a more recent change where the intent needs to be specified in code as well.

Indeed, but searching for a solution for that had always lead me to allowing privileged intents, despite having them allowed the whole time, so hopefully someone will find the solution now.
