### ISSUE TITLE
GetMessagesAsync returning no messages

### ISSUE THREAD

**Issue by cooltrain7** [RogueException/Discord.Net#1705]
Hi all, I spotted my Clear command for messages stopped working a few weeks back and went looking for the source. I used to be able to just grab past messages pretty easily.

`var messages = await Context.Channel.GetMessagesAsync(50).FlattenAsync();`

Since then I've set a cache for messages (which it used to work without being set?), I've enabled the intents in the dev panel, and switched to using the nightly. But it still won't return messages.

Any ideas?

**Comment by SubZero0** [comment]
GetMessagesAsync is a REST request so it has nothing to do with intents, you might be having another issue (like missing permissions or didn't notice an error somewhere else).

**Comment by cooltrain7** [comment]
I feel like a bit of a moron... I should have checked the permissions before making this issue. Ah well you live and you learn ;)
