### ISSUE TITLE
This is actually still an issue, but the @everyone role has to be set to deny voice connect at the category level.

### ISSUE THREAD

**Issue by mikewojtkiewicz** [RogueException/Discord.Net#1707]
This is actually still an issue, but the @everyone role has to be set to deny voice connect at the category level.

_Originally posted by @mikewojtkiewicz in https://github.com/discord-net/Discord.Net/issues/426#issuecomment-740288103_

**Comment by SubZero0** [comment]
Deleting a channel is just a simple [http delete](https://discord.com/developers/docs/resources/channel#deleteclose-channel) (look at [DiscordRestApiClient.cs#L352](https://github.com/discord-net/Discord.Net/blob/dev/src/Discord.Net.Rest/DiscordRestApiClient.cs#L352)) so it shouldn't be related to the library itself.
