### ISSUE TITLE
ISocketMessageChannel.SendMessageAsync returns a RestUserMessage

### ISSUE THREAD

**Issue by ErwanTLG** [RogueException/Discord.Net#1709]
So when I found out about this, I was at first confused about why my code returned an error. Basically, it doesn't seem logic for the `SendMessageAsync` method to return a **REST**-based message when called from a **Web-Socket**-based channel. 
Is there a particular reason for doing this ?

This confuses me a lot because I am using almost only Web-Socket objects, but here I need to switch from the Web-Socket api to the REST api, even if I would like to stay with the Web-Socket api.

**Comment by k-boyle** [comment]
Because you're making a _rest_ request?

**Comment by ErwanTLG** [comment]
Isn't there a way to convert a `RestUserMessage` to a `SocketUserMessage` then ?

**Comment by Anu6is** [comment]
No, there probably isn't an actual case where you need to. If you are in a situation where you may have one or the other then just use the shared IUserMessage interface

**Comment by ErwanTLG** [comment]
Okay, thanks for the info
