### ISSUE TITLE
DiscordSocketClient fails to reconnect due to deadlock

### ISSUE THREAD

**Issue by Anonbun** [RogueException/Discord.Net#171]
The DiscordSocketClient hangs after WebSocketClosedException is thrown with the message, `The server sent close 1000: ""`. After the exception is thrown, StartReconnectAsync is called from the ApiClient.Disconnected event. However, _reconnectTask is not null, therefore StartReconnectAsync returns early. The issue is _reconnectTask doesn't proceed because a second exception is thrown in the task, ArgumentNullException. The stack trace is as follows:
```
System.ArgumentNullException: Value cannot be null.
Parameter name: exception
   at System.Threading.Tasks.TaskCompletionSource`1.TrySetException(Exception exception)
   at Discord.WebSocket.DiscordSocketClient.<DisconnectAsync>d__68.MoveNext() in \Discord.Net\WebSocket\DiscordSocketClient.cs:line 196
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Discord.WebSocket.DiscordSocketClient.<ReconnectInternalAsync>d__71.MoveNext() in \Discord.Net\WebSocket\DiscordSocketClient.cs:line 273
```

It says that DisconnectAsync is what threw the exception after ReconnectInternalAsync called it. DisconnectAsync calls TrySetException while the passed exception is null. The issue occurs when _connectTask is not null. I'm not entirely sure why _connectTask needs it exception set in DisconnectAsync, but I'm pretty sure the solution is to add a simple null check at the beginning of the if statement.

Edit: Looking at the problem again the better solution might be to have ReconnectInternalAsync call DisconnectInternalAsync directly, bypassing DisconnectAsync. Alternatively, DisconnectAsync() could have it's signature include a default bool parameter set to false. Then ReconnectInternalAsync could call DisconnectAsync(true). Any of these would work, though I'm more in favor of ReconnectInternalAsync calling DisconnectInternalAsync.

**Comment by khionu** [comment]
When was the last time you pulled? Commits are frequent, you could easily be 50 behind if you haven't pulled in 4-5 days.

**Comment by RogueException** [comment]
I assume this is BunBun from the Discord channel, right? The code hasn't been touched since the last time we talked, so I'll look into it when I get a chance.

**Comment by Anonbun** [comment]
Yes, I'm BunBun from Discord. If I can ask you, what is the purpose of setting the exception of or canceling _connectTask?

**Comment by RogueException** [comment]
Did we ever manage to fix this?

**Comment by RogueException** [comment]
A few people are still reporting issues but cant repro - postponed until we can. Anyone with more info, please post it here.

**Comment by RogueException** [comment]
Managed to repro this on my production server

**Comment by RogueException** [comment]
I've been unable to repro this after the last wave of websocket fixes. Marking this as solved unless we see it happen again after Beta 1's release.
