### ISSUE TITLE
Streaming status not working

### ISSUE THREAD

**Issue by Mijuri** [RogueException/Discord.Net#1712]
The status doesnt show that stream is live tried with multiple programs to name a few OBS, Xsplit, GeForce Experiance

**Comment by sudo-gab** [comment]
??? discord.net doesn't automatically detect programs that are running, as opposed to the official client.

if you want streaming status, use [DiscordSocketClient#SetGameAsync](https://docs.stillu.cc/api/Discord.WebSocket.DiscordSocketClient.html#Discord_WebSocket_DiscordSocketClient_SetGameAsync_System_String_System_String_Discord_ActivityType_)

**Comment by SubZero0** [comment]
Like cryy said, use SetGameAsync (or SetActivityAsync).
