### ISSUE TITLE
Get user's custom name on a server

### ISSUE THREAD

**Issue by TheAirBlow** [RogueException/Discord.Net#1715]
Hey, currently I am trying to create a bot that will prevent from using special characters (@!#$, etc.)
I can't find how to get user's custom name on a server (I'm using SocketGuild user, not SocketUser, cuz I need the guild)
Is it even possible within Discord API? If yes, how I can get user's custom name on a server?

**Comment by Anu6is** [comment]
The `Nickname` property

**Comment by TheAirBlow** [comment]
I alredy found it, sorry
