### ISSUE TITLE
Support discord slash commands

### ISSUE THREAD

**Issue by LazyBoot** [RogueException/Discord.Net#1716]
discord is rolling out support for slash commands, would be nice if the lib could support those at some point

https://discord.com/developers/docs/interactions/slash-commands

**Comment by quinchs** [comment]
Working on a pull request right now, Stay tuned!

**Comment by Pdzly** [comment]
I will wait for that :)

**Comment by TraceLD** [comment]
Any ETA on this?

**Comment by quinchs** [comment]
Up to the reviewers

**Comment by ohkriss** [comment]
Still work in progress? Is it possible to contribute?

**Comment by quinchs** [comment]
The underlying support for it is 95% done in #1717 while a slash command service is being written in #1733, I'd recommend checking out each pull and asking about how you can help there

**Comment by viveksh1** [comment]
@quinchs What is the progress on this? Has it completed yet?

**Comment by quinchs** [comment]
> @quinchs What is the progress on this? Has it completed yet?

The progress can be checked In #1717

**Comment by viveksh1** [comment]
> > @quinchs What is the progress on this? Has it completed yet?
> 
> The progress can be checked In #1717

@quinchs Do slash commands work yet? Can I implement them into my bot?

**Comment by quinchs** [comment]
@VladPutinEu yes.. you can see what is implemented on #1717..

**Comment by ghost** [comment]
are slash commands still under development in this lib?

**Comment by christopherfowers** [comment]
> are slash commands still under development in this lib?

The progress can be checked In [#1717](https://github.com/discord-net/Discord.Net/pull/1717)

**Comment by leocb** [comment]
Awesome work! Is there a documentation or example project we can use to referencce these new features?

**Comment by MrCakeSlayer** [comment]
This has now been implemented via the merged labs PR (#1923)
