### ISSUE TITLE
I couldn't get the list of users

### ISSUE THREAD

**Issue by mboukhlouf** [RogueException/Discord.Net#1718]
I tried everything. I tried using the AlwaysDownloadUsers property set to true in the DiscordSocketConfig. I tried using the event GuildMembersDownloaded, and it was never called. When I use the method DownloadUsersAsync, it gets stuck at it.

.NET Core 3.1

**Comment by M-Boukhlouf** [comment]
I just found out that there is an error when trying to download the users: A Ready handler is blocking the gateway task.

**Comment by SubZero0** [comment]
If DownloadUsersAsync is stuck, you are either calling it inside another gateway event or don't have the Guild Member intent enabled. Check https://github.com/discord-net/Discord.Net/issues/1679#issuecomment-727843325 for other possible reasons.

**Comment by mboukhlouf** [comment]
> If DownloadUsersAsync is stuck, you are either calling it inside another gateway event or don't have the Guild Member intent enabled. Check https://github.com/discord-net/Discord.Net/issues/1679#issuecomment-727843325 for other possible reasons.

That is correct. It's the intent. But even though I added the member intent in the Bot settings, I found out that it should be enabled from the application as well. But I didn't find anything about it in the current release.
I used the nightly release of DSharpPlus. It had intents added, and it worked.

**Comment by SubZero0** [comment]
Closing since you got your solution.
