### ISSUE TITLE
 discord.foxbot.me  Error 522 

### ISSUE THREAD

**Issue by MostHated** [RogueException/Discord.Net#1719]
When attempting to look at the documentation, I keep getting a 522 error. Is there a known issue currently?

![](https://i.imgur.com/DPNnEGw.png)

**Comment by TheNoodleMummy** [comment]
i guess the host is having some issues in the meantime (or always) you can use https://docs.stillu.cc/ this is a latest verison of docs or join the discordapi guild and join the #dotnet_discord-net channel to ask more

**Comment by MostHated** [comment]
Ah, great, thank you. I appreciate it.

**Comment by Still34** [comment]
Might update the docs links - will have to talk to @foxbot about that.

**Comment by Still34** [comment]
Closed via https://github.com/discord-net/Discord.Net/commit/accd3510dfeb64623491580ae2c47fbc815c7da2

**Comment by KatPurpy** [comment]
The host is still down

**Comment by Still34** [comment]
Yes, which is why a nightly link is available.

**Comment by Nyefan** [comment]
When forcing an attempt to connect to the host by going to `http://discord.foxbot.me`, it redirects to a site that attempts to install malware.  Can the link be removed at least until that is resolved?
