### ISSUE TITLE
PreConditions for Commands

### ISSUE THREAD

**Issue by khionu** [RogueException/Discord.Net#172]
What we have already agreed on:
- To provide a Levels system, and a replacement for `IPermissionChecker`s

What I would recommend:
- Having the checks be done before `CommandService.Execute`, not as a part of, so Users have flexibility in that regards. Maybe as a part of `CommandService.Search`?
- Making use of our DI, again, for the IPermissionChecker's, providing `IMessage` and `IDependencyMap`

**Comment by Joe4evr** [comment]
Question: Will there be a built-in `help` command again, and if so, a way to hide certain commands from it?

Also, it seems that "[precondition](https://en.wiktionary.org/wiki/precondition)" is a single word (no hyphen or anything), so I would suggest to have a lower-case 'c' as is convention.

**Comment by DigiTechs** [comment]
I say that we introduce another attribute, similar to MVC; AuthorizeAttribute. This attribute would have a get/set property for level required which the commands system will detect and honor.

I'm thinking it would look something like this:

```cs
class AuthorizeAttribute : Attribute
{
    public int MinLevel { get; set; }
}
```

Another option would be to have an attribute ('FilterAttribute'? Any other names?) which developers create custom attributes from to add custom 'preconditions'. The attribute could look something like this:

```cs
class FilterAttribute : Attribute
{
    public void OnCommandExecuting(CommandExecutionContext context)
    {
        // something here
        // set context.Handled = true to ignore command
    }
}
```

As for the help command, I believe that should belong in its own issue as it is not entirely related to preconditions.

**Comment by Joe4evr** [comment]
While an Attribute would be consistent with the design of 1.0 Commands, aren't those entirely limited to static content, because they get compiled as metadata? That would preclude any kind of runtime checks.

> As for the help command, I believe that should belong in its own issue as it is not entirely related to preconditions.

Maybe so, but the built-in help command in 0.x was pretty smart in that, if a command was hidden or a check failed, it wouldn't be displayed in the list to the user. I think that's a highly desirable feature, and there should at least be some consideration to make the same behavior *possible*, if not for a built-in command, then for bot authors who may want to roll their own `help`.

**Comment by DigiTechs** [comment]
> While an Attribute would be consistent with the design of 1.0 Commands, aren't those entirely limited to static content, because they get compiled as metadata? That would preclude any kind of runtime checks.

ASP.NET uses attributes for stuff like this; so it is definitely possible. The code would look something like this:

```cs
var ctx = new CommandExecutionContext();
var attrs = method.GetCustomAttributes<FilterAttribute>();
foreach (var attr in attrs)
{
    attr.OnCommandExecuting(ctx);
}

if (ctx.Handled)
    return;
```

As for your help command, we could provide an addon to provide a help command which respects these attributes. An extension method for the CommandService ('UserMeetsPermissionsRequirements') could be added to make this easier.
