### ISSUE TITLE
GuildMemberUpdated event not fired on status change

### ISSUE THREAD

**Issue by michael-klfsh** [RogueException/Discord.Net#1723]
I notice that the GuildMemberUpdated event isnt fired on status change. There is a Issue #1505 pointing out the behavior but with no comment on the issue. I couldnt find any documentation of this new behavior.
Is it fixed? And is there an other event to catch status changes?

**Comment by Anu6is** [comment]
The issue you linked is unrelated. Your issue is most likely because you didn't enable server member intents for your bot on the discord developer portal

**Comment by michael-klfsh** [comment]
Oh, yes you are right. Thank you
