### ISSUE TITLE
NuGet packages are out of date

### ISSUE THREAD

**Issue by Madpeterz** [RogueException/Discord.Net#1725]
https://www.nuget.org/packages/Discord.Net.WebSocket
https://www.nuget.org/packages/Discord.Net.Webhook

both last updated 8 months ago

related issues for me (Will update as I go)
https://github.com/discord-net/Discord.Net/pull/1551

**Comment by Anu6is** [comment]
Use the [nightly](https://docs.stillu.cc/guides/getting_started/nightlies.html#installing-with-myget-recommended)

**Comment by Still34** [comment]
The nightly has all the latest changes. We only push a new revision to stable when deemed appropriate.

**Comment by Madpeterz** [comment]
Related: https://github.com/discord-net/Discord.Net/issues/1568
