### ISSUE TITLE
meta: Change nuget releases 

### ISSUE THREAD

**Issue by Madpeterz** [RogueException/Discord.Net#1728]
currently the "stable" nuget gets updated when someone "feels" like it is stable.
this has left it not updated in over 8 months.

my suggestion is as follows:
1: at the start of the month push a updated version to nuget
2: the version code for these will be marked as -alpha
3: the version code will increase the current stable patch value by one

for example  the current non dev stable version is 2.2.*
and this update would be the 5th monthly update the version tagged would be
2.2.5-alpha

we ignore the patch number for stable for the monthly -alpha builds

| Stable |  Monthly |
|--|--|
|2.2.0  | 2.2.0-alpha |
|- | 2.2.1-alpha |
| - | 2.2.2-alpha |
|-  | 2.2.3-alpha |
| 2.2.1 | 2.2.4-alpha |
| - | 2.2.5-alpha |
| 2.3.0 | 2.3.0-alpha |
| - | 2.3.1-alpha |
| - | 2.3.2-alpha |
   

if you want the newest and most up-to date you can still use the nightly myget

Pros:
Nuget gets updated more often with pre-release versions
No need to add a 2nd nuget source and update your docker build to support that.

Cons:
Have to tag stuff.
Only updating the minor tag for the alphas does not correctly signal breaking changes.

**Comment by Emzi0767** [comment]
Hello, [I used Google for you](https://docs.stillu.cc/guides/getting_started/nightlies.html?tabs=vs).

**Comment by Madpeterz** [comment]
Thanks for using google for me when I did not ask adding nothing

**Comment by Madpeterz** [comment]
> Hello, [I used Google for you](https://docs.stillu.cc/guides/getting_started/nightlies.html?tabs=vs).
"if you want the newest and most up-to date you can still use the nightly myget"
thanks for the super helpful comment.

**Comment by Madpeterz** [comment]
> Hello, [I used Google for you](https://docs.stillu.cc/guides/getting_started/nightlies.html?tabs=vs).

"if you want the newest and most up-to date you can still use the nightly myget"

**Comment by liny-fox** [comment]
Saying "just use the nightlies" is frankly not acceptable to some that dont want the bleeding edge with all the bugs and having to deal with constant updates to fix said bugs and hoping new things dont break as well.

**Comment by FiniteReality** [comment]
> Saying "just use the nightlies" is frankly not acceptable to some that dont want the bleeding edge with all the bugs and having to deal with constant updates to fix said bugs and hoping new things dont break as well.

You're always welcome to use DSharpPlus. Honestly, I'd probably recommend it at this point. Discord.Net is effectively dead, as much as *some people* will try to claim it's not.

**Comment by Quahu** [comment]
> Saying "just use the nightlies" is frankly not acceptable to some that dont want the bleeding edge with all the bugs and having to deal with constant updates to fix said bugs and hoping new things dont break as well.

I mean, if you're not ready for said bleeding edge you're not really ready to develop for Discord itself which in a nutshell is constant changes and updates while `hoping new things dont break as well`. You won't find a library that doesn't constantly either break or push out new releases preemptively and whether or not you label it as nightly or stable builds you'll end up with the same thing.

**Comment by SubZero0** [comment]
> You're always welcome to use DSharpPlus. Honestly, I'd probably recommend it at this point. Discord.Net is effectively dead, as much as _some people_ will try to claim it's not.

I fail to see how it's dead considering the amount of work done by me, Still, and other contributors to put Discord.Net mostly up to date. The only missing features in my list are templates and new webhook endpoints. There's a few things that could get some love too like voice and commands but it's not dead.

The only reason there's isn't a new nuget package, it's because only one person, foxbot, can push them afaik and for some reason he still didn't.

**Comment by FiniteReality** [comment]
That's why I consider it dead. A maintainer who doesn't maintain means that the project is effectively dead in the water.

**Comment by SubZero0** [comment]
The project is still maintained, there's more than one maintainer thanks to it being open-source. This repo is the project, not the nuget, and it keeps being updated and, while not optimal, there's still plenty of releases in the MyGet.

I won't keep debating about it, I'm sure I made my point clear. I'll try to reach fox to see if he can push 2.3 to NuGet.

**Comment by liny-fox** [comment]
Maybe also see if nuget has the ability to have multiple maintainers for it (surely it must), and set add to it the same list of people that have push access to the main repo? Then your not waiting on one point.

**Comment by byBlurr** [comment]
NuGet has organisations to allow packages to be published as teams or groups. Or people can be added to a package as an owner, but this gives them full control over the package

**Comment by Madpeterz** [comment]
Closing the issue, its been almost 6 months.
