### ISSUE TITLE
Unable to retrieve information about deleted message from MessageDeleted event

### ISSUE THREAD

**Issue by Xeevis** [RogueException/Discord.Net#173]
For logging purposes I'd like to retrieve author/content of the deleted message. But IMessage optional parameter appears to be always null, this line is never reached:

https://github.com/RogueException/Discord.Net/blob/dev/src/Discord.Net/WebSocket/DiscordSocketClient.cs#L1253

**Comment by khionu** [comment]
I'll take a look today, try to repro

**Comment by Xeevis** [comment]
```csharp
public async Task Run()
{
    client = new DiscordSocketClient(new DiscordSocketConfig { LogLevel = LogSeverity.Verbose });

    client.MessageDeleted += async (id, msg) =>
    {
        await Console.Out.WriteLineAsync($"Message present: {msg.IsSpecified}"); // Always returns False
    };

    client.Log += async (message) => await Console.Out.WriteLineAsync($"[{message.Severity}] {message.Source} -> {message.Message}");

    await client.LoginAsync(...);
    await client.ConnectAsync();

    Console.Read();
}
```

**Comment by khionu** [comment]
I traced the issue. Can repro.

**Comment by khionu** [comment]
Non issue, found the reason: if the message isn't cached, it won't have anything but what Discord sends, which is very limited.
