### ISSUE TITLE
Feature: Interfacing the existing objects

### ISSUE THREAD

**Issue by jamesreiati** [RogueException/Discord.Net#1730]
I've been utilizing the interfaces in my project so that I can unit test and do offline development with a console-based implementation. I'm only able to use a slimmed down version of the entire API because of how little the interfaces expose. It looks like v3 was going in this direction, and I was curious if there was any appetite for doing this earlier than whenever v3 releases.

**Comment by SubZero0** [comment]
I don't there's any plans on changing the interfaces and breaking changes wouldn't be accepted so doing it would need to be done carefully. What do you have in mind specifically?

**Comment by Tdue21** [comment]
I know it a bit of a drag, but you could just write your own client wrapper, which implements the interface you want. 
That way, you can mock the client to your heart's content. 
And not break the API ;)

**Comment by jamesreiati** [comment]
When I get a moment, I'll do a little research into if this could be done in a purely additive way. Otherwise, yeah I think making personal wrappers is my only choice.
