### ISSUE TITLE
Pings returns null

### ISSUE THREAD

**Issue by Citrom67** [RogueException/Discord.Net#1732]
Hello, after a few months, I've noticed that many of my commands broke simply because a discord.net update I think.
There are commands in my bot that you could ping other people for, but every time you ping them, it returns with an error, saying that the user is not found.
I have both intent enabled because I've read on other discussions that you need that, but nothing is changed

  ```      
        [Command("avatar")]
        [Alias("a", "av")]
        [RequireBotPermission(GuildPermission.SendMessages)]
        public async Task SendAvatar(SocketUser user = null)
        {
            if (user == null)
            {
                user = Context.User;
            }

            embed.WithImageUrl(user.GetAvatarUrl(ImageFormat.Auto, 1024));
            embed.WithAuthor(Context.User.Username ,Context.Client.CurrentUser.GetAvatarUrl());
            embed.WithCurrentTimestamp();

            await ReplyAsync("", false, embed.Build());


        }
```

A simple example is this, every time I try to run it without ping it runs just fine and returns the sender's avatar, but when I ping anyone it returns with this error message
> ObjectNotFound
> User not found.

**Comment by zbroderson** [comment]
This is not the result of a discord.net update.  This is the result of the intents.  The user is not in the cache so the user type reader does not find it.

**Comment by Citrom67** [comment]
And how could I fix it?
I'm kinda new to these things so I have no idea

**Comment by zbroderson** [comment]
Usually specifying the intents on the discord developer portal and then downloading users on startup will do the trick.  Feel free to ask in the discord.net support channel in https://discord.gg/discord-api

**Comment by Citrom67** [comment]
Alrighty, thank you
