### ISSUE TITLE
Why can't something like this be used to make the api simpler to use

### ISSUE THREAD

**Issue by Shadowblitz16** [RogueException/Discord.Net#1734]
Here is a example of how simple discord.py is..

```python
client         = commands.Bot(command_prefix="!")

@client.event
async def on_ready():
    print("Bot is ready.")

@client.event
async def on_member_join(member):
    print(f'{member} has joined a server.')


@client.event
async def on_member_remove(member):
    print(f'{member} has left a server.')

@client.command() #easy to do
async def clear(ctx, amount: int):
    #if (ctx.message.author.permissions_in(ctx.message.channel).):
    await ctx.channel.purge(limit=amount+1)

client.run('abcdefghijklmnopqrstuvwxyz0123456789')
```

If not can discord.net be made to work like this?

I also like the fact that you don't need to create a new object to specify configuration settings as you can set it right in the constructor.

**EDIT** My bad I should provide how it would look in C#.
```cs

public class MyBot : DiscordBot
{
    public override void OnRun()
    { 
        //registers the built in CommandModule no need to code it from scratch
        var module = new CommandModule(this, Prefix: "!");
        
        //Register events
        Ready       += OnReady;
        MemberJoin  += OnMemberJoin;
        MemberLeave += OnMemberLeave;

        //Blocking
        Connect('abcdefghijklmnopqrstuvwxyz0123456789');



        //Non blocking
        //client.RunAsync('abcdefghijklmnopqrstuvwxyz0123456789');
        //...
    }

    private async void OnReady()
    {
        //Write info when bot connects
        Console.Writeline("Bot is ready.");
    }

    private async void OnMemberJoin(IMember member)
    { 
        //print member has joined
        Console.Writeline(Member.ToString() + " has joined");
    }

    private async void OnMemberLeave(IMember member)
    {
        //print member has left
        Console.Writeline(Member.ToString() + " has left");
    }

    [Command] //doesn't do anything if a command module isn't registered
    private async void Clear(IContext ctx, int amount=0)
    {
          await ctx.Channel.Purge(limit: amount+1);
    }
}

public static void Main(string[] args)
{
    //static accesser
    MyBot.Run();
}

```

**Comment by TheHeartOfFire** [comment]
My process is probably hot garbage, but it seems to be identical to what you're looking for. Here's what i'm using in my bots.

```
private static void Main(string[] args)
         => new Program().MainAsync().GetAwaiter().GetResult();

        private async Task MainAsync()
        {
            await PersistentData.Constructor();
            var Config = PersistentData.Data.Config;
            Token = Config.Token;
            Game = Config.Game;
            Prefix = Config.CommandPrefix;

            Client = new DiscordSocketClient(new DiscordSocketConfig
            {
                LogLevel = LogSeverity.Verbose
            });

            Commands = new CommandService(new CommandServiceConfig
            {
                CaseSensitiveCommands = false,
                DefaultRunMode = RunMode.Async,
                LogLevel = LogSeverity.Debug
            });

            Service = new ServiceCollection()
                .AddSingleton(Client)
                .AddSingleton(Commands)
                .BuildServiceProvider();

            await Commands.AddModulesAsync(Assembly.GetEntryAssembly(), Service);
            Client.MessageReceived += Client_MessageReceived;
            Client.Ready += Client_Ready;
            Client.Log += Client_Log;
            Client.ReactionAdded += Client_ReactionAdded;
            Client.ReactionRemoved += Client_ReactionRemoved;
            Client.JoinedGuild += Client_JoinedGuild;
            Client.LeftGuild += Client_LeftGuild;
            Client.UserJoined += Client_UserJoined;
            Client.UserLeft += Client_UserLeft;
            await Client.LoginAsync(TokenType.Bot, Token);
            await Client.StartAsync();
            ModuleManager.InitializeModules();
            await Task.Delay(-1);
        }
```

**Comment by TheHeartOfFire** [comment]
I may have jumped the gun on my response here but what exactly are you trying to do? It seemed like you were just trying to register events which is certainly doable. If i seem like a noob i am so please excuse me if i'm being naive.

**Comment by Shadowblitz16** [comment]
Mine is more of why can't I do the following?
- use named/optional arguments instead of configs.
- register modules by creating a new one and passing the bot
- allowing passing token or file with token directly to a connection method
- using attributes to register command and command parameter info

it really has nothing to do with oop but simplification

**Comment by SubZero0** [comment]
> * use named/optional arguments instead of configs.

Adding a property to a class won't break previous versions, unlike a new argument.
You can easily do something as `new DiscordSocketClient(new DiscordSocketConfig { SomeProperty = someValue })`.

> * register modules by creating a new one and passing the bot

This isn't that much different. It's just decoupled to not make Discord.Commands required (you can choose to use another solution instead).
`await commandService.AddModulesAsync(Assembly.GetEntryAssembly(), null);` would register all valid commands and modules in the same assembly.

> * allowing passing token or file with token directly to a connection method

You can already pass a `string` to `LoginAsync` so it's basically writing the token directly or using something like `System.IO.File.ReadAllText("token.txt")` for a file.

> * using attributes to register command and command parameter info

Not sure if I misunderstod but this is done by adding `[Command("command")]` to a method. The only requirement is being inside a public class that inherits `ModuleBase`.

---------

It would be possible to "translate" your python bot to:
```cs
var client = new DiscordSocketClient();

client.Ready += ()
    => Console.Out.WriteLineAsync("Bot is ready.");

client.UserJoined += (user)
    => Console.Out.WriteLineAsync($"{user} has joined a server.");

client.UserLeft += (user)
    => Console.Out.WriteLineAsync($"{user} has left a server.");

var commandService = new CommandService();
await commandService.AddModulesAsync(Assembly.GetEntryAssembly(), null); // register commands
client.MessageReceived += (message) // execute them
    => message is SocketUserMessage userMessasge && message.Content.StartsWith('!') ? commandService.ExecuteAsync(new SocketCommandContext(client, userMessasge), 1, null) : Task.CompletedTask;

await client.LoginAsync(TokenType.Bot, "token"); // or something like `System.IO.File.ReadAllText("token.txt")` for text
await client.StartAsync();
await Task.Delay(-1);

public class Commands : ModuleBase
{
    [Command("cmd")]
    public Task CommandAsync(int amount = 0)
        => Context.Channel.SendMessageAsync($"Amount: {amount}");
}
```
\* For people reading this issue: don't copy this since I made it as simple as possible. The guide in the documentation provides better examples and explains them.

**Comment by Shadowblitz16** [comment]
> > * use named/optional arguments instead of configs.
> 
> Adding a property to a class won't break previous versions, unlike a new argument.
> You can easily do something as `new DiscordSocketClient(new DiscordSocketConfig { SomeProperty = someValue })`.

This could be a overload.

> 
> > * register modules by creating a new one and passing the bot
> 
> This isn't that much different. It's just decoupled to not make Discord.Commands required (you can choose to use another solution instead).
> `await commandService.AddModulesAsync(Assembly.GetEntryAssembly(), null);` would register all valid commands and modules in the same assembly.

its still decoupled since a CommandModuleBase could keep track of the client and the commands
> 
> > * allowing passing token or file with token directly to a connection method
> 
> You can already pass a `string` to `LoginAsync` so it's basically writing the token directly or using something like `System.IO.File.ReadAllText("token.txt")` for a file.

why do we need a logic async and a start async when it can just be passed to the client object or the startAsync?
> 
> > * using attributes to register command and command parameter info
> 
> Not sure if I misunderstod but this is done by adding `[Command("command")]` to a method. The only requirement is being inside a public class that inherits `ModuleBase`.

ya I know that's not a problem I was just saying it for a example

also `await Task.Delay(-1);` could automatically be called after OnRun invoke in my example
and according to the documentation I have to manually implement my own CommandService

**Comment by SubZero0** [comment]
> This could be a overload.

It could, would be a different design choice, but imo it would look terrible with the amount of arguments we would need.

> its still decoupled since a CommandModuleBase could keep track of the client and the commands

Being decoupled is by design so it isn't an issue, still simple to use.

> why do we need a logic async and a start async when it can just be passed to the client object or the startAsync?

Because the person who wrote this library decided to do it like that and it can't be changed now without breaking previous versions.

> also `await Task.Delay(-1);` could automatically be called after OnRun invoke in my example

It could but it would also add something that isn't needed or makes sense in all cases.
It's useful for console applications that are solely a bot, but a GUI wouldn't need that for example.

> and according to the documentation I have to manually implement my own CommandService

You don't need to implement your own CommandService, it mentions your own command handler.
Obviously creating a class to handle them is better since you can do a lot more, like logging, different execution logic depending on the result, etc.
My "handler" is literally the `message is SocketUserMessage userMessasge && message.Content.StartsWith('!')` that is the most basic as possible, only for that example.
