### ISSUE TITLE
Extension methods on IMessageChannel to get the first and last message of the channel as an IMessage

### ISSUE THREAD

**Issue by Rekkonnect** [RogueException/Discord.Net#1736]
I believe that this functionality is relatively common among several bots, and having to do
```csharp
var firstMessage = (await channel.GetMessagesAsync(0, Direction.After, 1).FlattenAsync()).FirstOrDefault();
var lastMessage = (await channel.GetMessagesAsync(1).FlattenAsync()).FirstOrDefault();
```
quickly becomes confusing to read.

Having a `GetFirstMessageAsync()` and `GetLastMessageAsync()` would greatly reduce the complexity of the above snippet.

**Comment by Quahu** [comment]
I think it's not really that common (especially the former method) and you can always make an extension method, if it's used commonly enough throughout your code.

**Comment by Rekkonnect** [comment]
I've already made those extension methods in my code, but would it really hurt to have them in the API itself? Besides, they don't add any clutter, as they're only extension methods, and can only be consumed.

**Comment by SubZero0** [comment]
Imo they are too specific and don't really have any good general purpose or are that common. So it's a no for me.
