### ISSUE TITLE
Discord Rule Screening: User.Pending = true?

### ISSUE THREAD

**Issue by TheHeartOfFire** [RogueException/Discord.Net#1737]
With the new rule screening feature @ everyone cannot interact with the server until they agree to a set of rules. The [documentation](https://discord.com/developers/docs/resources/guild#guild-member-object-guild-member-structure) indicates that users have a flag called pending that indicates whether or not a user has agreed to the rules. I wasn't able to find any kind of Pending flag in the SocketGuildUser object. Am i looking for this flag in the wrong place? If we aren't currently able to get this flag would we be able to update this project to grab the flag?

**Comment by zbroderson** [comment]
Hello, are you using the latest nuget version?  If so please update to the nightly builds.  They are the only builds with the pending flag and many other features.

https://docs.stillu.cc/guides/getting_started/nightlies.html?tabs=vs

**Comment by TheHeartOfFire** [comment]
> Hello, are you using the latest nuget version? If so please update to the nightly builds. They are the only builds with the pending flag and many other features.
> 
> https://docs.stillu.cc/guides/getting_started/nightlies.html?tabs=vs

Ahh, alrighty then will do! Thanks!

EDIT: I found it once i update. Thanks again! This can be closed.
