### ISSUE TITLE
Documentation expression

### ISSUE THREAD

**Issue by Rekkonnect** [RogueException/Discord.Net#1738]
Documentation in general should be objective. Exclamation marks indicate subjective expressions, which contrast that. While there are certain remarks that must be made in the documentation, it is best to emphasize them in a more objective manner, without using exclamation marks.

**Comment by ohkriss** [comment]
This sounds more like a personal issue, and not a issue related to discord.net

**Comment by Still34** [comment]
Exclamation does not necessarily indicate subjective expression. While I can understand the use of exclamation mark can be inappropriate in XML docs strings, this should be a non-issue for general docs or guidelines. As a general rule of thumb, informality is the only thing we don't accept in this project. Closing.
