### ISSUE TITLE
DiscordShardedClient's SetGameAsync() not working with ActivityType.CustomStatus

### ISSUE THREAD

**Issue by hburn7** [RogueException/Discord.Net#1739]
Discord.NET Version: `2.3.0-dev-20201223.7`

When using a `DiscordShardedClient`'s `SetGameAsync()` method with a custom status, the bot's status appears as the default status (blank).

```cs
public class Foo
{
    private string _myText;
    private ActivityType _myActivity;
    private DiscordShardedClient _myClient;

    public Foo(DiscordShardedClient client)
    {
        _myText = "Some status";
       _myActivity = ActivityType.CustomStatus;
       _myClient = client;
    }

    public async Task SetStatusAsync()
    {
        await _client.SetGameAsync(_myText, null, _myActivity); // Empty status.
    }
}
```

Using any other activity type correctly displays the status.

**Comment by zbroderson** [comment]
Bots cannot use custom statuses.

Bots have to use "Playing", "Listening", "Streaming"

**Comment by hburn7** [comment]
> Bots cannot use custom statuses.
> 
> Bots have to use "Playing", "Listening", "Streaming"

If this is the case, why is it an option? Is ActivityType used outside of the `SetgameAsync()` method? If so, should another type be created, such as `BotActivityType`?

**Comment by zbroderson** [comment]
ActivityType is also used to describe user Activities.  Another type could be created, but I'm not here to discuss design philosophy.  There may be a reason that it is this way or there may not be.

**Comment by SubZero0** [comment]
Since this question was answered, I'll be closing it.
