### ISSUE TITLE
(Rest) User returning offline (latest version)

### ISSUE THREAD

**Issue by djthegr8** [RogueException/Discord.Net#1740]
Every user is returning as offline. I am running `GetUsersAsync()` then checking the status, but it always returns offline.

**Comment by zbroderson** [comment]
Take a look at intents:

intents are here, please do some light reading. to specify intents, please update to the nightly builds. https://discordapp.com/channels/81384788765712384/381871767846780928/770678489404932146 and also join https://discord.gg/discord-developers for lots of info straight from the horses mouth

**Comment by djthegr8** [comment]
@Zackattak01 I have all intents checked. Anyways, if you'd see the function, I'm running `RestUser.GetUsersAsync` so I'm not using the Gateway itself. A plausible explanation is that RestUser.status is a useless attribute cause the REST API doesn't return a status

**Comment by zbroderson** [comment]
Sorry! Didn't catch that it was a REST method.  Yeah I can't explain why status is there since your are correct in saying that the REST api does not send status data.

**Comment by djthegr8** [comment]
Yeah, I think `RestUser` perhaps *needs* a status attribute due to inheriting `IUser` but not sure... Anyways `GetUserAsync` *is* a REST method, a gateway method would be `GetUser` hehe

**Comment by SubZero0** [comment]
Rest will never return their status so they will always show as offline, this isn't a bug but how Discord works (and how D.Net handles it). If you want status and/or presences, you will need to use the gateway (+ enabe the presence intent).

`GetUserAsync` isn't always a rest request, it depends on where you are calling it, gateway entities will always do a cache lookup.

**Comment by djthegr8** [comment]
> Rest will never return their status so they will always show as offline, this isn't a bug but how Discord works (and how D.Net handles it). If you want status and/or presences, you will need to use the gateway (+ enable the presence intent).

Yes, yes...
> 
> `GetUserAsync` isn't always a rest request, it depends on where you are calling it, gateway entities will always do a cache lookup.

Alright
