### ISSUE TITLE
What does UserStatus.AFK mean?

### ISSUE THREAD

**Issue by djthegr8** [RogueException/Discord.Net#1744]
In Discord, for a user at least, there are 4 possible statuses of `Idle, Online, Offline` and `Invisible`                                  
What is `UserStatus.AFK`?

**Comment by Anu6is** [comment]
Idle

**Comment by djthegr8** [comment]
`UserStatus.Idle` is for that... You don't need `UserStatus.AFK` at all

**Comment by SubZero0** [comment]
They have one difference internally, AFK will send since when it started.
https://github.com/discord-net/Discord.Net/blob/8b25c9bbfb88818f0a3eda6ca04ba3c06a4fec43/src/Discord.Net.WebSocket/DiscordSocketClient.cs#L430-L433

**Comment by djthegr8** [comment]
Alright, thanks.
