### ISSUE TITLE
Bot not working on Debian 10

### ISSUE THREAD

**Issue by Cr1TiKa7** [RogueException/Discord.Net#1745]
Hello,
i've just written a discord bot which works perfectly on my windows machine.
Now i wanted to deploy it on my linux server (installed the runtime and sdk), started the bot and everything seems to work.
But normally when my bot joines a new guild it should send the admin a message and should also start to react on commands but it just doesn't.

My bot doesn't disconnect or throws any exceptions. Also the login state is always LoggedIn.

someone knows what could be the problem?
Thanks in advance!

**Comment by SubZero0** [comment]
It's probably throwing an exception somewhere that you aren't logging.

https://docs.stillu.cc/guides/concepts/logging.html

**Comment by Still34** [comment]
Stale issue; reopen if the issue persists after the suggestion above.
