### ISSUE TITLE
User Reacts, but Guild.GetUser is null

### ISSUE THREAD

**Issue by dbones** [RogueException/Discord.Net#1746]
Discord .net 2.2.0

on the `client.ReactionAdded` being involved by a user that has not recently been in a `VoiceChannel`. When they react to a message I cannot get the user. 

this issue happens with the `IGuild.GetUserAsync()`, `SocketGuildChannel.GetUser()` and also with the `SocketGuildChannel.Users.FirstOrDefault()`

How ever if the user enters a VoiceChannel, the same code works.

**Steps to repeat**, log into discord, and react to a message (i have duplicated the issue with the windows, mobile, and firefox clients)

![not-working](https://user-images.githubusercontent.com/183849/103946872-215d2f80-512f-11eb-9748-688b9b1e8176.gif)
 to a message.
 
 
btw - `guild.DownloadUserAsync` - just hangs

https://github.com/discord-net/Discord.Net/issues/1533 - This issue looks to be about new users, these users are already part of the guild (so I would say not applicable)

**Comment by k-boyle** [comment]
intents are here, please do some light reading. to specify intents, please update to the nightly builds. https://discordapp.com/channels/81384788765712384/381871767846780928/770678489404932146 and also join https://discord.gg/discord-developers for lots of info straight from the horses mouth (100% match)

**Comment by dbones** [comment]
ARGH, it looks like i may require `PRESENCE INTENT`

testing it now
