### ISSUE TITLE
All users showing offline

### ISSUE THREAD

**Issue by reynoldsbj** [RogueException/Discord.Net#1748]
I am using Context.Guild.Users to pull up all of the users in the server, and I want to get the users that are online, but all of them show as Offline even though they are online. I'm using v2.2.0

**Comment by SubZero0** [comment]
You are probably missing the presence intent.

**Comment by reynoldsbj** [comment]
> You are probably missing the presence intent.

Can you elaborate?

**Comment by SubZero0** [comment]
"[...] go to your application in the Developer Portal and enable the toggle for the Privileged Intents you wish to use. If your bot is in 100 or more guilds, you must also get your bot verified.". [[Privileged Intents](https://discord.com/developers/docs/topics/gateway#privileged-intents)]

Just enable it and it should work.

**Comment by reynoldsbj** [comment]
> "[...] go to your application in the Developer Portal and enable the toggle for the Privileged Intents you wish to use. If your bot is in 100 or more guilds, you must also get your bot verified.". [[Privileged Intents](https://discord.com/developers/docs/topics/gateway#privileged-intents)]
> 
> Just enable it and it should work.

That was it. I thought admin permissions would cover everything. I'll look over the rest of the configuration next time before opening another issue. Thanks!
