### ISSUE TITLE
How to send a reply to a message from another user

### ISSUE THREAD

**Issue by nminaya** [RogueException/Discord.Net#1751]
I started to use this library to play with a bot.

But I can't find a way to make my bot send a reply message to a message from another user.

I want the bot to send a reply based on the content of a message.

So in my MessageReceived method I have something like:

```cs
...
var context = new SocketCommandContext(discordSockerClient, socketUserMessage);

// How do I specify this is a reply to a message?
await context.Channel.SendMessageAsync("Reply message");
```

```SendMessageAsync``` method doesn't have an overload to specify the message is a reply to another message.

Can I get help with this? Maybe I'm doing it the wrong way.

Thanks.

**Comment by TheNoodleMummy** [comment]
you would need the [nightly builds](https://docs.stillu.cc/guides/getting_started/nightlies.html?tabs=vs) of dnet to do this. 
if you have any more question feel free to join [Discord-api](https://discord.gg/discord-api) and look for the #dotnet_discord-net channel

**Comment by nminaya** [comment]
@TheNoodleMummy Thank you for the information.

Just for the record, after updating Discord.NET to a nightly build, ```SendMessageAsync``` method has a ```messageReference``` optional parameter where you can specify the message you want to reply to.
