### ISSUE TITLE
Inline reply not working with SendFileAsync

### ISSUE THREAD

**Issue by sitiom** [RogueException/Discord.Net#1754]
```cs
await Context.Channel.SendFileAsync(data, "audio.wav", messageReference: new MessageReference(Context.Message.Id));
```

The inline reply should be working the same way like `ReplyAsync` or `Context.Channel.SendMessageAsync` however it doesn't.

**Comment by SubZero0** [comment]
Thanks for reporting, fixed in 20957016653e2dba1a7a1007f2c684b7c02a6ee8
