### ISSUE TITLE
Support INTEGRATION_CREATE, INTEGRATION_UPDATE and INTEGRATION_DELETE

### ISSUE THREAD

**Issue by byBlurr** [RogueException/Discord.Net#1755]
These are currently throwing warnings on my bot. 

Here is an issue related to these on Discord-api-docs: https://github.com/discord/discord-api-docs/issues/2121

**Comment by quinchs** [comment]
#1717

**Comment by MrCakeSlayer** [comment]
This has now been implemented via the merged labs PR (#1923)
