### ISSUE TITLE
Incompatible with EF after IAsyncEnumerable changes

### ISSUE THREAD

**Issue by MangoDevx** [RogueException/Discord.Net#1756]
`Severity    Code    Description    Project    File    Line    Suppression State
Error    CS0121    The call is ambiguous between the following methods or properties: 'System.Linq.AsyncEnumerable.Where<TSource>(System.Collections.Generic.IAsyncEnumerable<TSource>, System.Func<TSource, bool>)' and 'System.Linq.Queryable.Where<TSource>(System.Linq.IQueryable<TSource>, System.Linq.Expressions.Expression<System.Func<TSource, bool>>)' `

`<PackageReference Include="Discord.Net" Version="2.3.0-dev-20210121.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="5.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="5.0.1">`

**Comment by zbroderson** [comment]
Try using the AsQuerable (preferred) or AsEnumerable methods.  It removes the ambiguity and allows you to use linq on a db set

(p.s. https://github.com/dotnet/efcore/issues/18220)

**Comment by MangoDevx** [comment]
> Try using the AsEnumerable or AsQuerable methods. It removes the ambiguity and allows you to use linq on a db set
> 
> (p.s. [dotnet/efcore#18220](https://github.com/dotnet/efcore/issues/18220))

Sure you can do that, but this has not been the behavior in the past. Not a huge issue, just did not see any other issues posted about it. Maybe I am blind? :)

**Comment by zbroderson** [comment]
It's not exactly something the lib maintainers have control over.  This is more of a dotnet issue in general.

**Comment by snnaakee** [comment]
> Try using the AsQuerable (preferred) or AsEnumerable methods. It removes the ambiguity and allows you to use linq on a db set
> 
> (p.s. [dotnet/efcore#18220](https://github.com/dotnet/efcore/issues/18220))

AsQuerable returns a cached value, so you can easily end up with different values than the db has stored.
Avoiding an issue is generally not a good idea. Microsoft had the same trouble with EF and it got fixed since EF 6.0.
I think Discord.NET should avoid using Linq.Async.
