### ISSUE TITLE
Webhook URL Regex

### ISSUE THREAD

**Issue by bami55** [RogueException/Discord.Net#1758]
Is `A-Z` not enough? 
> `^.*(discord|discordapp)\.com\/api\/webhooks\/([\d]+)\/([a-z0-9_-]+)$`
↓
`^.*(discord|discordapp)\.com\/api\/webhooks\/([\d]+)\/([a-zA-Z0-9_-]+)$`

https://github.com/discord-net/Discord.Net/blob/20957016653e2dba1a7a1007f2c684b7c02a6ee8/src/Discord.Net.Webhook/DiscordWebhookClient.cs#L36

**Comment by bami55** [comment]
ex

```
https://discord.com/api/webhooks/804226398075355146/WRzX5u_q8u5F-gmcIbkLfgZQTvalYZ0rOCzSs92AsW_iMHiSm1fZ19atig9MGxGmhTPv
```

**Comment by SubZero0** [comment]
That would fail any url with any capitalized letter before it.
