### ISSUE TITLE
How to clone channel new messages to my channel

### ISSUE THREAD

**Issue by Sl4vP0weR** [RogueException/Discord.Net#1759]
It is possible to handle message receive from channel A on server X and copy it to channel B on server Y ?
Bot didn't invited to server X

**Comment by byBlurr** [comment]
The bot needs to have access to the channel where the messages are received to then replicate and send a new message in your channel. Not that I am supporting this exactly?

**Comment by Sl4vP0weR** [comment]
I want to do alternative of anouncements, I need every new message, not only published

**Comment by byBlurr** [comment]
> The bot needs to have access to the channel where the messages are received

If the bot is not in server X - It can't access the channel to get the required data

**Comment by Sl4vP0weR** [comment]
So, how can I solve this problem ?
Mb I can access server X as user and get data from there ?

**Comment by byBlurr** [comment]
I don't quite understand what you mean. You can access the server as a user and copy it yeah but not pull the data automatically. You can only pull that data automatically through a bot if the bot itself has access to read the channel.

**Comment by Sl4vP0weR** [comment]
1. Await messages from X-A
2. Send messages to Y-B

**Comment by Sl4vP0weR** [comment]
Well, then I should auth as user

**Comment by TheNoodleMummy** [comment]
logging bots in as users is against discord ToS and not supported by discord.net

**Comment by byBlurr** [comment]
That's what I thought
