### ISSUE TITLE
Allow command arguments to have repeating type combinations.

### ISSUE THREAD

**Issue by expeehaa** [RogueException/Discord.Net#1763]
In my bot I want to implement a simple poll command using reactions.
If I know that my poll can have e.g. 2 answers, I can define the method signature like this:

```csharp
Task Poll(string question, Emote reaction1, string answer1, Emote reaction2, string answer2);
```

This obviously is not good because of the fixed amount of possible answers.
Also, I may want to ensure that a combination of a reaction and an answer is always given.

I imagine the following as my ideal method signature.
```csharp
Task Poll(string question, params (Emote reaction, string answer)[] answers);
```
As far as I can tell, this or a comparable feature is currently not implemented in Discord.Net.

I would be able to implement that myself and create a pull request, in case this feature request will not be rejected.

**Comment by Hamsterland** [comment]
```cs
public class PollOption
{
    public IEmote Emote { get; }
    public string Answer { get; }

    public PollOption(IEmote emote, string answer)
    {
        Emote = emote;
        Answer = answer;
    }
}
```
```cs
Task Poll(string question, params PollOption[] options); 
```
Then all you need to do is create a custom `TypeReader` for `PollOption`

**Comment by expeehaa** [comment]
@Hamsterland Yes, this would be an option, but then I would have to implement a custom `TypeReader` anyway. (I just noticed that there isn't even a `TypeReader` for `Emoji` or `Emote`, but that's a different problem.)
My goal is to make use of `ValueTuple` and avoid having to specify a custom `TypeReader` at all when the types in the value tuple (or at least some) can already be parsed by existing type readers.

**Comment by Hamsterland** [comment]
Well your goal is pretty convoluted. Just create your own parsers for that class and don't mess with Tuples.
