### ISSUE TITLE
Thoughts on adding a method to un-cache guild users?

### ISSUE THREAD

**Issue by 230Daniel** [RogueException/Discord.Net#1764]
When I re-wrote my bot I tried to keep its memory usage to an absolute minimum. The biggest memory hog is certainly the user cache in Discord.NET, so I optimised this by only caching users for the guilds that needed their users cached. For example, those with my role persist feature enabled. I noticed that as my bot stayed online for longer and longer, the memory usage crept up fairly significantly.

I did a test with 780 servers (514431 total users), and the original cached user count of 76861 was up to 89073 after 20 hours of running. The 12212 extra users meant that my bot was using up 130 MB more memory after 20 hours than when it started up. It's my understanding that users are cached once they send a message or do something else in the guild.

I would love to be able to un-cache these users to free up some memory because I can imagine this becoming a bigger problem as my bot grows. A simple way of doing this would be allowing the library users to remove items from `SocketGuild.Users`, but I understand that this might be confusing for some developers who don't completely understand the caching system.

Does anybody have a good idea about how this could be implemented? Or should it not be implemented at all? I'd love to work on the implementation myself, although I'm not very familiar with how the library works.

**Comment by k-boyle** [comment]
There's an internal method on SocketGuld to purge the users (which I don't think gets exposed elsewhere like the purge channel does, not that that method should ever be called) which you could use reflection to call, whether the lib survives after that's called is a different issue, but worth trying I guess. iirc Paulo said he tried to get the lib into a state where it can work cacheless but was a mess

**Comment by 230Daniel** [comment]
Ah cool, thanks for the pointer. That method has 2 references, one is called when the guild is removed and the other is called from public method DiscordSocketClient.PurgeUserCache() which is just a foreach loop calling the PurgeGuildUsers method.

It appears that the PurgeGuildUserCache also removes each user from some kind of global cache, so I would assume that the method was designed to be called for all guilds at once, and that if it's only called for a few guilds then problems will occur.

However, if it's safe to call the method for the one guild when it's removed, surely it must be safe to call it at any time? I've added a way to call the method and have added a script to my bot to clear all unnecessary users every 15 seconds. I'll see if I spot any issues, but everything has been working great so far.
