### ISSUE TITLE
Discord Webhook 500

### ISSUE THREAD

**Issue by asdat3** [RogueException/Discord.Net#1769]
hey kids please don't fight on my github issue, this has been answered, thanks.

_Originally posted by @foxbot in https://github.com/discord-net/Discord.Net/issues/1069#issuecomment-392347206_

Heyy,
eh I am not sure about anything and yes it might by my code but if I am grabbing the data I am sending and put it into Discohook it has no issue with it too.

I am getting the 500 internal server error when sending the Discord webhook at my open source memory checker:
https://github.com/asdat3/Discord-Server-Checker

lmk if you have any ideas what could trigger this issue, thanks

**Comment by Anu6is** [comment]
You aren't even using Discord.Net. Why are you raising issues here?

**Comment by asdat3** [comment]
sorry
