### ISSUE TITLE
Rate Limit Triggered channels/802199828847001655

### ISSUE THREAD

**Issue by Atomfred456** [RogueException/Discord.Net#1770]
I´m creating a Bot to manage tournaments. And when i start a tournament, every signed Team gets a Voicechannel, a Textchannel and a Role created. This worked out very well earlier, but now it stops after 1 or 2 teams with the following error code:

21:40:18 Rest Rate limit triggered: channels/802199828847001655

I even tried only creating the channels without any role creation or permission assignment to the channels, and it still stops after 1 or 2 teams.

The ID in the error is always the same.

If i keep it running it will create the remaining channels but is really slow it takes 3 min to create the channels for the next team.

`[Command("starttournament")]
        public async Task starttournament(string turnierName)
        {
            var guildUser = Context.Guild.GetUser(Context.Message.Author.Id);
            await Context.Message.DeleteAsync();
            if (guildUser.Roles.Select(x => x.Id).Contains(Roles.Orga))
            {
                var helper = new SpaceCupDataSetHelper();
                var dataSet = helper.GetSpaceCupDataSet();
                helper.FillDataSet(dataSet);
                SpaceCupDataSet.TurnierRow turnier = null;
                try
                {
                    turnier = dataSet.Turnier.Single(x => x.Bezeichnung.TrimEnd(' ') == turnierName);
                }
                catch
                {
                    await Context.Message.DeleteAsync();
                    RestUserMessage m;
                    if(guildUser.Roles.Select(x => x.Id).Contains(Roles.Englisch))
                        m = await Context.Channel.SendMessageAsync("The Tournament was not found.");
                    else
                        m = await Context.Channel.SendMessageAsync("Das Turnier wurde nicht gefunden.");
                    await Task.Delay(5000);
                    await m.DeleteAsync();
                    return;
                }

                if (turnier.istInitialisiert && (turnier.Status.TrimEnd(' ') == TurnierStati.Initialisiert || turnier.Status.TrimEnd(' ') == TurnierStati.Anmeldephase))
                {
                    //Matches und Teams werden zugeordnet

                    switch (turnier.TurnierArt)
                    {
                        case ((int)TurnierArten.KO16):
                            #region
                            var matches = dataSet.Match.Where(x => x.TurnierID == turnier.TurnierID && x.MatchEbene == 8).ToList();
                            var teamsInTurnier = dataSet.TeamINTurnier.Where(x => x.TurnierID == turnier.TurnierID).ToList();
                            int count = 0;

                            foreach (var match in matches)
                            {
                                try
                                {
                                    match.TeamBlau = teamsInTurnier[count].TeamRow.TeamID;
                                }
                                catch (ArgumentOutOfRangeException e)
                                {
                                    match.TeamBlau = 0;
                                }

                                try
                                {
                                    match.TeamOrange = teamsInTurnier[count + 1].TeamRow.TeamID;
                                }
                                catch (ArgumentOutOfRangeException e)
                                {
                                    match.TeamOrange = 0;
                                }

                                match.Status = MatchStati.TeamsZugeordnet;

                                count += 2;
                            }

                            turnier.Status = TurnierStati.Laufend;
                            #endregion
                            break;
                        default:
                            break;
                    }

                    //Fehlende Channels werden erstellt.
                    var teams = turnier.GetTeamINTurnierRows().Select(x => x.TeamID);

                    foreach (var teamID in teams)
                    {
                        try
                        {
                            dataSet.TeamVoiceChannel.Single(x => x.TeamID == teamID);
                        }
                        catch
                        {
                            ulong channel = 0;
                            ulong textChannel;
                            IRole role = null;
                            try
                            {
                                var ch = await Context.Guild.CreateVoiceChannelAsync(dataSet.Team.FindByTeamID(teamID).TeamName, prop => prop.CategoryId = Categories.TeamChannels);
                                channel = ch.Id;
                                var tC = await Context.Guild.CreateTextChannelAsync(dataSet.Team.FindByTeamID(teamID).TeamName, prop => prop.CategoryId = Categories.TeamChannels);
                                textChannel = tC.Id;
                                role = await Context.Guild.CreateRoleAsync(dataSet.Team.FindByTeamID(teamID).TeamName, null, null, false, null);
                                await ch.AddPermissionOverwriteAsync(Context.Guild.EveryoneRole, DiscordBot.GetChannelDenyPermissions());
                                await ch.ModifyAsync(x => { x.UserLimit = 8; });
                                await ch.AddPermissionOverwriteAsync(role, DiscordBot.GetAdminPermissions());
                                await tC.AddPermissionOverwriteAsync(Context.Guild.EveryoneRole, OverwritePermissions.DenyAll(ch));
                                await tC.AddPermissionOverwriteAsync(role, DiscordBot.GetAdminPermissions());
                                await tC.SendMessageAsync("Dieser Channel ist nur von euren Teammitgliedern sichtbar und wird nach der Beendigung des Turniers gelöscht.\n" +
                                    "\n" +
                                    "Hier bekommt ihr die Infos zu den Matches. Diese werden auch dem Team Captain geschickt.\n" +
                                    "\n" +
                                    "Das Ergebnis **jeder** Map wird in einem **Screenshot** am Ende des Matches festgehalten.\n" +
                                    "Dieser muss anschließend in den #screenshots Channel,** in Kombination mit der hier zu findenden MatchID**, gesendet werden.\n" +
                                    "\n" +
                                    "Bei Fragen, Lob, aber besonders bei Kritik, wendet euch gerne an unsere Support oder die Cup Orga.\n" +
                                    "\n" +
                                    "Desweiteren Wünschen wir euch viel Spaß bei unserem Turnier!");

                                await tC.SendMessageAsync("This Channel can only be seen by your team and will be deleted after the tournament has finished.\n" +
                                    "\n" +
                                    "Here your team will get it´s Infos about upcoming matches. Your Team Captain will also get a notification.\n" +
                                    "\n" +
                                    "The result of **every** played map needs to be **screenshotted** at the end of a map.\n" +
                                    "The Screenshot **needs to be sent** in the #screenshots channel **together with the MatchID**, wich is found here.\n" +
                                    "\n" +
                                    "If you have any questions or feedback, feel free to contact our Support or Cup Orga.\n" +
                                    "\n" +
                                    "We wish you good luck and lots of fun during our tournament!");

                                dataSet.TeamVoiceChannel.AddTeamVoiceChannelRow((long)channel, teamID, (long)role.Id, (long)textChannel);
                            }
                            catch
                            {
                                await Context.Message.DeleteAsync();
                                RestUserMessage mes;
                                if (guildUser.Roles.Select(x => x.Id).Contains(Roles.Englisch))
                                    mes = await Context.Channel.SendMessageAsync("Channel couldn´t be created!");
                                else
                                    mes = await Context.Channel.SendMessageAsync("Fehler beim erstellen der Channel. Abbruch!");
                                await Task.Delay(8000);
                                await mes.DeleteAsync();
                            }
                        }

                        var voicechannel = Context.Guild.GetVoiceChannel(VoiceChannels.TurnierNameChannel);
                        await voicechannel.ModifyAsync(x => x.Name = turnier.Bezeichnung.TrimEnd(' '));

                        var voicechannelPhase = Context.Guild.GetVoiceChannel(VoiceChannels.TurnierNameChannel);
                        await voicechannelPhase.ModifyAsync(x => x.Name = "Turnier läuft!");
                    }

                    helper.saveChanges(dataSet);

                    await Context.Message.DeleteAsync(); 
                    RestUserMessage m;
                    if (guildUser.Roles.Select(x => x.Id).Contains(Roles.Englisch))
                        m = await Context.Channel.SendMessageAsync("The Tournament was started successfully.");
                    else
                        m = await Context.Channel.SendMessageAsync("Das Turnier wurde erfolgreich gestartet.");
                    await Task.Delay(5000);
                    await m.DeleteAsync();
                }
                else
                {
                    await Context.Message.DeleteAsync();
                    RestUserMessage m;
                    if (guildUser.Roles.Select(x => x.Id).Contains(Roles.Englisch))
                        m = await Context.Channel.SendMessageAsync("The tournament has to be initialised or it needs to be in the registration phase.");
                    else
                        m = await Context.Channel.SendMessageAsync("Das Turnier muss Initialisiert sein und in der Anmeldephase, oder den Status Initialisiert haben.");
                    await Task.Delay(5000);
                    await m.DeleteAsync();
                }
            }
        }`

**Comment by 230Daniel** [comment]
Any rate limit triggered message means that you're making too many requests to the Discord API too quickly. I suggest reading their documentation about rate limits [here](https://discord.com/developers/docs/topics/rate-limits). Try adding delays of a couple of seconds between each action.

**Comment by Atomfred456** [comment]
As i already said, i removed all other things and just created the channels without anz permissons or else and its still not working

**Comment by AraHaan** [comment]
> 
> 
> As i already said, i removed all other things and just created the channels without anz permissons or else and its still not working

combine those 2 send messages because there is a max of 2k characters per message anyway, also it would help reduce requests too.

**Comment by Atomfred456** [comment]
No that cant be the Problem

I tried removing everything, every Role assignment, creation or assignment of Permissions to the Channels and also the Messages. And this doesnt work too, Just Creating the Channels is not working in any way anymore, it was working with permissions, roles and everything. But not after i once started it with the messages.

**Comment by AraHaan** [comment]
> 
> 
> No that cant be the Problem
> 
> I tried removing everything, every Role assignment, creation or assignment of Permissions to the Channels and also the Messages. And this doesnt work too, Just Creating the Channels is not working in any way anymore, it was working with permissions, roles and everything. But not after i once started it with the messages.

then you are requesting the creation of channels too fast, why not use some sort of ``ConcurrentQueue`` on everything that needs to be added so that way you can know when you are about to ratelimit (by popping off of the Queue only when the request is successful, on failure do that wait that you done in the code above).

**Comment by Atomfred456** [comment]
Even if it was working out earlier @AraHaan ?

**Comment by Atomfred456** [comment]
And how can i know if a Request was succesful? I couldn´t find anything on that. :/

**Comment by AraHaan** [comment]
> 
> 
> And how can i know if a Request was succesful? I couldn´t find anything on that. :/

it would throw an exception no?

**Comment by Atomfred456** [comment]
It actually doesnt it keeps creating the channels and waits to be abled to create the next

**Comment by Atomfred456** [comment]
@AraHaan could it be causing problems, because i´m trying to send messages to non existent Users? because i created id´s like 1 2 or something and i have the sendMessage in a Try Catch block.

**Comment by quinchs** [comment]
The issue is modifying the voice channel name, around the time of this issue there was a change to the modify channel ratelimits.
