### ISSUE TITLE
Readme - url linked for the documentation is outdated

### ISSUE THREAD

**Issue by BrayanKhosravian** [RogueException/Discord.Net#1771]
Hello, when I click on the link which should delegate me to the docs page 
I get a "website is not reachable".

Is this probably the actual documentation? https://docs.stillu.cc/

![image](https://user-images.githubusercontent.com/35541212/107088561-6d1dfa00-67fd-11eb-9188-98036c90d674.png)

**Comment by erxkk** [comment]
The Site is offline because the previous maintainer foxbot is MIA, you'll have to use the nightly docs for now which are generated from the repo directly on each push and might include features that are not on the stable version.
