### ISSUE TITLE
TypeReader doesn't take CommandService.SeparatorChar into consideration

### ISSUE THREAD

**Issue by Arnaud-F** [RogueException/Discord.Net#1772]
I'm creating a custom TypeReader and seems to be the SeparatorChar is not taken into consideration to split input.

**Steps to reproduce**
Create your CommandService
```csharp
var serviceConfig = new CommandServiceConfig() { DefaultRunMode = RunMode.Async, SeparatorChar = ',' };
return new ServiceCollection()
                .AddSingleton<CommandService>(new CommandService(serviceConfig))
```
Add your TypeReader 
```csharp
_commands.AddTypeReader<Champion>(_services.GetRequiredService<ChampionsTypeReader>());
await _commands.AddModulesAsync(Assembly.GetEntryAssembly(), _services);
```
Create your method taking an array of your custom type :
```csharp
[Command("add")]
public async Task AddAsync(params Champion[] champions)
{
    await ReplyAsync(champions.Length.ToString());
}
```

Then launch the bot and type the command: 
 ```csharp
!add a b, c
```

**Expected result**
First time it enters to this method:
 ```csharp
public override async Task<TypeReaderResult> ReadAsync(ICommandContext context, string input, IServiceProvider services)
```
```input``` should be equal to ```a b```
Second iteration ```input``` **should** be equal to `c`

**What really happens**
First time it enters to this method:
 ```csharp
public override async Task<TypeReaderResult> ReadAsync(ICommandContext context, string input, IServiceProvider services)
```
```input``` is be equal to ```a``` (only) meaning it does not take the separator char into consideration.

Sorry about that but I struggle with this TypeReader for days now, general idea is pretty good but could be great to have the possibility to override some behaviors.

**Comment by quinchs** [comment]
Seems like this isn't just a type reader issue, looking at the [CommandParser#92](https://github.com/discord-net/Discord.Net/blob/b5c150dc166f288ab4a400097259a1ecda5ce399/src/Discord.Net.Commands/CommandParser.cs#L92) the separator character isn't taken into effect for this. Seeing that this code hasn't been touched in a long time I don't now how anyone has not noticed this issue before.

Going to cc @SubZero0 here for a second look into this

**Comment by SubZero0** [comment]
From what I looked, `SeparatorChar` is only taken into consideration to separate modules and commands, so I assume to instead of having something like `?command subcommand arg`, it would be `?command.subcommand arg` for example.

I doubt this was a mistake, but by design.
