### ISSUE TITLE
EnterTypingState before command execution but only for valid commands?

### ISSUE THREAD

**Issue by blai30** [RogueException/Discord.Net#1775]
Given the example from [the intro to command service guide](https://docs.stillu.cc/guides/commands/intro.html):
```csharp
var context = new SocketCommandContext(_client, message);
await _commands.ExecuteAsync(context, argPos, _provider);
```

I can then wrap this snippet with a `using context.Channel.EnterTypingState()`:
```csharp
using (context.Channel.EnterTypingState())
{
    var context = new SocketCommandContext(_client, message);
    await _commands.ExecuteAsync(context, argPos, _provider);
}
```

This will cause the client to enter typing state as long as the author's message meets the criteria for executing commands, regardless if the command is actually valid.

Is there a way to use `EnterTypingState()` for only valid commands without using `BeforeExecute()` from `ModuleBase` nor `TriggerTypingAsync()`?

**Comment by Joe4evr** [comment]
You'll have to perform all the steps of `ExecuteAsync` manually to do that.
```cs
var context = new SocketCommandContext(_client, message);
var searchResult = _commands.Search(context, argPos);
if (searchResult.IsSuccess)
{
    using (context.Channel.EnterTypingState())
    {
        //.....
    }
}
```

Finding the right command out of the search result takes a bit of effort, [at worst you can copy the code here as-is](https://github.com/discord-net/Discord.Net/blob/0fc713a8977d2474adf03dc83a46d02ffcd295e8/src/Discord.Net.Commands/CommandService.cs#L516), but you'll have to decide for yourself if it's worth the effort.

**Comment by blai30** [comment]
This is how I did it:
```csharp
// abstract class that inherits ModuleBase<SocketCommandContext>
protected override void BeforeExecute(CommandInfo command)
{
    base.BeforeExecute(command);
    using IDisposable typing = Context.Channel.EnterTypingState();
}
```
