### ISSUE TITLE
Bot doesn't download Guild Users

### ISSUE THREAD

**Issue by Thrithralas** [RogueException/Discord.Net#1779]
I'm trying to get a list of every user in a pretty small (~30 members) server, but the bot only downloads me (the person who issued the command) and the bot itself.

I feel like I'm just missing something becasue there is a `HasAllMembers` property of `SocketGuild` which is false in every scenario. Adding `AlwaysDownloadUsers = true` to the socker configuration didn't do anything.

I feel like I'm either missing something obvious or these is a way to force download everyone, because this feels more like a feature than a bug due to HasAllMembers being a thing.

Thanks for the help in advance.

![image](https://user-images.githubusercontent.com/48440160/107892094-275ee100-6f23-11eb-930e-ddf329a629d2.png)

**Comment by zbroderson** [comment]
intents are here, please do some light reading. to specify intents, please update to 2.3.0. https://discordapp.com/channels/81384788765712384/381871767846780928/770678489404932146 and also join https://discord.gg/discord-developers for lots of info straight from the horses mouth (100% match)

**Comment by LedgendODST** [comment]
He really copy and pasted it

**Comment by Thrithralas** [comment]
> intents are here, please do some light reading. to specify intents, please update to 2.3.0. https://discordapp.com/channels/81384788765712384/381871767846780928/770678489404932146 and also join https://discord.gg/discord-developers for lots of info straight from the horses mouth (100% match)

Well the link you sent me leads to a non-existent text channel (or maybe I just don't have access to it, not sure). I joined the discord server and managed to find the 'Gateway Intents' part which led me to the documentation again. Now it seems to work, thanks for the help.

**Comment by zbroderson** [comment]
The first link leads to a channel in the Unofficial Discord API guild (https://discord.gg/discord-api).  Your welcome to come join and ask questions if you have any further issues.

**Comment by Thrithralas** [comment]
> The first link leads to a channel in the Unofficial Discord API guild (https://discord.gg/discord-api). Your welcome to come join and ask questions if you have any further issues.

Ah alright, I'm not in that server. I've got my issue figured out but thanks for the heads up.
