### ISSUE TITLE
Use the overloading mechanism instead of the optional parameters.

### ISSUE THREAD

**Issue by dongsu8142** [RogueException/Discord.Net#1782]
```
void Notify(string company)
{
  Notify(company, "QJZ");
}
void Notify(string company, string office)
{
}
```

I don't know how to apply this method to discord.net. Attempts fail.

**Comment by erxkk** [comment]
How does that relate to discord.net? You'll have to give a bit more context.

**Comment by dongsu8142** [comment]
https://app.codacy.com/gh/hands8142/csharpbot/issues

I tried many times to solve this issue, but I couldn't.

**Comment by Joe4evr** [comment]
We don't have anything to do with what this Codacy platform tells you. We support both optional command parameters and overloaded commands, and it's up to your own preference to what you want to use. And if you're using some third-party tool that disagrees with your preference, maybe you should stop listening to that tool. 🙃

**Comment by erxkk** [comment]
Optional parameters also enable you to specify the default value of it for your help command, unlike overloads which only show you that there is an overload that accepts less parameters. I don't see any reason to pick overloads over optionals in this case.

EDIT: you should also close the issue as this is not a discord.net issue at all, commands currently work as expected.
