### ISSUE TITLE
i want to be able to select a role only for premium users to use premium commands can i get the code for this please

### ISSUE THREAD

**Issue by mut3-sux** [RogueException/Discord.Net#1783]
i want to be able to select a role only for premium users to use premium commands can i get the code for this please

**Comment by LedgendODST** [comment]
the code is 
while(true)
await client.Loggoutasync(); 

Hope it help you, have a good rest of your year!

**Comment by Emzi0767** [comment]
What's your budget?

**Comment by SubZero0** [comment]
This is a place for issues with Discord.Net, not asking people to code for you.
