### ISSUE TITLE
Bot is not resplonding to commands

### ISSUE THREAD

**Issue by tetrahydrocannabin0l** [RogueException/Discord.Net#1784]
i got this commandhandler:
![image](https://user-images.githubusercontent.com/77512417/109341794-f4e6a980-787b-11eb-8078-ea5914382b27.png)

and bot is simply not responding:
![image](https://user-images.githubusercontent.com/77512417/109342165-80f8d100-787c-11eb-8779-8f3470a13824.png)

**Comment by erxkk** [comment]
Have you debugged and checked if the handler is actually run? That seems like the only logical explanation form the limited code snippet i can see here. Consider adding more code, preferably inside code blocks not images.

**Comment by tetrahydrocannabin0l** [comment]
oh bruh handler is not starting. what i need to do then?

**Comment by ohkriss** [comment]
You should look at the command framework sample. I can already see that you aren't hooking the function to MessageReceived. All you have to do is getting the DiscordSocketClient instance and hook CommandHandler like this _Discord.MessageReceived += CommandHandler;_

**Comment by xenoverse-us** [comment]
> oh bruh handler is not starting. what i need to do then?

Follow this example to start your very first bot.
https://github.com/discord-net/Discord.Net/tree/dev/samples/02_commands_framework

**Comment by tetrahydrocannabin0l** [comment]
> You should look at the command framework sample. I can already see that you aren't hooking the function to MessageReceived. All you have to do is getting the DiscordSocketClient instance and hook CommandHandler like this _Discord.MessageReceived += CommandHandler;_

worked thx!
