### ISSUE TITLE
[Feature Request] Webhook Delete, Edit And Create Handlers (Or Similar)

### ISSUE THREAD

**Issue by MistressPlague** [RogueException/Discord.Net#1785]
Please?

**Comment by MistressPlague** [comment]
I did not mean webhook messages, I mean the webhooks themselves.

**Comment by SubZero0** [comment]
If you meant WEBHOOK_UPDATE, there was a suggestion about it, #1450 
Or did you mean INTEGRATION_x events?

**Comment by MistressPlague** [comment]
The creation of a webhook, editing of one (such as name change) or most
importantly a webhook being deleted.

**Comment by SubZero0** [comment]
After some testing, webhooks will only fire a WEBHOOKS_UPDATE when any of those events happen (even when it's inside the integrations tab).
So I'll be closing this issue as a duplicate of #1450 , any updates will be done there.

**Comment by MistressPlague** [comment]
Discord is dumb ig :/
