### ISSUE TITLE
Can't look up a user by any means

### ISSUE THREAD

**Issue by NinthDesertDude** [RogueException/Discord.Net#1788]
I can't look up any user that isn't the bot creator or the bot.

**Version:** Discord.Net v2.3.0-dev-20210121.1 (API v6)

**Expectation: it's possible (and allowed) to look up a user active in a server my bot is in**
Actual: Calling `GetUser()` with either a snowflake ID or a name#discriminator combo is returning null.
- The snowflake was obtained by right-clicking a user and clicking "Copy ID"
- The user is in the same server
- server members intent is true before and after joining the bot to the server

**Expectation: it's possible to download a list of users and look up a user that way**
Actual: `Client.Guilds` always evaluates to zero after any amount of time the bot has been active. Therefore, `DownloadUsersAsync(Client.Guilds)` always fails.
- server members intent is true before and after joining the bot to the server

**Comment by LedgendODST** [comment]
Hmm have you activated intents on the web page too?

**Comment by NinthDesertDude** [comment]
I think there's only one place where you activate intents (I'd love to be wrong, though):
![image](https://user-images.githubusercontent.com/30244654/109846716-50f65880-7c03-11eb-846c-24cde1cc32ae.png)

**Comment by rdissertori** [comment]
I had the same issue, it worked when the user came online. Isn't it supposed to work on offline users too in a guild?

**Comment by SubZero0** [comment]
Update to 2.3.1 then check this reply and see if find why you are having your issue: https://github.com/discord-net/Discord.Net/issues/1679#issuecomment-727843325

**Comment by NinthDesertDude** [comment]
I'm no longer using discord.net, closing now
