### ISSUE TITLE
IUserMessage.ModifyAsync: Embed is unspecified

### ISSUE THREAD

**Issue by MaxEtMoritz** [RogueException/Discord.Net#1789]
I wanted to make my Bot send a Message with an Embed and edit the Embed later on. But when trying to Modify the message, the Embed property is always not specified. This simple Command shows what i mean:

```cs
[Command("test")]
public Task Test()
{
    IUserMessage msg = ReplyAsync(embed: new EmbedBuilder().Build()).Result;
    msg.ModifyAsync((m) =>
    {
         Console.WriteLine(m.Embed.IsSpecified); // output is false!
    });
    return Task.CompletedTask;
}
```
Am i missing something? is there a better way to edit an Embed than modifying the message, converting the current Embed to an EmbedBuilder, modifying it and re-building the Embed?

I use Discord.Net v2.3.0 by the way.

**Comment by zbroderson** [comment]
ModifyAsync provides no data.  Your meant to supply the data to it.  Try using msg.Embeds to get the embeds on the message.  Then yes, u have to convert to EmbedBuilder, modify accordingly, rebuild, then modify the message

**Comment by erxkk** [comment]
As Zack said, it does not have any information about the message because it's just a trick by the library to let you set values with private/internal setters. Therefore it will always have the default Optional Value that is Empty.

**Comment by MaxEtMoritz** [comment]
Ah, okay, that makes sense! Thank You for Your quick responses! Sorry for taking your time then!

It just confused me that the properties are also getters, so i assumed they contained the current values...
