### ISSUE TITLE
Hello, how can I accept friend request?

### ISSUE THREAD

**Issue by el-bekasto** [RogueException/Discord.Net#1790]
Is there any method which can be used to accept friend request?

**Comment by Joe4evr** [comment]
Bots cannot have friends, and using User accounts is against Discord ToS.

**Comment by el-bekasto** [comment]
> Bots cannot have friends, and using User accounts is against Discord ToS.

So this lib doesn't have this feature? That's sad

**Comment by SubZero0** [comment]
User accounts aren't supported.
