### ISSUE TITLE
[Feature Request] Have a Command with no Text

### ISSUE THREAD

**Issue by Brianbloke** [RogueException/Discord.Net#1793]
Looking for a way to have a command based on an Image. I'm using AWS for Rekognition to read the image to understand what the user is looking for, and the user doesn't usually specify any text with their image.

I was told to put my code for reading an image within the client Message Received handler (from StackOverflow), but it's not ideal for my code as it's a large method that needs to run. I also have commands so, I'd rather keep them all in one place. I still need the message, for the author etc.. too.

**Comment by sudo-gab** [comment]
if you don't have any commands to execute... then you don't need to use commands?

use the MessageReceived event like you got told, as for it being too big, nothing is preventing you from splitting it into smaller methods. you can get the author regardless, the context you see in commands is just a wrapper around properties from the message (you can check the source).

**Comment by Brianbloke** [comment]
Thanks for your response.

I have just figured out a way to do it after reviewing the 'ExecuteAsync' on the commandservice. 
Probably done it a more unconvential way than what you suggested. My worry was that I would need a static method to get this to work and that wasn't something I wanted to do due to requiring a non static method to run my other commands (they basically link together eventually at the end running the same code).

The way I done it is detailed below for reference in future if anyone decided to do it this way

`                    if (message.Attachments.Count > 0)
                    {
                        var result = await _commands.ExecuteAsync(context, "ReadImage", _services);
                        if (!result.IsSuccess) Console.WriteLine(result.ErrorReason);
                    }
                    else
                    {
                        var result = await _commands.ExecuteAsync(context, argPos, _services);
                        if (!result.IsSuccess) Console.WriteLine(result.ErrorReason);
                    }
`

And on my 'Listener' for the command.

` [Command("ReadImage", RunMode = RunMode.Async)]
        public async Task ReadImage()
{
//do stuff
}`
