### ISSUE TITLE
UserJoined and UserLeft issues

### ISSUE THREAD

**Issue by 1GX** [RogueException/Discord.Net#1796]
The UserJoined and UserLeft events are not being called when a user joins or leaves the guild.

**Comment by SylveonDeko** [comment]
Do you have intents enabled in dev settings?

**Comment by 1GX** [comment]
Is this something new? Last I used my bot was around a year ago, I updated the nuget package and all the other events work besides those two. If it is new where would i find this? Thanks

**Comment by SylveonDeko** [comment]
This would be under your bot settings in the dev panel, should be user intents and server intents where you change your bot name

**Comment by 1GX** [comment]
Cool thank you!

**Comment by SubZero0** [comment]
Closing as it's solved.
