### ISSUE TITLE
ReplyAsync(... messageReference) doesn't reply

### ISSUE THREAD

**Issue by Noxxys** [RogueException/Discord.Net#1798]
Discord.Net version: 2.3.1
Console app written in .NET 5.0

Hi. I'm trying to use `ModuleBase.ReplyAsync` to reply to the message that sent the command. Using the code below, the bot only sends a message to the proper channel, but not as a reply to the original message:

```C#
[Command("hello")]
public async Task ReplyHello()
{
    await ReplyAsync(
        "This doesn't reply the hello message",
        messageReference: Context.Message.Reference)
        .ConfigureAwait(false);
}
```
However, if I use the extension method `IUserMessage.ReplyAsync()`, then the reply works fine:
```C#
[Command("hello")]
public async Task ReplyHello()
{
    await Context
        .Message
        .ReplyAsync("This replies the hello message properly")
        .ConfigureAwait(false);
}
```

**Comment by zbroderson** [comment]
Message.Reference will not give you a usable reference for replying.  It gives you the reference that the target message is replying to (among other cases).  Use the constructor to create a message reference obj instead

**Comment by erxkk** [comment]
This has legacy reasons, the ModuleBase#ReplyAsync was introduced before replies were a thing and didn't get changed to avoid breaking changes.

**Comment by Noxxys** [comment]
Wow, that was fast, thank you for the quick answer. It works fine using `messageReference: new MessageReference(Context.Message.Id)` in my first example. Cheers.

**Comment by SubZero0** [comment]
Closing as its solved.
