### ISSUE TITLE
Moment at which Discord.NET actually creates an instance of modules

### ISSUE THREAD

**Issue by ghost** [RogueException/Discord.Net#1799]
I'm looking for the code Discord.NET uses to create an instance of classes implementing ModuleBase, more specifically the moment it reads the parameters of a class and uses DI to pass the valid parameters. Unless it doesn't do that all and in which case I'll find it myself.

No need to give me an explanation, just show me the file and the line where the whole process starts. I'm looking for inspiration for a project I'm working on. Thanks for your time

**Comment by k-boyle** [comment]
<https://github.com/discord-net/Discord.Net/blob/1b64d19c845cb7c612a1c52288c8b44cff605105/src/Discord.Net.Commands/Builders/ModuleClassBuilder.cs#L201-L228>
creates the command callback, then the rest is kind of all over the place but
<https://github.com/discord-net/Discord.Net/blob/1b64d19c845cb7c612a1c52288c8b44cff605105/src/Discord.Net.Commands/CommandService.cs#L504>
<https://github.com/discord-net/Discord.Net/blob/1b64d19c845cb7c612a1c52288c8b44cff605105/src/Discord.Net.Commands/Info/CommandInfo.cs#L179>
<https://github.com/discord-net/Discord.Net/blob/1b64d19c845cb7c612a1c52288c8b44cff605105/src/Discord.Net.Commands/CommandParser.cs#L17>

**Comment by ghost** [comment]
Alright, thanks for the help

I wish I could link to the github repository so you could see what's going on but it's private, maybe in a close future it'll be open.
