### ISSUE TITLE
Unable to SyncPermissionsAsync by ID.

### ISSUE THREAD

**Issue by ImNoOSRS** [RogueException/Discord.Net#1802]
In my case i have a channel id and im unable to get a RestTextChannel, it always nulls or doesnt work with SyncChannelsAsync

When i create a channel i can grab the creaeted RestTextChannel, and then Sync it.

But after that im unable to achieve this using the channelid.

Converting ISocketMessageChannel to RestTextChannel does not work either or getting it from the guild.

**Comment by zbroderson** [comment]
Well, a ISocketMessageChannel will never be a RestTextChannel.  However, they can be a SocketTextChannel, which also has SyncPermissionsAsync on it, so try casting to a SocketTextChannel.

**Comment by ImNoOSRS** [comment]
> Well, a ISocketMessageChannel will never be a RestTextChannel.  However, they can be a SocketTextChannel, which also has SyncPermissionsAsync on it, so try casting to a SocketTextChannel.

I dont think a SocketTextChannel has the featur to sync

**Comment by zbroderson** [comment]
@ImNoOSRS 
The docs say it does:
https://docs.stillu.cc/api/Discord.WebSocket.SocketTextChannel.html#Discord_WebSocket_SocketTextChannel_SyncPermissionsAsync_Discord_RequestOptions_

**Comment by ImNoOSRS** [comment]
> @ImNoOSRS 
> 
> The docs say it does:
> 
> https://docs.stillu.cc/api/Discord.WebSocket.SocketTextChannel.html#Discord_WebSocket_SocketTextChannel_SyncPermissionsAsync_Discord_RequestOptions_
> 
> 

It has Add and Remove etc not a SyncPermissionsAsync like the rest channel

**Comment by zbroderson** [comment]
[It does](https://api.zackbroderson.com/images/MjAyMS0wMy0yMF8xMy0zMy5wbmc=.png)

[Source Code](https://github.com/Still34/Discord.Net/blob/docs/pre-release/src/Discord.Net.WebSocket/Entities/Channels/SocketTextChannel.cs/#L36)

**Comment by ImNoOSRS** [comment]
I realised this is implented in the latest Discord.NET and i was using the old one, thankyou!
