### ISSUE TITLE
How to DM some user after bot restarts?

### ISSUE THREAD

**Issue by Sarodh** [RogueException/Discord.Net#1804]
Hello, I'm currently trying to implement a notification pattern with the bot. 

The user registers to be notified of a future event, e.g:  `!notify me of x`. Now the problem I'm having is incase the bot restarts my Discord connections are reset and even though I have the user ID and channel ID I'm still not able to connect and reply to them.

**Comment by SubZero0** [comment]
If you don't have the user cached, you can use the rest client (Rest property in the socket client) to get the user and then `SendMessageAsync`.

**Comment by Sarodh** [comment]
Resolved by using either Rest client or Webhooks.
