### ISSUE TITLE
Running the ping command example, the client is logging "Unknown Dispatch (INTERACTION_CREATE)"

### ISSUE THREAD

**Issue by Moises-Soares** [RogueException/Discord.Net#1809]
I am running your example and:
- the client is logging Unknown Dispatch (INTERACTION_CREATE).
- discord is showing This interaction failed

My commands are: 

{
    "name": "ping",
    "description": "get a ping pong",
    "options": []
}

**Comment by zbroderson** [comment]
Is this a slash command?  Slash commands have not been merged yet.  Any issues related to their use are best posted on those pull requests

If these are not slash commands it should safe to ignore the message.

**Comment by Moises-Soares** [comment]
Yes, it is a slash command.

**Comment by quinchs** [comment]
Slash commands are available by cloning pull #1717, they are not yet available on the dev branch.

**Comment by MrCakeSlayer** [comment]
This has now been implemented via the merged labs PR (#1923)
