### ISSUE TITLE
how to send links

### ISSUE THREAD

**Issue by jcmag** [RogueException/Discord.Net#1810]
Hi,

I'm using ReplyAsync to send text from my bot, and I'd like to send links using the markdown format: \[text\](link)
but if I do :

`await ReplyAsync("[text](link)");`

in the channel I receive \[text](link) as is...
what am I doing wrong?

**Comment by Joe4evr** [comment]
Markdown links only work inside of embeds.

**Comment by jcmag** [comment]
I've just tried the first example of embed (https://docs.stillu.cc/api/Discord.EmbedBuilder.html), and the message received in the channel is empty...

**Comment by SubZero0** [comment]
> I've just tried the first example of embed (https://docs.stillu.cc/api/Discord.EmbedBuilder.html), and the message received in the channel is empty...

You need to have "Show website preview info from links pasted into chat" enabled to see embeds if that's what you meant.

**Comment by jcmag** [comment]
Thanks! I'm really new to Discord ^^
