### ISSUE TITLE
Support for Markdown URL Hover Text

### ISSUE THREAD

**Issue by Micalobia** [RogueException/Discord.Net#1811]
Something you can do in Markdown for URLs, on top of the standard `[Name](URL)` is do something like `[Name](URL "Hover Text")`, and support for that in `Discord.Format.Url` would be nice.

Example: `[Google](https://google.com "To Google")` => [Google](https://google.com "To Google")

**Comment by erxkk** [comment]
We have no influence over that, that's a discord client issue.

**Comment by Micalobia** [comment]
I'm not sure what you mean, Discord does support that kind of formatting unless I'm misunderstanding what you're saying.

**Comment by Still34** [comment]
I'm not aware of such feature being an API feature.
