### ISSUE TITLE
Is there any which to check which Precondition failed in CommandExecuted

### ISSUE THREAD

**Issue by Hamsterland** [RogueException/Discord.Net#1812]
Title.

**Comment by Hamsterland** [comment]
On an extended note, should `CheckPermissionsAsync` return a concrete `PreconditionResult` at all? It would be much more flexible to be able to return a custom implementation of the `IResult` interface directly.

**Comment by csmir** [comment]
PreconditionResult is extendable, and can be used to add additional information. This feature can be used to solve both of your questions.
