### ISSUE TITLE
GetUser(string username, string discriminator) always returns null

### ISSUE THREAD

**Issue by cracksii** [RogueException/Discord.Net#1813]
I have  an application that communicates with the client via dm channels. The goal is, that a user can challenge another user with a dm just like that: `challenge "Some User#1234"`. My application can parse the input correctly, but the GetUser method always returns null except the user I want to get is the challenger. My code looks like that:
```
private async Task MessageReceived(SocketMessage message)  // Handles the incoming messages
{
    if(!isValid(message))  // Checks if the channel is a dm channel
        return;

    List<string> args = await Parse(message as IUserMessage);

    if(args[0] == "challenge" && args.Count > 1)
    {
        try
        {
            if(args[1].Length > 5 && args[1][^5] == '#')
            {
                await SimpleEmbed(client.GetUser(args[1].Split('#')[0], args[1].Split('#')[1]).GetOrCreateDMChannelAsync() as ISocketMessageChannel, "Challenge", $"{message.Author.Username + "#" + message.Author.Discriminator} challenged you for a chess game");
                await SimpleEmbed(message.Channel, "Challenge", $"Succesfully challenged {args[1]}", new Wrapper(GREEN));
            }
            else
                await Error(message.Channel, "The username has to be specified like this: \"Username#tag\"");
        }
        catch
        {
            await Error(message.Channel, "An error occured while trying to challenge somebody");
        }
    }
}
```

I have read about a somehow similar issue with problems when getting a user with its id, and because of that I have enabled both presence and user intent for my bot. I think its probably a problem with the api, because I am using the latest Discord.Net version 2.3.1. Maybe someone can help me?

EDIT:
I tried sending the challenge not in a dm channel but in a guild and doing that I received the same error, but when I then tried to challenge via dm it suddenly worked. I have no idea what to do.

**Comment by cracksii** [comment]
This issue has  been fixed

**Comment by uatec** [comment]
What was the solution? I have the same issue i think, but noone writes down how they solved their problems.

**Comment by cracksii** [comment]
For me it just worked at some point and thats why I thought it was an api problem, that had been fixed by discord.

But when I saw you having the same problem I tried to remember the modifications I did to the code after I had the problem. 

I dont have my code right here, because I changed my pc, but the main problem in my opinion occurs when you call the synchronus `GetUser` method from the asynchronus `MessageReceive` function.

I am not an expert at this topic, but I can imagine, that the return value gets lost somewhere around there so maybe something like this will work `var User = await Task.Run(client.GetUser(name, discriminator))`.

The `Task.Run` method does nothing else, than executing synchronus code asynchronusly on the thread pool, so the problem should be fixed.

I currently have no other ideas but on monday the 8th I should be able to send you my working code.

Let me know, if it works.

**Comment by cracksii** [comment]
After reading my code again I have to tell that it works without the solution I suggested above. The problem is, that the code changed a lot and is now very different from what I posted, when I opened the issue. But anyway here is the code I am using now:
```
if(args.Count == 2)
{
	var user = await api.GetUser(args[1]);  // Gets an user object from the api. It contains all connected clients...
	if(user == null)
		new Thread(new ThreadStart(() => Error(message.Channel, $"User with username `{args[1]}` wasn't found"))).Start();  // I am creating a new thread, because the error-message has to be deleted after a delay and the program shoudn't freeze
else
{
	if(user.Authenticated.ContainsKey(ClientType.Discord))  // Check if user has a discord client authenticated
	{
		var stuff = await api.CreateGame(api.GetUserFromDiscordName(message.Author.ToString()).Result.Username, user.Username);  // Create game with the senders account
		await Task.Run(() => pendingGames.Add(stuff.Split(" ")[0].ToLower(), user.Authenticated[ClientType.Discord]));  // Queue the game 
		await SimpleEmbed(client.GetUser(user.Authenticated[ClientType.Discord].Split("#")[0], user.Authenticated[ClientType.Discord].Split("#")[1]), "Challenge", $"`{api.GetUserFromDiscordName(message.Author.ToString()).Result.Username}` challenged you for a game chess! `{prefix}accept` to accept the challenge!");  // Send the challenge message. 
	}
	else if(user.Authenticated.Count > 0)
	{
		// TODO: Send request to the other plattform
	}
	else
	{
		new Thread(new ThreadStart(() => Error(message.Channel, $"User `{args[1]}` has no clients authenticated with his account."))).Start();
		return;
	}
	await SimpleEmbed(message.Channel, "Challenge", $"Succesfully challenged `{args[1]}`", new Wrapper(GREEN));
}
```

I could think about a problem, when parsing the args or just something else. I really don't know anything more, but I hope I were able to help you. If not, just join the Discord API Server right [here](https://discord.gg/discord-api) and ask your question there.

**Comment by cracksii** [comment]
Anyone, who found a solution is welcome and asked to post it.

 Thank you

**Comment by Anu6is** [comment]
Enable intents in the dev portal and specify them in your code

**Comment by cracksii** [comment]
> Enable intents in the dev portal and specify them in your code

I just went to my portal and can state, that this is probably the solution, because I activated it for my application, just like Anu6is explained. 
I will leave this issue open for a week or two, so you can wright, if it is still not working properly.

Thanks for your solution Anu6is!
