### ISSUE TITLE
Newlines are ignored with `params string[]` as command parameter

### ISSUE THREAD

**Issue by rednir** [RogueException/Discord.Net#1814]
```cs
[Command("temp")]
public async Task Temp(params string[] input)
{
    string message = string.Join(' ', input);
    await ReplyAsync(message);
}
```
If I typed in Discord:
```
!temp hello

world
```
I get the reply `hello world` without newlines.
Shouldn't `input` be something along the lines of `{ "hello\n\n", "world" }`?

**Comment by LedgendODST** [comment]
Add a remainder attribute like [Remainder] string test

**Comment by JerzyKruszewski** [comment]
Instead of this:
```
[Command("temp")]
public async Task Temp(params string[] input)
{
    string message = string.Join(' ', input);
    await ReplyAsync(message);
}
```
Try this:
```
[Command("temp")]
public async Task Temp([Remainder]string message)
{
    await ReplyAsync(message);
}
```

More info: https://docs.stillu.cc/api/Discord.Commands.RemainderAttribute.html

**Comment by rednir** [comment]
I did come across this solution eventually. I suppose these two methods pretty much cover all use cases, so no point in leaving this issue open.
