### ISSUE TITLE
DiscordSocketClient's ReactionAdded Cacheable msg returns RestUserMessage rather than SocketUserMessage

### ISSUE THREAD

**Issue by dill0wn** [RogueException/Discord.Net#1816]
Problem:

I expect DiscordSocketClient to deal solely with SocketBlank entities where applicable. However in a snippet like this returns a RestUserMessage:
```csharp
public class CommandListeners
{
    private readonly IServiceProvider services;
    private readonly CommandService commands;
    private readonly DiscordSocketClient client;

    public CommandListeners(IServiceProvider services, CommandService commands, DiscordSocketClient client)
    {
        this.services = services;
        this.commands = commands;
        this.client = client;

        // elsewhere commands.AddModuleAsync() has already been run...

        client.ReactionAdded += this.HandleReactionAdded;
    }

    private async Task HandleReactionAdded(Cacheable<IUserMessage, ulong> msgCache, ISocketMessageChannel channel, SocketReaction reaction)
    {
        // message is Discord.Rest.RestUserMessage
        var message = await msgCache.GetOrDownloadAsync(); 
        // next line throws compile error as message isn't correct type. 
        // ...also casting `message as DiscordSocketMessage` gives a null value
        var commandContext = new DiscordCommandContext(this.client, message); 
        // throws error
        var result = await commands.ExecuteAsync(commandContext, "ping", this.services);
        Console.WriteLine("CommandListeners executed command {0}", result);
    }
}

public class PingModule : ModuleBase<SocketCommandContext>
{
    [Command("ping")]
    public Task SayAsync() => ReplyAsync("pong");
}
```

(Forgive me, this a a cleaned up snippet taken from my larger project and hasn't been tested to compile).

I thought I would instead be able to `GetMessageAsync` since the `channel` param is an instance of SocketTextChannel.
```csharp
var message = await channel.GetMessageAsync(msgCache.Id);
```

But that result is ALSO an instance of RestUserMessage.

It doesn't look like there are any problems (yet) if I just convert my module to use a basic `CommandContext` and ExecuteAsync's context to be a `CommandContext`, so it's not a huge problem. However, I am not sure of the implications of either implementation down the road.

**Comment by zbroderson** [comment]
You're receiving a RestUserMessage because the message in question is not in the internal message cache (or u dont have the message cache enabled).  Since the message is not cached you must use the REST api to fetch the message.

Also you can make a custom command context.
