### ISSUE TITLE
How to use DiscordSocketConfig with Sample 02

### ISSUE THREAD

**Issue by MoonTM-GIT** [RogueException/Discord.Net#1818]
Im trying to add a config to something based on the [Sample 02](https://github.com/discord-net/Discord.Net/tree/dev/samples/02_commands_framework). 

Where would I put the config if I define it like this:

`var config = new DiscordSocketConfig
{
    AlwaysDownloadUsers = true,
};`

**Comment by erxkk** [comment]
It goes into the DiscordSocketClient ctor, see, you could've just asked on the discord server that is linked on the README.
Don't open an issue to ask for help.

EDIT:
The linked sample is also 10 months old.

**Comment by MoonTM-GIT** [comment]
Oh sorry, didn't know about that discord. Thank you though
