### ISSUE TITLE
How would I make this work?

### ISSUE THREAD

**Issue by 1GX** [RogueException/Discord.Net#1819]
How would I make the following work.
if (Context.Channel.GetType() == ChannelType.DM)

GetType returns a type and ChannelType cannot be compared to Type. Thanks

**Comment by zbroderson** [comment]
Pattern match Context.Channel for IDMChannel.

Also feel free to join the support channel to ask questions instead of opening issues (https://discord.gg/discord-api)

**Comment by 1GX** [comment]
Cool i'll join that now. And what do you mean by pattern match?

**Comment by zbroderson** [comment]
https://docs.microsoft.com/en-us/dotnet/csharp/pattern-matching

**Comment by 1GX** [comment]
Thanks figured it out
