### ISSUE TITLE
Dm people of a given server?

### ISSUE THREAD

**Issue by diogoribeirodev** [RogueException/Discord.Net#1820]
Anyone knows if it's posssible to dm members of a given server? I am trying to do it but it's just too hard for me i guess.

**Comment by zbroderson** [comment]
Check these docs
Extension Method:
https://docs.stillu.cc/api/Discord.UserExtensions.html#Discord_UserExtensions_SendMessageAsync_Discord_IUser_System_String_System_Boolean_Discord_Embed_Discord_RequestOptions_Discord_AllowedMentions_

Manual Method:
https://docs.stillu.cc/api/Discord.WebSocket.SocketUser.html#Discord_WebSocket_SocketUser_GetOrCreateDMChannelAsync_Discord_RequestOptions_

**Comment by diogoribeirodev** [comment]
Yeah, couldn't do it...
Even watch this videos, but still wasn't able, i guess i will never be able to be a developer...
https://www.youtube.com/watch?v=IcnuPWyxMes&ab_channel=Avient
https://www.youtube.com/c/CodingwithEfehan/videos
https://www.youtube.com/watch?v=uOV1rg_ecMo&ab_channel=CodingwithEfehan
