### ISSUE TITLE
User-Feeback if a command does not exist

### ISSUE THREAD

**Issue by DaNeubi** [RogueException/Discord.Net#1822]
Hey there,

I'm struggling to find a spot, where I can return some user feedback if a command does not exist.
So far I can see, the command gets executed, but there is nowhere where I could give the user some feedback.
I couldn't find anything among the existing and closed issues. If I missed out on one, please let me know!

Thanks ahead.

**Comment by erxkk** [comment]
See the guide section for post execution handling on the docs. It shows how to properly handle the results given back by any command, failed or not.

**Comment by DaNeubi** [comment]
Thanks, I overlooked that.
