### ISSUE TITLE
How do i declare the variable context?

### ISSUE THREAD

**Issue by diogoribeirodev** [RogueException/Discord.Net#1823]
I keeps seeing people's code and a variale called context! Where and how do i declare it?This is what i have currently
P.s: I am trying to build a bot do dm users.

public static void Main(string[] args)
        => new Program().MainAsync().GetAwaiter().GetResult();

        private DiscordSocketClient _client;

        public async Task MainAsync()
        {
            _client = new DiscordSocketClient();
            var token = File.ReadAllText("token.txt");
            await _client.LoginAsync(TokenType.Bot, token);
            await _client.StartAsync();
            await Task.Delay(-1);
        }
public async Task dmUser(ulong userid, string message)
        {
            
        }

**Comment by TheNoodleMummy** [comment]
Context is a property thats inherited from moduleBase<T>.
Have a read tough [The docs](https://docs.stillu.cc/guides/commands/intro.html) note that this only works when in a module is loaded and all trough the commandservice.
If you have anymore question [Join discord-api](https://discord.gg/discord-api) and look for the channel name #dotnet_discord-net.
