### ISSUE TITLE
Bot's voice client blocks all other voice clients on network

### ISSUE THREAD

**Issue by rednir** [RogueException/Discord.Net#1833]
When my bot's voice client is connected, no other device on my network can connect to that voice channel. The bot can still stream audio without fault.
If I'm already in the voice channel and then the bot joins, I will stop receiving audio and Discord will tell me I have 5000ms ping.

Previously with the exact same code, I have been able to be in the same channel as my bot just fine. Recently I got it working out of nowhere by changing nothing, then reconnected the bot to the voice channel I was in, and the issue returned. So it feels completely random.

[Here's a video](https://streamable.com/wrvs8i) (Rythm used to show when I get disconnected)

**Comment by quinchs** [comment]
This might be something related to your home network as im unable to reproduce it. I've developed music bots with dnet and have had no issue with being in the call at the same time with my bot running on the same computer.
