### ISSUE TITLE
Can no longer add multiple reactions with v2.3.1

### ISSUE THREAD

**Issue by gsemac** [RogueException/Discord.Net#1834]
Under release `2.3.1`, attempting to add more than one reaction to a message results in getting immediately rate-limited after the first reaction is added. When this occurs, execution will halt until `AddReactionsAsync` finally times out and the second reaction is never added. 

This issue is very easy to reproduce with the following command:
```csharp
[Command("test", RunMode = RunMode.Async)]
public async Task Test() {

    IUserMessage message = await ReplyAsync("test");

    await message.AddReactionsAsync(new[] {
        new Emoji("👍"),
        new Emoji("👎"),
    });

}
```
This has been happening since release `2.2.0`, but does **not** occur in `2.1.1`.

Manually adding a 250ms delay between reactions mitigates the problem, but manual rate-limiting like this is inconvenient for obvious reasons, especially across multiple threads (i.e. when using `RunMode.Async`).

**Comment by th0mk** [comment]
Related Discord issue: https://github.com/discord/discord-api-docs/issues/2886#issuecomment-833204108

**Comment by marens101** [comment]
[discord/discord-api-docs#2886](https://github.com/discord/discord-api-docs/issues/2886#issuecomment-833836834)   
Discord says issue resolved

**Comment by gsemac** [comment]
Thanks for the responses, guys. It does seem to be resolved now, so I'm closing this issue.

That said, the delay when adding reactions with `2.3.1` is oddly still far more noticeable than with `2.1.1`.
