### ISSUE TITLE
tell me how to make the bot write first

### ISSUE THREAD

**Issue by 0KEKC0** [RogueException/Discord.Net#1836]
the task is this: write a message to a person with whom the bot has not previously contacted in any way

**Comment by k-boyle** [comment]
This is a really good challenge, can't wait to see the solutions!

**Comment by sudo-gab** [comment]
dw guys this isn't malicious intent at all! just trust me!

**Comment by quinchs** [comment]
You can look at [SocketUser.GetOrCreateDMChannelAsync](https://github.com/discord-net/Discord.Net/blob/dev/src/Discord.Net.WebSocket/Entities/Users/SocketUser.cs#L97) to get a `IDMChannel` to send messages to.

**Comment by 0KEKC0** [comment]
I can't do something (maybe I'm stupid), can I use an example?

**Comment by quinchs** [comment]
```cs
// First we need the user who we want to send this message to, if you are using a command for this you can use Context.User, otherwise you can get the user via Client.GetUser(id);
var user = Context.User;

// Next we need to get the dm channel to send messages to, we can do this with SocketUser.GetOrCreateDMChannelAsync
var channel = await user.GetOrCreateDMChannelAsync();

// Next we can send the message with IDMChannel.SendMessageAsync();
var message = await channel.SendMessageAsync("Hello! This is a DM message!");
```

**Comment by 0KEKC0** [comment]
Client.GetUser(id) will return the user only if earlier at least somehow she interacted for example there is a common group or something like this. And I need to write useru from which there were no contacts at all. 
`
            DiscordSocketClient Client = new DiscordSocketClient();
           
            Client.Log += (msg)=>
            {
                Console.WriteLine(msg.ToString());
                return Task.CompletedTask;
            };

            Client.Connected += ()=> 
            {
                SocketUser user1 = null, user2 = null;
                user1 = Client.GetUser(543109179636973600);
                user2 = Client.GetUser("kekc","7561");

                if (user1 != null || user2 != null)
                    Console.WriteLine("Eureka");

                return Task.CompletedTask;
            };
           
            Client.LoginAsync(TokenType.Bot, "Token");
            Client.StartAsync();

            while (true)
            {
                Console.ReadLine();
            }
`
user1 and  user2 will be null

**Comment by quinchs** [comment]
You can only DM users who are in a mutual guild. If this was not the case, discord would be filled with "local women in your area want to dm you" bots.

**Comment by 0KEKC0** [comment]
Well, how does the official discord client also add new friends?

**Comment by quinchs** [comment]
Bot users _cannot_ add people as friends.

**Comment by AntiTcb** [comment]
> Well, how does the official discord client also add new friends?

The official client does *tons* of things that bots cannot do. Naturally, the company that makes the entire product can do things that they don't provide access for everyone to do.
