### ISSUE TITLE
Simple multiple channel receiver

### ISSUE THREAD

**Issue by ffbboy30** [RogueException/Discord.Net#1841]
Hi,
I don't find the way to make a massage receiver for multiple server.
Do you have a sample that explain how to create the channel between the client and the server ?

Thanks

**Comment by DaNeubi** [comment]
If I get your question correct, you want to be able to listen to multiple channels for commands?

As far as I know, the `HandleCommandAsync(SocketMessage message)` method will listen to every channel on the discord.

I restric this with a simple `if`:

In my case, the bot will only listen to messages sent to a channel called `bot-commands`
If you debug and set a breakpoint in your `HandleCommandAsync` method you will see, that every text input in the guild is calling this function.
```CS
// _configuration.General.CommandChannel = "bot-commands"
//Check that the message is executed in the bot-commands channel
            if (message.Channel.Name != _configuration.General.CommandChannel)
            {
                return;
            }
```

For your case this would be:

If you want to listen to either channels and don't care from where the message is from
```CS
//Check that the message is executed in the XXXX channel
            if (message.Channel.Name != "some-channel-name" || message.Channel.Name != "some-other-channel")
            {
                return;
            }
```

**Comment by ffbboy30** [comment]
Hi,
I've found the server ID with a right click on it but I don't find the solution to get the channel name in a server.
Thanks

**Comment by DaNeubi** [comment]
If you want to get a channel from a guild here's my way of doing it. I'm sure there is a better way but `It's working on my machine TM`

Code from my bot: [Sahnee-bot -> Util.GetBotCommandsChannel()](https://github.com/Sahnee-DE/sahnee-bot/blob/master/sahnee-bot/Util/GetBotCommandsChannel.cs)

```CS
        //Variables
        private readonly Logger _logger = new Logger();

        /// <summary>
        /// Gets the bot-commands channel of the given guild
        /// </summary>
        /// <param name="guild">the guild to get the channel from</param>
        /// <returns></returns>
        public async Task<IGuildChannel> GetBotCommandsChannelAsync(IGuild guild)
        {
            try
            {
                //get all guild channels and filter the bot-commands channel out of them
                IGuildChannel botCommandsChannel = null!;
                IReadOnlyCollection<IGuildChannel> guildChannels = await guild.GetChannelsAsync(CacheMode.AllowDownload);
                foreach (IGuildChannel guildChannel in guildChannels)
                {
                    if (guildChannel.Name == "bot-commands")
                    {
                        botCommandsChannel = guildChannel;
                    }
                }
                return botCommandsChannel;
            }
            catch (Exception e)
            {
                await _logger.Log(e.Message, LogLevel.Error, "GetBotCommandsChannel:GetBotCommandsChannelAsync");
                return null;
            }
        }
```

**Comment by ffbboy30** [comment]
Hi,
I've a studpi question about the utilization of the API.
What is the way to read channel message ?
I've a lot of code to make bot. I don't want this I just need to get messages from a friend channel.
I must create a bot ? and how can connect it to my friend channel ?
I never use discord and I found it not really easy to understand .
I've followed the discord.net tutorial but I don't find the goal to connect to my friend.
Thanks

**Comment by DaNeubi** [comment]
You need to create a bot.
As mentionend above, the bot will listen to all Channels.
There is a verry good Step by Step guide [https://docs.stillu.cc/guides/introduction/intro.html](https://docs.stillu.cc/guides/introduction/intro.html)

If you want to get the messages on any guild, the bot needs to be on that guild.

**Comment by ffbboy30** [comment]
Yes, I've understand this. I will make my app with telegram is it possible to do what I want.

Thanks
