### ISSUE TITLE
Discord Bot Not Logging In!

### ISSUE THREAD

**Issue by CodeDiseaseDev** [RogueException/Discord.Net#1843]
So just opened a new project and installed Discord.Net so I could create a Discord bot.

But when I ran the program it fires the loggedIn event like normal but the bot is offline and its not responding to commands.

I then use the log event to see whether it was connecting to Discords gateway but no, it just tells me the API version and that's it.

Here's my code:

```cs
static void Main(string[] args)
{
    new Thread(async () =>
    {
        client.LoggedIn += OnLoggedIn;
        client.MessageReceived += OnMessageReceive;
        client.Log += Client_Log;
        await client.LoginAsync(TokenType.Bot, token);
    }).Start();

    Thread.Sleep(-1);
}

private static Task Client_Log(LogMessage arg)
{
    Console.WriteLine(arg);
    return Task.CompletedTask;
}

static DiscordSocketClient client = new DiscordSocketClient();

static string token = "My token goes here.";

private static Task OnLoggedIn()
{
    Console.WriteLine("logged in.");
    return Task.CompletedTask;
}

private static Task OnMessageReceive(SocketMessage arg)
{
    Console.WriteLine(arg.Content);
    return Task.CompletedTask;
}
```
![Screenshot_3](https://user-images.githubusercontent.com/70626250/118764245-85051f80-b8bc-11eb-8225-c63494ee86de.png)

**Comment by dropout1337** [comment]
u forgot to make the token h4xor

**Comment by erxkk** [comment]
Why are you dispatching a thread yourself and then blocking the main thread forever? What's with the static abuse? You should be following the [guides](https://docs.stillu.cc/guides/introduction/intro.html) in the docs unless you know what you're doing, and quite frankly, you don't.
There's high chance something is failing and not getting picked up because you sent it to the other thread manually without any regard for error handling.

**Comment by CodeDiseaseDev** [comment]
i got rid of the new thread and now ive got it running on the main thread but its still doing nothing.

**Comment by CodeDiseaseDev** [comment]
```cs
static void Main(string[] args)
{
    AsyncMain();
    while (true) { }
}

static async Task AsyncMain()
{
    client.LoggedIn += OnLoggedIn;
    client.MessageReceived += OnMessageReceive;
    client.Log += Client_Log;
    await client.LoginAsync(TokenType.Bot, token);
}

private static Task Client_Log(LogMessage arg)
{
    Console.WriteLine(arg);
    return Task.CompletedTask;
}

static DiscordSocketClient client = new DiscordSocketClient();

static string token = "My token goes here.";

private static Task OnLoggedIn()
{
    Console.WriteLine("logged in.");
    return Task.CompletedTask;
}

private static Task OnMessageReceive(SocketMessage arg)
{
    Console.WriteLine(arg.Content);
    return Task.CompletedTask;
}
```

also
without the `while(true) {}` in the main function it just closes instantly...

**Comment by erxkk** [comment]
Consider using `async Task Main(string[] args)` with a `await Task.Delay(-1);` at the end instead of synchnonously blocking.
Stop using static fields as you are now and then make sure you have the correct token supplied.

EDIT:
You also shouldn't be opening Issues on GitHub for what is clearly a "help why doesn't this work" kinda question. Issues are reserved for actual library problems.

**Comment by CodeDiseaseDev** [comment]
it is a library problem!! its still not logging in. and ive made a bot with discord.net before

**Comment by erxkk** [comment]
If it was a library problem it then it wouldn't work for everybody else as well wouldn't it? You still haven't checked for the correct token have you?

**Comment by CodeDiseaseDev** [comment]
my token works perfectly with discord.js

**Comment by erxkk** [comment]
I've been made aware on the discord that you're not calling StartAsync on your client, there for obviously no gateway connection is started.

**Comment by erxkk** [comment]
Now close the issue and next time before assuming you're infallible, stop and think if it even makes sense that only you are having a library wide issue. Read the guides before doing whatever you're doing, stop the static abuse and thread spawning. And if you have other issue, ask on the discord, this is not a help forum.

**Comment by dodoflix** [comment]
I came here and thought why this has too many issue post and i see now why guys this is a not help forum and there's a basic guide how to use it.

**Comment by DaNeubi** [comment]
You are missing
```CS
 await client.StartAsync();
 ```
As mentioned in [Start making a bot](https://docs.stillu.cc/guides/getting_started/first-bot.html)

I would recommend you to use `await Task.Delay(-1);` as mentioned by @erxkk

**Comment by MrCakeSlayer** [comment]
@CodeDiseaseDev are you still having issues with this?
