### ISSUE TITLE
Support message components

### ISSUE THREAD

**Issue by frobinsonj** [RogueException/Discord.Net#1856]
Would be nice to see support added for message components.

![buttons](https://user-images.githubusercontent.com/16726902/119859560-6a125b00-bf0d-11eb-8c34-3055e487206e.png)

A consistent API to handle these interactions along with slash commands would be needed. See issue #1716 (Support discord slash commands)

https://support.discord.com/hc/en-us/articles/1500012250861-Bots-Buttons
https://discord.com/developers/docs/interactions/message-components

**Comment by quinchs** [comment]
Discord Message Components are supported in [Discord.Net Labs](https://github.com/Discord-Net-Labs/Discord.Net-Labs). I'm currently implementing them as they use my interaction PR.

Once all the bugs are squashed and we figure out the best way to use them a PR will be opened up here with the changes, In the mean time feel free to use Discord.net labs.

**Comment by frobinsonj** [comment]
> Discord Message Components are supported in [Discord.Net Labs](https://github.com/Discord-Net-Labs/Discord.Net-Labs). I'm currently implementing them as they use my interaction PR.

Thanks for sharing. I'll have a play with that. Not trying to push for this to be added prematurely or rushed, just thought I'd add an issue just to make sure it was seen :)

**Comment by quinchs** [comment]
Feel free to leave suggestions and feedback on the Discord.Net Labs repo!

**Comment by nitz** [comment]
It looks like [as of June 30, 2021](https://discord.com/developers/docs/change-log#june-30-2021), the API added support for [Select Menus](https://discord.com/developers/docs/interactions/message-components#select-menus). It's a component that presents itself as a single/multi select list UI, like so:

![image](https://user-images.githubusercontent.com/602691/124159070-b569dd00-da68-11eb-852d-565cd1423c5a.png)

Thought I'd leave a note for anyone doing the design on this side (@quinchs)!

Cheers

**Comment by quinchs** [comment]
Working on it, should have a testable version out on labs tmr

**Comment by quinchs** [comment]
@nitz Check out labs dev build. should have working select menu's

Metapackage: https://www.nuget.org/packages/Discord.Net.Labs/2.3.8-dev
Rest: https://www.nuget.org/packages/Discord.Net.Labs.Rest/2.3.9-dev
Websocket: https://www.nuget.org/packages/Discord.Net.Labs.WebSocket/2.3.9-dev
Core: https://www.nuget.org/packages/Discord.Net.Labs.Core/2.3.9-dev

**Comment by nitz** [comment]
Fantastic, that was lightning quick. I'll tinker with it this week!

**Comment by quinchs** [comment]
> Fantastic, that was lightning quick. I'll tinker with it this week!

The builds are no longer in dev so just use the most recent version

**Comment by TheTrueHonker** [comment]
So are the buttons in 2.4.0 and if yes, how do I use them?

**Comment by MrCakeSlayer** [comment]
This has now been implemented via the merged labs PR (#1923)
