### ISSUE TITLE
issue regarding member receiving

### ISSUE THREAD

**Issue by dabo123148** [RogueException/Discord.Net#1866]
Using version: 2.4.0
 Error started occurring in the last few hours, before was running smooth
 
 Serializer Error:
Newtonsoft.Json.JsonSerializationException: Error converting value {null} to type 'System.DateTimeOffset'. Path 'member.joined_at'. ---> System.ArgumentException: Could not cast or convert from {null} to System.DateTimeOffset.
   bei Newtonsoft.Json.Utilities.ConvertUtils.EnsureTypeAssignable(Object value, Type initialType, Type targetType)
   bei Newtonsoft.Json.Utilities.ConvertUtils.ConvertOrCast(Object initialValue, CultureInfo culture, Type targetType)
   bei Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
   bei Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   bei Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)

**Comment by d4n3436** [comment]
Related: https://github.com/discord/discord-api-docs/pull/2911

**Comment by quinchs** [comment]
This was fixed in #1923
