### ISSUE TITLE
Is there some way to access the module instance from ModuleInfo?

### ISSUE THREAD

**Issue by emctague** [RogueException/Discord.Net#1867]
I want to separate certain event handlers into modules - for example, if I have a `ReactRoles` module that provides a command to set up reaction-based roles, I would like to be able to define a handler for the `ReactionAdded` event *directly in the module* to keep it near to the relevant behaviour.

In theory, I could do this by registering the event handler within the module's constructor, but I feel that it would be cleaner if I could add use some annotation (e.g. `[OnReactionAdded]`) on a method to bind these events to a module. Doing that, I could bind the event handler during initialization:

```cs
await _commands.AddModulesAsync(Assembly.GetEntryAssembly(), _services);

foreach (var module in _commands.Modules)
{
    // TODO: Find some way to access the underlying module *object*
    // so that we can check its methods for [OnReactionAdded] and create bindings.
    // Eventually we'd do _client.ReactionAdded += whatever.
}
```

But I would need to be able to access the actual Module object here. Is there any way to access the underlying instance of a module given its ModuleInfo? (Or, some other stage at which I can access the created object?)

**Comment by Quahu** [comment]
Command modules are transient, you can't do that. Having a singleton `ReactRoles` service to go alongside the module is the correct approach here.
