### ISSUE TITLE
Embed Duplicates

### ISSUE THREAD

**Issue by svelluto** [RogueException/Discord.Net#1869]
I'm figuring out how to put thumbnails into Embeds. I followed the example from the documentation and that worked, but I noticed something string - embeds were being duplicated.

I'm using the Discord.Net Labs version 2.3.7 - for the buttons, love the buttons!

I have a simple command (!say) that just echos back what you type in an embed, with a button I was testing. Very simple.
What happens is when I run the command, it writes the embed. When I call it again, it writes the previous embed with the newest at the bottom. It will continue to do this, creating a list of embeds that it readds each time you run the command again.

I initially thought it was something with the SendFileAsync, while I was testing the thumbnail, but I switched it back to very simple code and SendMessageAsync, but it was still duplicating.

The stranger part is it persists if the bot is restarted, and it only happens on some channels with some embeds, not all of them.

**Comment by Quahu** [comment]
https://github.com/Discord-Net-Labs/Discord.Net-Labs/issues

**Comment by quinchs** [comment]
Going to close this as Labs has changed *alot* since this issue, if it still persist please open an issue on the labs repo which Quahu has kindly provided the link to.
