### ISSUE TITLE
Add the ability to modify modules/commands during runtime

### ISSUE THREAD

**Issue by FireController1847** [RogueException/Discord.Net#1875]
Yes, I know you have `AddModuleAsync`. But, think of this scenario: I fetch a database result from my database (or whatever reason you want to come up with), and I would like to dynamically add an alias during runtime. Currently, I cannot do this without completely recreating the module manually using the module builder. Wouldn't life be so much easier if we could just modify the CommandInfo or something along those lines?

I don't know how hard this would be to internally implement, but as an end user it appears as though that the command just has a readonly alias array. I'd assume an internal method to modify the array internally would work out well.

Maybe like an Command#addAlias and Command#removeAlias? And similar commands for other properties and whatnot?

I don't see the purpose in disallowing the user to edit this stuff during runtime and requiring them to recreate the entire module. It seems excessive... But maybe that's just me.

**Comment by FiniteReality** [comment]
Mutable commands are dangerous and are prone to race conditions. Immutable commands are much safer, since they're written once, and then can be read multiple times without a race condition. Keep in mind that every time a module or alias changes, we have to effectively scan the entire command tree; sometimes multiple times if there are many aliases.

The current "remove a module and rebuild it entirely" solution is about as good a middle-ground as we can get, since it walks through the tree the least and presents the smallest chance of hitting a race condition.

**Comment by FireController1847** [comment]
I absolutely understand the concern with race conditions. However, I do think the requirement to completely remove/recreate a module is excessively restrictive. Would doing this not have the same issues of a race condition? I don't think modifications to attributes to a command during runtime would create "breaking" race conditions per-say. I mean, if re-creating the entire module is done during runtime, would that not be far more dangerous because now you're removing an entire module and re-adding it, which not only could take quite a bit longer but also cause things related to the module to break entirely?

Race conditions are something developers have to deal with often, and I suppose there's a big trade off between "protecting the developer" and allowing "modification freedom" (as is shown by the constant debate between get/set, public, private, and protected protection levels).

**Comment by AraHaan** [comment]
I mean I understand this but cant you use Hot Reload to modify them though at runtime without needing any changes to Discord.Net?

**Comment by BobVul** [comment]
I did configurable aliases by preprocessing the message content (`input`) before it's passed into `ExecuteAsync`. This way also lets admins set their own per-guild aliases.

**Comment by FireController1847** [comment]
@BobVul Would you mind sharing a code snippet of how you did that? I couldn't seem to figure it out, I was having difficulty in my command handler understanding exactly how to ensure the right command is run, especially being unable to edit the message's content before it's parsed (which was a trick I used back when I used Discord.js - basically "trick" the library to think that the message actually said something else)

**Comment by BobVul** [comment]
```csharp
            var commandString = message.Content[argPos..];
            using (var scope = serviceProvider.CreateScope())
            {
                using (var db = scope.ServiceProvider.GetRequiredService<BotDbContext>())
                {
                    var alias = db.GuildCommandAliases.SingleOrDefault(ga =>
                        ga.Guild.DiscordGuildId == context.Guild.Id && commandString.StartsWith(ga.Alias));
                    if (alias != null)
                    {
                        commandString = alias.Target + commandString[alias.Alias.Length..];
                    }
                }
            }

            await commands.ExecuteAsync(
                context: context,
                input: commandString,
                services: context.ServiceScope.ServiceProvider);
```

Based on the [documented example command handler](https://docs.stillu.cc/guides/commands/intro.html).

Where `argPos` is set by `HasMentionPrefix`/`HasStringPrefix` and indicates the beginning of the actual command.

Note that the [`ExecuteAsync` overload originally called](https://github.com/discord-net/Discord.Net/blob/c46daaad19f86d4396c752010ccffc08aa144cee/src/Discord.Net.Commands/CommandService.cs#L491) uses `argPos` to `Substring` the message `Content` (to remove the bot prefix) before calling [the actual implementation](https://github.com/discord-net/Discord.Net/blob/c46daaad19f86d4396c752010ccffc08aa144cee/src/Discord.Net.Commands/CommandService.cs#L504) with the `Substring`'d command.

Here I just move that `Substring` into my own code so I can play with the unprefixed command before passing it in for execution. `commandString` is the message with the command prefix removed (i.e. message from `argPos` index onwards). Then it's just a matter of doing a database lookup for an alias that the `commandString` starts with, and replacing the alias with the alias target.

The actual `input` that gets passed into `ExecuteAsync` is this modified command.

So `"!alias foo bar"` => `"alias foo bar"` => `"target foo bar"` => `ExecuteAsync(input: "target foo bar", ...)`

---

Performance note, depending on command volume you might want to look at adding a database cache layer, or at least making sure the lookups are indexed. In my case, EF Core translates the `StartsWith` into something like `@__commandString_1 LIKE "g"."Alias" || '%'`, which you *definitely* don't want to do [without an index on the lookup column](https://dba.stackexchange.com/a/43444/156693). Something like a trie (or any other structure optimised for prefix-matching) in local memory might also help for high-volume. But I'm at the point where Discord network ops take *much* longer than any database lookup, and I assume that'd be the case as long as you're not at the point of needing sharding.

Also... I don't think the `CommandService` has a particularly optimised command matching anyway. So at the very least this shouldn't be any worse than loading an excessively large number of prefixes into the modules themselves.

**Comment by FireController1847** [comment]
I'm going to be honest, I didn't know you could just pass a command string to ExecuteAsync, I thought it had to be the parsed message... like you mentioned I had always been passing argPos. This will be helpful, thank you for the code and tips!

**Comment by quinchs** [comment]
Going to close this as FiniteReality's answer covers this concern, and it seems you've found a solution
