### ISSUE TITLE
Update max embed description length

### ISSUE THREAD

**Issue by BobVul** [RogueException/Discord.Net#1881]
While the official documentation is a bit behind, it appears that the API can now take up to 4096 characters in an embed description. Please consider updating the limits in [EmbedBuilder](https://github.com/discord-net/Discord.Net/blob/22bb1b02dd9ec20c2485657f1b55193e18df393f/src/Discord.Net.Core/Entities/Messages/EmbedBuilder.cs#L30) to match.

This is especially important for bots that may quote user messages (starboards, logging, etc.), since Nitro users can now post messages with over 2048 chars.

![Screenshot](https://cdn.discordapp.com/attachments/381887113391505410/858132902017499146/unknown.png) from https://discord.com/channels/81384788765712384/381887113391505410/858132903727464466 (Discord API server).

**Comment by mwpowellhtx** [comment]
To clarify in terms of `SocketGuild` or `SocketTextChannel` for example, `Name` and `Description` maximum lengths are `256` and `2048`, respectively? Thanks...

**Comment by Misha-133** [comment]
@mwpowellhtx please no more necroposting thanks. make a new discussion or ask in our support server.
______
those limits are a completely separate thing, not related to embeds in any way; and you can check them in both API docs and API spec;
Guild name must be from 2 to 100 characters long, description - from 0 to 120.
