### ISSUE TITLE
How to use logger in my module classes?

### ISSUE THREAD

**Issue by gac-noob** [RogueException/Discord.Net#1883]
Hi everyone,

Sorry to bother people here with a noob question, I'm very new to this...and I kinda get confused
especially with DependencyInjection...anyway...

Since main() is no longer using the following code: `var builder = new HostBuilder()..ConfigureLogging(x => { ... })` and is now using the `using (var services = ConfigureServices())`, I coded my ConfigureServices() like this:

```
private ServiceProvider ConfigureServices()
{
     return new ServiceCollection()
          .AddSingleton(new DiscordSocketClient(new DiscordSocketConfig
          {
               LogLevel = LogSeverity.Verbose,
               AlwaysDownloadUsers = true,
               MessageCacheSize = 200,
          }))
          .AddSingleton(new CommandService(new CommandServiceConfig
          {
               LogLevel = LogSeverity.Verbose,
               CaseSensitiveCommands = false,
               DefaultRunMode = RunMode.Sync
          }))
          .AddSingleton<CommandService>()
          .AddSingleton<CommandHandlerService>()
          .AddSingleton<HttpClient>()
          .AddSingleton<PSEWebApiService>()
          .BuildServiceProvider();
}
```

Questions:
1. How do I configure the logger and set properties like `SetMinimumLevel(LogLevel.Debug)`? It used to be part of the HostBuilder(), like this:

```
.ConfigureLogging(x =>
{
     x.AddConsole();
     x.SetMinimumLevel(LogLevel.Debug); 
})
```

But now, I don't know how to set it...

2. Also how do I call the logger function in my module classes such as `_logger.LogInformation($"{Context.User.Username} executed the ping command!")`? Before, I can use it this way:

```
public class TestModule : ModuleBase<SocketCommandContext>
{
     private readonly ILogger<TestModule> _logger;

     public TestModule(ILogger<TestModule> logger)
          => _logger = logger;

     [Command("ping")]
     public async Task PingAsync()
     {
          await ReplyAsync("Pong!");
          _logger.LogInformation($"{Context.User.Username} executed the ping command!");
     }
}
```

But now it does not work anymore, because it can't find the logger...

All help is highly appreciated! 🙏🙏🙏

**Comment by Hawxy** [comment]
As a note, support questions like these belong on the discord.net channel on the discord api guild, not github issues.

> Since main() is no longer using the following code: var builder = new HostBuilder()..ConfigureLogging(x => { ... }) and is now using the using (var services = ConfigureServices())

> It used to be part of the HostBuilder()

Why did you stop using the HostBuilder?

**Comment by gac-noob** [comment]
ohh...sorry sorry! I'll move to discord.net channel in discord..

But to answer why I stopped HostBuilder, is because I followed the code in:
_samples/02_commands_framework/Program.cs_ 

And I saw that there was no HostBuilder() and the code used the `using (var services = ConfigureServices())` configure the rest, and I also found the new code to be very clean and easy to understand...

But I don't know how to mix the new code with HostBuilder, so I thought there's a way to set it inside the `ConfigureServices()`

Thank you for the response sir @Hawxy !

**Comment by Hawxy** [comment]
If you were already using the HostBuilder, I'd recommend sticking with that and following examples in [my own repository](https://github.com/Hawxy/Discord.Addons.Hosting) and [other example repositories around github](https://github.com/Directoire/Discord.NET-Template). 

The examples in this repo are effectively 2-3 years old at this point, before generic hosting and logging were popular within the ecosystem.

**Comment by gac-noob** [comment]
Thank you very much sir @Hawxy !
