### ISSUE TITLE
Sticker.Count doesn't seem to provide any value other than 0 even when stickers are present

### ISSUE THREAD

**Issue by DeSinc** [RogueException/Discord.Net#1884]
Sticker.Count doesn't seem to provide any value other than 0 even when stickers are present. I made a simple "if (Msg.Sticker.Count > 0)" and when debugging a message which is just a sticker, or a text line with a sticker added to it, regardless I just get a 0 value.
https://cdn.discordapp.com/attachments/701382696525496371/860412833057472522/unknown.png

Currently I can't see a way of telling if a message has a sticker or not.

**Comment by MrCakeSlayer** [comment]
This has now been fixed via the merged labs PR (#1923)
