### ISSUE TITLE
Buttons?

### ISSUE THREAD

**Issue by TH3AL3X** [RogueException/Discord.Net#1885]

**Comment by erxkk** [comment]
Jesus christ, ignoring the fact that you are using an issue tracker to request a feature, did you even think about making a proper request?
You don't even provide anything useful ith that question. 

The library is currently being rewritten so you'll have to either use another library that already supports buttons or wait for the rewrite to finish.

**Comment by Anu6is** [comment]
Still got them a reasonable response though 🙃

**Comment by TH3AL3X** [comment]
> Jesus christ, ignoring the fact that you are using an issue tracker to request a feature, did you even think about making a proper request?
> You don't even provide anything useful ith that question.
> 
> The library is currently being rewritten so you'll have to either use another library that already supports buttons or wait for the rewrite to finish.

are you mad?

**Comment by TH3AL3X** [comment]
https://github.com/Discord-Net-Labs/Discord.Net-Labs
