### ISSUE TITLE
Constant connection errors followed by an Ubuntu Server crash

### ISSUE THREAD

**Issue by landynmj** [RogueException/Discord.Net#1887]
`02:04:05 Discord     Discord.Net v2.4.0 (API v6)
02:04:09 Gateway     Connecting
02:04:14 Gateway     Connected
02:04:15 Gateway     Ready
COMMAND > Landyn J#5729 is attempting to run > $hello with message ID > 861427919774416906
ERROR AB000 > Command 861427919774416906 returned Error:"Not Implemented"
03:00:25 Gateway     Discord.WebSocket.GatewayReconnectException: Server requested a reconnect
   at Discord.ConnectionManager.<>c__DisplayClass29_0.<<StartAsync>b__0>d.MoveNext()
03:00:25 Gateway     Disconnecting
03:00:25 Gateway     Disconnected
03:00:26 Gateway     Connecting
03:00:27 Gateway     Connected
03:00:27 Gateway     Resumed previous session
04:50:11 Gateway     Discord.WebSocket.GatewayReconnectException: Server requested a reconnect
   at Discord.ConnectionManager.<>c__DisplayClass29_0.<<StartAsync>b__0>d.MoveNext()
04:50:11 Gateway     Disconnecting
04:50:11 Gateway     Disconnected
04:50:12 Gateway     Connecting
04:50:13 Gateway     Connected
04:50:13 Gateway     Resumed previous session
07:34:12 Gateway     Discord.WebSocket.GatewayReconnectException: Server requested a reconnect
   at Discord.ConnectionManager.<>c__DisplayClass29_0.<<StartAsync>b__0>d.MoveNext()
07:34:12 Gateway     Disconnecting
07:34:12 Gateway     Disconnected
07:34:13 Gateway     Connecting
07:34:14 Gateway     Connected
07:34:14 Gateway     Resumed previous session
10:45:19 Gateway     Discord.WebSocket.GatewayReconnectException: Server requested a reconnect
   at Discord.ConnectionManager.<>c__DisplayClass29_0.<<StartAsync>b__0>d.MoveNext()
10:45:19 Gateway     Disconnecting
10:45:19 Gateway     Disconnected
10:45:20 Gateway     Connecting
10:45:21 Gateway     Connected
10:45:21 Gateway     Resumed previous session
`

**Comment by landynmj** [comment]
Then my server crashed

**Comment by zbroderson** [comment]
This looks like normal behavior. Discord will reconnect your bot whenever they feel like it. The reconnects look hours apart and they appear to successfully reconnect. I believe u have other issues
