### ISSUE TITLE
bot doesn't recognize commands

### ISSUE THREAD

**Issue by DrEnyo** [RogueException/Discord.Net#1889]
Hello, I'm trying to make a bot for my server. It logs in, but it doesn't seem to recognize any text at all. At this point the CommandHandler looks exactly like the one in this guide: https://docs.stillu.cc/guides/commands/intro.html I tried to put a console log inside HandleCommandAsync, but nothing showed up. I don't know what the problem might be. Any help would be appreciated.

**Comment by Anu6is** [comment]
You should consider joining the [discord-net](https://discord.gg/discord-api) channel if you're looking to trouble shoot an issue.
Do you actually instantiate your command handler and call `InstallCommandsAsync()`?

**Comment by DrEnyo** [comment]
> You should consider joining the [discord-net](https://discord.gg/discord-api) channel if you're looking to trouble shoot an issue.
> Do you actually instantiate your command handler and call `InstallCommandsAsync()`?

No, should I do it in `MainAsync()` ?
