### ISSUE TITLE
How to rename channel?

### ISSUE THREAD

**Issue by basi1ik** [RogueException/Discord.Net#1892]

**Comment by erxkk** [comment]
Stop posting issues (#1891,  this) that are literally just lack of any self effort, Discord.Net has a [docs page](https://docs.stillu.cc/), there's a [help guild](https://discord.gg/discord-api) and this is not a library issue but a question. You didn't even put enough effort into the issue itself, it has not description of what you tried already and what not.

**Comment by gnubufferoverflows** [comment]
Channel modifications are done with ModifyAsync:
```csharp

await channel.ModifyAsync(m =>
{
     // modify your channel here using m, as explained in the docs
});
```

**Comment by MrCakeSlayer** [comment]
Do you still need help with this @basi1ik ?

**Comment by basi1ik** [comment]
> Do you still need help with this @basi1ik ?

😄 No, thank you!
