### ISSUE TITLE
the  socketuser.SendMessageAsync dont works in certain situation

### ISSUE THREAD

**Issue by MCenters** [RogueException/Discord.Net#1895]
First  bot receives a message, the message contains some mention users  in its .mentionusers field
if we try to send message via  
var k=message.mentionusers.firstordefault
k.sendmessageasync("hi")

there will be indefinite wait time, no exception , no crash, just it get stucks somewhere in this command

**Comment by Anu6is** [comment]
It would be better if you showed actual reproduceable code. Additionally, ensure that you have proper logging enabled. The message should either be sent or throw an exception if you user has DMs disabled.

**Comment by Avabin** [comment]
> First  bot receives a message, the message contains some mention users  in its .mentionusers field
> if we try to send message via  
> var k=message.mentionusers.firstordefault
> k.sendmessageasync("hi")
> 
> there will be indefinite wait time, no exception , no crash, just it get stucks somewhere in this command

Just keep in mind that you are calling an async method that returns a task.

You need to await that task for the operation to complete.

Try something like this
```csharp
var user = message.MentionUsers.FirstOrDefault();
await user.SendMessageAsync("hi");
```

If you don't know what `await` is, I recommend reading through Microsoft documentation.

https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/async/

**Comment by MrCakeSlayer** [comment]
@tinedpakgamer are you still having issues with this?
