### ISSUE TITLE
No warning with malformed embed URL

### ISSUE THREAD

**Issue by cassandra288** [RogueException/Discord.Net#1897]
I'm not totally sure whether this is a bug for Discord.NET or the Discord API in general but there seems to be a problem when using URLs for images in embeds when the URL has a space in it.
Usually browsers supplement the space with %20 and everything works fine but when submitting the message to the discord API I get a 400 bad request error. I'm unsure of if it is intended behaviour by the Discord API, though if it is I feel Discord.NET should be throwing an error for a malformed URL.

**Comment by cassandra288** [comment]
Forgot to add, if you replace spaces with %20 manually, it does work.

**Comment by MrCakeSlayer** [comment]
This has now been implemented via the merged labs PR (#1923)
