### ISSUE TITLE
No Guild Data in Reactions

### ISSUE THREAD

**Issue by Wellendox** [RogueException/Discord.Net#1898]
I sure hope I am as blind as a bat, and what I say is not true, but here goes:

Are you guys leaving out guild information on reactions? You have a Cacheable<IUserMessage, that does not hold **any** guild data. You have a ISocketMessageChannel which does not hold **any** guild data. And the SocketReaction does not, wait for it... hold **any** guild data.

Guys, I really need to have the guild data for what I need to have my bot do. Something as simple as a role reaction is an absolute pain in the ass to work with.
How I solved it at the moment? 
Every single time I have my bot send an embed or message that people gotta react to (role reactions, polls and such) I have to save the messageID, and guildID in the database. Then, in the ReactionAdded event, first thing I do is run a SQL Query looking whether the message ID of the reaction is found in the database. If so, I do all my other stuff because I have the guild ID to do all other things with.

It's very performance heavy if a bot is in thousands of servers, and handles thousands of users. I dont know if my tunnel vision is kicking in, or if you guys seriously did not think that through. I'm turning desperate here.

**Comment by erxkk** [comment]
Reactions can occur in DM's as well, you need to type check the IMessageChannel to a ITextChannel (which is a essentially GuildMessageChannel).

This is simple inheritance/polymorphism, reading the [docs](https://docs.stillu.cc/) would help.

EDIT: this could've easily been resolved on the [Discord API guild](https://discord.gg/discord-api), this library has a channel there and asking there first is better than opening an issue.

**Comment by Anu6is** [comment]
That's a really long rant for a you issue 😆

**Comment by Wellendox** [comment]
> That's a really long rant for a you issue 😆

Didn't know where to throw it man, had to get it out there. Was getting frustrated here! :P

> Reactions can occur in DM's as well, you need to type check the IMessageChannel to a ITextChannel (which is a essentially GuildMessageChannel).
> 
> This is simple inheritance/polymorphism, reading the [docs](https://docs.stillu.cc/) would help.
> 
> EDIT: this could've easily been resolved on the [Discord API guild](https://discord.gg/discord-api), this library has a channel there and asking there first is better than opening an issue.

Gotcha! Did not know that Discord exists, oddly enough. Will join it for future issues. Coming from Discord.js, the documentation of discord.net is written like a master's degree final, with little to no example practical code snippets. Just blank theory. Can get confusing at times!

**Comment by Quahu** [comment]
@Wellendox This exact problem is documented as an article that's 2 minutes to read at most [right here, in the basic concepts section](https://docs.stillu.cc/guides/concepts/entities.html#inheritance).
