### ISSUE TITLE
Color DebuggerDisplay not working

### ISSUE THREAD

**Issue by Scorr** [RogueException/Discord.Net#190]
When debugging IRole.Color it gives the error
`-Color    error CS0428: Cannot convert method group 'DebuggerDisplay' to non-delegate type 'object'. Did you intend to invoke the method?    Discord.Color`

Image: http://puu.sh/qxGBF/141f0460ae.png

Guessing it is because in the source it's defined as
`private string DebuggerDisplay() =>
            $"#{Convert.ToString(RawValue, 16)} ({RawValue})";`
Which is a method but DebuggerDisplay needs to be a property with a getter.

**Comment by RogueException** [comment]
As yes, that should have been a property.

**Comment by RogueException** [comment]
Fixed in https://github.com/RogueException/Discord.Net/commit/3f53472c51d01f6470fb98abbbddccf3697d98d2
