### ISSUE TITLE
 Could not load file or assembly 'PresentationCore. Can't install discord

### ISSUE THREAD

**Issue by emptycrwn** [RogueException/Discord.Net#1903]
Was trying to reinstall discord as it wouldn't open on startup/even when I would run it normally and an error pops up with "installation has failed". This is the setup log;

[squirrelsetup v1.txt](https://github.com/discord-net/Discord.Net/files/6912232/squirrelsetup.v1.txt)
 
 Anyone know what the problem is? I've ran a .net repair tool and have tried many other solutions but nothing seems to fix this error.

**Comment by FiniteReality** [comment]
We're not Discord support - you'll want to contact Discord about this, not us.
