### ISSUE TITLE
Discord.Net/Discord.Commands Not having what documentation needs

### ISSUE THREAD

**Issue by ali-m-sc** [RogueException/Discord.Net#1905]
So i'm working on a discord bot and was going with the documentation on discord.net and it shows 
_client.MessageReceived += HandleCommandAsync;
await _commands.AddModuleAsync(assembly: Assembly.GetEntryAssembly(), services: null);
But Visual Studio doesn't recognize some of it
![dicord net_problem](https://user-images.githubusercontent.com/77641752/128611353-70226f91-b976-4408-907c-690cbd5a3089.png)

**Comment by sudo-gab** [comment]
hover over it, visual studio has [intellisense](https://visualstudio.microsoft.com/services/intellicode/) which helps you detect the root of the issue. `Assembly` is in the `System.Reflection` namespace

**Comment by ali-m-sc** [comment]
but then what to i do, do i import system,reflection?
Edit: I did it but it says that AddModuleAsync does not have the parameter named assembly
and also HandleCommandAsync still isn't in the context

**Comment by ohkriss** [comment]
> but then what to i do, do i import system,reflection?
> Edit: I did it but it says that AddModuleAsync does not have the parameter named assembly
> and also HandleCommandAsync still isn't in the context

Use `_commands.AddModulesAsync()` instead

**Comment by ali-m-sc** [comment]
alright

**Comment by ali-m-sc** [comment]
oh wait i just tested copying and pasting the code they had and it worked so guess I jut had to finish the code
