### ISSUE TITLE
50001 Missing access

### ISSUE THREAD

**Issue by sametguzeldev** [RogueException/Discord.Net#1908]
Hello there.

I haven't changed any code or made changes on my discord. My bot has full access with administrator enabled.
I've debugged it and saw that it throws 50001 error when I call guild.GetUsersAsync() method. I can confirm that the guild exists and the guild name is the one that it has the administrator rights on it.

Also it was working yesterday and it started to gave me this error today. Haven't changed any code or anything.

**Comment by Anu6is** [comment]
Member intents should be turned on in the developer portal

**Comment by sametguzeldev** [comment]
Yes that solved the issue thanks. Is this a new checkbox that was implemented recently? Because I had no errors before :)
It was working for at least 4-5 months I can say.

**Comment by Anu6is** [comment]
No, this is not new. Intents were introduced last year.

**Comment by sametguzeldev** [comment]
Hmmm.. it is weird then. I was using that method for at least 5 months and haven't received this error until now. Anyway thank you for your help!
