### ISSUE TITLE
How can I send more than one Embed one message

### ISSUE THREAD

**Issue by ITilyaGO** [RogueException/Discord.Net#1909]
Discord supports multiple instances of Embed in a single message.
I want to send a message containing multiple Embed. But SendMessageAsync() only accepts one instance.
Please add this feature or tell me how I can do it.

Example
https://ibb.co/sWJGCXh

**Comment by Anu6is** [comment]
This isn't yet supported in DNet for not messages. You'd have to send a message via Webhook

**Comment by ITilyaGO** [comment]
1. Is there a chance that a similar feature will be added?
2. Is the Discord.Webhook library suitable for sending messages with multiple Embed?

**Comment by Anu6is** [comment]
1. The Discord API does provide for it, so it's up to Discord.Net to implement it at some point.
2.  Yes.

**Comment by MrCakeSlayer** [comment]
This has now been implemented via the merged labs PR (#1923)
