### ISSUE TITLE
IGuild.DownloadUsersAsync() on v3.0.0-dev-20210710.3 blocks entire code execution

### ISSUE THREAD

**Issue by JerzyKruszewski** [RogueException/Discord.Net#1911]
IGuild.DownloadUsersAsync() on v3.0.0-dev-20210710.3 blocks entire code execution which can lead to "A MessageReceived handler is blocking the gateway task." or aborting (or stuck) executing command.
Also looks like DiscordSocketConfig.AlwaysDownloadUsers doesn't work correctly as well: When I called SocketGuild.Users on the server with 46 users it returned only 2.

Windows 10
Discord.Net-v3.0.0-dev-20210710.3
My bot has SERVER MEMBERS INTENT enabled

**Comment by nickmartin1ee7** [comment]
This is also happening to me on Discord.Net v2.4.0 (API v6), Windows 10. The HasAllMembers is false, and calling either Context.Client.DownloadUsersAsync or SocketGuild.DownloadUsersAsync causes this blocking behavior. No exceptions are thrown (when awaited).

**Comment by jaddie** [comment]
Throwing my 2p in to confirm that this also is behaving in an incorrect manner and I am going to likely start looking at alternative libraries so any suggestions would be welcome :)

**Comment by JerzyKruszewski** [comment]
> Throwing my 2p in to confirm that this also is behaving in an incorrect manner and I am going to likely start looking at alternative libraries so any suggestions would be welcome :)

I think that for C# there is only DSharpPlus as an alternative.

**Comment by ohkriss** [comment]
> Throwing my 2p in to confirm that this also is behaving in an incorrect manner and I am going to likely start looking at alternative libraries so any suggestions would be welcome :)

Disqord and DSharpPlus would be your options

**Comment by quinchs** [comment]
You need to specify the members gateway intent otherwise this function will hang

**Comment by anthonylangsworth** [comment]
@quinchs is correct. To fix this:
1. Navigate to your bot's configuration page (usually https://discord.com/developers/applications/id/bot where "id" is your bot's ID.
2. Set the SERVER_MEMBERS_INTENT to on. Without it, your bot will never receive a response. This causes Discord.Net to appear to hang.

Confirmed on Discort.Net v2.4.0. Otherwise, calls to SocketGuild.Users will only return the currently online users.
