### ISSUE TITLE
Adding support for attachments in embed.

### ISSUE THREAD

**Issue by ghost** [RogueException/Discord.Net#1912]
I've noticed that there is no attachment class etc for adding files from the source code to send it in embed messages.

Discord.JS has this in the below way:
```js
const attachment = new Discord.MessageAttachment("./path/to/file.png", "file.png");

// Embed....
.attachFiles([attachment])
.setImage("attachment://file.png")
```

It would be a lot more easier and nicer if this was added.

**Comment by zbroderson** [comment]
Pretty sure your looking for https://docs.stillu.cc/api/Discord.EmbedBuilder.html#usage-with-local-images

**Comment by ghost** [comment]
Sadly no, The code provided in the documentation is not working. Please see [this image](https://media.julianvs.dev/media/MXOBogDGYWtJx2QO2jOS.png).

The image and embed are sent separately.

My code:
```cs
var embed = new EmbedBuilder()
{
   ImageUrl = $"attachment://{levelCard}"
}.Build();

await Context.Channel.SendFileAsync(levelCard, embed: embed);
```

Edit: the var levelcard is the path to the image.

**Comment by zbroderson** [comment]
for the image url it needs to be "attachment://{filename}" not the path iirc

(also obligatory works on my machine)

**Comment by ghost** [comment]
So actually I am forced to store all images in the root of my project? I have a command that generates the levelcard, which stores the image in the `/cards/` folder.

**Comment by xXBuilderBXx** [comment]
You can do image stream/bytes too.
```
Embed.Author.IconUrl = "attachment://avatar.webp";
using MemoryStream stream = new MemoryStream(CacheBytes);
await Chan.SendFileAsync(stream, "avatar.webp", "", false, Embed.Build());```

**Comment by zbroderson** [comment]
> So actually I am forced to store all images in the root of my project?

Not at all the case.

https://api.zackbroderson.com/images/MjAyMS0wOC0yNF8xOC01NC5wbmc=.png

**Comment by ghost** [comment]
Ahhh like that. Didn't think about that tbh. Issue can be resolved as solved. Sorry to bother you and thanks for the support!

**Comment by zbroderson** [comment]
No problem.  And if you have any further issues feel free to join the DAPI server and ask in the dnet channel.  
(And make sure to close the issue ;) )
