### ISSUE TITLE
Ambiguous call when using LINQ extension method on DbSet<T> (EF Core)

### ISSUE THREAD

**Issue by snnaakee** [RogueException/Discord.Net#1914]
Combining EF Core 6.4.4 and Discord.NET 2.4.0.

With this setting plain simple where expression fails:
`var test = _db. Accounts.Where(i => i.Active == true). ToList();`

Generates error:
`Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0121	The call is ambiguous between the following methods or properties: 'System.Linq.Queryable.Where<TSource>(System.Linq.IQueryable<TSource>, System.Linq.Expressions.Expression<System.Func<TSource, bool>>)' and 'System.Linq.AsyncEnumerable.Where<TSource>(System.Collections.Generic.IAsyncEnumerable<TSource>, System.Func<TSource, bool>)'
`

As many people say, we can either use AsQueryable() or AsAsyncEnumerable() which explicitly return the respective interfaces. 
But, first it's very ugly, then it's not accurate. I'm getting a cached value rather than what the db has stored. Clearly not the ideal solution, I need it to be the most up to date.

**Comment by zbroderson** [comment]
Your previously stated solutions are your only options afaik.

see: https://github.com/dotnet/efcore/issues/18124

**Comment by BobVul** [comment]
> then it's not accurate. I'm getting a cached value rather than what the db has stored. Clearly not the ideal solution, I need it to be the most up to date.

`AsQueryable()` is [no more than](https://github.com/dotnet/efcore/blob/681727494fcdd6f795d719d38857820fad89c70e/src/EFCore/DbSet.cs#L83) the equivalent of a cast to `IQueryable<TEntity>`. Its only purpose and effect is disambiguation. There should be no way that it has any effect on caching.

You should probably look elsewhere for the cause of (and solution to) your caching problem. For example, if you have a caching layer configured for EF.

**Comment by snnaakee** [comment]
Alright so the caching problem seems to be a default behavior of EF Core. People think the bot isn't syncing correctly due to outdated results. I did nothing more than adding the db context, building the models and injecting it into the dependency injection. Anyway that's not the main issue brought here, I will find a solution.

As for the ambiguous call, I still think AsQueryable() solution is not a solution, but more a workaround.

**Comment by Cyral** [comment]
> Alright so the caching problem seems to be a default behavior of EF Core. People think the bot isn't syncing correctly due to outdated results. I did nothing more than adding the db context, building the models and injecting it into the dependency injection. Anyway that's not the main issue brought here, I will find a solution.
> 
> As for the ambiguous call, I still think AsQueryable() solution is not a solution, but more a workaround.

Your caching problem is probably by using a singleton instance of EF Core and allowing the database to be modified elsewhere. If you create a new scoped database context for each request (or rather, command), you wouldn't see cached data.
