### ISSUE TITLE
Support buttons

### ISSUE THREAD

**Issue by Sasino97** [RogueException/Discord.Net#1915]
Discord.NET should support the new buttons feature.
Article by Discord here: https://support.discord.com/hc/en-us/articles/1500012250861-Bots-Buttons
![image](https://user-images.githubusercontent.com/17410173/131928945-9b218a89-3e55-45ce-8c56-de499bf90488.png)

**Comment by zbroderson** [comment]
Please search for existing issues before opening your own. 

Check #1856.
As of now most of the other dotnet libs support components and several dnet forks do as well

**Comment by Sasino97** [comment]
I did. I searched for "buttons", nothing came up. The user who made that issue didn't use the word "button".
The official Discord page for general public calls them "buttons" not "message components".

**Comment by MrCakeSlayer** [comment]
This has now been implemented via the merged labs PR (#1923)
