### ISSUE TITLE
[FEATURE REQUEST] Ability To Read User Text-Status And About Me

### ISSUE THREAD

**Issue by MistressPlague** [RogueException/Discord.Net#1916]
I would like to be able to read a user's status and about me for filtering my users into roles based on criteria, can this be added please? Thank you.

**Comment by zbroderson** [comment]
About me is not supported by the api afaik.

As for a custom status u can check the Activities property on a user.

Also of course feel free to join the support channel in the DAPI server (https://discord.gg/discord-api) for help rather than opening issues.

**Comment by MistressPlague** [comment]
Thank you.
