### ISSUE TITLE
Context.Guild.GetUser object reference not set to instance of an object.

### ISSUE THREAD

**Issue by Luke20201** [RogueException/Discord.Net#1920]
In a socket Command context:

`
                         ulong id = Convert.ToUInt64(rdr[1]); //returns a UserID. Checked with Console.Writeline and correct id is return
                        await Context.Guild.GetUser(id); // Throws error here.
`
Does anybody know why this happens?

**Comment by MichailiK** [comment]
Do you have the guild members intent? Do you have [all guild members downloaded](https://docs.stillu.cc/api/Discord.WebSocket.SocketGuild.html#Discord_WebSocket_SocketGuild_HasAllMembers)?

**Comment by Luke20201** [comment]
> Do you have the guild members intent? Do you have [all guild members downloaded](https://docs.stillu.cc/api/Discord.WebSocket.SocketGuild.html#Discord_WebSocket_SocketGuild_HasAllMembers)?

Is that required? I assumed GetUser downloaded the User via the ID. I will try downloading them. Thanks.

EDIT: I attempted to download the User's. But that actually threw an error at Context.Guild as well. Here is the full code block the issue is occurring in:

` public async Task MuteRead()
        {
            await Task.Run(async () =>
            {

                string connStr = "";
                MySqlConnection conn = new MySqlConnection(connStr);
                try
                {
                    conn.Open();

                    MySqlCommand cmd = new MySqlCommand("SELECT * FROM `mutes` WHERE MuteUntil <= 0", conn);
                    MySqlDataReader rdr = cmd.ExecuteReader();

                    while (rdr.Read())
                    {
                        if (!hasSentLog)
                        {
                            SendLog("Mute Manager__", "**Member**        | <@" + rdr[1] + ">\n **Punishment**       | UNMUTE" + "\n **Punished by**          | <@" + rdr[4] + ">");
                            hasSentLog = true;
                        }
                        await Context.Guild.DownloadUsersAsync(); // Line error occurs on
                        ulong id = Convert.ToUInt64(rdr[1]);
                        await Context.Guild.GetUser(id).RemoveRoleAsync(553340347606892544); // Need to get the user from id refed above
                         sqlQuery = "DELETE FROM `mutes` WHERE `UserID` = " + rdr[1] + ";";
                        SQLInsert();
                        hasSentLog = false;
                        
                    }
                    rdr.Close();
                }
`

**Comment by MichailiK** [comment]
> I assumed GetUser downloaded the User via the ID

`GetUser` is a synchronous method, it does not do any asynchronous operations (downloading users not in the cache for example). I think `GetUserAsync` does what you're looking for.

**Comment by Luke20201** [comment]
> > I assumed GetUser downloaded the User via the ID
> 
> `GetUser` is a synchronous method, it does not do any asynchronous operations (downloading users not in the cache for example). I think `GetUserAsync` does what you're looking for.

Hey, I edited my reply before you commented again. GetUserAsync does not exist in SocketGuild.

**Comment by MichailiK** [comment]
Apologies, I might be misremembering. What exception is being thrown?

**Comment by Luke20201** [comment]
> Apologies, I might be misremembering. What exception is being thrown?

SocketGuild does not have a definition for 'GetUserAsync'

**Comment by MichailiK** [comment]
... I meant in the snippet you previously posted

> ```cs
> await Context.Guild.DownloadUsersAsync(); // Line error occurs on
> ```

**Comment by Luke20201** [comment]
> ... I meant in the snippet you previously posted
> 
> > ```cs
> > await Context.Guild.DownloadUsersAsync(); // Line error occurs on
> > ```

Ah, Object reference is not set to instance of an object.

**Comment by MichailiK** [comment]
`Context` or `Guild` is null? Is the bot being used in a DM? There is not much to go on. Consider using a debugger to be able to more easily figure out what's wrong.

**Comment by Luke20201** [comment]
> `Context` or `Guild` is null? Is the bot being used in a DM? There is not much to go on. Consider using a debugger to be able to more easily figure out what's wrong.

Right above I added                         Console.WriteLine(Context.Client.Latency); to confirm which it was. That threw an error so it appears to be Context

**Comment by MichailiK** [comment]
How is your method being invoked? Do you use a command handler, which finds, sets up & runs the method for you, or are you trying to run the method manually? Consider pasting the stack trace too, which can make things easier.

**Comment by Luke20201** [comment]
> How is your method being invoked? Do you use a command handler, which finds, sets up & runs the method for you, or are you trying to run the method manually? Consider pasting the stack trace too, which can make things easier.

The method is invoked by a method that is run automatically on startup.

**Comment by MichailiK** [comment]
Don't do that!!! The `Context` doesn't initialize by itself; It's being initialized by the command handler every time a user runs a command. Put your code you wanna run somewhere else, like in the Ready event.

**Comment by Luke20201** [comment]
> Don't do that!!! The `Context` doesn't initialize by itself; It's being initialized by the command handler every time a user runs a command. Put your code you wanna run somewhere else, like in the Ready event.

Thank you. Moving this into a method called by the Ready event directly worked.
