### ISSUE TITLE
Is there any way to perform long-lasting commands in DiscordSocketClient?

### ISSUE THREAD

**Issue by Sevarius** [RogueException/Discord.Net#1924]
I have a problem, that my discord bot is not able to answer to commands, if there some long-lasting command is performing.
```
var client = new DiscordSocketClient();
client.MessageReceived += ClientOnMessageReceived;
client.LoginAsync(TokenType.Bot, <botToken>);
client.StartAsync();

private async Task ClientOnMessageReceived(SocketMessage arg)
{
    if (arg.Content.StartsWith("!"))
    {
        await Task.Delay(TimeSpan.FromMinutes(1));
        await arg.Channel.SendMessageAsync("Answer after 1 minute");
    }
}
```
If i send two commands to bot, only first one will work, while second won't even start executing.

Can you please help me, what am i doing wrong?
Is there any way to execute long-lasting commands asynchronously?

**Comment by MichailiK** [comment]
This code blocks the Gateway thread. The Gateway thread is responsible for receiving & processing events that come from Discord. If you do any long-running operations on it, Discord.Net will be unable to process any Events until you are done. Consider running your code on a new/different Task or Thread. See https://docs.stillu.cc/faq/commands/general.html#discordnet-keeps-saying-that-a-messagereceived-handler-is-blocking-the-gateway-what-should-i-do

**Comment by Sevarius** [comment]
Thank you very much for your answer)
