### ISSUE TITLE
Markdown in Embed

### ISSUE THREAD

**Issue by Hantse** [RogueException/Discord.Net#1926]
Hello,

Is actually try to use this library to generate Embed in discord with bot.

When i try to insert markdown in embed field, it's not interpreted.

The code i use to generate embed.
```
var embed = new EmbedBuilder();
embed.WithUrl("https://tbc.wowhead.com/item=32090");
embed.Title = "Wishlist pour [Cowl of Naaru Blessings]";
embed.AddField("Tank", "1. Xemac  2. Ayshae");
embed.AddField("DPS", "<ul><li>Xemac</li><li>Ayshae</li>");
await arg.Channel.SendMessageAsync("[Capuche des bénédictions des naaru]");
await arg.Channel.SendMessageAsync(embed: embed.Build());
```

**Comment by Anu6is** [comment]
Discord doesn't support lists via markdown.

**Comment by Hantse** [comment]
In this case, how to generate this type of complexe embed ?

![image](https://user-images.githubusercontent.com/701241/134509551-37addc70-dd06-410f-87e8-24e82f0af018.png)

**Comment by Joe4evr** [comment]
That's just newlines.

**Comment by Hantse** [comment]
New line of ? When i try to add AddField, it's not work with empty name or value.

**Comment by Yotimoto** [comment]
Newlines (`\n`) in the value. What I'm guessing you'll want is something like:
```
embed.AddField("Tank", "1. Xemac \n 2. Ayshae", true);
embed.AddField("DPS", "Xemac \n Ayshae", true);
```
The optional `true` at the end of the `AddField` makes your fields inline with each other, up to 3 columns.

**Comment by Hantse** [comment]
Hum ... of course thank you @Yotimoto 
I also see some emote, it's require specific escape for ?

**Comment by ghost** [comment]
> Hum ... of course thank you @Yotimoto
> I also see some emote, it's require specific escape for ?

you must upload those emotes to a discord server first then you can use them in embed and messages.
here i wrote a method

`
        public static string ToDiscordEmote(this ulong id)
        {
            return $"<:em:{id}>";
        }
`
