### ISSUE TITLE
Is there a way to run DiscordSocketClient from Blazor webassembly?

### ISSUE THREAD

**Issue by Swordancer** [RogueException/Discord.Net#1927]
I was trying to write a tool for making bots using flowgraph system and I was able to made it in Blazor Server at least in a simplified version but I realized that flow graph itself is a little heavy thing.  I thought a webassemlby would be a better solution as I don't need to process anything related directly with Discord on my server and users can use thier own bot tokens without exposing anything to the server which I couldn't allow anyway. Then user can serialize logic and load it in to the seperate .net core service app with linux support just to run it with thier own token on thier own machine.

For now the only thing I was able to do was to rewrite DefaultRestClientProvider to work on browser, at least partially but it seems websocket doesn't work at all. After few hours of trying I gave up and I thought that I could rewrite UI to XAML even though I don't really like it but I figured I'd ask here first, maybe there's a way out to save my time.

I'd rather not mess with WPF because after years of working with it, I found out I didn't like it but I like Blazor despite the fact that it also has its drawbacks that drive me crazy.

I would be grateful for any advice.

**Comment by csmir** [comment]
Please follow up if you still have need for the answer to this question. Closing for now
