### ISSUE TITLE
SocketChannel#GetMessagesAsync doesn't appear to add fetched messages to cache

### ISSUE THREAD

**Issue by Draco18s** [RogueException/Discord.Net#1928]
Due to the specific use-case of one server I'm in (we used Nadeko for this previously), we had one user who would post things, then delete them and change his user name to attempt to hide the fact that he'd posted those things, so we logged all deleted messages in an admin-visible channel. Due to various factors, the bot has been offline for a while, and due to a recent episode of posting pictures of self-harm (and deleting them before mods could be involved) I offered to write a simple bot to handle this task.

When the bot signs in, I wanted it to fetch a chunk of recent message history as when a message was deleted, if it wasn't in the cache, all details about the message were invisible (no ability to repost the content or author), so I wrote the following and had to add *my own cache* as simply downloading messages and assuming the DiscordSocketClient (`_client`) would cache them was insufficient. I didn't want the bot to be blind if it had to restart for any reason. It didn't need *that* much history, just more than "none."

	private async Task RefreshMessageCacheAsync() {
		foreach(SocketGuild guild in _client.Guilds) {
			foreach(SocketTextChannel channel in guild.TextChannels) {
				if(!ResolvePermissionsAllowedToReadChannel(guild, channel)) continue; //no built in?
				IAsyncEnumerator<IMessage> enumerator = channel.GetMessagesAsync(100)
					.Flatten().GetAsyncEnumerator();
				while(await enumerator.MoveNextAsync()) {
					messageCache.Add(enumerator.Current); //had to do this
				}
			}
		}
	}

(I also had to write my own permissions resolution function to determine if the bot was allowed to see a channel and read message history. Surely this exists as part of the API already, right, and I'm just blind, right?)

**Comment by Anu6is** [comment]
1. Caching messages that existed before bot startup - No this is not available as part of the API
2. Check channel permissions - Yes, [SocketGuildUser#GetPermissions](https://docs.stillu.cc/api/Discord.WebSocket.SocketGuildUser.html#Discord_WebSocket_SocketGuildUser_GetPermissions_Discord_IGuildChannel_)

**Comment by Draco18s** [comment]
2. Awesome, exactly what I had been looking for. It was just in a location I didn't think to look.
