### ISSUE TITLE
Object not found when user mention

### ISSUE THREAD

**Issue by BiggerIron** [RogueException/Discord.Net#1929]
Im having some issues where im trying to make a bot be able to take the user you mentioned and get information about them, but the result is always object not found

![image](https://user-images.githubusercontent.com/91643482/135370240-62fdc04e-701d-4479-a0b0-b9ec3510d359.png)

![image](https://user-images.githubusercontent.com/91643482/135370286-d0309ad3-276a-44cf-8ce9-87de43c862dc.png)

![image](https://user-images.githubusercontent.com/91643482/135370360-7cc1919a-2a90-4c85-80d8-d1030e56eacb.png)

**Comment by atom0s** [comment]
Make sure you have enabled the user info intent on the Discord developer portal for your bot. It's off by default so you won't get user information until it's turned on.

Go to: https://discord.com/developers/applications

Then select your bot, and go to the 'Bot' subpage. It'll be listed there as 'SERVER MEMBERS INTENT'.

**Comment by Cruik** [comment]
Hey,
 i m running into the same error...
i already enabled the 'SERVER MEMBERS INTENT', but the error ist still occurs.
