### ISSUE TITLE
User not found when trying to ban user

### ISSUE THREAD

**Issue by oreydeore** [RogueException/Discord.Net#1930]
hello i can't ban anyone because the "user is not found"
![image](https://user-images.githubusercontent.com/91790557/135719727-d6b9f017-b12d-4b73-bb26-722b150bf985.png)
![image](https://user-images.githubusercontent.com/91790557/135719750-3c97998d-4b57-4d69-bd05-86742bf4ed1e.png)

**Comment by LedgendODST** [comment]
Are intents enabled? Also there is a property on SocketGuildUser arg that bans the user. 

See https://docs.stillu.cc/api/Discord.WebSocket.SocketGuildUser.html   for that 

Well here enable intens on the dev portal and set them on the config also make sure u have Alwaysdownloadusers enabled in the discordsocketconfig

**Comment by oreydeore** [comment]
intents are enabled, i'll go try enabling alwaysdownloadusers

**Comment by oreydeore** [comment]
how do i enable alwaysdownloadusers in discordsocketconfig tho

**Comment by oreydeore** [comment]
thanks buddy, works now
