### ISSUE TITLE
how can I add a custom status to a bot in discord.net? 

### ISSUE THREAD

**Issue by whoschisa** [RogueException/Discord.Net#1931]

**Comment by hrkyr** [comment]
`await Client.SetGameAsync("Spotify");`

**Comment by hrkyr** [comment]
i mis-understood. you cannot do that with Discord.Net. `await Client.SetActivityAsync(ActivityType.CustomStatus)` would work but it doesnt.

**Comment by MrCakeSlayer** [comment]
As stated above you can set bot status with `await Client.SetGameAsync("Name Here");` and set the type with with `await Client.SetActivityAsync(ActivityType.X)` however the API currently prevents bots from using the "CustomStatus" type.
