### ISSUE TITLE
Content is ALWAYS empty

### ISSUE THREAD

**Issue by NKCSS** [RogueException/Discord.Net#1932]
Here's a piece of test code; needless to say, it will always read 0/X for some reason. all other data (Guild, Author, etc. lists just fine). Logging in using Bearer token.
```
            int msgCount = 0, nonEmpty = 0;
            _client.MessageReceived += (message) =>
            {
                if (!string.IsNullOrWhiteSpace(message.Content))
                {
                    ++nonEmpty;
                    Console.WriteLine(message.Content);
                }
                if(++msgCount % 100 == 0)
                {
                    Console.WriteLine($"{nonEmpty}/{msgCount} were non-empty...");
                }
                return Task.CompletedTask;
            };                
```

**Comment by quinchs** [comment]
`if(++msgCount % 100 == 0)` seems kinda stange. have you tried just replacing this with an else statement

**Comment by NKCSS** [comment]
> `if(++msgCount % 100 == 0)` seems kinda stange. have you tried just replacing this with an else statement

That's just a counter to print out stats every 100th message. I figured out what the issue is; Discord recognises it as a bot, even though I login with my own account token, and then they stripp all content & embeds.

**Comment by nefe01** [comment]
> > `if(++msgCount % 100 == 0)` seems kinda stange. have you tried just replacing this with an else statement
> 
> That's just a counter to print out stats every 100th message. I figured out what the issue is; Discord recognises it as a bot, even though I login with my own account token, and then they stripp all content & embeds.

I have the same issue upgrading from version 2.4 to 3.0. Did you solve the issue?
