### ISSUE TITLE
Custom bot emojis

### ISSUE THREAD

**Issue by moddingforreal** [RogueException/Discord.Net#1938]
Many bots have **custom emojis** like the _Aki_ or the _Dank memer_ bot. These emojis do not have to be on the server.
Just the bot can use these. Is there an implementation of this, and if not, could you add this?

**Comment by martindevans** [comment]
It looks like this may just be those bots using emoji from another server, as if they had Nitro. See here for example: https://github.com/AnIdiotsGuide/discordjs-bot-guide/blob/master/coding-guides/using-emojis.md#using-emojis.

**Comment by MrCakeSlayer** [comment]
As stated above the bots simply use the emotes from a guild/server that the bot is in. The bot can access emoji on any server the bot is added to just like nitro users. There is no special implementation needed for this.
