### ISSUE TITLE
dotnet restore fails if .NET core myget feed is not enabled

### ISSUE THREAD

**Issue by FiniteReality** [RogueException/Discord.Net#194]
After clearing my NuGet package cache and disabling the .NET core myget feed in my NuGet.config, I fail to restore the dev version of System.Net.WebSockets.Client that we use: http://i.imgur.com/pGQWXHm.png

A simple way to solve this issue would be to put a notice on the feed saying that users *need* to enable the .NET core feed as well, at least until the managed implementation of WebSocketClient becomes available on NuGet.

**Comment by RogueException** [comment]
The goal is that we shouldnt need this once the fix gets pushed to nuget, but... I'm not sure how long it'll take?

I might end up removing this, and adding instructions for overriding the websocket ver on linux builds.

**Comment by RogueException** [comment]
Yeah, I went ahead and reverted us back to stable websockets. Info is on the readme now.
