### ISSUE TITLE
A MessageReceived handler is blocking the gateway task.

### ISSUE THREAD

**Issue by Chris166** [RogueException/Discord.Net#1940]
When I type command that command it show me error in console "A MessageReceived handler is blocking the gateway task." I am using .NET Core os that it runs on Windows 11 

        [Command("redeem")]
        public async Task redeem(string key = null)
        {
            if (Helper.IsBlacklisted(Uri.EscapeDataString(Context.User.Username.ToString())))
            {
                await ReplyAsync($"{Context.User.Mention}, You're blacklisted from AuthGG Application.");
                return;

            }

            var chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";
            var stringChars = new char[25];
            var random = new Random();
            for (int i = 0; i < stringChars.Length; i++)
            {
                stringChars[i] = chars[random.Next(chars.Length)];
            }
            var randomString = new String(stringChars);
            string resultPass = randomString;

            if (key == null)
            {
                await ReplyAsync($"{Context.User.Mention}, usage: `$redeem key-example`");
                return;
            }

            var username = Context.Guild.GetUser(Context.User.Id).Username;
            dynamic response = JsonConvert.DeserializeObject(HttpRequest.Post("https://api.auth.gg/v1/", new NameValueCollection() {
                { "type", "register"},
                { "aid", AuthGG.AID},
                { "apikey", AuthGG.APIKEY},
                { "secret", AuthGG.SECRET},
                { "username",  Uri.EscapeDataString(Context.User.Username.ToString())},
                { "password", resultPass },
                { "email", "ID: " + Context.User.Id.ToString()},
                { "license", key },
                { "hwid","no_hwid_set" }
            }));

            if (response["result"] == "success")
            {
                dynamic authdata = JsonConvert.DeserializeObject(HttpRequest.Get($"https://developers.auth.gg/USERS/?type=fetch&authorization={AuthGG.Authorization}&user={Uri.EscapeDataString(Context.User.Username.ToString())}"));
                dynamic reset_hwid_result = JsonConvert.DeserializeObject(HttpRequest.Get($"https://developers.auth.gg/HWID/?type=reset&authorization={AuthGG.Authorization}&user={Uri.EscapeDataString(Context.User.Username.ToString())}"));

                if (authdata["status"] == "success" && reset_hwid_result["status"] == "success")
                {
                    SocketGuildUser user = Context.Guild.CurrentUser;
                    if (user.Guild.Id == Servers.PrivateGuild)
                    {

                        var CustomerRole = Context.Guild.Roles.FirstOrDefault(x => (x.Name.ToString().Contains("Customer"))); //CHANGE "customer" to the customer role name!
                        await ((SocketGuildUser)Context.User).AddRoleAsync(CustomerRole);
                        await ReplyAsync($"{Context.User.Mention}, Key Successfully Redeemed, Expiration: `{authdata["expiry"]}`");

                        await Context.User.SendMessageAsync($"{Context.User.Mention}, Your Account Details:\n \n**Username:** ** {Uri.EscapeDataString(Context.User.Username.ToString())}**\n**Password:  ** **{resultPass}**\n**Expiration:** **{authdata["expiry"]}**");
                        return;
                    }
                    else if (user.Guild.Id == Servers.PublicGuild)
                    {

                        var CustomerRole = Context.Guild.Roles.FirstOrDefault(x => (x.Name.ToString().Contains("Gang")));
                        await ((SocketGuildUser)Context.User).AddRoleAsync(CustomerRole);
                        await ReplyAsync($"{Context.User.Mention}, Key Successfully Redeemed, Expiration: `{authdata["expiry"]}`");
                        await Context.User.SendMessageAsync($"{Context.User.Mention}, Your Details:\n \n**Username:** ** {Uri.EscapeDataString(Context.User.Username.ToString())}**\n**Password:  ** **{resultPass}**\n**Expiration:** **{authdata["expiry"]}**");
                        return;
                    }
                }
                else
                {
                    await ReplyAsync($"{Context.User.Mention}, We couldn't add you to the customer group, Please contact support.");
                    return;
                }

            }
            else if (response["result"] == "invalid_license")
            {

                await ReplyAsync($"{Context.User.Mention}, Key is invalid or already redeemed.");
                return;

            }
            else if (response["result"] == "email_used")
            {

                await ReplyAsync($"{Context.User.Mention}, Something went wrong trying to make your account. Contact Staff.");
                return;

            }
            else if (response["result"] == "invalid_username")
            {

                await ReplyAsync($"{Context.User.Mention}, Your username is already taken, contact staff.");
                return;

            }

        }

**Comment by Anu6is** [comment]
Your command is taking to long to execute. You should set it's `RunMode` to `RunMode.Async`
