### ISSUE TITLE
Slash commands are not registered (I'm using dev branch of lib)

### ISSUE THREAD

**Issue by BlitDev** [RogueException/Discord.Net#1951]
I try write:
```csharp
var command = new SlashCommandBuilder();
```
but this class is not in the Discord namespace. Though it is listed in the documentation and Guide.

**Comment by BlitDev** [comment]
The required classes are available only in the dev version of the lib. When is the library update?

**Comment by BlitDev** [comment]
![image](https://user-images.githubusercontent.com/79034202/144719766-9755d268-ebb5-4a38-9347-2cb8c1a7c97d.png)
I tried to register a Slash command in all guilds, but it had no effect, no commands were created, made the properties using the SlashCommandBuilder class.

**Comment by quinchs** [comment]
Have a peek at the [Slash Command Documentation](https://discord-net-labs.com/guides/interactions/application-commands/01-getting-started.html)

**Comment by BlitGaming** [comment]
> Have a peek at the [Slash Command Documentation](https://discord-net-labs.com/guides/interactions/application-commands/01-getting-started.html) 

It only about slash commands permissions on Discord Dev. I have configured this

**Comment by BlitDev** [comment]
> Have a peek at the [Slash Command Documentation](https://discord-net-labs.com/guides/interactions/application-commands/01-getting-started.html) 

I can't find this documentation right away (is it unofficial?)

**Comment by quinchs** [comment]
Why cant you find it?

**Comment by quinchs** [comment]
Have you looked through the documentation? it lists how to create slash commands and receive them. you can also use the interaction framework to use slash commands. docs for that is [here](https://discord-net-labs.com/guides/interactions_framework/intro.html)

**Comment by BlitDev** [comment]
> Why cant you find it?

It's fork docs, not official

**Comment by quinchs** [comment]
Well the fork has been merged in #1923 making the docs valid for reference on the dev branch

**Comment by BlitDev** [comment]
> Well the fork has been merged in #1923 making the docs valid for reference on the dev branch

I didn't see it, thanks

**Comment by kieranedwards** [comment]
> Have a peek at the [Slash Command Documentation](https://discord-net-labs.com/guides/interactions/application-commands/01-getting-started.html)

Hey, is there an alternative site to getting an example of how to code in slash command support for discord.net? Or can someone somehow export the docs and share it in here perhaps? This url is inaccessible for me. I get a "ERR_SSL_PROTOCOL_ERROR" response on the entire website in general. Not sure if anyone else experiences similar?

**Comment by 1NieR** [comment]
> > Have a peek at the [Slash Command Documentation](https://discord-net-labs.com/guides/interactions/application-commands/01-getting-started.html)
> 
> Hey, is there an alternative site to getting an example of how to code in slash command support for discord.net? Or can someone somehow export the docs and share it in here perhaps? This url is inaccessible for me. I get a "ERR_SSL_PROTOCOL_ERROR" response on the entire website in general. Not sure if anyone else experiences similar?

New link https://discordnet.dev/guides/int_basics/application-commands/intro.html

**Comment by kieranedwards** [comment]
> > > Have a peek at the [Slash Command Documentation](https://discord-net-labs.com/guides/interactions/application-commands/01-getting-started.html)
> > 
> > 
> > Hey, is there an alternative site to getting an example of how to code in slash command support for discord.net? Or can someone somehow export the docs and share it in here perhaps? This url is inaccessible for me. I get a "ERR_SSL_PROTOCOL_ERROR" response on the entire website in general. Not sure if anyone else experiences similar?
> 
> New link https://discordnet.dev/guides/int_basics/application-commands/intro.html

That is perfect, thank you!
