### ISSUE TITLE
No error thrown for using 'CommandContext.Execute' to a 'Modulebase<SocketCommandContext>' class

### ISSUE THREAD

**Issue by Thomas-Valkenburg** [RogueException/Discord.Net#1962]
The class 'CommandContext' doesn't contain all of the properties required to operate in a class that inherits the 'SocketCommandContext' class. Therefore any attempt to execute a command in a class that inherits 'SocketCommandContext' will fail.

No error is thrown when this error occurs.

**Comment by quinchs** [comment]
Does the command service `Log` event fire an error?

**Comment by Thomas-Valkenburg** [comment]
I wasn't aware the command service had a log method.

Just added it and yes it does fire an error, but only in the console and not in the application itself. Which seems odd since deleting a message that doesn't exist anymore will crash the application.

**Comment by quinchs** [comment]
Can you send the exception logged to the console?

cc: @Cenngo

**Comment by Cenngo** [comment]
You should be able to recieve the exceptions by changing CommandServiceConfig.ThrowOnException to true but i dont think thats a good idea. Why would you want command execution errors to be critical?

**Comment by Thomas-Valkenburg** [comment]
Like I mentioned, CommandService doesn't contain all properties to perform a command in a SocketCommandService. Therefore trying to is application breaking since your application doesn't work at all.

**Comment by Thomas-Valkenburg** [comment]
I do agree that an command failing shouldn't be critical, since there might be smaller stuff going on, but the command not performing at all seems like a critical error.

**Comment by Cenngo** [comment]
Module base throws an exception if you try to set its context from a different type [here](https://github.com/discord-net/Discord.Net/blob/dev/src/Discord.Net.Commands/ModuleBase.cs#L74-L78). And thats is logged by the command service.

**Comment by quinchs** [comment]
As long as your module base has the correct context as the generic parameter it *should* work fine, ex:
```cs
public class MyModule : ModuleBase<MyCustomContext> 
```
