### ISSUE TITLE
Async infinite loop blocking the gateway task

### ISSUE THREAD

**Issue by BlitDev** [RogueException/Discord.Net#1963]
I begin async loop in Ready handler:
```c#
// Begin loop
await new VoiceExperienceLoop(_client, 60).Begin();
```
VoiceExperienceLoop.Begin code:
```c#
public override async Task Begin()
    {
        while (true)
        {
            foreach (var voiceChannel in _client.GetGuild(Bot.MainGuildId).VoiceChannels)
            {
                foreach (var user in voiceChannel.Users)
                {
                    if (!Bot.Db.UserIsExists(user.Id).Result)
                    {
                        await Bot.Db.CreateUser(user.Id);
                    }

                    var currentExperience = await Bot.Db.GetExperience(user.Id);
                    await Bot.Db.SetExperience(user.Id, currentExperience + 1);
                }
            }

            await Task.Delay(_delaySeconds * 1000);
        }
        // ReSharper disable once FunctionNeverReturns
    }
```
But it throws an error in console **"A Ready handler is blocking the gateway task."**
What am I doing wrong? I'm a beginner in C# programming.

**Comment by LedgendODST** [comment]
The event handler is taking so long to execute so u would need to either make ur new task

**Comment by iProgramMC** [comment]
Try splitting away the code into a new function.  Then in the Begin function, `await Task.Run(() => YourNewFunction());` and return a `Task.CompletedTask`.

**Comment by BlitDev** [comment]
> Try splitting away the code into a new function. Then in the Begin function, `await Task.Run(() => YourNewFunction());` and return a `Task.CompletedTask`.

It helped me. I split code into a new **async** function **Run**, and writed
```c#
Task.Run(Run);
return Task.CompletedTask;
```
into **no async** Task Begin()

UPD: **The method that is called from the Ready handler must not be asynchronous, otherwise it will block the gateway task.**
