### ISSUE TITLE
Direct messages are not sent

### ISSUE THREAD

**Issue by BlitDev** [RogueException/Discord.Net#1964]
I need to send a message to all guild participants
I have a message handler:
```c#
var userId = socketMessage.Author.Id;
var mainGuild = _client.GetGuild(Bot.MainGuildId);

// Send news
if (socketMessage.Channel.Id == NewsChannelId)
{    
    var users = mainGuild.GetUsersAsync().GetAsyncEnumerator();
    
    while (users.MoveNextAsync().Result)
    {
        Console.WriteLine(users.Current.Count);
        
        foreach (var user in users.Current)
        {
            try
            {
                var channel = await user.GetOrCreateDMChannelAsync();
                await channel.SendMessageAsync(socketMessage.Content);
            
                Console.WriteLine($"Sent msg to {user.Username}");
            }
            catch (Discord.Net.HttpException e)
            { 
                Console.Write($"Msg: {e.Message}\n" +
                            $"Username: {user.Username}");
            }   
        }
    }
}
```
But while sending a message to the user ( users.MoveNextAsync() ), an HttpException is thrown with the message "Missing Access".
This is probably due to the fact that there is no DIRECT_MESSAGES intent in the config, but if I connect it, the bot will process Ready for a very long time and after that it will not respond to anything.

**Comment by LedgendODST** [comment]
That's called mass dming that's not allowed

**Comment by BlitDev** [comment]
There are at least 3 people in the guild who have DM messages enabled. Before that, I tried getting SocketGuild.Users property and run through all users in a loop. In this case, the message was sent only to me, and the sending stopped at the first exception, despite the presence of the try .. catch block. Now I'm trying to use the MoveNextAsync() method, but it immediately throws an exception.

**Comment by BlitDev** [comment]
Now I have found another bug. When I enabling Server Member intents, bot hang.

**Comment by quinchs** [comment]
Are you using 2.4.0?

**Comment by BlitDev** [comment]
> Are you using 2.4.0?

Yes.

**Comment by BlitDev** [comment]
> Are you using 2.4.0?

These two bugs persist even if the bot is launched with latest version of Discord.Net Labs.

**Comment by Thomas-Valkenburg** [comment]
Just filter out the users that have dm turned off. 
On top of that you are sending the messages to the amount of users squared since you are doing a foreach(user) in a while(foreachUser).

**Comment by BlitDev** [comment]
> Just filter out the users that have dm turned off. 
> On top of that you are sending the messages to the amount of users squared since you are doing a foreach(user) in a while(foreachUser).

First, you need to get a list of users of the entire server. However, even when using DownloadUsersAsync(), the list of users contains only 2 users.

**Comment by Thomas-Valkenburg** [comment]
Would you mind sending the code you have right now. I'm assuming you have changed it since you are talking about `DownloadUsersAsync()` but your original code doesn't have that. I'm having a hard time understanding what you are trying to do and what you are doing. As well as perhaps more information on what you are trying to do and how you are trying to achieve it.

**Comment by Sasino97** [comment]
I've tried mass DMing, not worth it, you'll just get your Discord application banned. If you're gonna do it anyway, then add a 10-minute delay every 10 users DMed.
