### ISSUE TITLE
GetOrCreateDMChannelAsync() NullReferenceException

### ISSUE THREAD

**Issue by ubikusss** [RogueException/Discord.Net#1965]
Hello, 

Trying to create a DMChannel but I even if the `SocketUser` is not `null` I get a `NullReferenceException`. See image.

![image](https://user-images.githubusercontent.com/10058111/145713816-58e37b28-8e73-4a3b-a96b-258a7bebdc0a.png)
```
System.AggregateException
  HResult=0x80131500
  Message=One or more errors occurred. (Object reference not set to an instance of an object.)
  Source=System.Private.CoreLib
  StackTrace:
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at MainBGJob.SendDiscordNotifications(UserSettings notificationData) in E:\Code\XXXX\XXXX\XXXX\XXXX\Jobs\MainBGJob.cs:line 97
   at MainBGJob.Execute(IJobExecutionContext context) in E:\Code\XXXX\XXXX\XXXX\XXXX\Jobs\MainBGJob.cs:line 59
   at Quartz.Simpl.MicrosoftDependencyInjectionJobFactory.ScopedJob.Execute(IJobExecutionContext context)
   at Quartz.Core.JobRunShell.<Run>d__10.MoveNext()

  This exception was originally thrown at this call stack:
    [External Code]

Inner Exception 1:
NullReferenceException: Object reference not set to an instance of an object.
```

**Comment by LedgendODST** [comment]
Enable intents on code side and website 
Make sure u have Alwaysdownloadusers set to true
Make sure u fire this code in the client ready event

**Comment by ubikusss** [comment]
Thanks for the reply! 
All intents are enabled for the discord bot (website) but I am not sure how to enable them on code side :(
Sorry, new to `discord.net` 😞

Regarding `AlwaysDownloadUsers()`, if I already have the user populated, is this needed? 
Also if I have the user populated, doesn't that make the client ready?

**Comment by drobbins329** [comment]
Intents need enabled on both the website, and in the DiscordSocketConfig. Example:

var client = new DiscordSocketClient(new DiscordSocketConfig{GatewayIntents = GatewayIntents.All});

**Comment by LedgendODST** [comment]
but don't enable all GatewayIntents it can cause memory leaks, only enable the GatewayIntents u really need.

**Comment by LedgendODST** [comment]
> Thanks for the reply! All intents are enabled for the discord bot (website) but I am not sure how to enable them on code side :( Sorry, new to `discord.net` 😞
> 
> Regarding `AlwaysDownloadUsers()`, if I already have the user populated, is this needed? Also if I have the user populated, doesn't that make the client ready?

the Client Ready event is more then that, it fires when the client is fully ready and downloaded all users when u turned AlwaysDownloadUsers On.

**Comment by ubikusss** [comment]
Thank you very much guys, very helpful!
I will be closing this issue then, it worked.
