### ISSUE TITLE
Bot don't recognize inactive/invisible user on guild

### ISSUE THREAD

**Issue by 0lfu** [RogueException/Discord.Net#1972]
Can't execute command on user which is inactive when bot starts - like such user doesn't exist. 
However when user is active when bot starts, everything is working just fine.

**Comment by 0lfu** [comment]
It works on api 2.4 though. Is that a bug then?

**Comment by 0lfu** [comment]
```cs
public async Task TestCommand()
{
    var users = Global.Client.Guilds.ToList()[0].Users.ToList();
    foreach (object o in users)
    {
        await ReplyAsync(o.ToString());
    }
}
//Global.Client is DiscordSocketClient
```

![image](https://user-images.githubusercontent.com/39961884/146900804-52adddbb-2602-4793-9e91-155187b49d99.png)

**Comment by quinchs** [comment]
The user isn't in the cache, try adding the guild member intent and setting AlwaysDownloadUsers to true in your config

**Comment by Anu6is** [comment]
in addition to the above, you also need to set the intents you want in the SocketClientConfig

**Comment by 0lfu** [comment]
Yep! Setting
```cs
AlwaysDownloadUsers = true
GatewayIntents = GatewayIntents.All
```
in SocketConfig solved all the issues!
