### ISSUE TITLE
Object Not Found when using User's mention

### ISSUE THREAD

**Issue by BlyZeDev** [RogueException/Discord.Net#1973]
Hello, a last couple of days, i have a problem with my bot: The API cannot propably find the Object for user

It doesn't work for one or more users, but it works for another user(s).

What can be made wrong, or what's the problem?
![135370176-ca1951a5-e0bc-4b96-88de-ab3268628b89](https://user-images.githubusercontent.com/95288041/146691942-d7f1cf1c-fcef-418c-804b-70af5f9e392c.png)

**Comment by quinchs** [comment]
The user could be null due to the user not being in the cache. The [default user type reader](https://github.com/Discord-Net/Discord.Net/blob/dev/src/Discord.Net.Commands/Readers/UserTypeReader.cs) only works off of the cache, you could write your own to use rest if the user isn't cached.

**Comment by BlyZeDev** [comment]
> The user could be null due to the user not being in the cache. The [default user type reader](https://github.com/Discord-Net/Discord.Net/blob/dev/src/Discord.Net.Commands/Readers/UserTypeReader.cs) only works off of the cache, you could write your own to use rest if the user isn't cached.

How do I get all Users in can every time i Run any Command?

**Comment by xenoverse-us** [comment]
> > The user could be null due to the user not being in the cache. The [default user type reader](https://github.com/Discord-Net/Discord.Net/blob/dev/src/Discord.Net.Commands/Readers/UserTypeReader.cs) only works off of the cache, you could write your own to use rest if the user isn't cached.
> 
> How do I get all Users in can every time i Run any Command?

I think you can always create a DiscordRestClient then use public Task<RestGuildUser> GetGuildUserAsync(ulong guildId, ulong id, RequestOptions options = null) to get a RestGuildUser which gives you access to Roles (Indirectly since you get role id's but then you can get role using those id's)

**Comment by BlyZeDev** [comment]
> > > The user could be null due to the user not being in the cache. The [default user type reader](https://github.com/Discord-Net/Discord.Net/blob/dev/src/Discord.Net.Commands/Readers/UserTypeReader.cs) only works off of the cache, you could write your own to use rest if the user isn't cached.
> > 
> > How do I get all Users in can every time i Run any Command?
> 
> I think you can always create a DiscordRestClient then use public Task<RestGuildUser> GetGuildUserAsync(ulong guildId, ulong id, RequestOptions options = null) to get a RestGuildUser which gives you access to Roles (Indirectly since you get role id's but then you can get role using those id's)

How do I do this😅

**Comment by xenoverse-us** [comment]
> > > > The user could be null due to the user not being in the cache. The [default user type reader](https://github.com/Discord-Net/Discord.Net/blob/dev/src/Discord.Net.Commands/Readers/UserTypeReader.cs) only works off of the cache, you could write your own to use rest if the user isn't cached.
> > > 
> > > How do I get all Users in can every time i Run any Command?
> > 
> > I think you can always create a DiscordRestClient then use public Task<RestGuildUser> GetGuildUserAsync(ulong guildId, ulong id, RequestOptions options = null) to get a RestGuildUser which gives you access to Roles (Indirectly since you get role id's but then you can get role using those id's)
> 
> How do I do this😅

This should get you started. 

https://discordnet.dev/api/Discord.Rest.DiscordRestClient.html?q=DiscordRestclient

**Comment by BlyZeDev** [comment]
`var config = new DiscordSocketConfig
            {
                AlwaysDownloadUsers = true,
                MessageCacheSize = 100,
                GatewayIntents = GatewayIntents.All
            };`

This worked for me :)
