### ISSUE TITLE
Bot doesn't recognize online user on guild

### ISSUE THREAD

**Issue by BlyZeDev** [RogueException/Discord.Net#1974]
One embed is just 0 online member but there more than 0 users online:
![Screenshot 2021-12-19 224923](https://user-images.githubusercontent.com/95288041/146692057-a7139b3f-6ca3-4432-9df5-35b8f6fa1373.png)

**Comment by quinchs** [comment]
Make sure you have the guild members intent and the users are in the cache.

**Comment by BlyZeDev** [comment]
> Make sure you have the guild members intent and the users are in the cache.

How can I do that?

**Comment by xenoverse-us** [comment]
> > Make sure you have the guild members intent and the users are in the cache.
> 
> How can I do that?

1. You need to apply for those intents in your Discord Developer Portal if your bot is installed on more than 100 servers. https://discord.com/developers/docs/topics/gateway#gateway-intents
2. You need to configure to always download users. https://discordnet.dev/api/Discord.WebSocket.DiscordSocketConfig.html

**Comment by BlyZeDev** [comment]
> > > Make sure you have the guild members intent and the users are in the cache.
> > 
> > How can I do that?
> 
> 1. You need to apply for those intents in your Discord Developer Portal if your bot is installed on more than 100 servers. https://discord.com/developers/docs/topics/gateway#gateway-intents
> 2. You need to configure to always download users. https://discordnet.dev/api/Discord.WebSocket.DiscordSocketConfig.html

1.The bot is currently only on my server.

2. Where so I put this code?
(sorry im noob xD)

**Comment by xenoverse-us** [comment]
> > > > Make sure you have the guild members intent and the users are in the cache.
> > > 
> > > How can I do that?
> > 
> > 1. You need to apply for those intents in your Discord Developer Portal if your bot is installed on more than 100 servers. https://discord.com/developers/docs/topics/gateway#gateway-intents
> > 2. You need to configure to always download users. https://discordnet.dev/api/Discord.WebSocket.DiscordSocketConfig.html
> 
> 1.The bot is currently only on my server.
> 
> 2. Where so I put this code?
> (sorry im noob xD)

1. You don't need to worry about if your bot is in less than 100 servers. 

2. Link is to documentation with example code snippet. Take a look there. Basically where you create your client.

**Comment by Cruik** [comment]
Hey, 
i did exactly this. Does this take some time to be available ? Because my cached User list ist still empty and i get the ObjectNotFound exception :/

**Comment by BlyZeDev** [comment]
This is my bot code

![Screenshot 2021-12-22 000759](https://user-images.githubusercontent.com/95288041/147009238-45a32fef-ff20-41f8-b8b0-68fb51676f6c.png)
But when I use this command the bot always says 0.

![Screenshot 2021-12-22 000827](https://user-images.githubusercontent.com/95288041/147009237-5c36897e-b2e8-48fd-92ea-dc3b5b46799f.png)

**Comment by csmir** [comment]
You require to enable the ` server members intent ` to view users inside a guild. Since Discord API v9 this has been added to the ` DiscordSocketConfig ` as well as the bot client needs to specify its intents now. You can enable/set these under: ` GatewayIntents = .. ` I suggest for starting out to just add ` GatewayIntents.All ` to the configuration item.

**Comment by xenoverse-us** [comment]
> You require to enable the `server members intent` to view users inside a guild. Since Discord API v9 this has been added to the `DiscordSocketConfig` as well as the bot client needs to specify its intents now. You can enable/set these under: `GatewayIntents = ..` I suggest for starting out to just add `GatewayIntents.All` to the configuration item.

`GatewayIntents.All` only exists in v3 not in v2.4. Also `DiscordSocketConfig.GatewayIntents` is a nullable enum in v2.4. I do not have it configured but can still get guild members while on v2.4.

There seems to be some issues with GatewayIntents in the config. I've documented them in another issue I created.

**Comment by BlyZeDev** [comment]
> > You require to enable the `server members intent` to view users inside a guild. Since Discord API v9 this has been added to the `DiscordSocketConfig` as well as the bot client needs to specify its intents now. You can enable/set these under: `GatewayIntents = ..` I suggest for starting out to just add `GatewayIntents.All` to the configuration item.
> 
> `GatewayIntents.All` only exists in v3 not in v2.4. Also `DiscordSocketConfig.GatewayIntents` is a nullable enum in v2.4. I do not have it configured but can still get guild members while on v2.4.
> 
> There seems to be some issues with GatewayIntents in the config. I've documented them in another issue I created.

Okay so what should I do to fix that issue?

**Comment by csmir** [comment]
Solution covered in duplicate: #1983. The additional problem presented by @xenoverse-us does not apply. v3 is not the same as v2.4 and uses a different Discord API version.

**Comment by Cruik** [comment]
> Solution covered in duplicate: #1983. The additional problem presented by @xenoverse-us does not apply. v3 is not the same as v2.4 and uses a different Discord API version.

The link to this solution solved my issue! perfect thanks!

**Comment by BlyZeDev** [comment]
```
var config = new DiscordSocketConfig
            {
                AlwaysDownloadUsers = true,
                MessageCacheSize = 100,
                GatewayIntents = GatewayIntents.All
            };
```
This works for me :)

**Comment by drobbins329** [comment]
> ```
> var config = new DiscordSocketConfig
>             {
>                 AlwaysDownloadUsers = true,
>                 MessageCacheSize = 100,
>                 GatewayIntents = GatewayIntents.All
>             };
> ```
> 
> This works for me :)

If this is solved, please close the issue.
