### ISSUE TITLE
RequireRoleAttribute checks for existence of Role inside a guild, not on the user.

### ISSUE THREAD

**Issue by JMWren** [RogueException/Discord.Net#1975]
Hey there,

When testing the new interactions I found that the RequireRole precondition for interactions was passing every time, even when the user did not have the specified role. 

It seems that the RequireRoleAttribute precondition for interactions is checking the existence of the Role inside of the guild when supplied with a string value, rather than for the user. This causes the condition to succeed if the role exists in the guild.

![image](https://user-images.githubusercontent.com/29394737/146692501-8c30fc19-b273-4a55-ac3d-e6472622d0ed.png)

Here is the code sample I was running.

![image](https://user-images.githubusercontent.com/29394737/146692721-094a89dc-c9a8-4935-9de1-9534166fe279.png)

**Comment by quinchs** [comment]
cc: @Cenngo

**Comment by Cenngo** [comment]
This should be an easy fix. @quinchs Where do you want me to push it? Here or Labs

**Comment by quinchs** [comment]
Push it here and il make a labs commit
