### ISSUE TITLE
Discussion on allowing multiple role names/ids in attributes

### ISSUE THREAD

**Issue by Bakersbakebread** [RogueException/Discord.Net#1981]
See commit on my branch [here](https://github.com/Bakersbakebread/Discord.Net/commit/eb5ee23ff6cfb4c3909808233c98daa5d062b758)

This would allow developers to specify with their attribute, that a user invoking the command must have one of the defined rolenames.

This is an `OR` check, not an `AND` check. 

```cs
        [SlashCommand("ping", "Recieve a pong")]
        [RequireRoleAttribute(new[]{"test role", "test role 2"})]
        public async Task Ping()
        {
            await RespondAsync("pong");
        }
```

What's the thoughts?

**Comment by csmir** [comment]
this could be an overload perhaps? cc @Cenngo. I don't see a reason to not implement this. Potentially ORing could be made primary in an optional param alongside AND in an enum?

**Comment by Anu6is** [comment]
This is something that can be left as a custom implementation per developer. The lib provides the functionality for you to spin up your own pre-conditions, there's not need for it to cover every edge case.

**Comment by Cenngo** [comment]
I mean this definitely depends on your use case but if you are using, i dunno less than 3 roles in this check i think using multiple preconditions allows you to have finer control over this . For example, ORing `[RequireRole("Test Role", "A"), RequireRole("Test Role 2", "A")]`. And i agree with @Anu6is, built-in preconditions are meant to be a starting point for newcomers, preconditions pattern is designed to be a way of allowing users to create implementations for their own needs. We cant implement a precondition for every edge case and bloat the library.

**Comment by Bakersbakebread** [comment]
Seems reasonable to be a custom implementation. closing.
