### ISSUE TITLE
DiscordSocketClient.Ready firing twice

### ISSUE THREAD

**Issue by v-maxson** [RogueException/Discord.Net#1982]
Put simply, the ready event fires twice due to the Client failing to resume a previous session. Is there a way to stop it from attempting to resume a previous session?

**Comment by Anu6is** [comment]
No there isn't. The reconnection request is sent from Discord and upon receiving that request the bot should reconnect to the gateway. Ideally it should resume the session, but if it does fail then it would need to reidentify and yes, this will trigger the ready event. 

If you have logic in your ready event that should only be triggered once, then you should unsubscribe from the event the first time it's raised. That way you ignore any subsequent triggers.

**Comment by v-maxson** [comment]
Gotcha, thought I'd make sure before I attempted to do anything else with it. Thanks
