### ISSUE TITLE
Bot has Server Member Intent from Discord Dev Portal but DownloadUsersAsync still throws Missing required gateway intent GuildMembers

### ISSUE THREAD

**Issue by xenoverse-us** [RogueException/Discord.Net#1983]
Version: Discord.NET v3
`Discord.WebSocket.DiscordSocketClient.DownloadUsersAsync` starts to throw 

```
System.InvalidOperationException: Missing required gateway intent GuildMembers in order to execute this operation.
at Discord.WebSocket.DiscordSocketClient.EnsureGatewayIntent(GatewayIntents intents)
at Discord.WebSocket.DiscordSocketClient.DownloadUsersAsync(IEnumerable`1 guilds)
```

Expected: Should work since it was working in v2.4 and my app has Server Member Intent.

After I upgraded to v3. When running v2.4 this was fine. Discord Developer Portal shows that my app has Server Member Intent, which is the one I applied for long time ago and was working fine until I upgraded to v3.

<img width="1031" alt="image" src="https://user-images.githubusercontent.com/11079437/147008260-4b1d6f7e-d9db-4c44-8c2f-fd38b7590d94.png">

Update1: It has been awhile since I last call this method in my code in production. Just reverted back to v2.4 and will verify that after deployment is done.

Update2: Confirmed that `Discord.WebSocket.DiscordSocketClient.DownloadUsersAsync` works fine after I revert back to v2.4. The reason I tried to call `DownloadUserAsync` is because I noticed my bot's user cache isn't getting populated after the build with v3 booted up so I tried to manually "force" it. I think there is another issue with user cache not getting populated in v3 when it should be.

**Comment by LedgendODST** [comment]
U need to set the intents in the socketconfig in ur code

**Comment by csmir** [comment]
To add to this response:

` DiscordSocketConfig ` includes a field called ` GatewayIntents `, which is a **required** configuration to set if you use any privileged intents. You can match the ` GatewayIntents ` to what you have enabled in the portal. If you are not sure what all the intents imply, use ` GatewayIntents.All ` as the value for this option, as it adds all unprivileged and privileged intents to your socketclient.

Edit: The reason why it does not work now is because Discord API v9 requires intents to be set by the client, previous API versions did not.

Example:
```cs

var config = new DiscordSocketConfig() 
{
    ... // any other options
    GatewayIntents = GatewayIntents.All
}
_client = new DiscordSocketClient(config);
```

**Comment by LedgendODST** [comment]
But don't use all just use the one u need, if u add intents u don't need it may causes memory leaks...

**Comment by csmir** [comment]
The above is made known by the library, responsive warnings are thrown to warn the user of this. To figure out what intents you might need and not need, refer to the [documentation](https://discordnet.dev/api/Discord.GatewayIntents.html#Discord_GatewayIntents_AllUnprivileged). 

Stacking intents can be done as followed:

```cs

GatewayIntents = GatewayIntents.AllUnprivileged | GatewayIntents.GuildMembers | ..

```

**Comment by xenoverse-us** [comment]
@Rozen4334 thanks for the clarification. I figured it may be a version difference. I checked my log and confirmed that v2.4 is using Discord v6 API whereas v3 is using Discord v9 API.

There are still issues.

With this configuration, which the exception says I need to have for `Discord.WebSocket.DiscordSocketClient.DownloadUsersAsync`
```
var discordClient = new DiscordSocketClient(new DiscordSocketConfig
{
   // other options
    GatewayIntents = GatewayIntents.GuildMembers
});
```
I receive no message at all. Break point in my MessageReceived handler does not get hit.
`discordClient.MessageReceived += HandleCommandAsync;`

if I use `GatewayIntents = GatewayIntents.All` instead, I get those warnings like you mentioned
```
You're using the GuildPresences intent without listening to the PresenceUpdate event, consider removing the intent from your config.
You're using the GuildScheduledEvents gateway intent without listening to any events related to that intent, consider removing the intent from your config.
You're using the GuildInvites gateway intent without listening to any events related to that intent, consider removing the intent from your config.
```
But, my MessageReceived handler works fine, break point there gets triggered and `Discord.WebSocket.DiscordSocketClient.DownloadUsersAsync` completes without throwing an exception.

So I'm a little confused as to why exception says I need `GuildMembers` intent but when I actually configure it my bot hangs. Yet if I configure my bot with `All`, everything looks fine exception the above warnings.

**Comment by csmir** [comment]
> ```cs
> GatewayIntents = GatewayIntents.AllUnprivileged | GatewayIntents.GuildMembers | ..
> ```

As mentioned here, you can stack several intents. Specifying only ` GuildMembers ` gets rid of several other intents that are required in your case. Adding the ` AllUnprivileged `* intent would solve the issue. This adds a group of intents that are required for using several 'regular' events like listening for messages, from the ` GuildMessages, DirectMessages ` intents.

> ***unprivileged**, thus not required to enable in the developer portal.

**Comment by xenoverse-us** [comment]
> > ```cs
> > GatewayIntents = GatewayIntents.AllUnprivileged | GatewayIntents.GuildMembers | ..
> > ```
> 
> As mentioned here, you can stack several intents. Specifying only `GuildMembers` gets rid of several other intents that are required in your case. Adding the `AllUnprivileged`* intent would solve the issue. This adds a group of intents that are required for using several 'regular' events like listening for messages, from the `GuildMessages, DirectMessages` intents.
> 
> > ***unprivileged**, thus not required to enable in the developer portal.

Thanks for sharing this. I was about to try to OR those two flags together myself. I can confirm that it indeed fixes the issue for me.

Hopefully, Discord API version change could also be documented here https://discordnet.dev/guides/v2_v3_guide/v2_to_v3_guide.html so that we are aware of potential need to configure GatewayIntents.

Anyways, thanks for the help, please consider this issue closed.
