### ISSUE TITLE
Upgrading to 3.0 Results in Events like DiscordSocketClient.GuildMemberUpdated, DiscordSocketClient.UserJoined and DiscordSocketClient.UserLeft Not To Fire

### ISSUE THREAD

**Issue by kieranedwards** [RogueException/Discord.Net#1988]
Hi,

After updating to Discord.Net 3.0 from 2.4, I've found that some of the events appear to have stopped firing. This includes:

- DiscordSocketClient.GuildMemberUpdated
- DiscordSocketClient.UserJoined
- DiscordSocketClient.UserLeft

Could a change in 3.0 have caused the above to have broken?

I confirm that the following appear to still be working as expected:

- DiscordSocketClient.OnMessageDeletedAsync
- DiscordSocketClient.MessageUpdated
- DiscordSocketClient.UserVoiceStateUpdated

Example event that works without issue:
![image](https://user-images.githubusercontent.com/6440075/147148655-331f83b2-0ca2-4483-aac6-42e07e40922a.png)

Example event that appears not to fire anymore in 3.0:
![image](https://user-images.githubusercontent.com/6440075/147148695-46c22f4c-82e7-47cd-b0c6-fa657f8faf17.png)

The exact same code works in 2.4 so I am suspecting that something has broken in 3.0 though I am hoping its fixable by me making some changes in my code.

Thank you.

**Comment by quinchs** [comment]
What gateway intents are you passing into your config?

**Comment by quinchs** [comment]
Have a look at https://discordnet.dev/guides/v2_v3_guide/v2_to_v3_guide.html#gatewayintents

**Comment by kieranedwards** [comment]
Hi quinchs, that helped! I registered the intents I needed and those events fire as expected, thank you so much! :)
