### ISSUE TITLE
GetGuild(AppId) is not working anymore

### ISSUE THREAD

**Issue by KomodoCrypto** [RogueException/Discord.Net#1991]
Hello, I use to get the guild where the Bot is added as GetGuild(AppId) but now is always returning null. I have the server members intent option enable, administrator priviledges... But always return null.
If I get the guild using the GuildId as an argument, like GetGuild(GuildId), I can get the object but the users are not retrieved. I only can see one single user that corresponds to the Bot itself, but no other users.
Same behaviour for 2.4 and 3.0 versions.
How to get the complete list of the users of the guild that a Bot is associated?

**Comment by quinchs** [comment]
You need to download the users by using `guild.DownloadUsersAsync()` or by adding `AlwaysDownloadUsers = true` to your config

**Comment by KomodoCrypto** [comment]
Thank you @quinchs. Based on your reply, It made me finally found the solution.
So, guild.DownloadUsersAsync() is another method to retrieve the users as GetGuild(GuildId).users. The problem applies for both.
The solution is to set your desired intent config when creating the client object. This was not necessary before because I set it from discord's website. However it is not working anymore and following arguments are needed:

            _client = new DiscordSocketClient(new DiscordSocketConfig() { 
                AlwaysDownloadUsers = true,
                GatewayIntents = GatewayIntents.Guilds | GatewayIntents.GuildMembers       
            });
