### ISSUE TITLE
Exception thrown on client.DownloadMessages 

### ISSUE THREAD

**Issue by iamwyza** [RogueException/Discord.Net#20]
when client.DownloadMessages tries to fetch a message that belongs to a user that no longer exists on the server, it will throw a nullreferenceexception.

**Comment by iamwyza** [comment]
Ps this is on 0.7.3, might not be a problem in the .9 alpah

**Comment by RogueException** [comment]
Thanks for the report, but 0.9 involved rewriting most of the logic for REST requests, so this likely isn't a problem anymore. I'll check it during my next round of testing just in case.
