### ISSUE TITLE
SocketGuild.Owner.get error

### ISSUE THREAD

**Issue by kolya112** [RogueException/Discord.Net#2000]
My bot cannot determine the owner of the server in the "client.JoinedGuild" event, although, for example, the name can be determined without problems. Error: "System.NullReferenceException:" Object reference not set to an instance of an object. "
Discord.WebSocket.SocketGuild.Owner.get return null. "On string owner = guild.Owner.Nickname;

Full code:

```
private async Task NewGuild(SocketGuild guild)
        {
            Console.WriteLine("test");
            string owner = guild.Owner.Nickname;
            await guild.SystemChannel.SendMessageAsync($"Owner: {owner}");
        }
```

**Comment by BobVul** [comment]
Not everyone will have a nickname (i.e. guild-specific name) set. Use the `.Username` property instead, to get the global username. Use `.ToString()` to get a uniquely identifying string, currently `{Username}#{Discriminator}`. If you actually want just the nickname with a fallback to username when one does not exist, use `.Nickname ?? .Username`.

**Comment by quinchs** [comment]
By default the owner isnt cached, discord doesn't provide the owner user object on guild create. You would either need to download all the users in the guild or use rest to get the user

**Comment by kolya112** [comment]
GetUser (ulong id) returns the same. Is that not cached too?

**Comment by quinchs** [comment]
GetUser is cached.

try 
```cs
var owner = await client.Rest.GetGuildUserAsync(guildId, guild.OwnerId);
```

**Comment by kolya112** [comment]
It works, thanks!
