### ISSUE TITLE
Embed ImageUrl with link

### ISSUE THREAD

**Issue by BlyZeDev** [RogueException/Discord.Net#2004]
Is it possible that you can open a link when you click on the image of an embed?

I mean not the image source link but a link that you can choose that opens when you click on the image..

I dont know if this is understandable...

![Bild_2021-12-25_025907](https://user-images.githubusercontent.com/95288041/147375755-379b097c-f860-4c99-9eb9-7b2cc7fc3540.png)

I mean that you can open the link above the image when you click the image :)

**Comment by quinchs** [comment]
No, Discord doesn't support a feature like that.
