### ISSUE TITLE
CreateModuleAsync in InteractionService cannot be used to create a buildable Module.

### ISSUE THREAD

**Issue by Blu3SoulsIT** [RogueException/Discord.Net#2006]
### The Problem:
CreateModuleAsync offers a BuilderAction, however, you cannot set the TypeInfo of the Module you want to build in the passed ModuleBuilder object. This results in a `NullReferenceException` when the builder is being built.
```csharp
interactionService.CreateModuleAsync("name", serviceProvider, builder =>
{
    builder.TypeInfo = typeof(MyModule); // Not possible as the 'TypeInfo' property is marked internal.
});
```

The main problem is that the TypeInfo property is marked internal and there's no way to provide a TypeInfo to the ModuleBuilder object externally.

#### 1. Add a Setter-Method to ModuleBuilder.
```csharp
public ModuleBuilder WithTypeInfo(TypeInfo typeInfo)
{
    TypeInfo = typeInfo;
    return this;
}
```
##### Possible Problems:
The TypeInfo may be invalid. As validity checks are normally done in the ModuleClassBuilder type, a duplicate check or a reference to ModuleClassBuilder would have to be added.

#### 2. Pass the TypeInfo from the CreateModuleAsync method and instantiate the ModuleBuilder via the ModuleClassBuilder.

In InteractionService:
```csharp
public async Task<ModuleInfo> CreateModuleAsync(string name, TypeInfo typeInfo, IServiceProvider services,
    Action<ModuleBuilder> buildFunc)
{
    // ...
    try
    {
        var moduleInfo = ModuleClassBuilder.CreateModuleAsync(name, typeInfo, buildFunc, this, services);
        LoadModuleInternal(moduleInfo);

        return moduleInfo;
    }
    // ...
}
```
In ModuleClassBuilder:
```csharp
public static ModuleInfo CreateModuleAsync(string name, TypeInfo typeInfo, Action<ModuleBuilder> buildFunc,
    InteractionService interactionService, IServiceProvider services)
{
    if (!IsValidModuleDefinition(typeInfo))
        throw new InvalidOperationException();

    var builder = new ModuleBuilder(interactionService);
    builder.TypeInfo = typeInfo; // Set TypeInfo here after it has been checked.

    buildFunc(builder);
    var moduleInfo = builder.Build(interactionService, services);

    return moduleInfo;
}
```

##### Possible Problems:
This would most likely be a breaking change as the signature of CreateModuleAsync would need to be changed to accommodate the TypeInfo parameter.
But seeing as the method can't be used anyway, this might be the cleanest way to handle this.

**Comment by Cenngo** [comment]
`CreateModuleAsync` method isn't meant to be used with reflection so setting TypeInfo on its own wouldnt accomplish much aside from solving the NRE. Instead, we can just add a null check and method validation before executing Module.OnModuleBuilding.

```cs
if(TypeInfo is not null && ModuleClassBuilder.IsValidModuleDefinition(TypeInfo))
```

Great issue btw.

**Comment by Blu3SoulsIT** [comment]
I like your proposal as it's simple to implement.
It would, however, prevent all custom modules from receiving the `OnModuleBuilding` callback even if one could provide a valid type to handle the callback.

**Comment by Cenngo** [comment]
What is the point of implementing `OnModuleBuilding` if you are the one building the method?

**Comment by Blu3SoulsIT** [comment]
In my case, I am trying to use the BuilderAction to create modules, just like you would normally, by creating an attributed class that inherits from `InteractionModuleBase<>`.

However, I'm using my own attributes to add metadata to the ModuleBuilder as I need different defaults and groupings.
Using the attributes provided by the Discord.Net framework, I would always have to specify attributes like `[DefaultPermission(false)]`.

As you said:
> `CreateModuleAsync` method isn't meant to be used with reflection

But this is exactly what I *want* to do.

Personally, I don't need to consume the `OnModuleBuilding` callback, but the framework could provide the functionality if `TypeInfo` was settable.

A good compromise would be to add the `WithTypeInfo(TypeInfo typeInfo)` method and add type checks before invoking the `OnModuleBuilding` callback.

**Comment by Cenngo** [comment]
Would changing the method signature of `OnModuleBuilding` to make it inline with its Discord.Commands counterpart ( `void OnModuleBuilding (InteractionService commandService, ModuleBuilder module)` ) solve your issue? Normally in Discord.Commands you can use that to modify the module before it is finalized.

Obviously changing its signature would be a breaking change but we could add a seperate method.

**Comment by Blu3SoulsIT** [comment]
Yes, that would also work.
Modules that are added by `InteractionService` are collected via their inheritance, and no predefined attribute is strictly required to create the `ModuleBuilder`.
I could do all of my processing in `OnModuleBuilding`.

**Comment by Cenngo** [comment]
Probably going to introduce a new `Construct` method for performing this task.

**Comment by Blu3SoulsIT** [comment]
I noticed that you cannot set the `Callback` property, when using the `moduleBuilder.AddSlashCommand` method.
There is also no other way of creating a `ModuleInfo` with SlashCommands containing valid `Callback` properties other than using the built-in InteractionService methods (except CreateModuleAsync of course).

Should I open a separate Issue for this?

**Comment by Cenngo** [comment]
> Should I open a separate Issue for this?

yes
