### ISSUE TITLE
Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by hrkyr** [RogueException/Discord.Net#2008]
Im trying to send a message when the bot starts up, but I get "System.NullReferenceException: "Object reference not set to an instance of an object."

My code:
`
            public async Task MainAsync() { 
            Handler = new CommandHandler();
            Client = new DiscordSocketClient();
            
            await Handler.Init(Client);

            var token = "u dont get this";

            await Client.LoginAsync(TokenType.Bot, token);
            await Client.StartAsync();

            ulong gid = 881998970057003009;
            ulong cid = 881998970518380546;

            var Guild = Client.GetGuild(gid);
            var channel = Guild.GetTextChannel(cid);

            await channel.SendMessageAsync("Started!");
            await Task.Delay(-1);
        }`

**Comment by moiph** [comment]
Guild data isn't available immediately; the `Ready` event will be fired once data is downloaded: https://discordnet.dev/api/Discord.WebSocket.DiscordSocketClient.html#Discord_WebSocket_DiscordSocketClient_Ready

**Comment by quinchs** [comment]
Above answers this
