### ISSUE TITLE
REST channel entities do not correctly implement GetMessagesAsync

### ISSUE THREAD

**Issue by FiniteReality** [RogueException/Discord.Net#201]
Source: https://github.com/RogueException/Discord.Net/blob/dev/src/Discord.Net/Rest/Entities/Channels/DMChannel.cs#L102

The GetMessagesAsync overloads for DMChannel and TextChannel do not correctly implement `fromMessageId` and `dir` and will return incorrect values.

**Comment by khionu** [comment]
Worked fine for me. You do realize that you are citing the top-most level of that request?

The SocketClient GetMessage implementations are not tested, but the RestClient work just fine.

**Comment by RogueException** [comment]
Definitely a bug, we have unused variables in there. Issue is open for whoever wants to PR it.
