### ISSUE TITLE
ModuleInfo.CheckTopLevel returns the wrong value

### ISSUE THREAD

**Issue by erraineon** [RogueException/Discord.Net#2011]
When initializing a module such as...
```
public class TestModule : InteractionModuleBase<IInteractionContext>
{
    [SlashCommand("ping", "Responds with pong.")]
    public async Task Ping()
    {
        await ReplyAsync("Pong");
    }
}
```

Upon inspecting the registered `ModuleInfo`, its `IsTopLevelGroup` will be set to true. That's because `CheckTopLevel` returns true even if the module has no `GroupAttribute` declared on it. 

This makes you unable to use functions like `InteractionService.ModifySlashCommandPermissionsAsync` unless the targeted commands have `IgnoreGroupNames` set to true. That's because `IsTopLevelCommand` checks for `IgnoreGroupNames || !Module.IsTopLevelGroup`, and every unparented module currently is a "top level group".

**Comment by quinchs** [comment]
cc @Cenngo
