### ISSUE TITLE
MessageReceived SocketUserMessage Content is Empty

### ISSUE THREAD

**Issue by nefe01** [RogueException/Discord.Net#2013]
Updating from 2.4 to 3.0 some times i get message Content to Empty

Adding Message receivend event:

>                   var _client = new DiscordSocketClient();
>                   _client.MessageReceived += HandleCommandAsync;

>    [Command("HandleCommandAsync", RunMode = RunMode.Async)]
>     private void HandleCommandAsync(SocketMessage arg)
>     {
>         if (arg is SocketUserMessage message)
>         {
>             var messageString = message.Content;
>         }
>     }

    
   Downgrading to 2.4 the problem doesn't appear.

**Comment by drobbins329** [comment]
Have you enabled GatewayIntents in the socket config? this is a API V9 thing.

**Comment by nefe01** [comment]
> Have you enabled GatewayIntents in the socket config? this is a API V9 thing.

I have tried passing the config on constructor but i have the same issue.

>           var config = new DiscordSocketConfig() { 
>             GatewayIntents = GatewayIntents.All         
>             };

Ps: Some times i get the message, some times no. If i downgrade to 2.4 i recive always the message content.

Ps2: I have two task in parallel that do a LoginAsync (with two different token), it seems that one got the message, while the other got content empty.

**Comment by quinchs** [comment]
Are you able to create some reproducible code for us to test?
