### ISSUE TITLE
Build errors (The reference assemblies for .NETFramework,Version=v4.6.1 were not found)

### ISSUE THREAD

**Issue by FaiqueAli** [RogueException/Discord.Net#2019]
Hi All,
I am new to open source community.
I found this project for the contribution. when I build this project I found following build errors.
_The reference assemblies for .NETFramework,Version=v4.6.1 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application._

I have visual studio 22 installed on my machine.
I have tried some other project that also has same issue.
as per the description of this project vs2017 is need so do I have to install vs 2017 because I am already at higher version so why should I go to lower version?
please guid me, 
Thanks :)
Faiq

**Comment by CottageDwellingCat** [comment]
Hi, 
You should still be able to build the net and netcoreapp versions of Discord.net without that dependency. If you need netframework for testing with your bot you can install it from https://dotnet.microsoft.com/en-us/download/dotnet-framework.
Let me know if you have more questions.

**Comment by FaiqueAli** [comment]
hi thx for rep.
infact 4.6.1 has no longer from microsoft, if I install 4.6.1 will I be still able to work on vs22 ?

**Comment by CottageDwellingCat** [comment]
Hello, 
You **do not** need to install .net framework in order to work on the project, you can simply ignore the warnings. I am able to contribute from Linux, having only installed .net5/6, without any issues. If visual studio won't let you open the project, and the install page won't work, you can click [here](https://go.microsoft.com/fwlink/?linkid=2099470) to force start the download. You can use whatever editor/ide you choose, although I do not use it, multiple contributors have shown vs2022 working in the solution.

**Comment by sabihoshi** [comment]
It's an error, not a warning. The reason why is because Discord.Net targets .Net 4.6.1.

The way to fix this is to install the .Net 4.6.1 targeting pack.
![image](https://user-images.githubusercontent.com/25006819/148490079-354e517f-48a9-4975-8d33-1dea94403a8b.png)

**Comment by FaiqueAli** [comment]
@sabihoshi, both .net 4.6.1. and .net5/6 can be install at the same time ?
or we need one version at a time?

**Comment by FaiqueAli** [comment]
I am not able to install 4.6.1 as I am already updated!
<img width="576" alt="error" src="https://user-images.githubusercontent.com/15321863/148528577-1e0b38ca-afdd-47fd-bb4c-2812d917a078.png">

**Comment by sabihoshi** [comment]
I specifically mentioned 4.6.1 targeting pack, which is different from what you're installing (4.6.1 SDK) go to your VS installer and under components find the same one as in the image I sent earlier.

**Comment by FaiqueAli** [comment]
Thank you @sabihoshi it works fine after following your instruction :)
Thanks.
