### ISSUE TITLE
RegisterCommandsToGuildAsync does not work

### ISSUE THREAD

**Issue by Nic13Gamer** [RogueException/Discord.Net#2028]
The method of a `InteractionService` instance, `RegisterCommandsToGuildAsync` never returns something and keep awaiting. This stops my program and does not add the commands to the guild. The `RegisterCommandsGloballyAsync` also does the same thing.

As the Discord.Net interactions package is really new, I cannot find a answer to this.
I have a public repository of all of my code in [here](https://github.com/Nic13Gamer/Banco-Bahia-Bot)

Thanks :)

**Comment by csmir** [comment]
Does your bot have the Application Commands scope enabled when invited to target guild(s)? If not, please reinvite your bot with that scope enabled in the invite link. 

If you did do this and this issue persists, can you lowercase your command name and see if that works? I'm not sure if the library auto-lowers the command names as Discord wants explicitly lowercase command names.

**Comment by Nic13Gamer** [comment]
Hey, the bot has the Application Commands scope.

Lowering the case of the name of the command have worked! Strange, because yesterday it did not work.

Thanks for the response!
