### ISSUE TITLE
Migration to v3.0.0 guidelines

### ISSUE THREAD

**Issue by Sasino97** [RogueException/Discord.Net#2029]
There should be a page with information on how to migrate from 2.x.x to 3.x.x since it broke backward compatibility and many method signatures have changed. For example, in the UserLeft event, there's no longer a `SocketGuildUser` object as an argument, but there's a `SocketGuild` param and a `SocketUser` param, and I have no clue on how to obtain the user's nickname in the guild.

**Comment by csmir** [comment]
It's very important to investigate the docs before opening an issue about it. [This](https://discordnet.dev/guides/v2_v3_guide/v2_to_v3_guide.html) is most likely what you're looking for.

However, a minor change like this has not been documented as it has no major influence on the workflow. As the user leaves the guild, the user is not in the guild anymore. Unless the user exists in your cache, you can't get the nickname from it anymore.

A potential way you can cast it to a guilduser is by doing ` if (olduser is SocketGuildUser oldGuilduser) `

**Comment by quinchs** [comment]
@Rozen4334 The `UserLeft` event should be added to the v3 guide when you get a chance

**Comment by quinchs** [comment]
See https://github.com/Discord-Net-Labs/Discord.Net-Labs/pull/417
