### ISSUE TITLE
Migrating existing commands to the slash interaction service

### ISSUE THREAD

**Issue by rippo** [RogueException/Discord.Net#2043]
I have finally got around to upgrading my bot to use slash commands alongside normal commands, all works good. However I am failing to find anything that allows me to register a normal command and a slash command within one end point?

An end point that uses commands and inherits from

```c#
public class PingModule : ModuleBase<SocketCommandContext>

[Command("ping")]
public async Task PingAsync() => await ReplyAsync("pong!");
```

A second end point that uses slash commands and inherits from

```c#
public class TestSlashModule : InteractionModuleBase<SocketInteractionContext>

[SlashCommand("slash", "Recieve a pong")]
public async Task SlashPing() => await RespondAsync("pong");
```

The [docs ](https://discordnet.dev/guides/v2_v3_guide/v2_to_v3_guide.html) states this, so I suppose I need to register the commands differently but nothing jumps out in intell sense and I have scanned the docs but to no avail.

![image](https://user-images.githubusercontent.com/772549/149544263-8c58e46b-d4e8-43c1-ac01-06c40282b1e8.png)

I suspect this is one of those stupid questions but I just need a pointer. Thanks

**Comment by Cenngo** [comment]
Check out the repo's [sample app](https://github.com/discord-net/Discord.Net/tree/dev/samples/04_interactions_framework) or this [demo project](https://github.com/Cenngo/InteractionsDemo).They should help you out

**Comment by Marilyth** [comment]
I think the question here is if something like this can be done (which isn't possible right now I think), which would be great and reduce redundancy.
Converting to slash commands for me meant to copy & paste all my code and change the headers.
```csharp
public class TestSlashModule : SomeModuleBase<SocketContext>

[SlashCommand("ping", "Recieve a pong")]
[Command("ping")]
public async Task PingAsync() => await ReplyAsync("pong!");
```

**Comment by Cenngo** [comment]
> I think the question here is if something like this can be done (which isn't possible right now I think), which would be great and reduce redundancy. Converting to slash commands for me meant to copy & paste all my code and change the headers.
> 
> ```cs
> public class TestSlashModule : SomeModuleBase<SocketContext>
> 
> [SlashCommand("ping", "Recieve a pong")]
> [Command("ping")]
> public async Task PingAsync() => await ReplyAsync("pong!");
> ```

Doing so would limit the capabilities of slash commands.text commands and slash commands cannot be used interchangeably. They must be responded to using different methods and their contexts are different.

**Comment by Marilyth** [comment]
I am by no means versed in the code of Discord.Net. But it seems to me the non-interchangeability is created by design, not because it is really impossible.
Slash commands and normal commands are used almost identically, after all.

**Comment by Cenngo** [comment]
> Doing so would limit the capabilities of slash commands.

why dont you create a static helper class and direct command requests there

**Comment by rippo** [comment]
Thanks all, can close this. I have the notion of a commandhandler using a mediator patterm that both end points can call.
Bot has quite a lot of commands and I feel I dont want to move them all over in one hit. 
Assummed it was a stupid question but I may have missed something. Ta
