### ISSUE TITLE
ChannelTypesAttribute does not work with slash command

### ISSUE THREAD

**Issue by Georgiks** [RogueException/Discord.Net#2047]
Adding `ChannelTypesAttribute` to `IChannel` parameter of a slash command does not have effect on restricting the allowed channel types in Discord.

I suspect the bug is here
https://github.com/discord-net/Discord.Net/blob/5897dc5a45d9ab7fbee0b80dd8da9c9311bdd429/src/Discord.Net.Interactions/TypeConverters/DefaultEntityTypeConverter.cs#L75
used from
 https://github.com/discord-net/Discord.Net/blob/5897dc5a45d9ab7fbee0b80dd8da9c9311bdd429/src/Discord.Net.Interactions/Utilities/ApplicationCommandRestUtil.cs#L29

where the type converter of the parameter (IChannel) overwrites the types from attribute

**Comment by Cenngo** [comment]
i forgot to PR the fix for this. ill do it when i get back
