### ISSUE TITLE
I can not use SocketGuildChannel

### ISSUE THREAD

**Issue by ghost** [RogueException/Discord.Net#2049]
I'm making a discord bot, and I make a channel, so in this channel I want to modify the permissions, but, when I get the channel I made, either by id or cast it as a `SocketGuildChannel` it will just throw an exception claiming it is null, and that I can not use it. I tried getting an existent channel with it's id, but it will fail anyway. 

The bot has administrator, so it should be able to get all the channels, even though I don't think this should matter at all, since the channel was made by it anyways

**Comment by drobbins329** [comment]
please share the bit of code that is not functioning as desired.

from the channel creation to the permissions modify.

**Comment by ghost** [comment]
The code that I'm doing is this one, it is to handle a ticket
```
        private static async Task MakeTicketChannel(SocketMessageComponent button, string TicketReason, ulong categoryID)
        {
            OverwritePermissions perms =
                new(
                        viewChannel: PermValue.Allow,
                        sendMessages: PermValue.Allow,
                        readMessageHistory: PermValue.Allow
                    );
            Random rand = new();
            IMessageChannel ticket = await Program.guild.CreateTextChannelAsync($"ticket-{rand.Next(0, 9999)}",
                a =>
                {
                    a.Name = "ticket-channel";
                    a.Locked = true;
                    a.CategoryId = categoryID;
                    a.IsNsfw = false;
                    a.Topic = $"A channel made to handle {button.User.Username}'s \"{TicketReason}\" Ticket.";
                });

            using (ticket.EnterTypingState())
            {
                await ticket.SendMessageAsync($"Ticket opened {button.User.Mention}! An Administrator will arrive shortly to talk with you.");
                SocketGuildChannel channel = ticket as SocketGuildChannel;
                await channel.AddPermissionOverwriteAsync(button.User, perms);
            }
        }
```

**Comment by drobbins329** [comment]
instead of IMessageChannel, try casting it as a RestGuildChannel or RestTextChannel.

Is the channel being created, and you can't interact with it? Or, is it faulting before the channel is created?

**Comment by ghost** [comment]
Let me try what you said, I can interact with it, since as you see, I send a message to it, and it actually gets sent, and the exception comes when I try to overwrite the permissions

**Comment by ghost** [comment]
Ok, That did the trick perfectly, thanks, sorry for opening an issue for such thing
