### ISSUE TITLE
System.InvalidOperationException: Cannot respond, update, or defer twice to the same interaction

### ISSUE THREAD

**Issue by xBYRKI** [RogueException/Discord.Net#2052]
Is there any chance to react on multiple button interactions in one time?
Also, is there any chance for turning off the reactions for clicking on the button without getting an error, caused of non exisiting RespondAsync?

**Comment by quinchs** [comment]
If you're trying to respond twice with two messages, use `RespondAsync` then `FollowupAsync`

This error cannot be turned off as its set by the discord api.
