### ISSUE TITLE
Missing Intent, but Intent is granted

### ISSUE THREAD

**Issue by Asrothear** [RogueException/Discord.Net#2057]
So i came across some weird Prolbem, when ever i tried to use this siple code   

```cs
SocketGuild guild = DiscordBot.Bot.GetGuild(#AWESOME_GUILD_ID#);
guild.DownloadUsersAsync().Wait();
```   

i got the following error   

```cs
xecution of Server:discord:CheckDCUser threw an error: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.AggregateException: One or more errors occurred. (Missing required gateway intent GuildMembers in order to execute this operation.)
 ---> System.InvalidOperationException: Missing required gateway intent GuildMembers in order to execute this operation.
   at Discord.WebSocket.DiscordSocketClient.EnsureGatewayIntent(GatewayIntents intents)
   at Discord.WebSocket.DiscordSocketClient.DownloadUsersAsync(IEnumerable`1 guilds)
   at Discord.WebSocket.SocketGuild.DownloadUsersAsync()
   --- End of inner exception stack trace ---
```   

![image](https://user-images.githubusercontent.com/38018660/151035605-e56305e7-c6cf-4ef1-93ef-cbd6f3877e2c.png)   

The Intends are all grandted,  and there is aboslutey no mistake that i configured the wrong bot !   

So what did i miss?

**Comment by drobbins329** [comment]
Take a read here, on intents: https://discordnet.dev/guides/v2_v3_guide/v2_to_v3_guide.html

**Comment by Asrothear** [comment]
Meh, too Simple thats why i asked what i´m missing.
I will try it, shouldn´t took to long

**Comment by Asrothear** [comment]
Thank you very much, it worked. (Why shouldn´t it ^^)
I hate google btw. everthing but not the information with the API update...
