### ISSUE TITLE
No overload for method 'ExecuteAsync' takes 2 arguments

### ISSUE THREAD

**Issue by vezcodes** [RogueException/Discord.Net#2067]
No overload for method 'ExecuteAsync' takes 2 arguments

**Comment by MaxEtMoritz** [comment]
assuming you mean [CommandService.ExecuteAsync](https://discordnet.dev/api/Discord.Commands.CommandService.html#Discord_Commands_CommandService_ExecuteAsync_Discord_Commands_ICommandContext_System_Int32_IServiceProvider_Discord_Commands_MultiMatchHandling_): You need to pass at least three arguments:
- The Command Context,
- the index where the command starts OR the command input as string (depending on which method overload you use)
- a Service Provider.

If you don't use Service Providers, pass null as third argument.
