### ISSUE TITLE
[BUG] Intents won't identify?

### ISSUE THREAD

**Issue by panthernet** [RogueException/Discord.Net#2068]
After updating to the `latest commit` from 2.4.0 I see that bot intents inside the lib during presence checks are: `AllUnprivileged`
Meanwhile all intents on the dev site has been enabled long ago and been working with 2.4.0. 

Now the lib just fails to get or download users. Need an advice  on how to fix it.

![image](https://user-images.githubusercontent.com/5926603/151665951-d868924c-792b-4711-925f-2476c6de8db6.png)

Exact error message: Missing required gateway intent GuildMembers in order to execute this operation.
`DiscordSocketClient.cs line 2912 in EnsureGatewayIntent() method`

UPD: checked bot ID on site and in Discord - identical.
UPD2: I can't find where `_gatewayIntents` var is updated, only in class constructor which seems to use default value of `AllUnprivileged`

**Comment by Hawxy** [comment]
See the relevant upgrade guide for gateway intents:
https://discordnet.dev/guides/v2_v3_guide/v2_to_v3_guide.html#gatewayintents

**Comment by panthernet** [comment]
Thanks, haven't seen that. So I must specify intents myself?
