### ISSUE TITLE
Are rate limits applied per channel or entire socket?

### ISSUE THREAD

**Issue by asteria121** [RogueException/Discord.Net#2073]
I want to make a reminder which sends dm at the specified time. (ex: Send dm every 1 minutes or 21:30) I wonder if my bot have thousand of live users and it would trigger rate limit.

**Comment by csmir** [comment]
![image](https://user-images.githubusercontent.com/68127614/151963831-23398ef9-90dd-4717-b075-1710e1d30e44.png)

At: https://discord.com/developers/docs/topics/rate-limits#rate-limits.

As stated here, rate limits per channel_id and guild_id are unique, and not global.

**Comment by asteria121** [comment]
> 

Thanks bro
