### ISSUE TITLE
Couldn't parse Discord Canary webhook URLs

### ISSUE THREAD

**Issue by minhducsun2002** [RogueException/Discord.Net#2074]
Relevant stack trace :
```
System.ArgumentException: The given webhook Url was not in a valid format. The webhook Id could not be parsed. (Parameter 'webhookUrl')
   at Discord.Webhook.DiscordWebhookClient.ParseWebhookUrl(String webhookUrl, UInt64& webhookId, String& webhookToken)
   at Discord.Webhook.DiscordWebhookClient..ctor(String webhookUrl, DiscordRestConfig config)
```
The webhook URL in question was `https://canary.discord.com/api/webhooks/937967020320899092/BWKbVhNqu5shH9t96qWQKlzYisoHmM7PIMv88-IokTdR-lwHX7fNeWKk_Y2VBtSJpD2b`
![image](https://user-images.githubusercontent.com/32769878/152136373-5777154a-0470-4d85-8308-ddaaffc6ffad.png)
(I made sure to invalidate the webhook URL for security purposes, it's fine to pass this around).

**Comment by MichailiK** [comment]
This seems to work fine for me. Can you verify that the environment variable is set as expected? (`Console.WriteLine(Environment.GetEnvironmentVariable("DISCORD_WEBHOOK_LOG");`)

**Comment by csmir** [comment]
> Can you verify that the environment variable is set as expected? (`Console.WriteLine(Environment.GetEnvironmentVariable("DISCORD_WEBHOOK_LOG");`)

Prior to the patch I pushed, webhook URL's did not allow uppercase characters in the final match. They now will, whether the URL in question was valid or not, they have discovered a flaw.

**Comment by minhducsun2002** [comment]
> This seems to work fine for me. Can you verify that the environment variable is set as expected? (`Console.WriteLine(Environment.GetEnvironmentVariable("DISCORD_WEBHOOK_LOG");`)

@michailiK It was. Sorry, I did not pay attention screenshooting it.

The bug is there even if I hard-code the URL.

**Comment by csmir** [comment]
In testing, this issue does not occur to me. Can you show reproduction code? My approach was wrong initially, so I have reverted my PR towards a fix.
