### ISSUE TITLE
Task dosent runs

### ISSUE THREAD

**Issue by NiTiSon** [RogueException/Discord.Net#2085]
[Source code](https://github.com/NiTiS-Dev/NiTiSRPGBot/blob/9d619f97e7a0b62a94d405baf8591b538e0ddcf7/Modules/AdminModule.cs)
Chunk of code what dont work
```cs
...
[Command("name")]
public Task Name(IUser user)
{
    ReplyAsync(user?.Username ?? "None");
    return Task.CompletedTask;
}
...
```

When i useit on me or other bots its works
BUT when i try to mention other users command not executes

Breakpoint shows me what it not exception on my method. He just not starts

Example:
![](https://i.imgur.com/jLdJkWm.png)

Logs:
```
[authorID:authorUsername<messageID>]messageContent
[508012163307143168:?NiTiS.Net?#3995<939908289674764348>]::name <@!938910112083476522> //Bot reply NiTiS RPG (Bot username)
[508012163307143168:?NiTiS.Net?#3995<939908315612319824>]::name <@!566569247514558464> //Task doesnt started
[508012163307143168:?NiTiS.Net?#3995<939908337150091285>]::name <@!508012163307143168> //Bot reply NiTiS.Net (My username)
```

Here we can see that message go to the attribute parser and losing

**Comment by NiTiSon** [comment]
If anyone needs, I use .Net 6

**Comment by drobbins329** [comment]
is this on d.net v3?
if so, it looks like the user you are mentioning is not cached.
take a look here:
https://discordnet.dev/guides/v2_v3_guide/v2_to_v3_guide.html

also, be sure to have AlwaysDownloadUsers in your discordscoketconfig.

**Comment by NiTiSon** [comment]
```cs
client = new DiscordSocketClient(new DiscordSocketConfig()
{
    GatewayIntents = GatewayIntents.AllUnprivileged
});
```

I Writed something like this
Same thing

**Comment by exsersewo** [comment]
Guild Members are a privileged intent, try adding the `GuildMembers` gateway intent, and enabling it in the developer dashboard.

**Comment by NiTiSon** [comment]
![](https://i.imgur.com/ukusBtc.png)

I turn up all of this checkboxes
Same thing

**Comment by NiTiSon** [comment]
Or you keep in mind other buttons

**Comment by exsersewo** [comment]
You need to add it to your client in the `DiscordSocketConfig` where you set `GatewayIntents`. 

So it becomes `GatewayIntents = GatewayIntents.AllUnprivileged | GatewayIntents.GuildMembers`.

**Comment by NiTiSon** [comment]
I wrote this
```cs
this.token = token;
this.Prefix = botPrefix;
client = new DiscordSocketClient(new DiscordSocketConfig()
{
    GatewayIntents = GatewayIntents.AllUnprivileged | GatewayIntents.GuildMembers,
    LogLevel = LogSeverity.Debug,
});
client.Log += Log;
client.Ready += LogReady;
client.MessageReceived += MessageReceived;
client.InteractionCreated += InteractionCreated;
```
Same thing :(

**Comment by exsersewo** [comment]
Try adding `AlwaysDownloadUsers = true` to your `DiscordSocketConfig`.

It's very likely that it wont be caching the users, as I just recreated the issue where it wont execute and adding that to the config allowed it to get them on startup and allows the command to execute.

**Comment by NiTiSon** [comment]
Yeap, its works
Big Russian Спасибо
