### ISSUE TITLE
How do I make NextMessageAsync work in slash commands?

### ISSUE THREAD

**Issue by HAHOOS** [RogueException/Discord.Net#2096]
Hello, so I wanted to use NextMessageAsync for my bot, but I got problem. It needs something called `SocketCommandContext` and it does need user and message, but firstly in `SocketCommandContext` user must be `DiscordSocketClient`, but `SocketClient` cannot be converted, secondly you need command message, but slash command is not a messsage, please help!

**Comment by csmir** [comment]
This is not part of Discord.Net and thus should not be resolved here. Please refer to the library you are using and open an issue there.

**Comment by HAHOOS** [comment]
Alright
