### ISSUE TITLE
GetMessagesAsync returns async collection of message-collections. Should return collection of messages.

### ISSUE THREAD

**Issue by SeidChr** [RogueException/Discord.Net#2097]
https://github.com/discord-net/Discord.Net/blob/0352374e74d4cf07696f7e13993646ea344131c5/src/Discord.Net.WebSocket/Entities/Channels/SocketTextChannel.cs#L166

Found this strange interface and wanted to embrace a change towards a more logical and usable one. 
This method should really not return a collection of collections of messages, but a collection of messages instead.

Here i am forced to iterate over the inner collection again..
![image](https://user-images.githubusercontent.com/1927076/153566703-451c4cba-6711-4493-a20a-af4f06abe483.png)

I believe you did this to reflect the server-side pagination, but IMO the API should hide this pagination behavior.

**Comment by openmilk** [comment]
It returns a collection of a collection as it may need to do more then 1 api call, hence it might return two or more collections.

**Comment by SeidChr** [comment]
Right. Thats what i meant with server-side pagination. I dont see how it is usefull to do so. If the api-user needs more message, he will just take the next one either way. but with this solution he has to ask for the next collection first, which is just jumping through the hoops. 
The api should hide this behaviour.

**Comment by quinchs** [comment]
This is because the API limits getting messages to 100 per batch.

You can flatten the collection to a single collection by calling `.FlattenAsync()` on the `IAsyncEnumerable`, this will loop over the async enumerable and join all the results together in one collection.

**Comment by SeidChr** [comment]
Good to know!
I figured that flattening is not hard to do, and the api should take care of it. 
Still strange design. What are the usecases of getting the single pages?
Also the method is saying GetMessages, and not GetMessagePages which is why i struggled with it in the first place.

**Comment by SylveonDeko** [comment]
Its because the api rate limits you to 100 messages per channel, per second

**Comment by somebody1234** [comment]
@SeidChr i'm pretty sure hiding this behavior would be extremely undesirable, since with a huge api call (e.g. if you want to delete every message) you'd have to wait for discord.net to recieve every message first... which can potentially take hours

**Comment by SeidChr** [comment]
> @SeidChr i'm pretty sure hiding this behavior would be extremely undesirable, since with a huge api call (e.g. if you want to delete every message) you'd have to wait for discord.net to recieve every message first... which can potentially take hours

I don't mean to make it synchronous. As @quinchs said, is possible to flatten the list asynchronously.

But tbh. To take care of pagination is sth i expect from the library. And it actually does take care of it. But still exposing the single pages to me for some reason. 
Would just love to understand the reason for this design. I can't think of a case where i would want to see the pages..

**Comment by somebody1234** [comment]
ah right, so you want something more like `IAsyncEnumerable<IMessage>`

**Comment by csmir** [comment]
> ...
> I don't mean to make it synchronous. As @quinchs said, is possible to flatten the list asynchronously.
> 
> But tbh. To take care of pagination is sth i expect from the library. And it actually does take care of it. But still exposing the single pages to me for some reason. Would just love to understand the reason for this design. I can't think of a case where i would want to see the pages.

**A few reasons not to change this behavior:**

- The reasons why people would want specific pages is unknown to us, but some people might.
- The Discord API limits 100 messages per get, and this library is a wrapper doing as little as possible to change the behavior Discord limits us to.
- This would be a breaking change, because `FlattenAsync()` would need to be removed by the developer to further use this call.

I truly do not see an issue with calling `FlattenAsync()` in your own code, the return type is formatted like this in respect to how the result is retrieved from Discord. There are no effects on efficiency so there is no harm in its implementation.

**Comment by somebody1234** [comment]
@Rozen4334 changing behavior is definitely a bad idea. however that doesn't mean it's a bad idea to add another function that returns a `IAsyncEnumerable<IMessage>`

**Comment by SeidChr** [comment]
So the basic discrepancy is, that the method is not doing what the name suggests.
It returns a list of lists of messages, and not a list of messages.
Adding another method which does the right thing but is named differently is just as bad, as the name it should have is already given to the original method.

Making this "right" without having a breaking change, seems to be impossible, since every change in that direction would ultimately mean to change the interface.

As I deem this a minor inconvenience, I would probably just try to highlight the workarounds a little better. Not sure whether there is a hint about .FlattenAsync() in the xml-docs about GetMessagesAsync, but it should be there and in some form in an article if possible.

**Comment by csmir** [comment]
The use of FlattenAsync and why it should be used is covered extensively on the IMessageChannel interface, which all message channels implement. All GetMessagesAsync implementations have xml that directly suggests reading this documentation for further details. Due to the different implementations among REST and Socket channel types, the documentation has not been inherited as normal.
