### ISSUE TITLE
Some Questions

### ISSUE THREAD

**Issue by NiTiSon** [RogueException/Discord.Net#2102]
+ How to create invite link to the channel?
+ How to write some actions to audit log?

**Comment by CottageDwellingCat** [comment]
You can create a channel invite by calling `CreateInviteAsync` on an `INestedChannel`:
```cs
public static async Task<IInviteMetadata> GetInviteAsync(IChannel channel)
{
	if (channel is not INestedChannel nestedChannel) 
		throw new ArgumentException("Channel must be in a guild and category.", nameof(channel));

	return await nestedChannel.CreateInviteAsync();
}
```

Bots cannot create audit entries outside of doing actions that would normally appear in the audit log. To specify the `AuditLogReason` on actions your bot takes you need to provide `RequestOptions`:
```cs
var options = new RequestOptions()
{
	AuditLogReason = "Your reason here",
};
await nestedChannel.DeleteAsync(options);
```

**Comment by NiTiSon** [comment]
Yes, but how make invite endless

**Comment by CottageDwellingCat** [comment]
The function's [documentation](https://discordnet.dev/api/Discord.INestedChannel.html#Discord_INestedChannel_CreateInviteAsync_System_Nullable_System_Int32__System_Nullable_System_Int32__System_Boolean_System_Boolean_Discord_RequestOptions_) says you can set the first parameter to `null` to disable expiration.

**Comment by NiTiSon** [comment]
Can i create Audit log from nothing (any time)?

**Comment by CottageDwellingCat** [comment]
You can not.
