### ISSUE TITLE
[Suggestion] Add support for steam:// protocols in buttons

### ISSUE THREAD

**Issue by ITeMbI4** [RogueException/Discord.Net#2105]
It will be great to use steam:// protocols in buttons

**Comment by somebody1234** [comment]
You'd probably have to ask discord to add that:
https://github.com/discord/discord-api-docs/discussions/new

**Comment by csmir** [comment]
As mentioned above, this is completely unsupported by Discord currently, so we are not capable of adding such a feature.

**Comment by ITeMbI4** [comment]
Ok, thank you.
I will ask discord for that first.
