### ISSUE TITLE
How to add slash command to every server | user?

### ISSUE THREAD

**Issue by NiTiSon** [RogueException/Discord.Net#2120]

**Comment by DaNeubi** [comment]
You might want to check out the guide on the official page: [https://discordnet.dev/guides/int_basics/application-commands/intro.html](https://discordnet.dev/guides/int_basics/application-commands/intro.html)

You should also check out the interaction framework: [https://discordnet.dev/guides/int_framework/intro.html](https://discordnet.dev/guides/int_framework/intro.html)

**Comment by NiTiSon** [comment]
Are commands added instantly? They never showed up for me.

**Comment by SylveonDeko** [comment]
Global commands take up to an hour to show up, directly adding to all guilds is not recommended as you'll hit rate limits really quickly
