### ISSUE TITLE
Add image property to CreateEventAsync.

### ISSUE THREAD

**Issue by 1NieR** [RogueException/Discord.Net#2122]
![image](https://user-images.githubusercontent.com/49203428/154573381-732df577-8371-4b80-84d1-0bdf9c284af8.png)

**Comment by nikita-petko** [comment]
This would probably make 2 versions of this method:
1 with a Stream as a parameter
1 with a string as a parameter to read a file

**Comment by Hantick** [comment]
@1NieR  How can I parse `IAttachment` sent from slash command to a `Image`?
