### ISSUE TITLE
[Bug]: Throws 'Unknown command' when responding to ComponentInteraction

### ISSUE THREAD

**Issue by Almighty-Shogun** [RogueException/Discord.Net#2129]
### Check The Docs

- [X] I double checked the docs and couldn't find any useful information.

### Verify Issue Source

- [X] I verified the issue was caused by Discord.Net.

### Check your intents

- [X] I double checked that I have the required intents.

### Description

The bots keeps responding with "Unknown command" when clicking the button. I am using the Interaction Framework and have all the events/interactions copied exactly like this example: [InteractionFramework/CommandHandler.cs](https://github.com/discord-net/Discord.Net/blob/dev/samples/InteractionFramework/CommandHandler.cs) from the samples.

I added `Console.WriteLine(arg3.ErrorReason);` to the `SlashCommandExecuted`, `ContextCommandExecuted` and `ComponentCommandExecuted` but it doesn't give me an proper error.

### Version

3.3.2

### Logs

The only thing it logs is this `No Discord.Interactions.ComponentCommandInfo found for my-button`

### Sample

The command with the button
```cs
public class Test3: InteractionModuleBase<SocketInteractionContext>
{
    [SlashCommand("button", "Shows a Discord button")]
    public async Task ButtonAsync()
    {
        await RespondAsync("Here is the button! Do you like it?", components: new ComponentBuilder().WithButton("Button", "my-button", ButtonStyle.Success).Build());
    }
}

public class Test3Interaction : InteractionModuleBase<SocketInteractionContext<SocketMessageComponent>>
{
    [ComponentInteraction("my-button")]
    public async Task ButtonAsync()
    {
        await Context.Interaction.UpdateAsync(msg => msg.Content = $"{Context.Interaction.User.Mention} has clicked the button.");
    }
}
```

The buttonExecuted code I use:
```cs
_client.ButtonExecuted += async (SocketMessageComponent smc) => 
{
      var ctx = new SocketInteractionContext<SocketMessageComponent>(_client, smc);
      await _interactionService.ExecuteCommandAsync(ctx, _serviceProvider);
};
```

**Comment by Almighty-Shogun** [comment]
Edit: I don't know for 100% sure if this is a bug caused by Discord.NET or that I am just failing to understand this.

**Comment by nikita-petko** [comment]
I think this is a Discord issue, not a Discord.Net issue, because it happens sometimes with slash commands on reregistration

**Comment by CottageDwellingCat** [comment]
You should use `[ComponentInteraction("my-button", true)]` this tells the interaction service to ignore the name of the button's parent command group.

**Comment by Almighty-Shogun** [comment]
> I think this is a Discord issue, not a Discord.Net issue, because it happens sometimes with slash commands on reregistration

I actually changed the command name for this because it was `btn` first. So the command is new. I can give it another try by giving it another name.

Edit: No that doesn't work either. It still returns 'unknown command.' see this [GIF](https://i.imgur.com/cOrnA1d.mp4) of the bot responding it after clicking the button.

**Comment by Almighty-Shogun** [comment]
> You should use `[ComponentInteraction("my-button", true)]` this tells the interaction service to ignore the name of the button's parent command group.

I just did that, and it still returns 'unknown command'

**Comment by Almighty-Shogun** [comment]
So it has been a while now and I have been trying a lot but I came to the conclusion that it came from the `ButtonExecuted` code that I used.

```cs
_client.ButtonExecuted += async (SocketMessageComponent component) => 
{
        // This does not work.
        var ctx = new SocketInteractionContext<SocketMessageComponent>(_client, component);
        await _interactionService.ExecuteCommandAsync(ctx, _serviceProvider);
        
        // This does work
        switch(component.Data.CustomId)
        {
            case "my-button":
                await component.RespondAsync($"{component.User.Mention} has clicked the button!");
            break;
        }
};
```

I don't understand why the first code doesn't work (for me). I suppose there must be a way to get this working without having to define each `customId` from buttons into this switch statement. So if I am doing something wrong can someone explain it to me and/or if you have an working example can you show it to me?

**Comment by Almighty-Shogun** [comment]
So I got it working now, I honestly didn't know what I have been doing wrong. But I started a new solution again and it suddenly worked. When someone clicked the button and the bot has responded it gives the following error:

The loggers I have enabled:
```cs
// client is DiscordSocketClient
client.Log += (msg) =>
{
    Console.WriteLine($"client: {msg.ToString()}");
    return Task.CompletedTask;
};

// cmds is InteractionService
cmds.Log += (msg) =>
{
    Console.WriteLine($"cmds: {msg.ToString()}");
    return Task.CompletedTask;
};
```

The error:
```
cmds: 13:35:31 App Command System.InvalidOperationException: Invalid context type. Expected SocketInteractionContext`1, got SocketInteractionContext.
   at Discord.Interactions.InteractionModuleBase`1.SetContext(IInteractionContext context)
   at Discord.Interactions.InteractionModuleBase`1.Discord.Interactions.IInteractionModuleBase.SetContext(IInteractionContext context)
   at Discord.Interactions.Builders.ModuleClassBuilder.<>c__DisplayClass11_0.<<CreateCallback>g__ExecuteCallback|1>d.MoveNext()
--- End of stack trace from previous location ---
   at Discord.Interactions.CommandInfo`1.ExecuteInternalAsync(IInteractionContext context, Object[] args, IServiceProvider services)
```

The error itself doesn't do anything and the bot still works after it, but I think it might need some attention from the devs.

**Comment by drobbins329** [comment]
Why break the button into a separate handler? this code:
```
private async Task HandleInteraction (SocketInteraction arg)
        {
            try
            {
                // Create an execution context that matches the generic type parameter of your InteractionModuleBase<T> modules
                var ctx = new SocketInteractionContext(_client, arg);
                await _commands.ExecuteCommandAsync(ctx, _services);
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex);

                // If a Slash Command execution fails it is most likely that the original interaction acknowledgement will persist. It is a good idea to delete the original
                // response, or at least let the user know that something went wrong during the command execution.
                if(arg.Type == InteractionType.ApplicationCommand)
                    await arg.GetOriginalResponseAsync().ContinueWith(async (msg) => await msg.Result.DeleteAsync());
            }
        }
```
        will handle button and select menu interactions fine. 
        so, you can move your [ComponentInteraction("my-button")] and subsequent method into the Test3 class.

**Comment by Almighty-Shogun** [comment]
> Why break the button into a separate handler? this code:
> 
> ```
> private async Task HandleInteraction (SocketInteraction arg)
>         {
>             try
>             {
>                 // Create an execution context that matches the generic type parameter of your InteractionModuleBase<T> modules
>                 var ctx = new SocketInteractionContext(_client, arg);
>                 await _commands.ExecuteCommandAsync(ctx, _services);
>             }
>             catch (Exception ex)
>             {
>                 Console.WriteLine(ex);
> 
>                 // If a Slash Command execution fails it is most likely that the original interaction acknowledgement will persist. It is a good idea to delete the original
>                 // response, or at least let the user know that something went wrong during the command execution.
>                 if(arg.Type == InteractionType.ApplicationCommand)
>                     await arg.GetOriginalResponseAsync().ContinueWith(async (msg) => await msg.Result.DeleteAsync());
>             }
>         }
> ```
> 
> ```
>     will handle button and select menu interactions fine. 
>     so, you can move your [ComponentInteraction("my-button")] and subsequent method into the Test3 class.
> ```

I saw it in someone's Interaction Framework demo tbh. But I'll try to use `HandleInteraction` for the button aswell.

Edit: I tried it, but it doens't do the action when the button is pressed. So I will just keep `ButtonExecuted` for now.

**Comment by quinchs** [comment]
cc @Cenngo

**Comment by Cenngo** [comment]
yeah i cannot repro this but your handlers may have been not getting registered properly. If you still have the buggy project lying around you could try to use a breakpoint to inspect the internal _componentCommandMap of the InteractionService instance to see if thats the case or not.

**Comment by Almighty-Shogun** [comment]
I don't have it anymore. I started a new project and it suddenly worked. I just assumed I did something wrong (I probably have). The issue can be closed
