### ISSUE TITLE
Can't get slash commands to work

### ISSUE THREAD

**Issue by Bregann** [RogueException/Discord.Net#2138]
Hey,

I'm moving over from D#+ however I'm struggling with getting the slash commands to work properly.

I've got this to register the Modules which it is registering properly 

![image](https://user-images.githubusercontent.com/35966588/155813325-6d4e8f95-fbb3-47ae-87db-aa7656285401.png)

![image](https://user-images.githubusercontent.com/35966588/155812755-b4d4089d-c434-4df4-9398-7461f9c89873.png)

however when doing the command in Discord it just says it doesn't respond
![image](https://user-images.githubusercontent.com/35966588/155812891-b1369bd5-cb7c-4704-a4b6-653ca55075f4.png)

![image](https://user-images.githubusercontent.com/35966588/155812916-d1bdecd1-9311-4894-8cfa-2c1268b64982.png)

The code for the slash command is below
![image](https://user-images.githubusercontent.com/35966588/155812974-315a0152-7269-4019-88cf-cdae8a1e4277.png)

Any help would be appreciated 

Thanks

**Comment by Cenngo** [comment]
You need to direct the DiscordSocketClient.InteractionCreated event to InteractionService.ExecuteCommandAsync. You can check out the [sample app](https://github.com/discord-net/Discord.Net/tree/dev/samples/InteractionFramework) and the [demo app](https://github.com/Cenngo/InteractionsDemo) to see how thats implemented.

**Comment by Almighty-Shogun** [comment]
The code for your slash command is good but it needs an extra thing. See this example:

```cs
public class DailyCommandModules: InteractionModuleBase<SocketInteractionContext>
{
	[SlashCommand("daily", "Claim your daily points")]
	public async Task DailyPointsCollection()
	{
		await RespondAsync("test");
	}
}
```

Your `DiscordSocketClient` also needs to listen and do something when the `InteractionCreated` event is triggered. Based on your code this can be done in the following way:

```cs
DiscordClient.InteractionCreated += (SocketInteraction socketInteraction) =>
{
	try
	{
		var context = new SocketInteractionContext(DiscordClient, socketInteraction);
		await _interactionService.ExecuteCommandAsync(context, _serviceProvider);
		// The '_serviceProvider' belongs to the IServiceProvider class, you need to initialize it
	}
	catch (Exception e)
	{
		Console.WriteLine(e.ToString());
        
		if(socketInteraction.Type == InteractionType.ApplicationCommand)
		{
			await socketInteraction.GetOriginalResponseAsync()
					.ContinueWith(async message => await message.Result.DeleteAsync());
		}
	}
}
```

**Comment by Bregann** [comment]
> You need to direct the DiscordSocketClient.InteractionCreated event to InteractionService.ExecuteCommandAsync. You can check out the [sample app](https://github.com/discord-net/Discord.Net/tree/dev/samples/InteractionFramework) and the [demo app](https://github.com/Cenngo/InteractionsDemo) to see how thats implemented.



> The code for your slash command is good but it needs an extra thing. See this example:
> 
> ```cs
> public class DailyCommandModules: InteractionModuleBase<SocketInteractionContext>
> {
> 	[SlashCommand("daily", "Claim your daily points")]
> 	public async Task DailyPointsCollection()
> 	{
> 		await RespondAsync("test");
> 	}
> }
> ```
> 
> Your `DiscordSocketClient` also needs to listen and do something when the `InteractionCreated` event is triggered. Based on your code this can be done in the following way:
> 
> ```cs
> DiscordClient.InteractionCreated += (SocketInteraction socketInteraction) =>
> {
> 	try
> 	{
> 		var context = new SocketInteractionContext(DiscordClient, socketInteraction);
> 		await _interactionService.ExecuteCommandAsync(context, _serviceProvider);
> 		// The '_serviceProvider' belongs to the IServiceProvider class, you need to initialize it
> 	}
> 	catch (Exception e)
> 	{
> 		Console.WriteLine(e.ToString());
>         
> 		if(socketInteraction.Type == InteractionType.ApplicationCommand)
> 		{
> 			await socketInteraction.GetOriginalResponseAsync()
> 					.ContinueWith(async message => await message.Result.DeleteAsync());
> 		}
> 	}
> }
> ```

Awesome thank you both very much for the help - got this working now :)
