### ISSUE TITLE
[Feature-request] Allow `UpdateAsync` to be used without `Context.Interaction.`

### ISSUE THREAD

**Issue by Almighty-Shogun** [RogueException/Discord.Net#2139]
Hi,

Could there be an feature where the method `UpdateAsync` from `SocketMessageComponent` can be used without having to write down `Context.Interaction.UpdateAsync` ? 

The method `FollowupAsync` comes from the same class and can be used without the `Context.Interaction`. I believe it will be easier to just use `UpdateAsync` instead of the `Context.Interaction.UpdateAsync` all the time.

**Comment by Cenngo** [comment]
`InteractionModuleBase` only exposes the methods that are shared among every interaction type. Methods like `UpdateAsync` and `DeferLoadingAsync` are exclusive to Component Interactions and it wouldn't be wise to add a pass-through method withouth knowing for sure that the interaction being handled is a Component Interaction and this may mislead newcommers. And what you are requesting can be easily implemented custom by extending the `InteractionModuleBase`.

**Comment by Almighty-Shogun** [comment]
> `InteractionModuleBase` only exposes the methods that are shared among every interaction type. Methods like `UpdateAsync` and `DeferLoadingAsync` are exclusive to Component Interactions and it wouldn't be wise to add a pass-through method withouth knowing for sure that the interaction being handled is a Component Interaction and this may mislead newcommers. And what you are requesting can be easily implemented custom by extending the `InteractionModuleBase`.

Thanks for your repsonse! How can I extend the `InteractionModuleBase` the best way? I am using your [InteractionsDemo's ComponentOnlyModule](https://github.com/Cenngo/InteractionsDemo/blob/master/InteractionsDemo/Modules/ComponentOnlyModule.cs) as an example on how to work with component interactions

**Comment by Cenngo** [comment]
Something like this should do
```cs
public abstract class ComponentModuleBase : InteractionModuleBase<SocketInteractionContext<ComponentInteraction>>
{
     protected virtual Task UpdateAsync(...) => Context.Interaction.UpdateAsync(...);
}
```
Then inherit from this whenever you want to create a module for handling Component Interactions

**Comment by Almighty-Shogun** [comment]
> Something like this should do
> 
> ```cs
> public abstract class ComponentModuleBase : InteractionModuleBase<SocketInteractionContext<ComponentInteraction>>
> {
>      protected virtual Task UpdateAsync(...) => Context.Interaction.UpdateAsync(...);
> }
> ```
> 
> Then inherit from this whenever you want to create a module for handling Component Interactions

Thanks for the example. It works, so I am happy.
