### ISSUE TITLE
More clarity is needed on using Components - e.g. TextInputs/Modals

### ISSUE THREAD

**Issue by owenashurst** [RogueException/Discord.Net#2140]
Hi,

I'm trying to figure out how to use text inputs however the [documentation](https://discordnet.dev/guides/int_basics/message-components/text-input.html) seems to lack how to actually use it in a response back to the author/channel.

When a SelectMenuExecuted event is invoked, you get a SocketMessageComponent. From what I understand, you can use this to respond back to the user or the channel where it was invoked from.

I need further information from the user after the SelectMenu has been used, so I try and create a TextInputBuilder like so;

```
var textInputBuilder = new TextInputBuilder()
                    .WithLabel("My Text")
                    .WithCustomId("text_input");
```

I then try and send this via
```
await arg.Channel.SendMessageAsync("", components: builder.Build());
```

Where arg is of type `SocketMessageComponent`

However, that isn't valid as SendMessageAsync requires an embed or message component. 

So the question is, how do you use it as it isn't specified in the docs?

Thanks,
Owen

**Comment by CottageDwellingCat** [comment]
`TextInputComponents` can only be used inside of modals, Discord says this is to avoid issues typing in a moving text box if chat goes quickly.

**Comment by owenashurst** [comment]
Thanks @CottageDwellingCat. I've just come across https://discordnet.dev/guides/int_basics/modals/intro.html which I didn't see before. This has helped out a lot. Thanks.

**Comment by Almighty-Shogun** [comment]
If you want a `TextInputBuilder` you need a modal as said by the user above me. You can do it this way:

```cs
public class Test5: InteractionModuleBase<SocketInteractionContext>
{
    [SlashCommand("modal", "Get a test modal")]
    public async Task GetModal()
    {
        var mb = new ModalBuilder()
            .WithTitle("Test modal")
            .WithCustomId("food_menu")
            .AddTextInput("What is your favorite food?", "food_name", placeholder:"Pizza")
            .AddTextInput("Why it is your favorite food?", "food_reason", TextInputStyle.Paragraph, "I like the flavor!");

        await RespondWithModalAsync(mb.Build());
    }
}
```
