### ISSUE TITLE
[Bug]: Cannot delete components from `InteractionModuleBase<SocketInteractionContext>`

### ISSUE THREAD

**Issue by Almighty-Shogun** [RogueException/Discord.Net#2142]
### Check The Docs

- [X] I double checked the docs and couldn't find any useful information.

### Verify Issue Source

- [X] I verified the issue was caused by Discord.Net.

### Check your intents

- [X] I double checked that I have the required intents.

### Description

When trying out the new components I am trying different solutions and how to use them etc. I came to the following conclusion for myself:

1. When using a different class for handling with buttons, select menus and using  `InteractionModuleBase<SocketInteractionContext<SocketMessageComponent>>` I can delete the component, but when a user uses the select menu is keeps saying the interaction failed
2. When using the command and the handling for buttons, select menus etc and using `InteractionModuleBase<SocketInteractionContext>` I can't delete the component, but the interaction doesn't fail.

Is there a way to get one of the two above working? Either the separate classes but that each interaction will work or that there is a way to remove the component.

I am not very familiar with C# so far and have only being doing it for a month or two now. I've seen a few repo's of how to use the `InteractionFramework` and I still can't figure it out. So please help me out and/or explain if I am doing something wrong.

### Version

3.3.2

### Logs

None

### Sample

**Command and interaction handler in the same class**
```cs
public class ButtonModule: InteractionModuleBase<SocketInteractionContext>
{
    [SlashCommand("button", "Get a Discord button")]
    public async Task ButtonAsync()
    {
        var btnOne = new ButtonBuilder()
        {
            Label = "Button 1",
            CustomId = "my-button",
            Style = ButtonStyle.Primary,
            Emote = new Emoji("😊")
        };

        await RespondAsync("Here is a button.", components: new ComponentBuilder().WithButton(btnOne).Build());
    }
    
    [ComponentInteraction("my-button")]
    public async Task ButtonHandlerAsync()
    {
        await ModifyOriginalResponseAsync(msg =>
        {
            msg.Content = "YOU CLICKED ME YOOOOHOOOOOOOO";
            msg.Components = null; // This doesn't work
        });
    }
}
```

**Command and handler in a different class**

```cs
// Command
public class ButtonModuleSeparate: InteractionModuleBase<SocketInteractionContext>
{
    [SlashCommand("button2", "Get a Discord button")]
    public async Task ButtonAsync()
    {
        var btnOne = new ButtonBuilder()
        {
            Label = "Button 2",
            CustomId = "my-button-2",
            Style = ButtonStyle.Primary,
            Emote = new Emoji("😊")
        };

        await RespondAsync("Here is a button.", components: new ComponentBuilder().WithButton(btnOne).Build());
    }
}

// Handler
public class ButtonModuleHandler : InteractionModuleBase<SocketInteractionContext<SocketMessageComponent>>
{
    [ComponentInteraction("my-button-2")]
    public async Task ButtonHandlerAsync()
    {
        await Context.Interaction.UpdateAsync(msg =>
        {
            msg.Content = "Button 2 can be removed :D";
            msg.Components = null; // This does work
        });
    }
}
```

**Comment by Almighty-Shogun** [comment]
For people having the same troubles with select menu's not working when having it in a separate class/file and are using `InteractionModuleBase<SocketInteractionContext<SocketMessageComponent>>`. If you're select menu is sending but does not do anything after you have used it and the `customId` has `-` in it replace it with `_`.

It appears the `customId` for select menu's cannot contain a `-`

**Comment by MapManagement** [comment]
Hey, I just ran in a similar but not quite the same bug, so I just thought about asking you.
The ``UpdateAsync`` method only works for me, if I set the components of the previous message to ``null``. I cannot replace the components with something else. I tried select menus, buttons and a mix of both but I wasn't able to update the components. Changing the content of the original message also worked.
Is there something else I need to take care of?

**Comment by cjbonn** [comment]
> Hey, I just ran in a similar but not quite the same bug, so I just thought about asking you. The `UpdateAsync` method only works for me, if I set the components of the previous message to `null`. I cannot replace the components with something else. I tried select menus, buttons and a mix of both but I wasn't able to update the components. Changing the content of the original message also worked. Is there something else I need to take care of?

Wait for the next release, or build using the current - this was already fixed, it's just not in a public release yet. Where null doesn't work, pass in an empty object instead.

**Comment by MapManagement** [comment]
Thank you for this information, I would have tried for several hours more.
