### ISSUE TITLE
[Bug]: SocketThreadChannel.Owner returns null

### ISSUE THREAD

**Issue by budgetdevv** [RogueException/Discord.Net#2143]
### Check The Docs

- [X] I double checked the docs and couldn't find any useful information.

### Verify Issue Source

- [X] I verified the issue was caused by Discord.Net.

### Check your intents

- [X] I double checked that I have the required intents.

### Description

Interestingly, `SocketThreadChannel.Owner` returns null. Not too sure if such is intended, as I expected the owner to be the starter of the thread

### Version

3.6.1

### Logs

Sample code prints true

### Sample

```cs
Console.WriteLine(Thread.Owner == null);
```

**Comment by Almighty-Shogun** [comment]
Can you show me an example how you did this? I am trying to reproduce this

**Comment by budgetdevv** [comment]
Sure thing!

```cs
Client.ThreadCreated += OnThreadCreated;
.
.
.
private static Task OnThreadCreated(SocketThreadChannel Thread)
{
   Console.WriteLine(Thread.Owner == null);
   
   return Task.CompletedTask;
}
```

**Comment by budgetdevv** [comment]
As per Discord docs, the owner will be the user in which started the thread it seems

**Comment by csmir** [comment]
Is AlwaysDownloadUsers enabled in your socket config? Do you have the guildmembers intent enabled?

**Comment by budgetdevv** [comment]
I have all intents enabled...not too sure about AlwaysDownloadUsers, will go figure!

**Comment by budgetdevv** [comment]
Seems to be still null, despite adding AlwaysDownloadUsers to the config

**Comment by csmir** [comment]
Who is creating the thread?

**Comment by budgetdevv** [comment]
A GuildUser

**Comment by drobbins329** [comment]
You have Gateway Intents set in both the dev portal AND the DiscordSocketConfig?

**Comment by budgetdevv** [comment]
Yup

**Comment by quinchs** [comment]
Can you try using Discord.Net 3.3.2 instead of Labs?

**Comment by budgetdevv** [comment]
@quinchs Tried using 3.3.2, still returns null
