### ISSUE TITLE
Ambigiuous call preventing creation of role.

### ISSUE THREAD

**Issue by RickyDivjakovski** [RogueException/Discord.Net#2167]
Check The Docs
- [x]  double checked the docs and couldn't find any useful information.

Verify Issue Source
- [x]  verified the issue was caused by Discord.Net.

Check your intents
- [x]  double checked that I have the required intents.

Description
Unable to create a role due to an ambiguous call.

Version
3.4.0

Working Version
None since prior to version 2.2.0

Sample
// Create a new role
`SocketRole role = await arg.CreateRoleAsync("MyRole");`
Throws a compiler ambiguity error.
Reproduced by members in the discord API server

Screenshot
![image](https://user-images.githubusercontent.com/4088705/156859265-af4cfcc4-6c06-4cd6-9c38-83edfd8e9aad.png)

Error surfaced in 2.2.0 and has not been resolved
![image](https://user-images.githubusercontent.com/4088705/156859035-e89df0b1-abec-49c0-ab61-272bf5bc5770.png)

**Comment by csmir** [comment]
Due to the nature of our versioning, removing this now will result in a breaking change. This **will** be resolved, but not before 4.x.
