### ISSUE TITLE
Hide commands from application list

### ISSUE THREAD

**Issue by Almighty-Shogun** [RogueException/Discord.Net#2172]
Hello everyone,

Is there a way how to "hide" commands from the application list when a user does not has the required permissions? I made an group "change-bot" and added `RequireOwner`. But the user can still see the command, but cannot execute it. Is there any way to hide it?

Here is the code (if needed)
```cs
[Group("change-bot", "Change things of the bot")]
[RequireOwner]
public class ChangeAvatarCommand : InteractionModuleBase<SocketInteractionContext>
{
    [SlashCommand("avatar", "Change avatar of the bot")]
    public async Task ChangeBotAvatarAsync()
    {
        await RespondAsync("change-bot avatar command executed.");
    }
    
    [SlashCommand("status", "Change status of the bot")]
    public async Task ChangeBotStatusAsync()
    {
        await RespondAsync("change-bot status command executed.");
    }
    
    [SlashCommand("game", "Change game of the bot")]
    public async Task ChangeBotGameAsync()
    {
        await RespondAsync("change-bot game command executed.");
    }
}
```

**Comment by CottageDwellingCat** [comment]
This is not currently possible but discord says they may support in the future.

**Comment by Almighty-Shogun** [comment]
Is there a way then to send the user a message in the form off a response to let them know they can't use the command?

**Comment by SylveonDeko** [comment]
Yes, use an Ephemeral response using the SlashCommandExecuted event

**Comment by SylveonDeko** [comment]
https://github.com/Sylveon76/Mewdeko/blob/main/src/Mewdeko/Services/CommandHandler.cs#L92

**Comment by Almighty-Shogun** [comment]
I was just about to ask for a example, but you sended it already. Thanks for the example.

**Comment by SylveonDeko** [comment]
Np
