### ISSUE TITLE
Expose ContentType/Description in IAttachment

### ISSUE THREAD

**Issue by SquidDev** [RogueException/Discord.Net#2177]
I'm currently porting a bot to Discord.Net, and noticed that while [the content_type/description fields][attachment] are available on the internal `Attachment` type, they're not present on the public `IAttachment`/`Attachment` types.

Just wondering if there was a reason these were left off (not sure if they're read-only in some contexts), or if you'd accept a PR to add them?

[attachment]: https://discord.com/developers/docs/resources/channel#attachment-object

**Comment by SquidDev** [comment]
Thank you so much!

**Comment by quinchs** [comment]
Thanks for the Computer craft mods! Kept me busy thru quarantine!
