### ISSUE TITLE
Does UserStatus include a status for when a user is streaming "Live on Twitch"?

### ISSUE THREAD

**Issue by rixis19** [RogueException/Discord.Net#2191]
I've been looking at the API to see if there is a way to detect if a user is streaming on Twitch via checking if their status is set to Streaming via the UserStatus enum. I've noticed that there is no field for if they are streaming in UserStatus, so I am wondering if there is a way to check for this. I was unsure if this would fall under another status field or is simply undocumented.

**Comment by Almighty-Shogun** [comment]
`UserStatus` is only for the user's actual status like `Online`, `Dnd/DoNotDisturb`, `Idle` or `Invisible/Offline`. I'll check to see if I am able to find some way to see that, when I do I'll post the used code here.

**Comment by Almighty-Shogun** [comment]
@rixis19 I've found an way to do this.

The code I've been using (just made it quickly):
```cs
public class TestCommand : InteractionModuleBase<SocketInteractionContext>
{
    [RequireOwner]
    [SlashCommand("my-activity", "test-command")]
    public async Task GetUserActivity()
    {
        var user = Context.User as SocketGuildUser;

        var userActivities = user?.Activities.ToList();

        var userAct = userActivities?.First();

        var respondMsg = "";

        respondMsg += "```\n";
        respondMsg += $"User: {user?.Username}\n"; // To see if we have the correct user
        respondMsg += $"ActivityType: {userAct?.Type}\n"; // "Playing" etc...
        respondMsg += $"ActivityName: {userAct?.Name}\n"; // The name of the game
        respondMsg += "```";
        
        await RespondAsync(respondMsg);
    }
}
```
The image below shows the output (it is correct)
![image](https://user-images.githubusercontent.com/96011415/158886205-8dab4b3e-6a61-47a3-8212-ad693e1ea169.png)

**Comment by MagKon** [comment]
> @rixis19 I've found an way to do this.
> 
> The code I've been using (just made it quickly):
> 
> ```cs
> public class TestCommand : InteractionModuleBase<SocketInteractionContext>
> {
>     [RequireOwner]
>     [SlashCommand("my-activity", "test-command")]
>     public async Task GetUserActivity()
>     {
>         var user = Context.User as SocketGuildUser;
> 
>         var userActivities = user?.Activities.ToList();
> 
>         var userAct = userActivities?.First();
> 
>         var respondMsg = "";
> 
>         respondMsg += "```\n";
>         respondMsg += $"User: {user?.Username}\n"; // To see if we have the correct user
>         respondMsg += $"ActivityType: {userAct?.Type}\n"; // "Playing" etc...
>         respondMsg += $"ActivityName: {userAct?.Name}\n"; // The name of the game
>         respondMsg += "```";
>         
>         await RespondAsync(respondMsg);
>     }
> }
> ```
> 
> The image below shows the output (it is correct) ![image](https://user-images.githubusercontent.com/96011415/158886205-8dab4b3e-6a61-47a3-8212-ad693e1ea169.png)

Sorry to revive an old thread, but I am having trouble getting any activities from the user and I am unsure of what I am doing wrong. I can find the user (me) but it doesn't return a value when I check my activities while I am listening to Spotify or in a game.

I'm still fairly new to making Discord bots and I am slowly learning how and what.

**Comment by Almighty-Shogun** [comment]
> > @rixis19 I've found an way to do this.
> > The code I've been using (just made it quickly):
> > ```cs
> > public class TestCommand : InteractionModuleBase<SocketInteractionContext>
> > {
> >     [RequireOwner]
> >     [SlashCommand("my-activity", "test-command")]
> >     public async Task GetUserActivity()
> >     {
> >         var user = Context.User as SocketGuildUser;
> > 
> >         var userActivities = user?.Activities.ToList();
> > 
> >         var userAct = userActivities?.First();
> > 
> >         var respondMsg = "";
> > 
> >         respondMsg += "```\n";
> >         respondMsg += $"User: {user?.Username}\n"; // To see if we have the correct user
> >         respondMsg += $"ActivityType: {userAct?.Type}\n"; // "Playing" etc...
> >         respondMsg += $"ActivityName: {userAct?.Name}\n"; // The name of the game
> >         respondMsg += "```";
> >         
> >         await RespondAsync(respondMsg);
> >     }
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The image below shows the output (it is correct) ![image](https://user-images.githubusercontent.com/96011415/158886205-8dab4b3e-6a61-47a3-8212-ad693e1ea169.png)
> 
> Sorry to revive an old thread, but I am having trouble getting any activities from the user and I am unsure of what I am doing wrong. I can find the user (me) but it doesn't return a value when I check my activities while I am listening to Spotify or in a game.
> 
> I'm still fairly new to making Discord bots and I am slowly learning how and what.

Did the code I provided not work? Because it worked for me. If it doesn't work, please let me know asap and I will try to see what it going wrong.

**Comment by MrCakeSlayer** [comment]
Keep in mind you'll need to have the presence intent enabled on the Discord Dev panel and specify it in your intents to grab user presence/statuses

**Comment by Almighty-Shogun** [comment]
Also what @MrCakeSlayer said. You need to enable the intent for that.

The intent in the developer panel.
![image](https://user-images.githubusercontent.com/96011415/163016264-8c972c51-a316-4f86-b950-567f7d9d774d.png)

You also need to set the intents you are using with `DiscordSocketConfig`.

The code I am using for that is this:
```cs
const discordConfig = new DiscordSocketConfig
{
	GatewayIntents = GatewayIntents.AllUnprivileged | GatewayIntents.GuildMembers | GatewayIntents.GuildPresences,
	AlwaysDownloadUsers = true
};
var client = new DiscordSocketClient(discordConfig);
```

**Comment by MagKon** [comment]
> Also what @MrCakeSlayer said. You need to enable the intent for that.
> 
> The intent in the developer panel. ![image](https://user-images.githubusercontent.com/96011415/163016264-8c972c51-a316-4f86-b950-567f7d9d774d.png)
> 
> You also need to set the intents you are using with `DiscordSocketConfig`.
> 
> The code I am using for that is this:
> 
> ```cs
> const discordConfig = new DiscordSocketConfig
> {
> 	GatewayIntents = GatewayIntents.AllUnprivileged | GatewayIntents.GuildMembers | GatewayIntents.GuildPresences,
> 	AlwaysDownloadUsers = true
> };
> var client = new DiscordSocketClient(discordConfig);
> ```

It is most likely here I am doing something wrong but I don't fully understand where to implement this. 
Following the guides and samples is a bit messy as they seem to disagree on how to do stuff...

Edit:
I attempted to use this for socket config
`        
        private readonly DiscordSocketConfig _socketConfig = new()
        {

            GatewayIntents = GatewayIntents.AllUnprivileged | GatewayIntents.GuildMembers,
            AlwaysDownloadUsers = true,
        };
`
but it still returns 0. 
I tried adding your slash command as a text command as I simply don't understand how slash commands work at the current moment.

Edit 2:
It is working now! I was simply missing 'GatewayIntents.GuildPresences' in my Gateway.

**Comment by Almighty-Shogun** [comment]
@TheLonelyDude glad u got it working!
