### ISSUE TITLE
Invalid throwed exceptions

### ISSUE THREAD

**Issue by Almighty-Shogun** [RogueException/Discord.Net#2199]
Hello,

So everytime I us an button, select-menu, modal in my command the code keeps throwing errors while there is nothing wrong. I am using the https://discordnet.dev/guides/int_framework/post-execution.html#commandexecuted-events as code.

The error it keeps throwing:
```
Invalid context type. Expected SocketInteractionContext`1, got SocketInteractionContext.
```

The code works just fine as it executed and handles everything perfect.

Edit: Is there a way to fix this? I want to get actual exceptions when they happen, but I don't wanna get spammed with invalid exceptions.

**Comment by Alan-Shan** [comment]
Second this. 
Also getting:
```
App Commands: System.InvalidOperationException: Invalid context type. Expected SocketInteractionContext`1, got SocketInteractionContext.
   at Discord.Interactions.InteractionModuleBase`1.SetContext(IInteractionContext context)
   at Discord.Interactions.InteractionModuleBase`1.Discord.Interactions.IInteractionModuleBase.SetContext(IInteractionContext context)
   at Discord.Interactions.Builders.ModuleClassBuilder.<>c__DisplayClass11_0.<<CreateCallback>g__ExecuteCallback|1>d.MoveNext()
--- End of stack trace from previous location ---
   at Discord.Interactions.CommandInfo`1.ExecuteInternalAsync(IInteractionContext context, Object[] args, IServiceProvider services)

``` 
while using slash command declared as: 
```
public class ExampleClass: InteractionModuleBase<SocketInteractionContext<SocketSlashCommand>>
{
    [SlashCommand("command", "This is a command")]
    public async Task Command()
    {
        await RespondAsync(111.ToString());
    }
} 
```
This exception could be resolved by just inheriting from ```InteractionModuleBase<SocketInteractionContext>``` and not specifying  the type of interactions contained in the module, which at least lowers it severity. But it's pretty misleading since as [samples show](https://github.com/discord-net/Discord.Net/blob/dev/samples/InteractionFramework/Modules/SlashCommandModule.cs) you should be able to create SlashCommand's modules. (Also if you try to run that example it won't register any command declared in SlashCommandModule, which is also kinda confusing).

Is it something wrong with the sample or am I registering modules which inherit ` SocketInteractionContext<TInteraction> ` incorrectly?

**Comment by Almighty-Shogun** [comment]
It is in the example so I think `InteractionModuleBase<SocketInteractionContext<SocketSlashCommand>>` is what needs to be used and is what I am using to. When handling an error (result) I have been testing with some checks to see if `result.ErrorReason` contains **Invalid context type. Expected SocketInteractionContext`1, got SocketInteractionContext.**. When I use that, the bot won't execute anything and says it is an invalid webhook.

So I have the exact same question as @Alan-Shan 
> Is it something wrong with the sample or am I registering modules which inherit SocketInteractionContext<TInteraction> incorrectly?

Or might it even by a bug?

Edit: I just hope it will be fixed before I make my bot public and accessable to users, kinda not in the mood for getting spammed to dead because it throws invalid exceptions 😅

**Comment by Alan-Shan** [comment]
@Almighty-Shogun it works if you inherit your command module from `InteractionModuleBase<SocketInteractionContext>`. But if you try to run the example, it's not even registering commands defined in the module which inherits SocketSlashCommand context. 

Although in my project it sees and registers them correctly just not executing and throwing that invalid context exception.

**Comment by Almighty-Shogun** [comment]
@Alan-Shan yeah I might go full "noob" mode now but I don't really understand what u mean. The way I am doing it is that all slash commands, button/modal/select-menu commands and their handlers are in separate classes. I like it this way to keep a little bit of order

**Comment by Alan-Shan** [comment]
> @Alan-Shan yeah I might go full "noob" mode now but I don't really understand what u mean. The way I am doing it is that all slash commands, button/modal/select-menu commands and their handlers are in separate classes. I like it this way to keep a little bit of order

Take a look [here](https://github.com/discord-net/Discord.Net/blob/dev/samples/InteractionFramework/Modules/GeneralModule.cs).
```
    public class GeneralModule : InteractionModuleBase<SocketInteractionContext>
```
it inherits ```InteractionModuleBase<SocketInteractionContext>``` but you still can declare Slash Commands as follows:
```
        [SlashCommand("echo", "Repeat the input")]
        public async Task Echo(string echo, [Summary(description: "mention the user")]bool mention = false)
        {
            await RespondAsync(echo + (mention ? Context.User.Mention : string.Empty));
        }
```
You can ofc add other types of interactions in a General Module but if you want to separate logically, just keep only Slash Commands in that class. Hope it helps! 😄

**Comment by csmir** [comment]
The issue comes down to a bad context creation. If you have a module with a generic context signature, you will want to create a generic context:

```cs
public static IInteractionContext CreateGeneric(SocketInteraction interaction, DiscordSocketClient client)
    => interaction switch
    {
        SocketModal modal => new SocketInteractionContext<SocketModal>(client, modal),
        SocketUserCommand user => new SocketInteractionContext<SocketUserCommand>(client, user),
        SocketSlashCommand slash => new SocketInteractionContext<SocketSlashCommand>(client, slash),
        SocketMessageCommand message => new SocketInteractionContext<SocketMessageCommand>(client, message),
        SocketMessageComponent component => new SocketInteractionContext<SocketMessageComponent>(client, component),
        _ => throw new InvalidOperationException("This interaction type is unsupported! Please report this.")
    };
 ```
 > This operation works the same for rest & sharded interaction contexts, and can be swapped out without consequences.
 
 This method is how I create generic contexts for modules that are declared as such:
 
 ```cs
 
 var context = CreateGeneric(interaction, client);
 
 ```
 - Alternatively you can do as @Alan-Shan mentioned, and remove the generic marking from the module signature.
 
 Projects that implement both generic as well as non-generic modules will not work with the same context. Depending on the name/data of the command received, you will want to pass a different kind of context. This greatly complicates usage, so it's best to use unboxing inside your methods for specific interaction data.

**Comment by Almighty-Shogun** [comment]
I still don't understand this. So I am gonna try to explain my situation on how my code is build.

For slash commands I use: `InteractionModuleBase<SocketInteractionContext>`
For buttons/select-menu I use: `InteractionModuleBase<SocketInteractionContext<SocketMessageComponent>>`
For modals I use: `InteractionModuleBase<SocketInteractionContext<SocketModal>>`

I make for each command a separate file. For commands that have buttons/select-menu's or modals I have 2 classes:
- CommandName
- CommandNameHandler

Whenever a command uses:
- Button
- Select menu
- Modal

It throws the invalid exception.

The code for my `_client.InteractionCreated`
```cs
var context = new SocketInteractionContext(_client, socketInteraction);
await _interactionService.ExecuteCommandAsync(context, _serviceProvider);
```

The code for my `_client.ButtonExecuted` and `_client.SelectMenuExecuted`
```cs
var context = new SocketInteractionContext<SocketMessageComponent>(_client, socketMessageComponent);
await _interactionService.ExecuteCommandAsync(context, _serviceProvider);
```

The code for my `_client.ModalSubmitted`
```cs
var context = new SocketInteractionContext<SocketModal>(_client, socketModal);
await _interactionService.ExecuteCommandAsync(context, _serviceProvider);
```

What am I doing wrong and how can I resolve it?

Am I supposed to remove
- `<SocketMessageComponent>` from button/select-menu classes?
- `<SocketModal>` from modal classes?

And if I would use the `CreateGeneric` method u have provided how would I apply it into my code? Does it needs to be in an event or? Please help me to understand this

**Comment by csmir** [comment]
The `InteractionCreated` event is fired regardless of the other subscribed-to events, so your `InteractionCreated` will fire even if the interaction type matches an already subbed event. This is what causes the error.

You already answered your own question. You *should* remove the `<SocketMessageComponent>` and `<SocketModal>` signature to decrease further complicating the assembly with sorting and depending on the command type to handle the interaction.

The `CreateGeneric` method can be anywhere, in an extension class, inside the `HandleInteraction` method or whatever else you want. It's just a static method after all.

If you want to change the signature of your 'default' module, you can, and then you can apply the use of `CreateContext` inside the `InteractionCreated` event. You do not need to handle interactions in separate events. This works both ways, so if you remove all `<T>` from the `SocketInteractionContext`, you can also just remove the separate events and depend on `InteractionCreated`.

**Comment by Almighty-Shogun** [comment]
Thank u for explaining it more to me. I have a better understanding of how the code works now.
