### ISSUE TITLE
[Bug]: Failed to create role

### ISSUE THREAD

**Issue by NebulaMods** [RogueException/Discord.Net#2200]
### Check The Docs

- [X] I double checked the docs and couldn't find any useful information.

### Verify Issue Source

- [X] I verified the issue was caused by Discord.Net.

### Check your intents

- [X] I double checked that I have the required intents.

### Description

Not throwing an exception or continuing to execute any code after failing to create role because of ratelimit, even when retry mode is set to fail always in the client config. 

request: https://unhittable.nebulamods.ca/3E7VHO24
response: https://unhittable.nebulamods.ca/29TQ8YG8

### Version

3.6.1

### Logs

n/a

### Sample

```cs
                try
                {
                    var broken = await Context.Guild.CreateRoleAsync("broken ratelimit", null, null, false, null);
                    if (broken is null)
                        continue;
                }
                catch(Exception e)
                {
                    Console.WriteLine(e.Message);
                }
```

### Packages

Discord.Net.Labs

**Comment by csmir** [comment]
Please update to Discord.Net and see if this issue persists. Labs development has been deprecated and will not contain any further fixes/patches. 

> Discord.Net is several versions ahead, while containing everything Labs originally implemented

**Comment by MrCakeSlayer** [comment]
@NebulaMods are you still having this issue when using the main DNet library instead of labs?
Also the 2 images you uploaded are no longer available, could you use something more persistent such as imgur?

**Comment by NebulaMods** [comment]
Hello, yes I am.

**Comment by wnelson03** [comment]
@Rozen4334 he's using stable and still having issues

**Comment by csmir** [comment]
I will attempt to reproduce this. Please try to get some images again, because these are no longer available as @MrCakeSlayer already mentioned.

**Comment by csmir** [comment]
I can't reproduce this. I have attempted to create 100 roles in the same guild in a for-loop, with no issues at all. 
```cs
            for (int i = 0; i < 100; i++)
            {
                try
                {
                    var broken = await Context.Guild.CreateRoleAsync("broken ratelimit", null, null, false);
                    if (broken is null)
                        continue;
                }
                catch (Exception e)
                {
                    Console.WriteLine(e.Message);
                }
            }
```
![image](https://user-images.githubusercontent.com/68127614/168481331-450de3eb-1a1c-4723-97de-67fdb148b5d7.png)
