### ISSUE TITLE
[Bug]: EnumInput in Slashcommands don't work with RequireNSFW

### ISSUE THREAD

**Issue by Bilgard** [RogueException/Discord.Net#2207]
### Check The Docs

- [X] I double checked the docs and couldn't find any useful information.

### Verify Issue Source

- [X] I verified the issue was caused by Discord.Net.

### Check your intents

- [X] I double checked that I have the required intents.

### Description

This works:
```
        [SlashCommand("test","test")]
        public async Task HentaiCom(testEnum thema)
        {
            await RespondAsync("test");
        }
```
But this doesn't work:
```
        [SlashCommand("test","test")]
        [RequireNsfw]
        public async Task HentaiCom(testEnum thema)
        {
            await RespondAsync("test");
        }
```

### Version

3.4.1

### Logs

nA

### Packages

just discord.net

**Comment by quinchs** [comment]
What doesn't work about it? Does it throw an error? does it let people execute the command in non-nsfw channels?

One thing to note is make sure you're using the `Discord.Interactions.RequireNsfw` enum.
