### ISSUE TITLE
Feature: `ParameterSummary` above the method

### ISSUE THREAD

**Issue by Almighty-Shogun** [RogueException/Discord.Net#2208]
Hello everyone,

I am not sure if this is possible but what if there is a way to add the current summary now used for parameters, to be placed above the method? When having multiple parameters in a commands it can become very messy in my opinion.

What if there is a way to use the parameter summary above the method? Like this:

```cs
namespace Example;

public class ExampleClass : InteractionModuleBase<SocketInteractionContext>
{
	[SlashCommand("say", "Let the bot say something")]
	[ParameterSummary("echo", "Give some text the bot will say for u")]
	public async Task HandleCommandAsync(string echo) => await RespondAsync(echo);
}
```

**Comment by exsersewo** [comment]
This already exists within the library.
See [SummaryAttribute](https://discordnet.dev/api/Discord.Interactions.SummaryAttribute.html)

With your example it would work as such:
```cs
public class ExampleClass : InteractionModuleBase<SocketInteractionContext>
{
	[SlashCommand("say", "Let the bot say something")]
	public async Task HandleCommandAsync([Summary(description: "Give some text the bot will say for u")] string echo) => await RespondAsync(echo);
}
```

**Comment by Almighty-Shogun** [comment]
@exsersewo I know that [SummaryAttribute](https://discordnet.dev/api/Discord.Interactions.SummaryAttribute.html) already exists. My question is a feature for it to be above the method and not in the `(...)` of the method.

Current
```cs
public class ExampleClass : InteractionModuleBase<SocketInteractionContext>
{
	[SlashCommand("say", "Let the bot say something")]
	public async Task HandleCommandAsync([Summary(description: "Give some text the bot will say for u")] string echo) => await RespondAsync(echo);
}
```

The feature I meant:
```cs
public class ExampleClass : InteractionModuleBase<SocketInteractionContext>
{
	[SlashCommand("say", "Let the bot say something")]
        [Summary("echo", "Give some text the bot will say for u")]
	public async Task HandleCommandAsync(string echo) => await RespondAsync(echo);
}
```

**Comment by exsersewo** [comment]
Ahh. My bad, I completely misread. 😅😅

**Comment by Almighty-Shogun** [comment]
> Ahh. My bad, I completely misread. 😅😅

No worries. Tbh I think (if possible) this feature will be really good, because if you need to add an `Summary` for each parameter the method will become very long. And it the way I showed it, were u can place it above the method the code will be more organized and cleaner (personal opinion)

**Comment by CottageDwellingCat** [comment]
If your issue is method length you could insert newlines and put `[Summary]` and the param on the same line:
```cs
[SlashCommand("edit", "modify a guild attribute")]
public async Task Edit
(
	[Autocomplete(typeof(GuildCharacterAttributeAutocompleteProvider))]
	[Summary("attribute", "the attribute to edit.")] GuildCharacterAttribute attribute,
	[Summary("required", "Do characters need the attribute to rollplay?")] bool? required = null,
	[Summary("validator", "Enter the regex validator to check attributes against")] string? validator = null,
	[Summary("min-length", "Enter the shortest aloud input length")] int? minValue = null,
	[Summary("max-length", "Enter the largest aloud input length")] int? maxValue = null,
	[Summary("multiline", "Is the attribute multiline?")] bool? multiline = null
)
```

**Comment by exsersewo** [comment]
@CottageDwellingCat I was just about to post that 😅

**Comment by Almighty-Shogun** [comment]
@CottageDwellingCat that is tbh an option, but not an option I would prefer

**Comment by Cenngo** [comment]
How do you propose to tie the attributes to the actual parameters? In my oppinion the only viable option is to do something like this:
```cs
[SlashCommand(...)]
[Summary("msg", "name", "description")]
public async Task Command(string msg)
{ ...}
```
(cant recall if nameof() works witth command parameters but even if it does)
This is just adding more points of failure and complexity. If we botch the name field to simplify this then we are sacrificing the abilify to customize parameter names independently from clr name regulations. And i would prefer to have the compiler catch any discrepancies in the naming on compile time. I understand that this feature would make customizing parameter names more convenient but i wouldnt sacrifice code robustness for that.

**Comment by Almighty-Shogun** [comment]
@Cenngo 

> How do you propose to tie the attributes to the actual parameters?

I have honestly no idea, while I have some experience in C# I am not that good on to make such functionalities. But if it would add more `failure and complexity` as you said, maybe the feature is not worth it then? I have honestly no idea how it works and how it will work may if ever be implemented. It is just an idea I thought of when adding description for the parameters.

**Comment by SylveonDeko** [comment]
Why not try and find out how xml comments do it?

**Comment by Cenngo** [comment]
> Why not try and find out how xml comments do it?

Xml comments still do it using the name of the parameter but with Xml comments, name validation is done by the compiler which wouldnt be the case if we used string literals for that purpose.

**Comment by csmir** [comment]
This does not appear to be a realistic idea for now
