### ISSUE TITLE
[Bug]: SerializerError on startup using Guilds intent

### ISSUE THREAD

**Issue by DylanTusler** [RogueException/Discord.Net#2214]
### Check The Docs

- [X] I double checked the docs and couldn't find any useful information.

### Verify Issue Source

- [X] I verified the issue was caused by Discord.Net.

### Check your intents

- [X] I double checked that I have the required intents.

### Description

When my client starts up, I am using the following:

```
   var config = new DiscordSocketConfig
            {
                GatewayIntents = GatewayIntents.GuildMessages 
                | GatewayIntents.GuildMessageReactions 
                | GatewayIntents.GuildEmojis 
                | GatewayIntents.GuildMembers
                | GatewayIntents.GuildVoiceStates
                | GatewayIntents.DirectMessageReactions
                | GatewayIntents.DirectMessageTyping
                | GatewayIntents.DirectMessages
                | GatewayIntents.GuildEmojis
                | GatewayIntents.Guilds
            };
            _client = new DiscordSocketClient(config);
            _client.Log += Log;
            _client.Ready += _client_Ready;
            _client.SlashCommandExecuted += _client_SlashCommandExecuted;

```

After the Connected event, I receive two SerializerError exceptions
{"Error converting value {null} to type 'System.DateTimeOffset'. Path 'threads[1].thread_metadata.create_timestamp'."}
These are being thrown by Newtonsoft.
After this the bot seems to operate normally.

If I remove the GatewayIntents.Guilds intent, then the SerializerErrors go away, but also my slashcommands don't work any more.

My codebase recently migrated to the latest version of Discord.Net as I am adding slashcommands to an existing bot.

Console output:
```
Discord.Net v3.4.1 (API v9)
Connecting
Connected
Serializer Error
Serializer Error
Ready
```

### Version

3.4.1

### Logs

 at Newtonsoft.Json.JsonSerializer.Deserialize[T](JsonReader reader)\r\n   at Discord.Net.Converters.OptionalConverter`1.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)

### Packages

  <package id="Discord.Net" version="3.4.1" targetFramework="net472" />
  <package id="Discord.Net.Commands" version="3.4.1" targetFramework="net472" />
  <package id="Discord.Net.Core" version="3.4.1" targetFramework="net472" />
  <package id="Discord.Net.Interactions" version="3.4.1" targetFramework="net472" />
  <package id="Discord.Net.Rest" version="3.4.1" targetFramework="net472" />
  <package id="Discord.Net.Webhook" version="3.4.1" targetFramework="net472" />
  <package id="Discord.Net.WebSocket" version="3.4.1" targetFramework="net472" />
  <package id="Newtonsoft.Json" version="13.0.1" targetFramework="net472" />

**Comment by csmir** [comment]
Fix is already committed, will be implemented in new release soon

**Comment by punchready** [comment]
(#2184)

**Comment by MrCakeSlayer** [comment]
Should be fixed in the latest release https://github.com/discord-net/Discord.Net/releases/tag/3.5.0
