### ISSUE TITLE
[Bug]: Library doesn't work when bot has only "application.command" permission without "bot" permissions

### ISSUE THREAD

**Issue by vit3k** [RogueException/Discord.Net#2215]
### Check The Docs

- [X] I double checked the docs and couldn't find any useful information.

### Verify Issue Source

- [X] I verified the issue was caused by Discord.Net.

### Check your intents

- [X] I double checked that I have the required intents.

### Description

It looks like library doesn't work when only "applications.commands" permission is assigned without "bot" permission (that means that we can use commands but bot is not visible on the server)

I get this error during receiving interaction and interaction handler is not called:
```
18:23:56 Gateway     Error handling Dispatch (INTERACTION_CREATE):
System.NullReferenceException: Object reference not set to an instance of an object.
   at Discord.WebSocket.DiscordSocketClient.ProcessMessageAsync(GatewayOpCode opCode, Nullable`1 seq, String type, Object payload)
```

When I change nothing in code and only apply "bot" permission to my bot and it joins the server and it's visible then it works:
```
18:24:59 Gateway     Received Dispatch (INTERACTION_CREATE)
interaction created: 958763787035504640

```
It works in discord.js library.

### Version

3.4.1

### Logs

18:23:56 Gateway     Error handling Dispatch (INTERACTION_CREATE):
System.NullReferenceException: Object reference not set to an instance of an object.
   at Discord.WebSocket.DiscordSocketClient.ProcessMessageAsync(GatewayOpCode opCode, Nullable`1 seq, String type, Object payload)

### Sample

using Discord;
```
using Discord.WebSocket;

var _client = new DiscordSocketClient(new DiscordSocketConfig {
    LogLevel = LogSeverity.Debug
});

_client.Log += Log;
_client.Ready += async () => {
    var slashCommandProps = new SlashCommandBuilder().WithName("echo").WithDefaultPermission(true).WithDescription("echo").Build();
    await _client.Rest.CreateGuildCommand(slashCommandProps, guildId);

    _client.InteractionCreated += InteractionCreatedHandler;
};

await _client.LoginAsync(TokenType.Bot, "secret token");
await _client.StartAsync();

await Task.Delay(Timeout.Infinite);

async Task InteractionCreatedHandler(SocketInteraction interaction) {
    Console.WriteLine("interaction created: " + interaction.Id);
}

async Task Log(LogMessage msg)
{
    Console.WriteLine(msg.ToString());
}
```

### Packages

Discord.Net

**Comment by csmir** [comment]
Even passthrough events cannot be served to the client if the socketclient has no access to the gateway (bot scope). This is no bug of the library. The application.commands scope is responsible for the REST interactions counterpart of the API and to control commands themselves, **not their execution.**

**Comment by vit3k** [comment]
It works when I'm using Discord.js so it's possible. Also in documentation we have https://discord.com/developers/docs/interactions/application-commands#authorizing-your-application

> Application commands do not depend on a bot user in the guild; they use the [interactions](https://discord.com/developers/docs/interactions/receiving-and-responding) model. To create commands in a guild, your app must be authorized with the applications.commands scope.

> If your application does not require a bot user within the guild for its commands to work, **you no longer need to add for the bot scope or specific permissions.**

**Comment by csmir** [comment]
It appears this may have been implemented outside of my knowledge.

**Comment by vit3k** [comment]
Hi @Rozen4334 
I was looking through your PR and there is this comment:
`// The channel isnt required when responding to an interaction, so we can leave the channel null.`

I think channel id would be usefull if one wants to restrict using slash command only to specific channels.

**Comment by csmir** [comment]
#2217 has received a [commit](https://github.com/discord-net/Discord.Net/pull/2217/commits/1f0d639352d2dcd6d7b1633801e5ddedb2451ffe) to expose this property.
