### ISSUE TITLE
[Bug]: GetBansAsync() cannot get more than 1000 Users

### ISSUE THREAD

**Issue by 1NieR** [RogueException/Discord.Net#2232]
### Check The Docs

- [X] I double checked the docs and couldn't find any useful information.

### Verify Issue Source

- [x] I verified the issue was caused by Discord.Net.

### Check your intents

- [X] I double checked that I have the required intents.

### Description

Guild.GetBansAsync() cannot get more than 1000 Users.

![](https://media.discordapp.net/attachments/848177410306342942/961145289127919687/unknown.png)
![](https://media.discordapp.net/attachments/848177410306342942/961145289371168778/unknown.png)

### Version

Discord.Net 3.5.0

### Working Version

Discord.Net 3.4.1

### Logs

No response

### Sample

```cs
            public async Task Unban([Leftover] string user)
            {
                var bans = await ctx.Guild.GetBansAsync(limit: 25000).FlattenAsync().ConfigureAwait(false);

                var bun = bans.FirstOrDefault(x => x.User.ToString()?.ToLowerInvariant() == user.ToLowerInvariant());

                if (bun is null)
                {
                    return;
                }
                
                await UnbanInternal(bun.User).ConfigureAwait(false);
            }
 ```

### Packages

No response

**Comment by exsersewo** [comment]
You can only get 1,000 per request at a time, you'll have to navigate the collection rather than flattening a single collection for it.

https://discord.com/developers/docs/resources/guild#get-guild-bans
![image](https://user-images.githubusercontent.com/25526843/161991034-7a3d4d4c-61f7-4c6c-bb58-add261187b48.png)

**Comment by 1NieR** [comment]
@exsersewo Shouldn't it work the same way as the GetMessagesAsync()?
![image](https://user-images.githubusercontent.com/49203428/161994612-07180b54-7217-4eca-b8b2-43bf2727cd9a.png)
![image](https://user-images.githubusercontent.com/49203428/161995138-0c4c39e4-f4b5-4495-9019-a2d34008760b.png)

**Comment by csmir** [comment]
It does, the intended behavior is to make calls until the self-defined limit is reached. Currently trying to figure out what is causing this to close out at 1000.
