### ISSUE TITLE
Create private channel

### ISSUE THREAD

**Issue by gbrlstr** [RogueException/Discord.Net#2240]
how can i ta creating private channel.
even using 
`AddPermissionOverwriteAsync viewChannel:PermValue.Allow`
Everyone can see the new text channel creating.

**Comment by budgetdevv** [comment]
You're allowing viewing of channels?

**Comment by gbrlstr** [comment]
> 
yes. this is my code.

![discord](https://user-images.githubusercontent.com/23707052/162593946-827740ea-1328-4ece-a16f-cf9aa088582b.png)

**Comment by budgetdevv** [comment]
OK, I think I understand now. Perhaps deny read perms for the @everyone role?

**Comment by gbrlstr** [comment]
I did that but still no success =/

**Comment by csmir** [comment]
Why are you not setting the overwrites on channel creation? You can do so by using the channel properties action behind the name. 

Right now, you're allowing everyone to view the channel (or whatever default perms the category has*), and manually adding the user to also be able to view the channel. You need to set the default channel permissions to disallow, and then add the user to allow.

**Comment by csmir** [comment]
Closing by lack of followup.
