### ISSUE TITLE
Command parameters no longer have a description

### ISSUE THREAD

**Issue by Scorr** [RogueException/Discord.Net#225]
Not sure if this is an intended change or a regression bug. Commands still have a Description and a Summary, but now command parameters only have a Summary. Trying to add a Description to a command parameter (like in the docs) will result in the error
`Attribute 'Description' is not valid on this declaration type. It is only valid on 'class, method' declarations.`

I imagine this isn't intended because description and summary mean different things.

**Comment by khionu** [comment]
It's intended.

**Comment by khionu** [comment]
More information: Description is intended to be the Long cosmetic texts, while Summary is meant to be the Short

**Comment by khionu** [comment]
Last note, 1.0 is still in Dev. Things are changing, and they will continue to change. This is to be expected when using a WIP version of any software
