### ISSUE TITLE
[Enhancement] Add who deleted the message to MessageDeleted event

### ISSUE THREAD

**Issue by storm37000** [RogueException/Discord.Net#2252]
It would be nice to be able to get who deleted the message, for logging purposes for example.

**Comment by MrCakeSlayer** [comment]
All information that Discord sends with the event is passed down through the events already.

**Comment by SylveonDeko** [comment]
You would need to get guild audit data for that, and filter by deleted messages

**Comment by SylveonDeko** [comment]
Just do note that it doesn't show when messages are self deleted

**Comment by MrCakeSlayer** [comment]
You would also run into the issue where the bot might not actually have access to view the audit log data as well.

**Comment by BobVul** [comment]
Bots deleting single messages also won't come up in the audit logs so you can't assume an unlogged delete is always a self-delete.
