### ISSUE TITLE
[Bug]: Oauth2 The server sent close 4004: "Authentication failed."

### ISSUE THREAD

**Issue by yungd1plomat** [RogueException/Discord.Net#2253]
### Check The Docs

- [X] I double checked the docs and couldn't find any useful information.

### Verify Issue Source

- [X] I verified the issue was caused by Discord.Net.

### Check your intents

- [X] I double checked that I have the required intents.

### Description

The server sent close 4004: "Authentication failed." when using oauth2 token
Get token with oauth2 from https://discord.com/api/oauth2/authorize?client_id=1234&redirect_uri=https%3a%2f%2flocalhost%3a7258%2fapi%2fauth&response_type=code&scope=messages.read
And this token not working with DiscordSocketClient

### Version

3.5.0

### Logs

Gateway     System.Exception: WebSocket connection was closed
 ---> Discord.Net.WebSocketClosedException: The server sent close 4004: "Authentication failed."
   at Discord.Net.WebSockets.DefaultWebSocketClient.RunAsync(CancellationToken cancelToken)
   --- End of inner exception stack trace ---
   at Discord.ConnectionManager.WaitAsync()
   at Discord.WebSocket.DiscordSocketClient.OnConnectingAsync()
   at Discord.ConnectionManager.ConnectAsync(CancellationTokenSource reconnectCancelToken)
   at Discord.ConnectionManager.<>c__DisplayClass29_0.<<StartAsync>b__0>d.MoveNext()

### Sample

```
        static Task Client_Log(Discord.LogMessage arg)
        {
            Console.WriteLine(arg.ToString());
            return Task.CompletedTask;
        }

        static async Task Main()
        {
            DiscordSocketClient client = new DiscordSocketClient();
            client.Log += Client_Log;
            await client.LoginAsync(Discord.TokenType.Bearer, "PEygWQXYAr7XWzzl0DWsAnEhtqLe9R", false);
            await client.StartAsync();
            Console.ReadLine();
        }
```

### Packages

nothing

**Comment by MrCakeSlayer** [comment]
You get your bot's token from the bot page on the discord developer dashboard:
https://discord.com/developers/applications/{YOURBOTID}/bot

**Comment by yungd1plomat** [comment]
> You get your bot's token from the bot page on the discord developer dashboard: [https://discord.com/developers/applications/{YOURBOTID}/bot](https://discord.com/developers/applications/%7BYOURBOTID%7D/bot)

no, i want to use user oauth2 token, not bot

**Comment by MrCakeSlayer** [comment]
The library supports bot tokens, not user tokens. You shouldn't be trying to make a user bot as it's against TOS.

**Comment by yungd1plomat** [comment]
> The library supports bot tokens, not user tokens. You shouldn't be trying to make a user bot as it's against TOS.

![изображение](https://user-images.githubusercontent.com/64736191/163875882-594acf3a-bea5-4c87-b8a5-c69423f61100.png)

**Comment by MrCakeSlayer** [comment]
You can interact with the API using user tokens yes, however, you're trying to use a bot library. DNet only supports bot tokens.

Using user tokens is for authenticating a user via a website to do actions on their behalf using their account token. Such as listing servers they are in or inviting them to a server.

DNet is not used for web authentication and is used for creating bots.

**Comment by yungd1plomat** [comment]
> You can interact with the API using user tokens yes, however, you're trying to use a bot library. DNet only supports bot tokens.

![изображение](https://user-images.githubusercontent.com/64736191/163876440-f30ea3a3-acf0-4790-a1c7-156d3a5ee6d5.png)

**Comment by csmir** [comment]
Bearer tokens are also applicable for OAuth2 apps such as web dashboards. OAuth2 tokens are not directly user-tokens. It appears you are misinformed. Another maintainer has already given you a clear answer. Discord.Net is a recognized library by Discord itself, and adheres to its TOS. By their terms, user tokens cannot be used inside Discord.Net.
