### ISSUE TITLE
ITextChannel lacks getter for AutoArchiveDuration

### ISSUE THREAD

**Issue by TheKrush** [RogueException/Discord.Net#2257]
`await textChannel.ModifyAsync(x => x.AutoArchiveDuration = threadArchiveDuration);`

ITextChannel can modify the value but has no way of fetching the current value.

version 3.5

**Comment by Spider570** [comment]
If you cast the channel as an IThreadChannel then you can get that property.

Example:
`var duration = (textChannel as IThreadChannel).AutoArchiveDuration`

**Comment by TheKrush** [comment]
> If you cast the channel as an IThreadChannel then you can get that property.
> 
> Example: `var duration = (textChannel as IThreadChannel).AutoArchiveDuration`

Does that work on non-threads?

![image](https://user-images.githubusercontent.com/671500/164878254-e6e63e03-1bf4-4621-8f85-eeddc0969f5f.png)

Like would it work on "high-times-bar-grill" ?

**Comment by TheKrush** [comment]
Yeah if you try that on a normal text channel, it returns null. But discord definitely has the value on them as the client shows it.

**Comment by TheKrush** [comment]
![image](https://user-images.githubusercontent.com/671500/164883595-2d285acf-cdf5-4dcc-8bef-cb0d003f4ce7.png)
It also appears that using it in the ModifyAsync call also doesn't work. But here it is marked in the discord client showing it's an option for a channel.
