### ISSUE TITLE
[Bug]: Missing CreateWebhook API Command

### ISSUE THREAD

**Issue by Deantwo** [RogueException/Discord.Net#2258]
### Check The Docs

- [X] I double checked the docs and couldn't find any useful information.

### Verify Issue Source

- [X] I verified the issue was caused by Discord.Net.

### Check your intents

- [X] I double checked that I have the required intents.

### Description

I cannot find a method to create a new channel webhook anywhere in **Discord.NET**.

The API call exists in the Discord API here: https://discord.com/developers/docs/resources/webhook#create-webhook

I would have assumed that the method would exist on either the `IMessageChannel` interface or the `IGuild` interface. But it is neither in the code nor in the **Discord.NET** documentation.

### Version

3.5.0

### Logs

N/A

### Packages

N/A

**Comment by SylveonDeko** [comment]
ITextChannel#CreateWebhookAsync

https://discordnet.dev/api/Discord.ITextChannel.html#Discord_ITextChannel_CreateWebhookAsync_System_String_Stream_Discord_RequestOptions_

**Comment by Deantwo** [comment]
Oh, well I feel stupid now. I guess I forgot that `IMessageChannel` isn't that same as `ITextChannel`.

Google kept failing me too, but I guess I didn't google for specifcally "CreateWebhookAsync". Having "webhook" in a google search brings up a lot of stuff specific to webhooks only.

Thanks and sorry.

**Comment by Anu6is** [comment]
Search the two repo or docs instead of Google
