### ISSUE TITLE
[Bug]: ShardedClient not working!

### ISSUE THREAD

**Issue by s1upy** [RogueException/Discord.Net#2279]
### Check The Docs

- [x] I double checked the docs and couldn't find any useful information.

### Verify Issue Source

- [x] I verified the issue was caused by Discord.Net.

### Check your intents

- [X] I double checked that I have the required intents.

### Description

ShardedClient is not working. I completely copied the source code and set everything up, but the problem is that when the Bot starts, it gives an error related to the registration of slash commands.
![image](https://user-images.githubusercontent.com/64200055/166140908-8c5f860c-3b4a-4f74-8f8e-6ffa8959fe52.png)

### Version

3.6.1

### Logs

System.InvalidOperationException: "Provided client is not ready to execute this operation, invoke this operation after a `Client Ready` event"

### Sample

using Discord;
using Discord.Commands;
using Discord.Interactions;
using Discord.WebSocket;
using Microsoft.Extensions.DependencyInjection;
using Bot.Services;
using System;
using System.Threading;
using System.Threading.Tasks;

namespace Bot
{
    // This is a minimal example of using Discord.Net's Sharded Client
    // The provided DiscordShardedClient class simplifies having multiple
    // DiscordSocketClient instances (or shards) to serve a large number of guilds.
    class Program
    {
        static void Main(string[] args)
            => new Program()
                .MainAsync()
                .GetAwaiter()
                .GetResult();

        public async Task MainAsync()
        {
            var config = new DiscordSocketConfig
            {
                TotalShards = 2
            };

            using (var services = ConfigureServices(config))
            {
                var client = services.GetRequiredService<DiscordShardedClient>();

                // The Sharded Client does not have a Ready event.
                // The ShardReady event is used instead, allowing for individual
                // control per shard.
                client.ShardReady += ReadyAsync;
                client.Log += LogAsync;

                await services.GetRequiredService<InteractionHandlingService>()
                    .InitializeAsync();

                /* await services.GetRequiredService<CommandHandlingService>()
                    .InitializeAsync(); */

                // Tokens should be considered secret data, and never hard-coded.
                await client.LoginAsync(TokenType.Bot, "TOKEN");
                await client.StartAsync();

                await Task.Delay(Timeout.Infinite);
            }
        }

        private ServiceProvider ConfigureServices(DiscordSocketConfig config)
            => new ServiceCollection()
                .AddSingleton(new DiscordShardedClient(config))
                .AddSingleton<CommandService>()
                .AddSingleton(x => new InteractionService(x.GetRequiredService<DiscordShardedClient>()))
                .AddSingleton<CommandHandlingService>()
                .AddSingleton<InteractionHandlingService>()
                .BuildServiceProvider();

        private Task ReadyAsync(DiscordSocketClient shard)
        {
            Console.WriteLine($"Shard Number {shard.ShardId} is connected and ready!");
            return Task.CompletedTask;
        }

        private Task LogAsync(LogMessage log)
        {
            Console.WriteLine(log.ToString());
            return Task.CompletedTask;
        }
    }
}

### Packages

N/A

**Comment by Cenngo** [comment]
You need to register your commands in the ReadyAsync handler

**Comment by s1upy** [comment]
> You need to register your commands in the ReadyAsync handler

Sorry I'm new to this. Can you show an example please?

**Comment by Cenngo** [comment]
```cs
_client.Ready += ReadyAsync;

private async Task ReadyAsync()
{
     if (Program.IsDebug())
         await _interactionService.RegisterCommandsToGuildAsync(_configuration.GetValue<ulong>("testGuild"), true);
     else
         await _interactionService.RegisterCommandsGloballyAsync(true);
}
```

If you want to take a look at a working barebones example, there is a sample project [here](https://github.com/discord-net/Discord.Net/tree/dev/samples/InteractionFramework)

**Comment by s1upy** [comment]
> ```cs
> _client.Ready += ReadyAsync;
> 
> private async Task ReadyAsync()
> {
>      if (Program.IsDebug())
>          await _interactionService.RegisterCommandsToGuildAsync(_configuration.GetValue<ulong>("testGuild"), true);
>      else
>          await _interactionService.RegisterCommandsGloballyAsync(true);
> }
> ```
> 
> If you want to take a look at a working barebones example, there is a sample project [here](https://github.com/discord-net/Discord.Net/tree/dev/samples/InteractionFramework)

But I use code with shards. There is no client.Ready...

**Comment by Cenngo** [comment]
You need to use Shard_Ready in that case

**Comment by s1upy** [comment]
> You need to use Shard_Ready in that case

I tried but it doesn't work...

**Comment by csmir** [comment]
It is very unlikely that this not working is caused by Discord.Net. Rest client initialization is part of the first shard, so the first time ShardReady is called the client *is* ready to accept application command calls. Please consider looking at the flow of the code, and potentially supply some more code that may be the cause so we can reproduce.

**Comment by csmir** [comment]
@Slupy has this been resolved? If not, please follow up on the above message.

**Comment by bootyberry** [comment]
I have the same exact issue. The code sample from https://github.com/discord-net/Discord.Net/tree/dev/samples/ShardedClient just doesn't work and gives this error. Copy and paste, no changes.
