### ISSUE TITLE
Inconsistency between property type and its comment in IGuild.PremiumSubscriptionCount

### ISSUE THREAD

**Issue by gehongyan** [RogueException/Discord.Net#2280]
Around `IGuild.PremiumSubscriptionCount`.

The type is `int`, but it is commented that `<see langword="null" /> if not available`.

I am not sure which is better to change the type to `int?` or `Optional<int>`, or to edit the comment. Hence the opening of this issue.

> https://github.com/discord-net/Discord.Net/blob/dev/src/Discord.Net.Core/Entities/Guilds/IGuild.cs#L272-L274

**Comment by csmir** [comment]
Very late followup on this issue, I apologize. This property should be made nullable indeed.

**Comment by gehongyan** [comment]
#1685 
#1686 

Current behaviors need to be investigated.
