### ISSUE TITLE
[Bug]: Application commands are disabled to everyone except admins by default

### ISSUE THREAD

**Issue by d4n3436** [RogueException/Discord.Net#2292]
### Check The Docs

- [X] I double checked the docs and couldn't find any useful information.

### Verify Issue Source

- [X] I verified the issue was caused by Discord.Net.

### Check your intents

- [X] I double checked that I have the required intents.

### Description

On Discord.Net 3.6.0+, all application commands (except sub-commands) are being registered with `default_member_permissions` set to 0 by default. [According to Discord](https://discord.com/developers/docs/interactions/application-commands#application-command-object), setting this to 0 means the commands will be disabled to everyone except admins by default. This can be proven by requesting the app commands and inspecting the JSON response:

```json
[
    {
        "id": "972032022631567420",
        "application_id": "id",
        "version": "974181358614233090",
        "default_permission": true,
        "default_member_permissions": "0", // Message command, disabled to everyone except admins
        "type": 3, 
        "name": "Reverse Image Search",
        "description": "",
        "dm_permission": true
    },
    {
        "id": "972032022631567421",
        "application_id": "id",
        "version": "974181358614233091",
        "default_permission": true,
        "default_member_permissions": null, // Slash command group, enabled to everyone
        "type": 1, 
        "name": "img",
        "description": "Image search commands.",
        "dm_permission": true,
        "options": []
    },
    {
        "id": "972032022631567427",
        "application_id": "450865985545830401",
        "version": "974181358614233097",
        "default_permission": true,
        "default_member_permissions": "0", // Top-level slash command, disabled to everyone except admins
        "type": 1,
        "name": "help",
        "description": "Displays some help.",
        "dm_permission": true
    },
]
```
Downgrading to 3.5.0 fixes the issue.

### Version

3.6.1

### Working Version

3.5.0

### Logs

None

### Sample

None

### Packages

None

**Comment by Cenngo** [comment]
hmm, that wasnt an issue when i did the closed beta testing. i wonder if theyve changed the behaviour at some point. ill make a pr for this tonight.
