### ISSUE TITLE
Add support for slash command attachment option (11)

### ISSUE THREAD

**Issue by dmcbride** [RogueException/Discord.Net#2301]
It appears discord [supports attachments on slash commands](https://discord.com/developers/docs/interactions/application-commands#application-command-object-application-command-option-type) as type 11.  This works in my testing using `(ApplicationCommandOptionType)11` as the command option type.  However, I can't yet figure out how to get the attachment, probably because the returned json field is being ignored.

This issue is to request the enhancement that would allow Discord.NET(.Labs) applications to use this feature, both as an additional enum and as the attachments coming back.

**Comment by Almighty-Shogun** [comment]
Would be nice if it was added. Would be an easier way to update the avatar of the bot and could be usefull for other commands.

**Comment by dmcbride** [comment]
Nevermind - I was still on the .Labs version, the regular version has this, so just need the documentation updated.

**Comment by Almighty-Shogun** [comment]
> Nevermind - I was still on the .Labs version, the regular version has this, so just need the documentation updated.

Documentation has been added (by me) the PR for this is still open https://github.com/discord-net/Discord.Net/pull/2302
