### ISSUE TITLE
Does FromError (precondition) send an message to the user?

### ISSUE THREAD

**Issue by mquillot** [RogueException/Discord.Net#2308]
Hello,

Firstly, thank you for the work you did on Discord.net, it's very cool! :D 

In my code, I have custom precondition (in interaction mode) that just return an error (FromError). It was just a test but I will verify somethings latter. 

I observed that the user that tries to launch the command get the following message even if I add a string to FromError: "The application did not respond".

So my question is : How can I send a message when the precondition is not respected?

Here you can find the code of my precondition attribute and of my module : 
```c#
public class RequireSignUp : PreconditionAttribute
{
    public override async Task<PreconditionResult> CheckRequirementsAsync(IInteractionContext context, ICommandInfo commandInfo, IServiceProvider services)
    {
            return PreconditionResult.FromError("You need to signup before using this command!");
    }
}
```

```c#
[SlashCommand("mycommand", "a basic command")]
[RequireSignUp]
public async Task mycommand(IUser user)
{
  // Something
}
```

More info : I use .NET 6 on a Mac M1 (yes it works very well) and I use the version 3.6.1 of Discord.Net.

I suppose it is not a bug but I preferred to create an issue to ensure that. And maybe you can help easily.
Best regards.

**Comment by csmir** [comment]
Quick answer: not by default. Long answer: you can make it. The `InteractionService` has an event called `InteractionExecuted` or something like that. When subscribing to this, itll be called every time a command is executed. `IResult` will be the `PreconditionResult` of your command in case it failed, so if you check `IsSuccess == false` and cast to `PreconditionResult`, you can extract your error message, and use the `IInteractionContext.Interaction` parameter to send a message to the user in question.

**Comment by mquillot** [comment]
Ok, so I created this method on my CommandHandler class that I created previously: 

```c#
private async Task<Task> InteractionExecuted(ICommandInfo commandInfo, IInteractionContext interactionContext, IResult result)
{
    if(result.IsSuccess == false)
    {
        await interactionContext.User.SendMessageAsync(result.ErrorReason);
    }
    return Task.CompletedTask;
}
```

And then I added it to the "InteractionExecuted" from my InteractionService 
Here I declare the service on my CommandHandler (it was already made before)
```c#
private readonly InteractionService _commands;
```

Here I add my method InteractionExecuted to the events handled by my service
```c#
_commands.InteractionExecuted += InteractionExecuted; 
```

And everything is working fine! Thank you! 😇
