### ISSUE TITLE
[Bug]: InteractionCommandError.ConvertFailed doesn't throw exception

### ISSUE THREAD

**Issue by Zaratusa** [RogueException/Discord.Net#2310]
### Check The Docs

- [X] I double checked the docs and couldn't find any useful information.

### Verify Issue Source

- [X] I verified the issue was caused by Discord.Net.

### Check your intents

- [X] I double checked that I have the required intents.

### Description

A `InteractionCommandError.ConvertFailed` is shown as "The application did not respond" when using slash commands, it should at least throw an exception.

### Version

3.6.1´

### Logs

They are missing....

**Comment by Cenngo** [comment]
This is not a bug, you are the one who is responsible for handling the execution result and notifying the user. Interaction service provides the means for achieving this https://discordnet.dev/guides/int_framework/post-execution.html
