### ISSUE TITLE
getChannel getGuild return null

### ISSUE THREAD

**Issue by Mikisugi** [RogueException/Discord.Net#2314]
hi,
i saw that this question has been asked many times but i couldn't find my answer in them.
so i'm trying to use the getChannel getGuild commands because i want to send announcement messages. but for some reason they alway return null.
i have put them in the client.ready handler so the client should be ready when getChannel or getGuild is being called.

**Comment by Tripletri** [comment]
It will be easier to deal with this, if you provide code samples and links to relative issues.

**Comment by csmir** [comment]
`GetChannel` and `GetGuild` address the `DiscordSocketClient`'s cache. If you have not yet received an event from the guild/channel in question, it will not be cached and thus the value will be `null`. Consider getting the channel/guild from REST instead, which addresses the Discord API itself: `_client.Rest.GetChannelAsync/GetGuildAsync`.
