### ISSUE TITLE
Removing of IMessage.CleanContent

### ISSUE THREAD

**Issue by Tripletri** [RogueException/Discord.Net#2317]
# Problem
## Wrong implementation
As docs says, it represents _"message stripped of mentions, markdown…"_.
https://github.com/discord-net/Discord.Net/blob/54a5af7db40188b94adc263141955b8a896f82dc/src/Discord.Net.Core/Entities/Messages/IMessage.cs#L55-L61
It's implementation uses `Format.StripMarkDown`https://github.com/discord-net/Discord.Net/blob/54a5af7db40188b94adc263141955b8a896f82dc/src/Discord.Net.Core/Format.cs#L98-L108
This method simply removes the markdown characters without considering the context.
Test for this function does't cover more complicated cases.
https://github.com/discord-net/Discord.Net/blob/54a5af7db40188b94adc263141955b8a896f82dc/test/Discord.Net.Tests.Unit/FormatTests.cs#L63-L76
Related issue: #2118
## Hard to maintain
As discord markdown changing we need to correct this feature too.
# Suggestion
This feature should be removed until it is correctly implemented so as not to confuse users.

**Comment by JustArchi** [comment]
The solution is to use proper markdown parsing library such as https://github.com/xoofx/markdig instead of relying on very poorly implemented regex.

Removing a valid feature just because it doesn't work doesn't address #2118.
