### ISSUE TITLE
[Bug]: Discord Caching can prevent connection to the gateway

### ISSUE THREAD

**Issue by ndelta0** [RogueException/Discord.Net#2327]
### Check The Docs

- [X] I double checked the docs and couldn't find any useful information.

### Verify Issue Source

- [X] I verified the issue was caused by Discord.Net.

### Check your intents

- [X] I double checked that I have the required intents.

### Description

Discord could possibly cache an invalid response for the `/gateway` endpoint thus preventing the connection to the Gateway. Today at around 11 AM UTC Discord cached the following response for about 5 hours (depending on the geological location):
```json
{
  "global": true,
  "message": "You are being rate limited.",
  "retry_after": 0.77
}
```
thus not getting the Gateway address and not being able to connect.

My recommendation would be to either:

- Try calling the gateway endpoint with a random query argument
- Always use the `/gateway/bot` endpoint which requires authentication and thus is not cached

### Version

3.x

### Logs

n/a

### Packages

n/a

**Comment by ooliver1** [comment]
for reference [discord.gg/developers#api-questions@gateway endpoint ratelimit issue](https://canary.discord.com/channels/613425648685547541/979027703355285554/979076371160649759)

**Comment by quinchs** [comment]
seems to be resolved

**Comment by ooliver1** [comment]
it was resolved, this issue does not target that

this issue targets a future prevention on ~~if~~ when this happens another time

a good and future-proof fix would be to use `/gateway/bot` for the reason said in the issue body

**Comment by Misha-133** [comment]
*Kind of a late update... Hey from 2023*
The library uses `/gateway/bot`, so i'm closing this.
