### ISSUE TITLE
How to access to services when a listener is activated?

### ISSUE THREAD

**Issue by mquillot** [RogueException/Discord.Net#2340]
Hello ! 

I am playing with interactions. I have a module class that receives services when the constructor is called, including one instance of my database class. I coded it by following the documentation, with entity framework and postgresql.

When I use slash commands, everything is working fine. But I also want to check if a button is executed and then to realize an action demanding to access to the database. It also works, but I have an Exception : **System.ObjectDisposedException** with the following message : 
```
Cannot access a disposed context instance. A common cause of this error is disposing a context instance that was resolved from dependency injection and then later trying to use the same context instance elsewhere in your application. This may occur if you are calling 'Dispose' on the context instance, or wrapping it in a using statement. If you are using dependency injection, you should let the dependency injection container take care of disposing context instances.
Object name: 'ApplicationDbContext'.
```

Everything is working anyway but I would like to avoid this kind of error message. I suppose that it can lead to side effects.

Does anyone know how to fix this problem?
I think the question should be: how to correctly get access to the context services in the called method event? 
Here you have the code of my module.

```c#
    public class MyCommands : InteractionModuleBase<SocketInteractionContext>
    {
        public InteractionService Commands { get; set; }

        private CommandHandler _handler;
        private readonly ApplicationDbContext _db;
        private readonly DiscordSocketClient _discord;

        // constructor injection is also a valid way to access the dependecies
        public MyCommands(DiscordSocketClient discord, CommandHandler handler, ApplicationDbContext db)
        {
            _handler = handler;
            _db = db;
            _discord = discord;

            
            _discord.ButtonExecuted += (arg) => this.ButtonHandler(arg);
        }

        public async Task ButtonHandler(SocketMessageComponent component)
        {
            // Access to database somewhere
            // And also edit some private messages of the bot or send private message to a user
            // When it is activated, I ged the System.ObjectDisposedException
        }
            
        /*
            Other slash commands of interaction.
            Here, I do not have the problem when a access to database.
        */
    }
```

Thank you for all the work you do! It is so amazing! :D

**Comment by csmir** [comment]
Because of the nature of command modules, this example will never reach the invocation of `ButtonHandler` with populated context. A module is `Transient`, meaning its only ever created at command execution, and disposed right after. With this logic in mind, subscribing to the `ButtonExecuted` event will leave it to run from nothing, as there is no context available post-disposal. 

You could instead opt to change out your button handler to a `ComponentInteractionAttribute` marked method, just like with slash commands and the likes. An example of how this would look is found [here](https://github.com/discord-net/Discord.Net/blob/dev/samples/InteractionFramework/Modules/ExampleModule.cs#L54).

**Comment by mquillot** [comment]
Thank you very much!

It helped me a lot. 

I would like to add that if you want to get the `SocketMessageComponent` (parameter named "component" in my previous example), you can use this example : 

```c#
[ComponentInteraction("interaction")]
public async Task InteractionButtonHandler()
{
    SocketMessageComponent component = (SocketMessageComponent)this.Context.Interaction;
}
```
It took me a long time to find it 😂 

It is useful when you want to get the CustomId for example:
```c#
component.Data.CustomId
```
