### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Archi97** [RogueException/Discord.Net#2349]
### Check The Docs

- [X] I double checked the docs and couldn't find any useful information.

### Verify Issue Source

- [X] I verified the issue was caused by Discord.Net.

### Check your intents

- [X] I double checked that I have the required intents.

### Description

This part of the code only prints the users that are in voice chat right now.
How to get all users list. ALL - online, offline, bots, etc.????
if (arg.Id.ToString() == GuildID)
            {
                foreach (var item in _client.GetGuild(arg.Id).Users)
                {
                    Console.WriteLine(item.DisplayName);
                }
            }

Also, the user statuses are incorrect as well..
And YES, im downloading user data always
### Version

3.7.2

### Logs

No error

### Packages

non

**Comment by SylveonDeko** [comment]
first off update your discord.net

**Comment by Archi97** [comment]
@Sylveon76  MissInformation, Im using 3.7.2 version

**Comment by Archi97** [comment]
@Sylveon76  what next?

**Comment by csmir** [comment]
Do you have the guildmembers intent enabled in code

**Comment by Archi97** [comment]
> Do you have the guildmembers intent enabled in code

it ask for redirect URL, + it is not included in your docs(tutorial)
i have added it, but still not working

**Comment by SylveonDeko** [comment]
No it doesn't where are you looking, you need to specify both the presence intent in your socketconfig and enable server members intent on your bot dashboard

**Comment by Archi97** [comment]
> 

Ok.  I had Server Members intent enabled in Bot dashboard.
Didn't understand the part with socketconfig.   Alwaysdownload user is enabled.

**Comment by Archi97** [comment]
Worked by using 
cfg.GatewayIntents = GatewayIntents.Guilds | GatewayIntents.GuildPresences;
