### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by NiTiSon** [RogueException/Discord.Net#2351]
### Check The Docs

- [x] I double checked the docs and couldn't find any useful information.

### Verify Issue Source

- [X] I verified the issue was caused by Discord.Net.

### Check your intents

- [X] I double checked that I have the required intents.

### Description

I registered a basic interaction command successfully, but he doesn't work

When i use 
```cs
interactionService.ExecuteCommandAsync(context, provider);
```
Its returning `Succsess`, but command code doesn't called

Yes i got event when command is send, but `ExecuteCommandAsync` doesn't run it (but returned Success)

### Version

3.7.2

### Logs

Bug at runtime

### Packages

Discord.Net.Interaction 3.7.2

**Comment by exsersewo** [comment]
Intentional behaviour according to [Post-Execution Logic](https://discordnet.dev/guides/int_framework/post-execution.html). As default run mode is `RunMode.Async`. The behaviour in ExecuteCommandAsync is to return an immediate success as you're meant to use the CommandExecuted event on the InteractionService to handle ost-Execution Logic in that mode.

**Comment by NiTiSon** [comment]
Okay, but why command not executed?

**Comment by exsersewo** [comment]
Listen to the CommandExecuted event and find the reason from the `IResult` parameter

**Comment by NiTiSon** [comment]
Command doesnt executed, and event `SlashCommandExecuted` also

**Comment by csmir** [comment]
Could you show us the module code? Also, where are you registering your modules?

**Comment by NiTiSon** [comment]
```cs
public class HelpModule : InteractionModuleBase<SocketInteractionContext>
{
	[SlashCommand("bitrate", "Gets the bitrate of a specific voice channel.")]
	public async Task GetBitrateAsync([ChannelTypes(ChannelType.Voice, ChannelType.Stage)] IChannel channel)
	{
		await RespondAsync(text: $"This voice channel has a bitrate of {(channel as IVoiceChannel)?.Bitrate ?? -1}");
	}
	[SlashCommand("abc", "lm")]
	public async Task Abc()
	{
		await RespondAsync(text: "OMG");
	}
}
```
![Response](https://user-images.githubusercontent.com/60577131/173559145-b276fdd2-75fa-4cd9-93f4-d90d37cf6fb8.png)

<br/>

![CommandMenu](https://user-images.githubusercontent.com/60577131/173559243-f740e6a9-48d6-40a2-8651-261312de8abe.png)

**Comment by NiTiSon** [comment]
Okay, i known why it's doesnt working

Discord.Net has no support any ServiceProvider except Microsoft ServiceProvider
