### ISSUE TITLE
Sample project ShardedClient

### ISSUE THREAD

**Issue by Crystal1462** [RogueException/Discord.Net#2357]
I am new with this and not sure if the samples are just a forgotten entity and no one checks to see if they work or not.  I simply opened it, only made changes to the bot token and guild token and I get this issue:

System.InvalidOperationException: 'Provided client is not ready to execute this operation, invoke this operation after a `Client Ready` event'

        static void Main(string[] args)
            => new Program()
                .MainAsync()
                .GetAwaiter()
                .GetResult();

I figured best place to learn would be the Samples, if this was an error on my part let me know.  

Thanks

**Comment by csmir** [comment]
The method you're trying to call is most likely something along the lines of `AddCommandsX` from the interaction service. This is not supported pre-`_client.Ready`, and you will have to process this event in order to succesfully handle the method call you're trying to make.

```cs
// x = the underlying DiscordSocketClient for the shard that is ready at invoke. 
// At multiple shards, multiple ready's will be invoked.
_client.Ready += (x) => {
  ...
}

await _client.LoginAsync();
await _client.StartAsync();
```
