### ISSUE TITLE
Should we isolate system messages?

### ISSUE THREAD

**Issue by RogueException** [RogueException/Discord.Net#236]
All messages with a type of non-zero should not be processed as if they were user messages. Is this enough to a warrant a new function like `DiscordSocketClient.SystemMessageReceived`, or should we keep it unified in one place?

**Comment by khionu** [comment]
At the moment, usage is limited, but I think it's clear that it won't stay that way. I'm for moving isolating

**Comment by FiniteReality** [comment]
I think separating the events would make sense. After all, most developers who are looking to create a bot won't be interested in the other message types.

**Comment by khionu** [comment]
Ehhh, that's debateable. But SystemMessages aren't what people are expecting in MessageReceived, I think

**Comment by Joe4evr** [comment]
And the 1-2% of devs that do want to hook into system messages should be knowledgeable enough to find the new event by themselves.
