### ISSUE TITLE
[REQ] how can i get  custom name on a server ?

### ISSUE THREAD

**Issue by ChristopheTdn** [RogueException/Discord.Net#2363]
I try :
```
DiscordSocketConfig config = new DiscordSocketConfig { AlwaysDownloadUsers = true };
 _client = new DiscordSocketClient(config);

string name =  _client.GetUserAsync(id).Result.Username.ToString();
```
This only return user 's GENERAL PROFIL NAME. How can i get custom server profil Name ( nickname ?) 
Thx for your help

**Comment by SylveonDeko** [comment]
First off never ever use .Result, second off you need to use guild.GetUserAsync and use .Nickname from that

**Comment by ChristopheTdn** [comment]
Thx for your quick rponse. When i try guild.GetUserAsync, it tell me : DiscordSocketClient don t have 'guild definition' . And why .Result is a bad idea ? how can i catch username in other way ?

**Comment by SylveonDeko** [comment]
You need to either do _client.GetGuild or if you're in a module use Context.Guild, also .Result ruins the point of async

**Comment by ChristopheTdn** [comment]
As you can see, i m not very familiar with async.  Thx for your explanation.
I don t understand about the getGuild usage. Do you have a sample somewhere to implement this _client.GetGuild ?
Thx for your patience

**Comment by pedrofcj** [comment]
The GetGuild will retrieve a SocketGuild object where you can interact with it.
For example, to get a specific Nickname, you can user something like this: _client.GetGuild(guildId).GetUser(userId).Nickname;

In this example, you are retrieving an user by its Id, using the Guild context, where you have the user nickname, roles, guild picture, etc

**Comment by ChristopheTdn** [comment]
Thank you very much !!!
 I give it a try and come back very quickly !!!

**Comment by ChristopheTdn** [comment]
finally it works !!! 

```
                DiscordSocketConfig config = new DiscordSocketConfig
                {
                    GatewayIntents = GatewayIntents.All | GatewayIntents.GuildMembers,
                    AlwaysDownloadUsers = true
                };
                _client = new DiscordSocketClient(config);
                // Subscribing to client events, so that we may receive them whenever they're invoked.
                _client.Ready += ReadyAsync;
```

              
[....] and finally
       
```
var nick = _client.GetGuild(xxxxxxguildIDxxxxxxx).GetUser(xxxxxuserIDxxxxx).Nickname;
```
      
thanks for your help !!!
