### ISSUE TITLE
[Bug]: IVoiceChannel is missing DeleteMessagesAsync

### ISSUE THREAD

**Issue by ghost** [RogueException/Discord.Net#2365]
### Check The Docs

- [X] I double checked the docs and couldn't find any useful information.

### Verify Issue Source

- [X] I verified the issue was caused by Discord.Net.

### Check your intents

- [X] I double checked that I have the required intents.

### Description

DeleteMessagesAsync is in ITextChannel, but now that voice channels are text channels too, they are missing this method (assuming it's supported).

The issue probably can not be solved by moving DeleteMessagesAsync to IMessageChannel because DM channels apparently don't have that capability.

Creating an interface from which both IVoiceChannel and ITextChannel inherit would be probably ideal, as it would solve this issue and act as a drop-in replacement for ITextChannel without the need for code refactors. (Or hijacking ITextChannel and creating new interface for actual guild text channels)

### Version

3.7.2

### Logs

-

### Packages

-

**Comment by SylveonDeko** [comment]
I'll try and make a PR for this tomorrow (and actually contribute to dnet for once)

**Comment by SylveonDeko** [comment]
#2367 

PR is open, apparently the implementation existed but the method under the interface didn't.
