### ISSUE TITLE
[Question] Deleting/Removing Interaction Commands

### ISSUE THREAD

**Issue by ArcadeArchie** [RogueException/Discord.Net#2383]
Is there currently a way to delete/remove old/defunct slash commands so they dont show up in discord?

I know the API has the URLs to do it but manually pinging the API to delete the commands isnt really a good long term solution for me.

**Comment by csmir** [comment]
You can fetch all your active commands through the `DiscordXClient`. Depending on your implementation, you will have to find the overload in the Rest client (`GetXApplicationCommandsAsync`). When having fetched all commands, you can iterate through the result and manually skip, delete or modify them with available exposed methods.

**Comment by ArcadeArchie** [comment]
Ok thanks
