### ISSUE TITLE
[Bug]: There doesn't seem to be a way to get a user's top role?

### ISSUE THREAD

**Issue by froghood** [RogueException/Discord.Net#2396]
### Check The Docs

- [X] I double checked the docs and couldn't find any useful information.

### Verify Issue Source

- [X] I verified the issue was caused by Discord.Net.

### Check your intents

- [X] I double checked that I have the required intents.

### Description

the ordering of SocketGuildUser.Roles doesnt seem to match with what would show on the actual discord client. I tried doing something like `user.Roles.Last()` as suggested for a discord.py question but that doesn't seem to return the top role. discord.py also seems to have a "top_role" attribute for their member object but it appears like discord.net doesn't have this functionality. maybe I'm missing something here?

### Version

3.7.2

### Logs

~

### Packages

~

**Comment by thatmaxplayle** [comment]
I would argue that this isn't a bug - unless you're referring exclusively to the fact the ordering in the Roles collection isn't correct... otherwise, it's more a feature suggestion.

**Comment by Sasino97** [comment]
This works for me (snippet from my bot):
```csharp

            // Check role hierarchy
            var sourceRole = source.Roles.OrderByDescending(r => r.Position).FirstOrDefault();
            var userRole = user.Roles.OrderByDescending(r => r.Position).FirstOrDefault();

            if (sourceRole.Position <= userRole.Position)
            {
                await command.RespondWithEmbedAsync($"You can't ban {user.Mention} because their highest role ({userRole.Mention}) is higher than yours ({sourceRole.Mention}).");
                return;
            }
```

**Comment by BobVul** [comment]
If you just need their relative position, `IGuildUser` provides a `Hierarchy` property, also accounting for the server owner. However, that is a computed property and only returns the position, so it's not efficient if you wanted to fetch the actual role object (e.g. to get the name).

If you need the actual role objects, what @SaSiNO97 provided is probably the only way. But consider replacing the sorts with `MaxBy` (.NET 6).

**Comment by froghood** [comment]
damn i feel silly for not noticing the position property, but it seems to work perfectly. thanks for the help guys!
