### ISSUE TITLE
[Bug]: Unused GuildPresences intent warning shouldn't show

### ISSUE THREAD

**Issue by MAttila42** [RogueException/Discord.Net#2397]
### Check The Docs

- [x] I double checked the docs and couldn't find any useful information.

### Verify Issue Source

- [X] I verified the issue was caused by Discord.Net.

### Check your intents

- [X] I double checked that I have the required intents.

### Description

In order to use the `Guild.GetUser()` method I need the GuildPresences intent. However if I set my config to include it I get the warning:
```
You're using the GuildPresences intent without listening to the PresenceUpdate event, consider removing the intent from your config.
```
Without the intent I won't get any result from the method.

### Version

3.7.2

### Logs

![image](https://user-images.githubusercontent.com/65223119/180601821-0f65c73a-31d9-44fc-8acc-3e989b2efefe.png)

### Sample

```cs
// when initializing the bot
this._client = new DiscordSocketClient(new DiscordSocketConfig
{
    GatewayIntents = GatewayIntents.GuildPresences
});

// using the Interaction framework
await Context.Guild.GetUser(userId).AddRoleAsync(roleId);
```

### Packages

--

**Comment by MichailiK** [comment]
Getting users requires the Guild Members intent, not Guild Presences. Presences are for online status and playing/listening to/custom status.

**Comment by MAttila42** [comment]
> Getting users requires the Guild Members intent, not Guild Presences. Presences are for online status and playing/listening to/custom status.

Only using GuildMembers intent doesn't work. Only using GuildPresences intent works. How's that? I even removed the GuildMembers intent from the developer portal

**Comment by MichailiK** [comment]
The Discord API will not send you all guild members by default. You need to make Discord.Net request members by using [`SocketGuild.DownloadUsersAsync`](https://discordnet.dev/api/Discord.WebSocket.SocketGuild.html#Discord_WebSocket_SocketGuild_DownloadUsersAsync) or by setting [`AlwaysDownloadUsers`](https://discordnet.dev/api/Discord.WebSocket.DiscordSocketConfig.html#Discord_WebSocket_DiscordSocketConfig_AlwaysDownloadUsers) to true in your socket config.

**Comment by Misha-133** [comment]
> You need to make Discord.Net request members

And to do that you need both `Guilds` and `GuildMembers` intents

**Comment by MAttila42** [comment]
I see. I managed to make it work like how you showed. Well I had a strange case where I only needed the GuildPresences.

**Comment by MichailiK** [comment]
> Well I had a strange case where I only needed the GuildPresences.

That's likely because the Discord API has sent you some online members. Discord won't do that when you only have the Guild Members intent.
