### ISSUE TITLE
C# Bot does not come online after login and start

### ISSUE THREAD

**Issue by w00ter007** [RogueException/Discord.Net#2399]
My C# program was working fine until a while ago (it stopped working without changing code, I think it was a few weeks ago)
I only get this output:

Discord.Net v3.7.2 (API v9)
Connecting
Connecting ApiClient
GET gateway: 288.9 ms

Nothing else happens, no errors or other info that I can find to solve this.
The Connected function does not fire and neither does Disconnected.
The bot does not show up online in Discord.
The project is a Console Application with Target framework .NET Framework 4.6.1.
The token is correct, as I made sure by resetting the token and copying the new one.

Part of the code in Program.cs:

        static void Main(string[] args) => new Program().StartAsync().GetAwaiter().GetResult();

        public async Task StartAsync()
        {
            if (string.IsNullOrEmpty(CommandHandler.Token)) return;
            Directory.SetCurrentDirectory(AppDomain.CurrentDomain.BaseDirectory);
            _client = new DiscordSocketClient(new DiscordSocketConfig
            {
                LogLevel = LogSeverity.Debug,
                WebSocketProvider = WS4NetProvider.Instance
            });
            _client.Log += Log;
            _client.Connected += Connected;
            _client.Disconnected += Disconnected;
            await _client.LoginAsync(TokenType.Bot, CommandHandler.Token);
            await _client.StartAsync();
            _handler = new CommandHandler();
            await _handler.InitializeAsync(_client);
            await Task.Delay(-1);
        }

**Comment by Misha-133** [comment]
You might need to bump .NET Framework version to 4.8 because DiscordAPI only supports TLS >1.2 now

**Comment by csmir** [comment]
Is this resolved? Please follow up.

**Comment by Veggie13** [comment]
I'm not the OP but I'm having the exact same issue. Didn't change my code or upgrade my client version, didn't change my permissions or integrations on Discord. A week or two ago the bot was able to connect to the voice channel fine, now ConnectAsync() times out. My setup is on .NET 5.0. I don't know anything about TLS so I'm not sure how to verify if that's the issue.

**Comment by Veggie13** [comment]
> I'm not the OP but I'm having the exact same issue. Didn't change my code or upgrade my client version, didn't change my permissions or integrations on Discord. A week or two ago the bot was able to connect to the voice channel fine, now ConnectAsync() times out. My setup is on .NET 5.0. I don't know anything about TLS so I'm not sure how to verify if that's the issue.

I was able to solve the issue. I don't know if it's identical to OP's issue, but this solved it for me: https://stackoverflow.com/questions/63959263/how-to-fix-a-messagereceived-handler-is-blocking-the-gateway-task-in-discordb

Basically, the MessageReceived handler could not be async because it never seemed to return control to the client. By handling it in a Task and immediately returning Completed from the handler, the issue was resolved. It might be possible to allow MessageReceived to be async if you immediately return control using await Task.Yield() but I haven't tried it.

**Comment by csmir** [comment]
Glad you were able to resolve the issue, it appears your handler was indeed blocking the gateway task. This is not related to the issue of OP though. The OP is having trouble because of TLS version support in net framework. This issue does not exist in net5. 

Closing by lack of followup by OP.

**Comment by XxQuickSilverZz** [comment]
SAME PROBLEM
@csmir 
@w00ter007 you solved this?
