### ISSUE TITLE
[Feature Missing] Seems as if that the manage_permissions are missing in the OverwritePermissions

### ISSUE THREAD

**Issue by killerfrienddk** [RogueException/Discord.Net#2402]
### Check The Docs

- [X] I double checked the docs and couldn't find any useful information.

### Verify Issue Source

- [X] I verified the issue was caused by Discord.Net.

### Check your intents

- [X] I double checked that I have the required intents.

### Description

Seems as if that the managePermissions are missing in the OverwritePermissions.

![image](https://user-images.githubusercontent.com/5002439/182034114-8ed7796e-9188-4ebc-a0d1-311f1f886b27.png)

@Rozen4334 There you go.

### Version

3.7.2

### Logs

None

### Packages

None

**Comment by MichailiK** [comment]
its manageRoles.
