### ISSUE TITLE
[Bug]: RestSlashCommand CommandName property results in NullReferenceException

### ISSUE THREAD

**Issue by AlcyrNymyn** [RogueException/Discord.Net#2413]
### Check The Docs

- [X] I double checked the docs and couldn't find any useful information.

### Verify Issue Source

- [X] I verified the issue was caused by Discord.Net.

### Check your intents

- [X] I double checked that I have the required intents.

### Description

This happens because the Data property on the derived class is set with the `new` modifier. This only hides the base class instead of overriding it, so when the CommandName and CommandId properties try to access it on the base class, it uses the base class' implementation of Data which is still null. Either RestCommandBase should be rewritten with actual inheritance for the Data property, or these getters should not be available on the base command to avoid confusion.

This would also apply to RestMessageCommand and RestUserCommand, I assume.

This does have an easy workaround of just using Data.Name/Data.Id instead, but providing a shortcut that doesn't work is awfully inconvenient.

### Version

3.7.2

### Logs

System.NullReferenceException: Object reference not set to an instance of an object.
at Discord.Rest.RestCommandBase.get_CommandName()

### Sample

```cs
var interaction = Client.ParseHttpInteractionAsync(PublicKey, signature, timestamp, body).Result;
var name = (interaction as RestSlashCommand).CommandName; // throws
```

### Packages

none but this field is required

**Comment by csmir** [comment]
Expect it to be resolved in the next release
