### ISSUE TITLE
[Bug]: GetActiveThreadsAsync() from IForumChannel returns all active threads across the server instead of those under the forum channel

### ISSUE THREAD

**Issue by reckhou** [RogueException/Discord.Net#2427]
### Check The Docs

- [x] I double checked the docs and couldn't find any useful information.

### Verify Issue Source

- [X] I verified the issue was caused by Discord.Net.

### Check your intents

- [X] I double checked that I have the required intents.

### Description

Not sure if it's only me, but seems `GetActiveThreadsAsync()` from `IForumChannel` returns all active threads across the whole server instead of the active threads under the forum channel.

Other APIs like `GetPublicArchivedThreadsAsync()` are also having the same issue.

### Version

3.7.2

### Logs

Result:

![image](https://user-images.githubusercontent.com/1331053/184269284-69d08060-d052-40d9-b9f9-a0abf2171b36.png)

It returns all active posts on the server(only those test threads should be returned)

### Sample

```
public async Task UpdateIndexAsync(ulong forumID)
        {
            IForumChannel forumChannel = _discord.GetChannel(forumID) as IForumChannel;
            if (forumChannel == null)
            {
                return;
            }
            string content = "";
            var threads = await forumChannel.GetActiveThreadsAsync();
            var threadList = new List<IThreadChannel>(threads);
            foreach (var thread in threadList)
            {
                content += $"**{thread.Name}**\n\n{thread.Id}";
            }
            Console.WriteLine(content);
}
```

### Packages

MediatR v10.0.1
Microsoft.Extensions.DependencyInjection v6.0.0

**Comment by SimplyJpk** [comment]
+1, ran into same behaviour.

It appears the ThreadHelper only returns all active threads, which is calling the api `$"guilds/{guildId}/threads/active"` I did have quick look at the API and found nothing for only getting the active threads on a forum. (At least not yet)

DiscordNet current documentation says it returns active threads in forum which may confuse people.
