### ISSUE TITLE
How should we implement configurable TypeReaders?

### ISSUE THREAD

**Issue by RogueException** [RogueException/Discord.Net#243]
(Continuing discussion from https://github.com/RogueException/Discord.Net/issues/229)

With https://github.com/RogueException/Discord.Net/issues/242, we'll be able to implement typereaders at the module or command level, so configuring a `TypeReader` isn't as dangerous. The issue atm is how we want to expose configuration at the attribute (per-parameter) level.

Json.Net handles this by accepting a list of parameters in the JsonConverter attribute to feed to a converter with zero intellisense or type safety. 

The alternative is making several type readers: `CachedMessageTypeReader` and `MessageTypeReader`, for example, for different configurations.

Thoughts?

**Comment by khionu** [comment]
I suggest the attributes be applicable to Commands and Groups/Modules, as well. Chances are if you want to apply it to one parameter, you'll want to apply it to any similar parameters in the context, as well.

**Comment by Auralytical** [comment]
Solved by TypeReader overrides
