### ISSUE TITLE
will someone PLEASE tell me how to check if a user has a certain role

### ISSUE THREAD

**Issue by barry-mcockiner** [RogueException/Discord.Net#2433]
i have read every single article on every single google page and no solution works. for the love of god please help me i have destroyed my second monitor because i have been trying to do this shit for 7 hours

**Comment by SylveonDeko** [comment]
get the user in the guild then do user.RoleIds.Contains(Id), don't think you read the docs

**Comment by Almighty-Shogun** [comment]
I have this (this is just made quickly as I was to lazy to make it properly but it does work)

```cs
var user = (Context.User as SocketGuildUser)!;
var role = Context.Guild.GetRole(ROLE_ID);

if (user.Roles.Contains(role))
{
    // do your thing here
}
```
