### ISSUE TITLE
CommandException in the Interactions framework.

### ISSUE THREAD

**Issue by Misha12** [RogueException/Discord.Net#2435]
In Discord.Commands i'll get wrapped exception CommandException with Context and original Exception in the Log event. Exists something simmilar in the Discord.Interactions?

**Comment by csmir** [comment]
No, not at this point. Is it worth adding something like this? @Cenngo

**Comment by Cenngo** [comment]
I dont see why not

**Comment by ghost** [comment]
I would see great benefit from this.
