### ISSUE TITLE
[Bug]: Every Message Returns "" out of nowhere

### ISSUE THREAD

**Issue by TheFrieber** [RogueException/Discord.Net#2449]
### Check The Docs

- [X] I double checked the docs and couldn't find any useful information.

### Verify Issue Source

- [X] I verified the issue was caused by Discord.Net.

### Check your intents

- [X] I double checked that I have the required intents.

### Description

Somehow a problem that the message.Content returns out of nowhere now only: ""
About 2H before it worked problemless, now every message is a "", but the events are working fine, i was developing in the bot user role checks, and then i tought it would be my code, but i started then an stable version(The unmodified version that runs on my VPS currently) did the same fault, no reaction to my commands. Out of nowhere it stopped working, why?

### Version

2.4.0

### Working Version

2.4.0

### Logs

dbug: Microsoft.Extensions.Hosting.Internal.Host[1]
      Hosting starting
info: Discord.Addons.Hosting.DiscordHostedService[0]
      Discord.NET hosted service is starting
info: Discord.WebSocket.DiscordSocketClient[0]
      Discord: Discord.Net v2.4.0 (API v6)
dbug: Discord.WebSocket.DiscordSocketClient[0]
      Rest: GET users/@me: 748.52 ms
dbug: Discord.Addons.Hosting.CommandServiceRegistrationHost[0]
      Registered logger for CommandService
info: Discord.WebSocket.DiscordSocketClient[0]
      Gateway: Connecting
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
info: Microsoft.Hosting.Lifetime[0]
      Content root path: /home/BOT/bin/Debug/net6.0/
dbug: Microsoft.Extensions.Hosting.Internal.Host[2]
      Hosting started
dbug: Discord.WebSocket.DiscordSocketClient[0]
      Rest: GET gateway: 55.43 ms
info: Discord.WebSocket.DiscordSocketClient[0]
      Gateway: Connected
dbug: Discord.WebSocket.DiscordSocketClient[0]
      Gateway: Connected to Mom's basement
info: Discord.WebSocket.DiscordSocketClient[0]
      Gateway: Ready

No logs was created, because no commands could get executed by this issue.

### Sample

```cs
private async Task OnMessageReceived(SocketMessage sm)
        {
            if (!(sm is SocketUserMessage message)) return;
            if (message.Source != MessageSource.User) return;

            var context = new SocketCommandContext(_client, message);

            if (message.Content.Contains("ping", StringComparison.CurrentCultureIgnoreCase)) //Breakpoint catches here, and returns, and how i told, this code wasn't touched and the VPS code didn't even get an update, still every message returns only: ""
            {
                var sendmessage = $"pong {sm.Author.Mention}!";
                await context.Channel.SendMessageAsync(sendmessage);
                return;
            }
        }
```

### Packages

Discord.Addons.Hosting 4.0.2

**Comment by csmir** [comment]
Privileged message intents have been pushed through. You will have to wait for the upcoming patch to fix this issue.

**Comment by TheFrieber** [comment]
Is it a me issue, d.net or discord?

> Privileged message intents have been pushed through. You will have to wait for the upcoming patch to fix this issue.

**Comment by csmir** [comment]
Discord, it suprises me you have not been informed about this yet, it's been announced almost a year ago

**Comment by TheFrieber** [comment]
> Discord, it suprises me you have not been informed about this yet, it's been announced almost a year ago

Could you tell me more about this, what it is?, I am new to coding those bots, so i don't even know how the api works ._.
Do i just need to wait and it fixes itself, or do i need to update something from client side?

**Comment by MrCakeSlayer** [comment]
Some articles from Discord explain it:
https://support-dev.discord.com/hc/en-us/articles/8561391080471
https://support-dev.discord.com/hc/en-us/articles/5324827539479
https://discord.com/developers/docs/topics/gateway#message-content-intent

**Comment by TheFrieber** [comment]
Fixed my issue by re-enabling "MESSAGE CONTENT INTENT" on the developers portal,
