### ISSUE TITLE
Are 'select menu's supported with modals?

### ISSUE THREAD

**Issue by essoperagma** [RogueException/Discord.Net#2455]
I'm trying to display a [select menu](https://discord.com/developers/docs/interactions/message-components#component-object-component-types) as a response to a slash command. But getting an exception that says "only text input components are allowed.". Is this expected?
 The data structures are there, so the exception got me confused a bit.

 Here is a snippet:
```csharp
await command.RespondWithModalAsync(
        new ModalBuilder("Bot Settings", "settings",
        new ModalComponentBuilder()
            {
                ActionRows = new List<ActionRowBuilder>()
                {
                    new ActionRowBuilder()
                        .WithSelectMenu( new SelectMenuBuilder()
                            .WithCustomId("alerts")
                            .WithOptions(new List<SelectMenuOptionBuilder>()
                            {
                                new SelectMenuOptionBuilder("Minimal","minimal","Minimum alert level."),
                                new SelectMenuOptionBuilder("Balanced","balanced","Balanced alert level."),
                                new SelectMenuOptionBuilder("Verbose","verbose","Verbose alert level."),
                            }))
                            ,
                }
            })
            .AddTextInput("Time format", "time_format")
            .Build());
```

Exception is thrown here: https://github.com/discord-net/Discord.Net/blob/dev/src/Discord.Net.Core/Entities/Interactions/Modals/ModalBuilder.cs#L124-L125

**Comment by KubaZ2** [comment]
Only text input components are supported with modals by Discord for now.

**Comment by essoperagma** [comment]
Looking at the official docs, it seems like it is supported by "Discord", but not by "Discord.Net". Is that accurate?

I wonder how far away we are from getting it done. If contributions are accepted, I could perhaps give it a try.

**Comment by KubaZ2** [comment]
https://discord.com/developers/docs/interactions/receiving-and-responding#interaction-response-object-modal
![obraz](https://user-images.githubusercontent.com/77853483/188281256-70383d0d-a82a-4c21-80d2-814a5a6dfb9c.png)

**Comment by essoperagma** [comment]
Ah, that's unfortunate. Thanks for clarifying!

**Comment by MrCakeSlayer** [comment]
Just leaving this as a note, we have some users who already wrote support for them in modals for DNet, we are simply waiting on Discord to actually release the feature before merging.

**Comment by camoire** [comment]
> Just leaving this as a note, we have some users who already wrote support for them in modals for DNet, we are simply waiting on Discord to actually release the feature before merging.

It appears as though the feature has been released by the Discord team. Possible to get the supporting code merged now?
- https://discord.com/developers/docs/components/reference#component-object

**Comment by MrCakeSlayer** [comment]
The current version of modal components that Discord released is actually significantly different than the original hacky implementation they had. however, a pending PR does exist for this currently which you can follow here: https://github.com/discord-net/Discord.Net/pull/3172

It will be released once it is stable and ready.

**Comment by camoire** [comment]
Looks like a lot of good things in there :)
