### ISSUE TITLE
[Bug]: Using DiscordShardedClient causes gateway intent warnings to be logged when it has no subscribers

### ISSUE THREAD

**Issue by GageAmes** [RogueException/Discord.Net#2461]
### Check The Docs

- [X] I double checked the docs and couldn't find any useful information.

### Verify Issue Source

- [X] I verified the issue was caused by Discord.Net.

### Check your intents

- [X] I double checked that I have the required intents.

### Description

Using the `DiscordShardedClient` without subscribing to any Discord events causes warnings to be logged about not specifying the required intents. For example:

> You're using the PresenceUpdate event without specifying the GuildPresences intent. Discord wont send this event to your client without the intent set in your config.

This appears to be happening because the `DiscordShardedClient` subscribes to all of the events on the underlying `DiscordSocketClient` for each shard so it can pass on the events to the `DiscordShardedClient`, even if the `DiscordShardedClient` itself is not subscribed to those events.

https://github.com/discord-net/Discord.Net/blob/d1678d1e8f607a0852e496d1db3ee509c279efbb/src/Discord.Net.WebSocket/DiscordShardedClient.cs#L452

When the underlying `DiscordShardedClient`(s) call [`LogGatewayIntentsWarning()`](https://github.com/discord-net/Discord.Net/blob/d1678d1e8f607a0852e496d1db3ee509c279efbb/src/Discord.Net.WebSocket/DiscordSocketClient.cs#L744), they detect the subscriptions that were automatically added by the `DiscordShardedClient` and log the warning message despite the `DiscordShardedClient` not actually using the events.

See the code sample below for a minimal example that causes the warnings to be logged without the user of the `DiscordShardedClient` explicitly subscribing to any events (other than the `Log` event).

### Version

3.8.0

### Logs

```
Discord.Net v3.8.0 (API v9)
Connecting
You're using the PresenceUpdate event without specifying the GuildPresences intent. Discord wont send this event to your client without the intent set in your config.
You're using events related to the GuildScheduledEvents gateway intent without specifying the intent. Discord wont send this event to your client without the intent set in your config.
You're using events related to the GuildInvites gateway intent without specifying the intent. Discord wont send this event to your client without the intent set in your config.
Connected
Ready
```

### Sample

```cs
using Discord;
using Discord.WebSocket;
using System;
using System.Threading;
using System.Threading.Tasks;

var client = new DiscordShardedClient(new DiscordSocketConfig
{
    GatewayIntents = GatewayIntents.None
});

client.Log += logMessage => Console.Out.WriteLineAsync(logMessage.Message);

await client.LoginAsync(TokenType.Bot, "<token redacted>");
await client.StartAsync();

// Observe console output for warnings about subscribing the events without the proper intents despite the fact that no events are being subscribed to by the DiscordShardedClient

await Task.Delay(Timeout.InfiniteTimeSpan);
```

### Packages

N/A

**Comment by Misha-133** [comment]
Issue should be solved in the latest release.

Please check if everything works correctly and close the issue

**Comment by GageAmes** [comment]
Yes, release version 3.8.1 fixes this issue. Thank you, @Misha-133!
