### ISSUE TITLE
[Bug]: Discord.NET does not send name translations (NameLocalizations) for ChoiceAttribute

### ISSUE THREAD

**Issue by Misha12** [RogueException/Discord.Net#2466]
### Check The Docs

- [x] I double checked the docs and couldn't find any useful information.

### Verify Issue Source

- [X] I verified the issue was caused by Discord.Net.

### Check your intents

- [X] I double checked that I have the required intents.

### Description

I updated to Discord.NET 3.8.1 and started implementation of localization via JsonLocalizationManager. Everything is fine except the localization of the ChoiceAttribute. After investigating, I found that the library does not setting the NameLocalization property in the ApplicationCommandOptionChoice class when registering commands (`RegisterCommandsToGuildAsync`).

I verified that indeed discord does not know about the localization of the choices even if I have it set in the JSON file.

Discord's response to the GetGuildApplicationCommands request
![image](https://user-images.githubusercontent.com/9041462/190243479-0f140239-c427-4d33-b93c-3ecfffdf8cfc.png)

My JSON with localization
![image](https://user-images.githubusercontent.com/9041462/190243578-1ac75f38-8fd1-42b5-9217-01ae5a9c6e13.png)

### Version

3.8.1

### Logs

This problem does not produce any logs to help explain the problem. Everything is described in the description.

### Packages

Discord.NET 3.8.1
Magick.NET-Q8-AnyCPU 11.2.1
MailKit 3.3.0
Npgsql.EntityFrameworkCore.PostgreSQL 6.0.5
Humanizer.Core 2.14.1
Unicode.net 2.0.0
Markdig 0.30.3

**Comment by csmir** [comment]
What is the state on this @Cenngo ?
