### ISSUE TITLE
Message content and clean content is always empty: 

### ISSUE THREAD

**Issue by ivo-lubans** [RogueException/Discord.Net#2470]
### Check The Docs

- [ ] I double checked the docs and couldn't find any useful information.

### Verify Issue Source

- [ ] I verified the issue was caused by Discord.Net.

### Check your intents

- [ ] I double checked that I have the required intents.

### Description

Message that I sent to my bot replaces on fully empty one. I tried many option to fix this, but this all didn't work. Discord message: 
![image](https://user-images.githubusercontent.com/63658345/190699943-3de9d37b-8230-4994-bf36-f4c21a94f9f9.png)
and code: 
![image](https://user-images.githubusercontent.com/63658345/190700227-4e202a7c-919d-4268-aa09-e88f4fc2af0a.png). I have no idea how to fix this.

### Version

3.8.1

### Logs

--

### Sample

private async Task HandleCommandAsync(SocketMessage arg)
        {
            var message = arg as SocketUserMessage;
            var context = new SocketCommandContext(_client, message);

            if (!message.Author.IsBot)
            {
                int argPos = 0;
                if (message.HasStringPrefix("!", ref argPos))
                {
                    var result = await _commands.ExecuteAsync(context, argPos, _services);
                    if (!result.IsSuccess) Console.WriteLine(result.ErrorReason);
                }
            }
        }

### Packages

Discord; Discord.Commands; Discord.WebSocket; Microsoft.Extensions.DependencyInjection; System.Reflection

**Comment by Misha-133** [comment]
Most likely you didn't enable `MessageContent` intent in both your `DiscordSocketConfig` and Dev Portal

**Comment by ivo-lubans** [comment]
I think that it's on... 
![image](https://user-images.githubusercontent.com/63658345/190700919-e5a626ae-30c4-446b-ac58-b1e719ae5b71.png)

**Comment by Misha-133** [comment]
Did you add one to the `DiscordSocketConfig` tho?
It should look like 
```cs
new DiscordSocketConfig { GatewayIntents = GatewayIntents.AllUnpriviliged | GatewayIntents.MessageContent }
```

**Comment by ivo-lubans** [comment]
No, I will try to do this. Thank you!

**Comment by ivo-lubans** [comment]
Thank you, helped a lot! It is working now
