### ISSUE TITLE
[Bug]: HandleCommandAsync keeps repeat

### ISSUE THREAD

**Issue by rasoolfetrati** [RogueException/Discord.Net#2472]
### Check The Docs

- [X] I double checked the docs and couldn't find any useful information.

### Verify Issue Source

- [X] I verified the issue was caused by Discord.Net.

### Check your intents

- [x] I double checked that I have the required intents.

### Description

```
private async Task HandleCommandAsync(SocketMessage messageParam)
    {
        // Don't process the command if it was a system message
        var message = messageParam as SocketUserMessage;
        if (message == null) return;

        // Create a number to track where the prefix ends and the command begins
        int argPos = 0;

        // Determine if the message is a command based on the prefix and make sure no bots trigger commands
       
        await message.Channel.SendMessageAsync("bowsadasd");

        // Create a WebSocket-based command context based on the message
        var context = new SocketCommandContext(_client, message);

        // Execute the command with the command context we just
        // created, along with the service provider for precondition checks.
        await _commands.ExecuteAsync(
            context: context,
            argPos: argPos,
            services: null);
await message.Channel.SendMessageAsync("blala");
    }
```

in the above method i send message with bot but bot repeat that many times

### Version

3.8.1

### Logs

nothing

### Packages

Discord.Net 3.8.1

**Comment by akaJuliaan** [comment]
why do you use `services: null`? you have to pass your `IServiceCollection` from your main class

**Comment by rasoolfetrati** [comment]
> why do you use `services: null`? you have to pass your `IServiceCollection` from your main class

ok but that not helpful!

**Comment by Anu6is** [comment]
You send messages from within the handle command method which would cause the method to be triggered again when those messages are received. There's a comment in your code to filter out non prefixed messages and bot messages but no actual code logic to do that.
