### ISSUE TITLE
[Bug]:

### ISSUE THREAD

**Issue by daijialong** [RogueException/Discord.Net#2476]
### Check The Docs

- [X] I double checked the docs and couldn't find any useful information.

### Verify Issue Source

- [X] I verified the issue was caused by Discord.Net.

### Check your intents

- [X] I double checked that I have the required intents.

### Description

When I upgraded the SDK to 3.8.1, the content in the message disappeared. Before 3.8.0, there was no such problem. Please ask for a fix.
`MessageReceived += (message)=>message.content ` the message content is lose.

### Version

3.8.1

### Working Version

3.8.0

### Logs

![image](https://user-images.githubusercontent.com/36257973/191924477-1af10c44-2773-4f9c-81b3-d8fd74f8b442.png)

### Packages

Discord 3.8.1
Discord.Net 3.8.1
Discord.WebSocket 3.8.1

**Comment by csmir** [comment]
In DiscordSocketConfig add the MessageContent intent to GatewayIntents. If this has not been specified in the developer portal yet, there you should do so as well.

**Comment by daijialong** [comment]
> 

Yes, my settings were default before, now I follow your suggestion and it works. Thank you for your help

**Comment by daijialong** [comment]
Yes,It works.Thank your help



---Original---
From: "Armano den ***@***.***&gt;
Date: Fri, Sep 23, 2022 16:53 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [discord-net/Discord.Net] [Bug]: (Issue #2476)




 
In DiscordSocketConfig add the MessageContent intent to GatewayIntents
