### ISSUE TITLE
Hierarchy Helper?

### ISSUE THREAD

**Issue by khionu** [RogueException/Discord.Net#248]
The hierarchy is messy business, and I think a function that takes two IGuildUsers and returns true if the first is above the second would be an extremely helpful addition.

To note. according to Meew0, hierarchy is determined by Role Position (higher), and tie breakers are by Role Id (smaller).

**Comment by RogueException** [comment]
Has Discord officially doc'd this yet? I'm wary of adding this since it could just up and change again :P

**Comment by khionu** [comment]
No, and idk if they plan to. Afaicr, they didn't discuss much after they made the change, And as much as I would like it to change, they made it pretty clear that they won't

**Comment by RogueException** [comment]
This would be good to have
