### ISSUE TITLE
Converting IAttachment to Image

### ISSUE THREAD

**Issue by Hantick** [RogueException/Discord.Net#2484]
Is there any possibility to parse `IAttachment` to a `Image` type?
I want to have `IAttachment` as property in my slash command and then create a cover image from it to my event

**Comment by killerfrienddk** [comment]
@Hantick since the `IAttachment` does not contain any data regarding the actual file besides: Filename, ContentType, Description and the URL of the image you would have download it yourself using something like this:

```
  private readonly HttpClient _httpClient;

  public ImageService(HttpClient httpClient) {
       _httpClient = httpClient;
  }

  public async Task<Stream> DowloadFile(string url) {
       return await _httpClient.GetStreamAsync(url);
  }
```

It will give you the stream.

**Comment by csmir** [comment]
Closing by lack of followup
