### ISSUE TITLE
[Bug]: SlashCommandExecuted handler throws 'Interaction token is no longer valid'

### ISSUE THREAD

**Issue by michal-kapala** [RogueException/Discord.Net#2489]
### Check The Docs

- [X] I double checked the docs and couldn't find any useful information.

### Verify Issue Source

- [X] I verified the issue was caused by Discord.Net.

### Check your intents

- [X] I double checked that I have the required intents.

### Description

I'm developing a basic slash command-based bot, I've tested it on my dev environment and it still works there as expected. After I brought it onto testing environment the websocket exception is thrown everytime a slash command is received:
```
20:09:20 Gateway     A SlashCommandExecuted handler has thrown an unhandled exception.:
System.InvalidOperationException: Interaction token is no longer valid
  at Discord.WebSocket.SocketCommandBase.RespondAsync(String text, Embed[] embeds, Boolean isTTS, Boolean ephemeral, AllowedMentions allowedMentions, MessageComponent components, Embed embed, RequestOptions options)
```
Every command returns the above. I thought it could be OAuth-related but after resetting the auth token the issue still persists. I have also tried running the bot as administrator, still without a success. I have no idea why the validity of interaction tokens would depend on the bot's hosting environment.

### Version

v3.8.1 (API v10)

### Logs

20:09:10 Discord     Discord.Net v3.8.1 (API v10)
20:09:10 Gateway     Connecting
20:09:11 Gateway     You're using the GuildScheduledEvents gateway intent without listening to any events related to that intent, consider removing the intent from your config.
20:09:11 Gateway     You're using the GuildInvites gateway intent without listening to any events related to that intent, consider removing the intent from your config.
20:09:11 Gateway     Connected
20:09:13 Gateway     Ready
20:09:20 Gateway     A SlashCommandExecuted handler has thrown an unhandled exception.:
System.InvalidOperationException: Interaction token is no longer valid
   at Discord.WebSocket.SocketCommandBase.RespondAsync(String text, Embed[] embeds, Boolean isTTS, Boolean ephemeral, AllowedMentions allowedMentions, MessageComponent components, Embed embed, RequestOptions options)
   at TheBot.CommandHandler.SlashCommandHandler(SocketSlashCommand command)
   at Discord.EventExtensions.InvokeAsync[T](AsyncEvent\`1 eventHandler, T arg)
   at Discord.WebSocket.DiscordSocketClient.TimeoutWrap(String name, Func\`1 action)

### Sample

```cs
// This is TheBot.CommandHandler.SlashCommandHandler(SocketSlashCommand command)
// which you can see in the logs
private async Task SlashCommandHandler(SocketSlashCommand command)
{
	string invoker = command.User.Username;
        // The exception is thrown from any of the command.RespondAsync() calls below
	switch(command.Data.Name)
	{
		case "help":
			EmbedBuilder eb = new()
			{
				Title = "Commands",
				Description = "Available bot commands:"
			};
			// builder gets prepared
                        // ...
			await command.RespondAsync(embed: eb.Build());
			break;
		case "lobbies":
			var embeds = await LobbyService.GetLobbies(invoker);
			await command.RespondAsync(embeds: embeds);
			break;
		case "ping":
			await command.RespondAsync("pong");
			break;
		case "players":
			var embed = await PlayerService.GetPlayerCounts(invoker);
			await command.RespondAsync(embed: embed);
			break;
		default:
			break;
	}
}
```

### Packages

- Microsoft.Extensions.DependencyInjection (6.0.0)
- [dotenv.net](https://github.com/bolorundurowb/dotenv.net) (3.1.1)

**Comment by Misha-133** [comment]
Interaction token get invalidated after 3 seconds if no initial response was sent or after 15minutes after initial response
1 - try syncing your system clock with NTP server because d.net uses it to check if token is no longer valid
2 - if one of you tasks take > 3 seconds to execute you should defer the interaction **before** executing the task - `command.DeferAsync()` - and then use `FollowupAsync()` instead of `RespondAsync()`

**Comment by michal-kapala** [comment]
Thank you so much, syncing the system clock worked out for me
