### ISSUE TITLE
How to join a voicechannel by ID?

### ISSUE THREAD

**Issue by TLA020** [RogueException/Discord.Net#2491]
I can't find any method in documentation to just simply join a voice channel by id.

**Comment by killerfrienddk** [comment]
@TLA020 you have to go and get the actual channel first using either rest or from an interaction.
![image](https://user-images.githubusercontent.com/5002439/197344102-d0424b3f-13d9-4b65-b90f-1c515d99b239.png)

The channel has a method which is called `ConnectAsync`

**Comment by csmir** [comment]
Closing by lack of followup
