### ISSUE TITLE
How to login into user using username and password in 3.8.1

### ISSUE THREAD

**Issue by ItsRedly** [RogueException/Discord.Net#2496]
Could not find any info in the wiki

**Comment by killerfrienddk** [comment]
@DoorsDev, just making sure you do not want to login to a discord account, right?
Doing that would be self-botting which is against discords TOS. It is there for not allowed. Self-botting would not work with this library anyway nor should you try self-botting it will only end with getting banned.

If you want to host a bot on Discord, then you would need to login on https://discord.com/developers/applications and then get a bot token.

Here is a little tutorial on how to do it, it is a bit outdated, but it will work.
https://www.youtube.com/watch?v=gAlcexDm9LM&list=PLaqoc7lYL3ZDCDT9TcP_5hEKuWQl7zudR&ab_channel=CodingwithEfehan

If you need more help than this regarding the proper way of making a bot, then you can join https://discord.com/invite/dnet.
