### ISSUE TITLE
[Bug]: SocketMessage has no content and components for bot message

### ISSUE THREAD

**Issue by Arke123** [RogueException/Discord.Net#2499]
### Check The Docs

- [X] I double checked the docs and couldn't find any useful information.

### Verify Issue Source

- [X] I verified the issue was caused by Discord.Net.

### Check your intents

- [X] I double checked that I have the required intents.

### Description

I'm using the event MessageReceived from the DiscordSocketClient. If a message from a bot is received it's content and components are empty. For user messages everything works fine.

### Version

3.8.1

### Logs

-

### Packages

-

**Comment by killerfrienddk** [comment]
@Arke123 make sure that you have MessageContent in your GatewayIntents.
![image](https://user-images.githubusercontent.com/5002439/197533803-dc354ff5-eea0-4453-8194-d286b4b14daf.png)

**Comment by Arke123** [comment]
Thanks man, that was the issue
