### ISSUE TITLE
[Bug]: Unable to create forum post if tags are mandatory

### ISSUE THREAD

**Issue by itsHeroYT** [RogueException/Discord.Net#2503]
### Check The Docs

- [X] I double checked the docs and couldn't find any useful information.

### Verify Issue Source

- [X] I verified the issue was caused by Discord.Net.

### Check your intents

- [X] I double checked that I have the required intents.

### Description

When trying to create a post in a forum channel where tags are mandatory, it fails with the following error code:
"The server responded with error 40067: A tag is required to create a forum post in this channel"
![screenshot](https://user-images.githubusercontent.com/33837102/198027586-6fb90a2c-eedb-4429-aaff-04ee580dec35.png)

### Version

3.8.1

### Working Version

-

### Logs

-

### Sample

```cs
//get guild
var guild = client.GetGuild(1034041984710627328);
//get forum channel
var forum = guild.GetForumChannel(1034381738442498078);
//try to create a forum post while tags are mandatory
await forum.CreatePostAsync("test");
```

### Packages

None

**Comment by Misha-133** [comment]
D.Net currently does not support some of forum channel features, one of which are tags
I made a PR that brings support for these features (#2469), but still waiting for a review from Quin
