### ISSUE TITLE
[Bug]: Give Role To Discord ID

### ISSUE THREAD

**Issue by Desync3** [RogueException/Discord.Net#2506]
### Check The Docs

- [X] I double checked the docs and couldn't find any useful information.

### Verify Issue Source

- [x] I verified the issue was caused by Discord.Net.

### Check your intents

- [X] I double checked that I have the required intents.

### Description

I'm trying to give a role to a user via the guildid/serverid and with their user id but i'm getting a error.

I'm getting this issue, please help me fix it.
![image](https://user-images.githubusercontent.com/49792134/198900904-954e3c12-da1c-44b2-80a9-56ff9e04ff1f.png)

I have no idea why this isn't working and i have been trying diffrent kinds of code exampels, only seems to work when the discord server you executed the command in not on manual id.

### Version

2.8.1

### Logs

System.InvalidCastException: Unable to cast object of type 'Discord.WebSocket.SocketGlobalUser' to type 'Discord.IGuildUser'.
   at TutorialBot.Modules.Commands.<vfw>d__7.MoveNext() in

### Sample

```
await (Context.Client.GetUser(Convert.ToUInt64(clientid)) as IGuildUser).AddRoleAsync(Context.Client.GetGuild(Convert.ToUInt64(serverid)).Roles.FirstOrDefault(x => x.Name == "Verified"));
```

### Packages

Discord.Net

**Comment by Anu6is** [comment]
You are retrieving a user from the client and attempting to cast it as a guild user. You should get the user from the guild instead. 

The error message even tells you that you can't cast the global user to a guild user.

**Comment by csmir** [comment]
Closing by lack of followup
