### ISSUE TITLE
[Bug]: Incorrect command permissions after using AddCommandsToGuildAsync with deleteMissing=false

### ISSUE THREAD

**Issue by Eloncase** [RogueException/Discord.Net#2515]
### Check The Docs

- [X] I double checked the docs and couldn't find any useful information.

### Verify Issue Source

- [X] I verified the issue was caused by Discord.Net.

### Check your intents

- [X] I double checked that I have the required intents.

### Description

If you use `AddCommandsToGuildAsync` with `deleteMissing` parameter set to `false` (or `AddModulesToGuildAsync`) already existing commands will start to require `Administator` permissions.

As far as I noticed the only difference between them inside `BulkOverwriteGuildCommandsAsync` method is `DefaultMemberPermission` property.
The old command (that will will start to require `Administator` permission) have `0`.
![image](https://user-images.githubusercontent.com/13663047/202660076-ee50aa51-fad1-43de-be96-5e3f684dab02.png)
While the new one have `null`.
![image](https://user-images.githubusercontent.com/13663047/202660292-328753ff-c3fc-4c37-ab79-0f475b5fefd4.png)

And changing it to `null` here resolves the problem. Which is kinda strange, `0` should mean no permissions according to the docs.

### Version

3.8.1

### Logs

-

### Sample

```cs
// add a command with no permissions
await _interaction.AddCommandsToGuildAsync(guild, true, command1);
// add a second one
await _interaction.AddCommandsToGuildAsync(guild, false, command2);

// command1 now requires Administrator permission
```

### Packages

-

**Comment by Eloncase** [comment]
Changing [this](https://github.com/discord-net/Discord.Net/blob/ea039b848cd4e2a81bf00d657067ba76a29234b6/src/Discord.Net.Interactions/Utilities/ApplicationCommandRestUtil.cs#L226) to this
```
DefaultMemberPermissions = command.DefaultMemberPermissions.RawValue == 0 ? new Optional<GuildPermission>() : (GuildPermission)command.DefaultMemberPermissions.RawValue
```
appears to solve the problem.

**Comment by dukesteen** [comment]
You should make a pr then
