### ISSUE TITLE
[Bug]:  Group permissions not functioning properly

### ISSUE THREAD

**Issue by jwoff78** [RogueException/Discord.Net#2522]
### Check The Docs

- [X] I double checked the docs and couldn't find any useful information.

### Verify Issue Source

- [X] I verified the issue was caused by Discord.Net.

### Check your intents

- [X] I double checked that I have the required intents.

### Description

DefaultMemberPremissions not working with Groups in interactionmodulebase

after [Group("mod", "moderation commands")] permissions fail to work

### Version

3.8.1

### Logs

There's no logs a user can ban themselves and I can't fix it

### Sample

```
   [SlashCommand("kick", "kick a user")]
            [DefaultMemberPermissions(GuildPermission.KickMembers)]
            public async Task KickMember(IUser user, [MaxLength(100)] string reason = "No reason provided")
```

### Packages

N/A

**Comment by Misha-133** [comment]
default member permissions only apply to top level commands - group of commands in your case.
```cs
// This will work
[DefaultMemberPermissions(GuildPermissions.ModerateMembers)]
[Group("mod", "mod commands")]
public class ModCommandsGroup : InteractionModuleBase<SocketInteractionContext>
{
    [SlashCommand("kick", "kick command")]
    public async Task .........
}
```

```cs
[Group("mod", "mod commands")]
public class ModCommandsGroup : InteractionModuleBase<SocketInteractionContext>
{
// This WON'T work
    [DefaultMemberPermissions(GuildPermissions.ModerateMembers)]
    [SlashCommand("kick", "kick command")]
}
```
more info in docs: https://discordnet.dev/guides/int_framework/permissions.html
