### ISSUE TITLE
Missing paramter in Doc for SlashCommandBuilder exsample

### ISSUE THREAD

**Issue by Halbritter** [RogueException/Discord.Net#2529]
The doc page docs/guides/int_basics/application-commands/slash-commands/parameters.md uses a empty constructor for the `SlashCommandBuilder` which is not valid. The constructor signature is `SlashCommandBuilder(ModuleBuilder module, string name, ExecuteCallback callback)`
Version 3.8.1 from nuget

**Comment by Misha-133** [comment]
It uses the `SlashCommandBuilder` from `Discord` namespace which doesn't have a construstor. 
You are confusing it with the one from `Discord.Interactions.Builders` namespace.

**Comment by Halbritter** [comment]
Thank you you for correcting me. You are right.
Maybe its a good idea to indicate the namespace in the example.

**Comment by Halbritter** [comment]
https://github.com/discord-net/Discord.Net/pull/2534
