### ISSUE TITLE
[Bug]: Remove the `reason` field from `AddBanAsync` and `KickAsync` methods or make them obsolete

### ISSUE THREAD

**Issue by 1NieR** [RogueException/Discord.Net#2538]
### Check The Docs

- [X] I double checked the docs and couldn't find any useful information.

### Verify Issue Source

- [X] I verified the issue was caused by Discord.Net.

### Check your intents

- [X] I double checked that I have the required intents.

### Description

Since API v10 the `reason` field has been removed and replaced by `X-Audit-Log-Reason`.
https://github.com/discord/discord-api-docs/pull/5219#issue-1312161437
![API V10](https://user-images.githubusercontent.com/49203428/208790886-1c5b30f9-3b1a-4f35-a7eb-8d3493dd4dd8.png)
![ban](https://user-images.githubusercontent.com/49203428/208790911-dc489bc7-4467-4230-8502-b2a8db704917.png)
![kick](https://user-images.githubusercontent.com/49203428/208790949-b986ba0b-d982-494e-b1a5-03401d58c852.png)

### Version

3.8.1

### Logs

(none)

### Packages

N/A

**Comment by SylveonDeko** [comment]
How about instead we fix the field and not break many many bots

**Comment by cjbonn** [comment]
Just noting the locations in case someone wants to PR. I might get around to this myself eventually. Should be easy enough to change the reason logic to add the `X-Audit-Log-Reason`  to the `options` parameter in both these methods (`options.AuditLogReason = reason;` perhaps?).

Possibly need to think of how to handle if both the reason param and RequestOptions.AuditLogReason are both supplied at the same time.

**Ban:** https://github.com/discord-net/Discord.Net/blob/25cfb8822fe63adfff4cb493326ad8915e634dbc/src/Discord.Net.Rest/DiscordRestApiClient.cs#L1648
**Kick:** https://github.com/discord-net/Discord.Net/blob/25cfb8822fe63adfff4cb493326ad8915e634dbc/src/Discord.Net.Rest/DiscordRestApiClient.cs#L1854
