### ISSUE TITLE
[Bug]: Creating a post on a forum channel, ignores the Tags assigned.

### ISSUE THREAD

**Issue by DiegoBao** [RogueException/Discord.Net#2539]
### Check The Docs

- [X] I double checked the docs and couldn't find any useful information.

### Verify Issue Source

- [X] I verified the issue was caused by Discord.Net.

### Check your intents

- [X] I double checked that I have the required intents.

### Description

When using the CreatePostAsync of a FocumChannel and passing correct tags, they are ignored and the post is created without the tags. 

Modifying the post once created with the same tags, assigned it to the post, so it is just an issue during creation.

### Version

3.9.0-nightly build.

### Logs

There are no applicable logs, as the CreatePostAsync method doesn't return any error but it doesn't assign tags.

### Sample

```cs
IForumChannel gamesChannel = guild.GetChannel(channelId) as IForumChannel;
ForumTag tag = gamesChannel.Tags.First();

IThreadChannel post = await gamesChannel.CreatePostAsync(
      title: "Title",
      archiveDuration: ThreadArchiveDuration.OneWeek,
      text: "Some text",
      tags: new[] { tag }
  );
```

### Packages

None.

**Comment by Misha-133** [comment]
Yup, this seems to be my oversight.
As a temporary solution you can use `SocketForumChannel` instead of `IForumChannel`
I'll PR the fix for this tho.
