### ISSUE TITLE
[Bug]: SocketMessage.Content is empty

### ISSUE THREAD

**Issue by Kira-PH** [RogueException/Discord.Net#2554]
### Check The Docs

- [X] I double checked the docs and couldn't find any useful information.

### Verify Issue Source

- [X] I verified the issue was caused by Discord.Net.

### Check your intents

- [X] I double checked that I have the required intents.

### Description

After updating to 3.8.1 or later, SocketMessage.Content is empty. With 3.8.0 or earlier, SocketMessage.Content is populated correctly.

### Version

3.8.1

### Working Version

3.8.0

### Logs

n/a

### Sample

```cs
private DiscordSocketClient _client;

public void Run()
{
    _client = new DiscordSocketClient(new DiscordSocketConfig
        {
	    AlwaysDownloadUsers = true,
	    LogLevel = LogSeverity.Debug
	});

    await _client.LoginAsync(TokenType.Bot, "secret");
    await _client.StartAsync();

    _client.MessageReceived += ProcessMessage;

    await Task.Delay(-1);
}

public void ProcessMessage(SocketMessage message)
{
    // message.Content is empty here
}
```

### Packages

n/a

**Comment by Misha-133** [comment]
Duplicate #2499, #2482, #2470

**Comment by Misha-133** [comment]
tdlr: add `GatewayIntents.MessageContent` to your `DiscordSocketConfig`

**Comment by Kira-PH** [comment]
Thank you!

Seems weird (as well as redundant and confusing) that you have to declare the intents when connecting as well as in the bot configuration. Not suggesting this is a fault on the part of Discord.Net, just griping a little about Discord making breaking changes.

**Comment by cjbonn** [comment]
> Thank you!
> 
> Seems weird (as well as redundant and confusing) that you have to declare the intents when connecting as well as in the bot configuration. Not suggesting this is a fault on the part of Discord.Net, just griping a little about Discord making breaking changes.

I mean, they did give us almost a year in advance warning that it was going to occur, and to apply for the intents before it happens. Plenty of time, imo.

**Comment by MrCakeSlayer** [comment]
Closing due to duplicate + solved
