### ISSUE TITLE
[Bug]: Button regex does not work

### ISSUE THREAD

**Issue by SylveonDeko** [RogueException/Discord.Net#2555]
### Check The Docs

- [X] I double checked the docs and couldn't find any useful information.

### Verify Issue Source

- [X] I verified the issue was caused by Discord.Net.

### Check your intents

- [X] I double checked that I have the required intents.

### Description

So, for some reason TreatAsRegex is off by default, which was not mentioned and probably many many bots needed refactoring, however even with TreatAsRegex enabled, for some reason a simple regex like ```[ComponentInteraction("trigger.*.runin.*$*", true), CheckPermissions]``` Does not work.

For some reason, it goes through all preconditions just fine but never runs the actual method

### Version

3.9

### Working Version

3.8.1

### Logs

No stack traces

### Packages

None

**Comment by Cenngo** [comment]
TreatAsRegex allows you to use raw Regex templates in the CustomID field which bypasses the Regex generator of IF. So whatever you put in the CustomID field must be a valid Regex template, thats why `trigger.*.runin.*$*` wouldnt work.  TreatAsRegex=false defaults to the wild card pattern used before 3.9.0.

**Comment by SylveonDeko** [comment]
in that case it didn't even run

**Comment by SylveonDeko** [comment]
it didnt even trigger the precondition

**Comment by cjbonn** [comment]
Issue appears to have to due with usage of $.

In my test `btn_apples-oranges` worked, `btn_apples$oranges` returned `No Discord.Interactions.ComponentCommandInfo found for btn_apples$oranges`.

**Comment by SylveonDeko** [comment]
I don't think that's supposed to happen lol, also we can't just replace it with something else because there's many many people who used buttons with custom json and that's part of the custom ID.

**Comment by Cenngo** [comment]
> I don't think that's supposed to happen lol, also we can't just replace it with something else because there's many many people who used buttons with custom json and that's part of the custom ID.

yep, working on a fix.

**Comment by Cenngo** [comment]
@SylveonDeko mind testing this out? #2557

**Comment by SylveonDeko** [comment]
I'm sick atm but I'll test it out asap

**Comment by Cenngo** [comment]
yea no rush, hope you feel better soon

**Comment by cjbonn** [comment]
Tested using same case before, worked for both, and also worked via regex. Looks good on my end, thanks!
