### ISSUE TITLE
Can't create a new message variable with a specific user and specific content.

### ISSUE THREAD

**Issue by aggiczy** [RogueException/Discord.Net#2556]
**Hey,**

_I want to create a sudo command in my bot and to make that I need to create a new message with a specific user and a specific content._
The problem is that I can't create a new message variable with the specific user and the new content either change the existing message's user and content. **How can I do one of these?**

**Thanks,
Aki26**

![Idle_1672757360](https://user-images.githubusercontent.com/64480571/210380768-864bd472-d776-4761-a456-31e6ec4a4857.png)
![Idle_1672757460](https://user-images.githubusercontent.com/64480571/210381079-45fa4dcf-1794-40d4-be6c-e6c896234ef8.png)
![Idle_1672757559](https://user-images.githubusercontent.com/64480571/210381426-15644c42-66fe-4e55-8d5e-4065e53a9988.png)

**Comment by SylveonDeko** [comment]
Make your own message class that inherits IUserMessage

**Comment by aggiczy** [comment]
> Make your own message class that inherits IUserMessage

First of all, thank you for your answer.

I get a long error for this. Did I do something wrong?
Also, what should be in the class?

![devenv_1672759952](https://user-images.githubusercontent.com/64480571/210389119-fece97c0-058b-4e96-8a05-c91b5fd73cbe.png)

```cs
using System;
using System.Threading.Tasks;
using Discord;

namespace RangerBot.Services.Message
{
    public class Message : IUserMessage
    {
    }
}
```

**Comment by SylveonDeko** [comment]
https://github.com/SylveonDeko/Mewdeko/blob/main/src/Mewdeko/Common/DiscordImplementations/MewdekoUserMessage.cs
