### ISSUE TITLE
[Bug]: ExecuteCommandAsync is not returning an error on failed Preconditions

### ISSUE THREAD

**Issue by FlameFlag** [RogueException/Discord.Net#2559]
### Check The Docs

- [X] I double checked the docs and couldn't find any useful information.

### Verify Issue Source

- [X] I verified the issue was caused by Discord.Net.

### Check your intents

- [X] I double checked that I have the required intents.

### Description

**ExecuteCommandAsync** always returns **true** on ``IsSuccess`` even if a **Precondition** returns an Error.

This affects built-in conditions such as ``[RequireOwner]`` and custom ones as well. 

### Version

3.9.0

### Logs

```
async TestAttAttribute.CheckRequirementsAsync()at /Users/user/RiderProjects/PatriotBot/Modules/TopLevel/AboutCommand.cs:line 52
AsyncMethodBuilderCore.Start<System.__Cuser>()
TestAttAttribute.CheckRequirementsAsync()
CommandInfo<SlashCommandParameterInfo>.<>c__DisplayClass45_0.<<CheckPreconditionsAsync>g__CheckGroups|0>d.MoveNext()
AsyncMethodBuilderCore.Start<Discord.Interactions.CommandInfo<Discord.Interactions.SlashCommandParameterInfo>.<>c__DisplayClass45_0.<<CheckPreconditionsAsync>g__CheckGroups|0>d>()
AsyncTaskMethodBuilder<PreconditionResult>.Start<Discord.Interactions.CommandInfo<Discord.Interactions.SlashCommandParameterInfo>.<>c__DisplayClass45_0.<<CheckPreconditionsAsync>g__CheckGroups|0>d>()
CommandInfo<SlashCommandParameterInfo>.<>c__DisplayClass45_0.<CheckPreconditionsAsync>g__CheckGroups|0()
CommandInfo<SlashCommandParameterInfo>.<CheckPreconditionsAsync>d__45.MoveNext()
AsyncMethodBuilderCore.Start<Discord.Interactions.CommandInfo<Discord.Interactions.SlashCommandParameterInfo>.<CheckPreconditionsAsync>d__45>()
AsyncTaskMethodBuilder<PreconditionResult>.Start<Discord.Interactions.CommandInfo<Discord.Interactions.SlashCommandParameterInfo>.<CheckPreconditionsAsync>d__45>()
CommandInfo<SlashCommandParameterInfo>.CheckPreconditionsAsync()
CommandInfo<SlashCommandParameterInfo>.<ExecuteInternalAsync>d__42.MoveNext()
AsyncMethodBuilderCore.Start<Discord.Interactions.CommandInfo<Discord.Interactions.SlashCommandParameterInfo>.<ExecuteInternalAsync>d__42>()
AsyncTaskMethodBuilder<IResult>.Start<Discord.Interactions.CommandInfo<Discord.Interactions.SlashCommandParameterInfo>.<ExecuteInternalAsync>d__42>()
CommandInfo<SlashCommandParameterInfo>.ExecuteInternalAsync()
CommandInfo<SlashCommandParameterInfo>.<>c__DisplayClass40_0.<<ExecuteAsync>b__0>d.MoveNext()
AsyncMethodBuilderCore.Start<Discord.Interactions.CommandInfo<Discord.Interactions.SlashCommandParameterInfo>.<>c__DisplayClass40_0.<<ExecuteAsync>b__0>d>()
AsyncTaskMethodBuilder.Start<Discord.Interactions.CommandInfo<Discord.Interactions.SlashCommandParameterInfo>.<>c__DisplayClass40_0.<<ExecuteAsync>b__0>d>()
CommandInfo<SlashCommandParameterInfo>.<>c__DisplayClass40_0.<ExecuteAsync>b__0()
Task<Task>.InnerInvoke()
ExecutionContext.RunFromThreadPoolDispatchLoop()
Task.ExecuteWithThreadLocal()
ThreadPoolWorkQueue.Dispatch()
PortableThreadPool.WorkerThread.WorkerThreadStart()
Thread.StartCallback()
[Native to Managed Transition]
```
![SCR-20230104-hbm](https://user-images.githubusercontent.com/57304299/210535494-47d713f0-e99f-4408-9aa6-1f0745d30226.png)

### Sample

```cs
using Discord.Interactions;

public sealed partial class TopLevel : InteractionModuleBase<SocketInteractionContext>
{
    [TestAtt]
    [SlashCommand("ping", "Pong!")]
    public async Task Ping() => await DeferAsync(ephemeral: true)
        .ContinueWith(async _ => await FollowupAsync("Pong!", ephemeral: true));
}

public class TestAttAttribute : PreconditionAttribute
{
    private HttpClient Client { get; } = new();

    public override async Task<PreconditionResult> CheckRequirementsAsync(IInteractionContext context, ICommandInfo commandInfo, IServiceProvider services)
    {
        if (Client.GetAsync("https://google.com").Result.IsSuccessStatusCode)
            return await Task.FromResult(PreconditionResult.FromError("Google is up!"));
        return PreconditionResult.FromSuccess();
    }
}
// InteractionHandler.cs
private async Task HandleInteraction(SocketInteraction interaction)
{
    try {
        var ctx = new SocketInteractionContext(_discordClient, interaction);
        var result = await _commands.ExecuteCommandAsync(ctx, _services);
        if (!result.IsSuccess)
        {
            if (result.Error is InteractionCommandError.UnmetPrecondition)
            {
                await interaction.RespondAsync("Failed to execute command");
            }
        }
    } catch (Exception ex) {
        Console.WriteLine(ex);
        if (interaction.Type is InteractionType.ApplicationCommand)
            await interaction.GetOriginalResponseAsync().ContinueWith(async msg => await msg.Result.DeleteAsync());
    }
}
```

### Packages

Microsoft.Extensions.DependencyInjection V7.0.0
Microsoft.Extensions.Hosting V7.0.0-rc.2.22472.3

**Comment by cjbonn** [comment]
Works fine for me. So it's likely user error in your interaction handler code.

**Comment by Cenngo** [comment]
See https://github.com/discord-net/Discord.Net/blob/dev/samples/InteractionFramework/InteractionHandler.cs#L52-L80.

**Comment by FlameFlag** [comment]
> See https://github.com/discord-net/Discord.Net/blob/dev/samples/InteractionFramework/InteractionHandler.cs#L52-L80.

I used the example InteractionHandler and I'm still getting ``The application did not respond``

**Comment by Cenngo** [comment]
> > See https://github.com/discord-net/Discord.Net/blob/dev/samples/InteractionFramework/InteractionHandler.cs#L52-L80.
> 
> I used the example InteractionHandler and I'm still getting `The application did not respond`

I mean you still need to put something like `await interaction.RespondAsync(result.ErrorReason)` where it says `//implement`

**Comment by Cenngo** [comment]
> > See https://github.com/discord-net/Discord.Net/blob/dev/samples/InteractionFramework/InteractionHandler.cs#L52-L80.
> 
> I used the example InteractionHandler and I'm still getting `The application did not respond`

I mean you still need to put something like `await interaction.RespondAsync(result.ErrorReason)` where it says `//implement`

**Comment by FlameFlag** [comment]
> > > See https://github.com/discord-net/Discord.Net/blob/dev/samples/InteractionFramework/InteractionHandler.cs#L52-L80.
> > 
> > 
> > I used the example InteractionHandler and I'm still getting `The application did not respond`
> 
> I mean you still need to put something like `await interaction.RespondAsync(result.ErrorReason)` where it says `//implement`

``result`` still *results* in success even when Condition is not met...

**Comment by cjbonn** [comment]
> > > > See https://github.com/discord-net/Discord.Net/blob/dev/samples/InteractionFramework/InteractionHandler.cs#L52-L80.
> > > 
> > > 
> > > I used the example InteractionHandler and I'm still getting `The application did not respond`
> > 
> > 
> > I mean you still need to put something like `await interaction.RespondAsync(result.ErrorReason)` where it says `//implement`
> 
> `result` still _results_ in success even when Condition is not met...

Remove your logic, throw the FromError by itself. Then throw the FromSuccess by itself. If both work, as they did on my end, the issue is in your code, not the library.

**Comment by FlameFlag** [comment]
> > > > > See https://github.com/discord-net/Discord.Net/blob/dev/samples/InteractionFramework/InteractionHandler.cs#L52-L80.
> > > > 
> > > > 
> > > > I used the example InteractionHandler and I'm still getting `The application did not respond`
> > > 
> > > 
> > > I mean you still need to put something like `await interaction.RespondAsync(result.ErrorReason)` where it says `//implement`
> > 
> > 
> > `result` still _results_ in success even when Condition is not met...
> 
> Remove your logic, throw the FromError by itself. Then throw the FromSuccess by itself. If both work, as they did on my end, the issue is in your code, not the library.

``IsSuccess`` is still **true** in ``var result`` even if the condition returns FromError regardless of anything.
```cs
public override async Task<PreconditionResult> CheckRequirementsAsync(IInteractionContext context, ICommandInfo commandInfo, IServiceProvider services) 
        => await Task.FromResult(PreconditionResult.FromError("Google is up!"));
```

This issue still occurs even if used the built-in conditions such as ``[RequireNsfw]`` for example

Here is the ``HandleInteraction``
```cs
private readonly DiscordSocketClient _discordClient;
private readonly InteractionService _commands;
private readonly IServiceProvider _services;

public InteractionHandler(DiscordSocketClient discordClient, InteractionService commands, IServiceProvider services)
{
    _discordClient = discordClient;
    _commands = commands;
    _services = services;
}

public async Task InitializeAsync()
{
    await _commands.AddModulesAsync(Assembly.GetEntryAssembly(), _services);
    _discordClient.InteractionCreated += HandleInteraction;
    _commands.SlashCommandExecuted += SlashCommandExecuted;
    _commands.ContextCommandExecuted += ContextCommandExecuted;
    _commands.ComponentCommandExecuted += ComponentCommandExecuted;
}

private static Task ComponentCommandExecuted(ComponentCommandInfo arg1, IInteractionContext arg2, IResult arg3) => Task.CompletedTask;

private static Task ContextCommandExecuted(ContextCommandInfo arg1, IInteractionContext arg2, IResult arg3) => Task.CompletedTask;

private static Task SlashCommandExecuted(SlashCommandInfo arg1, IInteractionContext arg2, IResult arg3) => Task.CompletedTask;

private async Task HandleInteraction(SocketInteraction interaction)
{
    try {
        // Create an execution context that matches the generic type parameter of your InteractionModuleBase<T> modules
        var ctx = new SocketInteractionContext(_discordClient, interaction);
        var result = await _commands.ExecuteCommandAsync(ctx, _services);
        if (!result.IsSuccess)
        {
            if (result.Error is InteractionCommandError.UnmetPrecondition)
            {
                await interaction.RespondAsync("Failed to execute command");
            }
        }
    } catch (Exception ex) {
        Console.WriteLine(ex);
        if (interaction.Type is InteractionType.ApplicationCommand)
            await interaction.GetOriginalResponseAsync().ContinueWith(async msg => await msg.Result.DeleteAsync());
    }
}
```

**Comment by cjbonn** [comment]
OK tested and confirmed. For clarity, the issue is that ExecuteCommandAsync is not returning an error on failed preconditions (please update your bug description). I'm not sure if this is intended or not - I personally always assumed that the result of the Execute was strictly if it was able to execute or not, so I discarded that result and used the results in XCommandExecuted, which does work as expected.

**Comment by FlameFlag** [comment]
I switched to **SlashCommandExecuted** and conditions do work now.

```cs
private static async Task SlashCommandExecuted(SlashCommandInfo arg1, IInteractionContext arg2, IResult arg3)
{
    if (arg3 is { IsSuccess: false, Error: InteractionCommandError.UnmetPrecondition })
        await arg2.Interaction.RespondAsync(arg3.ErrorReason, ephemeral: true);
}
```

If **ExecuteCommandAsync** is not suppose to account for this then I will close the issue.

**Comment by cjbonn** [comment]
It might be a case of Interaction Framework vs Base DNet (IE using service to build commands versus created them using the builder), as InteractionCreated is an event of the client, not the interaction service 🤔
