### ISSUE TITLE
[Bug]: RTCRegion is not sets in CreateVoiceChannelAsync

### ISSUE THREAD

**Issue by vl4d1at0r** [RogueException/Discord.Net#2563]
### Check The Docs

- [X] I double checked the docs and couldn't find any useful information.

### Verify Issue Source

- [X] I verified the issue was caused by Discord.Net.

### Check your intents

- [X] I double checked that I have the required intents.

### Description

When I set RTCRegion in properties parameter of CreateVoiceChannelAsync it not sets it in real channel and I need to modify channel after that to properly set RTCRegion

### Version

3.9.0

### Logs

No logs needed

### Packages

There is no problems with another packages

**Comment by cjbonn** [comment]
Tested the code below, and confirmed region is not set:
`await Context.Guild.CreateVoiceChannelAsync("test", props => props.RTCRegion = "us-west");`

[CreateGuildChannelParams.cs](https://github.com/discord-net/Discord.Net/blob/7c535b952a00166e3c22e3b39a68176fe52241c6/src/Discord.Net.Rest/API/Rest/CreateGuildChannelParams.cs) does not implement `rtc_region` or `video_quality_mode` currently. However, I do see it located in [VoiceChannelProperties](https://github.com/discord-net/Discord.Net/blob/933ea42eaac47094ef77608aa2aa3f6d602ac30d/src/Discord.Net.Core/Entities/Channels/VoiceChannelProperties.cs).
