### ISSUE TITLE
Discord Linked Roles feature

### ISSUE THREAD

**Issue by DurtyFree** [RogueException/Discord.Net#2566]
Discord has announced linked roles feature, which is gradually rolling out already. Are there any plans on adding this to the library any time soon? I couldn't find anything related here

Developer resources are already available and I would love to play around with it using the Discord.NET lib.

More information Linked roles: https://support.discord.com/hc/en-us/articles/10388356626711-Connections-Linked-Roles-Admins & related announcement @ https://discord.com/blog/connected-accounts-functionality-boost-linked-roles

Developer docs around linked roles: https://discord.com/developers/docs/tutorials/configuring-app-metadata-for-linked-roles

Would be great to see Discord.NET API around the role connection meta data stuff (https://discord.com/developers/docs/resources/application-role-connection-metadata)!

**Comment by cjbonn** [comment]
It's currently being drafted: #2530

**Comment by csmir** [comment]
Merged
