### ISSUE TITLE
[Bug]: SocketMessageComponent.Message.ReferencedMessage always returns null

### ISSUE THREAD

**Issue by drizzle-mizzle** [RogueException/Discord.Net#2567]
### Check The Docs

- [X] I double checked the docs and couldn't find any useful information.

### Verify Issue Source

- [X] I verified the issue was caused by Discord.Net.

### Check your intents

- [X] I double checked that I have the required intents.

### Description

When you get a message from an executed button:

![image](https://user-images.githubusercontent.com/55811932/212889880-faaf18a5-d8d7-47d7-831a-a26f55203b77.png)

...it has a `Reference`, but there's no `ReferencedMessage`.

**Example:**
- creating message with a button and a reference on another message:

  ![image](https://user-images.githubusercontent.com/55811932/212889343-18ca3a68-b75d-4ff6-bfaa-faf2dac44750.png)

- press any button:
  
  ![image](https://user-images.githubusercontent.com/55811932/212890183-88a2892d-83f4-4376-a002-4b13311044d3.png)

### Version

3.9.0

### Working Version

-

### Logs

-

### Sample

```
private async Task HandleButton(SocketMessageComponent component)
{
    var message = component.Message;
    var messageRef = message.ReferencedMessage;
    // ...
}
```

### Packages

-

**Comment by Misha-133** [comment]
That's not a bug.
API doesn't send the referenced message with interaction payload
