### ISSUE TITLE
Discord Select Menu types

### ISSUE THREAD

**Issue by Tyndareus** [RogueException/Discord.Net#2568]
I have noticed that the discord API suggests a dropdown involving roles and checkboxes.

Is this possible in the current select menu? I have had a little play around but don't seem to see a certain flow that would trigger that functionality...

If possible could it be included at some point?

**Comment by Misha-133** [comment]
Support for new select types is coming in the next D.Net release

**Comment by Tyndareus** [comment]
Ah thanks, will keep an eye out

**Comment by Misha-133** [comment]
Also, if you need them rn - you could compile the library yourself from source. The PR that brings support has been merged a while ago.

**Comment by Tyndareus** [comment]
Nah its alright I am currently just using the Min/Max values on a SelectMenu to send off some strings that I lookup in a dictionary for the correct role ID to assign..

On another note, is there anyway to forcibly set the selected state of these options based on the client?
The bot I have makes a single post where people can come and just click their desired roles. But obviously since the bot is still in development, having a SelectMenu appear _now_ would mean that it doesn't know what the user has.

Because the display is client side, was wondering if there was a way to tell it that those options are selected because the user has role 5 or something

**Comment by Misha-133** [comment]
Well
Sadly, you can't set selected state of options
