### ISSUE TITLE
GuildPermissions don't update on change

### ISSUE THREAD

**Issue by khionu** [RogueException/Discord.Net#257]

**Comment by RogueException** [comment]
On what change specifically? Editing a role? Modifying a user's roles? Is this REST/WebSocket? Gotta be more specific.

**Comment by khionu** [comment]
WebSocket, after editing a Role's Perms.

**Comment by RogueException** [comment]
User GuildPerms are no longer cached in beta2, so this shouldnt be an issue anymore
