### ISSUE TITLE
Add a way to get @me

### ISSUE THREAD

**Issue by Sasino97** [RogueException/Discord.Net#2570]
I suggest to add a parameterless `DiscordRestClient.GetUserAsync` that returns the user at `/users/@me`. This is useless in bots, but it can be useful to other applications using the Discord REST API through a bearer token.

**Comment by Misha-133** [comment]
`DiscordRestClient` gets current user when `LoginAsync` is called & stores it in `CurrentUser` property.

*p.s. I agree that there should be a public method for this tho*
