### ISSUE TITLE
[Bug]: Sending DMs can cause rate lmit issues. 

### ISSUE THREAD

**Issue by QuinnDamerell** [RogueException/Discord.Net#2595]
### Check The Docs

- [X] I double checked the docs and couldn't find any useful information.

### Verify Issue Source

- [X] I verified the issue was caused by Discord.Net.

### Check your intents

- [X] I double checked that I have the required intents.

### Description

I'm using this lib, and it works great. But I have a pretty big user base and recently, I have realized I have been hitting rate limit issues with my bot sending DMs. One of the issues is that for each DM I send, I currently have to make 3 API calls. This is my current logic:

                var user = await m_restClient.GetUserAsync(userId);
                if (user != null)
                {
                    var channel = await user.CreateDMChannelAsync();
                    if(channel != null)
                    {
                        await channel.SendMessageAsync(embed: embed);
                    }
                    else
                    {
                        // Error
                    }
                }
                else
                {
                     // Error
                }

The problem I'm facing is that I need a RestDmChannel object to send the DM, but there's no way I could create one beyond this chain of calls. When I send the first DM to the user, I assume I need to follow this path, but after that I wish I could record the ids needed to send DMs directly to the user in my database. Due to the design of my service, I can't cache the RestDMChannnel objects in memory or anything.

It looks like there's a constructor of  RestDMChannle that would simply take a few ids, but all of the constructors for most of these objects are `internal`. 

So my problem is, I don't think there's currently any way of sending a DM to a user, who I know my bot has an existing DM thread, without making 3 API calls. Making 3 API calls for each DM is making me hit my rate limits. 

If anyone knows of a more efficient way of sending DMs, please let me know!

### Version

3.9.9

### Logs

N/A

### Packages

Discord.Net and Discord.Net.Webhooks

**Comment by markski1** [comment]
I'm not sure how these methods work as far as explicit API calls work, but could you maybe save one call by just using `user.SendMessageAsync` on the RestUser object directly and skip manually making a DM channel?

You can still detect if the user doesn't allow DM's by catching the HttpException it'll throw.

**Comment by QuinnDamerell** [comment]
Thanks for the response. It seems to work just fine with the few args. I worked around it with this:

  var args = new object[] { m_restClient, dmChannelId, userId };
  var type = typeof(RestDMChannel);
  var instance = type.Assembly.CreateInstance(
      type.FullName, false,
      BindingFlags.Instance | BindingFlags.NonPublic,
      null, args, null, null);
  var dmChannel = (RestDMChannel)instance;
