### ISSUE TITLE
Nullable arguments should be treated as optional?

### ISSUE THREAD

**Issue by GotoFinal** [RogueException/Discord.Net#2607]
I find it a bit weird that currently if I want to have a optional argument I need to do one of these for my slash commands:
```csharp
    public async Task Cmd(int arg = 0)
    public async Task Cmd(int? arg = null)
```
I feel like it should work just fine with just:
```csharp
    public async Task Cmd(int? arg)
```
as there is no way provide null value as a client, so should be treated the same as optional, I have some commands where I can't provide default value directly because its not static, and I just find myself constantly forggeting that i need to manually set it to null first, like 
```csharp
    public async Task Cmd(int? seed) {
        seed ??= _random.nextInt(...);
    }
```
vs:
```csharp
    public async Task Cmd(int? seed = null) {
        seed ??= _random.nextInt(...);
    }
```

**Comment by Joe4evr** [comment]
> as there is no way provide null value as a client

This is an incorrect assumption.
https://github.com/discord-net/Discord.Net/blob/7b321afa4f53d61d063172067f0066b51a7bc4ea/src/Discord.Net.Commands/Readers/NullableTypeReader.cs#L30-L31

**Comment by Cenngo** [comment]
> as there is no way provide null value as a client, so should be treated the same as optional

It is not correct to draw a conclusion like this. Tho its true that you cant assign a null value to parameters from the Discord client, we are still working in C# and the library should adhere to the language guidelines, thus command handler signatures should be still perfectly readable by someone who isnt familiar with Discord API. `Nullable<>` is a type and not a parameter attribute and reference types are all `Nullable<>`s by default so how would you propose that we differentiate between optional and non-optional parameters. And from the coding perspective, its impossible to know that whether a parameter's value was explicitly assigned as `null` or it was left unpopulated, `Optional<>` and `Nullable<>` are seperate entities for a reason. And finally, its always nice to be able to enforce the 'optionals come last' rule using the compiler.

**Comment by GotoFinal** [comment]
@Joe4evr oh wow... now I really hope this is not enabled by default, especially with "nothing" also getting parsed to null, does that mean that any command accepting a string? will get null instead if someone types "nothing"? Or is it optional or working only for some types like int??

@Cenngo Well I can live without it, but I for sure don't agree with that reasoning. At the end of a day if I have a method signature with `int?` all i care if its a null or a number, and someone using a command usually does not even know what a null is, from user perspective its a number or nothing, so why would something that can be nothing still be required to be provided.

But well, if thats a stance of the project, the issue can be just closed. Tho would be nice to be able to control behaviour of this.

**Comment by csmir** [comment]
The language itself behaves the same way? Let's use these 2 signatures as an example:

```cs
public bool MyMethod(int? value = null) => true;
```

```cs
public bool MyMethodNonOptional(int? value) => false;
```

And now lets try to call them:
```cs
MyMethodNonOptional(); 
// this does not compile, for it needs a parameter that must be provided, null or otherwise.

MyMethod(); 
// this compiles, because it is given a base value from within the method signature, simple as that.
```

All we do is follow these limitations, because they make **sense**. Every command framework out there adheres to these restrictions... And how can you not agree with reasoning that proves it is simply impossible for code to check if a nullable parameter is optional? I am wildly confused there.

In the case of text input, `"nothing"` and `"null"` are successfully parsed as the expected input type, `string`. Any code after that, which would be responsible for assigning null to nullable parameters will never be executed, because it already returned a successful result. No configuration is necessary for this.

**Comment by Joe4evr** [comment]
> now I really hope this is not enabled by default, especially with "nothing" also getting parsed to null, does that mean that any command accepting a string? will get null instead if someone types "nothing"? Or is it optional or working only for some types like int??

This is the default reader for nullable value types (so `string` is unaffected), and the reason `"nothing"` works is because that's the name for `null` in VB.

**Comment by GotoFinal** [comment]
@csmir well i meant the `string?` but from what i quickly tested it seems to still to normally parse `"nothing"` so its fine. And for types like `int?` cant pass `null` anyways because its not a number, so for what it is actually used?

>  And how can you not agree with reasoning that proves it is simply impossible for code to check if a nullable parameter is optional? I am wildly confused there.

Because in this case every nullable parameter is optional, discord parameters are named, it  does not make any sense to provide a parameter just to set it to null - especially that the ability to do so is implementation detail of this library that is not expected by anyone actually using commands. I don't see a reason to follow what frameworks not realted to discord idea of commands are doing. 

Can't imagine someone creating a discord command accepting a `string?` for any other reason than it being optional, especially that you can't pass a null to it anyways as we just confirmed.
So its then just useless notation that does not provide any value other than adding confusion of having an argument that technically can be null but discord wants you to provide a value so it can't be null, so whats the point? 

When i see `[SlashCommand]` its no longer a c# method for me, just an DLS interface between my c# code and discord, I expect it to behave according to discord rules. Just how when I use linq and type `.Where(smh => smh.x == 5)` when interacting with database I don't expect `smh.x == 5` to actually be called for all elements from database as typical c# code. Or how often people don't thinks of gradle DLS as groovy but its own thing, even tho its the same, but very non-standard to allow more user friendly approach. Or even how in c# we interact with 

Also tbh with your example i would say both methods have optional parameter, but one is explicit and other implicit, both calls with or without saying null work exactly the same, just one is more annoying to use (often done on purpose to encourage use of that optional parameter), for that argument to work methods would need to be called the same, but that's not possible.

**Comment by Cenngo** [comment]
> especially that the ability to do so is implementation detail of this library that is not expected by anyone actually using commands. I don't see a reason to follow what frameworks not realted to discord idea of commands are doing.

but it might be needed to be maintained by someone who isnt very familiar with discord's inner workings. What you are suggesting is neither readable nor maintainable. Frameworks shouldnt call extension points that wouldnt compile otherwise as @csmir stated previously. You cannot assume the intentions of the consuming assembly. Nullable contexts have many applications but declaring optional parameters isnt one of them. I wont hard code such a behavior just for the sake of convenience and lock people out who might actually wanna use them for safe-coding. 

> When i see [SlashCommand] its no longer a c# method for me, just an DLS interface between my c# code and discord, I expect it to behave according to discord rules.

Uhm, no? Quite the opposite actually. Its a .NET method first and a discord command second. 

In the case of EFCore, code translations are still done in compliance with .NET coding conventions. Anyone without any prior sql knowledge wouldnt mistake `smth.x == 5` for anything else. Newcomers should be still able to understand what is optional and what isnt at a glance.

**Comment by GotoFinal** [comment]
>  Frameworks shouldnt call extension points that wouldnt compile otherwise 

They do compile, you are just providing more parameters for easier use and more straightforward/intuitive behavior for discord. And for me still, any nullable parameter is an optional one, whatever i need to actually pass the null manually or compiler will do it for me is just convenience depending on language/tool im using.

Well, closing then as we won't agree with each other for sure, so pointless to continue, thanks for the discussion
