### ISSUE TITLE
Possible idea for future?

### ISSUE THREAD

**Issue by nkrs200** [RogueException/Discord.Net#2612]
I feel that a built-in command cooldown attribute should be added to the bot to prevent rate limiting.  I host and built two different bots from the ground up, and I feel that if both a cooldown attribute and a cooldown model were added into the Discord.Net Framework, it would allow bot creators more flexibility to specify how a long a user can wait.

**Comment by Winter** [comment]
You can achieve this on your own quite trivally by using the existing [Custom Preconditions](https://discordnet.dev/guides/int_framework/preconditions.html#custom-preconditions) API. 

I don't think there's a need for Discord.Net to implement a solution for this.
