### ISSUE TITLE
[Bug]: Voice Channel returns way too many users on versions 3.7.0 and up

### ISSUE THREAD

**Issue by akulihin** [RogueException/Discord.Net#2633]
### Check The Docs

- [X] I double checked the docs and couldn't find any useful information.

### Verify Issue Source

- [X] I verified the issue was caused by Discord.Net.

### Check your intents

- [X] I double checked that I have the required intents.

### Description

I have a server where voice channels are being created and deleted dynamically, names can repeat from time to time and I found out that after upgrading to version 3.7.0 or higher the following code may return way too many users:

`DiscordShardedClient.GetGuild(guildId).GetVoiceChannel(VoiceChannelId).Users.Count;`

For most channels, it returns the correct number of users but only for some, it returns `20946` or `20945` users. This number is pretty close to the total amount of users on the server. I was checking one of the channels - it had only 2 users in it, but looking at what was returned I saw many people that are on the server but not in the voice channel

### Version

 3.7.0 and up

### Working Version

3.6.1

### Logs

N/A

### Sample

`DiscordShardedClient.GetGuild(guildId).GetVoiceChannel(VoiceChannelId).Users.Count;`

### Packages

N/A

**Comment by BobVul** [comment]
Use `ConnectedUsers` instead. `Users` was changed around the time text messaging in voice channels was introduced.

See 3.7.0 release notes: https://github.com/discord-net/Discord.Net/releases/tag/3.7.0

**Comment by akulihin** [comment]
That worked, thank you, BobVul. It's a little confusing now and not intuitive after this change
