### ISSUE TITLE
Operation timed out on `Discord.WebSocket.SocketGuild.ConnectAudioAsync`

### ISSUE THREAD

**Issue by sowa705** [RogueException/Discord.Net#2634]
Hi, since yesterday my bot stopped working with the following exception.
```
System.TimeoutException: The operation has timed out.
         at Discord.WebSocket.SocketGuild.ConnectAudioAsync(UInt64 channelId, Boolean selfDeaf, Boolean selfMute, Boolean external)
         at Discord.WebSocket.SocketGuild.ConnectAudioAsync(UInt64 channelId, Boolean selfDeaf, Boolean selfMute, Boolean external)
         at Discord.WebSocket.SocketVoiceChannel.ConnectAsync(Boolean selfDeaf, Boolean selfMute, Boolean external)
         at Template.Services.PlaybackService.CreateSession(IVoiceChannel channel) 
```
This is happening on two separate API keys and both when running the bot from my PC and a linux server.
What could be the cause and how to fix this?
I've tried updating Discord.Net to 3.9.0 but the issue persists.

**Comment by Xefise** [comment]
I have the same situation.
Dotnet update, VPN and changing discord server location did not solve this problem.

**Comment by KamGol97** [comment]
I had the same problem. I noticed that DiscordSocketClient in Log event says Unknown OpCode (Hello).  After handling this case, the client stopped throwing timeout and started to connect.

file: Discord.Net.WebSocket\Audio\AudioClient.cs -> ProcessMessageAsync method

I just added:
`case VoiceOpCode.Hello:
await _audioLogger.DebugAsync("Received Hello message").ConfigureAwait(false);
break;`

**Comment by kieransouth** [comment]
The fix for this has been pushed to the dev branch already but no build has been published to NuGet #2617 

You have to add the nightly build package source to your NuGet package sources, then get the nightly builds from 2nd March 2023.

Feed URL: https://www.myget.org/F/discord-net/api/v3/index.json

Your csproj file should look like this when all's done:

```
    <PackageReference Include="Discord.Net" Version="3.9.0-20230302.10" />
    <PackageReference Include="Discord.Net.Commands" Version="3.9.0-build-20230302.10" />
    <PackageReference Include="Discord.Net.Core" Version="3.9.0-build-20230302.10" />
    <PackageReference Include="Discord.Net.Interactions" Version="3.9.0-build-20230302.10" />
    <PackageReference Include="Discord.Net.Rest" Version="3.9.0-build-20230302.10" />
    <PackageReference Include="Discord.Net.Webhook" Version="3.9.0-build-20230302.10" />
    <PackageReference Include="Discord.Net.WebSocket" Version="3.9.0-build-20230302.10" />
```

Not the best solution, but if you need something while waiting for the official NuGet build, this works.

**Comment by cjbonn** [comment]
Ref: "all apps with Voice Connections using IP Discovery must send 74-byte UDP packets. IP Discovery requests sending the deprecated 70-byte packet will no longer receive a response." - Discord Dev API announcement. This change was rolled out yesterday.

**Comment by sowa705** [comment]
> The fix for this has been pushed to the dev branch already but no build has been published to NuGet #2617

Doesn't work for me

**Comment by sowa705** [comment]
> Ref: "all apps with Voice Connections using IP Discovery must send 74-byte UDP packets. IP Discovery requests sending the deprecated 70-byte packet will no longer receive a response." - Discord Dev API announcement. This change was rolled out yesterday.

Is it known when will the nuget get published with the fix? Seems like a pretty major issue when all voice apps stop working

**Comment by cjbonn** [comment]
> > Ref: "all apps with Voice Connections using IP Discovery must send 74-byte UDP packets. IP Discovery requests sending the deprecated 70-byte packet will no longer receive a response." - Discord Dev API announcement. This change was rolled out yesterday.
> 
> Is it known when will the nuget get published with the fix? Seems like a pretty major issue when all voice apps stop working

I am not privy to that information - that'd be up to the maintainers. I've been waiting for a new release since December with all the new features =_=

**Comment by ms-lemos** [comment]
> > The fix for this has been pushed to the dev branch already but no build has been published to NuGet #2617
> 
> Doesn't work for me

Did you add the nuget source? It worked for me

**Comment by RageMellon** [comment]
> > The fix for this has been pushed to the dev branch already but no build has been published to NuGet #2617
> 
> Doesn't work for me

I'm also still seeing this issue on the Dev build from 2nd March 2023. I've literally made a blank project from scratch to test this and my .csproj packages all match those in kieransouth's comment above. 

@ms-lemos did you do anything other than install those packages from the dev package source?

**Comment by Xefise** [comment]
@RageMellon In [my project](https://github.com/SenterisTeam/DSentBot/commit/3f14da0fe5e37dd3018e186792cb80ff180563d9) on dotnet 7 this worked. Check does packages gets from [discord.net source](https://www.myget.org/F/discord-net/api/v3/index.json) **for sure**. I spent about 5 mins to get understand how to do that in rider:D

**Comment by sowa705** [comment]
Is this project abandoned? No maintainer has said anything

**Comment by SylveonDeko** [comment]
> Is this project abandoned? No maintainer has said anything

It's not. People have their own lives.

**Comment by ms-lemos** [comment]
> > > The fix for this has been pushed to the dev branch already but no build has been published to NuGet #2617
> > 
> > 
> > Doesn't work for me
> 
> I'm also still seeing this issue on the Dev build from 2nd March 2023. I've literally made a blank project from scratch to test this and my .csproj packages all match those in kieransouth's comment above.
> 
> @ms-lemos did you do anything other than install those packages from the dev package source?

No, anything else, I've just set the packages like it was said to do and it worked again.
https://github.com/ms-lemos/BolineaBot/blob/aef6a9445a187d7240cbf8d6563cb8908cb5d58a/BolineaBot.Console/BolineaBot.Console.csproj#L48-L54

**Comment by sowa705** [comment]
It seems that discord fixed the issue on their end without updating anything. Also a hint: DSharpPlus has nightly builds on nuget :)

**Comment by quinchs** [comment]
I'll coordinate a release within the next couple of days, sorry for the late fixes :(

**Comment by quinchs** [comment]
Release is out: https://www.nuget.org/packages/Discord.Net/3.10.0
