### ISSUE TITLE
Is there a way to turn back on text-based commands after v3.8.1?

### ISSUE THREAD

**Issue by Xefise** [RogueException/Discord.Net#2635]
Hi! After **v3.8.1** text-based commands stopped working. Can I turn them back on?
Because of #2634 I need update Discord.Net.
I do not really like slash commands because of conflicts with other bots and other problems. Text-based commands are more simple.

As said [discord](https://support-dev.discord.com/hc/en-us/articles/4404772028055-Message-Content-Privileged-Intent-FAQ)
WHAT ABOUT UNVERIFIED BOTS?
Unverified bots and apps will not be impacted by this change and can continue to use message content in their bot development without requesting any Privileged Intent.

Sorry if I did not notice something.

**Comment by CottageDwellingCat** [comment]
Please enable the `MessageContent` gateway intent both in your client code as described [in the docs](https://discordnet.dev/guides/v2_v3_guide/v2_to_v3_guide.html#gatewayintents) and in the discord developer portal from app info>bot
![image](https://user-images.githubusercontent.com/80918250/226798236-996e3a82-7ba0-4fc8-9b08-01ab321cd182.png)

**Comment by Xefise** [comment]
Thank you for help but this was already checked.

My friend have found solution:  
Add `GatewayIntents = GatewayIntents.AllUnprivileged | GatewayIntents.MessageContent | GatewayIntents.GuildMessages`
to `DiscordSocketConfig`

https://github.com/SenterisTeam/DSentBot/commit/3f832c040c72139d781a2100551e9220dba6d520

**Comment by CottageDwellingCat** [comment]
`GuildMessages` is an unprivileged intent and should be included in `AllUnprivileged`, otherwise it looks good :3
