### ISSUE TITLE
[Additional Information] to the slash commands doc

### ISSUE THREAD

**Issue by Detective-Tapp** [RogueException/Discord.Net#2637]
Whilst adding slash commands to my bot, I kept on getting errors with the commands.

Turns out the command name cannot be capitalized. 

It would be nice, if that would be added to the doc as one of the bullet points. @ 
https://discordnet.dev/guides/int_basics/application-commands/slash-commands/creating-slash-commands.html

If this happens to be notated elsewhere, in that case forgive my ignorance.

**Comment by AnalogFeelings** [comment]
I think you missed this part in the example code:
```cs
// Note: Names have to be all lowercase and match the regular expression ^[\w-]{3,32}$
guildCommand.WithName("first-command");
```
