### ISSUE TITLE
Prioritise typed overloads in commands

### ISSUE THREAD

**Issue by FiniteReality** [RogueException/Discord.Net#264]
Right now our command system has an issue with multiple overloads:

``` cs
[Command("a")]
public async Task OverloadedCommand(IUserMessage message, int argument)
[Command("a")]
public async Task OverloadCommand(IUserMessage message, string argument)
```

Since these overloads do not get prioritised based on what arguments were provided, the overload with the string parameter may get invoked instead of the overload with the integer parameter, but never the other way around.

One solution for this, as foxbot suggested, would be to add a 'Priority' attribute, to prioritise commands manually. Another solution would be to use the data provided by the type readers to choose the best overload to invoke.

**Comment by Joe4evr** [comment]
![](http://i.imgur.com/Ur3j4cI.gif)
Basically I'm thinking:
* A user can specify a `[Priority]` manually
* If lacking the attribute, the lib implicitly rates an overload with a `string` parameter the lowest priority (if that exists), which could at least take care of the simplest case (which is the example given)

Also:
* What should happen if one overload has a `[Priority]` set and another doesn't?
* What should happen if multiple overloads have the same `[Priority]` value set?

**Comment by FiniteReality** [comment]
I'm thinking a mix of both would probably be best. We could defer to the typereader data in the case of a stalemate between priorities. In the case of no priority I'd say having a default '0' would be best.

**Comment by khionu** [comment]
Considering Typed over String first should be done, regardless, though. Though I definitely like what has been discussed, for the Priority attribute

**Comment by Kwoth** [comment]
How high is this on the priority list? Any progress being made? Quite annoying.

**Comment by FiniteReality** [comment]
Right now I'm not sure how to implement the consideration for typed properties over untyped properties but implementing a PriorityAttribute should be fairly simple.
