### ISSUE TITLE
[Bug]: Unknown channel type on Forum

### ISSUE THREAD

**Issue by Exorion1er** [RogueException/Discord.Net#2643]
### Check The Docs

- [X] I double checked the docs and couldn't find any useful information.

### Verify Issue Source

- [X] I verified the issue was caused by Discord.Net.

### Check your intents

- [X] I double checked that I have the required intents.

### Description

When the sample method is invoked with a channel type Forum (IForumChannel), it throws an error "Unknown channel type".
It doesn't throw any error when used in a post inside that same Forum.
The channel is not null, I debugged it to make sure.

This is my first bot using Discord-net so I might be doing something obviously wrong ? Sorry if that's the case.

### Version

3.9.0
(Also checked with 3.10.0, same issue)

### Logs

System.ArgumentException
  HResult=0x80070057
  Message=Unknown channel type. Arg_ParamName_Name
  Source=Discord.Net.Core
  StackTrace:
   at Discord.ChannelPermissions.All(IChannel channel)
   at Discord.Permissions.ResolveChannel(IGuild guild, IGuildUser user, IGuildChannel channel, UInt64 guildPermissions)
   at Discord.WebSocket.SocketGuildUser.GetPermissions(IGuildChannel channel)
   at Fidobot.Controllers.CommandsController.<DoesUserHavePerms>d__1.MoveNext() in D:\Data\Projects\Fidobot\Controllers\CommandsController.cs:line 61
   at Fidobot.Controllers.CommandsController.<EatHandler>d__2.MoveNext() in D:\Data\Projects\Fidobot\Controllers\CommandsController.cs:line 96

### Sample

```cs
private static async Task<bool> DoesUserHavePerms(IGuildChannel channel, SocketSlashCommand cmd) {
  IGuildUser user = (IGuildUser)cmd.User;
  if (user.GetPermissions(channel).ManageThreads) {
    return true;
  }
  await cmd.RespondAsync("**ERROR:** You don't have the necessary permissions on this channel to execute that command.");
  return false;
}
```

### Packages

None

**Comment by Exorion1er** [comment]
After some digging I found [this](https://github.com/discord-net/Discord.Net/blob/9ccd9cf75ba84550b563304609cc4b19feca2018/src/Discord.Net.Core/Entities/Permissions/ChannelPermissions.cs#L62) which doesn't contain Forum.
This is all guess work tho.

**Comment by quinchs** [comment]
@Misha-133 can you take a look?

**Comment by Misha-133** [comment]
> @Misha-133 can you take a look?

Yup
Was going to look at this after I'm done with the audit log event
