### ISSUE TITLE
Create new Webhook from the client

### ISSUE THREAD

**Issue by drizzle-mizzle** [RogueException/Discord.Net#2658]
Is there's a way to create a new webhook for a channel? I tried to google and search in documentation, but couldn't find anything about it. In Discord.js there is:
```js
channel.createWebhook({
  name: 'Username',
  avatar: 'link',
}).then(webhook => console.log(`Created webhook ${webhook}`))
```
Does Discord.Net have something like this?

**Comment by Misha-133** [comment]
Check out this [doc page](https://discordnet.dev/api/Discord.IIntegrationChannel.html#Discord_IIntegrationChannel_CreateWebhookAsync_System_String_Stream_Discord_RequestOptions_)

**Comment by drizzle-mizzle** [comment]
Судя по всему, такого интерфейса не существует...
![image](https://user-images.githubusercontent.com/55811932/230714854-4d851df8-6643-4135-8baa-78e01e620d7d.png)

**Comment by drizzle-mizzle** [comment]
Прошу прощения. Не заметил, что использую устаревшую версию 3.9.0
Большое спасибо.
