### ISSUE TITLE
[Bug]: The MessageDeleted event does not return a message

### ISSUE THREAD

**Issue by MrAfitol** [RogueException/Discord.Net#2661]
### Check The Docs

- [X] I double checked the docs and couldn't find any useful information.

### Verify Issue Source

- [X] I verified the issue was caused by Discord.Net.

### Check your intents

- [X] I double checked that I have the required intents.

### Description

The MessageDeleted event does not return a message, although I have message caching enabled and everything is correct in the config

### Version

3.10.0

### Logs

A message () from Nickname#0000 was removed from the channel moderator-only ():

### Sample

```cs
_client = new DiscordSocketClient(new DiscordSocketConfig { AlwaysDownloadUsers = true, MessageCacheSize = 10000, });

public async Task HandleMessageDelete(Cacheable<IMessage, ulong> cachedMessage, Cacheable<IMessageChannel, ulong> cachedChannel)
        {
            // check if the message exists in cache; if not, we cannot report what was removed
            if (!cachedMessage.HasValue)
                return;
            // gets or downloads the channel if it's not in the cache
            IMessageChannel channel = await cachedChannel.GetOrDownloadAsync();
            var message = cachedMessage.Value;
            Console.WriteLine(
                $"A message ({message.Id}) from {message.Author} was removed from the channel {channel.Name} ({channel.Id}):"
                + Environment.NewLine
                + message.Content);
        }
```

### Packages

Discord.Net v3.10.0, Discord.Net.* v3.10.0, Microsoft.Extensions.DependencyInjection v8.0.0

**Comment by MrAfitol** [comment]
**Everything is included but still not working**
![DiscordLog](https://user-images.githubusercontent.com/76150070/231277927-c9dcc52e-8aaf-4516-ae9f-1da883d2587b.png)

**Comment by Misha-133** [comment]
You also need to specify intents in the `DiscordSocketConfig`
something like 
```cs
new DiscordSocketConfig {
....
GatewayIntents = GatewayIntents.AllUnpriviliged | GatewayIntents.MessageContent
.....
}
```

**Comment by MrAfitol** [comment]
> You also need to specify intents in the `DiscordSocketConfig` something like
> 
> ```cs
> new DiscordSocketConfig {
> ....
> GatewayIntents = GatewayIntents.AllUnpriviliged | GatewayIntents.MessageContent
> .....
> }
> ```

It works, thank you very much

**Comment by MrAfitol** [comment]
> You also need to specify intents in the `DiscordSocketConfig` something like
> 
> ```cs
> new DiscordSocketConfig {
> ....
> GatewayIntents = GatewayIntents.AllUnpriviliged | GatewayIntents.MessageContent
> .....
> }
> ```

**This fixed the problem, thank you very much!**
