### ISSUE TITLE
[Bug]: Clyde AI causes an error.

### ISSUE THREAD

**Issue by Talan122** [RogueException/Discord.Net#2664]
### Check The Docs

- [X] I double checked the docs and couldn't find any useful information.

### Verify Issue Source

- [X] I verified the issue was caused by Discord.Net.

### Check your intents

- [X] I double checked that I have the required intents.

### Description

When using the new Clyde Discord AI, it causes a crash. It happens 100% of the time without fault.

I think it's a problem internally and has nothing to do with my code, everything was working fine *until* Clyde got added to our Discord server.

I'm also using all intents and they're all checked on the bot dev portal.

Short video showing off the bug: https://youtu.be/Fv6y7grYI1w

### Version

Custom fork that was just merged & tested with latest Git push. (The changes I made are irrelevant to the problem anyway.)

### Logs

System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=Discord.Net.WebSocket
  StackTrace:
   at Discord.WebSocket.SocketGuild.AddOrUpdateUser(GuildMember model) in \Discord.Net\src\Discord.Net.WebSocket\Entities\Guilds\SocketGuild.cs:line 1152

Call Stack shown off by Visual Studio:
![](https://cdn.discordapp.com/attachments/1091843077230051479/1096560249755934773/image.png)

### Packages

DotNetEnv 2.5.0
HtmlAgilityPack 1.11.46
Microsoft.Extentions.Configuration 7.0.0
Microsoft.Extentions.Configuration.EnvironmentVariables 7.0.0
Microsoft.Extentions.Configuration.FileExtentions 7.0.0
Microsoft.Extentions.DependencyInjection 7.0.0
Microsoft.Extentions.DependencyInjection.Abstractions 7.0.0
NetEscapades.Configuration.Yaml 2.2.0
Newtonsoft.Json 13.0.2
YoutubeExplode 6.2.10

**Comment by markski1** [comment]
Very strange, I am guessing because Clyde is technically not a registered discord user the framework might not be sure what to do as far as reporting it's actions go?

Either way, it looks like checking for `model` not being null and ignoring if that's the case should stop your crashes until the issue is fixed. Wish I could test this myself but Clyde has not been enabled on any of my servers

**Comment by Talan122** [comment]
Yea I did find out like 20 minutes after posting that it was the debugger pausing on the error, wasn't actually a crash... oops (and I forgot to update this issue). Should still be fixed at some point though. Its also throwing it when Clyde starts typing and not on him sending a message.. which is weird.

Going to change the name to reflect that.
