### ISSUE TITLE
[Question]: Reading an Audio-Stream

### ISSUE THREAD

**Issue by Nekonika** [RogueException/Discord.Net#2672]
Hello everyone,

I've been struggeling with this for a while now, but I am just unable to find any documentation or resources about what I want to do:
I am trying to get my bot to "be able to hear".

This is what I've done so far:
```cs
IAudioClient? AudioClient = await VoiceChannel.ConnectAsync();
AudioClient.StreamCreated += (ulong userId, AudioInStream stream) =>
{
    Task.Run(async () =>
    {
        byte[] Buffer = new byte[4096];
        await stream.ReadAsync(Buffer);

        // do amazing stuff with the captured data
    });
}
```

The event triggers as soon as someone in the channel starts talking, but `ReadAsync()` would just block and never return.
My question is: How would I read data from the AudioInStream? Do I have to use a certain OAuth-Option to be able to "hear" using the bot?

Just a hint about what I could be doing wrong would be great.
Thank you in advance ^^

**Comment by Nekonika** [comment]
Sorry for my ignorance.
I've found the issue.

I was used to just reading from Streams and totally forgot about it being a 'livestram'.

Using the method  `AudioInStream.ReadFrameAsync()` / `AudioInStream.TryReadFrame()` resolved the problem 👍.

In the end, it's always about reading the docs, huh 😆...

**Comment by jacob7395** [comment]
I'm still missing something, maybe I'm missing permissions?

If I use TryReadFrame, it returns but there is never any payload.

What documentation are you looking at?

Maybe my client is not configured properly...
```c#
_client = new DiscordSocketClient(new DiscordSocketConfig()
{
    GatewayIntents = GatewayIntents.AllUnprivileged | GatewayIntents.MessageContent,
    AlwaysDownloadUsers = true,
});

Task ConnectToVoice(SocketVoiceChannel voiceChannel)
{
    if (voiceChannel == null)
        return Task.CompletedTask;

    _ = Task.Run(async () =>
    {
        try
        {
            Console.WriteLine($"Connecting to channel {voiceChannel.Id}");
            _audioClient = await voiceChannel.ConnectAsync();
            _audioClient.StreamCreated += AudioClient_StreamCreated;
            Console.WriteLine($"Connected to channel {voiceChannel.Id}");
        }
        catch (Exception e)
        {
            Console.WriteLine(e);
            throw;
        }
    });
    return Task.CompletedTask;
}

Task AudioClient_StreamCreated(ulong userId, AudioInStream stream)
{
    Task.Run(() =>
    {
        while (true)
        {
            stream.TryReadFrame(token, out RTPFrame frame);

            if (frame.Payload is { })
            {
                _waveWriter?.Write(frame.Payload);
            }
        }
        return Task.CompletedTask;
    });

    return Task.CompletedTask;
}
```
