### ISSUE TITLE
[Bug]: InvalidOperationException in IDiscordInteraction.RespondAsync (New Issue)

### ISSUE THREAD

**Issue by Sasino97** [RogueException/Discord.Net#2685]
### Check The Docs

- [X] I double checked the docs and couldn't find any useful information.

### Verify Issue Source

- [X] I verified the issue was caused by Discord.Net.

### Check your intents

- [X] I double checked that I have the required intents.

### Description

It was working fine until earlier today: it stopped working with no code change at all. I have updated to the very latest Discord.Net Nuget package (3.10.0), and the issue still occurs, so I assume that something has changed in Discord's API.

### Version

3.10.0

### Working Version

3.10.0

### Logs

```
An exception of type System.InvalidOperationException has occurred. Stack trace:
   at Discord.WebSocket.SocketCommandBase.RespondAsync(String text, Embed[] embeds, Boolean isTTS, Boolean ephemeral, AllowedMentions allowedMentions, MessageComponent components, Embed embed, RequestOptions options)
   at Discord.WebSocket.SocketInteraction.Discord.IDiscordInteraction.RespondAsync(String text, Embed[] embeds, Boolean isTTS, Boolean ephemeral, AllowedMentions allowedMentions, MessageComponent components, Embed embed, RequestOptions options)
   at Gtacnr.DiscordBot.Global.RespondWithEmbedAsync(IDiscordInteraction interaction, String message, Nullable`1 color, Boolean ephemeral) in C:\Users\Sal\Workspace\Sasinosoft\GTACNR\gta-cnr\discord-bot\Global.cs:line 137
   at Gtacnr.DiscordBot.Moderation.TestCommand.HandleTestSlashCommand(IDiscordInteraction interaction) in C:\Users\Sal\Workspace\Sasinosoft\GTACNR\gta-cnr\discord-bot\TestCommand.cs:line 42
   at Gtacnr.DiscordBot.Services.DiscordInteractionHandler.<>c__DisplayClass7_0.<<ExecuteCommand>b__0>d.MoveNext() in C:\Users\Sal\Workspace\Sasinosoft\GTACNR\gta-cnr\discord-bot\Services\DiscordInteractionHandler.cs:line 124
```

### Sample

Code that causes it

```csharp

        public static async Task RespondWithEmbedAsync(this IDiscordInteraction interaction, string message, Color? color = null, bool ephemeral = false)
        {
            var embed = new EmbedBuilder()
                .WithDescription(message)
                .WithColor(color ?? Color.Red)
                .Build();
            
            await interaction.RespondAsync(embed: embed, ephemeral: ephemeral);
        }
```

I have also tried without embed, same result:

```csharp
        public static async Task RespondWithEmbedAsync(this IDiscordInteraction interaction, string message, Color? color = null, bool ephemeral = false)
        {
            //var embed = new EmbedBuilder()
            //    .WithDescription(message)
            //    .WithColor(color ?? Color.Red)
            //    .Build();
            //
            //await interaction.RespondAsync(embed: embed, ephemeral: ephemeral);

            await interaction.RespondAsync(message);
        }
```

### Packages

```
Dapper 2.0.123
Discord.Net 3.10.0
Discord.Net.Commands 3.10.0
Discord.Net.Core 3.10.0
Discord.Net.Interactions 3.10.0
Discord.Net.Rest 3.10.0
Discord.Net.Webhook 3.10.0
Discord.Net.WebSocket 3.10.0
Microsoft.Extensions.Configuration 7.0.0
Microsoft.Extensions.Configuration.Binder 7.0.4
Microsoft.Extensions.Configuration.FileExtensions 7.0.0
Microsoft.Extensions.Configuration.Json 7.0.0
Microsoft.Extensions.DependencyInjection 7.0.0
MySqlConnector 2.2.6
Newtonsoft.Json 13.0.3
```

**Comment by Misha-133** [comment]
The exception thrown should also have a `Message` property
Could you post the message here?

**Comment by Sasino97** [comment]
> The exception thrown should also have a `Message` property Could you post the message here?

The error message is: `Interaction token is no longer valid`

**Comment by Sasino97** [comment]
The "no longer valid" suddenly reminded me that I have messed with my dedicated server's date/time settings (to match another server of mine in another region). However, even after matching the time with the real world time, the issue persists
![image](https://github.com/discord-net/Discord.Net/assets/17410173/0a709e41-3ac1-4a66-8eab-e8db618dfb65)

**Comment by Sasino97** [comment]
Update: I have set everything to automatic (time & time zone), and made sure the time matches the real time of the region, I have logged out of Windows and logged back in, however the issue is still there. I have also updated the logger so that it shows the exception message, just to make 100% sure. Here's a screenshot:
![image](https://github.com/discord-net/Discord.Net/assets/17410173/43dec55e-c5ba-4817-872d-227d8377eceb)

**Comment by Sasino97** [comment]
I studied the Discord.NET source code and found the solution:

```csharp
UseInteractionSnowflakeDate = false
```

In the `DiscordSocketConfig`.

If anyone else is wondering: if you change your computer date and time, you need to set that to false otherwise the "DateTime.UtcNow" won't match the snowflake correctly.
