### ISSUE TITLE
Few changes to support mono

### ISSUE THREAD

**Issue by moile666** [RogueException/Discord.Net#2691]
### Discussed in https://github.com/discord-net/Discord.Net/discussions/2690

<div type='discussions-op-text'>

<sup>Originally posted by **moile666** June  2, 2023</sup>
Hi everyone,

I wanted to use Discord.Net on my NAS, running on mono.
I saw it was not supported so I builded it myself.
I had to make 2 small changes in source to make it work : 

class DefaultRestClient :
```
//var content = new MultipartFormDataContent("Upload----" + DateTime.Now.ToString(CultureInfo.InvariantCulture));
var content = new MultipartFormDataContent("Upload----" + DateTimeOffset.UtcNow.ToUnixTimeSeconds());
```
because spaces are not supported in boundary argument.

class RequestQueue, method EnterGlobalAsync :
```
        internal async Task EnterGlobalAsync(int id, RestRequest request)
        {
            //int millis = (int)Math.Ceiling((_waitUntil - DateTimeOffset.UtcNow).TotalMilliseconds);
            double millis = Math.Ceiling((_waitUntil - DateTimeOffset.UtcNow).TotalMilliseconds);
            if (millis > 0)
            {
#if DEBUG_LIMITS
                Debug.WriteLine($"[{id}] Sleeping {millis} ms (Pre-emptive) [Global]");
#endif
                //await Task.Delay(millis).ConfigureAwait(false);
                await Task.Delay((int)millis).ConfigureAwait(false);
            }
        }
```

because, the cast makes the app wait for a long long time (like forever).

These changes are not breaking other stuff (I guess) and could probably be integrated for mono users.

Regards,

</div>

**Comment by Misha-133** [comment]
As @Hawxy has already noted in the discussion - you can use .NET Core or .NET6+ to get the app running on linux/macos ([full list of supported platforms](https://github.com/dotnet/core/blob/main/release-notes/6.0/supported-os.md))

Also, we are going to drop .NET framework support in DNet v4, so these changes do not make that much sense. We *can* include these if it doesn't cause anything to break but I doubt we will

**Comment by moile666** [comment]
Ok, thanks for the reply.
