### ISSUE TITLE
[Bug]: New usernames are displayed with #0000 discriminator

### ISSUE THREAD

**Issue by gepbird** [RogueException/Discord.Net#2693]
### Check The Docs

- [X] I double checked the docs and couldn't find any useful information.

### Verify Issue Source

- [X] I verified the issue was caused by Discord.Net.

### Check your intents

- [X] I double checked that I have the required intents.

### Description

When I convert a SocketUser (who got the new, discriminatorless username) to a string, there is `#0000` at the end.

### Version

3.10.0

### Sample

```cs
SocketUser user; // assume this an account with the new username
Console.WriteLine(user.ToString()); // someone#0000
```

**Comment by Anu6is** [comment]
The #0 discriminator is provided by Discord temporarily until all user names have been updated.

**Comment by OldVamp** [comment]
please also be sure display names contain capital letters

**Comment by gepbird** [comment]
https://github.com/discord-net/Discord.Net/pull/2696 will close this issue.
