### ISSUE TITLE
Any way to access the legacy Discord/Name-Tag?

### ISSUE THREAD

**Issue by 3HMonkey** [RogueException/Discord.Net#2734]
Is there any way to access the "old" Discord username ("originally known as...") programmically?

![image](https://github.com/discord-net/Discord.Net/assets/4610892/95dfba2f-fb39-4a82-9d65-0d5a07822ba3)

thx for helping.

**Comment by Misha-133** [comment]
Nope, that info is not accessible by bots.

**Comment by Panthr75** [comment]
Same thing goes for `bio`s of users, `pronouns`, and any badge they could potentially have. All of them are served via the `/users/{userID}/profile` endpoint, which isn't available to bots sadly...

**Comment by 3HMonkey** [comment]
Thx for the reply. Is there any endpoint we can reach out collecting this information?

**Comment by Panthr75** [comment]
See [an issue raised by someone on the official api documentation](https://github.com/discord/discord-api-docs/discussions/6308)
