### ISSUE TITLE
Hide slash command from user

### ISSUE THREAD

**Issue by drizzle-mizzle** [RogueException/Discord.Net#2740]
Is there way to hide slash command from some user/role so it could not be seen at all?
I found this closed issue #2172 and there was said that Discord doesn't support it yet, but I know it does in the current moment, so, is there way to do it with Discord.Net now, or it's not yet implemented?

**Comment by drizzle-mizzle** [comment]
To be precise, I want to hide a command from `@everyone` and allow it to be seen only from a certain user.

**Comment by Misha-133** [comment]
That could be done in server settings => integrations tab => edit command permissions.
As a bot developer you can only set the default guild permission required to see/execute the command, unless you setup oauth for you app, use that to get a bearer token from a user with perms in the guild to change command permissions & edit ones for the command.

**Comment by drizzle-mizzle** [comment]
> That could be done in server settings => integrations tab => edit command permissions

Yep, that is what I'm talking about. I know there's no way to set the view permission for the command itself, but what if my bot has already joined the guild and got `ManageGuild` permission? It should be able to do the same thing then somehow, but I couldn't figure out how to actually do it.

**Comment by Misha-133** [comment]
As I said - it's not possible to do with a bot application.
Read the warning in the docs for [the endpoint](https://discord.com/developers/docs/interactions/application-commands#edit-application-command-permissions)

> This endpoint requires authentication with a Bearer token that has permission to manage the guild and its roles.

**Comment by drizzle-mizzle** [comment]
Oh, I see. I thought that you meant it as an option to get this permission, and that maybe just a *bot permission* itself would be equal for the token with it, but apparently it's not.
Thanks for your time.
