### ISSUE TITLE
[Bug]: IChannel.GetUsersAsync doesn't return users in voice chat

### ISSUE THREAD

**Issue by AracKnight** [RogueException/Discord.Net#2772]
### Check The Docs

- [X] I double checked the docs and couldn't find any useful information.

### Verify Issue Source

- [X] I verified the issue was caused by Discord.Net.

### Check your intents

- [X] I double checked that I have the required intents.

### Description

I try to check, if there are currently users in a given voice channel.
To do so I call the GetUsersAsync() function:
`var users = await channel.GetUsersAsync().FlattenAsync();`

But although there are currently two users in this channel, it returns an empty list.

### Version

3.12.0

### Logs

```cs
IAsyncEnumerable<IReadOnlyCollection<IGuildUser>> IGuildChannel.GetUsersAsync(
      CacheMode mode,
      RequestOptions options)
    {
      return AsyncEnumerable.Empty<IReadOnlyCollection<IGuildUser>>();
    }
```
This is the implementation that I can see in my debugger.

### Sample

```cs
// I create a room triggered by a command
private async Task<RestVoiceChannel> CreateRoom(IEnumerable<ulong> users)
    {
        var guild = _client.GetGuild(<myGuildId>);
        if (guild == null)
            throw new ArgumentException("Guild was null");
        var permissions = new OverwritePermissions(viewChannel: PermValue.Allow, connect: PermValue.Allow);
        var voiceChannel = await guild.CreateVoiceChannelAsync(name);foreach (var id in users)
        {
            var user = guild.GetUser(id);
            await voiceChannel.AddPermissionOverwriteAsync(user, permissions);
        }
        StartCancellationTimer(voiceChannel);
        return voiceChannel;
    }

//If the table is not used for an amount of time i want to delete it, so I start a timer to check in x seconds
private void StartCancellationTimer(IGuildChannel channel)
    {
        Task.Run(() =>
        {
            _ = new Timer(DeleteChannelIfUnused, channel, CheckForChannelDeletionInterval, Timeout.Infinite);
            Thread.Sleep(CheckForChannelDeletionInterval + 1000*60);
        });
    }

// check if there are people in the channel and if not remove it
private async void DeleteChannelIfUnused(object? channelObject)
    {
        if (channelObject is not IGuildChannel channel)
        {
            _logger.Error("Not a valid channel object");
            return;
        }

        var users = await channel.GetUsersAsync().FlattenAsync();
        if (users.Any())
        {
            StartCancellationTimer(channel);
            return;
        }

        try
        {
            RemoveChannel(channel);
            return;
        }
        catch (Exception e)
        {
            _logger.Error(e);
        }
        
        StartCancellationTimer(channel);
    }
```

### Packages

MySqlData 8.1.0
NLog 5.2.3
dotenv.net 3.1.2

### Environment

- **OS** Win10 Home 22H2
- **Architecture** 64bit
- **NET SDK** 6.0

**Comment by Misha-133** [comment]
`SocketVoiceChannel.GetUsersAsync()` returns only cached users; if no users are cached - the method would return an empty collection. That's most likely the issue you're experiencing.
And aside from this - this wouldn't work out for you anyway, as the `GetUsersAsync` returns all users who can see the channel. To get connected users you can only use the `SocketVoiceChannel.ConnectedUsers` property

**Comment by Misha-133** [comment]
Closing due to lack of followup.
