### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Draco18s** [RogueException/Discord.Net#2816]
### Check The Docs

- [X] I double checked the docs and couldn't find any useful information.

### Verify Issue Source

- [X] I verified the issue was caused by Discord.Net.

### Check your intents

- [X] I double checked that I have the required intents.

### Description

Sending a message with the MessageFlag.Ephemeral results in no apparent message being sent.

I have included an `AllowedMentions` object as well as a `MessageReference` object but in neither case does the ephemeral message show up for me.

### Version

3.10.0

### Logs

```shell
N/A
```

### Sample

```csharp
	public Task GetSettings()
	{
		AllowedMentions mentions = new AllowedMentions(AllowedMentionTypes.Users)
		{
			UserIds = new List<ulong>()
			{
				Context.Message.Author.Id
			}
		};
		Context.Channel.SendMessageAsync("This is an ephemeral message response", false, null, 
				null, mentions, new MessageReference(Context.Message.Id), null, null, 
				null, MessageFlags.Ephemeral);
		return Task.CompletedTask;
	}

### Packages

CSharpDiscordWebhook (2.7.1)
Microsoft.ClearScript.V8 (7.4.4)
System.Data.SQLite (1.0.117)
World2vec.Tools (2.1.0)

### Environment

- **OS:** Windows 10
- **Architecture:** x86
- **SDK:**  .NET 7.0

**Comment by Misha-133** [comment]
This is not a bug. It's not possible to send a message with an `Ephemeral` flag. It's only used when responding to an interaction ephemerally.

**Comment by Draco18s** [comment]
Alright, then how am I supposed to use it so I can send an ephemeral message to a single user?

**Comment by Misha-133** [comment]
You can't. 
You can only do this in response to an interaction, using `DeferAsync`, `RespondAsync` or `FollowupAsync` & setting `ephemeral: true`

**Comment by Draco18s** [comment]
Ah I see, that's unfortunate. I tried messing around with slash commands that're integrated rather than text-parsed, but never got them to register (Discord's docs say they don't show up immediately, but they never showed up at all).

Oh well.
