### ISSUE TITLE
[Bug]: Slash Commands not registering

### ISSUE THREAD

**Issue by Wqffles-com** [RogueException/Discord.Net#2817]
### Check The Docs

- [X] I double checked the docs and couldn't find any useful information.

### Verify Issue Source

- [X] I verified the issue was caused by Discord.Net.

### Check your intents

- [X] I double checked that I have the required intents.

### Description

My slash commands aren't registering, despite the "await _interactionService.RegisterCommandsGloballyAsync();" and await "_interactionService.AddModuleAsync<SlashCommandModule>(_serviceProvider);"

### Version

3.13.0

### Logs

```shell
[General/Info] 20:22:23 Discord     Discord.Net v3.13.0 (API v10)
[General/Info] 20:22:23 Gateway     Connecting
[General/Warning] 20:22:24 Gateway     You're using the GuildScheduledEvents gateway intent without listening to any events related to that intent, consider removing the intent from your config.
[General/Warning] 20:22:24 Gateway     You're using the GuildInvites gateway intent without listening to any events related to that intent, consider removing the intent from your config.
[General/Info] 20:22:24 Gateway     Connected
[General/Verbose] 20:22:25 Interaction Registering commands globally...
[General/Verbose] 20:22:25 Interaction Registered commands globally!
[General/Info] 20:22:25 Gateway     Ready
```

### Sample

```cs
 _client.Ready += async () =>
        {
            await _interactionService.AddModuleAsync<SlashCommandModule>(_serviceProvider);
            if (ConfigService.Production)
            {
                await LoggingService.LogAsync(new LogMessage(LogSeverity.Verbose, "Interactions",
                                "Registering commands globally..."));
                await _interactionService.RegisterCommandsGloballyAsync();
                await LoggingService.LogAsync(new LogMessage(LogSeverity.Verbose, "Interactions",
                                "Registered commands globally!"));
            }
            else
            {
                await LoggingService.LogAsync(new LogMessage(LogSeverity.Verbose, "Interactions",
                                "Registering commands to guild..."));
                await _interactionService.RegisterCommandsToGuildAsync(ConfigService.GuildId);
                await LoggingService.LogAsync(new LogMessage(LogSeverity.Verbose, "Interactions",
                                "Registered commands to guild!"));
            }
        };
```

```cs
public class SlashCommandModule : InteractionModuleBase
{
    [SlashCommand("echo", "Echo an input")]
    public async Task Echo(string input)
    {
        await RespondAsync(input);
    }
}
```

### Packages

Microsoft.Extensions.DependencyInjection 8.0.0

### Environment

- **OS**: Windows 11 23H2
- **Arch**: x64
- **.NET**: 7.0.311
- **SDK**: 7.0.305, 7.0.306, 7.0.311

**Comment by Misha-133** [comment]
Hmm, the code looks ok
- Could you check with the debugger if the `_interactionService.Modules` contains the module after running `AddModuleAsync`?
- Make sure you've added the app with the `applications.commands` scope (technically it's not required but just to make sure)
- Look in server settings => integrations tab => you app & see if the command is listed there

**Comment by Wqffles-com** [comment]
I see it's registered under "Integrations -> BlahajBot", but I can't run it.
EDIT: Image https://cdn.discordapp.com/attachments/1185322267660525581/1190379906492809236/image.png?ex=65a196ad&is=658f21ad&hm=b8c86ede03eac070cc77c59be57dd60153ea30f9efaccccd927e1067a3fdec8e&
EDIT 2: forgot the ping @Misha-133

**Comment by Misha-133** [comment]
No need to ping me😅

Well the command does actually get registered then...
- do you have admin perms in that guild?
- try creating perm overwrite for the command in guild settings
- try reloading your client (Ctrl+R)
- try adding a `[DefaultMemberPermissions(GuildPermission.ViewChannel)]` attribute on the command (and registering it again ofc)

**Comment by Wqffles-com** [comment]
The [DefaultMemberPermissions] worked, thanks!
