### ISSUE TITLE
Please help

### ISSUE THREAD

**Issue by G0Shark** [RogueException/Discord.Net#2824]
Hello everyone, i have a problem
I need to check user roles in DM context, i know thats `command.User as IGuildUser` dont work, but maybe i have way to fix it? (like getting user by channel.GetUserAsync(), or anything else)
Im realy need this, please help

**Comment by Anu6is** [comment]
If you are interacting with the user via direct messages, they aren't associated to a specific guild so there is no way to check roles. 
If the bot is only in one guild or you know which guild you are checking roles for then you can get the user from the guild (i.e. Guild.GetUserAsync())

**Comment by G0Shark** [comment]
> If you are interacting with the user via direct messages, they aren't associated to a specific guild so there is no way to check roles. If the bot is only in one guild or you know which guild you are checking roles for then you can get the user from the guild (i.e. Guild.GetUserAsync())

I use this, now visual studio dont saying about null reference, but it still dont works
`var user = client.GetGuild(1160613815877115934).GetUser(command.User.Id);
var role = (user as IGuildUser).Guild.Roles.FirstOrDefault(x => x.Name == "Участник");
if (user.Roles.Contains(role))
{
    await command.User.SendMessageAsync("пон");
}` script

A SlashCommandExecuted handler has thrown an unhandled exception.:
System.NullReferenceException: Object reference not set to an instance of an object.
   at Discord.Program.SlashCommandHandler(SocketSlashCommand command) in C:\Users\G0Shark_\source\repos\Discord\Discord\Program.cs:line 76
   at Discord.EventExtensions.InvokeAsync[T](AsyncEvent`1 eventHandler, T arg)
   at Discord.WebSocket.DiscordSocketClient.TimeoutWrap(String name, Func`1 action) error code (in logs)

**Comment by G0Shark** [comment]
Okay, i fix it, if anyone have this problem - add all GatewayIntents to your bot

**Comment by Anu6is** [comment]
That is **not** a solution. You should never have to add **all** intents. 
Add only the intents that you need... likely in this case you want the guild members intent
