### ISSUE TITLE
[Bug]: CreateTextChannelAsync/CreateGuildChannelAsync throws a NullReferenceException if Topic is set to null

### ISSUE THREAD

**Issue by BobVul** [RogueException/Discord.Net#2840]
### Check The Docs

- [X] I double checked the docs and couldn't find any useful information.

### Verify Issue Source

- [X] I verified the issue was caused by Discord.Net.

### Check your intents

- [X] I double checked that I have the required intents.

### Description

`DiscordRestApiClient.CreateGuildChannelAsync` as called via `SocketGuild.CreateTextChannelAsync` throws a `NullReferenceException` if `Topic` is set to `null`. Looks like it's being thrown by a precondition check at https://github.com/discord-net/Discord.Net/blob/89efe0f3add3eee046ab3c8051652d8998746389/src/Discord.Net.Rest/DiscordRestApiClient.cs#L374

This goes against the xmldoc of `TextChannelProperties.Topic`, which specifies:

> Setting this value to any string other than `null` or `String.Empty` will set the channel topic or description to the desired value.

Additionally this prevents trivial round-tripping since fetching `Topic` from an existing channel can return `null` if it is empty.

While this is easy enough to fix in calling code by adding a special case (e.g. `Topic = Topic ?? Optional<string>.Unspecified`), it currently feels like a D.Net bug and makes the issue difficult to track down since it throws a raw NRE without specifying which parameter is causing it.

Preferably I think D.Net should treat `null` the same as `Unspecified` here and just ignore it.

### Version

3.12.0

### Logs

```shell
-
```

### Sample

```csharp
var newChannel = await guild.CreateTextChannelAsync("test-channel", properties =>
{
    properties.Topic = null;
})
```

### Packages

-

### Environment

-

**Comment by Misha-133** [comment]
> This goes against the xmldoc of `TextChannelProperties.Topic`, which specifies:
> `Setting this value to any string other than null or `String.Empty` will set the channel topic or description to the desired value.`

 It does indeed. I will look into this
