### ISSUE TITLE
Can't install Discord.Net 1.0.0-beta-00417 beta

### ISSUE THREAD

**Issue by valli308** [RogueException/Discord.Net#289]
Whenever I try to install the Discord.NET 1.0 beta from the NuGet Package Manager I get the Error "Error Could not install package 'Discord.Net 1.0.0-beta-00417'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5.2', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author. "

Any Solution for the probem?

**Comment by khionu** [comment]
Discord.Net 1.0 is in Beta and is not ready for general use. You should use 0.9.

If you're still determined, read the Readme on the Dev Branch, there are installation instructions there. Discord.Net 1.0 requires 4.6.X+ or .NET Core 1.0
