### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by rossisdead** [RogueException/Discord.Net#2891]
### Check The Docs

- [X] I double checked the docs and couldn't find any useful information.

### Verify Issue Source

- [X] I verified the issue was caused by Discord.Net.

### Check your intents

- [X] I double checked that I have the required intents.

### Description

I have a very basic slash command that has been working fine for months on version 3.12.1 that has suddenly stopped working, even though there hasn't been any changes to the code. Even stripping it down to just the sample code still gives me this error.

The Console.WriteLine call I pulled in from what's being checked in the DeferAsync command before throwing that exception. On my end, I'm seeing anywhere from a 6 to 20 second difference between UtcNow and CreatedAt, except there's not an actual 20 second delay between me entering the command on Discord and it reaching my bot. It's practically instantaneous for that. 

I'm running this on Windows 11. I thought this may have been related to windows update KB5035853, but uninstalling that has had no effect.

Upgrading to Discord.Net 3.14.1 didn't make a difference.

### Version

3.14.1

### Logs

```shell
Not much applicable here.

Stack trace:
   at Discord.WebSocket.SocketCommandBase.<DeferAsync>d__20.MoveNext()
   at Bot.PictureGeneratingCommands.<GeneratePicture>d__4.MoveNext()
```

### Sample

```cs 
[SlashCommand("picture", "Generates a picture for you!", runMode: RunMode.Async)]
public async Task GeneratePicture(
    [Summary(description: "Prompt used to generate an image. Leave blank to see a random one.")]
    string? prompt = null)
{
    Console.WriteLine((DateTime.UtcNow - Context.Interaction.CreatedAt).TotalSeconds);
    await DeferAsync(false, new RequestOptions { Timeout = 60000 });
}```

### Packages

Not applicable

### Environment

OS: Windows 11 Pro Version 10.0.22621 Build 22621
.NET 7.0
x64

**Comment by PhantomX48** [comment]
Make sure your computer's clock is synced.

**Comment by rossisdead** [comment]
> Make sure your computer's clock is synced.

That was it! Apparently something got screwed up for me and syncing stopping happening a few days ago. Thank you!

**Comment by PhantomX48** [comment]
Nice! I had the same thing happen to me literally yesterday!
