### ISSUE TITLE
Audio Volume setting?

### ISSUE THREAD

**Issue by jilleJr** [RogueException/Discord.Net#293]
I tried out the audio module, and hooked it up to play some mp3 files via `IAudioClient.Send()`, all well and good. Now how I understand it your Send method just adds the bytes to a queue that gets handled by another process.  
I have little to none experience with sound programming, but I need to change the volume of the sound I am sending.

As far as I understand my options are:  
- Making my own streaming code (like your [VoiceBuffer.cs](https://github.com/RogueException/Discord.Net/blob/master/src/Discord.Net.Audio/VoiceBuffer.cs)? I've no idea how this system works so really need to research it I guess...)  
- Possibility that you may implement this, where you have a public variable or so that changes the volume for the outgoing traffic?

Apologies if such a feature already exists, but for such a noob sound-programmer as I, it's very difficult to know what to even search for while researching.

Thanks,
Kalle

**Comment by khionu** [comment]
This is what we recommend in the Support Channel
http://hastebin.com/umapabejis.cs

**Comment by jilleJr** [comment]
Oh yes that worked perfectly! Thanks! 😸

**Comment by Pdzly** [comment]
> This is what we recommend in the Support Channel
> http://hastebin.com/umapabejis.cs

Could you reupload? Thanks!
