### ISSUE TITLE
There is no API to get user's banner

### ISSUE THREAD

**Issue by FireNameFN** [RogueException/Discord.Net#2960]
There is one CDN method `GetUserBannerUrl()`, but it requires bannerId to get banner URL.
`SocketUser` doesn't have `GetBannerUrl()` or `BannerId`.

I checked it on version 3.15.2.

By the way Discord.Net-Labs had these methods. Added in https://github.com/Discord-Net-Labs/Discord.Net-Labs/pull/81.

**Comment by Misha-133** [comment]
That is correct, banner property & method are only available on the `RestUser`. Banner hash is not serialized in user objects sent over gateway.

**Comment by FireNameFN** [comment]
But you have added this API in one of latest commits.
https://github.com/discord-net/Discord.Net/commit/57eb906552c9854049280c14a6565a8d2c8a3700
