### ISSUE TITLE
There is no API to mute or deaf members

### ISSUE THREAD

**Issue by FireNameFN** [RogueException/Discord.Net#2961]
`SocketUser` has `IsMuted` and `IsDeafened` as read only properties.
There is no way to set mute or deaf.
Discord doesn't give API to mute and deaf `SocketUser`, but there is a way to mute and deaf guild members.
https://discord.com/developers/docs/resources/guild#modify-guild-member

Checked on version 3.15.2.

**Comment by exsersewo** [comment]
`SocketUser` does not expose `IsMuted` or `IsDeafened`. `SocketGuildUser` does, and contains a method called `ModifyAsync`. You can then set the `Mute`/`Deaf` properties of `GuildUserProperties`.

I.e.
```cs
var guild = socketClient.GetGuild(123);
var guildUser = guild.GetUser(456);

await guildUser.ModifyAsync(props => {
    props.Deaf = true;
    props.Mute = true;
});
```
