### ISSUE TITLE
Q: About Ready event state

### ISSUE THREAD

**Issue by mwpowellhtx** [RogueException/Discord.Net#2984]
Question about the reporting for the `Ready` event. Is it once `Ready` always `Ready`? Or can it report multiple times? Reason being, I'd like to signal within my `IDiscordService` when it is such. Maybe using a full `Semaphore` initially, then once `Ready`, `Semaphore.Release()`. Might there be a better gauge as to _"readiness"_, or is that generally it? Thanks...

**Comment by Quahu** [comment]
`Ready` can trigger multiple times. It will trigger every time your client has to reconnect and doesn't resume, but establishes a new gateway session.

As for signaling it, [`TaskCompletionSource<T>`](https://learn.microsoft.com/en-us/dotnet/api/system.threading.tasks.taskcompletionsource-1) or its non-generic variant would be better fit for this.

**Comment by mwpowellhtx** [comment]
Um okay... I am not familiar with that construct. How does it apply? I want to gauge is the client _"ready"_ sufficiently that I can poll for certain things, text channels, etc. Is there a 'simple' code snippet illustrating as much perhaps?

**Comment by mwpowellhtx** [comment]
In a nutshell, I'm thining _promises_ and _future_ patterns at least in [_Boost Futures_](https://boost.org/doc/libs/1_86_0/libs/fiber/doc/html/fiber/synchronization/futures.html) parlance.

**Comment by mwpowellhtx** [comment]
I'm not really sure that pattern fits the bill. There's no guarantee we would see the event triggered in a _"near term"_ time frame. What I really want is to ask for the current state of readiness. Without necessarily having to wait for a `Ready` event.

My use case is to feed my view models with things like the text channels and such like this. Maybe eventually feeding into things such as web hooks and [_Serilog_](https://github.com/serilog-contrib/Serilog-Sinks-Discord) based logging, but that's a bit more advanced use case. Initially I just want the channels.

**Comment by Quahu** [comment]
> Um okay... I am not familiar with that construct. How does it apply? I want to gauge is the client _"ready"_ sufficiently that I can poll for certain things, text channels, etc. Is there a 'simple' code snippet illustrating as much perhaps?

I assume you'd want something along the lines of:
```cs
var readyTcs = new TaskCompletionSource(TaskCreationOptions.RunContinuationsAsynchronously);

// client is DiscordSocketClient
client.Ready += () =>
{
    readyTcs.TrySetResult();
    return Task.CompletedTask;
}

// waits for the Ready event to fire
await readyTcs.Task;
```

**Comment by mwpowellhtx** [comment]
Fair enough, why doesn't a simple locked boolean work?

```csharp
bool _ready;

bool IsReady { get { lock (this) return _ready; } }

void OnClientReady()
{
    lock (this)
    {
        _ready = true;
    }
}
```

`this` being the `DiscordService`. The trick being detection when it may fall in and and out of a state of readiness. Or maybe it does not matter, or we stage some other tasked event handlers responding when ready does subsequently report, in order to message for changes and such.

There appear to be other such _updated_ events which may be more or less interesting as well, depending on how specialized we need for that refreshment to occur.

But again, not looking so much for _'ready as an event'_ so much as it being steady state, as much as it can be in an asynchronous distributed architecture.

Maybe the key is staging those messaging event handling actions ready for the ready event to fire.
