### ISSUE TITLE
Missing IGuild.GetUserAsync() method

### ISSUE THREAD

**Issue by FireNameFN** [RogueException/Discord.Net#2990]
There is no api for getting single user that doesn't exist in cache.
There is a way to download all users, but it can take too much memory.
It would be good if there was `IGuild.GetUserAsync()` method.

**Comment by Misha-133** [comment]
[`IGuild.GetUserAsync()`](https://docs.discordnet.dev/api/Discord.IGuild.html#Discord_IGuild_GetUserAsync_System_UInt64_Discord_CacheMode_Discord_RequestOptions_)

**Comment by Misha-133** [comment]
I asume that you are having this issue because this method is not public on a `SocketGuild`, but you can still cast the guild to `IGuild` and use the method this way. It's was a bad design choice IMHO, but its not gonna change until v4 comes out
