### ISSUE TITLE
Missing BulkDeleteMessages() API

### ISSUE THREAD

**Issue by FireNameFN** [RogueException/Discord.Net#2993]
There is Discord API: https://discord.com/developers/docs/resources/message#bulk-delete-messages
But there is no Discord.Net API for this.

**Comment by exsersewo** [comment]
https://docs.discordnet.dev/api/Discord.ITextChannel.html?q=deletemessagesasync#Discord_ITextChannel_DeleteMessagesAsync_System_Collections_Generic_IEnumerable_Discord_IMessage__Discord_RequestOptions_
