### ISSUE TITLE
Missing permissions on Enums

### ISSUE THREAD

**Issue by ForceFK** [RogueException/Discord.Net#2998]
Checking the permissions I noticed that some are missing that are present in the [API documentation](https://discord.com/developers/docs/topics/permissions#permissions), could someone who is familiar with this part update?

`CREATE_EVENTS`
`USE_EXTERNAL_SOUNDS`

**Comment by Misha-133** [comment]
>`CreateEvents` 

that is not correct, it's present in the lib - https://github.com/discord-net/Discord.Net/blob/dev/src/Discord.Net.Core/Entities/Permissions/ChannelPermission.cs#L179

> `USE_EXTERNAL_SOUNDS` 

it is/was going to be shipped with the soundboard support
i will probably add it separetly

**Comment by ForceFK** [comment]
> that is not correct, it's present in the lib - https://github.com/discord-net/Discord.Net/blob/dev/src/Discord.Net.Core/Entities/Permissions/ChannelPermission.cs#L179

Correct me if I'm wrong, but shouldn't `CreateEvents` also be present in `GuildPermission`?

**Comment by Misha-133** [comment]
hm yeah, that is correct
