### ISSUE TITLE
Doesn't run under Windows 7 due to ClientWebSocket dependency

### ISSUE THREAD

**Issue by ChaosCom** [RogueException/Discord.Net#3]
DiscordWebSocket internally uses System.Net.WebSockets.ClientWebSocket. Microsoft openly admits sabotaging their own framework by not providing the necessary "websocket.dll" dependency on Windows 7, Vista and Server 2008, thus artificially limiting it to Windows 8 and Windows Server 2012:

(from https://msdn.microsoft.com/library/system.net.websockets.clientwebsocket(v=vs.110).aspx)

Remarks
[...] the only public implementations of client and server WebSockets are supported on Windows 8 and Windows Server 2012. The class elements in the System.Net.WebSockets namespace that are supported on Windows 7, Windows Vista SP2, and Windows Server 2008 are **abstract** class elements. [...]

Any chances of dropping this dependency in favor of one of the free WebSocket implementations like

http://sta.github.io/websocket-sharp/ 
or
http://websocket4net.codeplex.com/

 (or rolling your own) and making this project available to a broader audience?

**Comment by RogueException** [comment]
Oh sorry, completely missed this issue.

We recently switched to websocket-sharp anyway due to issues using ClientWebSocket in Mono.
