### ISSUE TITLE
Add RetryMode to RequestOptions

### ISSUE THREAD

**Issue by RogueException** [RogueException/Discord.Net#300]
Should specify how to handle 502s or network outages. Can be combined with Timeout and CancelToken to continuously retry a request until timeout.

DiscordConfig could also specify the default mode for all requests? Unsure about that one.

**Comment by Auralytical** [comment]
Added by https://github.com/RogueException/Discord.Net/commit/1efcd3daf699b99330862364006ec1269f534dc7
