### ISSUE TITLE
DeleteMessagesAsync throws 'System.InvalidOperationException'

### ISSUE THREAD

**Issue by Jyrka98** [RogueException/Discord.Net#305]
"Failed to generate the bucket id for this operation"

**Comment by khionu** [comment]
We'll need a full stack for this.

**Comment by Jyrka98** [comment]
System.ArgumentOutOfRangeException occurred
  HResult=-2146233086
  Message=Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: startIndex
  ParamName=startIndex
  Source=mscorlib
  StackTrace:
       at System.Text.StringBuilder.Append(String value, Int32 startIndex, Int32 count)
  InnerException:

**Comment by RogueException** [comment]
I wasn't able to reproduce that specific exception, but please check if https://github.com/RogueException/Discord.Net/commit/30067959d74e148e35c3cce3d447b68fb2039125 resolves this.

**Comment by Jyrka98** [comment]
It still happens

**Comment by RogueException** [comment]
How about https://github.com/RogueException/Discord.Net/commit/84980ad203421f48405ebb9cbab3040b2aedebbf?

**Comment by Jyrka98** [comment]
That fixed it

**Comment by RogueException** [comment]
Awesome
