### ISSUE TITLE
Unable to use SetGame

### ISSUE THREAD

**Issue by PFCKrutonium** [RogueException/Discord.Net#31]
```
Imports Discord

Module Module1
    Dim Client As New DiscordClient
    Sub Main()

        Client.Connect("Username","Password")
        Client.SetGame("Anything")
        Console.ReadKey()
    End Sub
End Module
```
An unhandled exception of type 'System.NullReferenceException' occurred in Discord.Net.dll

Additional information: Object reference not set to an instance of an object.

Line 317 of DiscordClient.cs

**Comment by SSStormy** [comment]
Have you tried Await-ing the .Connect and .SetGame calls?

**Comment by PFCKrutonium** [comment]
Client.SetGame does not return a value, so Visual Studio will not let me await it.
