### ISSUE TITLE
Support code snippets as parameters in Discord.Net.Commands

### ISSUE THREAD

**Issue by DaZombieKiller** [RogueException/Discord.Net#325]
Currently, if a parameter such as

    `hello, i am some code`

is used, it will not yield "hello, i am some code", likewise, the following examples have the same issue

    ```C
    int x = 0;```

    ```
    hello, i am more code```

**Comment by Joe4evr** [comment]
`ParameterType.Unparsed` in 0.9, or `[Remainder]` in 1.0.

**Comment by khionu** [comment]
In 1.0, you can make your own type reader. I would strongly recommend making one for this.
It would also allow you to take advantage of the language indicator for hints to pass to your evaluator.

But anyways, the functionality of you being able to create your own Type Readers was for this very purpose, so we didn't have to cover every situation, especially when there would be difference of opinion on implementation.
