### ISSUE TITLE
Providing access to the exception that lead to failure of a command.

### ISSUE THREAD

**Issue by james7132** [RogueException/Discord.Net#335]
Right now, IResult only contains ErrorReason, which is fine when just replying in chat as to why a command failed, but makes it difficult to log actual bot errors that result from commands, especially when the error is rare. Could the exception that lead to the error be exposed in IResult?

**Comment by FiniteReality** [comment]
Cast the result to an `ExecuteResult`, which does expose the exception when a command fails to execute.

**Comment by james7132** [comment]
This should probably be documented in the guides, as it currently only shows the use of ErrorReason.

**Comment by khionu** [comment]
Anyone can contribute to the docs
