### ISSUE TITLE
SocketSelfUser.ModifyAsync fails to set avatar

### ISSUE THREAD

**Issue by aequasi** [RogueException/Discord.Net#338]
When passing a stream from downloading an image from a URL, ModifyAsync returns a `400 BadRequest` response.

**Comment by Xeevis** [comment]
+1

```
var fileStream = new FileStream(Directory.GetCurrentDirectory() + "/newAvatar.jpg", FileMode.Open);

await client.CurrentUser.ModifyAsync(x => x.Avatar = new Optional<Discord.API.Image>(new Discord.API.Image(fileStream)));
```

Fails with `The server responded with error 400 (BadRequest)`

**Comment by Sentinent** [comment]
I think it's failing because you need to pass an email and password to the gateway, but the method doesn't handle that.

**Comment by khionu** [comment]
@Sentinent Just a friendly reminder: bots don't have emails or passwords

**Comment by Jyrka98** [comment]
https://github.com/hammerandchisel/discord-api-docs/issues/169

**Comment by RogueException** [comment]
Is this fixed?

**Comment by Sentinent** [comment]
Seems to be fixed.

![image](https://cloud.githubusercontent.com/assets/14145932/20454659/f6d6e04c-adfb-11e6-9dc2-59cbd42dd466.png)

![image](https://cloud.githubusercontent.com/assets/14145932/20454658/ec045e60-adfb-11e6-8969-7d5b3be9259b.png)

Edit: Nevermind, the problem seems to be with bots.
Edit2: Seems to work with bots now.

**Comment by Scorr** [comment]
bot seems to hang on
`await Context.Client.CurrentUser.ModifyAsync(u => u.Avatar = image);`
for me. no errors or timeouts

**Comment by khionu** [comment]
@Scorr that would be a separate issue. Please open a new one.

**Comment by Auralytical** [comment]
Looks like this is resolved, closing.
