### ISSUE TITLE
GetCurrentUserAsync() no definition found

### ISSUE THREAD

**Issue by 0ffTopic** [RogueException/Discord.Net#347]
Trying to run the sample "Changing the bot's status"
`public async Task ModifyStatus()
{
    await (await _client.GetCurrentUserAsync()).ModifyStatusAsync(x =>
    {
        x.Status = UserStatus.Idle;
        x.Game = new Game("Type !help for help");
    });
}`
and I get 

'DiscordSocketClient' does not contain a definition for 'GetCurrentUserAsync' and no extension method 'GetCurrentUserAsync' accepting a first argument of type 'DiscordSocketClient' could be found (are you missing a using directive or an assembly reference?)

**Comment by Sentinent** [comment]
Use `DiscordSocketClient.CurrentUser` instead of `GetCurrentUserAsync()`.

**Comment by 0ffTopic** [comment]
But that way I can use `DiscordSocketClient.CurrentUser.ModifyAsync()` which only lets me change the Avatar and Username, not the Status.

**Comment by aequasi** [comment]
that moved, to `DiscordSocketClient.SetStatus()`. Along with `DiscordSocketClient.SetGame()`

**Comment by 0ffTopic** [comment]
Thanks
