### ISSUE TITLE
All invite metadata is zero, null, or false?

### ISSUE THREAD

**Issue by advorange** [RogueException/Discord.Net#385]
Such as in here: http://i.imgur.com/M1lUdrJ.png

Seems like only the metadata is missing; everything is zero, null, or false except the channel ID/name, the server ID/name, the code, and the URL. This is the case for three servers I've tried. The bot I am using has administrator in all three servers.

The API wrapper gets the invite information from a link like https://discordapp.com/api/invite/MBXypxb, right? Did these use to have more data and now they don't, or am I missing something on my end?

Edit: I should probably say what version I'm using: v0.9.6.

**Comment by khionu** [comment]
This isn't really a high-priority issue, if it is a valid bug, so I wouldn't expect it to be fixed before 1.0

**Comment by RogueException** [comment]
All of our effort is focused on 1.0-rc right now. We wont have time to go back and fix this, sorry.
