### ISSUE TITLE
Channel and Role implement IMentionable, but User does not.

### ISSUE THREAD

**Issue by Emzi0767** [RogueException/Discord.Net#388]
The classes `Channel` and `Role` implement the interface `IMentionable`, but the class `User` does not. Instead, it has a `Mention` property. It's an API inconsistency, which breaks certain behaviours, like picking up all mentions from a message (since `User` cannot be casted to `IMentionable`).

The issue applies to 0.9.6.

**Comment by khionu** [comment]
It is fixed in 1.0, but 0.9 is pretty much unmaintained at this point. Only critical issues will be patched.

https://github.com/RogueException/Discord.Net/blob/dev/src/Discord.Net.Core/Entities/Users/IUser.cs
