### ISSUE TITLE
You must send data by websocket after websocket is opened!

### ISSUE THREAD

**Issue by Mirageofmage** [RogueException/Discord.Net#389]
In the current version of Visual Studio for Mac, the bot is unable to connect to the discord servers and throws an exception "You must send data by websocket after websocket is opened!"

Visual Studio 7.0 (build 347)
MacBook Pro 2012 (Non-retina)

It works fine in Xamarin and I believe it might have to do with the updated .Net runtime

![screen shot 2016-11-27 at 6 04 32 pm](https://cloud.githubusercontent.com/assets/9158405/20652703/15445042-b4cc-11e6-8088-c03d14f496d5.png)

**Comment by Emzi0767** [comment]
You need to downgrade your Mono to 4.4.x.

**Comment by Mirageofmage** [comment]
Seemed to have fixed issue
