### ISSUE TITLE
Unhandled Exception: You must send data by websocket after websocket is opened! when using mono on RPi3b

### ISSUE THREAD

**Issue by GilliamJonathan** [RogueException/Discord.Net#406]
My Discord.Net is giving this error when using mono on my Raspberry Pi 3b, but not my PC

![capture](https://cloud.githubusercontent.com/assets/17790142/20952457/1cd5fb44-bbf2-11e6-9579-0115887322b0.PNG)

Any suggestions?

**Comment by samdivaio** [comment]
You're probably using mono 4.6, 
- check with `mono --version ` 
- use this guide to [downgrade mono, use snapshot if you like](https://github.com/samdivaio/NadekoBot/blob/0.9/docs/guides/Linux%20Guide.md)
- #297
