### ISSUE TITLE
Cannot edit server nickname

### ISSUE THREAD

**Issue by xXBuilderBXx** [RogueException/Discord.Net#413]
I am trying to edit the nickname of people on the server using user.nickname but this is not working on 0.9 or am i doing something wrong?

e.User.Edit(null, null, null, null ,"NewNickname");

**Comment by Emzi0767** [comment]
You need to `await` that.

**Comment by xXBuilderBXx** [comment]
Yes i have but i did not include it soz for the confusion

**Comment by khionu** [comment]
I think this can be counted as "Won't Fix", at this point
