### ISSUE TITLE
IsMuted/IsDeafened return false even when user is server muted/deafened

### ISSUE THREAD

**Issue by natekford** [RogueException/Discord.Net#414]
Using the latest dev build of the API.

User information: http://i.imgur.com/tfa7BxS.png
Clearly muted/deafened: http://i.imgur.com/eYdEuyL.png

Self muting/deafening returns true when self muted/deafened so there's no problem with those.

**Comment by RogueException** [comment]
This is a side effect of how voice states are stored internally. Looking into a better design.
