### ISSUE TITLE
Connection Lost and reconnecting every few minutes

### ISSUE THREAD

**Issue by stb109** [RogueException/Discord.Net#415]
I'm using v0.9.6 and every few minutes my bot will disconnect and reconnect. Here is some more info that another user has found out about the issue. https://i.imgur.com/LDRnLRk.png
The same person believes that the issue is around here... https://github.com/RogueException/Discord.Net/blob/master/src/Discord.Net/Net/WebSockets/GatewaySocket.cs#L34

**Comment by Auralytical** [comment]
With the approaching release of 1.0RC, it's unlikely this will be fixed.

**Comment by DusterTheFirst** [comment]
i have this issue and it really spams the console, it would be good if the bot would do this in the background or to not log it in `LogSeverity.Info`

**Comment by khionu** [comment]
@DusterTheFirst I would recommend you read the comment immediately before yours. Also, this is a Library for making Bots, among other things, not a bot in itself.
