### ISSUE TITLE
DiscordSocketClient.LoginAsync always throws rate limit exception

### ISSUE THREAD

**Issue by rexxar-tc** [RogueException/Discord.Net#448]
I'm writing a plugin for Space Engineers to bring discord chat into the game. When I upgraded to Discord.Net 1.0, my login method **always** throws a rate limit exception. Git repo https://github.com/rexxar-tc/DiscordPlugin/blob/e995635cffd0e3300e65b3162eeb53a1dfe472fd/DiscordPlugin/DiscordManager.cs#L54

I know for a fact that Discord isn't actually rate limiting me, as I tried with multiple accounts, and I also had a separate Discord bot running 0.9.5 that worked just fine.

**Comment by Auralytical** [comment]
I think I *just* pushed a fix for this. Try the latest commit/myget build.

**Comment by rexxar-tc** [comment]
Yes, it's 1.0. I tried beta 526 and it still doesn't work :(

**Comment by rexxar-tc** [comment]
Fixed in 527
