### ISSUE TITLE
Shouldn't GetMessagesAsync(N) automatically cache messages?

### ISSUE THREAD

**Issue by Xeevis** [RogueException/Discord.Net#452]
I'm developing a web widget that displays N number of last messages. When bot is restarted, to prevent widget starting empty I need to retrieve a bit of message history using 

    var messageHistory = await channel.GetMessagesAsync(50).Flatten();

Problems arise when I also want widget to support message updates and deletions. As these 50 messages will just die on `IsSpecified` being false.

    async Task Client_MessageDeleted(ulong id, Optional<SocketMessage> msg)
    {
        if (!msg.IsSpecified)
        {
            return;
        }
    }

Messages posted while bot is running are working fine so I assume GetMessagesAsync is just not caching them? Or should I take care of caching manually? How? Thank you for the help.

**Comment by Auralytical** [comment]
Yeah, GetMessagesAsync will not add the messages to cache. That could lead to a race condition with REST vs WebSocket that I don't want to touch.

The best thing to do is check the message to remove based on id, which is always provided in MessageDeleted.

**Comment by Xeevis** [comment]
I still need to know guild and channel id where that happened so I can properly broadcast the event using SignalR to relevant clients. Can always spin up an extra dictionary I guess. Thanks for the explanation.

**Comment by khionu** [comment]
That should be implemented in https://github.com/RogueException/Discord.Net/pull/395
