### ISSUE TITLE
DisconnectAsync throwing exception

### ISSUE THREAD

**Issue by SubZero0** [RogueException/Discord.Net#459]
Code:

> IAudioClient client = await channel.ConnectAsync();
> await Task.Delay(1000);
> await client.DisconnectAsync();

(already tried not awaiting DisconnectAsync())

Will throw:
> 19:36:37 Audio #1  Connecting
> 19:36:38 Audio #1  Unknown OpCode (8)
> 19:36:38 Audio #1  Connected
> 19:36:39 Audio #1  Disconnecting
> 19:36:39 Audio #1  Disconnected
> 19:36:39 Audio #1  Connection Closed:
> System.Net.WebSockets.WebSocketException: The 'System.Net.WebSockets.InternalClientWebSocket' instance cannot be used for communication because it has been transitioned into the 'Aborted' state. ---> System.Net.Http.WinHttpException: Opera├º├úo cancelada
>    --- End of inner exception stack trace ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Net.WebSockets.WinHttpWebSocket.<ReceiveAsync>d__27.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Discord.Net.WebSockets.DefaultWebSocketClient.<RunAsync>d__30.MoveNext()

The same exception happens if you try to ConnectAsync() when it's already connected.

**Comment by Auralytical** [comment]
The connection code has changed a ton since then. Feel free to reopen this if it's still an issue.
