### ISSUE TITLE
All users offline when they are online.

### ISSUE THREAD

**Issue by Kirdow** [RogueException/Discord.Net#476]
I'm making a bot for a single guild/server atm, at it seems like from yesterday the bot thinks everyone is offline. And they wont go online, I've tried restarting the bot multiple times, and I haven't changed my code in a way that would make this happen. Everytime someone send a message in the chat, I log their event.User.Status.ToString() into chat and it shows Offline nomatter what status they actually have. This is a problem as my bot provide a currency which regenerate every X seconds when a user is online, and if everyone is offline, when they are actually online, it's not really enjoyable with the users.

**Comment by khionu** [comment]
If this is 0.9, it won't be fixed. Their presence will start as offline, and be updated as you get an update from Discord.

1.0 shouldn't have this issue

**Comment by Kirdow** [comment]
1.0? Nuget tells me the latest one is 0.9.6, How do I get 1.0?

**Comment by LDSpits** [comment]
If you want to get 1.0.0. switch to the dev branch and follow the instructions on the readme. If you still have problems you can ask the guys over at the discord API server (https://discord.gg/DtHR2Aq)
