### ISSUE TITLE
Add NullableTypeReader to ParameterBuilder

### ISSUE THREAD

**Issue by SubZero0** [RogueException/Discord.Net#480]
To be able to create commands like:

```
[Command("command")]
public async Task Command(Nullable<int> number = null)
{
     if(number == null)
          //DoSomething
     //DoSomething
}
```

**Comment by FiniteReality** [comment]
We already support default values for parameters, so you should be setting that as your default value:
```cs
[Command("command")]
public async Task CommandAsync(int number = 5)
{
    await ReplyAsync($"Hello, I was given {number}.");
}
```

If you want two different things to happen when you provide an int or not, you'd be better using two different overloads:
```cs
[Command("command")]
public async Task CommandDefaultAsync()
{
    await ReplyAsync("Hello! You didn't give me any values!");
}
[Command("command")]
public async Task CommandParameterAsync(int number)
{
    await ReplyAsync($"Hello! You gave me {number}.");
}
```

**Comment by khionu** [comment]
Also, you can add support for your own TypeReaders. It's understandable to want to avoid a set number like `int.MinValue` or `int.MaxValue` as a default, so you can add a Nullable<int> TypeReader.

To learn more: https://discord.foxbot.me/docs/guides/commands.html#type-readers

**Comment by SubZero0** [comment]
@FiniteReality Hm, that's one way but I think they are ugly solutions...

@khionu Didn't know that I could add TypeReaders, will do that.
But the suggestion to add default support for Nullable for already supported Value Types still stands. It would be a nice addition.

**Comment by khionu** [comment]
Perhaps, but I'm not sure I would do that, myself. That said, not my decision.

**Comment by SubZero0** [comment]
If anyone is interested with Nullable, here is how I did it:

```
public class NullableTypeReader<T> : TypeReader
        where T : struct
{
    public delegate bool TryParse<W>(string str, out T value);
    public TryParse<T> tryParseFunc;
    public NullableTypeReader(TryParse<T> parseFunc)
    {
        tryParseFunc = parseFunc;
    }

    public override Task<TypeReaderResult> Read(ICommandContext context, string input)
    {
        T value;
        if (tryParseFunc(input, out value))
            return Task.FromResult(TypeReaderResult.FromSuccess(new Nullable<T>(value)));
        return Task.FromResult(TypeReaderResult.FromSuccess(new Nullable<T>()));
    }
}
```

And when creating your CommandService:
`commands.AddTypeReader<Nullable<int>>(new NullableTypeReader<int>(int.TryParse));`

Changing the Type and the TryParse function will do it for any structs.

Another example:
`commands.AddTypeReader<Nullable<bool>>(new NullableTypeReader<bool>(bool.TryParse));`

PS: The NullableTypeReader could be added to Discord.Net and everyone could add a new Nullable with their own struct easily.
But it's just a suggestion.

**Comment by BoGuu** [comment]
@SubZero0 You have to consider the case they have more than one nullable parameter, what if they have two int?, you can't determine which parameter they are trying to use

**Comment by khionu** [comment]
No, that's a problem with Optional Parameters, that is irrelevant to the type.

Anyone is free to make a PR. If you wish to add it as a default, feel free, however I would recommend creating each impl, yourself, rather than dropping it on the User.

**Comment by SubZero0** [comment]
@khionu I'm thinking about downloading VS 2017 to make it myself and PR but.. I can just imagine how many problems I'll face until it works (setup I meant). =P

The idea is adding the Nullables for the structs already supported by default (bool, int, float, etc).
It would be just add the NullableTypeReader (class) and add it to the TypeReader default list.
(Probably this list: https://github.com/RogueException/Discord.Net/blob/dev/src/Discord.Net.Commands/Builders/ParameterBuilder.cs#L45) (wish I could search dev branch with github to find where it goes)

I can't see why someone would create a struct if they would want to set it to null but it can happen.
So, if NullableTypeReader was already inside Discord.Net, it would be as easy as:
`commands.AddTypeReader<Nullable<MyStructType>>(new NullableTypeReader<MyStructType>(MyStructType.TryParse));`
TryParse being a method: `bool TryParse(string input, out MyStructType value)`

Someone can say: "that doesn't have any utility" but for me that's wrong. It probably doesn't have any utility for you but may have for someone else (like me).

And the library idea is to make everything easier to who's using it. The default CommandBuilder now does an awesome job, can't deny! But I think it could be better and that's a suggestion of how.

**Comment by SubZero0** [comment]
Now a PR: #484 
Closing...

**Comment by khionu** [comment]
For the record, issues aren't closed until they are resolved. Just because you made a PR doesn't mean it will be accepted. You may have changes requested or it may be denied out right
