### ISSUE TITLE
Unable to connect to discord with multiple shards

### ISSUE THREAD

**Issue by velddev** [RogueException/Discord.Net#483]
I tried connecting multiple shards to discord, but I the handshake failed for some, however when I connect one shard it works without any problem. 

Stack Trace 
http://pastebin.com/QNR3bpEj

**Comment by khionu** [comment]
What's the Exception Message? No good to know where it came from if we don't know what happened

**Comment by velddev** [comment]
At first it said 

https://a.pomf.cat/jyviin.png

But after foxbot adviced to add a bigger delay it timed out.

https://cdn.discordapp.com/attachments/184020182790832128/270321845335490572/unknown.png

**Comment by khionu** [comment]
If you are working with Foxbot in the Discord API guild, you should continue doing so there.

**Comment by velddev** [comment]
I asked him in PM, and after this conversation I was asked to put up an issue, so I did.

**Comment by velddev** [comment]
This has been fixed in a the recent version on D.Net
