### ISSUE TITLE
Question about Embeds

### ISSUE THREAD

**Issue by lyssieth** [RogueException/Discord.Net#493]
I can't figure out how to use the AddField method of an EmbedBuilder, yet, and would like to know how.

Also, why does C# have to be so goddamn annoying at times?

**Comment by FiniteReality** [comment]
Use a [lambda](https://msdn.microsoft.com/en-us/library/bb397687.aspx). Or you could wait for #460 to get merged which would make it easier.

**Comment by lyssieth** [comment]
I might do both, kind of. I'll use a lambda for now, and wait for #460.
