### ISSUE TITLE
Discord .NET Commands having trouble in multi-threaded environments (WPF)

### ISSUE THREAD

**Issue by AshkoreDracson** [RogueException/Discord.Net#496]
Hello!

Currently making a personal bot for my server. I created a WPF application to make it "neater" and that means that I've got to handle multi-threading, else the UI locks up.
Because of that `Client.ExecuteAndWait` runs on another thread.
It doesn't seem that the bot has much trouble handling all of this, however I am having trouble with initializing commands (Using `Discord.Commands`) correctly because of that.

Here's a rundown on how I register commands.

For each command, I create a new class inheriting from a custom `BotCommand`
```cs
public abstract class BotCommand
{
    public abstract void Initialize(CommandService service);
    public virtual void Trigger(CommandEventArgs e) { }
}
```
Example BotCommand class
```cs
public class CommandPing : BotCommand
{
    public override void Initialize(CommandService service)
    {
        service.CreateCommand("ping")
            .Do(new Action<CommandEventArgs>(Trigger));
    }
    public override async void Trigger(CommandEventArgs e)
    {
        await e.Channel.SendMessage("Pong!");
    }
}
```

And then at some point, I initialized all classes inheriting BotCommand in my own CommandManager class, which has a reference to the CommandService, the client and all. I initialize all of them in `CommandService.CreateCommands()`
Do take note that all of this is happening in another thread, not the main thread.
```cs
public class CommandManager
{
    public BotCommand[] BotCommands { get; private set; }
    public DiscordClient LinkedClient { get; private set; }
    public CommandService Service { get; private set; }

    public CommandManager(DiscordClient client)
    {
        Logman.Log("Initializing Command Service...");
        LinkedClient = client;

        client.UsingCommands(o =>
        {
            o.AllowMentionPrefix = true;
            o.HelpMode = HelpMode.Private;
            o.PrefixChar = '!';
        });
        Service = client.GetService<CommandService>();
        Service.CommandExecuted += Service_CommandExecuted;

        CreateCommands();
        Logman.Log("Command Service initialized!");
    }

    void Service_CommandExecuted(object sender, CommandEventArgs e)
    {
        Logman.Log($"{e.User.Name}#{e.User.Discriminator} executed \"{e.Message.Text}\"");
    }

    void CreateCommands()
    {
        Logman.Log("Creating commands...");

        var serviceSubclasses =
            (from assembly in AppDomain.CurrentDomain.GetAssemblies()
             from type in assembly.GetTypes()
             where type.IsSubclassOf(typeof(BotCommand))
             select type).ToArray();

        BotCommands = new BotCommand[serviceSubclasses.Length];
        for (int i = 0; i < BotCommands.Length; i++)
        {
            BotCommand nC = Activator.CreateInstance(serviceSubclasses[i]) as BotCommand;
            nC.Initialize(Service);
            BotCommands[i] = nC;
        }
    }
}
```

Here's a rough setup on how the bot starts

- `Bot.Start()` is called, new thread gets created into `Bot.BotWork()`
- Everything in `Bot.BotWork` is it's own new thread, bot continues initialization from here
- `DiscordClient` is created
- `CommandManager` is created, initializing all commands via `CommandManager.CreateCommands()`, also has a reference to the service and the client.
- `DiscordClient.ExecuteAndWait()` along with a `try catch` and `await DiscordClient.Connect()` inside said `try catch`

With all of that said, I have a neat start/stop that orchestrates all of this, often when started the first time, the bot will not react to commands, not even the registered `help` command by default.
I sometimes need to restart it two to three times before the bot finally takes commands into account. And sometimes when starting the first time it'll work straight away, or sometimes it'll work, then suddenly it doesn't react to commands anymore.

I have double-checked many places, but there seems to be no problems on my end, I checked all references, everything is alive and well, the bot just doesn't react to the commands.

Do note that it seems that I am also getting multiple `System.Threading.Tasks.TaskCanceledException` in an inconsistent manner through the bot life-time.

I have attached additional files for the extra information you may be missing, didn't want to clutter this issue too much.
[Bot Files.zip](https://github.com/RogueException/Discord.Net/files/722527/Bot.Files.zip)

**Comment by khionu** [comment]
Oh g-d, I actually feel bad saying this, because you've made such a beautifully thorough report, but 0.9 isn't really being maintained anymore. We're encouraging people to use 1.0, which is on the Dev branch.

Make sure to read the README.md, it has all the details, including links to documentation, to get started.

**Comment by AshkoreDracson** [comment]
Alright i'll update to 1.0 to see how this goes!
The NuGet doesn't seem to have 1.0 yet, is there a place where I can download the compiled version somewhere or do I have to compile it myself? I don't have VS 2017 RC right now.

**Comment by AshkoreDracson** [comment]
Nevermind I think I figured it out.
