### ISSUE TITLE
`Server.FindUsers` is searching for exact match despite that being set to false.

### ISSUE THREAD

**Issue by RheaAyase** [RogueException/Discord.Net#50]
`Server.FindUsers(expression, false);` will search for exact match only.
Expected behavior when `exactMatch = false` should be equal to `User.Name.ToLower().Contains(expression.ToLower())` while it seems to behave as `User.Name.ToLower() == expression.ToLower()` In other words, It is not case sensitive, but it won't find partial name.

Example of successful search to find user "Rhea the Cookie"
`expression = "rhea the cookie";`
`expression = "Rhea the Cookie";`
Example of unsuccessful search:
`expression = rhea`
`expression = Rhea`

**Suggested solution** (please excuse syntax issues, typing it right here..)
```
public IEnumerable<User> FindUsers(string name, bool exactMatch = false)
{
    if( string.IsNullOrEmpty(name) )
        throw new ArgumentNullException(nameof(name));

    if( exactMatch )
        return _users.Values.ToList().FindAll( u => u.Name == name );

    return _users.Values.ToList().FindAll( u => u.Name.ToLower().Contains(name.ToLower) );
}
```

ps. sorry but i can't submit pull right now...

**Comment by RogueException** [comment]
The FindXXX methods will be removed in 1.0. A separate issue could be made for something like a Search extension method maybe? We'll start looking into extension methods as 1.0 draws closer to launch.
