### ISSUE TITLE
Add some kind of callback option for _client.DisconnectAsync()

### ISSUE THREAD

**Issue by danny-may** [RogueException/Discord.Net#500]
I feel it would be useful for there to be some kind of clean way to detect when the bot is shutting down.
Either a "Shutdown" event or an overload of DisconnectAsync() that takes in a delegate, either would be executed after the client has cleanly disconnected.

**Comment by FiniteReality** [comment]
https://github.com/RogueException/Discord.Net/blob/dev/src/Discord.Net.WebSocket/DiscordSocketClient.Events.cs#L16 :thinking:

**Comment by danny-may** [comment]
That event gets fired both on _client.DisconnectAsync() and when there is a network disconnect, meaning its not useful for determining when you close the bot, only when it loses connection.

**Comment by FiniteReality** [comment]
If you're disconnecting the bot in application code, then you know where that is. We don't need to provide an event for something that you already know happened.

**Comment by danny-may** [comment]
Yeah, It is currently possible but its not very elegant to have to access the top level call in order to cancel the Task.Delay(-1, _tokenSource.Token) call from within the command area. I feel it would be more elegant to have an event specifically for the shutdown of the client rather than having to access areas that are kind of out of scope. Commands shouldn't really have any knowledge of how the application is called and initialised I feel.

**Comment by Auralytical** [comment]
`LoggedOut` is already effectively a shutdown event. It only triggers when `LogoutAsync()` is called or the bot's token was changed, and it only runs after the disconnect has completed.

**Comment by danny-may** [comment]
Ah, perfect! I saw the event but it wouldnt fire when I disconnected so I thought I was misunderstanding its purpose. Thanks!

**Comment by khionu** [comment]
I think this can be closed, now
