### ISSUE TITLE
ModifyAsync not working [1.0] Latest Version [588]

### ISSUE THREAD

**Issue by xXBuilderBXx** [RogueException/Discord.Net#507]
I am trying to modify a message with an embed using the example here https://discord.foxbot.me/docs/api/Discord.MessageProperties.html but Visual Studio says it cannot convert it to discord.optional
http://imgur.com/a/CO3f5

**Comment by Joe4evr** [comment]
You need to call `.Build()` at the end, because it expects an object of type `Embed`, not of type `EmbedBuilder`.

**Comment by xXBuilderBXx** [comment]
Ok let me try it

**Comment by xXBuilderBXx** [comment]
The Build() worked thanks Joe

**Comment by Joe4evr** [comment]
Resolution: PEBKAC
