### ISSUE TITLE
e.Channel.SendFile doesn't do anything

### ISSUE THREAD

**Issue by marco213** [RogueException/Discord.Net#51]
`        private void Bot_MessageReceived(object sender, MessageEventArgs e)
        {
              e.Channel.SendFile("test.jpg");
        }
`

after multiple attempts, sending an image that is inside the project does not work Someone else in the discord group seems to have the same problem. And Might as well say that e.Channel.SendTTSMessage is not working either. Am I missing something or those functions are bugged right now?

**Comment by khionu** [comment]
SendTTSMessage is broken, known issue. SendFile is not broken, I use it myself.

Are you using Nuget or Git Master?

**Comment by marco213** [comment]
I am using Nuget

**Comment by khionu** [comment]
Use Git Master. It has several critical updates that are not on Nuget, it's surprising Nuget still works.

**Comment by marco213** [comment]
I don't wanna sound dumb.. but how do I use Git Master? It's not really explained...

**Comment by khionu** [comment]
Download, open the project, build.

**Comment by marco213** [comment]
I downloaded the whole git project, and it compiled without any problems.. Buy whrn I run it, it says that there's no command in the global.json and I'm a but confused...

**Comment by khionu** [comment]
I advise you come to the Discord API server, to the channel #dotnet_discord-net, to discuss this further. This issue should be closed given the reason for opening it isn't a real issue, and further support can be given more effectively in the API server.
