### ISSUE TITLE
Update channel positions when changing one

### ISSUE THREAD

**Issue by SubZero0** [RogueException/Discord.Net#518]
**Where:** Modify the position of a channel to one that already exists.

**Current result:** two channels with the same position and a hole.

**Expected result:** the channel will change position and the old one that was there will have it's Position changed depending on where the channel that will occupy it's position was.
**Expected result example:**
![example](https://cloud.githubusercontent.com/assets/3085008/22764791/16c5bc82-ee54-11e6-95a7-ea3772f01e80.png)

**Current workaround** (by Advorange): https://hastebin.com/orerufuvah.cs
=> Change "manually" every channel position and update it with Guild.ModifyAsync and BulkGuildChannelProperties

**Comment by Auralytical** [comment]
This is currently by design as discord allows channels and roles to share positions. We may look into this as a new feature in the future.
