### ISSUE TITLE
Abstract DiscordShardedClient's group connection lock

### ISSUE THREAD

**Issue by RheaAyase** [RogueException/Discord.Net#519]
Description: Implement a system that could be used to `lock` both, connecting and reconnecting of the client.

Use case: Server cluster running one (or a few) shard(s) per hardware(or virtual) machine (or container)

=)

**Comment by Auralytical** [comment]
We already have a system like this in place for DiscordShardedClient, just need to abstract it to support scenarios where shards are in different processes.

**Comment by RheaAyase** [comment]
This should be in non-sharded client in my opinion, because the use case does not involve running multiple shards in one application. Single shard client should have synchronous event `i just started (re)connecting` in which one could halt and wait for whatever lock there needs be.

It is quite important event without which no large bot can function properly due to them "connecting" ratelimits.
