### ISSUE TITLE
Channel permission overwrites for individual users as opposed to roles

### ISSUE THREAD

**Issue by LordKanelsnegle** [RogueException/Discord.Net#521]
Given that Discord allows you to apply channel-specific permissions to both roles _and_ individual users, I initially assumed that the Discord API would allow you to do so as well - however, I couldn't find a way to overwrite a user's permissions rather than a particular role. After asking a number of times on the Discord API server Joe4evr suggested that I file an issue, so here I am ^_^

**Comment by FiniteReality** [comment]
Use `channel.AddPermissionOverwiteAsync`; it has an overload which accepts an IGuildUser and permission overwrites.
