### ISSUE TITLE
Can we have a consistent policy on `[AttributeUsage]` usage?

### ISSUE THREAD

**Issue by Joe4evr** [RogueException/Discord.Net#527]
I would like for all the attributes that the lib provides to have consistent behavior (preferably that most attributes get `Inherited = true`). If that's not desirable, then at the very least specify the `AllowMultiple` and `Inherited` properties explicitly everywhere, so that it can be picked up by Metadata as Source in VS, and make some behavior [a lot less surprising](https://en.wikipedia.org/wiki/Principle_of_least_astonishment).

**Comment by Auralytical** [comment]
I'm good with making this consistent, should discuss in dev chat.
