### ISSUE TITLE
Format.Sanitize should escape mentions

### ISSUE THREAD

**Issue by raphaelr** [RogueException/Discord.Net#529]
Currently `Format.Sanitize` does not escape mentions; this means that code like
```csharp
var untrustedInput = MentionUtils.MentionUser(Context.Message.Author.Id);
var shouldBeSafe = Format.Sanitize(untrustedInput);
await ReplyAsync(shouldBeSafe);
```
will successfully ping the user. In my opinion `Sanitize` should also escape mentions (by adding `<` and `>` to `Format.SensitiveCharacters`). This would also escape channel mentions, role mentions and external emojis.

With this fix the above message would show up as `<@!181451590533928934>` in Discord, which isn't pretty but it doesn't ping random people.

**Comment by Auralytical** [comment]
There is a bit of functionality overlap here. `MentionUtils.Resolve(userHandling: TagHandling.Sanitize)` inserts a nbsp to sanitize mentions

**Comment by Auralytical** [comment]
@foxbot @FiniteReality should Format.Sanitize maybe also call `MentionUtils.Resolve` with all params set to sanitize?

**Comment by FiniteReality** [comment]
I don't think it's a great idea, personally. The `Format` class should be used for Markdown formatting specifically IMO.

**Comment by Auralytical** [comment]
Yeah, I have to agree with that. I'm going to close this.
