### ISSUE TITLE
CommandInfo#Aliases returns group prefix as well as the command's name.

### ISSUE THREAD

**Issue by MarkusG** [RogueException/Discord.Net#539]
For example, assume there is a module with the prefix `core`. Within this module, there is a command which has a name `shutdown` and an alias `turnoff`. The CommandInfo object for that command will have a Name property of `shutdown`, as it should be, but the Aliases property will consist of `core shutdown` and `core turnoff`, rather than `shutdown` and `turnoff`.

**Comment by FiniteReality** [comment]
This is intentional. `Aliases` is supposed to return the full string used to invoke the command. If you want its name, use `CommandInfo.Name`, which you can set a friendly name with using `NameAttribute`.
