### ISSUE TITLE
The server responded with error 0: BadRequest

### ISSUE THREAD

**Issue by MysaNetAdmin** [RogueException/Discord.Net#544]
Hello, I am getting these:
"Exception thrown: 'Discord.Net.HttpException' in System.Private.CoreLib.ni.dll ("The server responded with error 0: BadRequest").", while trying to make an embed for my bot information
(I am using Discord.Net 1.0)
Any ideas about the error ?
Thanks ! :)

**Comment by Sentinent** [comment]
A error code 0 in embeds usually means a field with an empty value. Please post some code and ask in the [discord server](https://discord.gg/discord-api).

**Comment by MysaNetAdmin** [comment]
Oh i get it thanks !
