### ISSUE TITLE
IVoiceChannel.ConnectAsync() blocking thread until Timeout and not returning a result (using WS4Net)

### ISSUE THREAD

**Issue by FreezyLemon** [RogueException/Discord.Net#553]
I use WS4Net (Win7) for my bot.
Everything seems to work fine, except for joining voice channels:

```CSharp
IVoiceChannel channel = (Context.User as IGuildUser)?.VoiceChannel;
//if channel != null:
IAudioClient audioClient = await channel.ConnectAsync();
```
This connects to the channel (as in: I can see the bot connecting to voice inside of Discord), then blocks the whole App for ~15 seconds and tells me "The Timeout for this action has expired" (via ErrorReason) without changing the value of _audioClient.

I'm using version 1.0.0-rc-00614

**Comment by Flamanis** [comment]
You need to specify that the Command you're running is set to run as Async. 
This can be done in the Command attribute
`[Command("name", RunMode = RunMode.Async)]`

Commands by default are set to run as sync, which makes the timeout happen. Those more experienced than I might give a better explanation.

**Comment by FreezyLemon** [comment]
Wow... I totally missed that somehow.
Thanks! It works now

**Comment by Straafe** [comment]
Can someone help explain this to me? I added the Command Attribute on top of my join function (which contains "await channel.ConnectAsync();") but it still times out the same as before.

**Comment by LunayderKater** [comment]
same
