### ISSUE TITLE
DiscordShardedClient.CurrentUser is always null.

### ISSUE THREAD

**Issue by james7132** [RogueException/Discord.Net#557]
Even after starting a connection to Discord, DiscordSharded CurrentUser remains null indefinitely. Not sure if this is an issue with DiscordSocketClient, however.

**Comment by Auralytical** [comment]
This should be fixed in https://github.com/RogueException/Discord.Net/commit/5a1beeeb663bc1355a989f3358a27ed78b3080dd

**Comment by james7132** [comment]
Sorry for the delay. Seems to be fixed now.
