### ISSUE TITLE
Make base entity classes use MarshalByRefObject

### ISSUE THREAD

**Issue by XspeedPL** [RogueException/Discord.Net#570]
MarshalByRefObjects as you may know are for cross-AppDomain communication. If you're going for "modern and secure" practices, implementing it would be a good idea. There are no downsides to this known to me.  

AppDomains could be used to safely load DLL modules in a restricted sandboxed environment, and by using MarshalByRef enabled objects any entity can easily be accessed between AppDomains.  

Code changes are easy and unnoticeable. In case of SocketEntity.cs for example, it's a matter of changing  
`SocketEntity<T> : IEntity<T>`  
to  
`SocketEntity<T> : MarshalByRefObject, IEntity<T>`

**Comment by khionu** [comment]
.NET Standard doesn't cover AppDomains, and since Discord.Net 1.0 targets .NET Standard 1.1 and 1.3, it can't implement AppDomain APIs. This is a frustrating issue for many that relied upon AppDomains, as you can imagine.

**Comment by XspeedPL** [comment]
As far as I know .Net Standard does, while only .Net Core does not.  

From https://blogs.msdn.microsoft.com/dotnet/2016/09/26/introducing-net-standard/  
```
The AppDomain type has many APIs that aren’t tied to creating app domains, such as getting the list of loaded assemblies or registering an unhandled exception handler.  
These APIs are heavily used throughout the .NET library ecosystem.  
For this case, we decided it’s much better to add this type to .NET Standard and let the few APIs that deal with app domain creation throw exceptions on platforms that don’t support that, such as .NET Core.
```

**Comment by khionu** [comment]
Hmm, well, I personally won't be able to test to see if it would work for at least a few days, but if you want to test and make a PR, I don't see any reason that it would be rejected.

**Comment by Auralytical** [comment]
https://apisof.net/catalog/System.MarshalByRefObject is showing that this is not supported by .Net Standard 1.x nor .Net Core 1.x

**Comment by Auralytical** [comment]
We can look into this when we add .Net Standard 2.0+.Net4.x targets in the future, but we're blocked by tooling bugs atm.

**Comment by quinchs** [comment]
Closing due to https://github.com/discord-net/Discord.Net/pull/2230#issuecomment-1089247749
