### ISSUE TITLE
SocketGuild.CreateVoiceChannelAsync (string name) returns server error 0.

### ISSUE THREAD

**Issue by Lomztein** [RogueException/Discord.Net#576]
When I attempt to use the mentioned function, I get the following exception seen in the attached file: 
![image](https://cloud.githubusercontent.com/assets/6020468/24071754/472b30ca-0bda-11e7-8c93-c52ac6bebeef.png)

The line which this occurs on is line 237 found here: https://github.com/Lomztein/Adminthulhu/blob/master/AdminthulhuCore/AutomatedVoiceChannels.cs

**Comment by Auralytical** [comment]
Strange... I did a quick test and couldn't repro. Which build are you using?

**Comment by Auralytical** [comment]
Do you have a channel with a position of `Int32.MaxValue`? It appears Discord refuses to create more channels in this scenario.

**Comment by Lomztein** [comment]
That.. was actually the problem. It worked prior to 1.0, so I assumed it was a bug in the API. Sorry for the inconvenience, and thanks for the help!
