### ISSUE TITLE
00642 Cannot send a file (stream) without caption

### ISSUE THREAD

**Issue by Jofairden** [RogueException/Discord.Net#579]
On trying (build 00642)
`await Context.Channel.SendFileAsync(stream, $"{mod}.png", null);`
I get:
> Exception: The server responded with error 50006: Cannot send an empty message

This is strange behaviour, as the default value for text is null.
<img src="https://i.imgur.com/j68cCKT.png" />
The file sends without errors if I specify a caption.
Haven't tested when passing a path.

Edit: TC:
I was using client.**GetStreamAsync**, the following example will result in the mentioned error:
```
                using (var client = new System.Net.Http.HttpClient())
                using (var testStream = await client.GetStreamAsync(url))
                        await Context.Channel.SendFileAsync(testStream, "image.png");
```
while the following does not give this error:
```
                using (var client = new System.Net.Http.HttpClient())
                {
                    var response = await client.GetByteArrayAsync(url);
                    using (var stream = new MemoryStream(response))
                        await Context.Channel.SendFileAsync(stream, "image.png");
                }
```

**Comment by Still34** [comment]
It works fine for me. Are you sure {mod} is specified?

**Comment by Jofairden** [comment]
@Still34 yes, mod is specified (and correctly). See my edit on OP. Also, even if I just call it something like 'image.png', the issue persists

**Comment by LassieME** [comment]
So, delving a bit deeper into this issue, pretty sure this has something to do with the way HttpClient's GetStreamAsync works, which is by returning an unbuffered stream by default. https://github.com/dotnet/corefx/blob/master/src/System.Net.Http/src/System/Net/Http/HttpClient.cs#L245

This is probably pretty easily solved by simply reading the stream before passing it to the RestApiClient, but there is probably a better way.

For now either use the ByteArray/MemoryStream solution above or something like:
```CSharp
var responseMessage = await httpClient.GetAsync(e.Content, HttpCompletionOption.ResponseContentRead);
await e.Channel.SendFileAsync(await responseMessage.Content.ReadAsAsync(), "test.png");```

**Comment by Auralytical** [comment]
I suspect it's related to this part of HttpClient: https://github.com/dotnet/corefx/blob/master/src/System.Net.Http/src/System/Net/Http/StreamContent.cs#L69

Since the download stream is not seekable, the stream length is unknown and I assume it doesn't report `content-length` to Discord. https://github.com/RogueException/Discord.Net/commit/35d7a0cec89398a69fd5d3472fe6980f327f5d00 should fix this by copying to a memory stream if the provided stream's `CanSeek` is false.

**Comment by Jofairden** [comment]
@RogueException on build `00652`, which includes your commit, my result when running the example (faulty) code is discord showing an empty (0 bytes) 'corrupted' file. 
![](https://i.imgur.com/EfC4TcZ.png)

In this testcase I was ignoring input and just trying to grab a random png image: https://www.drupal.org/files/issues/sample_7.png
				
```
				using (var client = new System.Net.Http.HttpClient())
				using (var testStream = await client.GetStreamAsync("https://www.drupal.org/files/issues/sample_7.png"))
					await Context.Channel.SendFileAsync(testStream, "image.png");
```

Browser: `The image "https://cdn.discordapp.com/attachments/216276491544166401/296073797063147521/image.png 'can not be displayed because it contains errors."`

**Comment by Auralytical** [comment]
Should be fixed in https://github.com/RogueException/Discord.Net/commit/5aa92f8954af85d531dfc389927ec4c9e1c82ce2

**Comment by Jofairden** [comment]
@RogueException Yup, seems to  work properly now. Thanks.
