### ISSUE TITLE
Role Creation and Role Sorting issues

### ISSUE THREAD

**Issue by Cogsyy** [RogueException/Discord.Net#580]
I'm finding very odd issues with Context.Guild.CreateRoleAsync(), and Context.Guild.ModifyRolesAsync().
I've confirmed with another developer that ModifyRolesAsync doesn't appear to work properly, and doesn't reorder roles. Example: await newRole.ModifyAsync(x => x.Position = Context.Guild.Roles.Count - 2);. This code does execute, and no exceptions are thrown. The bot using this command is also the highest role, but the role doesn't change positions.

So now I've been working on a workaround with the other developer I mentioned, by creating a sorting array of the Server's roles, and modifying positions. The problem now is, Context.Guild.CreateRoleAsync() doesn't create the role right away, or "fast enough" for me to reference it after with Context.Guild.Roles. Here's the code sample for that:

IRole newRole = await Context.Guild.CreateRoleAsync(involvedGroup, GuildPermissions.None, new Color(255, 0, 0), false);

                    //await Task.Delay(10000);

                    IEnumerable<SocketRole> roles = (IEnumerable<SocketRole>)Context.Guild.Roles;
                    int positionRoleShouldBe = Context.Guild.Roles.Count - 2;// -1 because zero based, -2 because NyxBot is highest
                    SocketRole[] sortingArr = roles.OrderBy(x => x.Position).ToArray();//Stores the roles in the current order of the hierarchy
                    SocketRole temp = sortingArr[1];//this would be the newly created role
                    sortingArr[1] = sortingArr[positionRoleShouldBe];//swap it with the highest that's there currently

                    sortingArr[positionRoleShouldBe] = temp;
                    var sorting = sortingArr.Select((role, pos) =>
                    {
                        var res = new BulkRoleProperties(role.Id);
                        res.Position = pos;
                        return res;
                    });
                    await Context.Guild.ModifyRolesAsync(sorting);

**Comment by Auralytical** [comment]
Is this still happening on the latest build?

**Comment by Cogsyy** [comment]
No, it appears to have been fixed. Thanks!

**Comment by Jofairden** [comment]
If fixed, should be closed.

**Comment by kandarpgautam** [comment]
how was this issue resolved? I am experiencing something similar. Context.Guild.Roles don't return an updated roles list with the new role. Am I missing something?
Here is my code:
```
public async Task JailAsync(SocketGuildUser targetUser)
        {
            var jailrole = Context.Guild.Roles.Where(x=>x.Name=="jail").FirstOrDefault();
            if(jailrole == null)
            {
                await Context.Guild.CreateRoleAsync("jail",color: Color.DarkRed, isMentionable: false,isHoisted:true, permissions: GuildPermissions.None);
                jailrole = Context.Guild.Roles.Where(x=>x.Name=="jail").FirstOrDefault(); //here it returns null
                await jailrole.ModifyAsync(x=>x.Position= (Context.Guild.Roles.Where(x=>x.Name=="CyberSpace").Select(x=>x.Position).FirstOrDefault() + 1));
            }
            await targetUser.AddRoleAsync(jailrole);
            await ReplyAsync($"{targetUser} has been put in jail.");
        }
```

**Comment by quinchs** [comment]
It takes some time for the cache to add the newly created role

what you can do is this
```cs
        public async Task JailAsync(SocketGuildUser targetUser)
        {
            IRole jailrole = Context.Guild.Roles.Where(x=>x.Name=="jail").FirstOrDefault();
            if(jailrole == null)
            {
                jailrole  = await Context.Guild.CreateRoleAsync("jail",color: Color.DarkRed, isMentionable: false,isHoisted:true, permissions: GuildPermissions.None);
                await jailrole.ModifyAsync(x=>x.Position= (Context.Guild.Roles.Where(x=>x.Name=="CyberSpace").Select(x=>x.Position).FirstOrDefault() + 1));
            }
            await targetUser.AddRoleAsync(jailrole);
            await ReplyAsync($"{targetUser} has been put in jail.");
        }
```

**Comment by HarrySpyrou** [comment]
@quinchs answer is correct but when I try to do `Select(x=>x.Position).FirstOrDefault() + 1)` I get a permissions error. Only when I do `Select(x=>x.Position).FirstOrDefault() - 1)` it works. Just leaving this here for whoever runs into it.
