### ISSUE TITLE
Bulk Delete Messages not Working (Discord.Net 1.0)

### ISSUE THREAD

**Issue by ASTRELION** [RogueException/Discord.Net#582]
Forgive me as I am new to this and don't know the in's and out's of everything yet:

I am trying to bulk delete messages and am getting a message saying the messages I'm trying to delete are older than 2 weeks. However, I try to delete just 1 (recent) message and it gives me the same error. Weird thing is that if I try to cycle through the list of messages with a foreach loop, I can delete them individually but it obviously throws a ratelimit if I try to delete too much. Am I doing something wrong?

I get the messages with:
`var msgs = await Context.Channel.GetMessagesAsync(input).Flatten();`

And attempt to delete the messages with:
`await Context.Channel.DeleteMessagesAsync(msgs);`

**Comment by Cisien** [comment]
So... uhh... What error are you getting?

**Comment by ASTRELION** [comment]
In my channel my bot displays "Messages must be younger than two weeks to delete.
Parameter name: MessageIds" but the messages I am trying to delete are definitely not older than 2 weeks.

**Comment by AntiTcb** [comment]
Reproduced successfully. Seems like the math's a bit off [on this precondition.](https://github.com/RogueException/Discord.Net/blob/dev/src/Discord.Net.Core/Utils/Preconditions.cs#L186)

DateTimeOffset values:
```
Message older than 2 weeks: 2/28/2017 4:43:24 AM +00:00
Message grabbed today: 3/22/2017 2:52:10 AM +00:00
Value that messages are compared to in the precondition: 1/19/2033 1:00:28 PM +00:00
```

**Comment by ASTRELION** [comment]
How can I go about correcting the issue?

**Comment by Cisien** [comment]
```        public static DateTimeOffset FromSnowflake(ulong value)
            => FromUnixMilliseconds((long)((value >> 22) + 1420070400000UL));
        public static ulong ToSnowflake(DateTimeOffset value)
            => (ulong)(ToUnixMilliseconds(value) - 1420070400000L) << 22;
```
one number is a UL, the other is a L -- not sure if that would impact this or not.

**Comment by Auralytical** [comment]
Fixed in https://github.com/RogueException/Discord.Net/commit/13b9b15cf085b4b68324bb0b2f8d7ad6fd6ab2e8
