### ISSUE TITLE
CommandService.RemoveModuleAsync<T>() does not remove module from internal list

### ISSUE THREAD

**Issue by Obbi89** [RogueException/Discord.Net#584]
`private readonly ConcurrentDictionary<Type, ModuleInfo> _typedModuleDefs;`
_typedModuleDefs is used to store Type → ModuleInfo reference.

When a Module is removed from the CommandService it is not removed from the ConcurrentDictionary.
This prevents a removed Module from being ever added again.

Is this wanted behavior or just a tiny error?

see: [https://github.com/RogueException/Discord.Net/blob/dev/src/Discord.Net.Commands/CommandService.cs#L156](https://github.com/RogueException/Discord.Net/blob/dev/src/Discord.Net.Commands/CommandService.cs#L156)

**Comment by FiniteReality** [comment]
This is a :hash: blamefinite issue. Will fix.
