### ISSUE TITLE
C# Discord bot 401 unauthorized code

### ISSUE THREAD

**Issue by JayCobra** [RogueException/Discord.Net#585]
my code:
using Discord;
using Discord.Commands;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace DiscordBot
{
class MyBot
{

    DiscordClient discord;

    public MyBot()
    {
        discord = new DiscordClient(x =>
       {
           x.LogLevel = LogSeverity.Info;
           x.LogHandler = Log;
       });

        discord.UsingCommands(x =>
        {
            x.PrefixChar = '!';
            x.AllowMentionPrefix = true;

        });

        var commands = discord.GetService<CommandService>();

        commands.CreateCommand("Hello")
        .Do(async (e) =>
        {
            await e.Channel.SendMessage("Yo");
        });

            
        discord.ExecuteAndWait(async () =>
        {
            await discord.Connect("token",TokenType.Bot);
          
        });

    }
    private void Log(object sender, LogMessageEventArgs e)
    {
        Console.WriteLine(e.Message);
    }

}
}

Im using the latest .Net version

**Comment by Flamanis** [comment]
Eeeeey you found us!
401 errors stem from you not providing the correct token in your Connect call.

**Comment by JayCobra** [comment]
what do you mean? i just changed the token to "token" so you wont use it or something

**Comment by Flamanis** [comment]
Are you sure you had the correct token from the page? 401 unauthorized stems from sending the wrong thing as a token, or using the wrong kind of token.

**Comment by JayCobra** [comment]
im sure ill check it again just in case

**Comment by JayCobra** [comment]
ok its working ive set the client secret xD

**Comment by Flamanis** [comment]
It's a common mistake :P If you need more help though, you can join the [Discord API Server](https://discord.gg/discord-api) to get faster help through the channel dedicated to this library. #dotnet_discord-net

**Comment by JayCobra** [comment]
Joined ty so much =)
