### ISSUE TITLE
Presence updates should trigger GuildMemberUpdated

### ISSUE THREAD

**Issue by Xeevis** [RogueException/Discord.Net#588]
Up to commit 3bd920ce66d6f7ff24bdf6e7077ea24499ddb9c5 I used UserPresenceUpdated to track when someone comes online or goes offline in order to update user counter on a web widget (which is per guild). Since the merge there is no way to retrieve information about guild where that event happened from event itself since it's passing only 2 SocketUser parameters.

Even if I resort to extensive checking in which guilds user is joined there is this problem that we now treat UserUpdated as global event but it's in fact not. Event is fired per guild, not per user, meaning if 1 user is in 3 guilds where bot resides his single status change will result in 3 identical event executions, that can't be intended.

```
public DiscordWidgetService(IDependencyMap map)
{
    client.UserUpdated += Client_UserUpdated;
}

async Task Client_UserUpdated(SocketUser arg1, SocketUser arg2)
{
    await Console.Out.WriteLineAsync($"UserUpdated fired for {arg2.Username}");
}
```

**Comment by khionu** [comment]
Our options are limited, because of the way the Discord API is structured. We've discussed this issue extensively, and this is the best we can do, for now.

**Comment by FiniteReality** [comment]
Doesn't Discord pass the guild where the presence update originated from?

**Comment by Xeevis** [comment]
They do and thats how it was implemented up until the mentioned commit which I guess aimed to simplify things.

@khionu Since API does pass the guild id, wouldn't it make more sense to at least use GuildMemberUpdated instead of UserUpdated? Would solve my issue and better adhere to API structure which kinda does consider this to be a guild oriented event. 😄

    client.GuildMemberUpdated += Client_GuildMemberUpdatedAsync;

    async Task Client_GuildMemberUpdatedAsync(SocketGuildUser before, SocketGuildUser after)
    {
        await Console.Out.WriteLineAsync($"GuildMemberUpdated fired for {after.Username} in {after.Guild.Name}");
    }

**Comment by Auralytical** [comment]
We store presence at the global level, not per guild, so the previous event was flawed and buggy. Even though the API sends this data per-guild, it does not actually represent a per-guild state.

**Comment by Xeevis** [comment]
@RogueException But presence isn't considered or supported as global by discord. As explained by jhgg in [here](http://bit.ly/2opTyDL)

> Presences and roles are per-guild, whereas the user object is global.

![image](https://cloud.githubusercontent.com/assets/5835044/24561256/5d526a78-1646-11e7-90c5-c7739c22dd91.png)

**Comment by Auralytical** [comment]
Funny since I talked to Jake 3 weeks before that and was told to do it globally. Will ask around =\

Edit: Oh... the user is global and presence isn't? Ugh. Have I mentioned how much I hate PRESENCE_UPDATE?

**Comment by Xeevis** [comment]
I'd assume that's why Presence Update and User Update are separate events in the API.

And also description for Presence Update reads

> A user's presence is their current state on a guild. This event is sent when a user's presence is updated for a guild.

So yeah user precence is per-guild. I imagine sometime in the future we might even get option to set invisible for certain guilds while online in others. That would be cool.

**Comment by Auralytical** [comment]
Presence and User updates *arent* separate though. Presence updates still carry global user data. Hence my confusion.

**Comment by Auralytical** [comment]
This should be fixed in https://github.com/RogueException/Discord.Net/commit/fd72583a75a1c9ccc1f6040c8611d20c58513e4a
