### ISSUE TITLE
Problem following the guides.

### ISSUE THREAD

**Issue by ATypescriptEnjoyer** [RogueException/Discord.Net#597]
Hey, I seem to be having a problem following the guides on creating a bot, unsure whether i'm just being dumb or things no longer match.

The docs say that `DiscordSocketClient` is in `Discord.WebSocket` but all I have is `Discord.Net.WebSockets`. The nuget also apparently doesn't support .NET core 1.1 or 1.0, so really unsure whether I've just done something wrong.

Using VS 2017, unsure whether this is a problem

Thanks for helping, I've been looking into it for about an hour and can't even get the guide working 😢

**Comment by Erlite** [comment]
Did you download Discord.NET 0.9.6 by accident?

**Comment by Auralytical** [comment]
The `Discord.WebSocket` namespace is found in the `Discord.Net.WebSockets` package. Make sure to check show prereleases to get access to the 1.0.0-rc build, which supports .NET Core.

**Comment by ATypescriptEnjoyer** [comment]
That'll be it, I downloaded the latest stable release off Nuget, I'll get it a different way and try again

**Comment by Sentinent** [comment]
PS, these types of questions are more suitable for the [discord support server](http://discord.gg/discord-api) (click on #dotnet_discord-net).

**Comment by ATypescriptEnjoyer** [comment]
Everything seems fine now, thanks ^_^
