### ISSUE TITLE
CommandService.ExecuteResult returns UnknownCommand even though there are valid commands

### ISSUE THREAD

**Issue by Nensec** [RogueException/Discord.Net#601]
I've got 2 commands that have the same name, but different parameters. I have a precondition that currently returns false, on both said commands, with a custom error message.

The ExecuteResult returns **CommandError.UnknownCommand** with reason **UnknownCommand: This input does not match any overload.**. This doesn't feel like it should be the correct response, as my custom error message is never returned even though the debugger steps through it.

Is this the correct behavior that is expected or a bug?

To repro:

Precondition:

```
public class TestPreconditionAttribute : PreconditionAttribute
{
    public override async Task<PreconditionResult> CheckPermissions(ICommandContext context, CommandInfo command, IDependencyMap map)
    {
        //return PreconditionResult.FromSuccess();
        return PreconditionResult.FromError("Nope");
    }
}
```

Command:

```
[TestPrecondition]
[Command("test")]
public async Task Test(string input)
{
}

[TestPrecondition]
[Command("test")]
public async Task Test(string input, string input2)
{
}
```

**Comment by SubZero0** [comment]
Same as #514
