### ISSUE TITLE
Unable to change playing game on the fly?

### ISSUE THREAD

**Issue by MisterMorde** [RogueException/Discord.Net#612]
I've been attempting to create a command to change the bots current game - Is it possible to change it on the fly or does it need to be changed at startup (and unable to be changed afterwards) ?

**Comment by Flamanis** [comment]
It is possible to change at any point in runtime as long as the bot is connected.

**Comment by MisterMorde** [comment]
Would you be able to provide an example of how i would change it mid runtime - my command isn't currently working 

[Command("setgame")]
        public async Task SetGame([Remainder] string game = null)
        {
            var _client = new DiscordSocketClient();
            await _client.SetGameAsync(game);

        }

**Comment by Flamanis** [comment]
You are creating a new client, which is not what you should be doing. Use the object given to you that is Context.Client

**Comment by Bond-009** [comment]
```
        [Command("setgame")]
        [Summary("Sets the bot's game")]
        public async Task SetGame([Remainder] string input)
        {
            await (Context.Client as DiscordSocketClient).SetGameAsync(input);
        }
```

**Comment by MisterMorde** [comment]
Thanks guys, Definitely appreciated

**Comment by Flamanis** [comment]
In the future you can join the Channel and ask questions there: https://discord.gg/discord-api
Ask in the channel #dotnet_discord-net
