### ISSUE TITLE
TaskCanceledException with SendMessageAsync

### ISSUE THREAD

**Issue by SubZero0** [RogueException/Discord.Net#613]
This is an intermittent problem that I'm having when trying to send a message.

Stacktrace 1: https://hastebin.com/vigocomafa.pas
Line: https://github.com/SubZero0/DiscordNet-Docs/blob/master/src/DiscordNet/Handlers/CommandHandler.cs#L68

Stacktrace 2: https://hastebin.com/noyozisenu.cs
Line: https://github.com/SubZero0/DiscordNet-Docs/blob/master/src/DiscordNet/Modules/Commands.cs#L173

In the first stacktrace I'm just sending one message, there's no reason to trigger the ratelimit, so I guess Discord.Net is trying to send it (and failing) a lot of times and triggering it itself (?).

Additional infomation:
The bot is hosted on a Ubuntu 14.04 server with .NET Core 1.1.
I couldnt reproduce on Windows 10.

I will probably try running the bot on another OS, like Ubuntu 16.04/CentOS/Debian, with a fresh install.
I accept suggestions as well for what should be causing it or which OS should I try. =p

**Comment by Auralytical** [comment]
I suggest turning on debug logging which will show all outgoing requests and if there are any clustered together before the ratelimit is triggered.

**Comment by SubZero0** [comment]
Couldnt get the ratelimit again. But the error is still there.
Log with debug (the log starts when I sent the message):

Not awaiting the command handler:
1- https://hastebin.com/akexewinag.cs
2- https://hastebin.com/dirovuxide.cs

Awaiting the command handler:
1- https://hastebin.com/afeyasodab.sql

As it's possible to see, it receives the message but freezes the handler since the POST log only appears shortly before the exception.
The Sync approach makes the bot lose connection since it freezes the heartbeat. It's possible to see there's no long running method inside the "info" command (https://github.com/SubZero0/DiscordNet-Docs/blob/master/src/DiscordNet/Modules/Commands.cs#L173).

**Comment by SubZero0** [comment]
Tried changing the OS to CentOS 7.1 and Ubuntu 16.04 but the error still persists.
No idea what could be causing it :S

**Comment by Auralytical** [comment]
There's only two things that should be able to cause a TaskCanceledException: logging out of the client (or disposing of it, or logging in again), or canceling the CancellationToken passed via RequestOptions, if any.

**Comment by SubZero0** [comment]
I think it was related to where it was hosted.
I don't know what was causing it but I changed my host and it looks like it's working fine.
I'll close this since it doens't look like a lib-related issue.

Thanks Voltana.
