### ISSUE TITLE
No way to get guild from message/channel

### ISSUE THREAD

**Issue by Nolij** [RogueException/Discord.Net#621]
I'm trying to make a chat logger for my self bot, but I cant find an efficient way to get the guild a message/channel belongs to, is there one? Can one be added? Is it not added for a reason?

I'd highly appreciate it if someone could answer my questions.

PS: using 1.0 forgot to mention

EDIT: I found the endpoint its part of the JSON returned for channel objects https://mix1337.gyazo.com/1d6f2d63c2f4ff3bbc7dbc8626a367ed

**Comment by Yucked** [comment]
```cs
var chnl = message.Channel as SocketGuildChannel;
var Guild = chnl.Guild.Name;
```
Does that answer your question?

**Comment by Nolij** [comment]
Thanks, if an admin could close the issue

**Comment by FiniteReality** [comment]
You can close your own issues. Click the 'close issue' button.

**Comment by Yucked** [comment]
Also, consider joining D.net discord channel. https://discord.gg/discord-api

**Comment by Nolij** [comment]
Didn't know about close issue I'm new to github, also I'm already in the api discord I just never really get help I just get called an idiot or something along those lines
