### ISSUE TITLE
(1.0) Disconnect from Voice

### ISSUE THREAD

**Issue by hasezoey** [RogueException/Discord.Net#629]
I dont find Something to Leave from a Voice Channel, is there a way, not only to wait of the Timeout?

Like 
```C#
[Command("stop", RunMode = RunMode.Async)]
        public async Task MusicCStop()
        {
            IVoiceChannel channel = null;
            channel = channel ?? (Context.Client as IGuildUser).VoiceChannel;
            var AudioClient = await channel.DisconnectAsync(); //<--
        }
```
Because this to Join
```C#
[Command("join", RunMode = RunMode.Async)]
        [Alias("j")]
        public async Task MusicCJoin(IVoiceChannel channel = null)
        {
            channel = channel ?? (Context.Message.Author as IGuildUser)?.VoiceChannel;
            Program.ConsoleSendMessage($"{Context.Message.Author} {channel.Name}", true);
            var AudioClient = await channel.ConnectAsync();
            await ReplyAsync("Connectet");
        }
```

Tryed already [This](https://gist.github.com/Joe4evr/773d3ce6cc10dbea6924d59bbfa3c62a/308f8fd92e03febcb699023d95a4f0a8813aa46f) and there the Bot Cannot Join / Leave

**Comment by Mushroom** [comment]
Could you describe how joe4ever's gist does not work?

`IAudioClient.StopAsync()` is the way to disconnect gracefully.

**Comment by hasezoey** [comment]
I dont know whats wrong there, but it does nothing (no connect and no message whats wrong)

**Comment by Mushroom** [comment]
Okay, not sure about that, but to fix your issue, call `.StopAsync()` on the `IAudioClient` created by your 'join' command. This will gracefully disconnect you.

**Comment by hasezoey** [comment]
I have already maked my own, but thanks anyway ^^
