### ISSUE TITLE
Setting 'PreAuthenticate = False' causes the library to be unusable with Universal Applications

### ISSUE THREAD

**Issue by Mushroom** [RogueException/Discord.Net#63]
Ran into this when creating a UWP for Discord using Discord.NET and .NET Core RC3.

Steps to Reproduce:
1) Create a UWP app that uses .NET Core RC3
2) Add Discord.NET DLL as a reference
3) Attempt to initialise a DiscordClient

The app will throw an exception saying that setting the 'PreAuthenticate' value to 'false' is not supported.

**Comment by RogueException** [comment]
Looks like this property defaults to false anyway, I've removed it from master.

**Comment by RogueException** [comment]
Be sure to let me know if you build a working UWP app with Discord.Net. I haven't a chance to test the other platforms that .Net Standard 1.3 targets.

**Comment by Mushroom** [comment]
I have it working already on a Phone using the latest insider preview - building the UI is taking time though. Making substantial progress though - main test should be the Audio.

I'm attempting to recreate the mobile app on iOS - is the friends functionality available at all through the API? I couldn't find it...

**Comment by RogueException** [comment]
Awesome!

And no, the lib is currently focused around the bot API (which doesn't support friends). It *is* however a feature I plan to add... probably in v1.1.

**Comment by Mushroom** [comment]
Okay, I can work around that with the UI.

Depending on how well my app goes I may end up implementing something myself!

**Comment by RogueException** [comment]
:D I've added #64 to make sure I don't forget.

**Comment by Mushroom** [comment]
Great! Also joined the discord channel so I can discuss other things if need be :)
