### ISSUE TITLE
Commands from parent class / BaseType

### ISSUE THREAD

**Issue by Nikey646** [RogueException/Discord.Net#650]
It would be nice if the methods from the parent class of a module could be considered for commands on the module.

As it stands, if you wanted to do something like this (silly example)
```cs
public abstract class ExampleModule : ModuleBase
{
	[Command("class")]
	public async Task ExampleCommandAsync()
		=> await this.ReplyAsync($"I am the {this.GetType().Name} module.");
}

public class ChildModule : ExampleModule
{ }

public class OtherChildModule : ExampleModule
{ }
```
The way that methods are currently found won't detect the clearly valid command from the abstract `ExampleModule` class. This means that if you have two modules that are functionally identical, except for one part that can be controlled via an abstract property you still need to implement all commands twice (Even if you are only calling to a service)

The reason that this occurs is because when building the Module Info for the class, it only uses [`TypeInfo.DeclaredMethods`](https://github.com/RogueException/Discord.Net/blob/dev/src/Discord.Net.Commands/Builders/ModuleClassBuilder.cs#L114), which doesn't check the parent/base class methods at all.

The current functionality is also not consistent when compared against the Property Injection of Modules, which already does the [required work around](https://github.com/RogueException/Discord.Net/blob/dev/src/Discord.Net.Commands/Utilities/ReflectionUtils.cs#L57-L65) to get all Properties from the parent/base class

**Comment by FiniteReality** [comment]
What use case do you have for this? As far as I'm aware, ASP.NET has a similar restriction and in general it's just Bad Practice:tm:.

As for being inconsistent with dependency injection, dependency injection is a totally different thing so it behaves differently. Frankly, most of that code could be cleaned up using ASP.NET's ActivatorUtilities.CreateFactory method instead.

**Comment by Nikey646** [comment]
My use case is that i have a service that consumes a standard API from multiple different websites, and the only different is the url that it goes to.

It seems silly to need to have two classes with the only difference being one property having a different value, it is just plain redundant and completely goes against the DRY principle? 

Not to mention error prone, because if one thing changes that doesn't cause an error on the service, each and every class that implements service needs to be manually updated, which could be avoided by reading methods from the BaseType, and having a single class that controls all the methods, and the child classes would provide the unique parameters.

**Comment by Nikey646** [comment]
On the subject of ASP.Net having a "similar restriction" I just checked, and it's quite possible to do what i want in ASP.Net Core at least.

```cs
public abstract class ExampleController : Controller
{
    [Route("[Controller]/test")]
    public IActionResult Test()
        => this.Json(new {CurrentRoute = this.Request.Path});
}

public class ChildController : ExampleController
{ }
``` 
Using the above code and going to `/child/test` and produces the correct json (in this case `{"currentRoute":{"value":"/child/test","hasValue":true}}`)

So i'm not sure what the restriction you're talking about is, or why it is bad practice when ASP.Net Core seemingly allows me to do something similar to what i want, although i have no idea what the exact use case for this functionality in a website would be?

**Comment by quinchs** [comment]
@Cenngo Thoughts here?

**Comment by Cenngo** [comment]
I guess adding this feature wouldn't hurt but we need to trust the users to add a group attribute the deriving type to avoid collision.

If we choose to implement this i believe adding a BindingFlags.FlattenHierarchy to the GetMethods method will be enough

**Comment by quinchs** [comment]
@Cenngo Would you want to make a PR for this?

**Comment by Cenngo** [comment]
> @Cenngo Would you want to make a PR for this?

Yeah, i do. I will probably pr the changes on sunday

**Comment by Cenngo** [comment]
@quinchs go ahead and close this, seems like this is already implemented.
