### ISSUE TITLE
discord.SetGame

### ISSUE THREAD

**Issue by YoloMcWelfare** [RogueException/Discord.Net#660]
This is more of help rather than an issue but iv'e been messing around with discord.NET and i cant seem to figure out the discord.SetGame to get the bit is playing...
![capture](https://cloud.githubusercontent.com/assets/28795013/26228201/b32b7996-3c05-11e7-84c2-2a545d0c63b0.PNG)

**Comment by MarkusG** [comment]
# **RESET YOUR TOKEN**

`SetGame()` takes a single string argument which represents the "game" you want your bot to be "playing." Also, you have to call `SetGame()` after a delay after your bot connects, so put it after an `await Task.Delay(3000)` after you connect.

These questions are better suited for our channel in the [Discord API Guild](https://discord.gg/discord-api) (#dotnet_discord-net).

**Comment by FiniteReality** [comment]
Closing as this looks like it has been resolved externally.
