### ISSUE TITLE
Embeds not sending?

### ISSUE THREAD

**Issue by ghost** [RogueException/Discord.Net#664]
I'm creating a bot using Visual Studio 2015 and I am trying to get the bot to send embeds, but I'm not sure how to send them. I've tried multiple methods, to which had no prevail.

How do you correctly send embeds to Discord using Visual Basic/.NET Framework on Visual Studio 2015?

**Comment by v3Monsta** [comment]
ReplyAsync("", embed: embed) has worked fine for me if you're on 1.0

**Comment by ghost** [comment]
This is an example of one of my commands and how it is structured:
`commands.CreateCommand("roll")
    .Alias(new string[] { "dice", "rolldice", "rolldie"})
    .Description("Rolls a dice and provides a random number 1-6")
    .Do(async (e) =>
    {
        int rolledNumber = rand.Next(6);
        await e.Channel.SendMessage("<@" + e.User.Id + ">, you have rolled a " + (rolledNumber+1) + ".");
    });`
How do I implement embeds _using this code?_

**Comment by captainsalt** [comment]
You cannot send embeds because you're using 0.9. 
Embeds are only supported in versions 1.0 and greater.

**Comment by ghost** [comment]
How do I get 1.0? I just downloaded Discord.NET on the project this morning, so unless 1.0 came out after this morning, I'm unsure of how to get it.
@captainsalt

**Comment by Still34** [comment]
Check pre-release in your NuGet package manager, or add `-Pre` in your package manager console when installing the package. 1.0 has been in public RC for quite some time now. The latest RC is `rc2`.

**Comment by ghost** [comment]
All it lets me download is "Latest stable 0.9.6"

**Comment by ghost** [comment]
Oops, I found it.
