### ISSUE TITLE
Embed question

### ISSUE THREAD

**Issue by ghost** [RogueException/Discord.Net#668]
How do you create an embed using Discord.NET 1.0? I know that the embed itself is an argument within the `SendMessageAsync()` function, but I'm unsure of how they are meant to be formatted.

**Comment by khionu** [comment]
Make a new EmbedBuilder, then to get an Embed out of it, use `EmbedBuilder.Build()`

**Comment by ghost** [comment]
How? I'm not very experienced with C# and I'm mostly using other references to make my bot.

**Comment by ghost** [comment]
(furthermore, I don't even really know many basics about C#)

**Comment by ghost** [comment]
Nevermind, figured it out!
