### ISSUE TITLE
Bot cannot connect (or keeps disconnecting)

### ISSUE THREAD

**Issue by ghost** [RogueException/Discord.Net#671]
Whenever I attempt to start my bot with the simplest code I could think of, it doesn't work (Note that this is not the code's fault, others have tried it and it's working fine for them).

```
using System;
using System.Threading.Tasks;
using Discord;
using Discord.WebSocket;

namespace BotTest
{
    class BotMain
    {
        private static void Main(string[] args)
            => Start().GetAwaiter().GetResult();

        internal static DiscordSocketClient Client = new DiscordSocketClient (new DiscordSocketConfig
        {
            LogLevel = LogSeverity.Debug,
            //WebSocketProvider = Discord.Net.Providers.WS4Net.WS4NetProvider.Instance
        });

        private static async Task Start()
        {
            Client.Log += OutputLogMessage;
            await Client.LoginAsync(TokenType.Bot, "");
            await Client.StartAsync();
            await Task.Delay(-1);
        }

        private static Task OutputLogMessage(LogMessage m)
        {
            Console.WriteLine(m.Message);
            return Task.CompletedTask;
        }
    }
}

```

Note that line 16 is commented.

Without line 16 (so as it is now), whenever I run the program, it simply keeps disconnecting (and never manages to connect). This is how my output looks like:

![image](https://cloud.githubusercontent.com/assets/24478119/26462405/ef4974ca-4180-11e7-8beb-20269a4af5df.png)

When uncommenting line 16, it shows the same behaviour, but it never attempts to reconnect:

![image](https://cloud.githubusercontent.com/assets/24478119/26462431/1027870e-4181-11e7-8f99-9c4df4853ae5.png)

Am I doing something wrong? Is something wrongly setup? Or is there nothing I can do about it?

I am using version v1.0.0-rc3 and have all the packages and dependencies updated.

**Comment by ghost** [comment]
After further investigation, this seems to be the error:
```
Could not load file or assembly 'WebSocket4Net, Version=0.14.1.0, Culture=neutral, PublicKeyToken=eb4e154b696bf72a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
```

**Comment by Joe4evr** [comment]
Running on Windows 7 and targeting .NET Core?

**Comment by ghost** [comment]
Windows 7, targeting .NET Framework 4.6.1 .

**Comment by Joe4evr** [comment]
Interesting. 🤔 Try [this alternative provider](http://www.mediafire.com/file/28owz2o2299c24a/WS4NetCore.1.0.0-a.nupkg.zip) instead, anyway?

**Comment by ghost** [comment]
Nope, still receiving the same error.

**Comment by ghost** [comment]
Fixed by installing both the newest Discord.NET 1.0 and WS4NET updates from the Discord.NET nuget package source.
