### ISSUE TITLE
Log a warning when loading a non-public module class

### ISSUE THREAD

**Issue by Joe4evr** [RogueException/Discord.Net#675]
Filing mainly as a reminder.

We should log a warning [here](https://github.com/RogueException/Discord.Net/blob/dev/src/Discord.Net.Commands/Builders/ModuleClassBuilder.cs#L254) when a module class is not declared public. The check is as simple as `if (typeInfo.IsNotPublic)`, but because `ModuleClassBuilder` doesn't have access to a logger already *and* it's entirely `static`, implementation may require an overhaul of the class.

**Comment by Confruggy** [comment]
huh, the methods of ModuleClassBuilder have the CommandService as arg which has a logger.

**Comment by Joe4evr** [comment]
Oh does it? Didn't notice that, my bad.

**Comment by FiniteReality** [comment]
I'll cover this in #678 - it wouldn't be hard to check in AddModulesAsync for any types that have possibly been skipped due to not being public.

**Comment by Joe4evr** [comment]
👌
