### ISSUE TITLE
Inaccessible 

### ISSUE THREAD

**Issue by ghost** [RogueException/Discord.Net#679]
[Command("setavater")]
        public async Task avater()
        {
            var file = new FileStream(Directory.GetCurrentDirectory() + "/newAvatar.jpg", FileMode.Open);
            await Context.Client.CurrentUser.ModifyAsync(x =>
            {
                x.Avatar = new Discord.API.Image(file);
            });
        }
Image seems to giving me an error saying : 
'Image' is inaccessible due to its protection level

**Comment by knightking100** [comment]
use Discord.Image

**Comment by ghost** [comment]
Thanks alot, didnt know it was that simple lol (I think cause i am coding at 3 am) @knightking100
