### ISSUE TITLE
MessageUpdated & MessageDeleted not working as intended.

### ISSUE THREAD

**Issue by NotAkitake** [RogueException/Discord.Net#682]
_Using .NET 4.6.2, Discord.NET 1.0.0 RC2_ 

Hi, I think that **MessageUpdated** and **MessageDeleted** events aren't working as intended.
I can't manage to get the message's content in the state before it was deleted or updated.

[Here](https://hastebin.com/kijowikepu.cs) is my code.
And [here's](https://puu.sh/w5ysf/dc4c24f9ba.jpg) the ouput for **MessageUpdated**.
As for **MessageDeleted**, it simply does not send anything, meaning that **arg1** and **arg2** are most likely **null**

Now I might be completely dumb and doing this wrong, but I don't think so.

**Comment by AntiTcb** [comment]
You can't download a message's previous state after it was updated or deleted. You'll only be able to access it if you set your `DiscordSocketConfig.MessageCacheSize` to something higher than 0 to enable message caching.

**Comment by NotAkitake** [comment]
MessageCacheSize isn't even a thing in my book ?
It doesn't exist in DiscordSocketConfig nor DiscordConfig.
Plus I haven't been the only person complaining about those events.

**Comment by AntiTcb** [comment]
https://github.com/RogueException/Discord.Net/blob/dev/src/Discord.Net.WebSocket/DiscordSocketConfig.cs#L23

It's there for you. If you're not already, there's a constructor overload for `DiscordSocketClient` that takes a `DiscordSocketConfig` so you can very easily pass in a config with values that are different than the defaults.

**Comment by NotAkitake** [comment]
https://puu.sh/w5zcQ/cc50fab1c9.jpg

¯\_(ツ)_/¯

**Comment by AntiTcb** [comment]
You need an instance of it, it's not declared statically.

**Comment by NotAkitake** [comment]
```
        public DiscordSocketConfig cfg = new DiscordSocketConfig();
        public DiscordSocketClient client;
        ....
        cfg.MessageCacheSize = 100;
        client = new DiscordSocketClient(cfg);
```

Still the same results as in my first post.

**Comment by LassieME** [comment]
Did you send and then edit the message you're testing after you started your bot or did you just edit it?

**Comment by NotAkitake** [comment]
My bot was online when the message was sent AND when it was edited, if that's what you're asking.

**Comment by AntiTcb** [comment]
That's because your original code could never work. As I stated earlier, you cannot download the previous state of a message that has been updated or deleted. You would need to change your original code from `Cacheable<T,U>.DownloadAsync()` to `Cacheable<T,U>.Value`.

**Comment by DjRand** [comment]
The message has to be in the bot's message cache.   If you're looking to get ANY message "before" content, regardless of your bot being on or offline, you'll need to store the message ID + message content elsewhere (e.g. database).  The Discord API does not send the "before message" when it changes/deletes a message.

**Comment by NotAkitake** [comment]
> The message has to be in the bot's message cache. If you're looking to get ANY message "before" content, regardless of your bot being on or offline, you'll need to store the message ID + message content elsewhere (e.g. database). The Discord API does not send the "before message" when it changes/deletes a message.

Ehm, yes I know that.

> That's because your original code could never work. As I stated earlier, you cannot download the previous state of a message that has been updated or deleted. You would need to change your original code from Cacheable<T,U>.DownloadAsync() to Cacheable<T,U>.Value.

Thanks that fixed it: [code](https://hastebin.com/akotaqirek.cs)
It should be noted that this is a pretty weird way of getting the event to do what you actually want it to.
Maybe it should be re-thought slightly.

**Comment by DjRand** [comment]
Please mark this issue as closed now that you have it figured out.

**Comment by Joe4evr** [comment]
I see this as another reason we should be pointing people to the Quickstart, because this issue is explained [in its comments](https://github.com/RogueException/Discord.Net/blob/dev/docs/guides/getting_started/samples/intro/structure.cs#L32-L35).
