### ISSUE TITLE
OpCode Errors

### ISSUE THREAD

**Issue by MysaNetAdmin** [RogueException/Discord.Net#686]
Hello,
I'm having some unknow warning while running my bot:
[ Warning] Audio #2: Unknown OpCode (13) and
[ Warning] Audio #2: Unknown OpCode (8)

I tried looking for online documentation but couldn't found any..
If anyone can help me pls or give me a doc link...

Thanks in advance ! 💯

**Comment by FiniteReality** [comment]
You can generally ignore 'unknown opcode' warnings from audio. They won't cause your bot to break.

**Comment by MysaNetAdmin** [comment]
Ok thanks ! :)
