### ISSUE TITLE
LogService service with an error

### ISSUE THREAD

**Issue by level6ascend** [RogueException/Discord.Net#693]
>ILoggerFactory does not contain a definition for AddConsole

that

**Comment by level6ascend** [comment]
2 hoorays
okay

bump

**Comment by FiniteReality** [comment]
This is not a Discord.Net issue. If you need help, feel free to join Discord API and chat to us there, in #dotnet_discord-net

**Comment by level6ascend** [comment]
yes but i'm banned from it

**Comment by level6ascend** [comment]
oh yes, I think it's the **`Microsoft.Extensions.Logging.Console`** thing that's missing. **haha my fault**
