### ISSUE TITLE
(v0.9.6) (Pi3) (Mono): You must send data by websocket after websocket is opened!

### ISSUE THREAD

**Issue by AH-1** [RogueException/Discord.Net#695]
So I a Raspberry Pi 3 Model B and I wanted to use it to run a bot made on v0.9.6 for my server. However after countless trail and error, I'm in need of help as I've gotten stuck with this exception.

https://pastebin.com/nTnQ1hs0

Any help would be greatly appreciated. I've already tried everything I could find on this issue, so if you do have any ideas it would be nice if you could give some detailed instructions, since I must be missing something. In any case, thank you for reading this.

**Comment by Flamanis** [comment]
If memory serves, 0.9 only worked with one specific build of mono, and I don't believe anyone remembers what version it was. Unfortunately though, 0.9 is no longer being worked on, and so there is likely never going to be a fix for you.

**Comment by AH-1** [comment]
Ah, I didn't realize it was only one specific version of 0.9. In that case, I'll just work on updating my code for 1.0.0. Thank you.
