### ISSUE TITLE
Character Return when printing messages

### ISSUE THREAD

**Issue by Bojanema** [RogueException/Discord.Net#698]
I am starting to believe this to be an actual issue because after trying everything I can think of it still doesn't work.

I have a command !Test and the command is suppose to print out the following:
Hello
World!

However, the command prints out:
HelloWorld!

It completely ignores "\n" for new lines. Any ideas why?

**Comment by Emzi0767** [comment]
This is very vague. We don't know your D.NET version, what you're trying to do, how you're trying to do it.

Consider attaching that information and a piece of code.

Additionally, nothing in the lib that I can think of strips newline characters.

**Comment by Bojanema** [comment]
Alright, I will get that information to you.
