### ISSUE TITLE
Unhandled Exception on mono DiscoBot.exe on Linux

### ISSUE THREAD

**Issue by TalionOak** [RogueException/Discord.Net#701]
After using mono DiscoBot.exe i got this erro how to fix?
`
Unhandled Exception:
System.TypeLoadException: Could not load type of field 'Discord.DiscordClient:_connectionLock' (0) due to: Could not load file or assembly 'System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. assembly:System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a type:<unknown type> member:<none>
  at DiscoBot.Program.Main (System.String[] args) [0x00001] in <7da083de19434d9a8c628d3e8c963fd7>:0
[ERROR] FATAL UNHANDLED EXCEPTION: System.TypeLoadException: Could not load type of field 'Discord.DiscordClient:_connectionLock' (0) due to: Could not load file or assembly 'System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. assembly:System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a type:<unknown type> member:<none>
  at DiscoBot.Program.Main (System.String[] args) [0x00001] in <7da083de19434d9a8c628d3e8c963fd7>:0
`

**Comment by Emzi0767** [comment]
The fix is to upgrade to 1.0 and use .NET Core.

If you insist on 0.9, then it will only work with mono up to 4.4.2.

**Comment by TalionOak** [comment]
ok

**Comment by TalionOak** [comment]
worked for me on mono 4.4.2

**Comment by TalionOak** [comment]
i used this script @Emzi0767  
apt-get -y update && \
  apt-get -y install \
  wget \
  tar \
  git \
  autoconf \
  libtool \
  automake \
  build-essential \
  mono-devel \
  gettext
wget http://download.mono-project.com/sources/mono/mono-4.4.2.4.tar.bz2 -O mono-4.4.2.4.tar.bz2
tar xvf mono-4.4.2.4.tar.bz2
cd "mono-4.4.2.4/"
./configure
make
make install
