### ISSUE TITLE
Bot works on Windows, cannot connect on Raspbian ("Heartbeat Errored")

### ISSUE THREAD

**Issue by yojc** [RogueException/Discord.Net#703]
Hi,

My friend has written a very simple bot in C# using Discord.net. Source code available here: https://github.com/L-Dogg/Mariusz_Stefan
(nevermind the hardcoded path to keys.json, I've fixed that)

While the bot works well on Windows, I've ran into an issue when trying to run it on Raspbian (using mono) on my Raspberry Pi 1B. The bot is stuck in a connect-disconnect loop, sometimes receiving message "Heartbeat Errored":
```15/06/2017 13:24:28 [    Info] Discord: Discord.Net v1.0.0-rc (API v6)
15/06/2017 13:24:42 [    Info] Gateway: Connecting
15/06/2017 13:24:55 [ Warning] Gateway:
15/06/2017 13:24:55 [    Info] Gateway: Disconnecting
15/06/2017 13:24:55 [    Info] Gateway: Disconnected
15/06/2017 13:24:57 [    Info] Gateway: Connecting
15/06/2017 13:24:57 [ Warning] Gateway:
15/06/2017 13:24:57 [    Info] Gateway: Disconnecting
15/06/2017 13:24:57 [    Info] Gateway: Disconnected
15/06/2017 13:24:59 [    Info] Gateway: Connecting
15/06/2017 13:25:01 [ Warning] Gateway: Heartbeat Errored
15/06/2017 13:25:01 [ Warning] Gateway:
15/06/2017 13:25:01 [    Info] Gateway: Disconnecting
15/06/2017 13:25:02 [    Info] Gateway: Disconnected
15/06/2017 13:25:05 [    Info] Gateway: Connecting
15/06/2017 13:25:05 [ Warning] Gateway:
15/06/2017 13:25:05 [    Info] Gateway: Disconnecting
15/06/2017 13:25:05 [    Info] Gateway: Disconnected
```
Searching for similar issues for the web I've noticed many suggestions about using `certmgr`, I've tried `certmgr -ssl https://gateway.discord.gg` and `certmgr -ssl https://discordapp.com` to no avail. Also tried `mozroots --import --sync`, no luck either.

The bot's discord key seems to be read properly from the file.

Raspbian was installed and updated just today, the mono version I'm using is also the newest available (5.0.1.1)
Tried compiling it with Visual Studio, Mono on Windows, Mono on Linux - no difference.

Any ideas? There must be something trivial I'm missing.

**Comment by Bond-009** [comment]
1.0 doesn't work with mono, you should try with .Net Core 2.0

**Comment by yojc** [comment]
Wow, that was a fast reply.

Ah bugger, that's what I was suspecting. I'll try .Net Core. In the meantime, if anyone has any possible workarounds for Mono please let me know.

**Comment by khionu** [comment]
There are no workarounds.
