### ISSUE TITLE
Get and Send message from and to specific channel and direct message

### ISSUE THREAD

**Issue by StrangerGithuber** [RogueException/Discord.Net#714]
Hello
Sorry if I write this to bad section but I didn't see support menu.
So my question is how can I send and get messages from and to specific channel?
Other is, how can I get direct message and send to direct message?
I try to create a chat bot and my plan is that if someone write a direct message to chatbot then the chat bot answer to message in the same direct message.
Same with channel. For example I create a channel "test" channel and someone write something in "test" channel then the bot answer to "test" channel.

I tried somehow create a solution to this, but the chat bot get messages from everywhere not from specific parts.

My code is this:
`
```
client.MessageReceived += async (s, e) =>
          {
              if (!e.Message.IsAuthor)
              {
                  var responseString = await httpclient.GetStringAsync("http://api.program-o.com/v2/chatbot/?" + e.Message.Text + "&convo_id=exampleusage_1231232&format=json");
                  Botvalasza botvalasza = JsonConvert.DeserializeObject<Botvalasza>(responseString);
                  Console.WriteLine(botvalasza.botsay);

                  var channel = e.Server.FindChannels("test", ChannelType.Text).FirstOrDefault();
               
                  await channel.SendMessage(botvalasza.botsay);
              }
          };
```
`

This code send to specific channel answers but not to direct messages and this get all messages from all channels and direct messages.
Thank you in advance for your answer :)

**Comment by Emzi0767** [comment]
This is the best translation I could think of:

Your bot receives a message. Now you're trying to get that message, and respond in the channel it came from, correct? On top of that, you're using some cleverbot-like API. 

You got the API part down. Now for the response part.

If this is the case, EventArgs for `.MessageReceived` event contain the channel the message came from. With a little bit of intellisense, you can make it respond in the context's channel.

**Comment by StrangerGithuber** [comment]
Ok, I try explain better way with examples.
1.) I create a channel which is "test" channel
2.) In the test channel the chatbot get the message (not from other channel) and answer in the "test" channel
3.) If someone want ask the chatbot in direct message(DM, private message, PM) then the chatbot get the message from the direct message and answer to same user in direct message.

So my question how can I get "test" channel's messages and how can I get direct messages and send direct messages?

**Comment by Emzi0767** [comment]
In the message receive handler you check whether the id of the channel matches the ID of your desired channel, or if it's a DM channel. If neither is true, just don't do anything else.

If one of the criteria matches, do your API call and then post the response to the channel the message came from.

You can get the channel's ID by enabling developer mode, right-clicking the channel, and selecting Copy ID.

**Comment by StrangerGithuber** [comment]
I am no professional programmer. :( Can you share how can I check if the message come from DM or test channel?
I would be very grateful. :)

**Comment by Emzi0767** [comment]
Look through the documentation for the library. The version you're using is ancient, and nobody provides support for it anymore, so you're on your own.

**Comment by StrangerGithuber** [comment]
Ok, I found a solution. :D If someone want same thing as I then here is the solution.

If you want check if the message come via DM then you can use this:
```
if (e.Channel.Name == e.User.PrivateChannel.Name)
{
//your code
}
```

If the message come via specific channel then here is the code:

```
if (e.Channel.Name == "test")
{
//your code
}
```

**Comment by Emzi0767** [comment]
This... isn't really correct. `Channel.IsPrivate` indicates whether it's a DM channel or not.

**Comment by Bradisswag** [comment]
@LeaderSoul May i ask how and where you imported the api? i cant seem to find where you found it from

**Comment by Chrisdbhr** [comment]
For anyone who arrived here from Google like me:

I managed to check if a message is a _Direct Message_ casting the source message channel to **IDMChannel**. An example:

```c#
if (socketMessage.Channel is IDMChannel dmChannel) {
	// if arrived here, it is a DM
}
```
