### ISSUE TITLE
Commands count is doubled

### ISSUE THREAD

**Issue by xXBuilderBXx** [RogueException/Discord.Net#720]
The commandservice commands count is being doubled so instead of 2 commands it shows 4.

**Comment by AntiTcb** [comment]
Some example code that shows this behavior would be lovely, as I could not reproduce this behavior.

**Comment by FiniteReality** [comment]
Likewise, could not reproduce.

**Comment by xXBuilderBXx** [comment]
Could not reproduce this again idk something was being weird but i will close this.
