### ISSUE TITLE
IUserMessage#GetReactionUsersAsync() should take an IEmote instead of a string.

### ISSUE THREAD

**Issue by AntiTcb** [RogueException/Discord.Net#730]
Was forgotten about during the emoji redesign.

**Comment by SapiensAnatis** [comment]
Could this be why `var ReactionDataTick = await PossiblyExistingMessage.GetReactionUsersAsync("✔️");` is producing a 10014: Unknown Emoji error for me?

edit: no, it was something stupid to do with how the tick emoji got pasted in and actually represented two characters
