### ISSUE TITLE
IUserMessage.Reactions[Emoji].ReactionCount only accurate as of when IUserMessage was retrieved

### ISSUE THREAD

**Issue by SapiensAnatis** [RogueException/Discord.Net#749]
I'm storing messages in classes in a Ready handler and checking the reaction data later to make decisions. Unfortunately, it seems that this data does not reflect changes made to the reactions after the Ready handler concludes. 
I'm not an expert, but I'd assume some sort of caching is going on here, so as not to flood the API with requests every time this data is requested.

However, for what I'd like to do, up-to-date reaction data for a message which was stored in a variable at loading time is important. I can understand both sides of this issue; if this is intentional, perhaps we could add a method under IUserMessage to fetch new reaction data?

Alternatively, I could just be being stupid and there's an easy way to fix this. I would be delighted to hear that this is the case if so, because it means an easier fix for me and less waiting 😄

**Comment by khionu** [comment]
Duplicate of #684 and resolved by #723

**Comment by SapiensAnatis** [comment]
Correct me if I'm wrong, but reading #684 it seems that the issues aren't the same. My issue is that the reaction counts are static for a message previously retrieved when I think there should at least be a way to refresh the reaction data. That issue seems to be about retrieving a message and immediately checking the reaction count to see that it's wrong.

Either way, I was using 1.0.1 when I ran into this, which supposedly contains that fix.

**Comment by Bond-009** [comment]
You can just download the message again with `IMessageChannel.GetMessageAsync()`, than it will have the latest reaction data.

**Comment by SapiensAnatis** [comment]
Actually, I suppose you're right. This is what I ended up doing, and I think it's preferable to making reaction data requests async. I'll close.

My only qualm is that I'm now performing a LINQ check to see if the message that had a reaction change was relevant, so that happens every time someone reacts to anything in any guild...which could be slow.
