### ISSUE TITLE
Verify login state on client functions

### ISSUE THREAD

**Issue by RogueException** [RogueException/Discord.Net#76]
~~Also maybe start SocketClient with a blank DataStore? Shouldn't be null.~~ Added

**Comment by RogueException** [comment]
Specifically, we should not be able to sent and outgoing request without a token

**Comment by RogueException** [comment]
Grabbed by Digi

**Comment by RogueException** [comment]
DiscordRestClient/DiscordSocketClient/DiscordRpcClient shouldn't send anything if not logged in.

Scratch what I said about connection state, just worry about LoginState.

**Comment by khionu** [comment]
What's the status on this?

**Comment by RogueException** [comment]
I think there was a mixup? Not sure if Digi is actually working on this.

**Comment by RogueException** [comment]
Added in https://github.com/RogueException/Discord.Net/commit/ae867451b5cef980a1269f928d11ba86c27f7464
