### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Poyser1911** [RogueException/Discord.Net#763]
https://gyazo.com/126e721ee50aaa2352c6a2de343764c3

how do i make the bot send messages looking like that?
what is it called/where is the docs?

**Comment by MarkusG** [comment]
Look into the `EmbedBuilder` class. Also, these questions are better suited for our channel in the [Discord API guild](https://discord.gg/0SBTUU1wZTVjAMPx).

**Comment by vasuz** [comment]
https://discord.foxbot.me/docs/api/Discord.EmbedBuilder.html

**Comment by khionu** [comment]
I think this can be closed

**Comment by Poyser1911** [comment]
yea i got it thats all 👍
