### ISSUE TITLE
How to ban a user

### ISSUE THREAD

**Issue by DevBlocky** [RogueException/Discord.Net#769]
#  Banning of a user
I don't know if I am just dumb or if there is no feature for it but it seems to me that there is no method to ban a user from a discord server. I see one for kick but no ban.
If anyone would point to me what class it would be in (ie. `SocketUser`, `SocketGuildUser`, `RestUser`). I found a class called `RestBan` but I couldn't create a constructor because of the security 

> Banning a user would help me a lot in my application and I would seriously like to be pointed to, or request this feature.

### ~bwookzy

**Comment by Mezo** [comment]
SocketGuild.AddBanAsync() ?

**Comment by DevBlocky** [comment]
God damnit I didn't think that it would be in the server...

I'm stupid and thank you @Mezo

**Comment by Yucked** [comment]
Close the issue? @bwookzy

**Comment by Joe4evr** [comment]
Also, next time ask minor questions like these on [Discord API#dotnet_discord-net](https://discord.gg/0SBTUU1wZTVjAMPx) and leave the issues to *actual* bugs in the lib.
