### ISSUE TITLE
User-defined behavior in case of ambiguous command match

### ISSUE THREAD

**Issue by Joe4evr** [RogueException/Discord.Net#799]
In some cases, a user may want to have some custom behavior in case more than one command matched the parsing. I have an idea on how to implement this when **all** commands are from the same module, at least.

The first part of this is a new type: `AmbiguityResolveResult`
```cs
namespace Discord.Commands
{
    public class AmbiguityResolveResult : IResult
    {
        // IResult:
        public CommandError? Error { get; }
        public string ErrorReason { get; }
        public bool IsSuccess { get; }

        // Instantiation methods
        public static AmbiguityResolveResult FromError(string reason); //Don't select any match
        public static AmbiguityResolveResult FromSuccess(CommandMatch match); //Select this CommandMatch
        public static AmbiguityResolveResult Default(); // Do what the lib would've done anyway
    }
}
```

The second part is a method that will return that result type. Again, it would only matter if all the potential matches are from the same module.

If we can instantiate the module class in advance (and it makes sense to do so), I propose something like this be put on `ModuleBase<T>`:
```cs
protected virtual Task<AmbiguityResolveResult> OnAmbiguousCommand(IEnumerable<CommandMatch> matches)
{
    return Task.FromResult(AmbiguityResolveResult.Default());
}
```
which can then be overriden by users to do the appropriate thing. The `matches` would come in the order of priority.

If not, then search the module for a static method with the appropriate signature annotated with some kind of marker, ie. `[AmbiguityResolver]`. Example:
```cs
[AmbiguityResolver]
public static Task<AmbiguityResolveResult> AmbiguityResolver(IEnumerable<CommandMatch> matches, ICommandContext context); // Method name becomes irrelevant
```
We could do the appropriate reflection for this up-front and store it inside the `ModuleInfo` instance.
Open question on this version: Should we only accept `public`, or should the access modifier not matter?

Between the two options:
* Virtual
  * Pro: Full control of the method signature
  * Con: Has to execute *after* `SetContext()` at least, maybe even after `BeforeExecute()` which *could* quickly become 🍝 
* Static
  * Pro: Reflection for the method can be front-loaded when the module is registered
  * Pro: No need to instantiate the module when not needed in case the user would return a failed result
  * Con: Has to rely on the user to make a method with the appropriate signature

Thoughts? Pinging @FiniteReality since he did some work on ambiguous matches earlier.

**Comment by quinchs** [comment]
@Cenngo Can you take a look at this?

**Comment by Cenngo** [comment]
Isn't this the exact problem that `MultiMatchHandling` option was supposed to solve? Maybe we can add a new enum value to `MultiMatchHandling` that will directly fallback onto a pool of AmbiguityResolvers if `CommandError.MultipleMatches` is encounterd.
