### ISSUE TITLE
Emoji.Parse should accept Unicode Equivalent

### ISSUE THREAD

**Issue by khionu** [RogueException/Discord.Net#802]
At the moment, `Emoji.Parse("💙")` (`:blue_heart:` for those who can't see it) throws an exception, though it's [valid to post](http://i.imgur.com/bcgNVRp.png) through the REST API.

**Comment by khionu** [comment]
Also to note, if I had the Emoji object for `:blue_heart:`, `Emoji.Parse(blueHeart.Name)` would throw, because the Unicode is what is passed as the name.

**Comment by FiniteReality** [comment]
Emoji.Parse doesn't exist? If you're using Emote, then that's for custom emoji.

**Comment by khionu** [comment]
Lesson of the day..... Whoever came up with "Emoji" vs "Emote" is evil, and those words need to be kept as far apart as possible

**Comment by Joe4evr** [comment]
`Emoji` is the term used in the Unicode standard. `Emote` is the term that Twitch uses, which is subsequently used by Discord for their Twitch integration.

Bottom line: Blame Twitch. 🙃
