### ISSUE TITLE
The SocketClient should allow you to force an HTTP request

### ISSUE THREAD

**Issue by AntiTcb** [RogueException/Discord.Net#803]
Currently, the only way to obtain an uncached member is by calling `SocketGuild#DownloadUsersAsync()`.

The current implementation should probably be modified to mirror how cached vs uncached messages are handled. 
https://github.com/RogueException/Discord.Net/blob/3c1e76615e1ef37cf3deb9aa9ab3e3b2f2064e41/src/Discord.Net.WebSocket/Entities/Channels/SocketTextChannel.cs#L52-L60

**Comment by Joe4evr** [comment]
Isn't this precisely what `RequestOptions` is for?

**Comment by AntiTcb** [comment]
As far as I'm aware of, there are very few places, if any, in WebSocket where `CacheMode` is used properly (I looked at this a few months ago). Either there are two separate methods (the one that performs request just simply being an implicit implementation from the parent interface), or, cases like this where requesting is simply not present.

That probably should be the bigger issue to look at here.

**Comment by AntiTcb** [comment]
https://github.com/discordapp/discord-api-docs/pull/661

This should trivialize pulling in uncached members.
