### ISSUE TITLE
Discord API v6+ and Audio

### ISSUE THREAD

**Issue by HellGate94** [RogueException/Discord.Net#813]
In August the Discord API for anything below v6 will shut down. What does that mean to Discord.Net.Audio since the last version is still 0.9.6 and also deprecated. As far as i saw 0.9.6 uses the v3 API so it should break.

Is there a way to use the audio part it with the new versions? if not is there something planed?
its a core feature of my bot and it would really kill it

Thanks

**Comment by Still34** [comment]
Audio related APIs are in the new WebSocket package already.

**Comment by AntiTcb** [comment]
Audio is now combined with the Discord.Net.WebSocket package. 

Questions of this nature are definitely more appropriate for the [Discord API Guild](https://discord.gg/discord-api) in the Discord.Net rather than opening an issue.

**Comment by HellGate94** [comment]
my bad sorry. thanks for the info i missed that
