### ISSUE TITLE
Message timestamp always shows 12:00 AM

### ISSUE THREAD

**Issue by xXBuilderBXx** [RogueException/Discord.Net#833]
Im currently using the latest alpha version v2 833 and the message timestamp is always returning 12 AM as seen in the screenshot
https://i.imgur.com/CGlrMmZ.png

**Comment by AntiTcb** [comment]
Not a library issue. Using the `.Date` property on a `DateTime` gives you a new `DateTime` object without the time values.

**Comment by xXBuilderBXx** [comment]
Oh.......
