### ISSUE TITLE
Getting a user ID based on via nickname / on-screen name?

### ISSUE THREAD

**Issue by CoderReece** [RogueException/Discord.Net#838]
I hate posting my question here but i'm having trouble finding any information on something like this. I would like to get a users ID based from a string of their username.

**Comment by Still34** [comment]
You can LINQ through the Users collection within Guilds or use `DiscordSocketClient#GetUser` whose overload contain a method for username & discrim lookup.

**Comment by TheNoodleMummy** [comment]
you can always join https://discord.gg/discord-api and join the channel #dotnet_discord-net to ask questions ;)

**Comment by FiniteReality** [comment]
Seems like this has been resolved, closing for now.
