### ISSUE TITLE
Voice example: "audio_ffmpeg.cs" errors (CS0433)

### ISSUE THREAD

**Issue by jakedacatman** [RogueException/Discord.Net#840]
The example of how to run FFmpeg (https://github.com/RogueException/Discord.Net/blob/dev/docs/guides/voice/samples/audio_ffmpeg.cs) has the error "The type 'IAudioClient' exists in both 'Discord.Net.Audio, Version=0.9.6.0, Culture=neutral, PublicKeyToken=null' and 'Discord.Net.Core, Version=1.0.2.0, Culture=neutral, PublicKeyToken=null'". I am using the regular Discord namespace and the Discord.Audio namespace. When I removed the reference to the Discord.Audio namespace, I had errors. When I removed the Discord.Net.Core dll refererence, I had errors.

**Comment by AntiTcb** [comment]
Uninstall the Discord.Net.Audio package, it's deprecated. All audio related classes are packaged into v1.0.0+ versions of Discord.Net.WebSocket.

**Comment by jakedacatman** [comment]
Let's try that.

**Comment by jakedacatman** [comment]
Huh. I removed the dll reference to Discord.Net.Audio, but kept the namespace one, and I'm error free.

**Comment by AntiTcb** [comment]
It's always best to come to the [Discord API guild](https://discord.gg/discord-api) into the #dotnet_discord-net channel rather than opening an issue for things like this.

**Comment by jakedacatman** [comment]
Alright, will keep note of that for future reference. Thank you!
