### ISSUE TITLE
Read Permission -> View Permission

### ISSUE THREAD

**Issue by khionu** [RogueException/Discord.Net#854]
Given the same bitvalue is now used to determine whether you can see a voice channel, I propose creating a new value, named appropriately, giving it the bitvalue, then pointing the old value to the new, marking it as deprecated.

**Comment by Joe4evr** [comment]
Also have to reflect it in the `ChannelPermissions` struct. So the proposed diff is:
```diff
public enum ChannelPermission
{
+   [Obsolete("Use ViewChannel instead.")]
    ReadMessages = ...,

+   ViewChannel = ReadMessages,
}

public struct ChannelPermissions
{
+   [Obsolete("Use ViewChannel instead.")]
    public bool ReadMessages => ...;

+   public bool ViewChannel => ReadMessages;
}
```

**Comment by Chris-Johnston** [comment]
`ChannelPermissions` contains `ManageChannel` while in the API and in the `ChannelPermissions` and `GuildPermissions` enums it is `ManageChannels`. Should we also obsolete `ManageChannel` in `ChannelPermissions` and add `ManageChannels`?

**Comment by Joe4evr** [comment]
Ping @foxbot for input.
