### ISSUE TITLE
Client does not reconnect after websocket closed (due to #850)

### ISSUE THREAD

**Issue by RheaAyase** [RogueException/Discord.Net#856]
As the title says, after an occurrence of the issue #850 the DiscordSocketClient does not reconnect and remains in a ... stuck idle state.

_(The client.Disconnected event does fire and is the last activity observed.)_

**Comment by tash649** [comment]
good afternoon. The problem is not solved yet?

**Comment by velddev** [comment]
I'm having this issue too, causing my bot to completely freeze up for several hours tops when I am asleep. 

![](https://i.imgur.com/1wRfCbi.png)

**Comment by tash649** [comment]
you have bot after this continues to work? Or not?

**Comment by velddev** [comment]
No, the bot no longer responds on the corresponding shards.

**Comment by tash649** [comment]
We can try to monitor the Disconnect event and start the timer for one minute at that event. If the connection state is not equal to "Connected" or equal to "Disconnected" then just restart the bot.

**Comment by velddev** [comment]
It seems this issue has been mostly resolved in 2.0.0-beta. Atleast for my side it did.

![](https://i.imgur.com/kkuWbqh.png)

**Comment by tash649** [comment]
I do not have the opportunity to use the beta version. But developers could write in this problem that it is fixed in the new version.

**Comment by tash649** [comment]
In what program did you form this chart?

**Comment by RheaAyase** [comment]
It is not fixed.

**Comment by RheaAyase** [comment]
More recent issue #960 has more activity, so I'll close this one as a duplicate of that.
