### ISSUE TITLE
client.MessageReceived += HandleCommand(); problem.

### ISSUE THREAD

**Issue by htbrown** [RogueException/Discord.Net#858]
For some reason Visual Studio is saying that client.MessageReceived += HandleCommand(); is incorrect. I got it from [this](https://www.youtube.com/watch?v=hE6ZFkSWbNc) video and it's not working. The errors that VS is giving me are 
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0029	Cannot implicitly convert type 'System.Threading.Tasks.Task' to 'System.Func<Discord.WebSocket.SocketMessage, System.Threading.Tasks.Task>'	ChatterBot new	H:\People's Folders\Hayden\Visual Studio Projects\ChatterBot new\ChatterBot new\ChatterBot new\Program.cs	45	Active
and
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS7036	There is no argument given that corresponds to the required formal parameter 'msgParam' of 'Program.HandleCommand(SocketMessage)'	ChatterBot new	H:\People's Folders\Hayden\Visual Studio Projects\ChatterBot new\ChatterBot new\ChatterBot new\Program.cs	45	Active

**Comment by Joe4evr** [comment]
Don't put `()` after the method name when subscribing a method to a handler.

**Comment by htbrown** [comment]
Oh... Thanks!
