### ISSUE TITLE
Released assemblies aren't strongly named

### ISSUE THREAD

**Issue by Cyberboss** [RogueException/Discord.Net#875]
This prevent dependents projects that are strongly named from using the provided assemblies. Assemblies that aren't strongly named also can't be installed into the Global Assembly Cache.

See [here](https://docs.microsoft.com/en-us/dotnet/framework/app-domains/how-to-sign-an-assembly-with-a-strong-name) for assembly signing instructions

**Comment by FiniteReality** [comment]
According to [this](https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/strong-name-signing.md), strong name signing is no longer necessary, and isn't even recommended in some cases.

I'm also fairly sure the GAC is only a thing in .NET Framework, which really isn't our main target (our main target is .NET Core) so the only disadvantage of not being strongly named is the lack of support for projects which are strongly signed.

**Comment by Cyberboss** [comment]
Fair enough, we're just going to use a digital cert instead
