### ISSUE TITLE
Simple way to get bot to realize a message starts with someone mentioning the bot?

### ISSUE THREAD

**Issue by Straafe** [RogueException/Discord.Net#881]
message.content.StartsWith("BotName") doesn't work, what's the easiest way to do this?

**Comment by MarkusG** [comment]
`Discord.Commands` has an extension method on `IUserMessage` called `HasMentionPrefix()`. Also, these types of questions are better suited for our channel in the [Discord API guild](https://discord.gg/discord-api) (#dotnet_discord-net)

**Comment by Straafe** [comment]
Thanks, I will try over there and see if I can't get something working using your tip.

Edit:

For anyone else looking for a quick solution, this worked, but I am guessing it is not a very good implementation (this runs any time it doesn't detect other text commands, not using Discord.Commands but just looking at the message string):

`                SocketSelfUser selfUser = _client.CurrentUser;

                int argID = 0;

                IUserMessage msg = message as IUserMessage;

                if (msg.HasMentionPrefix(selfUser as IUser, ref argID))  
                {

                    await message.Channel.SendMessageAsync("I heard my name in this message: " + message.Content);

                }`


Also, for anyone else comparing strings, it looks like the mentions use an ID instead of the text you might expect, for example "<@365962747216587458>" so you would have to look for that
