### ISSUE TITLE
Discord disconnecting randomly

### ISSUE THREAD

**Issue by Zeenyoo** [RogueException/Discord.Net#882]
I'm having disconnecting problems, i'm normally talking with my friends then randomly i can't do anything else, see other servers or type in any chat, they don't load, every other thing im doing works fine, i can still play and my internet speed is totally fine, once it 'disconnects' i can still talk and hear my friends and they can also hear me normally, and it stays like that for 1 or 2 mins and it sends me to loading screen... help please!

**Comment by TheNoodleMummy** [comment]
you do know this isnt Discord github right this is discord.net a library used to make bots for discord

**Comment by AntiTcb** [comment]
You're going to want to get a hold of [Discord's Support Team](https://support.discordapp.com/hc/en-us). This is not an issue related to Discord.Net.

**Comment by Zeenyoo** [comment]
Oh someone linked me here for support, sorry!
