### ISSUE TITLE
Posting emoji using code

### ISSUE THREAD

**Issue by botiapa** [RogueException/Discord.Net#893]
I want to add a reaction to a message using code. The emoji I want to add is 1⃣ (`:one:`) I tried using the Emoji.Parse method but it didn't work. 

Thanks.

**Comment by Joe4evr** [comment]
You need to put in the Unicode emoji text, not the `:name:` kind of text. You can find this by escaping the name in the Discord client, or by going to [Emojipedia](https://emojipedia.org/keycap-digit-one/)

**Comment by botiapa** [comment]
What do you mean in escaping the name in the Discord client?

**Comment by Joe4evr** [comment]
I mean that you should type `\:someemojiname:`.
Also, you should ask these questions in our channel (#dotnet_discord-net) on the Discord API server (link in the [README](https://github.com/RogueException/Discord.Net/blob/dev/README.md)).

**Comment by botiapa** [comment]
And also this is an "Emoji sequence", if you check it on Emojipedia. How should I go about that?

**Comment by botiapa** [comment]
And If I escape it it says the same thing. Like `:zero:`

**Comment by FiniteReality** [comment]
The `0️⃣ ` emoji is actually a combination of multiple Unicode codepoints, which is likely why the backslash-trick doesn't work.

I'd suggest using something like [Emojipedia](https://emojipedia.org/keycap-digit-zero/), like Joe4evr suggested, as they show you how to create the emojis. For example, the page I linked says you should use `U+0030 U+FE0F U+20E3` to create the emoji, so you would use a string such as `"\x0030\xFE0F\x20E3"` to create the emoji.
