### ISSUE TITLE
Migrating from 0.9.6? API uses completely different syntax

### ISSUE THREAD

**Issue by Aida-Enna** [RogueException/Discord.Net#900]
Hey all - I've been using this API (and loving it!). Discord was rejecting my bot's connection, starting last night, citing "code 4012: Requested gateway version is no longer supported or invalid". I updated the API to it's current version 1.0.1 and my entire bot is throwing errors left and right. It appears the entire syntax/how the API library works has been completely... changed. The bot is sort of essential to our work and I'm immensely confused by all the changes to the API. I located the "migrating from 0.9x guide", but this new syntax is waaaaay over my head.

Is there anywhere in the documentation where I can see examples of sending messages to a channel via ID (located in the same server the bot is in), and editing messages? I tried all the different types of messages but none of them seem to support editing, aside from one which requires the string to be a task instead of a string?

I'm really lost here, and a few code samples would go a long way. Thanks.

Alternatively, is there any way I can use the 0.9.6 API and still access discord like before?

**Comment by TheNoodleMummy** [comment]
no discord has stopped APIV5 the one 0.9 used your only option is to start over with 1.0.2 (1.0.1 is broken) 
feel free to join https://discord.gg/discord-api and look for #dotnet_discord-net

**Comment by Aida-Enna** [comment]
That's unfortunate, but I understand. I'll go ahead and remake it, better and faster, stronger, etc. Thanks for the help, closing this issue!

**Comment by asm512** [comment]
If it helps there's a lot of public bots using the new Syntax, and most of the time you can find what you're looking for by searching the channel's messages
