### ISSUE TITLE
"Could not send request", HTTP Login Error

### ISSUE THREAD

**Issue by Kronix69** [RogueException/Discord.Net#902]
So I have been playing with the infamous bot DEA but i don't really like the new rewritten one so I wanted to use the old one so I got the source of it have put my token database userid and blah blah blah.
Now when i try to run it, it outputs === dea === and then it just creates an exception inside visual studio saying:

> `System.Net.Http.HttpRequestException
>   HResult=0x80131040
>   Message=An error occurred while sending the request.
>   Source=System.Private.CoreLib
>   StackTrace:
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
>    at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Discord.Net.Rest.DefaultRestClient.<SendInternalAsync>d__14.MoveNext()
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Discord.Net.Rest.DefaultRestClient.<SendAsync>d__11.MoveNext()
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Discord.Net.Queue.RestRequest.<SendAsync>d__19.MoveNext()
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Discord.Net.Queue.RequestBucket.<SendAsync>d__18.MoveNext()
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Discord.Net.Queue.RequestQueue.<SendAsync>d__14.MoveNext()
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Discord.API.DiscordRestApiClient.<SendInternalAsync>d__62.MoveNext()
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Discord.API.DiscordRestApiClient.<SendAsync>d__57`1.MoveNext()
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Discord.API.DiscordRestApiClient.<GetVoiceRegionsAsync>d__138.MoveNext()
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Discord.WebSocket.DiscordSocketClient.<OnLoginAsync>d__89.MoveNext()
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Discord.Rest.BaseDiscordClient.<LoginInternalAsync>d__34.MoveNext()
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at Discord.Rest.BaseDiscordClient.<LoginInternalAsync>d__34.MoveNext()
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Discord.Rest.BaseDiscordClient.<LoginAsync>d__33.MoveNext()
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at DEA.Program.<RunAsync>d__6.MoveNext() in C:\Users\Kronix\Desktop\DEA\src\Program.cs:line 60
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at DEA.Program.Main() in C:\Users\Kronix\Desktop\DEA\src\Program.cs:line 21
> 
> Inner Exception 1:
> FileLoadException: Could not load file or assembly 'System.Collections.NonGeneric, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

`
The code of the page where it happens is:

> `using DEA.Database.Models;
> using DEA.Services;
> using DEA.Services.Handlers;
> using DEA.Services.Static;
> using Discord;
> using Discord.Commands;
> using Discord.Net;
> using Discord.WebSocket;
> using Microsoft.Extensions.DependencyInjection;
> using MongoDB.Driver;
> using System;
> using System.Diagnostics;
> using System.Threading.Tasks;
> 
> namespace DEA
> {
>     internal sealed class Program
>     {
>         private static void Main()
>         {
>             new Program().RunAsync().GetAwaiter().GetResult();
>         }
> 
>         private readonly IServiceProvider _serviceProvider;
>         private readonly ServiceManager _serviceManager;
>         private readonly DiscordSocketClient _client;
>         private readonly CommandService _commandService;
> 
>         public Program()
>         {
>             _serviceManager = new ServiceManager();
> 
>             _serviceManager.InitiliazeData();
> 
>             _client = new DiscordSocketClient(new DiscordSocketConfig()
>             {
>                 MessageCacheSize = 10,
>                 TotalShards = _serviceManager.Credentials.ShardCount,
>                 AlwaysDownloadUsers = true,
>             });
> 
>             _commandService = new CommandService(new CommandServiceConfig()
>             {
>                 CaseSensitiveCommands = false,
>                 LogLevel = LogSeverity.Error,
>                 DefaultRunMode = RunMode.Async,
>             });
> 
>             _serviceProvider = _serviceManager.ConfigureServices(_client, _commandService);
>         }
> 
>         private async Task RunAsync()
>         {
>             Logger.NewLine("===   DEA   ===");
>             Logger.NewLine();
> 
>             var sw = Stopwatch.StartNew();
>             try
>             {
>                 await _client.LoginAsync(TokenType.Bot, _serviceManager.Credentials.Token);
>             }
>             catch (HttpException httpEx)
>             {
>                 Logger.Log(LogSeverity.Critical, $"Login failed", httpEx.Reason);
>                 Console.ReadLine();
>                 Environment.Exit(0);
>             }
> 
>             await _client.StartAsync();
>             sw.Stop();
>             Logger.Log(LogSeverity.Info, "Successfully connected", $"Elapsed time: {sw.Elapsed.TotalSeconds.ToString("N3")} seconds.");
> 
>             Logger.Log(LogSeverity.Info, "MongoDb Connection Verification", "Test connection has commenced...");
>             sw.Restart();
>             await _serviceProvider.GetService<IMongoCollection<User>>().CountAsync(y => y.Cash > 0);
>             sw.Stop();
>             Logger.Log(LogSeverity.Info, "Test connection has succeeded", $"Elapsed time: {sw.Elapsed.TotalSeconds.ToString("N3")} seconds.");
> 
>             _serviceManager.AddTypeReaders(_commandService, _serviceProvider);
>             Logger.Log(LogSeverity.Info, "Addition of custom Type Readers", $"Successfully initialized.");
> 
>             _serviceManager.InitializeTimersAndEvents(_serviceProvider);
>             await new CommandHandler(_commandService, _serviceProvider).InitializeAsync();
>             Logger.Log(LogSeverity.Info, "Events and command handler successfully initialized", $"Client ready.");
> 
>             await Task.Delay(-1);
>         }
>     }
> }
> `

I have put a function that outputs right after every line and noticed it happens at the loginasync, i would appreciate if someone would help me fix this!

**Comment by AntiTcb** [comment]
You should probably ask the people behind DEA if you're going to work with their bot as a template.

But from casually glancing at the stack trace, looks like it might just be an issue with a dependency not being loaded properly.

**Comment by Kronix69** [comment]
@AntiTcb I followed their video on how to run it and it just doesnt work

**Comment by AntiTcb** [comment]
Like I said, if it's their thing that you're using, you're going to get much better support from them, as they might have introduced something into their design that affects something that we're not accountable for.

**Comment by Kronix69** [comment]
Im pretty sure there are not much ways to contact them so...

**Comment by AntiTcb** [comment]
There's not much I can tell you. We're not the support for any bots that use this library, only the library itself. As I said previously, it looks like a dependency isn't being loaded properly that should be getting pulled from .NET's core libraries. If the project is built using the .NET Framework, this happens occasionally, and you research into alleviating the issue. It might be as simple as attempting to restore the project's dependencies, or possibly making it a .NET Core project.

**Comment by Kronix69** [comment]
1. It is an error with the api thought since it happens with the login giving an error so to be honest you must help me
2. How am i supposed to do that?

**Comment by Kronix69** [comment]
Nevermind I fixed it by changing the targeted framework from netcore 1.1 to netcore 2.0. Thank though

**Comment by khionu** [comment]
1) Help isn't ever obligatory; this is an OSS lib with volunteer contributors and maintainers.

2) Since your issue is resolved, it would be proper to close the issue.
