### ISSUE TITLE
Unknown Guild Channel Type on start up

### ISSUE THREAD

**Issue by MrEnvii** [RogueException/Discord.Net#903]
I am using a template that I had found for Discord.Net, I have added my token and it connects to the Discord Server but when it loads I get an InvalidOperationException of Unknown guild channel type.

The App continues but when I write a message in a channel on the server, it gives me an Unknown Channel Warning. 

Code:
The Error seems to occur within the _discord.StartAsync(); method.
![image](https://user-images.githubusercontent.com/19834082/33894281-83a448c6-df55-11e7-9ef2-2881964fd65c.png)

Console:
![image](https://user-images.githubusercontent.com/19834082/33894356-afeddfaa-df55-11e7-9207-2968a5766ffc.png)

Not sure if this is an issue with something that I have done or something in the Discord.Net code?

**Comment by TheNoodleMummy** [comment]
if you are not on Discord.NET 1.0.2 update to it that should fix it also feel free to join [Discord API](
https://discord.gg/discord-api) and look for #dotnet_discord-net if you have any more questions

**Comment by MrEnvii** [comment]
Yep, that was the issue, Thanks. 

Sorry about that, I thought I was on the latest version.

**Comment by TheNoodleMummy** [comment]
your welcome (please close the issue as its been resolved)
