### ISSUE TITLE
DiscordClient throws an exception since Discord.NET 1.0.2 update

### ISSUE THREAD

**Issue by notcarksss** [RogueException/Discord.Net#905]
`_client = new DiscordClient();
        _client.UsingAudio(x => // Opens an AudioConfigBuilder so we can configure our AudioService
        {
            x.Mode = AudioMode.Outgoing; // Tells the AudioService that we will only be sending audio
        });
            _client.Log.Message += (s, MessageEvent) => Console.WriteLine($"[{MessageEvent.Severity}] {MessageEvent.Source}: {MessageEvent.Message}"); // Log errors/info to console`

The _client = new DiscordClient(); throws an exception error: The type or namespace DiscordClient could not be found, are you missing a using directive or assembly reference

I've checked and I cant understand why its throwing that error

**Comment by Anu6is** [comment]
DiscordClient doesn't exist in 1.0.+
It's not DiscordSocketClient

**Comment by Yucked** [comment]
Read the docs: https://discord.foxbot.me/docs/
0.9.6 != 1.0.2
You will have to rewrite your bot completely.

**Comment by notcarksss** [comment]
Okay, I've recently updated due to an error so Ill re write it now. I didn't realize this until now so thanks for the help :)

**Comment by Yucked** [comment]
You're welcome. Please close this issue.

**Comment by notcarksss** [comment]
I have also found another reference issue,  public static IAudioClient _vClient;
The type IAudioClient exists in both Discord.Net.Audio version 0.9.6 and Discord.Net.Core 1.0.2,

**Comment by notcarksss** [comment]
I'll use the documentation to rewrite the bot. Thanks for helping anyway P
