### ISSUE TITLE
After updating Discord.net nuget packages, all bots that were made previous to 1.0.2 now throw out a large list of errors, as if it was programmed entirely incorrectly according to the new packages. 

### ISSUE THREAD

**Issue by FoxAndRoses** [RogueException/Discord.Net#908]
This has been an issue for me, for more than 2 months, I cannot find the solution, and it seems as though I would need to remake every bot. 
As a Content Creator this is a very big backpedal; therefore, I am wondering if there is a simple solution to a complex problem.

**Comment by Anu6is** [comment]
Discord no longer support the gateway version that 0.9 operates on. All bots MUST be updated to 1.0.+ in order to connect to the discord gateway successfully. This would essentially mean a rewrite of your existing bots.
https://discord.foxbot.me/docs/ - should help you get started.

**Comment by MarkusG** [comment]
If your previous bots were made using Discord.Net 0.x, yes, you will have to rewrite them. 1.0 is a complete rewrite of the library, therefore you'll have to rewrite your bots. See [the docs](https://discord.foxbot.me/docs/guides/getting_started/intro.html) for a guide on creating a 1.0 bot to get a feel for how 1.0 is structured, then start rewriting your bots.

**Comment by FoxAndRoses** [comment]
So the update did in fact kill off all previous creations, and is requiring me to re-write all of that work. 
Sounds about my luck; where should I start then?

**Comment by MarkusG** [comment]
Like I said, check out the guides on the docs to familiarize yourself with 1.0's structure, then plan out how you're going to port your code over. Your best option is to create an entirely new project and rewrite your old code for 1.0.
