### ISSUE TITLE
System.InvalidOperationException

### ISSUE THREAD

**Issue by DevBoostStudios** [RogueException/Discord.Net#914]
System.InvalidOperationException: 'No type reader found for type Uri, one must be specified'

Here is my code:

        static void Main(string[] args) => new Program().RunBotAsync().GetAwaiter().GetResult();

        private DiscordSocketClient _client;
        private CommandService _commands;
        private IServiceProvider _services;
        public async Task RunBotAsync()
        {
            _client = new DiscordSocketClient();
            _commands = new CommandService();

            var builder = new ConfigurationBuilder()
                .SetBasePath(Directory.GetCurrentDirectory()) // <== compile failing here
                .AddJsonFile("appsettings.json");

            _services = new ServiceCollection()
                .AddSingleton(_client)
                .AddSingleton(_commands)
                .BuildServiceProvider();
            string botToken = "TOKEN";

            //event subscriptions
            _client.Log += Log;
            _client.UserJoined += AnnounceJoinedUser;

            await _client.SetGameAsync("SETGAME");

            await RegisterCommandsAsync();

            await _client.LoginAsync(TokenType.Bot, botToken);

            await _client.StartAsync();

            await Task.Delay(-1);

        }

**Comment by MarkusG** [comment]
The error is pretty descriptive. You must provide a TypeReader for a URI if you want to take one as a command parameter.

**Comment by DevBoostStudios** [comment]
How exactly do I implement it because im fairly new to discord bots and its typereaders? I have also read https://discord.foxbot.me/docs/guides/commands.html#type-readers which led me to no use and still quite dont understand it.

**Comment by MarkusG** [comment]
The documentation should be sufficient to learn how to create a TypeReader. It's a class that takes a string and returns a `Task<TypeReaderResult>` containing the entity you've just read or an error. Everything in the `Read()` method is up to you.

Also, this type of conversation is better suited for our channel in the [Discord API Guild](https://discord.gg/discord-api) (#dotnet_discord-net).

**Comment by Joe4evr** [comment]
@DevBoostStudios Please close this issue if you don't need it anymore.
