### ISSUE TITLE
Game Status

### ISSUE THREAD

**Issue by FenikkusuKoneko** [RogueException/Discord.Net#916]
Hi!
I'm using Discord.Net 2.0.0-beta-00858 and the code SetGameAsync isn't working (works on beta 00854 but there animated emotes are not supported). Am I doing something wrong? Or I need to use IActivity instead?
Also, can be added "Watching" and "Listening to" game statuses please?
Listening to - game type 2
Watching - game type 3

**Comment by Anu6is** [comment]
Yes, you'd have to use Activity instead, based on the changes made.

**Comment by FenikkusuKoneko** [comment]
And, can I get an example? On how to set?

**Comment by Anu6is** [comment]
I haven't updated... I just know that that in particular was changed. Didn't take a look at it myself

**Comment by strajk-** [comment]
Would be interested to know how to use it too.
