### ISSUE TITLE
Module Cap?

### ISSUE THREAD

**Issue by UltraSkull1000** [RogueException/Discord.Net#919]
I was just going along making my bot and i added a new module, it no longer recognizes any commands until i comment out the new module... This halts my development so i would like a response soon thx

**Comment by Anu6is** [comment]
Chances are there is an error being thrown in you newly added module. Look into your stack trace and try to determine what that is.
I'd also suggest joining the [Discord api server](https://discord.gg/discord-api) and check out the channel for this lib to get any further assistance (#dotnet_discord-net channel)

**Comment by UltraSkull1000** [comment]
Oops im an idiot my bad xD
