### ISSUE TITLE
403 Forbidden Error when assigning roles to a user

### ISSUE THREAD

**Issue by MrEnvii** [RogueException/Discord.Net#921]
I am creating a method of which the user is able to sign up and have their account created of which will give them a permission depending on the parameters.

My code is running correctly, but when it gets to the role assignment it throws the error.
The following is my code:
![image](https://user-images.githubusercontent.com/19834082/34533271-6a2e6af8-f0b1-11e7-8370-b0f5f1dbf8dd.png)

The following is my error:
![image](https://user-images.githubusercontent.com/19834082/34533281-79cd24f4-f0b1-11e7-8497-76794ff1d968.png)

I don't know if there is a more efficient way of assigning roles which might be causing the issue or it is something else? 

Looking forward to a response

Thanks,
Brendon

**Comment by khionu** [comment]
Please make sure the following conditions are true
- Your bot's highest role is above the role(s) it is trying to assign
- Your bot has the Manage Roles permission

**Comment by AntiTcb** [comment]
You're likely running into issues with the role hierarchy.

> Imagine the following roles in order:
>Role A
>Role B
>Role C
>Role D
>Everyone
>
>If the bot's role is Role D on the list
And the role you're triyng to add is Role C, then you can't add it
Administrator doesn't bypass role hierarchy, but the Guild Owner can bypass everything

Questions of this nature are best asked in [the Discord API guild](https://discord.gg/discord-api) rather than in GitHub issues.

**Comment by MrEnvii** [comment]
Thank you very much, with both of your answers it helped! 

I had it a role with Administration but I didn't have Manage Role Permission activated and it wasn't at the top. I'll keep this in mind for the future, and thanks for the instant response
