### ISSUE TITLE
GetMessagesAsync.FlattenAsync is returning an empty collection

### ISSUE THREAD

**Issue by SubZero0** [RogueException/Discord.Net#932]
The latest build at myget is returning an empty collection when trying to get messages and "flattening" the result.

![issue](https://user-images.githubusercontent.com/3085008/34886788-5f0365b0-f7ab-11e7-8651-70ad4194cfa4.png)

On older versions (tested with 2.0.0-828 and 1.0.2), `Flatten()` is still working.

**Comment by ObsidianMinor** [comment]
That's probably my fault. I should've rewritten it before it was pulled anyway.
