### ISSUE TITLE
Issues with SocketGuild.DefaultChannel

### ISSUE THREAD

**Issue by Nishimba** [RogueException/Discord.Net#940]
Hey, I'm trying to convert a bot of mine from 0.9 to 1.0 but I'm having a slight problem. I am trying to debug a command that writes a message to all the servers it belongs to when someone tells it to shut down.
`[Command("stop")]
        public async Task stopCommand()
        {
            foreach(SocketGuild guild in Context.Client.Guilds)
            {
                Console.WriteLine(guild.DefaultChannel.Name);
            }
            Console.WriteLine($"{Context.User.Username} from {Context.Guild.Name} sent: ~stop");
        }`
My bot only belongs to two servers. This code correctly returns the name of one server's default channel, but returns the error "Object reference not set to an instance of an object" rather than returning the name of the second server's default channel.

Is my code wrong, is it possible for a server to not have a default channel, or is there a problem with SocketGuild.DefaultChannel?

Any help would be appreciated!

(Sorry for bad code block formatting I don't know how to format it well on GitHub)

**Comment by Anu6is** [comment]
DefaultChannels as they were are not longer a thing (Discord change). The 2.0 beta for DNet has an alternate implementation, 1.0+ does not (at least not a properly working one). You can either use LINQ to find the most accessible channel for your bot or update to the beta (it's stable)

**Comment by Nishimba** [comment]
@Anu6is Thanks! I'm a bit hesitant about moving from 1.0 to 2.0 as the API changes between 0.9 and 1.0 were a bit of a shock to me, are there many differences between 1.0 and 2.0 or is it an easy transition?

**Comment by Anu6is** [comment]
There are some changes but honestly they aren't that major. If you haven't done much with the transition to 1.0 you can easily just go 2.0 instead. If you join the DNet lib channel in the [Discord API ](https://discord.gg/discord-api) server, the changes are in the pinned messages of the channel.

[Default Channel changes](https://github.com/discordapp/discord-api-docs/blob/7b0344c22f70fec78679cecc08522789f809b6da/docs/Change_Log.md)

**Comment by Nishimba** [comment]
Thankyou very much! :)
