### ISSUE TITLE
Category Channels collection returns incorrect results

### ISSUE THREAD

**Issue by Still34** [RogueException/Discord.Net#948]
When getting a category channel, the `Channels` collection seems to return an entire list of channels outside of the category. 

For example, if I have a `Category A` with `Channel 1` inside, and a `Channel 0` outside of the category, upon getting the category, the channels collection would return `Category A` and `Channel 0` instead of the expected `Channel 1`.

![](https://i.imgur.com/Ncm9BlG.png)
![](https://i.imgur.com/pMffNp7.png)

Build: 2.0-881

**Comment by Emzi0767** [comment]
#945 addresses this

**Comment by Still34** [comment]
Resolved by #945.
