### ISSUE TITLE
ModifyAsync Message only works once?

### ISSUE THREAD

**Issue by discoli-zz** [RogueException/Discord.Net#950]
```
        [Command("Ping", RunMode = RunMode.Async)]
        public async Task Ping()
        {
            await Context.Message.ModifyAsync(msg => msg.Content = "Pinging...");
        }
```

This is my current code for my command, and now the weird thing is that I debugged it by adding a Console.WriteLine with the message ID above the ModifyAsync and it logged to the console every single time I ran the command, but it only edited on the first time I typed the command.

I am using this as a self bot and am using Mono for Linux.

Edit: Upon further testing, this is the cycle
1st attempt to execute command: Command does not execute, as in the Ping() method isn't called
2nd attempt to execute command: Command is executed and works flawlessly
3rd attempt and further to execute command: Command does not work at all, but method is called

**Comment by AntiTcb** [comment]
A) [Selfbots are against ToS](https://support.discordapp.com/hc/en-us/articles/115002192352-Automated-user-accounts-self-bots-?flash_digest=f62cf1b9e44beddc586c609b3740782ded86fa75), and [support for logging in as a user will be removed from the library in a future release.](https://github.com/RogueException/Discord.Net/issues/827)
B) This library is not completely compatible with Mono. Use .NET Core instead if your intent is to run on Linux.

**Comment by discoli-zz** [comment]
@AntiTcb that fixed it, thank you, and also thank you for the heads up :+1:
