### ISSUE TITLE
MissingMethodException in WebSocket4Net

### ISSUE THREAD

**Issue by Gronnesby** [RogueException/Discord.Net#954]
Stumbled upon the WebSocket4Net issue on Win7, and from what I've been able to google, the solution should be to set the `WebSocketProvider` for the `DiscordSocketClient` like so:

```csharp
private DiscordSocketClient client = new DiscordSocketClient(new DiscordSocketConfig {
	WebSocketProvider = Discord.Net.Providers.WS4Net.WS4NetProvider.Instance
});
```

But this seems to throw an error with a missing static constructor(?) for the `WebSocket4Net` library:
```
15:12:17 Gateway     Connecting
15:12:17 Gateway     System.MissingMethodException: Method not found: 'Void WebSocket4Net.WebSocket..ctor(System.String, System.String, System.Collections.Generic.List`1<System.Collections.Generic.KeyValuePair`2<System.String,System.String>>, System.Collections.Generic.List`1<System.Collections.Generic.KeyValuePair`2<System.String,System.String>>, System.String, System.String, WebSocket4Net.WebSocketVersion, System.Net.EndPoint)'.
   at Discord.Net.Providers.WS4Net.WS4NetClient.<ConnectInternalAsync>d__21.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at Discord.Net.Providers.WS4Net.WS4NetClient.ConnectInternalAsync(String host)
   at Discord.Net.Providers.WS4Net.WS4NetClient.<ConnectAsync>d__20.MoveNext()
```

Any thoughts on this? Sorry if I am missing something very obvious here, I have not used C# in quite a while.

PS: I am targeting the .Net Framework 4.6 running on Windows 7 in this project.

**Comment by Mahsaap** [comment]
What version of discord.net are you on?

**Comment by Emzi0767** [comment]
You updated WS4Net despite being told not to. In other words, you broke it yourself.

**Comment by Gronnesby** [comment]
@Mahsaap 1.0.2, the latest stable one available through NuGet.

@Emzi0767 I have no doubt I have overlooked something with regards to versions, but could you point me to where it is documented? I see multiple versions of `WebSocket4Net` available, but which one is compatible with `Discord.Net.Providers.WS4Net`?

**Comment by Emzi0767** [comment]
The one that it comes with.

**Comment by Gronnesby** [comment]
That is version 0.14.1, seems to work with that one, thanks!
