### ISSUE TITLE
Return default avatar for user

### ISSUE THREAD

**Issue by Still34** [RogueException/Discord.Net#971]
At the moment, Discord.NET does not care about user's default avatar at all. If no avatar ID is set, the `IUser#GetAvatarUrl` method returns `null`. It is possible to retrieve the user's default URL based on their discriminator with `discrimValue % 5`.

There should be an option for people to retrieve this value, and I propose these solutions.

a. Implement a `DefaultAvatarUrl` property in `IUser`.
b. Add a bool `defaultOnNone` or something under the `GetAvatarUrl` method.
c. Enforce the return of a default URL when the avatar ID is `null`.

I personally prefer a) as it allows people who has implemented a null fallback for their `GetAvatarUrl` to not be affected, and for whatever reason, allows people to retrieve the default URL for those who already has an avatar.

**Comment by aStonePenguin** [comment]
Adding `GetCustomAvatarUrl()` & `GetDefaultAvatarUrl()` then changing it to `GetAvatarUrl() => GetCustomAvatarUrl() ?? GetDefaultAvatarUrl()` would be the way to go imo

**Comment by Still34** [comment]
Resolved in 109f663a9adc450823f9cd91da03812256553f51.

**Comment by Luminoscity** [comment]
Does anyone know how discord will determine which default avatar to use when the discriminator goes away soon?
