### ISSUE TITLE
Issue when sending a file with a text in a channel. The text is not sent.

### ISSUE THREAD

**Issue by FenikkusuKoneko** [RogueException/Discord.Net#987]
Hi! I'm using beta2 version. I just figured out that from v.00900 to v.00908 sending a text before sending a file is not working.

**Comment by SubZero0** [comment]
Just confirming that this issue is reproducible.
Example:
`Context.Channel.SendFileAsync("test/test.png", "some text");`
< 900: Sends the image and the text.
\>= 900: Sends only the image.

Related to #978
