### ISSUE TITLE
Changing Another Bot's Nickname

### ISSUE THREAD

**Issue by jheitz223** [RogueException/Discord.Net#990]
So I'm trying to have my bot change my other bot's nickname every time someone sends a message. Inside of `MessageReceived()` I have this line here: 
```cs
var user = message.Channel.GetUserAsync(/*my other bot's ID*/);
```
Then I look inside of `user` and I don't see any properties/methods with which I can get/set the nickname of `user`. I know I've seen other people online doing something with `ModifyAsync()` but I don't see that method inside of `user`. Am I missing something?

**Comment by MarkusG** [comment]
FWIW: This has been handled in the guild.

**Comment by Joe4evr** [comment]
Please close if this is resolved.
